### ISSUE TITLE
wxImageList::Add(wxBitmap..)

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#10013]
*Issue migrated from trac ticket # 10013*

**component:** GUI-generic | **priority:** normal | **resolution:** fixed

#### 2008-10-01 09:45:41: giovesas (Gianni) created the issue

___
I'm developing an application running in Win and Linux using wxWidgets 2.8.
I found a difference in the wxImageList class.
i'm using wxTreeCtrl to show configuration informations. I load different multiple bitmaps in a image list.
When I compile in windows, the function wxImageList::Add return the correct offset of the new zero-based image index in the list. In linux, with GTK, Add() returns the offset of the last single bitmap loaded.
I solved it calling GetImageCount() before loading a new vector of bitmap, but I'd like to inform the forum about this little difference.
ex:
m_images contains 2 bitmaps.
Now loading a myBmp thta is a vector of 10 bitmaps

int addr=m_images->Add(myBmp,wxTransp);
m_imageAddr[i]=addr;

On window addr=2
On linux with GTK addr=11

The adopted solution:
addr=m_images->GetImageCount();
m_images->Add(myBmp,wxTransp);
m_imageAddr[i]=addr;

**Comment by paulcor** [comment]
This was broken again by c374eefd34

**Comment by paulcor** [comment]
Fixed again in f1731fd672

**Comment by vadz** [comment]
Oops, sorry for rebreaking this and thanks for fixing it!
