### ISSUE TITLE
wxGrid: Column resizing gets confused when changing order

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#10392]
*Issue migrated from trac ticket # 10392*

**component:** wxGrid | **priority:** normal

#### 2009-01-17 23:32:09: ZenJu (ZenJu) created the issue

___
Hello,

I am using wxGrid to display data via GUI. Since I want to enable the user to arrange the columns in a flexible way, I save and load the column positions via

-wxGrid::GetColPos()* and *wxGrid::SetColPos()*

Alas this seems to confuse the column resizing, leaving it practically in an unusable state.

To demonstrate the issue I've created a small video. It says more than 1000 words :)

Best regards, ZenJu

**Comment by DietmarSchwertberger** [comment]
I don't think that this issue still persists. I could not see anything in the demo.

**Comment by vadz** [comment]
Nice to know that it's fixed now, thanks for testing!
