### ISSUE TITLE
Double-clicking to select file in wxFileDialog results in EVT_MOTION event for the window beneath it

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#10924]
*Issue migrated from trac ticket # 10924*

**component:** wxMSW | **priority:** low | **keywords:** wxFileDialog

#### 2009-06-23 17:59:26: Kerry (Kerry Loux) created the issue

___
The wxGLCanvas' EVT_MOTION event is triggered when it shouldn't be.  As an example:  A file dialog appears from which the user selects a file to load.  The file is loaded and displayed on the GL canvas, but it does not appear as expected.  This is because the EVT_MOTION event handler in the wxGLCanvas was overloaded to allow the user to rotate the object in the scene, and one of the openGL matricies was erroneously transformed prior to the scene being rendered.

This bug occurs when:
1.  A wxFileDialog is placed above a wxGLCanvas.
2.  The user selects a file by double-clicking on it.
3.  At this point, the EVT_MOTION event for the wxGLCanvas object is called.

This bug DOES NOT occur when:
1.  The double-clicking does not occur directly over top of hte wxGLCanvas (if the file name extends beyond the edge of the canvas, and it is selected by double-clicking on the portion of the file name that is not over the canvas).
2.  The user presses Enter or clicks the Open button to select the file.

This bug was observed with wxMSW 2.8.10.  I've attached an example that demonstrates this problem.

**Comment by charvey2718** [comment]
This is maybe a similar workaround to that suggested by @RobinD42, but slightly different I think.
When a FileDialog is created, I set a global flag to suppress mouse clicks. Other controls that handle mouse clicks check the flag and only execute the event handling code if the flag is not set, and then unset the flag.
This means that controls that handle mouse clicks won't react to unconsumed events from the FileDialog.

It's not a general solution, onyl a workaround. And it's fairly simple, seems to work with only a few extra lines of code.

In case this can help anyone else, I have updated my minimum example in #23938 (closed as it duplicates this one) as follows:
````
#include <wx/wx.h>
#include <wx/filedlg.h>

class MyFrame:public wxFrame {
public:
    MyFrame(wxWindow* parent);
private:
    bool suppress_mouse_clicks = false;
};

class MyApp:public wxApp {
public:
    bool OnInit() {
        wxFrame* frame=new MyFrame(NULL);
        frame->Show();
        return true;                    
    }
};

DECLARE_APP(MyApp);
IMPLEMENT_APP(MyApp);

MyFrame::MyFrame(wxWindow* parent):wxFrame(parent,wxID_ANY,_("FileDialogMWE")) {
    SetClientSize(wxSize(200,200));
    wxBoxSizer* mainSizer=new wxBoxSizer(wxVERTICAL);
    wxButton* button=new wxButton(this,wxID_ANY,_("button"));
    button->Bind(wxEVT_LEFT_DOWN, [=](wxMouseEvent& event) { suppress_mouse_clicks = false; });
    button->Bind(wxEVT_LEFT_UP, [=](wxMouseEvent& event) {
        if(!suppress_mouse_clicks)
        {
            wxMessageBox("I got clicked");
            suppress_mouse_clicks = false;
        }
        event.Skip();
    });
    mainSizer->Add(button,1,wxEXPAND);
    
    wxButton* openButton=new wxButton(this,wxID_ANY,_("open dialog"),wxDefaultPosition,wxDefaultSize,wxALIGN_LEFT);
    openButton->Bind(wxEVT_BUTTON, [=](wxCommandEvent& event) {
        suppress_mouse_clicks = true;
        wxFileDialog *OpenDialog = new wxFileDialog(
            this, _("Open sequence"), wxEmptyString, wxEmptyString,
            _("all files (*.*)|*.*"),
            wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        OpenDialog->ShowModal();
    });
    mainSizer->Add(openButton,1,wxEXPAND);
    
    SetSizer(mainSizer);
}
````

**Comment by vadz** [comment]
Note: you should really call `event.Skip()` in `wxEVT_LEFT_DOWN` handler, otherwise it risks breaking other things.

I've just thought about something else: perhaps we could try draining the input queue when `wxFileDialog` is destroyed, i.e. removing all mouse messages from it? AFAICS this shouldn't result in anything bad happening and this would also take care of the bogus mouse move messages that can't be suppressed using such workaround.

**Comment by charvey2718** [comment]
> Note: you should really call event.Skip() in wxEVT_LEFT_DOWN handler, otherwise it risks breaking other things.

Yes, oops. That's erroneous copy/paste residual from my custom control for which I specifically don't want the event passed on. I understand it should be there in general.

Although I have a workaround that works for me, I experimented with your idea all the same in `wx/msw/filedlg.cpp`. The only way I could think to try was with `DeletePendingEvents()`. I tried this on the event handler of the wxFileDialog itself, its parent, and its parent's child windows. This was just after the FileDialog was destroyed.

Since it didn't help, I suspect I'm not "draining the input queue" in the way you meant, but I know of no other way to delete events.

I did spend a while reading the IFileDialog interface and related documentation, but in the end, I don't think that helps. I think the mouse up event needs clearing from the relevant wxwidgets eventhandler, and not much can be done about the FileDialog not consuming the it.

**Comment by vadz** [comment]
> Although I have a workaround that works for me, I experimented with your idea all the same in `wx/msw/filedlg.cpp`. The only way I could think to try was with `DeletePendingEvents()`.

No, this is for wx events only. We'd need to use `::PeekMessage(WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE)` to remove the Windows mouse messages from the thread input queue. I don't guarantee that it's going to work, but it looks like it ought to.

**Comment by charvey2718** [comment]
It's a bit hard to understand what is going on.

I found that adding line 3 in the below
````
// Finally do show the dialog.
const int rc = fileDialog.Show(hWndParent, options, &m_fileNames, &m_path);
for(int i=0;i<4;++i) PeekMessageW(NULL, NULL, WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE); // fixes issue #10924
if ( rc == wxID_OK )
{
````
in `filedlg.cpp` on line 1672 seems to solve it.

That addresses the new style IFileDialog. It appears that the traditional one is fixed by adding the same on line 1468, as follows:
````
//== Execute FileDialog >>=================================================

DWORD errCode;
bool success = DoShowCommFileDialog(&of, m_windowStyle, &errCode);
for(int i=0;i<4;++i) PeekMessageW(NULL, NULL, WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE); // fixes issue #10924
````

But there are some things I'm not sure about:

1. Why does it need to be done 4 times? Are there 4 events to be cleared, or could there perhaps be a timing sensitivity, i.e. a dependency on the time elapsed between the dialog closing and the mouse event being processed?

1. In my example (above), I noticed that the button underneath still gains the focus for a moment although it doesn't trigger a LEFT_UP event anymore. I haven't checked EVT_MOTION.

**Comment by vadz** [comment]
Nice, thanks for testing this and please don't hesitate making a PR with your changes.

> But why does it need to be done 4 times?

I have no idea and I wouldn't count on it, I'd just write a `while()` loop to call `PeekMessage()` (no need write the `W` explicitly) as many times as necessary and I'd pass `PM_QS_INPUT` to it to prevent it from consuming any messages posted to the queue (which shouldn't normally happen but who knows if it really never does or if there is some program relying on this to work).

**Comment by charvey2718** [comment]
Thanks. Using a `while()` loop checking the return value was my first thought too, but that just put it into an infinite loop. I didn't pass `PM_QS_INPUT` however - I don't know if it will make any difference (it doesn't sound like it).

I'll play with it some more later and then attempt a PR. (We'll see if my rough idea of how github works, never tested in practice, can translate into reality.)

**Comment by vadz** [comment]
> Thanks. Using a `while()` loop checking the return value was my first thought too, but that just put it into an infinite loop.

This is really weird, I don't see what would be generating an endless stream of mouse messages. Are you sure you had tested it with `PM_REMOVE`? Without it, the loop would be infinite, but with it it shouldn't. And if it is, could you open Spy++ and look at the messages being sent (or, alternatively, add a `wxLogDebug("Got %0x", msg.message);` where `MSG msg` would be passed to `PeekMessage()` as first parameter)?

> I didn't pass `PM_QS_INPUT` however - I don't know if it will make any difference (it doesn't sound like it).

No, this one shouldn't.

> I'll play with it some more later and then attempt a PR. (We'll see if my rough idea of how github works, never tested in practice, can translate into reality.)

Don't hesitate to ask if you run into any problems, but normally it's just

1. Create your own fork of the repository (you have a button to do it in the web UI or you can just git-clone it locally if you prefer).
2. Create a branch for your changes (`msw-filedlg-mouse-events` or whatever).
3. Commit to it.
4. Push the branch to your fork (just `git push origin HEAD` normally).
5. Follow the link GitHub gives you to create the PR or just do it from the web UI.

Good luck!

**Comment by charvey2718** [comment]
I revisited the `while()` loop as a solution. Inspecting the MSG and the return value helped to get to the bottom of it.

This now works:
````
MSG msg;
while(PeekMessage(&msg, NULL, WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE|PM_QS_INPUT)) { }
````

This doesn't work, and I don't know why:
````
while(PeekMessage(NULL, NULL, WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE|PM_QS_INPUT)) { }
````
Why does providing a NULL msg affect the return value?

The infinite loop I got before was from a misreading of the [docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagew) which caused me to write:
````
while(!PeekMessage(NULL, NULL, WM_MOUSEFIRST, WM_MOUSELAST, PM_REMOVE|PM_QS_INPUT)) { }
````

**Comment by vadz** [comment]
> Why does providing a NULL msg affect the return value?

I guess because by not providing a valid pointer you can't really remove the message from the queue?

Anyhow, the important thing is that it finally works, thanks a lot for fixing this looooong-standing bug!

**Comment by charvey2718** [comment]
Thanks for telling me what to do!
It's satisfying to have contributed something, even so small!
