### ISSUE TITLE
Task Dialogs/More flexible wxMessageDialog

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#11416]
*Issue migrated from trac ticket # 11416*

**component:** GUI-all | **priority:** normal

#### 2009-11-04 20:31:46: nielsm (Niels Martin Hansen) created the issue

___
I propose adding support for more complex generated dialogue boxes, specifically emulating or wrapping the [Task Dialogs](http://msdn.microsoft.com/en-us/library/bb760441%28VS.85%29.aspx) available in Windows Vista and later.

The main idea would be to use a native implementation when available, and an emulation when there is no native implementation. This would mean e.g. different code paths Windows versions before and after 6.0.

**Comment by vadz** [comment]
I've just stumbled upon this old issue while searching for something else and I think this is fixed since ede7b01760 (Provide a task-dialog based wxMSW wxMessageDialog implementation., 2010-08-18), so closing.
