### ISSUE TITLE
Controls based on windowless gtk widgets such as `wxStaticText` do not get wx Enter and Leave events

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#11848]
*Issue migrated from trac ticket # 11848*

**component:** wxGTK | **priority:** normal

#### 2010-03-22 23:44:56: oweno (Owen O'Neill) created the issue

___
Preamble:
for performance reasons gtk manages some widgets itself rather than creating a seperate window at the xserver level.
(e.g. label, static bitmap)

These controls don't get events themselves - instead the wx/gtk interface layer routes the event to the correct wxWindow.

At the wx level the label control derives from wxWindow, but the implementation under the hood uses a different class hierarchy, 
so a wxWindow has a gtkPizza object, whereas a wxStaticText control uses a gtkLabel.

As an example imagine we have a wxwindow containing a wxStaticText control.
The mouse now tracks from the parent window, across the child label control, and back onto the parent window.
At the Xserver level this is all one window - hence it does not generate a enter or leave event. Neither does the GTK layer.
At the wx level the events are routed to the right wx window, so the parent gets a series of "move" events - then the child gets a series of "move" events, then the parent gets "move" events again.
No enter or leave events happen - which they should do since at the wx level everything derives from window.

When GTK is on something other than Xserver this mapping of GTK widgets to the windowing systems windows may be different so the same problem may not occur.

One bit I don't understand is that I thought that gtkButton was a window-less gtk widget - but it DOES get leave & enter events. Maybe there is another factor at work.

anyway I started putting together a workround for my project which I've not even built, let alone tested.
I ended up doing something else for my project since we didn't fancy patching and building widgets for our project.

the fix basically tracks the last window that got a move event - and sents it a leave event if we track from a parent to a window-less child

fixes in.
src/gtk/window.cpp

additional static global variable

```cpp
// window-less GTK widgets do not generate leave and enter events. we synthesize them.
static wxWindowGTK *g_lastMotionWindow = NULL;
```

gtk_window_motion_notify_callback....

```cpp
    else // no capture
    {
      bool bIsValidChild;
        win = FindWindowForMouseEvent(win, event.m_x, event.m_y, g_lastMotionWindow, bIsValidChild );

        //have we moved across our non-window children ? (or from ourself to a non-window child)
      if ( bIsValidChild
        && g_lastMotionWindow
        && g_lastMotionWindow != win
        && GTK_WIDGET_NO_WINDOW( win->GetHandle() )
      {
        // don't really need the last bit of the test (GTK_WIDGET_NO_WINDOW) since
        // if it had a window then GTK would have sent the event direct to it instead of us having to forward it.

        //make up a mouse event for the window we are leaving
        wxMouseEvent eventL( wxEVT_LEAVE_WINDOW );
            InitMouseEvent(g_lastMotionWindow, eventL, gdk_event);
            eventL.SetEventObject(g_lastMotionWindow);
            g_lastMotionWindow->GTKProcessEvent(eventL);

        //make up a mouse event for the window we are entering
        wxMouseEvent eventE( wxEVT_ENTER_WINDOW );
            InitMouseEvent(win, eventE, gdk_event);
            eventE.SetEventObject(win);
            win->GTKProcessEvent(eventE);
      }

      g_lastMotionWindow = win;

        // reset the event object and id in case win changed.
        event.SetEventObject( win );
        event.SetId( win->GetId() );
    }
```

```cpp
// find the window to send the mouse event too
static
wxWindowGTK *FindWindowForMouseEvent(wxWindowGTK *win, wxCoord& x, wxCoord& y, wxWindowGTK *winChild # NULL, bool& bIsValidChildfalse)
{_the winChild is provided to validate the child window pointer when we are synthesizing leave and enter events
_we could use FindWindowById but since we're already iterating through the list of children there seems little point in doing it again.

    bIsValidChild = false;
    bool bStopHitTest = false;
    wxCoord xx = x;
    wxCoord yy = y;

    if (win->m_wxwindow)
    {
        wxPizza* pizza = WX_PIZZA(win->m_wxwindow);
        xx += pizza->m_scroll_x;
        yy += pizza->m_scroll_y;
    }

    wxWindowList::compatibility_iterator node = win->GetChildren().GetFirst();
    while (node && !bIsValidChild )
    {
        wxWindowGTK *child = node->GetData();

      //test to see if the supplied window really is one of our children
      if (winChild
        && winChild == child )
        bIsValidChild = true;

        node = node->GetNext();

      if (!bStopHitTest)
      {
        if (!child->IsShown())
            continue;

        if (child->GTKIsTransparentForMouse())
        {
            // wxStaticBox is transparent in the box itself
            int xx1 = child->m_x;
            int yy1 = child->m_y;
            int xx2 = child->m_x + child->m_width;
            int yy2 = child->m_y + child->m_height;

            // left
            if (((xx >= xx1) && (xx <= xx1+10) && (yy >= yy1) && (yy <= yy2)) ||
            // right
                ((xx >= xx2-10) && (xx <= xx2) && (yy >= yy1) && (yy <= yy2)) ||
            // top
                ((xx >= xx1) && (xx <= xx2) && (yy >= yy1) && (yy <= yy1+10)) ||
            // bottom
                ((xx >= xx1) && (xx <= xx2) && (yy >= yy2-1) && (yy <= yy2)))
            {
                win = child;
                x -= child->m_x;
                y -= child->m_y;

            if (!winChild)
                    break;

            bStopHitTest = true;
            }

        }
        else
        {
            if ((child->m_wxwindow == NULL) &&
                (child->m_x <= xx) &&
                (child->m_y <= yy) &&
                (child->m_x+child->m_width  >= xx) &&
                (child->m_y+child->m_height >= yy))
            {
                win = child;
                x -= child->m_x;
                y -= child->m_y;

            if (!winChild)
                    break;

            bStopHitTest = true;
            }
        }
    }
    }

    return win;
}
```

**Comment by vadz** [comment]
I don't know why did I close this, as it still doesn't work.

Moreover, it doesn't even work when using Wayland, so it's not X-specific: GTK "gadgets", such as `GtkLabel` used by `wxStaticText`, don't get any mouse events, neither enter, nor leave nor motion ones. The simplest way to make this is to put `GtkLabel` in its own window or we could use `GtkEventBox`.
