### ISSUE TITLE
[wxMSW] wxMessageDialog::ShowModal() is not really app modal

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#11887]
*Issue migrated from trac ticket # 11887*

**component:** wxMSW | **priority:** normal | **keywords:** modality

#### 2010-04-01 11:10:56: jatupper (Jeff Tupper) created the issue

___
I was assuming that wxMessageDialog::ShowModal on wxMSW was app-modal, but that conflicts with what I've observed with one of my applications.

I'm attaching a patch to the dialogs sample. With the patched sample one can observe a sequence of events that is similar to that which occurs with my executable. After building and launching the new dialogs sample:

1. Move the two frames apart (just for visual clarity, and to confirm that there are two frames).
2. Select Dialogs / Message box from one of the frames.
3. Select Dialogs / Message dialog from the other frame.
4. Close the Message Box Test Dialog.

After step 4, both menu bars can be used so the message box isn't even frame modal at that point.

JICAII: between steps 3 and 4, the message box can be dismissed.

Is step 3 where it all begins to fall apart?

**Comment by vadz** [comment]
And just (exactly!) 12 years later, the message boxes and other native modal dialogs are app modal in wxMSW now. Let's see if anybody complains about this now...
