### ISSUE TITLE
wxNumValidator should do range check in OnKillFocus() instead of OnChar()

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#12968]
*Issue migrated from trac ticket # 12968*

**component:** GUI-all | **priority:** normal | **keywords:** validator numbers OnChar

#### 2011-02-22 21:07:47: mmarsan (Manolo) created the issue

___
Range checking should be avoided at OnChar() processing.
If range is (100-200) and user types "1" as a first keystroke, the value "1" is out of range, so the stroke is not acepted.

**Comment by vadz** [comment]
Finally done now. Sorry for the slightly more than 12 year delay.
