### ISSUE TITLE
segfault on OpenBSD amd64 in src/regex/regexec.c:172

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#13822]
*Issue migrated from trac ticket # 13822*

**component:** base | **priority:** normal

#### 2012-01-03 14:15:12: buzzdee created the issue

___
Hi,

compiled wxWidgets with internal regex library. Compiled OpenNX against it, it crashes here when starting it with 

opennx --admin

(gdb) bt 
#0  0x000000020a254423 in wx_re_exec (re=Cannot access memory at address 0x20ab64278
) at ./src/regex/regexec.c:172
#1  0x000000020a1e7d7c in wxRegExImpl::Matches (this=0x2075c7d80, str=0x20648ce18, flags=0, len=6)
    at ./src/common/regex.cpp:413
#2  0x000000020a1e7f0d in wxRegEx::Matches (this=0x209be46e0, str=0x20648ce18, flags=0, len=6)
    at ./src/common/regex.cpp:645
#3  0x0000000000451c47 in wxRegEx::Matches (this=0x209be46e0, text=@0x20ab6cec0, flags=0) at regex.h:103
#4  0x00000000004909dc in SessionList::ScanDir (this=0x2075c7600) at SessionList.cpp:208
#5  0x00000000004914b1 in SessionList::Entry (this=0x2075c7600) at SessionList.cpp:306
#6  0x0000000000426dea in wxThreadHelperThread::Entry (this=0x204fa05c0) at thread.h:665
#7  0x000000020a23b31c in wxThreadInternal::PthreadStart (thread=0x204fa05c0)
    at ./src/unix/threadpsx.cpp:766
#8  0x000000020a23b43b in wxPthreadStart (ptr=0x204fa05c0) at ./src/unix/threadpsx.cpp:718
#9  0x0000000207a5e67d in _thread_start () at /usr/src/lib/libpthread/uthread/uthread_create.c:242
#10 0x000000000000002b in ?? ()
Cannot access memory at address 0x20ab6d000

opennx uses the wxRE_ADVANCED regexp type all over the place.

switching the wxRE_ADVANCED to wxRE_ENHANCED doesn't crash opennx anymore.

This was observed on OpenBSD amd64, but works fine on i386.

cheers,
Sebastian

**Comment by vadz** [comment]
This is surely not relevant any longer as the old regex code is no more.
