### ISSUE TITLE
wxOverlay doesn't work with wxScrolledWindow

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#14415]
*Issue migrated from trac ticket # 14415*

**component:** wxMSW | **priority:** normal | **keywords:** wxOverlay scrolling work-needed

#### 2012-06-18 05:27:57: @wsu-cb created the issue

___
Run the drawing sample.  Rubber band select an area, and have the select rectangle grow downward until the window starts auto-scrolling.  The rubber band rectangle will not be cleaned up properly.

I believe the problem is that the (wxMSW) wxOverlay/wxDCOverlay implementation ignores scrolling entirely, but I think it needs to take that into account.  Unfortunately, there are two aspects to the scrolling problem.  If the window starts out scrolled, the wxOverlay initialization does not even construct the correct bitmap cache because the bitmap is constructed using device coordinates, but the wxDC Blit function expects logical coordinates.  I patched my local system to use logical coordinates, and that fixed my wxOverlay problem until I triggered scrolling after the bitmap was constructed, thus making the bitmap no longer valid.

Unfortunately, I don't see how to force wxDCOverlay::Clear() (to erase the old rubber band) and wxOverlay::Reset() (to re-cache the window) calls into the processing before wxWindow::ScrollWindow() is called.

**Comment by vadz** [comment]
I've retested the drawing sample and the problem is fixed there now (thanks Paul!), so I believe this one can be closed.
