### ISSUE TITLE
wxGrid/wxDVC column does not autosize properly when the grid uses native header

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#15105]
*Issue migrated from trac ticket # 15105*

**component:** wxGrid | **priority:** normal | **keywords:** wxGrid wxHeaderCtrl column sizing

#### 2013-03-15 05:09:25: @oneeyeman1 created the issue

___
Hi,
The bug originally was found using wxGrid in 2.9.4, confirmed existence with wxGrid TRUNK (rev. 73262) and then found on wxDVC in 2.9.4.

Complete explanation with the patch to reproduce the bug to the grid sample can be found [here](https://groups.google.com/forum/?fromgroups=#!topic/wx-users/SMWtf8t02Lw).

When wxGenericHeaderCtrl is used everything sizes properly.

I did not test the bug on the other platforms, but since wxGrid is generic and wxHeaderCtrl is Windows I presume it is wxMSW specific.

I may look at the code to find out what is going on when time permits.

**Comment by DietmarSchwertberger** [comment]
I can't see this. I tried the modfications (smaller data and `AutoSize`) and it looks right:
![grafik](https://user-images.githubusercontent.com/5512021/162624580-70e030c1-78c0-440e-b247-c468c652397a.png)

**Comment by DietmarSchwertberger** [comment]
What I do see, though, is that the column size will take into account only the header, not the data:
![grafik](https://user-images.githubusercontent.com/5512021/162624917-ce7ed35c-626c-4c41-a43b-017f29c47130.png)
This is after a double-click on the column header separator between Size and Date.
(AutoSize deativated again.)
Is this intended?

**Comment by DietmarSchwertberger** [comment]
OK, this seems to be intentional: 
```
void wxGrid::AutoSizeColLabelSize( int col )
{
    // Hide the edit control, so it
    // won't interfere with drag-shrinking.
    AcceptCellEditControlIfShown();

    // autosize column width depending on label text
    SetColSize(col, -1);

    ForceRefresh();
}
```

**Comment by vadz** [comment]
This is indeed intentional because auto-sizing for all grid rows would be a `O(N)` operation and we don't want to have those in `wxGrid`, which is supposed to accommodate "infinitely many" elements.

Thanks for retesting this!
