### ISSUE TITLE
build error: fails with -j4

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#15147]
*Issue migrated from trac ticket # 15147*

**component:** build | **priority:** low | **keywords:** build mingw parallel

#### 2013-04-12 09:41:56: jaskij created the issue

___
Building with mingw fail when using the -j4 flag.
Exact command used:
`mingw32-make -f makefile.gcc SHARED=1 UNICODE=1 BUILD=release`
Attached are separate stdout (tmp.err) and stderr (tmp2.err) of the mingw32-make command.
The first line of the stderr output means "System can't find the specified path." (or something like that)

**Comment by vadz** [comment]
This is the same as #14470 and it doesn't seem useful to keep it open.
