### ISSUE TITLE
Fix compilation with wxUSE_MEM_TRACING==1 (--enable-mem_tracing)

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#15373]
*Issue migrated from trac ticket # 15373*

**component:** base | **priority:** low | **keywords:** gcc g++ compilation

#### 2013-07-30 05:31:08: jbbbms created the issue

___
wxWidgets-2.9.5.tar.bz2 MD5: e98c5f92805493f150656403ffef3bb0
GCC version: 4.7.2
Platform: Debian Wheezy.

While running the command make, it will stop and display an error message complaining the op new and op delete in src/common/memory/ are incorrect. It's easy to fix the compilation failure. Please see the patch. Thanks.

**Comment by vadz** [comment]
Not relevant any longer after the changes of e89f05faba (Remove memory debugging/tracing support and all related options, 2023-01-05)
