### ISSUE TITLE
Registration to trac.wxwidgets.org rejects legitimate registration tentative

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#16315]
*Issue migrated from trac ticket # 16315*

**component:** web site | **priority:** normal

#### 2014-06-03 10:14:09: cheritat (Arnaud Cheritat) created the issue

___
I got a 76% probability of spam registration on a legitimate tentative.

**Comment by tierra** [comment]
This is no longer a concern with the move to GitHub Issues.
