### ISSUE TITLE
wxQt's wxBitmapToggleButton's hierarchy is different

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#16737]
*Issue migrated from trac ticket # 16737*

**component:** wxQt | **priority:** normal

#### 2014-12-17 18:30:06: jengelh (Jan Engelhardt) created the issue

___
Code such as
```
#include <wx/wx.h>
#include <wx/tglbtn.h>
int main(void) {
        wxBitmap blah;
        wxBitmapButton *b = new wxBitmapToggleButton(NULL,-1,blah);
        return (b != NULL) ? 0 : 1;
}
```
fails to compile in wxQt, because the hierarchy of wxBitmapToggleButton is different from what it is in wxMSW and wxGTK:
```
btn.cpp: In function ‘int main()’:
btn.cpp:5:59: error: cannot convert ‘wxBitmapToggleButton*’ to ‘wxBitmapButton*’ in initialization
  wxBitmapButton *b = new wxBitmapToggleButton(NULL,-1,blah);
```
In include/wx/qt/tglbtn.h we find:
```
class WXDLLIMPEXP_CORE wxBitmapToggleButton: public wxToggleButtonBase
```
which is the reason for the break. The wxWidgets HTML documentation specifies that the conversion ought to be possible.

This is with trunk svn78217.

**Comment by AliKet** [comment]
Should be closed as invalid (or outdated?) because `wxBitmapToggleButton` now derives from `wxToggleButtonBase` under all platforms.

**Comment by vadz** [comment]
Thanks for fixing this! And closing.
