### ISSUE TITLE
wxWizard styles are ingnored when loading xrc

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17057]
*Issue migrated from trac ticket # 17057*

**component:** XRC | **priority:** normal | **keywords:** wxWizard styles resizing medium

#### 2015-07-06 17:03:22: diamant created the issue

___
wxWizardXmlHandler::DoCreateResource() does not take into account 'style' xrc node (but it does 'exstyle').
So wizards are created with wxDEFAULT_DIALOG_STYLE.
I suggest to pass to Create() result of call:
GetStyle(wxT("style"), wxDEFAULT_DIALOG_STYLE)
like it's done for wxDialog xml handler.

But it's not enough. To make it working, wxWizardXmlHandler::wxWizardXmlHandler() should add dialog styles.
I suggest
1) to add
void wxXmlResourceHandler::AddDialogStyles();
2) move code from wxDialogXmlHandler() to AddDialogStyles(), including AddWindowStyles() call; 
3) in wxDialogXmlHandler() just call AddDialogStyles();
4) replace AddWindowStyles() with AddDialogStyles() call in wxWizardXmlHandler().

P.S. Background of the issue:
I noticed that wizards were not resizable although wxRESIZE_BORDER was set in xrc. There are also wxWidgets forum posts messages about this issue.
Then I tried to call SetWindowStyle(GetWindowStyle() | wxRESIZE_BORDER) in wxWizard-derived class ctor, but it didn't help - the border appeared, the cursor changed on the border, but it didn't allow resizing itself. So probably it's one more issue.

**Comment by vadz** [comment]
This was finally done in 259c0fd335 (Support "style" XRC element for wxWizard, 2022-03-19), see #22207.
