### ISSUE TITLE
wxTextCtrl is too small on hiDPI system when using wxDefaultSize

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17081]
*Issue migrated from trac ticket # 17081*

**component:** wxMSW | **priority:** normal

#### 2015-07-28 01:15:27: @dconnet created the issue

___
When a text control is created on a hiDPI system without expanding it within a sizer, the control is created with the same number of pixels (width) as it is when created on a non-hiDPI system. The height is correct.

Note also the padding in the buttons looks disproportionally large.

Modifying the dialogs sample (dialogs.cpp):
```
3009c3009
<     sizerMsgs->Add(m_textTitle, wxSizerFlags().Expand().Border(wxBOTTOM));
---
>     sizerMsgs->Add(m_textTitle, wxSizerFlags().Border(wxBOTTOM));
```

and then viewing the 'Message Dialog' shows the clipped edit. (on my system, I can only see "ge Box")

I was testing on a Win8.1 machine with a 3840x2160 display.

Attached are an image of this dialog on a normal and hidpi machine.

**Comment by vadz** [comment]
It looks like this was fixed back in 633d04ca92 (Changed several places using hard-coded size values to use FromDIP instead., 2015-11-24)
