### ISSUE TITLE
[wxOSX] support hi-res images in wxAuiToolBar + wxXmlResource

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17247]
*Issue migrated from trac ticket # 17247*

**component:** wxOSX | **priority:** normal | **keywords:** wxBitmap wxAuiToolBar work-needed HiDPI

#### 2015-11-06 08:26:40: @eranif created the issue

___
Hi,

Attached is a patch that allows loading hi-res images using wxXmlResource (the same logic that is applied in wxBitmap): If a @2x file exists, load it instead of the "normal" resource

For wxAuiToolBar, I changed the drawing default art provider so now it takes into consideration the bitmap scale factor. In addition, wxBitmap::ConvertToDisabled (used for providing default disabled image) loses the scale factor
so I had to change this code as well.

The result is that I can now load and use hi-res images using wxAuiToolBar and also use wxXmlResource class to load hi-res images

Thanks

**Comment by vadz** [comment]
I think this is out of date now as we have support for `wxBitmapBundle` in `wxAuiToolBarXmlHandler` now (and also for notebook pages in `wxAuiXmlHandler`).
