### ISSUE TITLE
Drawing a bitmap onto Gtk3 DC causes blocky result on HiDPI screens

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17371]
*Issue migrated from trac ticket # 17371*

**component:** wxGTK | **priority:** normal | **keywords:** HiDPI Gtk3

#### 2016-02-12 19:13:58: m13253 (StarBrilliant) created the issue

___
This is an example program to demonstrate this issue:
https://github.com/m13253/wx-image-viewer/blob/63ee2da/imageview.cpp#L68
I will send the screenshot as an attachment. Running with 2x DPI, You can see the bitmap gets blocky, that is to say, `GetPixel(2*x, 2*y) == GetPixel(2*x+1, 2*y+1)`.

The first problem, `wxClientDC::GetSize` returns logical size instead of device size.

Ref [1]: [wxDC::GetSize](http://docs.wxwidgets.org/3.0/classwx_d_c.html#ab4c22c7c7490a4aabc13dfd9e7a285a3) gets the horizontal and vertical extent of this device context in **device** units. It can be used to scale graphics to fit the page.
Ref [2]: https://github.com/wxWidgets/wxWidgets/blob/baf6781/src/gtk/dcclient.cpp#L453
Ref [3]: https://github.com/wxWidgets/wxWidgets/blob/baf6781/src/gtk/dcclient.cpp#L2036
Ref [4]: https://github.com/wxWidgets/wxWidgets/blob/baf6781/src/gtk/dc.cpp#L211

The second problem, `LogicalScale` is not set automatically according to screen screen DPI.

According to [gdk_window_get_scale_factor doc](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-get-scale-factor), for HiDPI screen drawing is **automatically scaled up** to a higher resolution, so any code doing drawing will automatically look nicer. That means, [device-scale is automatically set by GDK](https://blogs.gnome.org/alexl/2013/06/28/hidpi-support-in-gnome/).
According to [wxMappingMode doc](http://docs.wxwidgets.org/3.0/interface_2wx_2dc_8h.html#a5a641b839b9ac2ff94514d0596f6e20a), a wxDC should have a `LogicalScale` of 1 by default.
Here comes the conflict: GDK assumes `device-scale` is larger but wxDC assumes `LogicalScale` is 1.
Either way is a compromise: break backward compatibility, or change the behavior of wxDC.

I hope we can come up with a solution, to fix up blocky bitmap painting on Gtk3.

**Comment by vadz** [comment]
I believe both drawing the bitmaps (provided a correct scale factor is used) and drawing using `wxGraphicsContext` directly works fine currently (~3.1.6), please reopen if there are still any problems here.
