### ISSUE TITLE
3.1.0 build fails on OSX 10.7.5 with g++ 4.2

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17471]
*Issue migrated from trac ticket # 17471*

**component:** wxOSX | **priority:** low

#### 2016-04-01 13:38:21: @raananb created the issue

___
With XCode 4.6.3 (latest for Lion) ans g++4.2, build fails.

Build output (lines folded by me; empty lines follow folded lines):

----------------------- Configuration: GCC Release -----------------------
In directory: /Users/mywx/wxWidgets-3.1.0/GCCBuildReleaseOSXCocoaUnicode
sh -c "if test ! -f /Users/mywx/wxWidgets-3.1.0/GCCBuildReleaseOSXCocoaUnicode/Makefile ;
then /Users/mywx/wxWidgets-3.1.0/configure --with-osx_cocoa --disable-debug --enable-unicode
--disable-universal --disable-monolithic --enable-gui --disable-shared --enable-exceptions --without-odbc
--without-opengl --enable-xrc --enable-html --with-regex=builtin --enable-richtext --disable-mediactrl
--enable-aui --enable-ribbon --enable-propgrid --enable-stc --with-macosx-version-min=10.7 CXX=g++ CC=gcc LD=g++ ; fi ; make"

/Users/mywx/wxWidgets-3.1.0/GCCBuildReleaseOSXCocoaUnicode/bk-deps g++ -mmacosx-version-min=10.7 -c -o
corelib_cocoa_window.o -I./.pch/wxprec_corelib -D__WXOSX_COCOA__
-DWXBUILDING -I/Users/mywx/wxWidgets-3.1.0/GCCBuildReleaseOSXCocoaUnicode/src/tiff/libtiff
-I/Users/mywx/wxWidgets-3.1.0/src/tiff/libtiff -I/Users/mywx/wxWidgets-3.1.0/src/jpeg
-I/Users/mywx/wxWidgets-3.1.0/src/png -DwxUSE_BASE=0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0
-I/Users/mywx/wxWidgets-3.1.0/GCCBuildReleaseOSXCocoaUnicode/lib/wx/include/osx_cocoa-unicode-static-3.1
-I/Users/mywx/wxWidgets-3.1.0/include -O2 -arch i386 /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm

-** /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm:2443: error: stray '@' in program
*** /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm:2450: error: stray '@' in program
*** /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm: In member function 'virtual void wxWidgetCocoaImpl::SetLabel(const wxString&, wxFontEncoding)':
*** /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm:2444: error: cannot convert '<anonymous enum>' to 'objc_object*' in argument passing
*** /Users/mywx/wxWidgets-3.1.0/src/osx/cocoa/window.mm:2451: error: cannot convert '<anonymous enum>' to 'objc_object*' in argument passing

-** make: *** [corelib_cocoa_window.o] Error 1

Done.

5 errors, 0 warnings

**Comment by vadz** [comment]
gcc can't be used for building wxOSX since a long time, so it's not really useful to keep this one open.
