### ISSUE TITLE
wxDataViewCtrl - freezing when scrolling a virtual list. Branch 3.1.0

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17550]
*Issue migrated from trac ticket # 17550*

**component:** GUI-all | **priority:** normal

#### 2016-05-26 23:14:02: seb_d (seb_d) created the issue

___
PROBLEM DESCRIPTION:
On Windows (Win7 64 bits) and wxWidgets 3.1.0 (64 bits & 32 bits), the scrolling seems to freeze when displaying many rows.
If a wxDataViewVirtualListModel is implemented with more than 10 000 000 rows, then scrolling stops at row 6 000 000 something: the display is not updated anymore

PROPOSED QUICK FIX:
The problems actually comes from the method wxDataViewMainWindow::OnPaint
If the following line 
```
wxAutoBufferedPaintDC dc( this );
```
 is changed to 
```
wxPaintDC dc(this);
```
 then the bug disappears (but flicker occurs, of course)
The quick fix is to declare a class like that:

```
class wxBufferedDC2 : public wxMemoryDC
{
    public:
        wxBufferedDC2(wxPaintDC &dc, wxBitmap &bmp)
            : wxMemoryDC(&dc), m_DC(dc), m_bmp(bmp)
        {
            SelectObject(m_bmp);
        }

        ~wxBufferedDC2(void)
        {
           _blit fails when y > 134 000 000 so we use DrawBitmap instead
_            int x0, y0;_            GetDeviceOrigin(&x0, &y0);
_            m_DC.Blit(0, 0, m_bmp.GetWidth(), m_bmp.GetHeight(), this, -x0, -y0);

            SelectObject(wxNullBitmap);
            m_DC.DrawBitmap(m_bmp, 0, 0);

            //m_bmp.SaveFile("bmp.bmp", wxBITMAP_TYPE_BMP);
        }

    protected:
        wxDC&       m_DC;
        wxBitmap&   m_bmp;
};
```

and to replace the line 
```
wxAutoBufferedPaintDC dc( this );
```
 with
    
```
    wxPaintDC paintDC(this);
    int w, h;
    GetClientSize(&w, &h);
    wxBitmap bmp(w, h); //could be cached somewhere, for performance
    wxBufferedDC2 dc(paintDC, bmp);
```

LONG TERM SOLUTION:
I did not have the time to investigate. It is perhaps some kind of overflow in the wxDC::Blit method on Windows

**Comment by vadz** [comment]
Just for the reference: the original patch is in the commit referenced above in a branch in my own fork, but wx master contains a more general fix of the problem.
