### ISSUE TITLE
Invalid write caused by wxHtmlDataObject::wxHtmlDataObject(wxString)?

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17637]
*Issue migrated from trac ticket # 17637*

**component:** wxGTK | **priority:** normal | **keywords:** clipboard repro-needed

#### 2016-08-22 06:50:10: @gunterkoenigsmann created the issue

___
Using the current git version of wxWidgets wxMaxima roughly since I added the possibility to put equations on the clipboard as "HTML" occasionally crashes on drag-and-drop. Valgrind tells me a possible reason:

    ==27004== Invalid write of size 1
    ==27004==    at 0x4C2FE37: strcpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==27004==    by 0x5B43B1C: wxHTMLDataObject::GetDataHere(void*) const (in /usr/lib/libwx_gtk2u_core-3.1.so.1.0.0)
    ==27004==    by 0x5A16660: selection_handler (in /usr/lib/libwx_gtk2u_core-3.1.so.1.0.0)
    ==27004==    by 0x7BA5FA4: g_closure_invoke (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==    by 0x7BB7FC0: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==    by 0x7BC0D5B: g_signal_emit_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==    by 0x7BC1554: g_signal_emit_by_name (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==    by 0x742A99A: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30)
    ==27004==    by 0x742C47F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30)
    ==27004==    by 0x73C7D9B: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30)
    ==27004==    by 0x7BA5FA4: g_closure_invoke (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==    by 0x7BB856D: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4902.0)
    ==27004==  Address 0x181a6838 is 0 bytes after a block of size 360 alloc'd

I fill the wxHtmlDataObject using its constructor that takes a wxString as argument and then fill a wxDataObjectComposite with it. wxTextDataObject doesn't raise the valgrind warning so there might be a difference between the two objects that causes the error message; Normally (but not always) valgrind finds things that turn out to be actual errors.

**Comment by vadz** [comment]
This is actually the same as (much later) #23660 which provided a test case allowing to fix the problem and so will be fixed when #23659 will be merged.

**Comment by vadz** [comment]
Fixed in master and will be fixed in 3.2 too soon.
