### ISSUE TITLE
wxVirtualDataViewCtrl - new control

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#17775]
*Issue migrated from trac ticket # 17775*

**component:** GUI-generic | **priority:** normal

#### 2017-01-11 23:57:13: seb_d (seb_d) created the issue

___
Hello,
I would like to contribute a new generic control, for data viewing. 

The code is available here:
[https://github.com/seb-dub/wxVirtualDataView]
and a release, with a binary sample (Windows 64 bits) is available here:
[https://github.com/seb-dub/wxVirtualDataView/releases]

It is very similar to wxDataView in the concept, but it has several key differences:
   - it is designed to handle many items (several millions)
   - 2 models : data model (as wxDataView), and a state model (for storing selection / expanded-collapsed / check state)
   - 1 "model renderer" for all drawing related tasks 
   - **built-in filtering and sorting** 
   - generic control (but tested only on Windows so far)

It has some key differences in design with wxDataView - see the "Overview" in the doc (.chm file attached in the release and in the repo)

A doxygen doc is available for more information. It needs to be completed with more high level information

There is still a lot of things I would like to finish inside, but it is in a very usable state (actually I use it at work). There is roughly 25000 lines of code (without comments / spaces)

There are also some components which can be reused for more generic tasks in wxWidgets:
   - some wxVariant utilities (comparison for sorting)
   - a wxVirtualHeaderCtrl which supports many rows/columns, and with filtering messages sent
   - a small LRU cache utility that I use for sorting / filtering. The code is not from me (this is adapted from something found on Internet). I cannot find back the original contributor
   - ...

Feel free to review it, and let me know your thought on it.

**Comment by vadz** [comment]
I think it's not really useful to keep this one open. The problem of #17550 will be fixed when #22382 is merged and we're not going to add yet another table/grid control to wx itself, sorry.
