### ISSUE TITLE
Bitmap graphics appear in different sizes on OS X and Windows with a HiDPI display

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18112]
*Issue migrated from trac ticket # 18112*

**component:** GUI-all | **priority:** normal | **keywords:** HiDPI

#### 2018-03-25 22:43:50: @softwarefailure created the issue

___
I've noticed some differences in behaviour between wxOSX and wxMSW when using bitmap graphics on high DPI displays. 

1) wxStaticBitmap: On MSW the bitmap graphics are rendered as is whereas on OS X they are scaled. Hence, on a high DPI display graphics embedded in a wxStaticBitmap appear much smaller on Windows than on OS X.

2) When using SetBitmap() on a wxButton you can observe the same behaviour: On OS X the bitmap graphics are scaled to match the higher DPI, on Windows they aren't and thus are very very small.

3) Same is true when using bitmap graphics in listviews, wxBookCtrl...

4) When creating a custom class based on wxWindow that does custom drawing, the class seems to use pixels on Windows and points on OS X. Hence, on OS X the class is scaled whereas on Windows it appears very small.

With high DPI displays becoming more and more common, I think we really need some sort of consistent behaviour here.

**Comment by vadz** [comment]
I think the issues here have all been addressed, so closing. Please open new bugs for any concrete remaining problems.
