### ISSUE TITLE
wxSpinButton down arrow disappears when clicking up arrow

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18231]
*Issue migrated from trac ticket # 18231*

**component:** wxMSW | **priority:** normal | **keywords:** wxSpinButton wxPropertyGrid

#### 2018-09-26 19:12:25: colleen (Colleen Curtin) created the issue

___
I am using wxWidgets 3.1 on Windows 10.

I am adding a wxSpinCtrl and a wxDateProperty to a property grid. When I click the up arrow multiple times in a row the bottom arrow disappears. When I hover over the spot where the town arrow button should be it reappears. The same does not happen the other way around (when clicking the down arrow the up arrow stays as it should). The wxDateProperty is using wxSpinCtrl so I think it is just a refresh issue with wxSpinCtrl.

**Comment by taler21** [comment]
Update on this ticket:

The disappearance of the down button in a `wxIntProperty` with `wxPGEditor_SpinCtrl` editor was recently fixed by 79567c83f4263df2860b0c4da38d91da834c1aab (Fix wxSpinButton redrawing when using WS_EX_COMPOSITED, 2023-07-08).

With `wxDateProperty` the issue still exists.

```patch
diff --git "a/samples/propgrid/propgrid.cpp" "b/samples/propgrid/propgrid.cpp"
index 7b423ca2d7..059baa0942 100644
--- "a/samples/propgrid/propgrid.cpp"
+++ "b/samples/propgrid/propgrid.cpp"
@@ -1462,13 +1462,13 @@ void FormMain::PopulateWithExamples ()
 
 #if wxUSE_DATEPICKCTRL
     pg->SetPropertyAttribute( "DateProperty", wxPG_DATE_PICKER_STYLE,
-                              (long)(wxDP_DROPDOWN |
+                              (long)(wxDP_SPIN |
                                      wxDP_SHOWCENTURY |
                                      wxDP_ALLOWNONE) );
 
     pg->SetPropertyHelpString( "DateProperty",
         "Attribute wxPG_DATE_PICKER_STYLE has been set to (long)"
-        "(wxDP_DROPDOWN | wxDP_SHOWCENTURY | wxDP_ALLOWNONE)." );
+        "(wxDP_SPIN | wxDP_SHOWCENTURY | wxDP_ALLOWNONE)." );
 #endif
 
 #endif

```

![wxDateProperty-with-SpinCtrl](https://github.com/wxWidgets/wxWidgets/assets/99262969/12f0fdd7-078c-4170-b9c4-a2a80eb832ce)

**Comment by vadz** [comment]
We probably need to apply the same workaround to `wxDatePickerCtrl` too.

**Comment by vadz** [comment]
The PR referenced above should fix this, please let me know if it doesn't.

**Comment by taler21** [comment]
I tested the PR and can confirm that it fixes the issue.
