### ISSUE TITLE
Always provide wxCRT functions in DLLs

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18373]
*Issue migrated from trac ticket # 18373*

**component:** base | **priority:** low | **keywords:** 3.0-only

#### 2019-03-27 16:47:24: SimonRichter (Simon Richter) created the issue

___
Some wxCRT functions are only provided if the one in the standard library is deemed inacceptable for some reason, but that may change depending on compiler flags.

Specifically, on msys2 `wxCRT_StrdupA(char const *)` is usually left out because wxWidgets is compiled with GNU extensions (as that is compiler default), but a program that uses `-std=c++11` will need a definition in the DLL.

This causes KiCad to [fail to compile](https://jenkins.simonrichter.eu/job/windows-kicad-msys2-patch/294/console) when disabling compiler extensions:

```
CMakeFiles/pcbnew_kiface.dir/objects.a(python_scripting.cpp.obj): In function `wxStrdup(char const*)':
C:/Users/Build/kicad-winbuilder/msys64/mingw64/include/wx-3.0/wx/wxcrtbase.h:687: undefined reference to `wxCRT_StrdupA(char const*)'
```

The DLL should provide these functions even if they are unused with compiler default settings.

**Comment by vadz** [comment]
I thought this was fixed in 3.1 and it doesn't seem to affect KiCad any longer, so closing -- please reopen if the problem can still be reproduced with 3.2, including the instructions for reproducing it.
