### ISSUE TITLE
High DPI and per-monitor support in wxMSW

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18474]
*Issue migrated from trac ticket # 18474*

**component:** wxMSW | **priority:** normal | **keywords:** HiDPI

#### 2019-08-25 00:21:52: @vadz created the issue

___
This is an umbrella ticket for all DPI-related issues in wxMSW.

Please don't modify this ticket directly, but create new tickets for the individual issues and use this one as "blocking" ticket for them to create a dependency.

**Comment by vadz** [comment]
For the record, this was blocked by #16116, #17721, #18090, #18112, #18236, #18288, #18564, #18576, #18649, #18822, #19130, #19152 in Trac.
