### ISSUE TITLE
Some HiDPI issues/regressions

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18576]
*Issue migrated from trac ticket # 18576*

**component:** wxMSW | **priority:** normal | **keywords:** HiDPI

#### 2019-11-13 21:06:50: @PBfordev created the issue

___
I have noticed in my application compiled with the master after fcda2beabba51269d6ef82f7a74c7532d2be3118 that button height can sometimes get too small when a dialog created on a HiDPI screen is moved to a standard DPI one. Trying to reproduce the issue with samples, I found some others. These issues are not related to the above-mention commit, I can reproduce them with a slightly older, post 3.1.3, wxWidgets version.

The text below is based on the dialogs sample.

# Issue I: Buttons shrink when moved from HiDPI to standard DPI screen1. Launch the sample on a HiDPI screen.
2. From menu Dialogs select Standard Buttons Sizer Dialog
3. In the dialog check Enable Affirmative Button and Enable Dismiss Button.
4. Move the dialog to the regular DPI screen and observe buttons being too tight around their labels (see attachment 1).

This dialog is resizable and when you increase its size enough, the buttons will adjust to their expected size. However, when decreasing the dialog size, they are willing to shrink too much again. Not all dialogs in the sample exhibit the same issue, the issue is not limited to the `wxStdDialogButtonSizer`. 

# Issue II: Resizable dialogs have drawing artifacts when moved from HiDPI to standard DPI screenIt seem this issue is worse with the dialogs not exhibiting Issue I. There are two short thick perpendicular white lines in the bottom left corner of the dialog, probably somehow related to drawing the window gripper (see attachment 2).

# Issue III: wxTextCtrl fits around the text when moved from HiDPI to standard DPIWhen moving the dialog invoked by "Test dialog default action" menu, the text control fits around the text and the dialog is left with a lot of empty space on its bottom, see attachment 3.
I am not sure if this is not within the sample itself, Multiple Line Entry dialog does not have the issue, but it may be related to proportions, sizer type, minimal size...

----
Tested on Windows 10 v1903 build 18362.418
One HiDPI screen (primary) at 125% (120 DPI) and one standard DPI screen.

**Comment by vadz** [comment]
I've retested this and I can still see all of these issues and I'm pretty certain they're due to the same causes as #18649, so I'm closing this one in favour of the other one as it has a longer/more useful discussion, even though this one is older.
