### ISSUE TITLE
EVT_CHAR not triggered for Alt+non_latin_letter (cyrillic, for example)

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18637]
*Issue migrated from trac ticket # 18637*

**component:** wxGTK | **priority:** normal | **keywords:** event

#### 2019-12-22 19:10:53: unxed created the issue

___
Alt+non_lating_letter generates EVT_KEY_DOWN/EVT_KEY_UP only, but no EVT_CHAR happens.

Tested on Linux Mint 19.3 x86_64, wx 3.1.3, GTK backend.

**Comment by unxed** [comment]
Fixed in https://github.com/wxWidgets/wxWidgets/commit/2c0f6a2aa0c8d0650d1f856aa279ce7495925c17

@vadz I think this issue can be closed now.

**Comment by vadz** [comment]
Thanks for the reminder!

**Comment by unxed** [comment]
> Fixed in [2c0f6a2](https://github.com/wxWidgets/wxWidgets/commit/2c0f6a2aa0c8d0650d1f856aa279ce7495925c17)
> @vadz I think this issue can be closed now.

Could you please tell me from which release this fix is included in wxWidgets?

**Comment by vadz** [comment]
It will be in 3.3.0 and 3.2.7.

**Comment by unxed** [comment]
But I still see it's code in v3.2.3 tag. How can it be there if it should appear in 3.2.7?

**Comment by vadz** [comment]
> But I see it's code in v3.2.3 tag. How can it be there if it should appear in 3.2.7?

Yes, you're right, your commit 87ae8d5aa7cbeddeb8ead289117c0e114fd72329 is included in 3.2.3 already. But then I don't understand your question, if you already know that it's included in 3.2.3, why are you asking?

**Comment by unxed** [comment]
Sorry for that! Already found everything I needed by myself
