### ISSUE TITLE
Invalid text height determined for empty string

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18825]
*Issue migrated from trac ticket # 18825*

**component:** wxMSW | **priority:** normal | **keywords:** text extent regression

#### 2020-07-14 17:15:38: LumaRay (Yury) created the issue

___
Hello.

I have cloned https://github.com/wxWidgets/wxWidgets and just compiled wxWidgets for Windows 10 x64 and run a sample of PropertyGrid. In this sample there is no help string showing: https://www.screencast.com/t/qJ0sGnRdoQ
I have tried to follow instructions from this page: https://docs.wxwidgets.org/trunk/plat_msw_install.html
In particular I compiled wxWidgets using Visual Studio 2019 compiler:
nmake /f makefile.vc BUILD=release SHARED=1 TARGET_CPU=X64
cd wxWidgets\samples\propgrid\
then I took dlls from wxWidgets\lib\vc_x64_dll\
and run propgrid.exe

I would like to use propertygrid, but without help strings it is not so convenient, can you fix it?

Thanks!

**Comment by vadz** [comment]
This was fixed a long time ago by the commit referenced above.
