### ISSUE TITLE
wxInfoBar icons don't scale with DPI

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18822]
*Issue migrated from trac ticket # 18822*

**component:** GUI-generic | **priority:** normal | **keywords:** HiDPI wxInfoBar

#### 2020-07-13 15:44:05: @vadz created the issue

___
By running the dialogs sample on high DPI display (e.g. with 200% scaling in my case) and showing the info bar in it (`Ctrl-I`) it can be seen that the icons are too small.

**Comment by vadz** [comment]
The size issue seems to have been already fixed. There is still a problem with the icons because they're upscaled -- but this will be fixed when #22229 is merged.
