### ISSUE TITLE
SetScaleFactor() for wxBitmap

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18869]
*Issue migrated from trac ticket # 18869*

**component:** base | **priority:** normal | **keywords:** HiDPI

#### 2020-07-31 14:55:37: @softwarefailure created the issue

___
I don't like to use wxBitmap::CreateScaled() because of potential floating point arithmetic inaccuracies that could come up with this method. Instead, I just create my bitmaps using the normal constructor and then apply the scaling factor using a helper method named SetScaleFactor() which is a counterpart to GetScaleFactor() that is already in wxWidgets.

I have done lots of tests with SetScaleFactor() and my projects on HiDPI systems using MSW, GTK3 and macOS and this solution works nicely so I'd be glad if this could be added into wxWidgets because it would save me the hassle of having to add it manually whenever I update to a newer wxWidgets version.

Patch attached.

**Comment by vadz** [comment]
We do have `SetScaleFactor()` now.
