### ISSUE TITLE
wxDataViewCtrl doesn't handle HiDPI bitmaps correctly

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18868]
*Issue migrated from trac ticket # 18868*

**component:** GUI-all | **priority:** normal | **keywords:** HiDPI

#### 2020-07-31 13:57:58: @softwarefailure created the issue

___
I noticed that HiDPI bitmaps don't work correctly when used as icons in a wxDataViewCtrl entry. I create the icon like that:

```

wxIcon *ic = new wxIcon;
ic->CopyFromBitmap(*bm);
```

The wxBitmap is created using the `CreateScaled()` API.

On GTK it seems that the HiDPI bitmap is scaled up by the content scale factor whereas on macOS it seems that the HiDPI bitmap is scaled down by the content scale factor. On Windows it's almost ok except that the icon is cut off at the top and the bottom. See my screenshots for reference.

With wxListCtrl HiDPI bitmaps work fine on all platforms but wxDataViewCtrl still seems to have those issues.

**Comment by vadz** [comment]
The latest version of dataview sample shows that icons work correctly in high DPI when using the new `wxBitmapBundle`-based API.
