### ISSUE TITLE
Write high DPI support overview

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18889]
*Issue migrated from trac ticket # 18889*

**component:** documentation | **priority:** normal | **keywords:** HiDPI

#### 2020-08-16 13:35:49: @vadz created the issue

___
We need to explain how to use `FromDIP()` etc and which coordinates are in physical pixels and which are in logical "points".

Also need to mention various platform-specific things that need to be done, such as

- Using `PerMonitorV2` DPI awareness in MSW manifest
- Setting `NSPrincipalClass` to `NSApplication` in `Info.plist` under macOS

Please feel free to add more things that should be covered in this overview to this ticket.

**Comment by vadz** [comment]
@iwbnwif I'm not aware of anything special happening to the font scaling, their sizes are typically specified in points, which are DPI-independent, so I don't know what to say about it.
