### ISSUE TITLE
wxDataViewCtrl renderers may be called with null value but don't expect it

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#18934]
*Issue migrated from trac ticket # 18934*

**component:** GUI-all | **priority:** normal | **resolution:** fixed

#### 2020-10-07 21:33:18: @softwarefailure created the issue

___
I have tree items in a wxDataViewCtrl which has five columns and the last column is a wxDataViewToggleRenderer one. This setup always get me the following failed assertion: "Could not convert to a bool" in wxVariant::GetBool(). 

I debugged what's going on and the problem is this: When the header control tries to calculate the width of the toggle column, `CheckedGetValue()` will return a `NULL` wxVariant for every row that doesn't have anything in the toggle column because there's a container in the first column.

Now the problem is that `wxDataViewRendererBase::PrepareForItem()` still calls `SetValue()` in that case even though the wxVariant is a `NULL` one. This will lead to the problem that the `GetBool()` call in `wxDataViewToggleRenderer::SetValue()` will trigger the assert because obviously there's no bool in the wxVariant but `NULL`.  

The fix is rather obvious. Just move `SetValue()` down a line... see attachment.

**Comment by vadz** [comment]
This will have to be fixed in some other way because we're going to need to revert [the origin fix](https://github.com/wxWidgets/wxWidgets/commit/e067e4233caf691d52b52bd146568de697de8311) as it broke existing code, as shown by the example of Poedit.
