### ISSUE TITLE
wxHTMLDataObject enhancements

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19043]
*Issue migrated from trac ticket # 19043*

**component:** GUI-all | **priority:** normal | **keywords:** wxHTMLDataObject,HTML data object,clipboard

#### 2021-01-14 13:28:02: @JulianSmart created the issue

___
This is an enhancement and a bug fix for wxHTMLDataObject that I had to make to get it working with my application.

1. Bug fix: the conversion to UTF-8 failed for me on Windows when pasting from Word, so if it fails it now tries a more relaxed UTF-8 conversion (in case there is rogue data after the HTML).

2. Enhancement: it may not be sufficient to pass or be passed only the HTML fragment. The application may not be able to parse partial HTML, and also it may be necessary to pass style information in the HTML head, which the current implementation does not allow on Windows.

So I have added a 'provision' member and accessors to indicate whether the application is passing - or wants to be passed - all of the data (Raw), the whole HTML (HTML), or just the fragment (Fragment). By default, this is Fragment on Windows and HTML on other platforms, for compatibility.

This should be fully compatible with applications that currently use wxHTMLDataObject.

**Comment by vadz** [comment]
I've just ended up mostly rewriting all this code in #23661 and I think this should work correctly now and this shouldn't be needed any more, but please reopen if you still see anything wrong with this PR applied (as it will be soon).
