### ISSUE TITLE
GTK3 backend has a blurry taskbar icon on HiDPI display

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19048]
*Issue migrated from trac ticket # 19048*

**component:** wxGTK | **priority:** normal

#### 2021-01-18 23:12:18: ancwrd1 (Dmitry Pankratov) created the issue

___
**OS version**: Linux x86_64, openSUSE Tumbleweed.
**Desktop environment**: KDE Plasma 5.20, X11
**wxWidgets version**: master branch, built from sources
**Target backend**: wxGTK3, GTK version 3.24.24-1.1
**Screen resolution**: 3840x2160

wxWidgets configured with:
`../wxWidgets/configure --enable-monolithic --enable-stl --enable-webview --enable-cxx11 --disable-tests --disable-debug_flag --disable-compat30`

Problem description:

When running a sample "taskbar" application the icon looks blurry (downscaled) unless I set "GDK_SCALE=2", in which case the icon is ok but then the text is too large. The issue is only with the taskbar icon, the menu text is scaled correctly.

See attached images.

`LD_LIBRARY_PATH=../../lib ldd ./taskbar` output:

  libwx_gtk3u-3.1.so.5 => ../../lib/libwx_gtk3u-3.1.so.5 (0x00007f8ae2ebf000)
  ...
  libgtk-3.so.0 => /usr/lib64/libgtk-3.so.0 (0x00007f24f5eb0000)
  libgdk-3.so.0 => /usr/lib64/libgdk-3.so.0 (0x00007f24f5daf000)
  libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007f24f5d9c000)
  libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007f24f5d49000)
  libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f24f5c75000)
  libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007f24f5c4b000)
  libcairo-gobject.so.2 => /usr/lib64/libcairo-gobject.so.2 (0x00007f24f5c3f000)
  libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007f24f5b0a000)
  libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007f24f5ae1000)
  ...

**Comment by vadz** [comment]
I think the original problem was fixed by switching to `wxBitmapBundle`: it's now possible to provide several bitmap sizes or even render the bitmap on demand.

The problem with `wxTaskBarIcon` not working at all on recent Linux systems unfortunately remains, but I think this is already covered by #18081. And any patches/PRs to use libappindicator3 or whatever would still be very welcome, of course.
