### ISSUE TITLE
Mac "Save As" dialog, command-A does not select the filename text.

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19054]
*Issue migrated from trac ticket # 19054*

**component:** wxOSX | **priority:** normal | **keywords:** Mac Save As select all

#### 2021-01-21 18:34:15: @andymrob created the issue

___
This is a minor issue but strange. I'm using the "image" sample to illustrate, because it has a "Save" dialog.

Use the "Show any image" command to load an image. Then select the "Save As" command. Initially the full filename is selected "Untitled.bmp". Click on it and type something. Then press command-A. This should select the full name but in fact does nothing.

In the "Save" dialog of TextEdit, command-A does work for selecting the filename.

**Comment by csomor** [comment]
Thanks for pointing this out Andy, yes, it's the same problem as #22711, here we'd need to add 
a) a select all to the main menu, and b) a mini edit menu with cut/copy/paste/select-all for the image frame

**Comment by vadz** [comment]
Must _all_ Mac applications using file dialogs necessarily have the standard "Edit" menu with all the items, even if none of them makes sense for the main window of the application itself? This seems completely wild, so I'd like to be absolutely sure I understand this correctly.

Could we perhaps add a temporary menu just before showing the dialog and remove it afterwards (if the current menu bar doesn't have all the standard "Edit" commands already, of course)?

**Comment by csomor** [comment]
I mean the file open dialog works of course without it, but as we've seen the search fields or the name field for a save file dialog are expected to support the traditional keyboard combos, which means we need some menuitems these can target ...

**Comment by imciner2** [comment]
Can those menu items be created but hidden in menus? I know macOS supports hiding menu items from display but still leaving them in the menu (macOS and GTK do, Windows does not). I had started a branch adding that functionality to wxMenuItems a few years ago, but didn't push it upstream yet.

**Comment by csomor** [comment]
@imciner2 that's an excellent idea, we've had that back in the old days, so we'd add a menu containing just those items that have no handler in the menubar, I thought about shortcutting things even earlier in the controller, but then dealing with the keyboard shortcuts would become ugly, that's a better idea. Thanks, I'll test ...

**Comment by vadz** [comment]
> @vadz actually they should yes, because of the edit commands for the entry fields on the dialogs. 

My point was that the dialog shouldn't depend on the parent window, i.e. in the worst case it should install its own menus (maybe invisible ones as suggested above). It really doesn't make sense for it to rely on somebody else providing these menus for it...

Anyhow, let's close this one as it's essentially the same as #22711 and there is some example code there, so it seems better to keep that one open, even if this one is (much) older.
