### ISSUE TITLE
wxWebView - wxWebViewBackendEdge - Runscript - get stuck

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19075]
*Issue migrated from trac ticket # 19075*

**component:** WebView | **priority:** normal | **keywords:** wxWebView,wxWebViewBackendEdge

#### 2021-02-09 20:53:48: hiemann (Rico Hiemann) created the issue

___
Hi,

 I used the wxWebView sample from master branch and wrote a little test html, see below.
 I noticed different behaviour between wxWebViewBackendEdge vs
 wxWebViewBackendIE especially with RunScript.

 Using the backend: wxWebViewBackendIE
 All links change the images as expected:
InternGrey - grey image - OK
InternRed - red image - OK
ExternGrey - grey image - OK
ExternRed - red image - OK

 Than switching to the backend: wxWebViewBackendEdge
 (Compilation and installation worked - backend message from log:
 wxWebViewEdge Version: Microsoft Edge WebView2 88.0.705)

InternGrey - grey image - OK
InternRed - red image - OK
ExternGrey - change image on first click but function get stuck
ExternRed - change image on first click but function get stuck

The internal C++ part:

```
void WebFrame::OnTitleChanged(wxWebViewEvent& evt)
{
    wxString Msg = evt.GetString();
    if (Msg == "testexternred")
    {
        RunScript("setImage('red.jpg');");
    }
    else if (Msg == "testexterngrey")
    {
        RunScript("setImage('grey.jpg');");
    }
}
```

wxWebViewBackendEdge get stuck in line (infinite loop, no error or any response):

```
if (m_browser->RunScript(javascript, &result))
```

 Thanks in advance
 Rico

```
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
<script>
function setImage(content) 
{
	document.getElementById('myimage').setAttribute('src', content);
}
function mytitle(id)
{
	document.title = id;	
}	
</script>  
    <nav id="head">
	  <a href="#" id="testinterngrey" onclick="setImage('grey.jpg')">InternGrey</a>
	  <a href="#" id="testinternred" onclick="setImage('red.jpg')">InternRed</a>
	  <a href="#" id="testexterngrey" onclick="mytitle(this.id)">ExternGrey</a>
	  <a href="#" id="testexternred" onclick="mytitle(this.id)">ExternRed</a>
	</nav>
    <main>
		<img id="myimage" class="center" src="grey.jpg">
     </main>
  </body>
</html>
```

**Comment by PBfordev** [comment]
This Issue should probably be either closed or labeled for backport.

**Comment by vadz** [comment]
I don't know this code well enough to be confident in backporting this correctly, so I won't do it, even though I think it would indeed be useful to have this in 3.2, so if anybody is interested in doing this, please create a PR for 3.2 doing this.
