### ISSUE TITLE
Create a new sample showing how to correctly handle high DPI

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19130]
*Issue migrated from trac ticket # 19130*

**component:** GUI-all | **priority:** normal | **keywords:** HiDPI

#### 2021-04-04 15:30:58: @vadz created the issue

___
The point of this exercise is to actually make sure that we *can* handle all the different things below correctly, but having a sample showing how to do it should be useful in its own right.

Things that the sample should demonstrate:

1. Using DIP for layout, window sizing etc.
1. Dynamically selecting the bitmaps of the correct size to use with
   - `wxToolBar`
   - `wxImageList` (with e.g. `wxTreeCtrl`)
   - `wxStaticBitmap`
   - `wxGC::DrawBitmap()`
1. Rendering some graphics contents at maximum resolution, i.e. without scaling:
   - When using raster bitmaps (`wxImage`)
   - When drawing using the API calls.
1. Handling `wxEVT_DPI_CHANGED`.

Please add more tasks to this list if you can think of anything.

**Comment by vadz** [comment]
I think we're not going to add a new sample, finally, as most of these things are already shown in the existing samples. I'll address the point (4) which is the only one still missing, I think.
