### ISSUE TITLE
Remove MSVS 200x project files and support for generating them

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19150]
*Issue migrated from trac ticket # 19150*

**component:** build | **priority:** normal | **keywords:** bakefile

#### 2021-04-18 13:42:33: @vadz created the issue

___
This is (the easy) part of migrating away from using bakefile for wx project/make files.

**Comment by vadz** [comment]
Done in 1cf49f9909 (Remove MSVS 2005 and 2008 project files, 2022-10-09).
