### ISSUE TITLE
Remove WXWIN_COMPATIBILITY_2_8 in 3.3 branch

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19151]
*Issue migrated from trac ticket # 19151*

**component:** build | **priority:** normal

#### 2021-04-18 13:52:13: @vadz created the issue

___
Just a reminder to do it after 3.2.0 release.

Also set `WXWIN_COMPATIBILITY_3_0` to 0 by default.

**Comment by vadz** [comment]
This got duplicated as #22686 and was done in eb1242cc1ca28baf09b9f42967636cdd1470fb06
