### ISSUE TITLE
Contents are resized wrong when DPI is changed

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19152]
*Issue migrated from trac ticket # 19152*

**component:** wxMSW | **priority:** low | **keywords:** HiDPI

#### 2021-04-20 00:22:14: alerion created the issue

___
I have an app with several dialogs and most of them look fine after resizing done by wxWidgets.
Though one dialog has one of its text fields resized wrong when the app is started on a 100% display and moved to a 150% one. It looks fine in the oposite direction.

The dialog has a wxPanel as its only child. Contents of the panel have vertical borders, 15 to 20 of them, primarily of 5 px at 100%, some are 10 px. Upon DPI change SetSizeHints is called on the panel's sizer in a DPI change event handler. It computes a correct size for all the fields. But then `src/msw/nonownedwnd.cpp:277` has

```c++
SetSize(newRect);
```

which uses a size computed by Windows. This size is less than the correct one and and causes a problem for this dialog. Probably related to fractional sizes and rounding to an integer.

Can this call in nonownedwnd.cpp be made optional? This newRect has suggested sizes, not constraints, and sometimes they are a bit off.

Also, do you have recommendations of what should and should not be used for HiDPI to not cause such problems?

**Comment by vadz** [comment]
See also #18649.

Maybe we should only call this `SetSize()` if `wxDPIChangedEvent` was unprocessed? This would make sense, IMO.

**Comment by vadz** [comment]
For the record, I've finally done this in #22565, so that the application can now override the resizing done by wx itself if it can do it better.
