### ISSUE TITLE
OSX ListView last column sets to 0 size

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19167]
*Issue migrated from trac ticket # 19167*

**component:** wxOSX | **priority:** high

#### 2021-04-29 14:21:45: @dkulp created the issue

___

With 7555d1b2459949c128d6ee3a473669a1a134f124, it attempts to set the last column size to the rest of the width of the view.   However, if the width of the view is less than the width of all the columns (and thus a scroll bar appears, the last column ends up with 0 width and is invisible.  

There doesn't seem to be any way to disable this behavior.   It always sets the sizeLastColumnToFit if it's the last column, even if a specific width is set.

**Comment by vadz** [comment]
I think this was fixed by 5f34d07bc1 (Revert "Fix sizing of temporarily last columns in macOS wxDataViewCtrl", 2021-08-10), please reopen if the problem still exists and explain how can it be reproduced in this case. TIA!
