### ISSUE TITLE
Force Dark Mode (OSX)

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19185]
*Issue migrated from trac ticket # 19185*

**component:** wxOSX | **priority:** low | **keywords:** Dark mode

#### 2021-05-26 16:00:29: bartvanstiphout (Bart van Stiphout) created the issue

___
Hello,

I’ve extended wxSystemAppearance with a function to force the application to use the dark mode color scheme on OSX. 
Is this something which can be useful for more people and add the code to the wxwidgets source?

Best regards,

Bart

**Comment by vadz** [comment]
Please check #24461 and let me know (there) if you see any problems with it, TIA!
