### ISSUE TITLE
wx.GenericDirCtrl runtime error

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19182]
*Issue migrated from trac ticket # 19182*

**component:** GUI-generic | **priority:** normal | **keywords:** wxTreeCtrl::GetItemParam

#### 2021-05-25 16:44:52: rfresh737 (Ralph Freshour) created the issue

___
When I run the demo GenericDirCtrl app, I can reproduce a runtime error with the following steps:

    1.Start the GenericDirCtrl app.
    2.In the right side pane open up drive C to display the folders.
    3.Change all files to python files. The error will popup a window.

treectrl.cpp(1066): assert "Item.IsOK()" failed in wxTreeCtrl::GetItemParam()

**Comment by vadz** [comment]
So the reason for this is that we get a `wxEVT_TREE_SEL_CHANGED` event with an invalid tree item. Working around this is simple enough, of course, but I wonder if we should be getting this event in the first place. I'm almost certain that the generic version of `wxTreeCtrl` doesn't send it in this case. OTOH sending this event seems to be useful...

Finally I'll just add a trivial workaround, which is better than nothing.
