### ISSUE TITLE
wxPopupTransientWindow always closes on mouse click on MacOS

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19229]
*Issue migrated from trac ticket # 19229*

**component:** wxOSX | **priority:** normal | **keywords:** popup

#### 2021-07-21 20:01:33: whalley (Mark Whalley) created the issue

___
I can't get wxPopupTransientWindow to process anything without closing. 

Using the "samples/popup" code as soon as I click anywhere in the window the popup closes.

macOS 11.4 (20F71)
wxWidgets 3.1.5

**Comment by whalley** [comment]
Anybody with Cocoa expertise able to review and comment

**Comment by whalley** [comment]
Any Cocoa expert able to help, it is thwarting my efforts on an application of this dialog.

**Comment by vadz** [comment]
@csomor Would you have any idea about this one please? It looks like a bad bug, but I don't know at all how are you supposed to implement popups with Cocoa, so I can't do anything about this myself.

**Comment by csomor** [comment]
@vadz the problem lies in the OnKillFocus that is always received and results in a DismissAndNotify because it does not recognize that the window itself has not changed. I'll try to find out what could be done, but it's deep in focus handling where I have to emulate things for wx, as Cocoa offers less info than we what we need ..

**Comment by whalley** [comment]
@csomor Thanks for taking the time to look at this Stefan.

**Comment by csomor** [comment]
@whalley @vadz Ok, the problem is that in popupcmn.cpp line 328   `m_focus = FindFocus();` because the popup itself cannot receive the focus, it returns the former focused control, ie the one on the **main** window, thus attaching a focus lost handler on that, which obviously gets triggered the moment the first control on the popup is clicked ..

**Comment by csomor** [comment]
ok, I've tried to add a SetFocus to wxPopupWindow, but this did not really work correctly, so I'd propose the following: @whalley could you please deactivate the current macOS code in popupcmn.cpp line 324 by changing the `#if defined( __WXMAC__) && wxOSX_USE_COCOA_OR_CARBON` to a `#if 0` ? and report back ? Thanks a lot

**Comment by whalley** [comment]
@csomor Thanks, that works and stops the popup from disappearing until I move focus back to invoking app. The only odd behavior I have noticed is that when a popup is presented and I click outside of the application and it loses focus the popup does not close and then appears in front all MacOS apps. Was not expecting that.

https://user-images.githubusercontent.com/487345/172064040-20de88fa-8b3d-45a3-9520-f926dc8914ac.mp4

**Comment by csomor** [comment]
@whalley thanks, oh dear, ok, let's try this:
nonownedwnd.mm line 939, please add
`[m_macWindow setHidesOnDeactivate:YES];`

**Comment by whalley** [comment]
@csomor Getting there :-) Yes, that sort of works but it just hides the popup and does not dismiss it (I get no OnDismiss() triggered), it is still there and will be re-displayed if clicked on again. See below.

https://user-images.githubusercontent.com/487345/172074179-c3d60ae1-ec27-41e9-8999-54a44a2e1d1d.mp4

**Comment by whalley** [comment]
@csomor OK, I can live with that. The core functionality now works, which is great. Let's go with this fix.

**Comment by whalley** [comment]
@csomor Have encountered another issue with this that you can perhaps offer guidance on.

I have a dialog as below:
![CleanShot 2022-07-02 at 11 33 40](https://user-images.githubusercontent.com/487345/176997010-5b38b110-a8c0-4c4f-aaf4-b2a241976613.png)

I have implemented a Transient popup when right-clicking on the date that just pops a panel with a wxCalendarCtrl.

![CleanShot 2022-07-02 at 11 35 26](https://user-images.githubusercontent.com/487345/176997083-ee06c454-42e7-40ef-85be-1d070a4c5ccb.png)

I can use the Calendar control fine, except (it seems) on days where there is a widget under the control that seems to take the events, e.g. I can select Days 1 -6, 10, 13, 20, 27  but not the others. Is this a manifestation of the logic change you made? Is there any workaround I do in my application level to avoid this?

![CleanShot 2022-07-02 at 11 37 06](https://user-images.githubusercontent.com/487345/176997140-c98f5d96-b703-47ff-8770-3b726f44daef.png)

**Comment by csomor** [comment]
> @csomor Have encountered another issue with this that you can perhaps offer guidance on.

> I can use the Calendar control fine, except (it seems) on days where there is a widget under the control that seems to take the events, e.g. I can select Days 1 -6, 10, 13, 20, 27 but not the others. Is this a manifestation of the logic change you made? Is there any workaround I do in my application level to avoid this?

@whalley I don't know whether and how these might be related, could you please open a new issue and add a code snippet that allows me to reproduce the behaviour ? Thanks.

**Comment by whalley** [comment]
@csomor  Thanks Stefan... You solved my problem, as I created a code snippet and it worked! I returned to my failing code and it turned out I was passing the window reference in one place.  

All good now, thanks!
