### ISSUE TITLE
Size of toolbar buttons in webview sample in PMv2 DPI aware build has changed

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19287]
*Issue migrated from trac ticket # 19287*

**component:** samples | **priority:** normal | **keywords:** HiDPI bitmaps-needed

#### 2021-10-11 20:14:08: @vadz created the issue

___
As noted by PB:

> What I did notice is that the toolbar icons for Refresh and Stop in the webview sample look different from 3.1.5 when running as PMv2 DPI-aware on a system with primary display DPI scaling at 125%. They are larger and uglier (master on the top, 3.1.5 on the bottom):

See https://user-images.githubusercontent.com/12495521/136707744-dc6d0bc8-2ccd-4f02-9db1-d073c4a4566e.png

**Comment by vadz** [comment]
This was fixed when the PR above was merged in ccb6b10c1fe690b748b85b6ff47b6acd98e34385, thanks again.
