### ISSUE TITLE
Some child Dialogs disappear when moved from one monitor to another on macOS Catalina

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19300]
*Issue migrated from trac ticket # 19300*

**component:** wxOSX | **priority:** normal | **keywords:** child dialogs disappear Catalina

#### 2021-10-20 21:50:57: transana (David) created the issue

___
My apologies.  I usually work in wxPython and am not fluent in C++ and related work procedures.

This problem is limited to macOS Catalina (10.15).  It does not occur on macOS Mojave (10.14) nor on Big Sur (11.x) and does not occur on Windows.  I have not tested it on other platforms.

I create a main Frame for my application, then create a child Dialog using wxDialog, wxFindReplaceDialog, wxMultiChoiceDialog, wxProgressDialog, wxSingleChoiceDialog, wxTextEntryDialog, wxRearrangeDialog, or wxRichMessageDialog.  When the child dialog is displayed, I drag it from the monitor where it was created to the other monitor on my Mac.  The child dialog disappears.  It continues to exist, and if modal, continues to hold control of the program, but you can't see it.  IIRC, the same is true for wxWizards.

The two dialogs move in parallel when the parent is dragged,  If I drag the parent dialog away from the boundary with the second monitor, the missing dialog will show up if I can drag it far enough for it to move the child back to the original monitor. 

Pressing ESC sometimes will close an invisible Dialog and return control to the main frame, but not always.  It depends on the dialog type.

In wxPython, I can use "None" instead of "self" (the parent dialog) as the parent when creating the child Dialog.  Then the child will not disappear, and will not move in parallel with the (non)parent dialog.

I have reproduced this problem with wxPython's demo for all classes listed above.  Run the wxPython demo, start the demo sample for the appropriate Common Dialog, and drag the new dialog to the other monitor.  It will disappear, as described.

I have reproduced this problem in wxWidgets with C++ for the wxTextEntryDialog as well.  I edited the "bombs" sample program, replacing the AboutBox's wxMessageBox with a wxTextEntryDialog using this code:

```
void BombsFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
{_    wxMessageBox(
_        wxT("wxBombs (c) 1996 by P. Foggia\n"),
//        wxT("About wxBombs") );
     wxTextEntryDialog dlg(
         this,
         wxT("wxBombs (c) 2021 by P. Foggia\n"),
         wxT("About wxBombs"),
         wxT("Text to edit") );
     dlg.ShowModal();
     dlg.Destroy();
}
```

(Sorry, I couldn't figure out how to get an appropriately small diff file.)  I strongly suspect that similar changes would work for the other classes I identified as problematic in wxPython, but I admit, I didn't try to prove this.  My C++ knowledge is very limited.

**Comment by vadz** [comment]
This is the same as a later, but containing more information, #22242, so closing this one.
