### ISSUE TITLE
Events missing from wxSearchCtrl on Mac

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19321]
*Issue migrated from trac ticket # 19321*

**component:** wxOSX | **priority:** high

#### 2021-11-15 21:06:55: JeffYoung created the issue

___
I'm not getting any wxEVT_CHAR or wxEVT_CHAR_HOOK events from wxSearchCtrls on Mac.

This means that I can't use up/down arrows to cycle through the search hits, but it also means that Cmd-X/Cmd-C/Cmd-V don't work.  (I get events for both from wxTextCtrl, but not from wxSearchCtrl.)

The menu enable/disable for cut/copy/paste also doesn't work for native search controls in dialogs.  To reproduce run the "animate" sample, open the File Open dialog, type some text in the Search control and try to cut/copy/paste via Cmd-X/Cmd-C/Cmd-V.

**Comment by sethhillbrand** [comment]
Let me know if you need more details on this reproduce the issue

**Comment by vadz** [comment]
I can see it, I'll take a look.

**Comment by vadz** [comment]
I think comment by Jeff Young above is correct, i.e. we need to handle `wxNSSearchField` in `windowWillReturnFieldEditor:` too, as the field itself doesn't seem to get any key down events at all (it does get key up ones, but this is not very useful).

@csomor Any objections if I try to fix this and then, if it works, also refactor the code to add some virtual function that could be used instead of performing the moral equivalent of dynamic cast in `windowWillReturnFieldEditor:`?

**Comment by csomor** [comment]
@vadz no objection, I hope this will work, fingers crossed ...

**Comment by vadz** [comment]
This seems to have worked without any trouble (what am I missing??), see #22703.

The issue with `wxEVT_KILL_FOCUS` still remains though, so I've extracted it into its own issue.

@sethhillbrand Please let me know if you still see any problems with that fix and please also let me know if you rely on the kill focus events working, I could try to fix those ones too then.

**Comment by sethhillbrand** [comment]
@vadz Thanks!  We do also depend on the `wxEVT_KILL_FOCUS` in a number of places.  We'll pull the fix back to our wx branch and test.

**Comment by vadz** [comment]
@sethhillbrand The other bug turned out to be even simpler to fix, see #22706, please merge this one before/when testing. TIA!

**Comment by jey5nd6** [comment]
With the changes we're now getting key events for wxSearchCtrls in our dialogs, which is great. 🎆 

However, Cmd-V still doesn't work in search controls that are in the standard File Open dialog.  (This can also still be seen in the Animate sample.)

**Comment by vadz** [comment]
I have no idea how can we arrange for our `windowWillReturnFieldEditor:toObject:` to be called inside non-wx `NSWindow`s.

@csomor Can we set `wxNonOwnedWindowController` as a delegate for a standard dialog? If yes, I might try doing it, but it looks weird to me. If not, I wonder if we could use [fieldEditorForView:](https://developer.apple.com/documentation/appkit/nscell/1532763-fieldeditorforview/) to customize the editor at the control level and not bother with the window delegate at all? This would seem to be a better approach, but you must have had some reason not to use it originally, was it only for compatibility with the then current macOS versions (this one is 10.6+ "only") or was there something else?

**Comment by jey5nd6** [comment]
In the non-wx `NSWindow` case we don't really need the keystroke; we just need the platform to handle it in the native control.  For some reason (menu disabling, perhaps?) the key event isn't getting handled by the toolkit.

**Comment by vadz** [comment]
I think I may have misunderstood you, are you speaking of the standard search control, i.e. not a (custom) `wxSearchCtrl` at all? If so, this is indeed different and probably merits a separate issue...

**Comment by jey5nd6** [comment]
Correct; standard search control in standard File Open dialog.  Do you want me to log another issue for it?

**Comment by csomor** [comment]
@jey5nd6 you need a proper edit menu in the app with the corresponding keyboard shortcuts for this to work

**Comment by jey5nd6** [comment]
I do have an edit menu -- the problem appears (at first blush) to be that wxWidgets is disabling all the items in it when the dialog is open.

**Comment by csomor** [comment]
the menu items should be disabled, when a file open dialog is opened, only the ones like paste and select all remain active, and you are using the correct default menu identifiers for paste etc ... ?  I've added an edit menu to the animate sample, 203b78563f1fde227e6a27367f43046dfe440396

**Comment by jey5nd6** [comment]
Yeah, I added them to the clipboard sample and they do indeed work there:

```
/////////////////////////////////////////////////////////////////////////////
// Name:        clipboard.cpp
// Purpose:     clipboard wxWidgets sample
// Author:      Robert Roebling
// Copyright:   (c) Robert Roebling
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"


// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWidgets headers)
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

#include "wx/clipbrd.h"

#ifndef wxHAS_IMAGES_IN_RESOURCES
    #include "../sample.xpm"
#endif


#define USE_ASYNCHRONOUS_CLIPBOARD_REQUEST  0

class MyApp : public wxApp
{
public:
    virtual bool OnInit() wxOVERRIDE;
};

#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
enum AsyncRequestState
{
   Idle,
   Waiting,
   Finished
};
#endif

class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString& title);

    void OnQuit(wxCommandEvent&event);
    void OnAbout(wxCommandEvent&event);
    void OnFlush(wxCommandEvent &event);
    void OnOpen(wxCommandEvent &event);
    void OnWriteClipboardContents(wxCommandEvent&event);
    void OnUpdateUI(wxUpdateUIEvent&event);
#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
    void OnClipboardChange(wxClipboardEvent&event);
#endif

private:
    wxTextCtrl        *m_textctrl;
#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
    AsyncRequestState  m_request;
    bool               m_clipboardSupportsText;
#endif

    wxDECLARE_EVENT_TABLE();
};

enum
{
    ID_Quit   = wxID_EXIT,
    ID_About  = wxID_ABOUT,
    ID_Write  = 100,
    ID_Text   = 101,
    ID_Flush  = 102
};

wxBEGIN_EVENT_TABLE(MyFrame, wxFrame)
    EVT_MENU(ID_Quit,  MyFrame::OnQuit)
    EVT_MENU(ID_About, MyFrame::OnAbout)
    EVT_MENU(ID_Flush, MyFrame::OnFlush)
    EVT_MENU(2000, MyFrame::OnOpen)
    EVT_BUTTON(ID_Write, MyFrame::OnWriteClipboardContents)
    EVT_UPDATE_UI(ID_Write, MyFrame::OnUpdateUI)
#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
    EVT_CLIPBOARD_CHANGED(MyFrame::OnClipboardChange)
#endif
wxEND_EVENT_TABLE()

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
    if ( !wxApp::OnInit() )
        return false;

    MyFrame *frame = new MyFrame("wxClipboard sample");
    frame->Show(true);

    return true;
}

MyFrame::MyFrame(const wxString& title)
       : wxFrame(NULL, wxID_ANY, title)
{
    // set the frame icon
    SetIcon(wxICON(sample));

#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
    m_request = Idle;
    m_clipboardSupportsText = false;
#endif

#if wxUSE_MENUS
    // create a menu bar
    wxMenu *fileMenu = new wxMenu;

    // the "About" item should be in the help menu
    wxMenu *helpMenu = new wxMenu;
    helpMenu->Append(ID_About, "&About\tF1", "Show about dialog");

    fileMenu->Append(ID_Flush, "Flush the clipboard" );
    fileMenu->Append(ID_Quit, "E&xit\tAlt-X", "Quit this program");
    fileMenu->Append(2000, "Open\tCtrl-O");

    wxMenu *editMenu = new wxMenu;
    editMenu->Append(wxID_PASTE, "Paste\tCtrl-V");
    
    // now append the freshly created menu to the menu bar...
    wxMenuBar *menuBar = new wxMenuBar();
    menuBar->Append(fileMenu, "&File");
    menuBar->Append(editMenu, "&Edit");
    menuBar->Append(helpMenu, "&Help");

    // ... and attach this menu bar to the frame
    SetMenuBar(menuBar);
#endif // wxUSE_MENUS

    wxPanel *panel = new wxPanel( this, -1 );

    wxBoxSizer *main_sizer = new wxBoxSizer( wxVERTICAL );
    main_sizer->Add( new wxButton( panel, ID_Write, "Get clipboard text" ), 0, wxALL, 5 );
    m_textctrl = new wxTextCtrl( panel, ID_Text, "", wxDefaultPosition,
      wxDefaultSize, wxTE_MULTILINE );
    main_sizer->Add( m_textctrl, 1, wxGROW );
    panel->SetSizer( main_sizer );
}

void MyFrame::OnOpen(wxCommandEvent &WXUNUSED(event))
{
    wxFileDialog openDlg( this, _( "Open" ), "", "", "", wxFD_OPEN | wxFD_FILE_MUST_EXIST );
    
    openDlg.ShowModal();
}

void MyFrame::OnFlush(wxCommandEvent &WXUNUSED(event))
{
    wxClipboardLocker clipLock;

    if ( !clipLock )
    {
        m_textctrl->AppendText("Failed to lock clipboard.\n");
        return;
    }

    wxString clipData = wxString::Format("Text from wx clipboard sample at %s" , wxDateTime::Now().Format());
    if ( !wxTheClipboard->AddData(new wxTextDataObject(clipData)) )
    {
        m_textctrl->AppendText("Failed to put text on clipboard.\n");
        return;
    }

    if ( !wxTheClipboard->Flush() )
    {
        m_textctrl->AppendText("Failed to flush clipboard.\n");
        return;
    }

    m_textctrl->AppendText("Clipboard flushed successfully, you should now "
                           "be able to paste text even after closing the sample.");
}

void MyFrame::OnWriteClipboardContents(wxCommandEvent& WXUNUSED(event))
{
   if (wxTheClipboard->Open())
   {
        if (wxTheClipboard->IsSupported( wxDF_UNICODETEXT ))
        {
            wxTextDataObject data;
            wxTheClipboard->GetData( data );
            m_textctrl->Clear();
            m_textctrl->SetValue( data.GetText() );

        }
        wxTheClipboard->Close();
   }
}

#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
void MyFrame::OnClipboardChange(wxClipboardEvent&event)
{
    m_clipboardSupportsText = event.SupportsFormat( wxDF_UNICODETEXT );
    m_request = Finished;
}
#endif

void MyFrame::OnUpdateUI(wxUpdateUIEvent&event)
{
#if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
    if (m_request == Idle)
    {
        if (!wxTheClipboard->IsSupportedAsync( this ))
        {
            // request failed, try again later
            event.Enable( m_clipboardSupportsText ); // not yet known, assume last value
            return;
        }
        m_request = Waiting;
        event.Enable( m_clipboardSupportsText ); // not yet known, assume last value
    }
    else if (m_request == Waiting)
    {
        event.Enable( m_clipboardSupportsText ); // not yet known, assume last value
    }
    else if (m_request == Finished)
    {
        event.Enable( m_clipboardSupportsText );
        m_request = Idle;
    }
#else
    event.Enable( wxTheClipboard->IsSupported( wxDF_UNICODETEXT ) );
#endif
}

void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
{
    // true is to force the frame to close
    Close(true);
}

void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
{
    wxMessageBox("Clipboard sample", "About clipboard", wxOK|wxICON_INFORMATION, this);
}
```

We probably don't use the default menuIDs normally as we have an editable hotkey system.

I found one top-level window where we don't currently have an edit menu, so I added one there with standard `wxMenu` and standard `wx_ID`s.  This is indeed successful.

**Comment by csomor** [comment]
ok, then I understand, I have to map internally wx-menu-item-ids to 'native selectors' back and forth in order for these things to work (menu enabling and menu execution), so there is no way I can think of to avoid standard ids

**Comment by jey5nd6** [comment]
I think we had this same problem with `wxID_QUIT` or `wxID_CLOSE` or something and managed to work around it.  I don't remember the details but let me see if Ian does....

**Comment by csomor** [comment]
the edit-selectors are a little bit different, they are in `src/osx/cocoa/menuitem.mm` `sActionToWXMapping` just as a pointer ...

**Comment by jey5nd6** [comment]
I've hacked our menu-action system to use wxWidgets' IDs for cut/copy/paste.  It works for standard file dialogs brought up from document windows.

But I have another instance where a top-level-window brings up a modal dialog which has a `wxGrid` in it.  Some cells in the `wxGrid` have a `wxGridCellEditor` which shows a folder icon on the far right and brings up a standard file dialog when you click on it.  These still don't work.

The only difference I can think of is that in the `wxGrid` case the standard file dialog's parent is the `wxGrid`'s modal dialog rather than a document window.  Could this confuse wxWidgets when it's looking for the active menubar or something?

**Comment by jey5nd6** [comment]
![image](https://user-images.githubusercontent.com/34380939/183264626-3fb4d5bf-109f-4dd4-aefb-127f2b1f3412.png)

**Comment by csomor** [comment]
Yes, this might lead to the menu items not being traceable, could you please put together a small extension to a sample, that I can use to try my luck?

**Comment by vadz** [comment]
Guys, I hate to say it, but it would be really better to take this to another ticket because things are getting very confusing here as this is completely unrelated to the original problem.

**Comment by csomor** [comment]
@vadz sure, @jey5nd6 I think the new ticket Vadim opened #22711 would be a good place to move this to

**Comment by jey5nd6** [comment]
Cool, I took it up in the other report....
