### ISSUE TITLE
wxDataViewCtrl with huge data fails updating

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19328]
*Issue migrated from trac ticket # 19328*

**component:** wxMSW | **priority:** high | **keywords:** wxDataViewCtrl

#### 2021-11-27 00:14:51: KodamaDeveloped created the issue

___
If wxDataViewCtrl has a huge number of data, the control cannot be updated if displayed rows are beyond a specific limit.  Compile the followings by supplying appropriate lib files.  If the topmost row is less than 6100806 everything is OK.  Otherwise updating the control stops, that you can easily confirm by enlarging the window.  I googled to find probably the same issue reported (https://groups.google.com/g/wx-users/c/XEjLpl1wTRc), which doesn't show the solution however.

```
#!cpp
#include <wx/wx.h>
#include <wx/dataview.h>
class MyModel:public wxDataViewVirtualListModel
{
public:
    unsigned int GetColumnCount() const override {return 1;}
    wxString GetColumnType(unsigned int col) const override {return "string";}
    void GetValueByRow
        (wxVariant& variant,unsigned int row,unsigned int col) const override
        {variant=wxString::Format("%d",row);}
    bool SetValueByRow
        (const wxVariant& variant,unsigned int row,unsigned int col) override
        {return false;}
};
class MyFrame:public wxFrame
{
public:
    MyFrame(wxWindow* parent,wxWindowID id):wxFrame{parent,id,"DataViewCtrlTest"}
    {
        auto* ctrl=new wxDataViewCtrl{this,wxID_ANY};
        auto* model=new MyModel{};
        ctrl->AppendTextColumn("Row",0);
        ctrl->AssociateModel(model);
        model->DecRef();
        model->Reset(97612892);
        ctrl->EnsureVisible(model->GetItem(6100806));
    }
};
class MyApp:public wxApp
{
public:
    bool OnInit() override
    {
        auto* frame=new MyFrame{nullptr,wxID_ANY};
        frame->Show();
        SetTopWindow(frame);
        return true;
    }
};
wxIMPLEMENT_APP(MyApp);
```

The issue is located in wxDataViewMainWindow::OnPaint (src/generic/datavgen.cpp:2459).  There wxScrollHelper::PrepareDC() is called to execute all drawing operations on a device context (DC) by unscrolled coordinates.  In wxMSW the DC is wxBufferedPaintDC of which internal buffer is wxBufferedDC that uses a memory device context created by ::CreateCompatibleDC() winapi function.  Logical coordinates of the context are set by ::SetWindowOrgEx()/::SetViewportOrgEx()/::SetWindowExtEx()/::SetViewportExtEx() winapi functions according to the current scrolled area to match the unscrolled coordinates.  Possibly because the logical coordinates are exact one-to-one mapping to the device coordinates in this case, they are only valid in "device coordinate space" which is limited up to 2^27^ (https://docs.microsoft.com/en-us/windows/win32/gdi/transformation-of-coordinate-spaces).

All drawing operations on the wxBufferedPaintDC are actually on the wxBufferedDC, before the wxBufferPaintedDC destructor (include/wx/dcbuffer.h:183) calls wxBufferedDC::UnMask() (src/common/dcbufcmn.cpp:134) to copy (BitBlt) the contents to the actual DC.  If the top-left logical coordinates of the wxBufferedDC are beyond the "device coordinate space" the BitBlt fails.  If the topmost row is 6100806 the top y-coordinate is 6100806*22(line height) = 2^27^+4 > 2^27^, which is beyond the space.

To solve the issue in a project targeting only MSW I avoided calling the wxScrollHelper::PrepareDC() in wxDataViewMainWindow::OnPaint() and changed all drawing operations on the DC from by unscrolled coordinates to by scrolled coordinates.  That has worked well so far.

**Comment by vadz** [comment]
This was fixed in 4f9186f1a1 (Increase usable scrolling range in wxMSW by a factor of 10,000, 2022-04-30), included in 3.1.7 and, hence, 3.2.0.
