### ISSUE TITLE
Migrate wxTrac tickets to GitHub Issues

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#19349]
*Issue migrated from trac ticket # 19349*

**component:** project infrastructure | **priority:** normal

#### 2021-12-12 17:40:24: @vadz created the issue

___
There is a number of tools for migrating from Trac to GitHub Issues, here is a list combining those found in [SO question](https://stackoverflow.com/questions/6671584/how-to-export-trac-to-github-issues) and [this post](https://josh-ops.com/posts/trac-to-github/), which compares the 2 first ones and contains more details about them:

- https://github.com/mavam/trac-hub
 - Pro: uses [issues import API](https://gist.github.com/jonmagic/5282384165e0f86ef105).
 - Con: Doesn't support attachments (but see [the patch here](https://github.com/mavam/trac-hub/issues/8)).
- https://github.com/trustmaster/trac2github
 - Con: Doesn't support attachments
- https://github.com/svigerske/trac-to-github
- https://github.com/yegor256/trac2github
- https://github.com/behrisch/migrate-trac-issues-to-github
 - Con: doesn't preserve ticket numbers
- https://github.com/acdha/migrate-trac-issues-to-github
 - Con: seems to be the base/older version of the previous one
- https://github.com/buildbot/trac2gh
- https://github.com/hellais/gh-to-trac

Those seem to only work with SQLite databases (we use PostgreSQL):

- https://github.com/hershwg/github-migrate-trac-tickets
- https://github.com/atiti/trac2github

For completeness:

- https://github.com/tracboat/tracboat allows to migrate to GitLab but also export to locale files, could be useful for a backup.

mavam/trac-hub looks pretty good, but we need to check if we can migrate the attachments using it, as they're pretty important and we don't want to lose them (they contain reproducers for bugs, screenshots etc).

**Comment by vadz** [comment]
Migration is done now.
