### ISSUE TITLE
wxHtmlWindow BIG and SMALL tags both selecting the smallest font

### ISSUE THREAD

**Issue by bakcsizs** [wxWidgets/wxWidgets#22012]
Hello!

In m_fonts.cpp:330 (tag handler for BIG and SMALL):
```
int oldsize = m_WParser->GetFontSize();
int sz = (tag.GetName() == wxT("BIG")) ? +1 : -1;
m_WParser->SetFontSize(sz);
```
That results in SetFontSize(1) for BIG and SetFontSize(-1) for SMALL.
Looking at SetFontSize() in winpars.cpp:535:
```
if (s < 1)
    s = 1;
else if (s > 7)
    s = 7;
m_FontSize = s;
```
so both 1 and -1 result in m_FontSize = 1, the smallest font.

Tip for fix: m_fonts.cpp:333:
`m_WParser->SetFontSize(oldsize+sz);
`

Best Regards:
Zsolt

**Comment by vadz** [comment]
Thanks, this indeed seems like an obvious bug, it's just amazing that it went unnoticed for 21+ years. Will merge your fix soon, thanks again!
