### ISSUE TITLE
Fix wxArtProvider::GetSizeHint() when using multiple monitors with different DPI

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22022]
We currently have a problem with this function and `GetNativeSizeHint()`: they use `FromDIP()`, but always use the top application window, so their results are inappropriate for windows using different DPI value.

One solution would be to pass them an option `wxWindow* win = NULL` argument, which is very simple, but not necessarily most convenient. Another solution would be to return the values from these functions in DIPs and let the caller convert. This would be inconsistent with just about everything else though...

So maybe refactor this and add `GetSizeHintInDIPs()` and reimplement the existing function as `FromDIP(GetSizeHintInDIPs(), win)`?

@MaartenBent would you have any thoughts about this by chance?

**Comment by MaartenBent** [comment]
I don't really have a preference. Easiest is adding a `wxWindow` parameter (like `wxGetSystemMetrics`, though that one is private).
I'm also not really familiar with `wxArtProvider`, so I don't know what will be best/easiest for the user. And would `wxArtProvider::GetSizeHint(..)` need the same?

**Comment by vadz** [comment]
Thanks, let's add `wxWindow` parameter for now and see if it is enough (here and for `GetSizeHint()` too, of course).

I still suspect having a function returning the size in DIPs would be useful, but it can be added later.

**Comment by vadz** [comment]
Another problem is that the `size` parameter of `wxArtProvider::GetBitmapBundle()` is supposed to be in DIPs (and nothing else would make sense for a bundle), but all the other sizes must be in logical pixels. I wonder what could we do to reduce confusion here. We should probably at least name these parameters differently. But we still won't be able to pass the result of `GetSizeHint()` as the size to `GetBitmapBundle()`, so we need `GetSizeHintInDIPs()` right now.
