### ISSUE TITLE
Revert or at least document regressions in wxImageList behaviour

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22021]
After the recent changes in 838e45fd9b58392df0936cfb2bfd19bf95d1645d and 8f08233a1322283958b3097099f03bbc09b796b4, images with alpha are not shown correctly when using `wxImageList` created with default value of `mask = true`, see [this thread](https://groups.google.com/g/wx-users/c/tv2diRGSxig/m/UHdI-eVdFQAJ). Ideal would be to restore the old behaviour, but if this is impossible we should at least assert or `wxLogDebug()` the explanation to prevent people from losing their time trying to understand why things don't work any longer.

Also see previous [discussion here](https://github.com/wxWidgets/wxWidgets/commit/838e45fd9b58392df0936cfb2bfd19bf95d1645d).

cc @a-wi

**Comment by vadz** [comment]
@a-wi Just to avoid any duplication of work, I wanted to say that I'm going to fix this by converting mask to alpha in `wxImageList` rather than ignoring it entirely. Unfortunately I don't have a test case for the original bug (#19036), so I can only hope that this doesn't rebreak it again, but I'm relatively confident that it shouldn't.

Please let me know if you're, by chance, already working on this, but if not I'll try to do it myself soon as I'd really like to fix this before 3.1.6. Thanks!

**Comment by a-wi** [comment]
At the moment I don't work on this so please proceed.
