### ISSUE TITLE
wxFIleCtrl displays its content in wrong order

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22054]
`wxGenericFileCtrl` uses `wxStrcmp()` to compare names of folders and files for sorting its content:
https://github.com/wxWidgets/wxWidgets/blob/3cc4ef5f7727f3d0c0d74739a7bcdb4065fda137/src/generic/filectrlg.cpp#L49-L64

This means that sorting is case-sensitive, i.e., all uppercase letters sort before all lowercase letters, e.g., 'Z' goes before 'a'. Additionally, strings containing local characters are not sorted properly. This can be reproduced in the widgets sample:
![wxfilectrl-order](https://user-images.githubusercontent.com/12495521/150857556-9d1b2f74-de8f-4b29-85c1-726f64e7cb5c.png)
At least on MS Windows, the correct order (as displayed by File Explorer or Total Commander) is this:
```
a1.txt
A2.txt
Čeněk.txt
z1.txt
Z2.txt
```

I believe that `wxGenericFileCtrl` should use a compare function which is (a) case-insensitive and (b) takes locale into account, such as `wxUILocale::CompareStrings()`. Better yet, the control content should be sorted in the natural order, as AFAIK file managers usually do, i.e., use `wxNaturalStringSortAscending()` as the compare function.

**Comment by Cahlien** [comment]
What operating systems use case-sensitive sorting for filenames by default?
