### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by skeetor** [wxWidgets/wxWidgets#22060]
I'm currently developing an extension which I would hope to see integrated into wxWidgets later on. However, since this is not guaranteed, I created a separate project to develop it until it gets to a releasable state. When I create this on github project I have to choose a license and I wanted to use the wxWidgets license from the start, in order to make it easier to integrate later on. However, the wxWidgets license is not included in the list, so I selected GPL3.0 for now.
Now I was wondering if the wxWidget license will be applied to be included in the github licenses or which I license I should select. Or can I double license it by creating a license file on my own, referencing GPL3.0 and wxWidget license both?

The categories of the issues may not really be appropriate for this question, as it is neither a bug, nor a feature, nor an enhancement, so maybe it would be a good idea to also have a general category. :)

**Comment by vadz** [comment]
You can definitely relicense your own code under any licence you want at any time (you can't do it without agreement of the other contributors, but as long as you're the only one, it's not a problem).

Please post any further questions to the mailing list, this is not really the best place to discss stuff like this. TIA!
