### ISSUE TITLE
Handle or ignore other Pango font variants in wxWindowGTK::GTKApplyWidgetStyle()

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22064]
Using GTK 3.24.31 I get
```
src/gtk/window.cpp: In member function ‘void wxWindow::GTKApplyWidgetStyle(bool)’:
src/gtk/window.cpp:5595:28: warning: enumeration value ‘PANGO_VARIANT_ALL_SMALL_CAPS’ not handled in switch [-Wswitch]
  switch (pango_font_description_get_variant(pfd))
         ^
src/gtk/window.cpp:5595:28: warning: enumeration value ‘PANGO_VARIANT_PETITE_CAPS’ not handled in switch [-Wswitch]
src/gtk/window.cpp:5595:28: warning: enumeration value ‘PANGO_VARIANT_ALL_PETITE_CAPS’ not handled in switch [-Wswitch]
src/gtk/window.cpp:5595:28: warning: enumeration value ‘PANGO_VARIANT_UNICASE’ not handled in switch [-Wswitch]
src/gtk/window.cpp:5595:28: warning: enumeration value ‘PANGO_VARIANT_TITLE_CAPS’ not handled in switch [-Wswitch]
```
when building wxGTK.

It would, of course, be trivial to just suppress the warning, but I wonder if we should handle these variants too, somehow. Would somebody already know how are those called in GTK CSS terms by chance?

**Comment by swt2c** [comment]
The values seem to be here: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkcssenumvalue.c#L1015

I don't see any of them used in GTK 3.24.31 other than small-caps, so it seems perhaps they were defined in GTK3-era Pango before they actually got used in GTK 3.

**Comment by vadz** [comment]
Thanks! I'll add cases handling them just in case it can be useful, it's not like it costs much to have them anyhow.
