### ISSUE TITLE
[wxMSW] ribbon sample application crashes when toolbar is collapsed

### ISSUE THREAD

**Issue by HWiman-ICONIC** [wxWidgets/wxWidgets#22081]
**Describe the bug**
**I see now that the code I refer to further done has been changed since 3.1.5. I assume that this indicates that the issue may be solved already. I´ll test. Ignore this issue for now. My bad, did not find any relevant issue, so thought it was new.** Ribbon sample application crashes when clicking a collapsed toolbar item on Windows 10 wxMSW.

**Expected vs observed behaviour**
Clicking arrow on collapsed tool should show expanded buttons for that tool. Instead, application crashes with nullptr exception

**Patch or snippet allowing to reproduce the problem**

Found that buttonbar.cpp line 936 `wxRibbonBar* const ribbon = GetAncestorRibbonBar();` returns `ribbon==nullptr` if and only if tool is collapsed. `ribbon` is then used on line 947 `base->GetBitmaps(ribbon,..` causing nullptr exception. Did not get any further than that.

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. Run wx/samples/ribbon application
2. Reduce the window until the rightmost "Panel with sizer" tool is collapsed
![ribbon01](https://user-images.githubusercontent.com/78019492/152118144-99387e80-0a13-4f38-8616-2aaa169496eb.jpg)
 
3. Click the arrow to get expanded buttons
4. -> Crash

**Platform and version information**
 - wxWidgets version you use: 3.1.5 (from vcpkg 3.1.5#7)
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0.19041

**Comment by vadz** [comment]
Yes, I think this could have been fixed by 706ab2c300 (Fix crash when using popup window for wxRibbon button bars, 2021-09-05), see #19249.
