### ISSUE TITLE
dll suffix change between 3.1.3 and 3.1.4 (and 3.1.5)

### ISSUE THREAD

**Issue by hmaarrfk** [wxWidgets/wxWidgets#22086]
**Describe the problem**
I've successfully build wxWidgets on Windows 64 bit in the past for conda-forge.

I've build version 3.1.3 with the configuration shown in
https://github.com/conda-forge/wxwidgets-feedstock/blob/de27d822bd963f6db88613be39261da6b7cd1abb/recipe/bld.bat

However, upon trying to upgrade to 3.1.4 (and subsequently to 3.1.5) i noticed the DLL names change from being suffixed with x64_custom.dll to dropping the `x64` qualifier.

I'm afraid this will cause issues with people that depend on consistent names.

I'm also afraid that somehow I am accidentally building the 32 bit version (which would be very problematic).

I've attached the build logs for 
* 3.1.3 successful: [3.1.3_log.txt](https://github.com/wxWidgets/wxWidgets/files/7991319/3.1.3_log.txt)
* 3.1.5 attempt: [3.1.5_log.txt](https://github.com/wxWidgets/wxWidgets/files/7991320/3.1.5_log.txt)

Thank you for your help.

**Comment by PBfordev** [comment]
> upon trying to upgrade to 3.1.4 (and subsequently to 3.1.5) i noticed the DLL names change from being suffixed with x64_custom.dll to dropping the `x64` qualifier.

I think it was changed [here](https://github.com/wxWidgets/wxWidgets/pull/1735/files#diff-f40a855f70c14cf41f3d5dfaffdf9575cdaaa6882bd34d5e6c67dfa3aaa5aec9L150-R174), to make the library names consistent across compilers and build systems.

 
> I'm also afraid that somehow I am accidentally building the 32 bit version (which would be very problematic).

You are setting the architecture via CMake generator platform, see the log. So how could that happen?

**Comment by hmaarrfk** [comment]
> You are setting the architecture via CMake generator platform, see the log. So how could that happen?

That was my general belief, but I've seen some very crazy CMake files before that almost ignore all the standards.

I now see that I must specify `wxBUILD_VENDOR` not `wxVENDOR` as I was trying to specify. for backward compatibility. Or..... do something else that would restrict people from building with 3.1.3 and using 3.1.5 and keep the new defaults for 3.1.5.

Thank you for your help!
