### ISSUE TITLE
Custom StaticText on StatusBar

### ISSUE THREAD

**Issue by nlogozzo** [wxWidgets/wxWidgets#22084]
Hi, 
I'm implementing an in-house dark mode for my application. I need to set the StatusBar's text color to white when the background is dark. Settings the StatusBar's ForegroundColor has no effect, therefore I am wondering if there is a way I can add a StaticText to the StatusBar in which I will be able to then change the StaticText's Foreground to white. I tried StatusBar->AddChild(new wxStaticText...) but i get an error saying AddChild can't be called twice, there I'm stuck on how to accomplish this.
Thanks in advanced for any help.

**Comment by vadz** [comment]
Please use mailing list, forum or IRC for support requests.

In this particular case, please look at the statbar sample which shows how to add a control to the status bar.

**Comment by nlogozzo** [comment]
Ah ok, thank you!

**Comment by nlogozzo** [comment]
Also, maybe allow for GitHub discussions?
