### ISSUE TITLE
wxTextEntryDialog messing up threads

### ISSUE THREAD

**Issue by Felipe-Ribas** [wxWidgets/wxWidgets#22082]
I'm using Code::Blocks 20.03-r11983 64bits with wxWidgets 3.1.5 and MingW x86_64-8.1.0-posix on a Windows 10 64bits and I realized that only by adding a wxTextEntryDialog component in my project, it won't terminate the process anymore when closing the main windows as before. No code added whatsoever, just by simply placing the component on my project, I can still compile and run it, but when i try to finish the application, it closes but some task remains on the background and I have to forcely close it on the IDE "Abort" button. If I simply delete the component, it works normally again. 

As there is absolutely no changes in code, I wouldn't see a necessity of posting here anything, but of course I tested adding the component and just removing the initialization line:

`TextEntryDialog1 = new wxTextEntryDialog(this, wxEmptyString, _("Input Text"), wxEmptyString, wxOK|wxCANCEL|wxCENTRE|wxWS_EX_VALIDATE_RECURSIVELY, wxDefaultPosition);`

and it does work as without the component. It seems the simple initialization of the component is starting some kind of background task that won't be finished on app close action. Other dialogs work well (wxFileDialog, wxMessageDialog and so on...).

I tried start with a debugger active and pausing it after the main window is finished to see where it is, but it's trapped somewhere inside ntdll.dll or kernel32.dll calling some zwterminatethread functions in loop and apparently trying to terminate the process unsuccessfully.

**Comment by vadz** [comment]
If you create a new top level window, you must destroy it before the program exits by default. It's pretty unusual to create a modal dialog on the heap, usually they're allocated on the stack, but you can do it -- however in this case you need to destroy it.

IOW this is just a bug in your code, there is nothing wrong with `wxTextEntryDialog` and this has nothing to do with threads.

**Comment by Felipe-Ribas** [comment]
I'm not sure if I get what you mean. I did not even fire that window at all, just the object was created automatically by wxwidgets on it's creation. I never called, used nor showed it on the screen. The simple creation of the element causes the problem. And as I said, why dont the other similar components cause the same behavior?

**Comment by vadz** [comment]
The program exits, by default, when the last top level window is destroyed. You're creating a TLW (even if you don't _show_ it), which explains why it doesn't exit. Just don't do this.

The other non-native dialogs will result in the same behaviour. Native dialogs are different because they don't actually have any valid window before they're shown.

**Comment by Felipe-Ribas** [comment]
I honestly don't get it. How is the wxTextEntryDialog different from wxFileDialog, when they are both TLW, derived from the same classes? I already had multiple wxDialogs (fileDialog, messageDialog) which all have the exact same heritage according to documentation and are TLW, but this didn't happen before I added the wxTextEntryDialog. And then again, I did not create anything manually nor placed on the heap, I just used the GUI to add the component and nothing more, didn't touch any code whatsoever. Still, just by placing the component on the frame, causes the issue.

You mean I should manually destroy the wxTextEntryDialog unlike all other dialogs that I already had?

**Comment by vadz** [comment]
> I honestly don't get it. How is the wxTextEntryDialog different from wxFileDialog, when they are both TLW, derived from the same classes?

The latter is a native dialog, the former one is not, see above.

> I already had multiple wxDialogs (fileDialog, messageDialog) which all have the exact same heritage according to documentation and are TLW, but this didn't happen before I added the wxTextEntryDialog. And then again, I did not create anything manually nor placed on the heap, I just used the GUI to add the component and nothing more, didn't touch any code whatsoever. Still, just by placing the component on the frame, causes the issue.

If your tool adds code creating the dialog on the heap, it counts exactly the same as creating the dialog on the heap "manually", whatever this means. You're responsible for whatever ends up in your code, whether you write it yourself or generate it using a tool.
 
> You mean I should manually destroy the wxTextEntryDialog unlike all other dialogs that I already had?

I mean that you shouldn't be doing this (creating modal dialogs on the heap) in the first place, but if you absolutely want to do it, you need to destroy them. And this applies to all dialogs, the fact that this doesn't seem to result in visible problems for the native dialogs doesn't mean that doing this is right.

Please post to the mailing list if you have further questions.
