### ISSUE TITLE
wx-config returns bad lib flags when compiled as static

### ISSUE THREAD

**Issue by MrSurly** [wxWidgets/wxWidgets#22098]
**Describe the problem**

Building:
```
git clone https://github.com/wxWidgets/wxWidgets.git -b v3.1.5
cd wxWidgets
git submodule update --init --recursive
mkdir xxx; cd xxx
cmake .. -DwxBUILD_SHARED=OFF  -DCMAKE_INSTALL_PREFIX=`pwd`/install
make
make install
```
Now issue:
```
cd install/bin
./wx-config --cxxflags --libs
```

Resultant output:
```
-I/tmp/wxWidgets/xxx/install/lib/wx/include/gtk3-unicode-static-3.1 -I/tmp/wxWidgets/xxx/install/include/wx-3.1 -DWXUSINGDLL -D__WXGTK3__ -D__WXGTK__ -pthread
-L/tmp/wxWidgets/xxx/install/lib -pthread /tmp/wxWidgets/xxx/install/lib/libwx_gtk3u_xrc-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_gtk3u_qa-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_baseu_net-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_gtk3u_html-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_gtk3u_core-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_baseu_xml-3.1.a /tmp/wxWidgets/xxx/install/lib/libwx_baseu-3.1.a gtk-3 gdk-3 pangocairo-1.0 pango-1.0 harfbuzz atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 libSM.so libICE.so libX11.so libXext.so libXtst.so -lwx_gtk3u_core-3.1 gtk-3 gdk-3 pangocairo-1.0 pango-1.0 harfbuzz atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 libSM.so libICE.so libX11.so libXext.so libXtst.so libjpeg.so libpng.so libz.so libtiff.so libSDL2main.a libSDL2.so gtk-3 gdk-3 pangocairo-1.0 pango-1.0 harfbuzz atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 libSM.so libICE.so libX11.so libXext.so libXtst.so -lwx_baseu-3.1 libexpat.so gtk-3 gdk-3 pangocairo-1.0 pango-1.0 harfbuzz atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 libSM.so libICE.so libX11.so libXext.so libXtst.so libz.so -lwxregexu-3.1 libc.so dl
```
As seen above, it spits out a bunch full filenames for system libraries but without any `-l` prefix.  For example `libz.so` instead of `-lz`.

When `wx-config` used to build a compile or link command (``gcc -c source.c `wx-config --cxxflags --libs` -o source.o``) GCC will emit an error that the file is not found, because it believes the bare filenames are input files.

**Platform and version information**
 - wxWidgets version you use: 3.1.5
 - wxWidgets port you use: wxGTK
 - OS and its version: Ubuntu Linux 21.10
 - Compiler being used: gcc 11.2.0

**Comment by MaartenBent** [comment]
This has most likely been fixed in the latest master, see the history of [config.cmake](https://github.com/wxWidgets/wxWidgets/commits/master/build/cmake/config.cmake). Can you try that version?

**Comment by MrSurly** [comment]
> This has most likely been fixed in the latest master, see the history of [config.cmake](https://github.com/wxWidgets/wxWidgets/commits/master/build/cmake/config.cmake). Can you try that version?

Indeed it has. Thank you.
