### ISSUE TITLE
wxScrolled display issues on wxGTK

### ISSUE THREAD

**Issue by Jorilx** [wxWidgets/wxWidgets#22093]
(Opening an issue to track a problem raised [here](https://forums.wxwidgets.org/viewtopic.php?t=48372). Please see also the related wxPython issue [here](https://github.com/wxWidgets/Phoenix/issues/1173))

> On GTK+3, scrolled windows have two following issues:
> 
> 1. The scrollbars don't scroll up to the end leaving some space;
> 2. The whole window flickers if any OnDraw or paint callback is present (which is I guess stemmed from window contents being repainted over the scrollbars).
> 
> Here is a demonstration of scrolled window sample:

![Qj1LQDa](https://user-images.githubusercontent.com/600767/152562787-8e9e328b-9377-4026-86b3-f97795ce016e.gif)

**Platform and version information**
 - wxWidgets: 3.1.4
 - wxWidgets port: wxGTK with GTK 3.24.5
 - OS and its version: Debian 10

**Comment by paulcor** [comment]
Closed via c3b232dcfd25107903e0447b36794aab9242c99f
