### ISSUE TITLE
wxAuiTabArt and wxAuiDockArt documentation still says protected members are wxBitmap

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#22106]
Interface of wxAuiTabArt and wxAuiDockArt has not been updated to reflect the change from wxBitmap to wxBitmapBundle.

Platform: current master

[wxAuiDockArt documentation](https://docs.wxwidgets.org/trunk/classwx_aui_default_dock_art.html)

**Comment by vadz** [comment]
Thanks, I'll fix this.

I have to wonder why do we document these protected members at all though, is it really useful to access them directly?

**Comment by wh11204** [comment]
We access them directly from DrawTab() in two derived classes in Code::Blocks source (src\src\notebookstyles.cpp).
