### ISSUE TITLE
GTK3: wxDC SetAxisOrientation(true, true) Reverses DrawText()

### ISSUE THREAD

**Issue by butcherg** [wxWidgets/wxWidgets#22113]
**Describe the bug**
When I set SetAxisOrientation(true, true) in a wxDC and subsequently call DrawText(), the text is rendered backward: 
![backward-text](https://user-images.githubusercontent.com/379052/153254628-be42d202-9481-47d4-9db9-4182b744f448.png)

**Expected vs observed behaviour**
Same code in wxMSW works as expected, text renders normally

**Patch or snippet allowing to reproduce the problem**
```
void render(wxDC& dc)
	{
		margin = 30;
		int h = dc.GetSize().GetHeight();
		int w = dc.GetSize().GetWidth();
		dc.Clear();
		dc.SetDeviceOrigin( margin, h-margin );
		dc.SetAxisOrientation(true, true); //make y axis go from bottom up
		dc.DrawLine(0,0,w,0);
		dc.DrawLine(0,0,0,h);
		dc.DrawText("12345678",100,100);
	}
```

 - wxWidgets version  3.1.4, 3.1.5]
 - wxWidgets port you use: wxGTK
 - OS and its version: Windows 11, Ubuntu 22.04
 - GTK version: 3

**Comment by vadz** [comment]
I agree that axis orientation shouldn't affect text.

I guess we could reset the axis orientation to the default before drawing text and restoring it afterwards if nothing else works.
