### ISSUE TITLE
Font half size when using Direct2D with non-window based wxDC under HiDPI 

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#22130]
When using the Direct2D renderer for `wxDC`s (under a HiPDI environment, where the app is DPI aware), font drawing is half the size it should be if using it with a non-window based `wxDC`. In other words, Direct2D with `wxPaint` looks OK, but if you use Direct2D with a `wxMemoryDC` then the font is tiny.  Interestingly, it seems to only be a font issue--shape drawing is fine.

**To Reproduce**
On a HiDPI Windows system:

1. Open the drawing sample and run it.
2. Select `Screen->Text` screen
3. Select `Drawing->Use GDI+`.
4. Save it as a bitmap (`Drawing->Save`) and note that the bitmap looks like the screen.
5. Select `Drawing->Use Direct2D` and save as a bitmap again. It should look the same.
6. Now, change the sample to be *DPI aware*.
    - In Visual Studio, `Project->drawing Properties->Manifest Tool->Input and Output`. Set "DPI Aware" to "High DPI Aware" and rebuild.
7. Repeat steps 2-5.

Note how the bitmap saved when (DPI-aware) Direct2D was in use has its text half the size as the GDI+ image. If you try this with other screens the problem doesn't happen with shapes and whatnot; it appears to be a font size issue.

Digging into the code, I think it has do with the `wxGraphicsContext` created from `m_renderer->CreateContext()`. If the `wxDC` passed into this has a window related to it (e.g., a `wxPaintDC`), then the `wxGraphicsContext` will be aware of the DPI. However, if a `wxMemoryDC` is passed, then it doesn't know what the DPI is and falls back to the default 96.  I can see that the context created from a `wxMemoryDC` reports 96 when I call `GetDPI()`. However, I get 192 when I call `GetDPI()` with the context created from a `wxPaintDC`.  I'm guessing this discrepancy is the root cause.

**Platform and version information**
 - wxWidgets 3.1.6 (fetched on 2022-02-14)
 - Windows 10 (x64)
 - HiDPI display required (I'm using a Surface laptop)

**Comment by Kumazuma** [comment]
creataion of wxGraphicsFont for d2d
```cpp
// src/msw/graphicsd2d.cpp:5112
wxGraphicsFont wxD2DRenderer::CreateFont(
    double sizeInPixels, const wxString& facename,
    int flags,
    const wxColour& col)
{
    // Use the same DPI as wxFont will use in SetPixelSize, so these cancel
    // each other out and we are left with the actual pixel size.
    ScreenHDC hdc;
    wxRealPoint dpi(::GetDeviceCaps(hdc, LOGPIXELSX),
                    ::GetDeviceCaps(hdc, LOGPIXELSY));

    return CreateFontAtDPI(
        wxFontInfo(wxSize(sizeInPixels, sizeInPixels)).AllFlags(flags).FaceName(facename),
        dpi, col);
}
```

so... when dpi is not specific by user, dpi is set using screendc.

in same process on GDI+
```cpp
// src/msw/graphics.cpp:2858
wxGraphicsFont
wxGDIPlusRenderer::CreateFont( const wxFont &font,
                               const wxColour &col )
{
    return CreateFontAtDPI(font, wxRealPoint(), col);
}
```

so I suggest
```cpp
wxGraphicsFont wxD2DRenderer::CreateFont(
    double sizeInPixels, const wxString& facename,
    int flags,
    const wxColour& col)
{
    return CreateFontAtDPI(
        wxFontInfo(wxSize(sizeInPixels, sizeInPixels)).AllFlags(flags).FaceName(facename),
        wxRealPoint(), col);
}
```

**Comment by Blake-Madden** [comment]
No, didn't seem to help.  `wxGraphicsContext::CreateFont` (graphicscmn.cpp, line 952) still relies on `GetDPI`, which incorrectly reports 96 (not 192).  The lack of a window in the graphics context causes `GetDPI` to be problem.

**Comment by MaartenBent** [comment]
As a workaround/fix, you can associate the window with the `wxMemoryDC`. In the drawing sample:  `mdc.GetImpl()->SetWindow(this);`

**Comment by Blake-Madden** [comment]
> mdc.GetImpl()->SetWindow(this);

That totally works! Thank you!

**Comment by vadz** [comment]
I don't see any differences in the text size between the 3 bitmaps saved while running with 200% DPI scaling, see:

1. GDI: <br> ![gdi](https://user-images.githubusercontent.com/146917/160216119-bc467aa5-f17a-40ee-986c-1891d4c75b6a.png)
3. GDI+: <br> ![gdiplus](https://user-images.githubusercontent.com/146917/160216133-904f537d-b267-4013-89cb-e87a10485188.png)
4. Direct2D: <br> ![d2d](https://user-images.githubusercontent.com/146917/160216143-4252a615-9d50-45e7-8d2d-b42d3ce923fb.png)

I do see that the text is smaller than the much larger (and overlapping because of it...) text shown on screen. But normally I would say that this ought to be fixed with
```diff
diff --git a/samples/drawing/drawing.cpp b/samples/drawing/drawing.cpp
index 55e8e62c52..717f880560 100644
--- a/samples/drawing/drawing.cpp
+++ b/samples/drawing/drawing.cpp
@@ -2535,7 +2535,8 @@ void MyFrame::OnSave(wxCommandEvent& WXUNUSED(event))
         else
 #endif // wxUSE_POSTSCRIPT
         {
-            wxBitmap bmp(width, height);
+            wxBitmap bmp;
+            bmp.CreateWithDIPSize(wxSize(width, height), GetDPIScaleFactor());
             wxMemoryDC mdc(bmp);
             mdc.SetBackground(*wxWHITE_BRUSH);
             mdc.Clear();
```
(the use of DIP size is due to the fact that nothing is being scaled by DPI in this sample right now, so all pixels are actually DPI-independent in it under MSW) but this doesn't work neither right now because the bitmap scale factor is ignored by `wxMemoryDC` under MSW. I've tried fixing this in #22234 and with it the saved bitmap looks roughly like this in all 3 cases:

![fixed](https://user-images.githubusercontent.com/146917/160217717-b2b35ae6-cdae-41d4-8df1-7b5ad9ed54cf.png)

which is ugly but corresponds to the picture actually shown on the screen.

**Comment by vadz** [comment]
> I don't see any differences in the text size between the 3 bitmaps saved while running with 200% DPI scaling

Correction: as discussed in #22234, I do see the problem when actually running in 200% DPI and not just moving the window to a monitor using 200% DPI (while the main display still uses 100%).

**Comment by Blake-Madden** [comment]
Verified in my personal project as well.  Thanks for the fix!
