### ISSUE TITLE
macOS: wxToggleButton style is unexpected

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#22140]
**Describe the bug**
When creating a wxToggleButton on macOS, the style is standard push button style. This isn't an appropriate use of the push button style on macOS. That style is used for a momentary push button, not a toggle button. A more appropriate use would be square style with on/off type which would also match the wx documentation.

**Expected vs observed behaviour**
Using standard push button style for a toggle button is unexpected and not following the Mac human interface guidelines.

**Patch or snippet allowing to reproduce the problem**

Create an wxToggleButton on macOS and observe.

A patch to create a more expected toggle button in Cocoa would be to use these flags on the backing button (written in obj-c):

 [_button setButtonType:NSButtonTypePushOnPushOff];
 [_button setBezelStyle:NSBezelStyleShadowlessSquare];

**Platform and version information**
 - wxWidgets version you use: 3.1.5
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 11.6.4 (20G417)

Note: I do apologize for all the recent macOS bugs; I hope to have some time to submit some PRs to help improve the project! Keep up the great work!

**Comment by vadz** [comment]
We already set the correct button type, see https://github.com/wxWidgets/wxWidgets/blob/5cc8e34dfbb6dff37a97013e39ab7c324a287317/src/osx/cocoa/tglbtn.mm#L50 but only set the bezel to `NSShadowlessSquareBezelStyle` for the buttons with `wxBORDER_NONE` style. Can you please check if using this style results in the expected appearance? You should be able to check this easily in the widgets sample, it has menu commands for changing the button style.

**Comment by willco007** [comment]
Sorry, I should have been a bit more clear. It does work, and it also changes style correctly if you change the border type. The issue is the _default_ border type of `wxToggleButton` is normal push button while the default should be shadowless square. Using normal push button style as a toggle button on macOS is not expected usage.

**Comment by vadz** [comment]
So should we always use this bezel style for them, irrespectively of the border specified by the user? Can any other bezel make sense in combination with this button type?

Thanks!

**Comment by willco007** [comment]
No, there are a couple of other styles that do make sense for toggle buttons so keeping customization is useful. Thank you for entertaining this bug report!

**Comment by vadz** [comment]
I'm not sure which customizations make sense and, to be honest, the new look doesn't seem great to me, but then I couldn't find any toggle buttons in the macOS UI (only iOS-style on/off switches, that we really should have in wx...), so I don't really know how are they supposed to look like. But here is how it looks for me in the widgets sample after my changes: off

![toggle1](https://user-images.githubusercontent.com/146917/154853545-acfe2394-b9f6-410d-afdb-7ab79f00deb0.png)

and on:

![toggle2](https://user-images.githubusercontent.com/146917/154853554-9e3428e2-63c0-47d1-bb26-ab89eb69fd35.png)

Could you please test [my commit](https://github.com/wxWidgets/wxWidgets/commit/50794eda7d72e4fddd396b37e9cc45ea29bff833) and let me know if you can improve it.

**Comment by willco007** [comment]
I'm away from my computer today and on holiday tomorrow. I'll look at it first thing Tuesday (add back in styles that make sense). I do agree the default style is ugly. 🙂 Apple rarely uses this button and hasn't changed it in years, but it looks correct.

**Comment by vadz** [comment]
@willco007 FYI, I've created a PR with the commit above and will merge it if there are no objections.
