### ISSUE TITLE
Preferences Sample program throws exception on macOS

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#22154]
**Describe the bug**
When running the Preferences example app found in the Samples folder on macOS, the Sample program throws an exception due to an unloaded General icon image.

**Expected vs observed behaviour**
General preferences icon image is loaded when using the `Kind_General` preference type. 

**Patch or snippet allowing to reproduce the problem**

Run the Preferences Sample application and select the Preferences menu item to show the prefs dialog

<img width="873" alt="Screen Shot 2022-02-23 at 9 34 54 AM" src="https://user-images.githubusercontent.com/4294739/155375910-e7e3d7be-7b08-4954-b805-3a980565e9f7.png">

**Platform and version information**
 - wxWidgets version you use: [master] as of 2/22/22
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 11.6.4 (20G417)

**Comment by vadz** [comment]
FWIW this is fixed by #22187 and will be closed when it is merged.

**Comment by vadz** [comment]
Should be fixed now that this PR was merged, thanks again for reporting!
