### ISSUE TITLE
No mouse events in wxComboBox/macOS

### ISSUE THREAD

**Issue by dkulp** [wxWidgets/wxWidgets#22179]
**Describe the bug**
There doesn't seem to be any way to get the various mouse events from a wxComboBox on macOS.  In particular, we need to be able to override the OS provided context menu on a right click (wxContextMenuEvent) and the event is never sent.   We also tried a  wxEVT_RIGHT_DOWN and that doesn't arrive.   LEFT_DOWN doesn't either.  

**Expected vs observed behaviour**
We would expect to somehow get an event.   Note: with wxSpinCtrl, we only get the event if the mouse is over the up/down arrows, not the text field.  We'd be OK with as well, although getting the SpinCtrl fixed would also be great.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 12.2

**Comment by vadz** [comment]
Generally speaking wx doesn't guarantee (because it can't) that you will always get all the low level key/mouse events for the native controls. I don't know if it's possible to get them for this particular one, but the real problem is that you don't get `wxContextMenuEvent` -- this one _should_ be generated.

Unfortunately, as usual, I can't help much with wxOSX that I don't know well, but the thing to fix would be the higher-level event generation (if this means generating low-level events too, so be it, but this isn't necessarily the goal here).

**Comment by dkulp** [comment]
Agreed...  I was just trying to get the mouse events to see if there was some workaround I could use for the ContextMenu events now working.

**Comment by vadz** [comment]
FWIW it looks that in wxOSX, specifically, we do need to get the mouse events to generate `wxContextMenuEvent`s. And there is some code for dealing with them already here: https://github.com/wxWidgets/wxWidgets/blob/e43895e5317a1e82e295788264553d9839190337/src/osx/cocoa/combobox.mm#L219-L241

so we need to debug it to understand why it doesn't work. I'd probably start with checking whether `wxNSComboBoxControl::mouseEvent()` itself is called in the first place.

**Comment by dkulp** [comment]
This seems to work for the context menu case:
```
diff --git a/src/osx/cocoa/textctrl.mm b/src/osx/cocoa/textctrl.mm
index d756dc09d4..54ba1f3fbb 100644
--- a/src/osx/cocoa/textctrl.mm
+++ b/src/osx/cocoa/textctrl.mm
@@ -374,6 +374,14 @@ NSView* wxMacEditHelper::ms_viewCurrentlyEdited = nil;
         [super flagsChanged:event];
 }

+- (void) rightMouseDown:(NSEvent*) event
+{
+    wxWidgetCocoaImpl* impl = (wxWidgetCocoaImpl* ) wxWidgetImpl::FindFromWXWidget( (WXWidget) [self delegate] );
+    if ( impl == NULL || !impl->DoHandleMouseEvent( event ) )
+        [super rightMouseDown:event];
+}
+
+
 - (void) insertText:(id) str
 {
     // We should never generate char events for the text being inserted
@@ -412,6 +420,7 @@ NSView* wxMacEditHelper::ms_viewCurrentlyEdited = nil;
 }


+
 @end

 @implementation wxNSTextView
```

**Comment by dkulp** [comment]
The issue is that the wxComboBox on cocoa has a separate wxNSTextFieldEditor object set as it's text editor.  However, that object is NOT an wx***** clas at all.   It directly extends NSTextView and doesn't add any of the normal wxWidgets hooks.   In only has specific overrides for the couple of key handling events it needs.   The above at least adds the rightMouseDown stuff, but I'm not sure which other events it SHOULD get.    There are a bunch in wxOSXCocoaClassAddWXMethods that likely could be forwarded into the wxComboBox, but not really sure.

**Comment by vadz** [comment]
@csomor Could you please check if the solution above is acceptable?

BTW, please ignore my comment about `wxNSComboBoxControl::mouseEvent()` above, apparently it's just used to execute some code before/after the local event loop (is there really no way to intercept in a more foolproof way, e.g. what if the combobox is opened from keyboard? or is this really impossible under Mac?) and doesn't help with the mouse events dispatching -- although, presumably, it could be used for this too?

**Comment by csomor** [comment]
> @csomor Could you please check if the solution above is acceptable?

I'll look at it

**Comment by vadz** [comment]
I'd like to merge this before 3.1.6 to get some testing for it, so I'll apply the patch above if there are no objections or better solutions.

**Comment by vadz** [comment]
Still no response from Stefan, unfortunately, so I've merged this myself -- even if I'm still not confident that it is the right thing to do, at least I see now that we already the same thing for the key events, so I guess it can't be too bad. And it does fix the problem with the combobox.

Thanks for the patch!
