### ISSUE TITLE
MinGW build fails in webview_edge.cpp

### ISSUE THREAD

**Issue by ancwrd1** [wxWidgets/wxWidgets#22170]
**Describe the problem**

CMake mingw build fails with the following error:

```
/wxWidgets/src/msw/webview_edge.cpp: In member function 'virtual wxVersionInfo wxWebViewFactoryEdge::GetVersionInfo()':
/wxWidgets/src/msw/webview_edge.cpp:992:35: error: conversion from 'wxCoTaskMemPtr<wchar_t>' to non-scalar type 'wxString' requested
  992 |             wxString versionStr = nativeVersionStr;
      |                                   ^~~~~~~~~~~~~~~~

```

Configuration command:

```
cmake -DCMAKE_INSTALL_PREFIX=$target/target \
      -DCMAKE_SYSTEM_NAME=Windows \
      -DCMAKE_CXX_STANDARD=14 \
      -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
      -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
      -DCMAKE_BUILD_TYPE=Release \
      -DwxBUILD_COMPATIBILITY=3.1 \
      -DwxBUILD_MONOLITHIC=ON \
      -DwxBUILD_USE_STATIC_RUNTIME=ON \
      -DwxBUILD_OPTIMISE=ON \
      -DwxBUILD_SHARED=OFF \
      -DwxBUILD_DEBUG_LEVEL=0 \
      -DwxUSE_STL=ON \
      -DwxUSE_WEBVIEW=ON \
      -DwxUSE_WEBVIEW_EDGE=ON \
      -DwxUSE_HTML=ON \
      -DwxUSE_LIBMSPACK=OFF \
      -DwxUSE_LOG=OFF \
      -DwxUSE_LOGGUI=OFF \
      -DwxUSE_LOGWINDOW=OFF \
      -DwxUSE_LOG_DIALOG=OFF \
      -DwxUSE_DOC_VIEW_ARCHITECTURE=OFF \
      -DwxUSE_HELP=OFF \
      -DwxUSE_MS_HTML_HELP=OFF \
      -DwxUSE_WXHTML_HELP=OFF \
      -DwxUSE_AUI=OFF \
      -DwxUSE_PROPGRID=OFF \
      -DwxUSE_RIBBON=OFF \
      -DwxUSE_STC=OFF \
      -DwxUSE_MDI=OFF \
      -DwxUSE_MDI_ARCHITECTURE=OFF \
      -DwxUSE_MEDIACTRL=OFF \
      -DwxUSE_RICHTEXT=OFF \
      -DwxUSE_POSTSCRIPT=OFF \
      -DwxUSE_AFM_FOR_POSTSCRIPT=OFF \
      -DwxUSE_PRINTING_ARCHITECTURE=OFF \
      -G Ninja \
      ../wxWidgets
```

**Platform and version information**
 - wxWidgets version you use: master branch
 - wxWidgets port you use: wxMSW
 - OS and its version: Linux openSUSE Tumbleweed
 - Compiler being used: MinGW GCC 9.2 (cross)

**Comment by PBfordev** [comment]
I can reproduce the issue with GCC 10.2 from MSYS2 package mingw-w64-x86_64-gcc compiling directly on MSW. It can be fixed doing what is done in similar cases in other places in webview_edge source, i.e.:
```diff
diff --git a/src/msw/webview_edge.cpp b/src/msw/webview_edge.cpp
index 7afc2189ec..f23b7075c5 100644
--- a/src/msw/webview_edge.cpp
+++ b/src/msw/webview_edge.cpp
@@ -989,7 +989,7 @@ wxVersionInfo wxWebViewFactoryEdge::GetVersionInfo()
             wxWebViewEdgeImpl::ms_browserExecutableDir.wc_str(), &nativeVersionStr);
         if (SUCCEEDED(hr) && nativeVersionStr)
         {
-            wxString versionStr = nativeVersionStr;
+            wxString versionStr = wxString(nativeVersionStr);
             wxStringTokenizer tk(versionStr, ". ");
             // Ignore the return value because if the version component is missing
             // or invalid (i.e. non-numeric), the only thing we can do is to ignore
```

However, if this really should not work I do not understand why it works here, where the code converting `wxCoTaskMemPtr<wchar_t>` to `wxString` is virtually identical:
https://github.com/wxWidgets/wxWidgets/blob/e7096e85d2966e068d45a49bbc27100c74c815c3/src/msw/stdpaths.cpp#L168-L178

**Comment by vadz** [comment]
I guess we should just use
```cpp
            wxString versionStr(nativeVersionStr);
```
here instead, or even get rid of it completely and simply do
```cpp
            wxStringTokenizer tk(nativeVersionStr, ". ");
```

The reason the code works in `stdpaths.cpp` is that it uses `operator=()` there and applies implicit conversion to `wxCoTaskMemPtr`. The reason it doesn't work here is that, despite using similar syntax, `operator=()` is _not_ used and the ctor is -- but C++ doesn't apply more than one user-defined conversion and so won't use the implicit conversion to `wchar_t` here. The final piece of the puzzle is that MSVS compiles this code because it has a non-standard extension allowing it to do it...

Anyhow, if it's not too much to ask, could you please confirm that the fix above works for you? I don't have MinGW set up for compiling Edge stuff myself yet... TIA!
