### ISSUE TITLE
windows10 ./src/common/windowsid.cpp(110):assert "gs_autoIdsRefCount[winid]!=ID_FREE" failed in IncldRefCount():id should first be reserved

### ISSUE THREAD

**Issue by macoomac** [wxWidgets/wxWidgets#22171]
**Describe the bug**
run filezilla.exe
./src/common/windowsid.cpp(110):assert "gs_autoIdsRefCount[winid]!=ID_FREE" failed in IncldRefCount():id should first be reserved 
Do you want to stop the program?
You can also choose[Cancle] to suppress further warnings.
![1646125420(1)](https://user-images.githubusercontent.com/48351143/156138398-c7e6f0e0-93f8-4954-b3d9-1417f7feca28.png)

**Expected vs observed behaviour**

**Patch or snippet allowing to reproduce the problem**
wxMSW-3.0.5_gcc920TDM_Dev.7z
wxWidgets-3.0.5-headers.7z

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. 
windows10->msys2->msys64 -> mingw32
cd filezilla-3.56.0-rc1/
./configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --with-pugixml=builtin LDFLAGS="-static-libgcc -static-libstdc++"
make
...
makensis.exe install.nsi

2.
run filezilla.exe

3. See error

**Platform and version information**
 - wxWidgets version you use:  3.0.5
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0

**Comment by PBfordev** [comment]
> wxMSW-3.1.5_gcc920TDM_x64_Dev.7z
> windows10->msys2->msys64 -> mingw32
> ./configure --host=i686-w64-mingw32 --build=i686-w64-mingw32

I would not link wxWidgets binaries built with TDM-GCC with MSYS2. But I wonder if you actually do that as the TDM binaries are as x64 but you seem to run 32-bit mingw?

BTW, if you do not want to build wxWidgets by yourself and want to use MSYS2, you can get [wxWidets 3.1.5 package](https://packages.msys2.org/base/mingw-w64-wxWidgets3.1).

**Comment by vadz** [comment]
@macoomac Did you close this intentionally?
