### ISSUE TITLE
wxDC does not have DrawTextW

### ISSUE THREAD

**Issue by jshanab** [wxWidgets/wxWidgets#22175]
I have _UNICODE set in preprocessor and am linking to the ud versions of WX but for some reason I am getting an error when I try to use DrawText on the DC passed in to myPaint

The application compiles and runs up to this point that I am adding the dc.DrawText( "foo", ....

Almost like I am not linking the correct windows GDI. 
The micorsoft header is detecting the _UNICODE flag in it's #ifdef and defineing DrawText to DrawTextW

Windows 10, VS2019 (generated with CMake) ,  latest wxWidgets. 

What am I missing?

**Comment by vadz** [comment]
Don't include `windows.h` directly, use `wx/msw/wrapwin.h` or at least include `wx/msw/winundef.h` after including it. Or, better, don't include it at all -- why do you do it?

In any case, there is nothing we can do about `windows.h` brokenness, it remained like this for 30 years and clearly is never going to change/be fixed.

**Comment by jshanab** [comment]
I did not.! I will take a closer look in the morning. Maybe another lib
did. This a very basic wxaui project, based on example code as this is a
new project startup.
