### ISSUE TITLE
mingw32   wxWidgets-3.0.5  wxrc.exe _gxx_personality_sj0 error!

### ISSUE THREAD

**Issue by macoomac** [wxWidgets/wxWidgets#22174]
**Describe the bug**
run c:\msys64\home\oao\prefix\bin\wxrc.exe 
_gxx_personality_sj0 dll error!
c:\msys64\home\oao\prefix\bin\wxrc.exe  
...
c:\msys64\home\oao\prefix\bin\wxbase30u_xml_gcc_custdom.dll

**Expected vs observed behaviour**
wxWidgets-3.0.5
i686-7.2.0-release-win32-sjlj-rt_v5-rev1

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/7.2.0/threads-win32/sjlj/i686-7.2.0-release-win32-sjlj-rt_v5-rev1.7z/download

**Patch or snippet allowing to reproduce the problem**

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. 
set  i686-7.2.0-release-win32-sjlj-rt_v5-rev1/mingw32/bin
2.
cd  wxWidgets-3.0.5
./configure --prefix="$HOME/prefix" --enable-shared --host=i686-w64-mingw32 --build=i686-w64-mingw32 --enable-unicode --without-libtiff --without-libjpeg --with-expat=builtin --with-libpng=builtin  CXXFLAGS="-std=gnu++11 -fpermissive -Wno-deprecated-copy"
make && make install

3.
run c:\msys64\home\oao\prefix\bin\wxrc.exe 

4.  see error
_gxx_personality_sj0 dll error!
c:\msys64\home\oao\prefix\bin\wxrc.exe  

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.0.5]
 - wxWidgets port you use: [e.g. wxMSW]
 - OS and its version: [e.g. Windows 10.0]

**Comment by PBfordev** [comment]
What does step 1 mean?

You seem to mix the compiler distribution by mingw-64 project with MSYS2 environment: Is this a good idea?

AFAIK, the error comes from linking the application against libraries of one compiler and the application attempting to use DLL from another compiler (configuration).

BTW, when you close a GitHub issue, you are expected to explain why: Was the issue invalid, did you fix it and how...

**Comment by macoomac** [comment]
> What does step 1 mean?
cp i686-7.2.0-release-win32-sjlj-rt_v5-rev1/mingw32  c:\msys32\mingw32 -rf
run c:\msys32\migw32.exe
cd  wxWidgets-3.0.5/
./configure CXX=g++ --prefix="$HOME/prefix" --enable-shared --host=i686-w64-mingw32 --build=i686-w64-mingw32 --enable-unicode --without-libtiff --without-libjpeg --with-expat=builtin --with-libpng=builtin CXXFLAGS="-std=gnu++11 -fpermissive -Wno-deprecated-copy"
make && make install

 
> You seem to mix the compiler distribution by mingw-64 project with MSYS2 environment: Is this a good idea?
ls -l 
c:\MSYS32 \ming32  /*32bit*/
c:\MSYS32 \ming64  /*64bit*/


> AFAIK, the error comes from linking the application against libraries of one compiler and the application attempting to use DLL from another compiler (configuration).

 
> BTW, when you close a GitHub issue, you are expected to explain why: Was the issue invalid, did you fix it and how...
ok!

**Comment by PBfordev** [comment]
> cp i686-7.2.0-release-win32-sjlj-rt_v5-rev1/mingw32 c:\msys32\mingw32 -rf run c:\msys32\migw32.exe cd wxWidgets-3.0.5/ ./configure CXX=g++ --prefix="$HOME/prefix" --enable-shared --host=i686-w64-mingw32 --build=i686-w64-mingw32 --enable-unicode --without-libtiff --without-libjpeg --with-expat=builtin --with-libpng=builtin CXXFLAGS="-std=gnu++11 -fpermissive -Wno-deprecated-copy" make && make install

I have little knowledge of MSYS2 so I may be wrong here but still. I already asked: Why do you mix mingw-64 project distro and MSYS2 environment instead of installing MSYS2 packaged mingw toolchain, such as https://packages.msys2.org/group/mingw-w64-i686-toolchain (and possibly also using prepackaged wxWidgets binaries)? The only reason I can think of is that you want to stick with the ancient GCC?

As for the DLL error, you need to check if the GCC runtime libraries that are found first in the locations where Windows looks for them when launching an executable are the correct ones.

**Comment by vadz** [comment]
You're not using the runtime MinGW DLLs corresponding to the compiler you're using. This is a local installation problem and really has nothing to do with wxWidgets.

**Comment by macoomac** [comment]
> You're not using the runtime MinGW DLLs corresponding to the compiler you're using. This is a local installation problem and really has nothing to do with wxWidgets.

Install msys2 and compile wxwdigst as follows:,
Check the wxwdigs website and indicate that it is compiled with the provided mingw32 package i686-7.2.0-release-win32-sjlj-rt_v5-rev1

-----------------------------------------
msys2 error!
cd wxwidgets-3.0.5
./configure CXX=g++ --prefix="$HOME/prefix" --enable-shared --host=i686-w64-mingw32 --build=i686-w64-mingw32 .....
make 
./src/msw/mediactrl_am.cpp:2234:10: error: narrowing conversion of '4294966687' from 'unsigned int' to 'long int' [-Wnarrowing]
 2234 |     case 0xfffffd9f: // readystatechange in IActiveMovie2 and IMediaPlayer
      |          ^~~~~~~~~~
make: *** [Makefile:39587: mediadll_mediactrl_am.o] Error 1


$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw32\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --enable-checking=release --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev9, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--no-seh -Wl,--large-address-aware -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--no-seh -Wl,--large-address-aware' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--no-seh\ -Wl,--large-address-aware\ -Wl,--stack,12582912' --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev9, Built by MSYS2 project)

**Comment by vadz** [comment]
Please don't reuse an existing issue for reporting a completely different issue.

Also, please search before reporting your issue, a quick search would have shown that this is a known error that was fixed in 3.1, so please either use it or 3.1.5 or just apply the trivial fix from fd81223a2f878757158b5266c362da71d43abee5 manually.

**Comment by macoomac** [comment]
> Please don't reuse an existing issue for reporting a completely different issue.
> 
> Also, please search before reporting your issue, a quick search would have shown that this is a known error that was fixed in 3.1, so please either use it or 3.1.5 or just apply the trivial fix from [fd81223](https://github.com/wxWidgets/wxWidgets/commit/fd81223a2f878757158b5266c362da71d43abee5) manually.


thanks
