### ISSUE TITLE
Using keyboard to select cells behaves incorrectly

### ISSUE THREAD

**Issue by guzmanpaco** [wxWidgets/wxWidgets#22172]
When using wxGrid on wxWidgets 3.1.0 and 3.1.5, using keyboard to perform shift select to select cells results in incorrect behavior.

For example:
1. Select Cell (1,1) using mouse
2. Hold shift and press right arrow two times and down arrow two times. Cursor should now be at cell 3,3
3. Release shift key

Expected:
The following cells are selected:
a. 1,1
b. 1,2
c. 1,3
d. 2,1
e. 2,2
f. 2,3
g. 3,1
h. 3,2
i. 3,3

Actual:
Windows:
![winres](https://user-images.githubusercontent.com/98376398/156277644-52835545-fb8d-45a0-a95d-178fdd84d123.png)
Only 1,1 is selected

Mac:
![Screen Shot 2022-02-28 at 9 53 06](https://user-images.githubusercontent.com/98376398/156277707-144219fd-337b-4d6a-bb37-997227743cee.png)

Selected:
a. 1,1
b. 1,3
c. 2,3
d. 3,1
e. 3,2
f. 3,3

And, partially selected
a. 1,2
b. 2,2

Issue is not encountered when using mouse.
1. Select Cell (1,1) using mouse
2. Hold shift key and press cell (3,3)
3. Release shift key

Is this expected?

**Comment by vadz** [comment]
This absolutely looks like a bug from your description, but I can't reproduce it, at least with the current master under MSW in the grid sample. Do you see the problem there?

**Comment by guzmanpaco** [comment]
Anyway, we checked on latest 3.1.6 and it seems issue is no longer encountered.

**Comment by vadz** [comment]
OK, thanks for retesting.
