### ISSUE TITLE
Versionized standard message catalog won't be loaded

### ISSUE THREAD

**Issue by s-ag** [wxWidgets/wxWidgets#22198]
**Describe the bug**
wxTranslations::AddStdCatalog tries to load "wxstd-&lt;major&gt;.&lt;minor&gt;", but further down the line ".&lt;minor&gt;" is treated as file name extension and replaced by ".mo".

**Expected vs observed behaviour**
The standard message catalog with the name as installed by wxWidgets should get loaded automatically in wxLocale::Init, but isn't.

**Platform and version information**
 - wxWidgets 3.1.5
 - Platform-independent bug

**Proposed fix**

```
diff --git a/src/common/translation.cpp b/src/common/translation.cpp
index dc06114bdc..8a78044371 100644
--- a/src/common/translation.cpp
+++ b/src/common/translation.cpp
@@ -1524,7 +1524,7 @@ bool wxTranslations::AddStdCatalog()
     // the name without the version if it's not found, as message catalogs
     // typically won't have the version in their names under non-Unix platforms
     // (i.e. where they're not installed by our own "make install").
-    if ( AddCatalog("wxstd-" wxSTRINGIZE(wxMAJOR_VERSION) "." wxSTRINGIZE(wxMINOR_VERSION)) )
+    if ( AddCatalog("wxstd-" wxSTRINGIZE(wxMAJOR_VERSION) "." wxSTRINGIZE(wxMINOR_VERSION) ".mo") )
         return true;
 
     if ( AddCatalog(wxS("wxstd")) ) 
```

**Comment by vadz** [comment]
Thanks for debugging this!

I think a better fix might be
```diff
diff --git a/src/common/translation.cpp b/src/common/translation.cpp
index 789c1463a9..f806598904 100644
--- a/src/common/translation.cpp
+++ b/src/common/translation.cpp
@@ -1931,8 +1931,7 @@ wxMsgCatalog *wxFileTranslationsLoader::LoadCatalog(const wxString& domain,
         wxSplit(searchPath, wxPATH_SEP[0])
     );
 
-    wxFileName fn(domain);
-    fn.SetExt(wxS("mo"));
+    wxFileName fn(wxString(), domain, wxS("mo"));
 
     wxString strFullName;
     if ( !wxFindFileInPath(&strFullName, searchPath, fn.GetFullPath()) )
```

as I don't think the domain is supposed to ever contain either extension or path.

@vslavik Could you please confirm this?

**Comment by vslavik** [comment]
@vadz Yes, your fix is better. `AddCatalog` really needs to take *domain* as its argument, not filename - it may sometimes load the translations from something other than a file (e.g. win32 resources) and appending ".mo" would break that.
