### ISSUE TITLE
Translation of 'Finish' is truncated in wizard if it’s longer than the translation of 'Next'

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22200]
**Describe the bug**
If the translation of 'Finish' is longer than the translation of 'Next' (e.g. in German) it is displayed truncated in `wxWizard`.

**Expected vs observed behaviour**
Under Windows it looks correct (probably because the default size of the button is enough):
![wizard_de_Win10](https://user-images.githubusercontent.com/99262969/158615522-7f45ff8b-6941-425a-bfb7-dce83b04180e.png)

But under Linux it’s truncated (e.g. under Linux Mint and Ubuntu):
![wizard_de_Linux-Mint](https://user-images.githubusercontent.com/99262969/158615609-2c95736b-45f1-49cc-80b7-2e1f91607f29.png)
![wizard_de_Ubuntu](https://user-images.githubusercontent.com/99262969/158615671-dfa1686c-fca6-405a-9544-7ba1d2c259d0.png)

**To Reproduce**
The issue can be reproduced in the wizard sample using these modifications: [wizard-sample_patch.zip](https://github.com/wxWidgets/wxWidgets/files/8263373/wizard-sample_patch.zip)

**Platform and version information**
wxWidgets-3.1.5 with GTK2

**Comment by vadz** [comment]
The fix here would be to compute the maximum width of the labels used for all buttons in `wxWizard::AddButtonRow()` and size them all to use the width of the widest one -- because even under Windows it looks ugly now as the "Finish" button is clearly too small, even if the label (just) fits.

This should be relatively straightforward to do, so any PRs doing this would be welcome.

**Comment by taler21** [comment]
I'm not sure if the maximum label width should be used for all buttons.
Because a (very) long translation of one label would result in all the buttons being very wide.

Maybe it's better to just make sure the 'next' button is wide enough for its two label texts.
In this case, the bug fix could probably look like this:
```patch
diff --git "a/src/generic/wizard.cpp" "b/src/generic/wizard.cpp"
index c221ac7ae1..a9633d68a7 100644
--- "a/src/generic/wizard.cpp"
+++ "b/src/generic/wizard.cpp"
@@ -439,6 +439,15 @@ void wxWizard::AddButtonRow(wxBoxSizer *mainColumn)
 #endif
     m_btnPrev = new wxButton(this, wxID_BACKWARD, _("< &Back"), wxDefaultPosition, wxDefaultSize, buttonStyle);
 
+    // set minimum width of 'next' button for its longest label text
+    wxString longestBtnNextLabel =
+        m_btnNext->GetTextExtent( wxControl::RemoveMnemonics( m_nextLabel ) ).GetWidth() >
+        m_btnNext->GetTextExtent( wxControl::RemoveMnemonics( m_finishLabel ) ).GetWidth() ? m_nextLabel
+                                                                                           : m_finishLabel;
+    m_btnNext->SetLabel( longestBtnNextLabel );
+    m_btnNext->SetMinSize( m_btnNext->GetBestSize() );
+    m_btnNext->SetLabel( m_nextLabel );
+
     if (btnHelp)
     {
         buttonRow->Add(

```

With these changes applied, the buttons in the wizard will appear as follows.

Under Windows 10:
![wizard_de_Win10_fix1](https://user-images.githubusercontent.com/99262969/158802452-3406e9b7-5eaa-4ff4-8958-cb4c2a29e809.png)

Under Linux Mint and Ubuntu:
![wizard_de_Linux-Mint_fix1](https://user-images.githubusercontent.com/99262969/158802488-a179ec1f-5952-4d13-907d-888ed54740c9.png)
![wizard_de_Ubuntu_fix1](https://user-images.githubusercontent.com/99262969/158802509-43fa9a3c-68d8-400a-9cfa-b30c94c6a687.png)

**Comment by vadz** [comment]
Yes, this would be a possible fix too, but I think that having differently sized buttons next to each other doesn't look good.

The best would be to find some native (ideally Microsoft) program using a wizard and look at how its buttons look on your (presumably German) system -- do they use the same size or not?

**Comment by taler21** [comment]
Sorry but I couldn't find any wizard on a GNOME desktop. Any ideas where to find one?

Note that buttons of different widths are already possible with the current implementation, e.g. if the translation of 'Back' or 'Cancel' does not fit into the standard width of a button.
My suggested fix doesn't introduce this behavior, it just ensures that the 'Next' button is wide enough for both of its labels.
It's an improvement without any deterioration or change in behavior.

**Comment by vadz** [comment]
> Sorry but I couldn't find any wizard on a GNOME desktop. Any ideas where to find one?

Sorry, no, if I knew it, I would have just looked myself :-/
 
> Note that buttons of different widths are already possible with the current implementation, e.g. if the translation of 'Back' or 'Cancel' does not fit into the standard width of a button.

Indeed. It probably was relatively uncommon to see it, but I think we should have been using `wxGridSizer` for them from the beginning.

> My suggested fix doesn't introduce this behavior, it just ensures that the 'Next' button is wide enough for both of its labels. It's an improvement without any deterioration or change in behavior.

Yes, I agree. I'll commit the diff above if there is no appetite for more changes, thanks.

**Comment by taler21** [comment]
I am not sure if using `wxGridSizer` would be correct.
`wxWizard::AddButtonRow()` creates a 'help' button without a label text under macOS.

I don't have macOS, but after a quick google search I think macOS wizard buttons look like this.
The 'help' button is smaller than the others there.
![wizard_buttons_macOS](https://user-images.githubusercontent.com/99262969/159136630-bfa1ff41-92cc-4d6e-a54b-d17586c6892c.png)

So using `wxGridSizer` would not be correct, would it?

**Comment by taler21** [comment]
The following fix computes the maximum width of the buttons and uses it for all of them.
Truncated label text is now avoided and the same width is used for all buttons (that have a label text).

```patch
diff --git "a/src/generic/wizard.cpp" "b/src/generic/wizard.cpp"
index c221ac7ae1..bba4f6bc09 100644
--- "a/src/generic/wizard.cpp"
+++ "b/src/generic/wizard.cpp"
@@ -439,6 +439,35 @@ void wxWizard::AddButtonRow(wxBoxSizer *mainColumn)
 #endif
     m_btnPrev = new wxButton(this, wxID_BACKWARD, _("< &Back"), wxDefaultPosition, wxDefaultSize, buttonStyle);
 
+    // use the 'next' button temporarily with its longest label text
+    // so that its maximum width can be computed
+    wxString longestBtnNextLabel =
+        m_btnNext->GetTextExtent( wxControl::RemoveMnemonics( m_nextLabel ) ).GetWidth() >
+        m_btnNext->GetTextExtent( wxControl::RemoveMnemonics( m_finishLabel ) ).GetWidth() ? m_nextLabel
+                                                                                           : m_finishLabel;
+    m_btnNext->SetLabel( longestBtnNextLabel );
+
+    // compute the maximum width of the buttons and use it for all of them
+    wxSize buttonSize = wxDefaultSize;
+    buttonSize.x = wxMax( buttonSize.x, m_btnPrev->GetBestSize().GetWidth() );
+    buttonSize.x = wxMax( buttonSize.x, m_btnNext->GetBestSize().GetWidth() );
+    buttonSize.x = wxMax( buttonSize.x, btnCancel->GetBestSize().GetWidth() );
+#ifndef __WXMAC__
+    if (btnHelp)
+    {
+        buttonSize.x = wxMax( buttonSize.x, btnHelp->GetBestSize().GetWidth() );
+
+        btnHelp->SetMinSize( buttonSize );
+    }
+#endif
+    m_btnPrev->SetMinSize( buttonSize );
+    m_btnNext->SetMinSize( buttonSize );
+    btnCancel->SetMinSize( buttonSize );
+
+    // set the initial label of the 'next' button
+    // after temporarily using its longest label
+    m_btnNext->SetLabel( m_nextLabel );
+
     if (btnHelp)
     {
         buttonRow->Add(

```

With these changes applied, the buttons in the wizard will appear as follows.

Under Windows 10:
![wizard_de_Win10_fix2](https://user-images.githubusercontent.com/99262969/159506631-4547c149-e230-4bca-8465-ee4df66dec49.png)

Under Linux Mint:
![wizard_de_Linux-Mint_fix2](https://user-images.githubusercontent.com/99262969/159506697-5d8477c9-3bd0-4809-8f6b-74bbdc234061.png)

Under Ubuntu (GNOME desktop):
![wizard_de_Ubuntu_fix2](https://user-images.githubusercontent.com/99262969/159506723-7ed1f133-14ee-4951-beab-76af12a60684.png)

Under openSUSE (KDE desktop):
![wizard_de_openSUSE_fix2](https://user-images.githubusercontent.com/99262969/159506751-d43b1735-1127-4533-bd3d-e08b746948eb.png)

Hope you agree with this changes.
Would be great if you could apply the fix before 3.1.6. Thanks.

**Comment by vadz** [comment]
Thanks, normally we should be able to use `GetSizeFromText()` instead of changing the label twice, but I'll commit this for now and we can improve it later.

Please don't hesitate to open PRs rather than pasting patches here, this is almost as simple (or maybe even more so) and less error-prone. TIA!

**Comment by vadz** [comment]
Hmm, it looks like this will result in a crash if `wxWIZARD_EX_HELPBUTTON` is not specified. I'll modify the code to test for it.

**Comment by taler21** [comment]
I don't think so, because if `wxWIZARD_EX_HELPBUTTON` is not specified `btnHelp` will be initialised with `NULL` and so a check for `btnHelp` should be enough.

But feel free to improve my changes. Thanks.

**Comment by vadz** [comment]
> I don't think so, because if `wxWIZARD_EX_HELPBUTTON` is not specified `btnHelp` will be initialised with `NULL` and so a check for `btnHelp` should be enough.

Oops, yes, sorry, I didn't notice that there were both compile- and run-time checks. This code is a bit weird as it still defined `btnHelp` under non-Mac platforms even though it's never used there, and I got confused, sorry again.

Anyhow, I did change it a bit because I don't think we need to compute the text extents ourselves: as long as we're prepared to change the button label twice, we can just ask it for its size directly. So I've finally made #22221 with my version, please let me know if it works for you. TIA!

**Comment by taler21** [comment]
I don't think that the size of the "Help" button should be changed under macOS, as I mentioned in this [comment](https://github.com/wxWidgets/wxWidgets/issues/22200#issuecomment-1073073165).

So in my opinion both compile- and run-time checks are necessary.
But I can't try it because I don't have macOS.

Under Windows and Linux, your improved fix works.

**Comment by vadz** [comment]
Argh, I had misread the code even more completely than I had realized. Looking at it really carefully now I see that the button is actually used under Mac, it's just created in a different place for the Tab order reasons. Which is not the best way to do it, but I'm not going to change it now.

I'll add `#ifndef __WXMAC__` back, thanks.
