### ISSUE TITLE
Items in wxDataViewListCtrl are no longer displayed

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22205]
**Describe the bug**
Items in `wxDataViewListCtrl` are no longer displayed.

This issue was introduced with commit [0cb0db015f42fc57068df74b9b9646109d313f8c](https://github.com/wxWidgets/wxWidgets/commit/0cb0db015f42fc57068df74b9b9646109d313f8c)

It can also be seen in the **dataview sample**.
1. Start the sample
2. Go to page `wxDataViewListCtrl` (no items are displayed)

**Expected:**
![dvc-315](https://user-images.githubusercontent.com/99262969/159009809-4db1882c-a74a-463a-9dcd-488d665c5a34.png)

**Observed:**
![dvc-master](https://user-images.githubusercontent.com/99262969/159009840-b5a648c5-573b-4c0c-8e81-1bdf42d23e9d.png)

**Platform and version information**
 - wxWidgets version you use: **Latest master for upcoming 3.1.6**
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by vadz** [comment]
Oops, thanks for noticing this. @thesiv Could you please check this? Do we need a special case for the (non-virtual) list, i.e. flat model too or can this be somehow solved without it?
