### ISSUE TITLE
Git reports .vcxproj.filters files as modified right after a fresh clone on Linux

### ISSUE THREAD

**Issue by andriybyelikov** [wxWidgets/wxWidgets#22214]
`git status` reports several `*.vcxproj.filters` files as modified right after a fresh clone `git clone https://github.com/wxWidgets/wxWidgets.git` on Linux.

Behavior is inconsistent, but from my tests three cases can ocurr.

**Case 1. Git reports `build/msw/*.vcxproj.filters` and `samples/minimal/minimal.vcxproj.filters` as modified**
```
[user@andriybyelikov wxWidgets]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   build/msw/wx_aui.vcxproj.filters
	modified:   build/msw/wx_base.vcxproj.filters
	modified:   build/msw/wx_core.vcxproj.filters
	modified:   build/msw/wx_custom_build.vcxproj.filters
	modified:   build/msw/wx_gl.vcxproj.filters
	modified:   build/msw/wx_html.vcxproj.filters
	modified:   build/msw/wx_media.vcxproj.filters
	modified:   build/msw/wx_net.vcxproj.filters
	modified:   build/msw/wx_propgrid.vcxproj.filters
	modified:   build/msw/wx_qa.vcxproj.filters
	modified:   build/msw/wx_ribbon.vcxproj.filters
	modified:   build/msw/wx_richtext.vcxproj.filters
	modified:   build/msw/wx_stc.vcxproj.filters
	modified:   build/msw/wx_webview.vcxproj.filters
	modified:   build/msw/wx_wxexpat.vcxproj.filters
	modified:   build/msw/wx_wxjpeg.vcxproj.filters
	modified:   build/msw/wx_wxpng.vcxproj.filters
	modified:   build/msw/wx_wxregex.vcxproj.filters
	modified:   build/msw/wx_wxscintilla.vcxproj.filters
	modified:   build/msw/wx_wxtiff.vcxproj.filters
	modified:   build/msw/wx_wxzlib.vcxproj.filters
	modified:   build/msw/wx_xml.vcxproj.filters
	modified:   samples/minimal/minimal.vcxproj.filters

no changes added to commit (use "git add" and/or "git commit -a")
```

**Case 2. Git reports only `samples/minimal/minimal.vcxproj.filters` as modified**
```
[user@andriybyelikov wxWidgets]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   samples/minimal/minimal.vcxproj.filters

no changes added to commit (use "git add" and/or "git commit -a")
```

**Case 3. Git reports no files as modified**
```
[user@andriybyelikov wxWidgets]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Running `misc/scripts/check_mixed_eol.sh` seems to report no problems.
```
[user@andriybyelikov wxWidgets]$ bash misc/scripts/check_mixed_eol.sh
[user@andriybyelikov wxWidgets]$
```

**Platform and version information**
 - OS and its version: Arch Linux (rolling)
 - Git version: 2.35.1
 - Bash version: 5.1.16
 - User's `~/.gitconfig` contents:
```
[user]
	email = ***
	name = ***
[credential]
	helper = store
[core]
	editor = vim
```

**Comment by vadz** [comment]
I can't reproduce this with git version 2.35.1 from Debian Sid and I have really no idea what could explain it. We set `eol=crlf` for these files in our `.gitattributes`, i.e. these files are supposed to use CR LF and this is indeed the case for me:
```
% file samples/minimal/minimal.vcxproj.filters
samples/minimal/minimal.vcxproj.filters: XML 1.0 document, Unicode text, UTF-8 (with BOM) text, with CRLF line terminators
```
What does it say for you? Also, does `git diff` show anything useful and/or does `git diff -w` show nothing? If you have just LFs in the files, could you be using a filesystem with automatic CR LF to LF translation somehow?

Anyhow, AFAICS anything resulting in inconsistent behaviour of `git clone` (because, if I understand correctly, you're not getting the same results after performing the same command) can only be a bug in Git or some local weirdness, but can't be due to anything we do, so it's probably not useful to keep this issue opened -- we're unlikely to be able to do anything about it.

**Comment by dconnet** [comment]
Just FYI. I did have that happen to me too. No matter what I did, I couldn't fix it. Finally just deleted my repo and recloned (luckily I had no local branches) and all was good again.

**Comment by dconnet** [comment]
Just realized I misread the subject. I had that issue when I did a pull. A new clone fixed it for me.

**Comment by andriybyelikov** [comment]
I managed to fix the issue by cloning a case 1 repo, then running `git add --renormalize .`, as suggested by [this](https://stackoverflow.com/questions/66896135/git-messing-up-line-endings-despite-gitattributes) StackOverflow question, then commiting and pushing to a branch. After cloning said branch five times I got case 3 repos on all five tries. Quoting the StackOverflow question's accepted best answer...

> Basically, anytime you make a change to .gitattributes, you need to run git add --renormalize . and commit those changes as well. Otherwise, you can end up with things in an inconsistent state.

...it seems to me that the author of commit https://github.com/wxWidgets/wxWidgets/commit/e3535d6481d609d758f6d81a7735ee1bdbb8660d which added `*.vcxproj.filters eol=crlf` to `.gitattributes` did not perform this step before commiting. I looked for commits where this might have been done but only found this wxTrac ticket comment from 2015 mentioning Git renormalization: https://github.com/wxWidgets/wxWidgets/issues/15584#issuecomment-1011016785

This is the commit on my fork, branch `issue-22214`, which changes all 23 of the modified files reported by `git status` in case 1: https://github.com/andriybyelikov/wxWidgets/commit/4473ecd1a84c73fb835f041c6eac1c2c9e6658ea

**Comment by vadz** [comment]
Interesting, I didn't know about `add --renormalize` and just did the matching changes myself when I was changing the attributes, but it looks like the commit mentioned above indeed forgot to do it. I'll cherry-pick your commit and push it soon, thanks!
