### ISSUE TITLE
Problem with Unicode wxStrings in Linux

### ISSUE THREAD

**Issue by transmitterdan** [wxWidgets/wxWidgets#22219]
**Describe the bug**
When converting wxString containing some Unicode wide characters the conversion result in an empty string.

**Expected vs observed behaviour**
The wxString should be converted to a std::string.  I have observed that on Windows Visual Studio 2022 it produces the expected conversion but on every Linux system (Debian based) I have it does not convert the string.

**Patch or snippet allowing to reproduce the problem**
This should compile and run on Linux.  
```
// UnicodeBug.cpp : Demonstrate a suspected bug in wxString class.
//
// g++ `wx-config --cppflags` -g -o UnicodeBug UnicodeBug.cpp `wx-config --libs`
// ./UnicodeBug
// Hello CMake.
// Degree sign: °
// Degree sign: °
// 1: The next 2 lines should print: Degree sign: ° 
// 2: Degree sign: °
// 3: 
// 4: But instead 3: is just a blank line.

#include <iostream>
#include <wx/string.h>

using namespace std;

int main()
{
    cout << "Hello CMake." << endl;
    string mess("Degree sign: \u00B0");
    cout << "Degree sign: \u00B0" << endl;
    cout << mess << endl;
    wxString s(wxS("Degree sign: \u00B0"));
    string st = string((s.mb_str()));    // why does this convert to an empty std::string
    cout << "1: The next 2 lines should print: Degree sign: \u00B0 \n";
    cout << "2: " << mess << endl;
    cout << "3: " << st << endl;
    cout << "4: But instead 3: is just a blank line." << endl;
    return 0;
}
```

**To Reproduce**

1. Copy above program code to a file UnicodeBug.cpp in any folder. Then run next 2 bash commands.
2. g++ `wx-config --cppflags` -g -o UnicodeBug UnicodeBug.cpp `wx-config --libs`
3. ./UnicodeBug
4. See if wxString st is converted correctly to std::string printing correct degree symbol text or an empty string.

**Platform and version information**
 - wxWidgets version you use: 3.0.4 & 3.1.6
 - wxWidgets port you use: wxGTK
 - OS and its version: "Raspbian GNU/Linux 10 (buster)"
 - For wxGTK only:
   + GTK version: libgtk-3-0:armhf             3.24.5-1+rpt2  armhf        GTK+ graphical user interface library
   + Which GDK backend is used: X11
   + If relevant, i.e. for appearance-related problems: N/A

**Comment by vadz** [comment]
Use `utf8_str()` (or `utf8_string()` if you use new enough version of wx) to ensure the conversion is lossless. You can't rely on losslessly converting arbitrary Unicode strings to any other encoding (well, we don't speak of UTF-7 and such any more...).
