### ISSUE TITLE
vcpkg static debug is corrupted

### ISSUE THREAD

**Issue by Leonard-The-Wise** [wxWidgets/wxWidgets#22216]
Very simple: 
```
.\vcpkg install wxwidgets:x86-windows-static
.\vcpkg install wxwidgets:x64-windows-static
```

Now go and try to build a DLL project using [Debug] [x86] or [x64].
Release works fine.

**Comment by vadz** [comment]
As mentioned above, vcpkg packages are not under our control, please report the bug there.
