### ISSUE TITLE
wxLocale::Init( wxLANGUAGE_DEFAULT ) doesn't work any longer under Linux

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22212]
I am using this code to use the system default locale for formatting dates regardless of the language chosen by the user for the program.
It allows users to use the program in, for example, English (because there are no translations for their language) and still have dates in their usual formatting.
```cpp
m_locale.Init( wxLANGUAGE_DEFAULT, wxLOCALE_DONT_LOAD_DEFAULT );

wxTranslations* const trans = new wxTranslations();
trans->SetLanguage( m_lang );
wxTranslations::Set( trans );
```

Up to and including wxWidgets-3.1.5, this worked fine on both Windows and Linux.
On Windows, it still works with the current master. But on Linux it doesn't work any longer.
It now seems that the English locale is used by default under Linux instead of that of the system.

**To Reproduce**
The issue can be reproduced by using this modified internat sample: [internat_cpp.zip](https://github.com/wxWidgets/wxWidgets/files/8315248/internat_cpp.zip)

If runnig the sample on, for example, a German Ubuntu 18.04.:

With **wxWidgets-3.1.5** it uses the default locale of the system for formatting the date.
![locale-default_wx-315](https://user-images.githubusercontent.com/99262969/159258683-755dd39c-9f53-4834-9a55-add47a565dce.png)

With the **latest master**, the English locale seems to be used instead.
![locale-default_wx-master](https://user-images.githubusercontent.com/99262969/159258696-d49de2ac-befd-4a9c-a185-be080b24b0d6.png)

**Platform and version information**
 - wxWidgets version you use: **Latest master** of upcoming 3.1.6
 - wxWidgets port you use: wxGTK
 - OS and its version: Ubuntu 18.04
 - For wxGTK only:
   + GTK version: 2.24.31
   + Which GDK backend is used: X11

**Comment by vadz** [comment]
Yes, I think it makes sense, as the comment here https://github.com/wxWidgets/wxWidgets/blob/af9e7fd4609381e2086a13a603e5e46e64718a77/src/common/intl.cpp#L755-L756 says, `wxUILocale` is supposed to call `setlocale()` under Unix. I'll include it my upcoming locale-related PR.

Thanks for reporting this!
