### ISSUE TITLE
wxChoice layout error for GTK3

### ISSUE THREAD

**Issue by ZhipengShi** [wxWidgets/wxWidgets#22226]
**Describe the bug**
wxChoice layout error for GTK3.  GTK2 works fine. My test system is Ubuntu20.04

**Expected vs observed behaviour**
wxChoice layout correctly

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxGTK3
 - For wxGTK only:
   + GTK version: 3.24.20

Attachments are gtk2 and gtk3 GUI. gtk2 works fine.

![gtk2_1](https://user-images.githubusercontent.com/99629101/159836383-8ef21484-68f9-486b-a55e-283cf6778b4c.png)
![gtk2_2](https://user-images.githubusercontent.com/99629101/159836388-a05fb619-2b99-494a-a2be-e825a8034579.png)
![gtk2_3](https://user-images.githubusercontent.com/99629101/159836682-09cc6de4-4fc9-4467-82d6-394663301bb7.png)

![gtk3_1](https://user-images.githubusercontent.com/99629101/159836408-f9a155ae-37e4-4bd7-ac87-cf6c6196f854.png)
3-08439dcc8196.png)
![gtk3_2](https://user-images.githubusercontent.com/99629101/159836425-02a52515-0ef7-47b2-8477-6b3987820289.png)
![gtk3_3](https://user-images.githubusercontent.com/99629101/159836434-566d5cb7-76c3-486d-ac5f-353ada1ab7d5.png)
![example_source](https://user-images.githubusercontent.com/99629101/159836508-a262c5ad-d3e7-4e7a-86d9-811b907d49d5.png)

**Comment by paulcor** [comment]
For future reference, a screenshot of your code is not going to cut it. Please provide any code **as text**, preferably as a diff against one of the samples.

But from a cursory look, I can see that you are hard-coding the width of the `wxChoice` as 120. GTK3 is not tolerant of sizing controls smaller than their minimum. You need to allow the control to be the size it wants, `GetBestSize()` is your friend.

**Comment by ZhipengShi** [comment]
Hi paulcor,
    It is works. Thank you. I will provice code as text for future.
Regards
