### ISSUE TITLE
Reopening #22223

### ISSUE THREAD

**Issue by Leonard-The-Wise** [wxWidgets/wxWidgets#22225]
Original issue was #22223; Don't know why it got closed ASAP and without much considerations, but since the moderator asked me to reopen if I could explain better, I'll try once more. 

Yes, I know, changing a flag to /MT was supposed to be simple, but unfortunatelly it is not. I'm not sure if you understood the whole text, but I'll try again:

- If you try and build ALL your project (including libraries, wxwidgets, etc) using /MT flag, you get missing symbols, no matter what. That forced me to link my project to CRT dynamically (/MD), even when using your STATIC versions of the library. That was the ONLY way it worked until now.

This is your wxwidgets default configuration - from the download package:

![image](https://user-images.githubusercontent.com/99574879/159812520-a4e261eb-b2ff-4f1c-8e13-1d3a2e300213.png)

See the problem here? It is linking to the **DYNAMIC** CRT. The field: `Multithreaded DLL (/MD)`. And that config is part of the STATIC library.
Notice the configuration set to `Release` over there? Now compare to your `DLL Release` configuration:

![image](https://user-images.githubusercontent.com/99574879/159812721-9da3ef66-2596-481f-bf58-e7bb18ba576e.png)

See the `DLL Release` over there? Ok, this is the ***first problem***: why did you set everything to link DYNAMICALLY to CRT, when default static packages are supposed to link to the static CRT? You see, every package from `x64-windows-static` triplet on `vcpkg` will build with these configs:

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
```

Emphasys on **VCPKG_CRT_LINKAGE static**. This alone creates a problem, because your MSVC version diverts from default linkage.

***Second problem***: if you go and change the (first image) version to use /MT, it compiles, fine... but now you won't be able to build your **main project** anymore, because all you'll get are missing symbols from wxwidgets. That happens to any code compiled also with /MT. Don't ask me why, I tested this toroughly during a day and got the same results anywhere. Hence why I opened this issue.

Hope I could make things clearer now. Anything just ask...

But as I already said: 
```
you can create a MSVC solution from the beggining, go to your website, 
paste the code from the Hello World app there, and then try to build it ALL 
(including wxwidgets) with /MT and you'll see what happens. 
Don't use CMAKE or anything like that. Use the project attached on 
$wxwidgetsDir$\build\msw\wx_vc16.sln. 
Don't link to any DLL, link to the static .libs.
```

Thanks.

**Comment by vadz** [comment]
By "reopening" I really meant "reopen the same ticket", not "open another one about the same topic", let's keep the discussion in #22223.
