### ISSUE TITLE
wxTaskBarIcon on macOS is not rounded

### ISSUE THREAD

**Issue by arjndr** [wxWidgets/wxWidgets#22232]
**Describe the bug**
wxTaskBarIcon button on macOS (I'm on macOS Monterey) is not rounded as it's supposed to be:

**Expected vs observed behaviour**
Expected:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/20661194/160074485-4cffd0e2-6db2-4c41-a648-8bb0c95219d1.png">

Observed Behaviour:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/20661194/160074417-e4007ae1-1b55-475a-b332-f4825d125cb9.png">

**Patch or snippet allowing to reproduce the problem**
Can be reproduced using the taskbar sample

**To Reproduce**
Can be reproduced using the taskbar sample

**Platform and version information**
 - wxWidgets version you use: 3.1.5
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS Monterey v12.2.1

**Comment by vadz** [comment]
It would be interesting if you could retest this with the latest master (pre-3.1.6) as this code was changed in 4f7e09374a (Fix taskbar icon size when using high DPI under macOS, 2021-10-29), which switched to the newer API which might have fixed it. If it didn't, I have to admit that I have absolutely no idea how to customize the icon shape here, so someone more familiar with Cocoa would need to find it out.

**Comment by arjndr** [comment]
Hey @vadz it's still the same, do you have any other pointers to potentially debug this behaviour?

**Comment by vadz** [comment]
No, sorry, I really don't know what determines the icon shape here. Please try looking for it in Apple docs, maybe you can find something.

**Comment by arjndr** [comment]
@vadz Looks like this has been fixed, I recently tried this again on wxWidgets 3.2 from MacPorts

**Comment by vadz** [comment]
This is a bit strange because I don't see any changes to this code which could have fixed it since 3.1.6, but if it works correctly now, all the better.

Thanks for (re)testing!
