### ISSUE TITLE
My apologies to Vadz

### ISSUE THREAD

**Issue by Leonard-The-Wise** [wxWidgets/wxWidgets#22249]
Hi there, 

I am just opening this ticket because I don't know much of github and don't know if I post on a closed one will properly generate notifications. Anyway, what I came to do here is: I just want to apologize to @vadz for my last post on this board.  I was stressed with lots of things happening on my side and I may have misinterpreted what he said [there](https://github.com/wxWidgets/wxWidgets/issues/22223) as aggressive or dismissive, specially in this last post:

> This has nothing to do with "having packages embedded" (whatever this means). If you use functions from some system DLL, you have to link with the corresponding import library, whether you use them directly or by linking with static wx libraries using them. And yes, this is required and perfectly normal.

So, if that wasn't the case, I'm sorry for the [follow up](https://github.com/wxWidgets/wxWidgets/issues/22223#issuecomment-1077930859) I gave there also.

Aside from that, I still don't quite understand why I must link to the same libraries wxwidgets is linking when I also have built all the code with static linkage (even C-Runtime static). But this now is **not** an issue for me now, just a curiosity. I am kind of a newbie in C++ and I like to learn new things. If you care to explain further, I'll be happy to listen.

Anyway, thanks for your time and sorry to bother again.

(PS: as for the rest of the team, could I ask you to let @vadz close this ticket? So I will be sure he read the message.)

That's it. Thanks and bye.

**Comment by vadz** [comment]
I do read all the messages here and also on the mailing list, there is really no reason to use the issue tracker as a means of communicating with me, please just write an email to wx-users if you have questions.

**Comment by Leonard-The-Wise** [comment]
No problem. I just hope you did understand me this time. Anyway. Have a good day. 
Bye

**Comment by Leonard-The-Wise** [comment]
Ok then, thanks for replying.
A good day to you.

**Comment by Leonard-The-Wise** [comment]
Ok then, thanks for replying. I hope that with this text, this issue is settled now. Anything just give ma a call.
A good day to you. Bye.

**Comment by Leonard-The-Wise** [comment]
Ok then. I just hope that with this I indeed could fix that last previous situation (I mean, my last "less-than-educated" reply). So, anything else about this just give me a call.

A good day to you and sorry to bother again. 
Bye bye.

**Comment by Leonard-The-Wise** [comment]
(Hi, have written some things before, but the real issue is...)

Well. I thank you for the informations, but I wish that you could at least have had answered me in this post if my apologies were accepted or not. A bit of courtesy sometimes goes a long way and I did wish to hear something from you on that.

I hope I am not asking too much from you here, @vadz.

Thank you.

**Comment by vadz** [comment]
Sorry, I have no idea what are you apologizing about, so I can hardly accept anything considering that I didn't even know I was supposed to be harmed. But in any case, please stop updating this issue, your multiple updates result in multiple notifications going to hundreds of people. If you want to contact me directly, you can just email me, but I'd honestly prefer to just close this topic. Again, there is nothing to apologize about, so please just let it rest.

**Comment by Leonard-The-Wise** [comment]
Well, that's for the best then. I feel relieved you even didn't notice my what have happened before - but I keep in mind that my apologies still remains anyway if you ever do (seriously, don't even bother anymore).  Anyway, sorry to disturb your board, didn't know this replies would reach so many people.

In any case this will be the last one of them here, I promise. I still don't know what your email is, but in case I ever need it, I'll just go to your website and figure it out in other ways. And if you ever need to reach me, you can also mail me [here](mailto:illusion.kore@gmail.com).

Now, thanks for this last reply and sorry to bother everyone of you guys again.

Bye bye.
