### ISSUE TITLE
wxDisplay::GetScaleFactor returns wrong value

### ISSUE THREAD

**Issue by deadlocklogic** [wxWidgets/wxWidgets#22256]
**Describe the bug**
`wxDisplay::GetScaleFactor` returns wrong 1.0 when in fact it should be 1.25.

**Expected vs observed behaviour**
Observed value: 1.0
Expected value: 1.25.

**Patch or snippet allowing to reproduce the problem**
`wxDisplay(0u).GetScaleFactor()` inside an empty top frame.

**Platform and version information**
 - wxWidgets version you use: latest
 - wxWidgets port you use: wxMSW
 - OS and its version: [e.g. Windows 10.0.19043 Build 19043]

![wxCapture](https://user-images.githubusercontent.com/57906342/161352148-8ac181e5-f246-497e-8223-8ab132f485cb.PNG)
Thanks.

**Comment by deadlocklogic** [comment]
Must be a missing initialization somewhere, because I also tried testing this with wxPython: same result. Unless I installed a package named `screeninfo` and used this at the top:
```python
import screeninfo

screeninfo.get_monitors()
```
So maybe for C++ also there should be some `winapi` call missing.

**Comment by MaartenBent** [comment]
Is your application DPI aware? Otherwise scaling is always 1.0, see also the documentation of the [underlying function](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor).
Setting DPI awareness is normally done via the manifest. Recommended is System or Per Monitor V2 awareness.

**Comment by deadlocklogic** [comment]
So I will try this [High DPI Support in wxWidgets](https://docs.wxwidgets.org/trunk/overview_high_dpi.html). So basically if I mark my app as dpi-aware, does this affect the coordinate system as a whole? Because it is a bit confusing.

**Comment by MaartenBent** [comment]
I can't really explain it better than the docs. Basically if you use any fixed sizes, you'll have to scale them with `FromDIP()`.
For example, to make a frame with hardcoded `wxSize(400, 300)` at 100% scale appear the same at 200%, you'll have to use `FromDIP(wxSize(400, 300))`.

**Comment by deadlocklogic** [comment]
I will close for now and I will invest more in docs. The subject is kinda complex thought, if I faced more issues I will get back.
Since I am testing with python also this worked perfectly:
```py
try:
    ctypes.windll.shcore.SetProcessDpiAwareness(True)
except:
    pass
```
Thanks.

**Comment by deadlocklogic** [comment]
Just a question because I am still a bit confused.
Consider I am not using any DPI awareness. My monitor is 1920x1080, with a 125% scale.
Everything in wxwidgets is divided by 1.25 (which is somewhat logical because of the global OS scale).
But I am facing 2 main problems with: `wx.Display` queries, and using `UIActionSimulator`. The latter, needs unscaled coordinates to work well, but how to convert to unscaled physical coordinates? `ToDPI` isn't changing anything at all.
Any thoughts?

**Comment by MaartenBent** [comment]
> Consider I am not using any DPI awareness. My monitor is 1920x1080, with a 125% scale.
Everything in wxwidgets is divided by 1.25 (which is somewhat logical because of the global OS scale).

I don't think this is true. If it is not marked as DPI aware, everything is based on 100%/96DPI. And when showing it on screen, Windows just magnifies it with 25%. That's why it also looks a bit blurry.

I'm not familiar with `wxUIActionSimulator`. But I tried the `uiaction` sample without DPI awareness. It performs `MouseMove(m_button->GetScreenPosition() + wxPoint(10, 10))`. When I look at the actual position of the mouse pointer, it moved 15x15 physical pixels (my display is 150%).

When I mark the application as System DPI Aware, and run the same code, the mouse pointer is moved 10x10 physical pixels. So here it needs `FromDIP(wxPoint(10, 10))` to make it end up at the same relative spot.

> ToDPI isn't changing anything at all.

When your application is not DPI aware, `ToDIP` and `FromDIP` indeed do nothing, because everything is based on 100% scale.

**Comment by deadlocklogic** [comment]
In my test, `FromDIP(wxPoint(10, 10))` is giving the same as `wxPoint(10, 10)` which is pretty weird. Can't understand exactly what is going on, wish there is a definitive doc to read about.

**Comment by vadz** [comment]
`FromDIP(10)` should give `13` for 125% scaling (which implies that your application is DPI-aware, for non DPI-aware ones scaling is always 100% no matter what). I really don't think there can be any bugs at this level, it's much more likely that there is a problem somewhere else. But if you are sure that `FromDIP()` doesn't work correctly, please open a separate issue with the shortest possible example allowing to see it.

**Comment by deadlocklogic** [comment]
> `FromDIP(10)` should give `13` for 125% scaling (which implies that your application is DPI-aware, for non DPI-aware ones scaling is always 100% no matter what). I really don't think there can be any bugs at this level, it's much more likely that there is a problem somewhere else. But if you are sure that `FromDIP()` doesn't work correctly, please open a separate issue with the shortest possible example allowing to see it.

To be clear scaling is 125%, and **no DPI awareness** is used, is this normal that FromDIP(10) gives 10?
If so how to convert any coordinates? Because even the `wxDisplay` has a scaling factor of 1.

**Comment by vadz** [comment]
As already mentioned several times above, when no DPI awareness is used, the scaling is, by definition, 100% from the application point of view. This is the whole point of "DPI unawareness", in fact: it isolates legacy applications from DPI scaling entirely as they still believe they're running at 100% DPI no matter what the actual scaling is.

**Comment by deadlocklogic** [comment]
So basically I won't be able to convert any coordinates properly without DPI awareness right?

**Comment by MaartenBent** [comment]
Without DPI awareness there is nothing to convert. The application is not aware of any scaling, dpi, or whatever.

**Comment by deadlocklogic** [comment]
Yes I see, but the main confusion is that the coordinates I am getting with `ClientToScreen` are in the range [1536,864] instead of [1920,1080] so I couldn't get `wxUIActionSimulator` to work correctly because it is requiring the range [1920,1080].
The confusion arises mainly as why a **non aware DPI** wxwidgets is dividing by the 1.25 factor anyway!?

Now I am using a DPI aware setting, but the only thing which bothers me is that some widgets looks extra inflated.
