### ISSUE TITLE
PropertyGridManager: Thaw called twice when using Freeze/Hide/Thaw

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/wxWidgets#22269]
Some time ago I submitted a wxPython bug report around PropertyGridManager triggering an assertion: https://github.com/wxWidgets/Phoenix/issues/1626

Today I stepped through wxWidgets with the debugger and so I could track it down.
The assertion `Thaw() without matching Freeze()` is triggered by a sequence of `Freeze/Hide/Thaw` on a `PropertyGridManager`.

In `wincmn.cpp` `Freeze`/`Thaw` are recursively freezing/thawing all children as found by `GetChildren`, which for a `PropertyGridManager` does return the `PropertyGrid`.
But with the current implementation `Hide` is calling `DoThaw` which does call `m_pPropGrid->Thaw()` and so a later call to `Thaw` does trigger the assertion.

I think that this code in `manager.cpp` is not needed or needs to be changed to call `m_pPropGrid->Do...` instead:
```
void wxPropertyGridManager::DoFreeze()
{
    m_pPropGrid->Freeze();
    wxWindow::DoFreeze();
}

void wxPropertyGridManager::DoThaw()
{
    wxWindow::DoThaw();
    m_pPropGrid->Thaw();
}
```

**Platform and version information**
 - wxWidgets version you use: current wxPython (4.1.2a)
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by vadz** [comment]
Thanks, I agree that this seems unnecessary and these functions could be simply removed. Did you already test doing this and check that everything still works correctly? If so, let's just do it.

@a-wi Could you please confirm that this is the right thing to do?

**Comment by DietmarSchwertberger** [comment]
Yes, I stepped through and it looked good. (Before, `m_freezeCount` was `2`.)

**Comment by a-wi** [comment]
> that this seems unnecessary and these functions could be simply removed.
Indeed, they seem to be not necessary because wxPropertyGrid is a child of wxPropertyGridManager and Freeze/Thaw calls are forwarded directly.
