### ISSUE TITLE
Add possibility to popup frames from ribbonbar

### ISSUE THREAD

**Issue by Runtemund** [wxWidgets/wxWidgets#22265]
It would be great, to popup frames from ribbonbar similar as menus. I leave patch code here, which works for me. Sorry, I am not sure if this is the right way...

Best regards, Uwe

toolbar.h
```
--- C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6_\include\wx\ribbon\toolbar.h
+++ C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6\include\wx\ribbon\toolbar.h
@@ -214,6 +214,7 @@
     wxRibbonToolBar* GetBar() {return m_bar;}
     void SetBar(wxRibbonToolBar* bar) {m_bar = bar;}
     bool PopupMenu(wxMenu* menu);
+    bool PopupWindow(wxWindow* frame);
 
 protected:
     wxRibbonToolBar* m_bar;
```

toolbar.cpp
```
--- C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6_\src\ribbon\toolbar.cpp
+++ C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6\src\ribbon\toolbar.cpp
@@ -1264,4 +1264,35 @@
     return m_bar->PopupMenu(menu, pos);
 }
 
+bool wxRibbonToolBarEvent::PopupWindow(wxWindow* frame)
+{
+    wxPoint pos = wxDefaultPosition;
+    if (m_bar->m_active_tool)
+    {
+        // Find the group which contains the tool
+        size_t group_count = m_bar->m_groups.GetCount();
+        size_t g, t;
+        for (g = 0; g < group_count; ++g)
+        {
+            wxRibbonToolBarToolGroup* group = m_bar->m_groups.Item(g);
+            size_t tool_count = group->tools.GetCount();
+            for (t = 0; t < tool_count; ++t)
+            {
+                wxRibbonToolBarToolBase* tool = group->tools.Item(t);
+                if (tool == m_bar->m_active_tool)
+                {
+                    pos = group->position;
+                    pos += tool->position;
+                    pos.y += tool->size.GetHeight();
+                    g = group_count;
+                    break;
+                }
+            }
+        }
+    }
+    pos = m_bar->ClientToScreen(pos);
+    frame->SetPosition(pos);
+    return frame->Show();
+}
+
 #endif // wxUSE_RIBBON
```

buttonbar.h
```
--- C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6_\include\wx\ribbon\buttonbar.h
+++ C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6\include\wx\ribbon\buttonbar.h
@@ -235,6 +235,7 @@
     void SetBar(wxRibbonButtonBar* bar) {m_bar = bar;}
     void SetButton(wxRibbonButtonBarButtonBase* button) { m_button = button; }
     bool PopupMenu(wxMenu* menu);
+    bool PopupWindow(wxWindow* frame);
 
 protected:
     wxRibbonButtonBar* m_bar;
```

buttonbar.cpp
```
--- C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6_\src\ribbon\buttonbar.cpp
+++ C:\Users\uwe\Documents\Quellcode\wxWidgets-3.1.6\src\ribbon\buttonbar.cpp
@@ -1526,4 +1526,23 @@
     return m_bar->PopupMenu(menu, pos);
 }
 
+bool wxRibbonButtonBarEvent::PopupWindow(wxWindow* frame)
+{
+    wxPoint pos = wxDefaultPosition;
+    if (m_bar->m_active_button)
+    {
+        wxRibbonButtonBarButtonSizeInfo& size =
+            m_bar->m_active_button->base->sizes[m_bar->m_active_button->size];
+        wxRect btn_rect;
+        btn_rect.SetTopLeft(m_bar->m_layout_offset +
+            m_bar->m_active_button->position);
+        btn_rect.SetSize(size.size);
+        pos = btn_rect.GetBottomLeft();
+        pos.y++;
+    }
+    pos = m_bar->ClientToScreen(pos);
+    frame->SetPosition(pos);
+    return frame->Show();
+}
+
 #endif // wxUSE_RIBBON
```

**Comment by vadz** [comment]
No, sorry, this is not the right way, the right way is described at https://www.wxwidgets.org/develop/how-to-submit-patches/

But I'm also not sure why do we need a new function for this in wxRibbon classes, don't we already have some way of determining the position near the active button? If not, I'd rather add such a function and then simply call `window->Move()` with the position returned by it and `window->Show()` directly in the application code.

**Comment by Runtemund** [comment]
Good question. I use this function in a method bind to wxEVT_RIBBONBUTTONBAR_DROPDOWN_CLICKED for opening a custom UI component, when clicking on the item.

I didn't found a convenient way to get the active button position with existing API. wxRibbonButtonBar::GetActiveItem() returns wxRibbonButtonBarButtonBase which has a poor interface. And as far as I can see no members to get the position... (The position comes from wxRibbonButtonBarButtonInstance and wxRibbonButtonBarButtonBase does not seem to have an pointer to it)

I thought it was natural to create a PopupWindow() method analogous to existing PopupMenu() in the EventObject. For me, it would also be OK if I could easily get the window position via another method. However, I would not find it comfortable if I had to recalculate the screen coordinates every time I wanted to open a dropdown window, which occurs multiple times in my software.

Otherwise, please excuse the form, I am an old subversion stager and a git beginner. If I undestand it right, I shall create a pull request, right?

**Comment by vadz** [comment]
My thinking is that you may want to do many things at the current tool position. E.g. show a tooltip, or use `ShowWithEffect()` to show a window there instead of simple `Show()`. Adding `PopupWindow()` isn't enough for this.

I don't know wxRibbon API well, but shouldn't `GetToolRect()` return what you need? If not, or even if yes, I think we should add the position to `wxRibbon{Button,Tool}BarEvent` itself.

And, to answer the last question, yes, please submit PRs with your changes, TIA!

**Comment by vadz** [comment]
Yes, sure, good luck and TIA!

**Comment by Runtemund** [comment]
It is done, but unfortunately I have no idea how to create a pull request. After clicking "New Pull request" I get a comparing page and "Create pull request" is disabled. Via git it says "acces denied"... And the github help is not really helpfull for me. 

Do you have a tip, how to start in the right way? Sorry, but git is new for me...

**Comment by vadz** [comment]
AFAICS "Create pull request" is only disabled if you don't enter any title for your PR. Did you enter something there?

As for Git, it can/should be used to push your branch (to your own fork, not wx itself), but you can't create a PR using just Git (there is a separate `hub` tool from GitHub which can do it), so I'm not sure what do you do exactly to receive "access denied".

**Comment by Runtemund** [comment]
I cannot enter a title. There is nothing, only a page for comparing branches. Access denied means, that I have no write permissions to create a branch, which is the first think I have probably to do. I understand now, that I have to create a fork first.
