### ISSUE TITLE
Missing files while executing compiled exe on Windows

### ISSUE THREAD

**Issue by wanna-beat-by-bit** [wxWidgets/wxWidgets#22274]
Windows throws error, when i execute an exe file, that was compiled. The error says that files wxmsw316ud_core_gcc_custom.dll and wxbase316ud_gcc_custom.dll are missing. Same issue on lower version. Don't know, where to get that files.

**Comment by wanna-beat-by-bit** [comment]
Strange, but found this file here. build\lib\gcc_dll  Program was build by cmake, and my executable couldn't just follow the build\lib\gcc_dll path, and grub this dll's

**Comment by PBfordev** [comment]
> Strange, but found this file here. build\lib\gcc_dll Program was build by cmake, and my executable couldn't just follow the build\lib\gcc_dll path, and grub this dll's

This is not how it works. As always, DLLs used by application must be somewhere where Windows can find them when launching the executable. The best place is the folder with the executable itself, see [here](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order) for more.

BTW, your application very likely also needs GCC runtime libraries, but I suppose you have mingw's bin folder in PATH, so on your computer that "works" (and would not work on a regular user's computer).
