### ISSUE TITLE
Incorrect mouse event coordinates when autoscrolling

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#22289]
**Describe the bug**

`wxAutoScrollTimer::Notify()` uses [this code](https://github.com/wxWidgets/wxWidgets/blob/master/src/generic/scrlwing.cpp#L148) to do screen-to-client conversion.
This has the effect of slightly shifting the bottom edge of the rectangle (the rubber band selection rectangle) downward.

**Expected vs observed behaviour**

I expect the bottom edge of the rectangle to stick with the mouse position (as long as the rubber banding is in progress) and not jump to other position unexpectedly as it is now.

**Patch or snippet allowing to reproduce the problem**

can be seen in the drawing sample.

**Platform and version information**
 - wxWidgets version you use: 3.1.6 and older versions too.
 - wxWidgets port you use: wxMSW, wxGTK3
 - OS and its version: Windows 10, Ubuntu 18.04
 - For wxGTK only:
   + GTK version: 3.22.30
   + Which GDK backend is used: X11 and Wayland

With this patch everything is ok:
```
diff --git a/src/generic/scrlwing.cpp b/src/generic/scrlwing.cpp
index d25b9832bc..87d249c72f 100644
--- a/src/generic/scrlwing.cpp
+++ b/src/generic/scrlwing.cpp
@@ -147,12 +147,7 @@ void wxAutoScrollTimer::Notify()
 
             // the mouse event coordinates should be client, not screen as
             // returned by wxGetMousePosition
-            wxWindow *parentTop = m_win;
-            while ( parentTop->GetParent() )
-                parentTop = parentTop->GetParent();
-            wxPoint ptOrig = parentTop->GetPosition();
-            event2.m_x -= ptOrig.x;
-            event2.m_y -= ptOrig.y;
+            m_win->ScreenToClient(&event2.m_x, &event2.m_y);
 
             event2.SetEventObject(m_win);
 
```

**Comment by vadz** [comment]
I have no idea why doesn't the new code produce the same result as the new version (another bug?), but your patch is clearly good anyhow because, in addition to fixing the problem, it's much simpler -- so I'll apply it soon, thanks!
