### ISSUE TITLE
wxWidgets 3.1.6 no longer links with apps that build their own zlib (since zlib 1.2.12)

### ISSUE THREAD

**Issue by inkmeister** [wxWidgets/wxWidgets#22280]
Since the recent upgrade to zlib 1.2.12, wxWidgets prevents applications that link in their their own copy of zlib 1.2.12 from building, due to zlib’s three new functions not having the wx_zlib_ prefix applied in wxWidgets’ zconf.h.

Using Visual Studio 2022 17.1.3 under Windows 10:

2>wxzlibd.lib(crc32.obj) : error LNK2005: crc32_combine_op already defined in zlib.lib(crc32.obj)
2>wxzlibd.lib(crc32.obj) : error LNK2005: crc32_combine_gen already defined in zlib.lib(crc32.obj)
2>wxzlibd.lib(crc32.obj) : error LNK2005: crc32_combine_gen64 already defined in zlib.lib(crc32.obj)

**Comment by vadz** [comment]
Please test #22341 if you can and let me know if it fixes the problem for you, as it's supposed to. TIA!

**Comment by inkmeister** [comment]
> Please test #22341 if you can and let me know if it fixes the problem for you, as it's supposed to. TIA!

The fix works well. Thank you.
