### ISSUE TITLE
What about provide doc in qch for download?

### ISSUE THREAD

**Issue by playgithub** [wxWidgets/wxWidgets#22283]
Because
1. doc in qch looks well, and integrated with Qt Creator very well, it's very convenient. For chm, it also looks well, but it doesn't integrate to any IDE, and `hh.exe` is buggy for HDPI (see https://github.com/wxWidgets/wxWidgets/issues/19200)
2. It is tricky to build qch for wxWidgets
    * `doxygen` 1.9.3 (current release) can't build qch for wxWidgets succefully (https://github.com/doxygen/doxygen/issues/9257)
    * `doxygen` 1.8.19 it can build qch for wxWidgets succefully, but it's a little tricky due to `javacc` 7.0.9 as below<br>
        > In the file `vhdlparser.jj` replace the lines
        > ```
        > PARSER_INCLUDES="vhdljjparser.h";
        > TOKEN_MANAGER_INCLUDES="vhdlstring.h";
        > ```
        > with
        > ```
        > PARSER_INCLUDE="vhdljjparser.h";
        > TOKEN_MANAGER_INCLUDE="vhdlstring.h";
        > ```
        > From the javacc 7.0.6 release notes:
        > ```
        > C++ generation: renaming the option PARSER_INCLUDES by PARSER_INCLUDE
        > C++ generation: renaming the option TOKEN_MANAGER_INCLUDES by TOKEN_MANAGER_INCLUDE
        > ```

**Comment by vadz** [comment]
I wouldn't mind accepting PRs adding QCH to the various build scripts and instructions, but I'm unlikely to do this myself, sorry.

**Comment by playgithub** [comment]
It is a bug of doxygen, being fixed now
https://github.com/albert-github/doxygen/commit/f1cc0da77fed56e3a37ad615be73769d8453cdff
