### ISSUE TITLE
'SetFocus failed' when closing a "Save changes?" dialog

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22285]
**Describe the bug**
When closing a "Save changes?" dialog that is displayed when closing a document or exiting the application, an API error will be logged.
```
..\..\src\msw\window.cpp(594): 'SetFocus' failed with error 0x00000057 (Wrong parameter.).
```

It's a regression in wxWidgets-3.1.6.
With wxWidgets-3.1.5 it works without such API error.

**To Reproduce**
The issue can be also reproduced with the **dialogs sample**:
1. Start the dialogs sample.
2. Click on 'Dialogs' > 'Simulate an unsaved document at exit'.
3. Exit via close button [x] in the title bar.
   BTW: If the application is exited via the menu, the "Save changes?" dialog is not displayed.
   This seems to be another bug.
4. Close the displayed "Save changes?" dialog. It doesn't matter how you close it.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 7 and Windows 10

**Comment by vadz** [comment]
First of all, this debug error can be safely ignored -- the worst that can happen here is that the focus isn't restored correctly after the dialog is dismissed.

Second, this message exists to help with finding problems in our own code and here it indicates that the changes of d311c705d7 (Make native dialogs application-modal in wxMSW, 2022-04-01) were wrong: we need to re-enable the window before restoring the focus to it. Now I just need to find some way of doing it...

Thanks for reporting this, I suspect the problem already existed with generic modal dialogs even in 3.1.5, but it's not a reason not to fix it, of course.

**Comment by vadz** [comment]
This is fixed in the PR referenced above, please test it if possible to see if you have any other problems with it. TIA!

**Comment by taler21** [comment]
Works for me. Thanks for the quick fix.
