### ISSUE TITLE
Issue with MSYS2 mingw-w64 11.2 builds: "Entry point not found"

### ISSUE THREAD

**Issue by HackerDaGreat57** [wxWidgets/wxWidgets#22298]
**Describe the bug**
Windows is complaining that it cannot find the entry point in wxWidgets applications built with version 3.1.6. This issue happens with the official builds as well as custom from-sources.

**Expected vs observed behaviour**
I expected the application (in this case, the "wxrc" executable) to open up and do its thing. Instead, windows popped up this dialog: 
![image](https://user-images.githubusercontent.com/70416002/162873203-e550ce91-7d7f-4130-9ab3-a30bc6c3e64a.png)

**Patch or snippet allowing to reproduce the problem**
None - this is a build issue.

**To Reproduce**
Just build & run any sample of version 3.1.6 compiled by MSYS2 mingw-w64 11.2

**Platform and version information**
 - wxWidgets version: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 11
 - wxWidgets "mode": Not wxUniversal (using native wxMSW port)

**Comment by vadz** [comment]
`wxrc.exe` from https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.6/wxMSW-3.1.6_vc110_x64_Dev.7z works perfectly fine for me, so this looks like like some mixup of libstdc++/compiler versions.

How exactly do you build `wxrc.exe` which gives the message above?

P.S. Hint: you can press `Ctrl-C` to copy the message box contents as text and paste it, this is more useful (and much more searchable!) than an image.

**Comment by HackerDaGreat57** [comment]
That link looks like it's the Visual C++ version. I'm talking about the GCC 11.2 version.

Also, I seem to have Cygwin in my PATH - I will remove it from PATH and rebuild to see if that fixes it.

**Comment by vadz** [comment]
Sorry, my mouse slipped and I copied a wrong link. I meant https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.6/wxMSW-3.1.6_gcc1120_x64_Dev.7z, this is the one I tested.

As for copying and pasting, pressing `Ctrl-C` specifically in the message box definitely works, although it seems to be one of the best kept secrets in Windows as nobody knows about it, try it out.

**Comment by HackerDaGreat57** [comment]
No problem. Humans make mistakes 😁

Strangely enough, I copied the wxAUI sample to another computer and it magically worked. I have no idea what causes this, but maybe it's the difference between Windows 10 and 11? (The one that I'm getting the error on is 11, the other one is 10)

P.S. The Ctrl-C trick worked, but it gives me this:
`wxrc.exe - Entry Point Not Found`

`The procedure entry point _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv could not be located in the dynamic link library C:\Users\ys080\Downloads\wxMSW-3.1.6_gcc1120_x64_Dev (1)\lib\gcc1120_x64_dll\wxbase316u_gcc1120_x64.dll.`

**Comment by PBfordev** [comment]
> Strangely enough, I copied the wxAUI sample to another computer and it magically worked. I have no idea what causes this, but maybe it's the difference between Windows 10 and 11? (The one that I'm getting the error on is 11, the other one is 10)

To me, it does not seem strange at all and further confirms that the issue is caused by mismatched libraries. In other words, you have in PATH a different GCC library (version, build options) than the executable was built against.

Windows version should have no effect on this.

**Comment by vadz** [comment]
The error is about a symbol in the standard library (`std::__exception_ptr::exception_ptr::_M_release()` in demangled form), so it would indeed be explained if you had different/wrong `libstdc++-6.dll` versions on the different machines and I think this is the real problem.

If you still think it's a wx problem, please reopen, but provide more details about the MinGW DLLs you use.

**Comment by HackerDaGreat57** [comment]
Thanks. I will reinstall msys2/mingw-w64 and see if that fixes it.

**Comment by HackerDaGreat57** [comment]
Hrm.
![image](https://user-images.githubusercontent.com/70416002/167321776-0d513042-dea1-4d8c-a9c0-32fc77337fc4.png)

**Comment by HackerDaGreat57** [comment]
Alright. So I made it work by adding `-static-libgcc -static-libstdc++` to the linker options. Now it works like a charm!
