### ISSUE TITLE
wxStaticBitmap extented RTTI constructor definition

### ISSUE THREAD

**Issue by MaartenBent** [wxWidgets/wxWidgets#22300]
**Describe the problem**
I was checking if `brew` had updated their wxWidgets version to `3.1.6`, and found this https://github.com/Homebrew/homebrew-core/pull/98491

I'm not sure what and how they are testing, but they get:
```
 Symbol not found: __ZN14wxStaticBitmap6CreateEP8wxWindowiRK8wxBitmapRK7wxPointRK6wxSizelRK8wxString
```
Note that the error still references `wxBitmap` instead of `wxBitmapBundle`.

The only probable cause I could find was:
https://github.com/wxWidgets/wxWidgets/blob/eb054c828624a234991dbb46ef45cd9015b53ca8/src/common/statbmpcmn.cpp#L75-L76
I suppose this should be changed to `wxBitmapBundle`?

`wxBitmapButton` has the same faulty definition:
https://github.com/wxWidgets/wxWidgets/blob/ce46d773609154f9e6c663e08aca96e2314db23d/src/common/bmpbtncmn.cpp#L79-L80

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 15
 - Compiler being used: Clang I guess

**Comment by vadz** [comment]
Thanks for checking this!

I guess they must be building with `wxUSE_EXTENDED_RTTI==1` (i.e. `--enable-extended_rtti` with configure). We don't test these builds and I think we should drop this code entirely, but last time I brought this up @csomor still wanted to keep it, so I guess we need to change one of the CI builds to use this option -- and fix it, of course.

**Comment by MaartenBent** [comment]
Thats what I thought at first, but I don't see it in the [argument list](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxwidgets.rb).

**Comment by MaartenBent** [comment]
I might have slightly misinterpreted the issue. I think the actual problem is with `diff-pdf` failing to use the library because the function signature changed. And they just need to rebuild their `diff-pdf` with the new `wxWidgets` version.

I guess the milestone can be removed. But extended RTTI still needs the fix (and lots of others).

**Comment by vadz** [comment]
Strange that the dependencies are not being rebuilt when wx itself is, but if it's "just" this, then I guess it's indeed not such a big problem, thanks.

**Comment by nohal** [comment]
Just for future reference as it was not exactly straightforward to find out for a non-seasoned Homebrew contributor and could probably happen again:
If dependent packages in Homebrew need rebuild because of ABI changes in formula they depend on, they also need an update bumping the revision number in the same pull request (Done in https://github.com/Homebrew/homebrew-core/pull/99206).

**Comment by vadz** [comment]
Thanks @nohal for letting us know!

Is there anything we could do to somehow facilitate this (short of not changing ABI, which will be the case in 3.2.x, but not in 3.3.x when we get to it) or is this specifically a Homebrew thing?

**Comment by nohal** [comment]
My Homebrew knowledge is next to none, but I don't think there is anything the upstream could do to avoid this short of not changing the ABI.
