### ISSUE TITLE
wxNotebook becomes very slow

### ISSUE THREAD

**Issue by playgithub** [wxWidgets/wxWidgets#22308]
## Env
OS: Windows 10
wx: 3.1.6 or later, msw
Screen: 4K scaled at 200%

## Reproduce
Offical sample `notebook` without modification
Build it in release mode
Run and resize the main frame by dragging, when it is large enough (e.g. cover 90% of the screen), it becomes apparently slow for dragging
Meanwhile switching tabs in wxNotebook also becomes apparently slow

## More Info
In my application, because there are less controls, it'll be not so slow, but when set "DPI Awarebness" to "High DPI Aware", it becomes apparently slow.

## A Clue
When adding `wxNotebook` to a sizer, if param `proportion` is 0, it'll be always fast enough either when resizing or when switching tabs.

**Comment by vadz** [comment]
Could be another instance of DWM problem already discussed many times, although it's strange that it happens with so few controls. Profiling would be helpful, as always with this kind of problems.

**Comment by playgithub** [comment]
It's param `proportion` in `wxSizer::Add` causes the problem.
If the param is 0, no problem.
If the param is greater than 0, problem occurs.

**Comment by MaartenBent** [comment]
In the notebook sample it seems to be caused by the custom paint handler, most notably in `wxNotebook::OnPaint`:
https://github.com/wxWidgets/wxWidgets/blob/d72a3f7cecd1df5f1da946e11ad7ada7b3edba42/src/msw/notebook.cpp#L820-L822
That explains why it is more noticeable with high DPI, there are 4 times more pixels to draw.

What about only binding to `EVT_PAINT` when the user actually sets a background? Removing it from the event handler and  adding `Bind(wxEVT_PAINT, &wxNotebook::OnPaint, this);` to https://github.com/wxWidgets/wxWidgets/blob/533958be10a2bd0246e6ce740873f7377c14f906/include/wx/msw/notebook.h#L126

**Comment by playgithub** [comment]
> That explains why it is more noticeable with high DPI, there are 4 times more pixels to draw.

When `param` proportion in `wxSizer::Add` is 0, it is always very fast, how to explain this?

**Comment by MaartenBent** [comment]
When `proportion` is 0, it does not resize the `wxNotebook`, it keeps its original size while the frame/panel around it resizes. When `proportion` is 1, the `wxNotebook` is sized to the size of the frame/panel around it.
For example, the notebook sample uses proportion 5 (`wxSizerFlags(5)`), so the notebook is 5/6th of the screen, and the text control 1/6th.

(This is ignoring `wxEXPAND` / `wxSizerFlags().Expand()`, which will determine if the `wxNotebook` is expanded vertically/horizontally (the opposite direction of `proportion`).

**Comment by vadz** [comment]
> In the notebook sample it seems to be caused by the custom paint handler, most notably in `wxNotebook::OnPaint`:
> 
> https://github.com/wxWidgets/wxWidgets/blob/d72a3f7cecd1df5f1da946e11ad7ada7b3edba42/src/msw/notebook.cpp#L820-L822
> 
> That explains why it is more noticeable with high DPI, there are 4 times more pixels to draw.
> 
> What about only binding to `EVT_PAINT` when the user actually sets a background? Removing it from the event handler and adding `Bind(wxEVT_PAINT, &wxNotebook::OnPaint, this);` to
> 
> https://github.com/wxWidgets/wxWidgets/blob/533958be10a2bd0246e6ce740873f7377c14f906/include/wx/msw/notebook.h#L126

This seems like a good optimization and if you could please test that it works (i.e. speeds things up) and make a PR, I'd be glad to merge it.

I'm still puzzled as to why doing a simple `::FillRect()` should be noticeably slow, even in high DPI. This should be the fastest operation possible...

**Comment by playgithub** [comment]
> I'm still puzzled as to why doing a simple `::FillRect()` should be noticeably slow, even in high DPI. This should be the fastest operation possible...

When comment out "::FillRect" and it is still slow.
When comment out  "MSWDefWindowProc" it becomes fast.

Any optimization for `wxWindowMSW::MSWDefWindowProc`
https://github.com/wxWidgets/wxWidgets/blob/d72a3f7cecd1df5f1da946e11ad7ada7b3edba42/src/msw/window.cpp#L2476-L2495

**Comment by vadz** [comment]
No, we can't optimize this function, it's implemented inside Windows itself and is not under our control. I have no idea what does it do in order to be so slow...

**Comment by playgithub** [comment]
If comments out `MSWDefWindowProc` in `wxNotebook::OnPaint`, tabs will not show any more.
When debuging,  `MSWDefWindowProc` is `wxWindowMSW::MSWDefWindowProc`.
Does it mean `wxWindowMSW::MSWDefWindowProc` draws tabs for `wxNoteBook`?

**Comment by vadz** [comment]
Yes, this is the Windows function implementing drawing (and all the other behaviour) of the native control.

**Comment by playgithub** [comment]
Test PR https://github.com/MaartenBent/wxWidgets/commit/9948890010d6832657202c9840675e4e435ee4d0,
It solved the problem.
Thanks @MaartenBent

**Comment by MaartenBent** [comment]
I improved it a bit (don't bind when user changes to no background colour) and created https://github.com/wxWidgets/wxWidgets/pull/22320

**Comment by playgithub** [comment]
> I improved it a bit (don't bind when user changes to no background colour) and created #22320

Before and after this patch, it displays the same contents, why is it much slower for large screen before this patch?

**Comment by MaartenBent** [comment]
We repainted the `wxNotebook` with the default background colour and then let the Windows function redraw the whole `wxNotebook`. Now we do nothing and let Windows handle it. Maybe they only draw the area that is added by resizing.

With a 4k screen I still notice very slight lags when I resize the `wxNotebook` to the maximum screen size. So you can still notice the effect of `::DefWindowProc`.

**Comment by playgithub** [comment]
Before this patch, try the code below, `wxNotebook` also shows well, and fast.
It seems that `wxNotebook` draws twice.
```
void wxNotebook::OnPaint(wxPaintEvent& WXUNUSED(event))
{
    return;
}
```

**Comment by MaartenBent** [comment]
But for a custom background colour we have to do ` ::FillRect(hdc, &rc, hbr);` to paint the tab background colour, and then have to use `MSWDefWindowProc(WM_PAINT, (WPARAM)hdc, 0);` so it draws to notebook. Making it slow again.

**Comment by playgithub** [comment]
> But for a custom background colour we have to do ` ::FillRect(hdc, &rc, hbr);` to paint the tab background colour, and then have to use `MSWDefWindowProc(WM_PAINT, (WPARAM)hdc, 0);` so it draws to notebook. Making it slow again.

It seems that `MSWDefWindowProc` is called twice, on in `wxNotebook::OnPaint` one outside, but only one is enough.

**Comment by playgithub** [comment]
> Before this patch, try the code below, `wxNotebook` also shows well, and fast. It seems that `wxNotebook` draws twice.
> 
> ```c++
> void wxNotebook::OnPaint(wxPaintEvent& WXUNUSED(event))
> {
>     return;
> }
> ```
> 
> Better only this function determines everything to draw, so that it'll be also fast for custom background.

In other words, in sample `notebook`, `wxNotebook::OnPaint` is redundant, which slows down `wxNotebook`, right?

**Comment by vadz** [comment]
Using empty `OnPaint()` like above shouldn't work, as it doesn't draw anything on its own and prevents the native control from drawing itself too. So I'd expect display artefacts in this case.

**Comment by playgithub** [comment]
> Using empty `OnPaint()` like above shouldn't work, as it doesn't draw anything on its own and prevents the native control from drawing itself too. So I'd expect display artefacts in this case.

At least it works on my computer
Windows 10
VS2022
![image](https://user-images.githubusercontent.com/3665590/163720240-331d999a-d8bd-4e8a-857a-2286df867263.png)
