### ISSUE TITLE
wxFontDialog displays wrong pointsize in hi-dpi

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#22313]
When using wxFontDialog where I initialize wxFontData with a wxFont, the dialog shows the DPI-adjusted value.

The wxFont has been created at 8pt on a 150% system. The dialog shows 12pt.
myfont.GetPointSize() does report 8.

**Expected vs observed behaviour**
wxFontDialog should display the font size the font was created with, not the adjusted one.

**To Reproduce**
Sample: font
1. Start sample, see point size says 9.0
2. Select->Select Font, dialog shows 14. Cancel
3. In main window, change font size to 12.0, Apply changes.
4. Repeat step2: dialog shows 18 now.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0.19044.1645
 - Main monitor: 150% (monitor 2 is as 200%)

**Comment by dconnet** [comment]
Forgot to mention, the font size that is selected will be applied properly. So it is only the initialization that is broken.

**Comment by vadz** [comment]
Should be fixed by #22322, could you please test?
