### ISSUE TITLE
Performance optimization in `wxNotebook::OnSize`?

### ISSUE THREAD

**Issue by playgithub** [wxWidgets/wxWidgets#22319]
https://github.com/wxWidgets/wxWidgets/blob/d72a3f7cecd1df5f1da946e11ad7ada7b3edba42/src/msw/notebook.cpp#L893-L902

`rect = wxRect(...)`, `wxRect(...)` will be on the stack, I'm sure if values on the stack will be changed, if it changes, and `rect` here also changes, it means the values are copied twice.

For `wxRect(...)` is anoymous, optimization might make it copied only once.
If there a function like wxRect.Set(x, y, w, h), it'll be easier.

**Comment by vadz** [comment]
Copying 4 (or 8, or 12) integers is completely negligible compared to the actual `RefreshRect()` call. Moreover, I wouldn't be surprised if this were already optimized in release build, as `wxRect` ctor and assignment operators are both inline, so the compiler should see what they do.

Please run profiler or at least measure the time before and after the proposed change, you will see that it doesn't change at all.
