### ISSUE TITLE
Rendering performance issues for wxGrid components on MSW using custom wxGridCellStringRenderer

### ISSUE THREAD

**Issue by xamidi** [wxWidgets/wxWidgets#22317]
As first mentioned in [this](https://forums.wxwidgets.org/viewtopic.php?p=211683#p211683) and subsequent forum posts, I encountered significant rendering performance issues on wxWidgets 3.1.4, 3.1.5 and 3.1.6. For 3.1.3 and below, it works fine.

I created a [sample](https://mega.nz/file/G4kT2CjY#uT_77E4ZzJuvPd0Ey9pLTzyRubHe4LGM4yV7R7VniN4) from my code for reproducing the behaviour. I also created one [unproblematic](https://mega.nz/file/DwsjxayB#GnU5qQklIf7mj7icqO750Gntgj_cWHH6APw6809PpxM) and one [problematic](https://mega.nz/file/qw1whKrZ#SbZJZlYlx3NNGauZRRiAOR_zY-cz8qdXTSB0N1dGEio) binary (64-bit .exe for Windows 7+) as showcases. They were created from static wxWidgets 3.1.3 and 3.1.6 binaries that can be obtained from [here](https://mega.nz/file/7o9TWLDQ#TIpLZv-x8rDhHGd2bLunaam_oEvC73dgDdNGO845sZ4) and [here](https://mega.nz/file/Ts0QhSBa#hJ9O1tJm4wvZxNSBdEiw-kYHpAp1fOd9TWGfxQhux28), respectively. The compiler I used is the x86_64 version from [GCC 11.2.0 + MinGW-w64 9.0.0 MSVCRT](https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-msvcrt-r6), a standalone compiler for Windows. (Build instructions are given in the readme's linked on my forum post.)

What the sample does is creating a frame with a single grid, whose cells each have a custom renderer that prints wxBitmaps for certain text instead of the text itself. The bitmaps were obtained from SVGs, but once rendered, they are stored permanently, so the SVG renderer's speed is not an issue.
On my Windows 7 machine, when I maximize the wx3.1.6 sample, the frame essentially freezes for minutes. Everything works fine for the wx3.1.3 sample. Already on startup, the wx3.1.6 sample takes a while to be initially drawn. When resizing, it gets worse the more rendered images become visible.

I have prevously tried the grid sample, but the effect doesn't seem noticeable for normal text rendering.

**Comment by PBfordev** [comment]
Sorry, but the sample you provided is not of much use. There is so much irrelevant code. This makes it not only difficult (or at least unnecessarily time-expensive) to understand, it also looks suspicious that so much code is needed to reproduce allegedly a simple issue in wxWidgets. Therefore, the motivation for people to spend their time and effort looking into an issue may not be that high.

Why not do what is politely asked when creating an issue and provide just a patch to the grid sample? If the issue is really with just a bitmap renderer, that should be very easy, as this cannot not be related to the bitmap origin nor content.

If you really want to see the issue fixed and want to help with it, it would be great if you did a GIT bisect to find which commit introduced the issue.

**Comment by xamidi** [comment]
That's why I explained what it does. When you remove all the SVG stuff, you could as well define some wxBitmap images and solely use these. I never claimed that so much code is necessary, but I explained the opposite.

I don't really care if it gets fixed since versions 3.1.2 and 3.1.3 can do everything that I wish for, but I thought those who want to use more recent versions would care about the issue. I reported it to help you without gaining anything from it myself.

I am simply not willing to spend more time to create code that really is of no use for any better understanding, just for the sake of having a smaller sample. I mean, one can grasp the issue from reading two sentences that I wrote well enough to write another sample. The community can deal with my information as they wish.

**Comment by vadz** [comment]
Sorry, this is really not useful, I'm not going to download some stuff from mega.nz, whatever it is. If you'd like to help, please run git-bisect between 3.1.3 and 3.1.4 or, at least provide a simple patch that we could use to reproduce the problem. If you don't want to help, so be it, but it's useless to keep this issue opened in this case.

**Comment by xamidi** [comment]
"If you don't want to help, so be it"
I wanted to help and I did. If **you** don't want to help, so be it. Also it is not useless to mention something that doesn't work correctly with your project, since someone might want and be able to fix it. Your aversion against mega.nz is a genetic fallacy btw.
I guess I better won't reproduce and report further bugs on this project, as it is met with ingratitude, devaluation and misleading claims.

**Comment by vadz** [comment]
Sorry, but saying "it doesn't work" without providing any details doesn't help. Generally speaking, and this goes well beyond software bug reporting, it's best to let those you're helping to determine if what you do is helpful or not. If people you think to help tell you that you are not helping, maybe it's best to think about what you're actually doing rather than accuse them of ingratitude.

But well, I'm wasting my time here, don't I.

**Comment by xamidi** [comment]
I provided the details sufficient to tacke the issue. I even created binary showcases (including source code) that can simply be executed to view the issue in action. The effect is pretty obvious.
If you choose to ignore your own bugs, that's on you.

"If people you think to help tell you that you are not helping, maybe it's best to think about what you're actually doing [...]"
I did that and came to the conclusion that you are wrong, which I also provided valid arguments for. Truth is objective, you cannot simply choose it as suits your beliefs. If you are not willing to fix the issue, yes, your are wasting your and my time.

**Comment by xamidi** [comment]
I provided the details sufficient to tackle the issue. I even created binary showcases (including source code) that can simply be executed to view the issue in action. The effect is pretty obvious.
If you choose to ignore your own bugs, that's on you.

"If people you think to help tell you that you are not helping, maybe it's best to think about what you're actually doing [...]"
I did that and came to the conclusion that you are wrong, which I also provided valid arguments for. Truth is objective, you cannot simply choose it as suits your beliefs. If you are not willing to fix the issue, yes, your are wasting your and my time.

**Comment by vadz** [comment]
> I provided the details sufficient to tackle the issue.

Sorry, but this is almost laughably untrue. Maybe I've made a mistake of overestimating your degree of understanding of the open source software development process and, in particular, of how the bugs are fixed. Just in case you really don't know how it happens, let me explain a couple of things that are obvious to me but might not be to you:

1. In theory, saying "your software has a bug" is sufficient to find and fix the bug. In practice, this is never the case and more details are needed.
1. How much more depends on many factors, but, considering that a project like wxWidgets has a practically infinite number of bugs (which is also the case for ~99% of all the other big projects), the developers' focus will always be on the bugs that are the most serious and the easiest to reproduce and debug, so if you're interested in prioritizing the bug you're reporting, it's always better to be as helpful as possible.
1. Being helpful consists in making it as simple as possible for the developers to debug the problem. An example of something helping with it is providing a minimal patch with the smallest possible changes (a.k.a. [SSCCE](https://sscce.org/)). An example of something _not_ helping at all is providing binaries that would have to be built anyhow by anybody debugging the problem. It would have been much better if you spent the time wasted on building and uploading these binaries on doing something more productive, like running `git bisect`, which is another very helpful thing to do for the regressions.

Now please understand me: I'm really not interested in any discussion here and I'm no under illusion that you're going to make an effort and do something really helpful, like producing a SSCCE, running bisect, or actually debugging the problem locally and sharing the results. You've made your position perfectly clear and I don't expect it to change. However the above is, as you say, the objective truth about how things work in practice, whether you like it or not. So I can only hope it will be useful to you, and to any other open source projects that you decide to report the bugs to, in the future.

**Comment by xamidi** [comment]
Stop trying to look as you know anything about algorithms and software, which you clearly don't. Won't waste more time to read your trash. Fuck off.
