### ISSUE TITLE
_w64 can only be specified on int, long, and pointer types

### ISSUE THREAD

**Issue by weather-tracker** [wxWidgets/wxWidgets#22337]
**Describe the bug**
when using the hello world [tuturail](https://docs.wxwidgets.org/trunk/overview_helloworld.html)
i get in the error list in visual studio 2022 

**Expected vs observed behavior**
Please describe what you expected to happen and what actually happens.

I expected no errors. and i get an error.

**Patch or snippet allowing to reproduce the problem**
your code https://docs.wxwidgets.org/trunk/overview_helloworld.html

**Platform and version information**
 - wxWidgets version you use: [latest one in vcpkg]
 - wxWidgets port you use: [windows]
 - OS and its version: [e.g. Windows 10]

**Comment by weather-tracker** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1256	__w64 can only be specified on int, long, and pointer types	wxwindowstest	C:\Dev\vcpkg\installed\x64-windows\include\wx\types.h	375	


copied it directly
cannot build due to the error

**Comment by vadz** [comment]
This is indeed an analyser warning and it probably turns into an error just because you've turned on "SDL checks" option (or it might be on by default in MSVS 2022 for new projects?), so a simple solution is to turn it off in C/C++ compilation options.

And the warning itself should have been fixed by aaa2dabf5df which is part of 3.1.6, so you just need to update to the latest wx version or apply the change of this commit locally.

**Comment by PBfordev** [comment]
> And the warning itself should have been fixed by [aaa2dab](https://github.com/wxWidgets/wxWidgets/commit/aaa2dabf5dfe46b962825bb17eb5a3ffe3aa9dbc) which is part of 3.1.6, so you just need to update to the latest wx version

I understand that vcpkg is not "serviced" by the wxWidgets developer team, still: I have noticed that even though there were some commits yesterday, vcpkg wxWidgets package is still at v3.1.5
https://github.com/microsoft/vcpkg/blob/c25761eb765c380fa70c849795385108a7876eec/ports/wxwidgets/portfile.cmake#L3-L5

I don't know how vcpkg gets notified about a new wxWidgets release, I guess some user must make a PR there ( it took more than month to upgrade to 3.1.5 so perhaps it is more complicated)?
