### ISSUE TITLE
Fix scaling when using wxGraphicsContext under Mac

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22333]
The fix is to override `GetDPI` in `wxMacCoreGraphicsRenderer` and return `72` there. Because currently it uses the common `wxGraphicsContext::GetDPI` code that returns the DPI of the associated `wxWindow`.

_Originally posted by @MaartenBent in https://github.com/wxWidgets/wxWidgets/pull/22314#discussion_r852473514_

**Comment by MaartenBent** [comment]
The font is actually fine, it's everything else that is scaled.

**Comment by vadz** [comment]
So much for understanding the problem...

**Comment by MaartenBent** [comment]
I'm actually not sure if we should override `GetDPI` and always return `72`. Or if `GetDPI` should actually return the DPI of the associated `wxWindow`.
And instead make `GetDPIScaleFactor` virtual and override this in `wxMacCoreGraphicsRenderer` to return `1.0`.


Note, we should also verify `GetDPIScaleFactor` with `wxCairoRenderer`.

**Comment by MaartenBent** [comment]
Proposal in #22346

**Comment by vadz** [comment]
This should have been fixed by 9a36e26d4aac2dfc36de6292775cce11f9107e8f
