### ISSUE TITLE
building wxwidgets from master

### ISSUE THREAD

**Issue by Stormfinger** [wxWidgets/wxWidgets#22332]
**Describe the problem**
i downloaded zip from master branch and according to forum i understand that configure isnt necessary ..

**i executed** 

cd wxwidgets\build\msw\
mingw32-make -f makefile.gcc

**and result is** 

if not exist gcc_mswud mkdir gcc_mswud
if not exist ..\..\lib\gcc_lib mkdir ..\..\lib\gcc_lib
if not exist ..\..\lib\gcc_lib\mswud mkdir ..\..\lib\gcc_lib\mswud
if not exist ..\..\lib\gcc_lib\mswud\wx mkdir ..\..\lib\gcc_lib\mswud\wx
if not exist ..\..\lib\gcc_lib\mswud\wx\setup.h copy ..\..\include\wx\msw\setup.h ..\..\lib\gcc_lib\mswud\wx\setup.h
        1 file(s) copied.
if not exist ..\..\lib\gcc_lib\mswud\wx\msw mkdir ..\..\lib\gcc_lib\mswud\wx\msw
gcc -E  "..\..\include\wx\msw\genrcdefs.h" > "..\..\lib\gcc_lib\mswud\wx\msw\rcdefs.h"
mingw32-make: *** No rule to make target '../../3rdparty/pcre/src/pcre2_auto_possess.c', needed by 'gcc_mswud\wxregex_pcre2_auto_possess.o'.  Stop.

**Platform and version information**
 - wxWidgets version you use: [master]
 - wxWidgets port you use: [e.g. wxMSW]
 - OS and its version: [e.g. Windows 10.0]
 - Compiler being used: [gcc]

**Comment by PBfordev** [comment]
You cannot just download wxWidgets code from GitHub as a zip, the archive unfortunately does not contain code for the GIT submodules (this is a GitHub feature).

If you want to use the master, you need to use GIT (and make sure to checkout submodules),see https://github.com/wxWidgets/wxWidgets/blob/master/README-GIT.md.
