### ISSUE TITLE
error at run

### ISSUE THREAD

**Issue by weather-tracker** [wxWidgets/wxWidgets#22340]
**Describe the bug**

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	wxtesting	C:\Users\me\source\repos\wxtesting	C:\Users\me\source\repos\wxtesting\MSVCRTD.lib(exe_main.obj)	1	

after downloading and fowling the developers part for the release I am getting the above error that prevents me from running.

I have also gone and told it not to use vcpkg manager and manually set the lib ad include folders.

**Patch or snippet allowing to reproduce the problem**
your code at 
https://docs.wxwidgets.org/trunk/overview_helloworld.html

**Platform and version information**
 - wxWidgets version you use: [ 3.1.6]
 - wxWidgets port you use: [windows]
 - OS Windows 10.0]

**Comment by vadz** [comment]
Simply searching for "invoke_main wxWidgets" would have found [this answer](https://stackoverflow.com/a/59859491/15275) and several others, saying the same thing, i.e. that you need to build your application as a Windows, rather than a console, application.

**Comment by weather-tracker** [comment]
thanks that's what there mic docs said but i did not know if this was that was it or one of the many other options.
