### ISSUE TITLE
error building wxwidgets & mingw64  

### ISSUE THREAD

**Issue by codz01** [wxWidgets/wxWidgets#22348]
Hi
i was always been able to build wxwidgets with mingw w64 successfully with this command 
( mingw32-make -f makefile.gcc SHELL=CMD.exe -j2 SHARED=0 MONOLITHIC=1 UNICODE=1 BUILD=release ) until this last release , i got this error

if not exist ..\..\lib\gcc_lib\mswu\wx mkdir ..\..\lib\gcc_lib\mswu\wx
if not exist ..\..\lib\gcc_lib\mswu\wx\setup.h copy ..\..\include\wx\msw\setup.h
 ..\..\lib\gcc_lib\mswu\wx\setup.h
mingw32-make: *** No rule to make target '../../3rdparty/pcre/src/pcre2_auto_pos
sess.c', needed by 'gcc_mswu\wxregex_pcre2_auto_possess.o'.  Stop.
mingw32-make: *** Waiting for unfinished jobs....
        1 file(s) copied.  

any advice to get rid of this error ?

**Comment by vadz** [comment]
You need to get the submodules as explained in the [README](https://github.com/wxWidgets/wxWidgets/blob/master/README-GIT.md).
