### ISSUE TITLE
Argument checking for wxDataViewListCtrl::RowToItem and wxDataViewIndexListModel::GetItem?

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/wxWidgets#22358]
**Problem description:**

`wxDataViewListCtrl::RowToItem` does check for argument `wxNOT_FOUND`, but not for row numbers that are out of range.
For `wxNOT_FOUND` it's rather forgiving and returning an empty `wxDataViewItem`.
For too high row numbers there is an assertion in `GetItem` that will also trigger if `row` is e.g. `-2`.

**Current implementation:**

`include\wx\dataview.h`
```
class WXDLLIMPEXP_CORE wxDataViewListCtrl: public wxDataViewCtrl
{
public:
    wxDataViewItem RowToItem(int row) const
          { return row == wxNOT_FOUND ? wxDataViewItem() : GetStore()->GetItem(row); }
}
```

`src\common\datavcmn.cpp`
```
wxDataViewItem wxDataViewIndexListModel::GetItem( unsigned int row ) const
{
    wxASSERT( row < m_hash.GetCount() );
    return wxDataViewItem( m_hash[row] );
}
```

**Effect on wxPython:**

There is a wxPython bug report where invalid row numbers cause a fatal exception: https://github.com/wxWidgets/Phoenix/issues/2138

When `GetItem` is called with an invalid value, the assertion is triggered, as expected.
The default assertion handling in wxPython is `APP_ASSERT_EXCEPTION`. This sets an exception, but this will only have an effect on return from the C++ call. As there will be an address exception, the application will just crash before the user sees the exception.

As workaround I have tested this:
```
wxDataViewItem wxDataViewIndexListModel::GetItem( unsigned int row ) const
{
    wxASSERT( row < m_hash.GetCount() );
    if (row >= m_hash.GetCount())
        return wxDataViewItem();
    return wxDataViewItem( m_hash[row] );
}
```

What is your opinion on that? I see that `GetItem` is used internally a lot, so probably you would not want additional argument checks there, right? Is there any other way to avoid the address exception? For C++ it's probably not a problem...

**Comment by vadz** [comment]
The workaround is exactly what we need to do, semantically, but there is already a macro which does just that and we simply need to replace `wxASSERT()` in `GetItem()` with
```cpp
wxCHECK_MSG( row < GetCount(), wxDataViewItem(), "invalid index" );
```
I'll push this change in a moment.

**Comment by DietmarSchwertberger** [comment]
Thanks a lot.
