### ISSUE TITLE
Building wxWidgets with clang on Windows

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22363]
Building wxWidgets with clang on MSW is not supported ("Clang under macOS and Linux.") . Nevertheless, I am stuck at home with an injured leg, getting bored, so I tried anyway. :P I am not familiar with clang, so I may be doing something wrong.

I used the current MSYS2 package [mingw-w64-x86_64-clang](https://packages.msys2.org/package/mingw-w64-x86_64-clang) (`clang --version` outputs `clang version 14.0.0`, `Target: x86_64-w64-windows-gnu`, `InstalledDir: C:/msys64/mingw64/bin`). However, it seems to pick my MSVS headers (e.g., from `C:\Program Files (x86)\Windows Kits\10\include\...`) (likely not only) for COM and WinRT stuff? I do not having anything MSVS-related in my PATH.

I used CMake with "MinGW Makefiles" generator and `-DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++` and started shared debug build with this
```
PATH=C:\msys64\mingw64\bin;%PATH%
mingw32-make -f Makefile
```
When compiling the resource file, llvm-rc fails to compile the version resource
```
Building RC object libs/base/CMakeFiles/wxbase.dir/__/__/__/__/src/msw/version.rc.res
llvm-rc: Error in VERSIONINFO statement (ID 1):
Non-ASCII 8-bit codepoint (�) can't be interpreted in the current codepage
mingw32-make[2]: *** [libs\base\CMakeFiles\wxbase.dir\build.make:2060: libs/base/CMakeFiles/wxbase.dir/__/__/__/__/src/msw/version.rc.res] Error 1
mingw32-make[2]: *** Deleting file 'libs/base/CMakeFiles/wxbase.dir/__/__/__/__/src/msw/version.rc.res'
mingw32-make[1]: *** [CMakeFiles\Makefile2:823: libs/base/CMakeFiles/wxbase.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2 
```
I think the simplest solution would be to replace the `©` symbol with `(c)`. I checked a bunch of "big name" DLLs and most did not use the symbol, most use `(c)` or `(C)` after `Copyright`, some use just `Copyright YYYY...`  but some do use the symbol. See [here](https://github.com/curl/curl/issues/7765#issuecomment-927096097) for two alternate (but IMO not obviously superior) solutions.

Unfortunately, there is another resource issue
```
Linking CXX shared library ..\..\lib\clang_x64_dll\wxmsw317ud_core_clang_custom.dll
lld-link: error: /manifestdependency: is not allowed in .drectve
```
This is probably related to MSVC pragma like these https://github.com/wxWidgets/wxWidgets/blob/8245ba96ee5ce3e19564eabc6976435ab9ae906f/include/wx/defs.h#L3213-L3222

Another build failure occurred in Scintilla. 
```
In file included from D:/Dev/Desktop/!Lib/wxWidgets-PB-build-clang_x64_DLL-debug/libs/stc/CMakeFiles/wxscintilla.dir/cmake_pch.hxx:5:
D:/Dev/Desktop/!Lib/wxWidgets-PB/src/stc/scintilla/include/Scintilla.h:40:9: error: unknown type name 'uintptr_t'
typedef uintptr_t uptr_t;
        ^
D:/Dev/Desktop/!Lib/wxWidgets-PB/src/stc/scintilla/include/Scintilla.h:42:9: error: unknown type name 'intptr_t'
typedef intptr_t sptr_t;
        ^
2 errors generated.
mingw32-make[2]: *** [libs\stc\CMakeFiles\wxscintilla.dir\build.make:77: libs/stc/CMakeFiles/wxscintilla.dir/cmake_pch.hxx.pch] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:896: libs/stc/CMakeFiles/wxscintilla.dir/all] Error 2
```

I am Windows only, so I have no idea how the build succeeds on Linux and MacOS which I assume use the bundled Scintilla as well, perhaps the compiler system headers there are different. I think wxWidgets uses no longer supported version of Scintilla (due to being stuck with older C++ standard), so I have no idea how to deal with this.

Even if the Scintilla issue were fixed, there is no guarantee there will not be (many) more build errors uncovered.

Please feel free to close the issue if there is no actual desire to support clang builds on Windows. But perhaps the information here could prove useful in a future... But again, I may be doing something wrong, with clang not being properly identified.

BTW, it is not like wxWidgets build with a modern compiler is warning-free, but with clang there seem to be many more. Unfortunately, I am unable to tell which, if any, are actually useful.

**Comment by MaartenBent** [comment]
I've been building with Clang on MSYS2/MinGW64 for a while, and don't get any of those problems. Do you build in cmd/powershell or the actual MinGW64 console?

```
cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe -DCMAKE_BUILD_TYPE=Release path/to/wxWidgets
cmake --build . --target all -- -j4
```

**Comment by PBfordev** [comment]
I ran the commands posted in my previous post as a batch file. 

However, I was building the default Shared build, which may explain why you did not encounter the resource issues probably manifesting only when building a DLL.

OTOH, I cannot explain the difference in Scintilla build. Unlike you, I built the default Debug build but I don't think this should have any effect. 

I made no changes to CMake except setting the compilers (and used CMake v3.22).

**Comment by PBfordev** [comment]
The clang build on Windows works, the problem was between the chair and keyboard.

 I ran batch file
```
PATH=C:\msys64\mingw64\bin;C:\Program Files\CMake\bin\;%PATH%
cmake-gui -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++
```
and did not check the actual compilers used. For some reason, CMake-GUI picked the compilers from `C:\Program Files\LLVM\bin` folder, which I do not have in PATH (and even forgot I had installed). I should have investigated more after noticing MSVS headers were used.

When the compilers from MSYS2 are used, the build succeeds. I am very sorry for the noise.

BTW, the error 
```
Error copying file "
lib/wx/config/inplace-msw-unicode-3.1" to "D:/Dev/Desktop/!Lib/wxWidgets-PB-build-clang_x64_DLL-debug/wx-config".
```
is still there in CMake-GUI log after generating. There really is a new line after the first quotation mark.

**Comment by MaartenBent** [comment]
Good that it is resolved.

> BTW, the error
> 
> ```
> Error copying file "
> lib/wx/config/inplace-msw-unicode-3.1" to "D:/Dev/Desktop/!Lib/wxWidgets-PB-build-clang_x64_DLL-debug/wx-config".
> ```
> 
> is still there in CMake-GUI log after generating. There really is a new line after the first quotation mark

Yeah, I noticed that too.
I already have a [fix](https://github.com/wxWidgets/wxWidgets/pull/22346/commits/a2ddfcf80b62fb8ec841648e689960c52970a917), part of #22346.

**Comment by vadz** [comment]
Sorry to hear about your leg, I hope it gets fixed too soon!

Other than that, I'd just like to ask where do we say "Clang under macOS and Linux.", as it should probably be extended with "or cross-compiling, including from MSYS2 environment, wxMSW" or something similar.

**Comment by PBfordev** [comment]
> Sorry to hear about your leg, I hope it gets fixed too soon!

Thanks, I hope so too.

> I'd just like to ask where do we say "Clang under macOS and Linux."

It is in the main readme, I assumed Windows was excluded on purpose
https://github.com/wxWidgets/wxWidgets/blob/8245ba96ee5ce3e19564eabc6976435ab9ae906f/README.md?plain=1#L36-L40
