### ISSUE TITLE
Text controls are not properly laid out when the font is changed.

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#22374]
**Describe the bug**
Text controls are not properly sized (in layouts) when the font is changed.

**Expected vs observed behaviour**
The text control should be properly sized on layout. On Windows, this happens. On Mac is does not. The font is properly set, but the height of the control is not adjusted.

**Patch or snippet allowing to reproduce the problem**

Patch against the 'text' sample on the current trunk.
```
diff --git a/samples/text/text.cpp b/samples/text/text.cpp
index 4d40c8dcfb..227990b51b 100644
--- a/samples/text/text.cpp
+++ b/samples/text/text.cpp
@@ -1123,6 +1123,10 @@ MyPanel::MyPanel( wxFrame *frame, int x, int y, int w, int h )
     m_text->SetInsertionPoint(0);
     m_text->WriteText( "Prepended. " );

+    auto font = m_text->GetFont();
+    font.SetPointSize(font.GetPointSize() * 2);
+    m_text->SetFont(font);
+
 #if wxUSE_SPELLCHECK
     if ( m_text->EnableProofCheck(wxTextProofOptions::Default()) )
     {
```

**Platform and version information**
 - wxWidgets 3.1.6 (also happens on trunk)
 - wxWidgets port: wxOSX
 - OS and its version: OSX 12.2 and 10.15

**Comment by vadz** [comment]
@csomor I could be missing something, but I just don't see any `GetBestSize()` implementation for the single-line (`NSField`-based) `wxTextCtrl`. Do we need to implement it on our own or is there some way to get the size taking the font into account from Cocoa?

**Comment by csomor** [comment]
@vadz I assume then that the sizeToFit which should get called from window.mm either is not implemented, or does not take things like font size into account. I'll look what I can find.

**Comment by csomor** [comment]
Ok, I see more clearly now, it's funny, somewhere in the `wxTextWidgetImpl` extraction process, it lost connection to the `wxWindowMac::DoGetBestSize` implementation, I'll add the few lines now to the sublass responsible for the native `NSTextField`, `wxNSTextFieldControl`

**Comment by csomor** [comment]
@dconnet Dave, could you please retest ? Thanks

**Comment by dconnet** [comment]
Confirmed. Also confirmed when applying this patch to 3.1.6.
thx!

**Comment by whalley** [comment]
@csomor I noticed in v3.1.7 that the wxTectCtrl's have more space/padding at the bottom of the textbox than in v3.1.6 - Was this a result of this change? Was it intentional? These now look oddly sized compare to other controls.

See below from the samples/text
![CleanShot 2022-06-07 at 11 45 17@2x](https://user-images.githubusercontent.com/487345/172361942-d0dafac6-d2d3-41cd-bd8d-e757db531faa.png)

**Comment by vadz** [comment]
Seems to be the same problem as in #22498.

**Comment by csomor** [comment]
@dconnet Dave, if you have the time, could you please retest with @23295, I had to introduce a change because of a regression

**Comment by dconnet** [comment]
Looks good to me...
