### ISSUE TITLE
Accelerators don't work correctly anymore due to missing translations

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22388]
Since commit [3396a40](https://github.com/wxWidgets/wxWidgets/commit/3396a400152ba84f32e35dfa2f87af21e97d9657) keyboard key names are translated in a specific context.
But in the absence of such translations, accelerators do not work correctly in languages other than English.
If, for example, a software provides the accelerator `Strg+N` for the German language, this accelerator will take effect if only the `N` key is pressed.

The following changes make the translations of the most important key names (`ctrl`, `alt`, `shift`) effective in the new context so that the accelerators work again.
The same translations are used as previously in wxWidgets-3.1.6.
I did that only for the languages that are relevant for our software, which are: German, French, Italian, Spanish, Dutch, Danish, Czech, Hungarian and Romanian.
<details>
  <summary>Patch to make accelerators work again (in some languages)</summary>
  
 ```patch
diff -r -u -p a/locale/cs.po b/locale/cs.po
--- a/locale/cs.po	2022-05-03 11:26:39.130628800 +0200
+++ b/locale/cs.po	2022-05-03 10:29:24.068128800 +0200
@@ -766,19 +766,16 @@ msgid "Command"
 msgstr "Command"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "shift"
@@ -820,19 +817,16 @@ msgid "SPECIAL"
 msgstr "SPECIÁLNÍ"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Shift+"
diff -r -u -p a/locale/da.po b/locale/da.po
--- a/locale/da.po	2022-05-03 11:26:39.427503800 +0200
+++ b/locale/da.po	2022-05-03 10:28:48.708753800 +0200
@@ -770,19 +770,16 @@ msgid "Command"
 msgstr "Kommando"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "skift"
@@ -822,19 +819,16 @@ msgid "SPECIAL"
 msgstr "SPECIEL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Skift+"
diff -r -u -p a/locale/de.po b/locale/de.po
--- a/locale/de.po	2022-05-03 11:26:39.458753800 +0200
+++ b/locale/de.po	2022-05-03 09:56:04.400296800 +0200
@@ -774,19 +774,16 @@ msgid "Command"
 msgstr "Befehlstaste"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "strg"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "Umschalt"
@@ -804,7 +801,6 @@ msgid "num "
 msgstr "Num "
 
 #: ../src/common/accelcmn.cpp:258 ../src/common/accelcmn.cpp:356
-#, fuzzy
 msgctxt "keyboard key"
 msgid "F"
 msgstr "F"
@@ -828,19 +824,16 @@ msgid "SPECIAL"
 msgstr "SPEZIAL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Strg+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Umschalt+"
diff -r -u -p a/locale/es.po b/locale/es.po
--- a/locale/es.po	2022-05-03 11:26:39.505628800 +0200
+++ b/locale/es.po	2022-05-03 10:01:20.308807800 +0200
@@ -765,19 +765,16 @@ msgid "Command"
 msgstr "Orden"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "mayúsculas"
@@ -817,19 +814,16 @@ msgid "SPECIAL"
 msgstr "ESPECIAL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Mayúsculas+"
diff -r -u -p a/locale/fr.po b/locale/fr.po
--- a/locale/fr.po	2022-05-03 11:26:39.552503800 +0200
+++ b/locale/fr.po	2022-05-03 09:58:33.640748800 +0200
@@ -768,19 +768,16 @@ msgid "Command"
 msgstr "Commande"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "majuscule"
@@ -822,19 +819,16 @@ msgid "SPECIAL"
 msgstr "SPECIAL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Majuscule+"
diff -r -u -p a/locale/hu.po b/locale/hu.po
--- a/locale/hu.po	2022-05-03 11:26:39.615003800 +0200
+++ b/locale/hu.po	2022-05-03 10:45:51.130628800 +0200
@@ -743,19 +743,16 @@ msgid "Command"
 msgstr ""
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "eltol"
diff -r -u -p a/locale/it.po b/locale/it.po
--- a/locale/it.po	2022-05-03 11:26:39.661878800 +0200
+++ b/locale/it.po	2022-05-03 10:27:09.755628800 +0200
@@ -765,19 +765,16 @@ msgid "Command"
 msgstr "Comando"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "maiusc"
@@ -819,19 +816,16 @@ msgid "SPECIAL"
 msgstr "SPECIALE"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Maiusc+"
diff -r -u -p a/locale/nl.po b/locale/nl.po
--- a/locale/nl.po	2022-05-03 11:26:39.724378800 +0200
+++ b/locale/nl.po	2022-05-03 10:28:13.755628800 +0200
@@ -771,19 +771,16 @@ msgid "Command"
 msgstr "Commando"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "shift"
@@ -825,19 +822,16 @@ msgid "SPECIAL"
 msgstr "SPECIAAL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Shift+"
diff -r -u -p a/locale/ro.po b/locale/ro.po
--- a/locale/ro.po	2022-05-03 11:26:39.802503800 +0200
+++ b/locale/ro.po	2022-05-03 11:13:47.427503800 +0200
@@ -767,19 +767,16 @@ msgid "Command"
 msgstr "Command"
 
 #: ../src/common/accelcmn.cpp:186
-#, fuzzy
 msgctxt "keyboard key"
 msgid "ctrl"
 msgstr "ctrl"
 
 #: ../src/common/accelcmn.cpp:188
-#, fuzzy
 msgctxt "keyboard key"
 msgid "alt"
 msgstr "alt"
 
 #: ../src/common/accelcmn.cpp:190
-#, fuzzy
 msgctxt "keyboard key"
 msgid "shift"
 msgstr "shift"
@@ -821,19 +818,16 @@ msgid "SPECIAL"
 msgstr "SPECIAL"
 
 #: ../src/common/accelcmn.cpp:343
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Alt+"
 msgstr "Alt+"
 
 #: ../src/common/accelcmn.cpp:345
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Ctrl+"
 msgstr "Ctrl+"
 
 #: ../src/common/accelcmn.cpp:347
-#, fuzzy
 msgctxt "keyboard key"
 msgid "Shift+"
 msgstr "Shift+"

```
</details>

**Comment by lanurmi** [comment]
This is surprising. Does it also mean that if one does not distribute the `wxstd` translation files with one's product at all, accelerators will always work incorrectly in languages other than English?

I looked at your patch, and at a quick glance it seems for the languages `cs`, `nl`, `ro`, each translation is identical to the source text. Do accelerators really fail to work correctly with these languages without the patch applied?

**Comment by taler21** [comment]
> This is surprising. Does it also mean that if one does not distribute the `wxstd` translation files with one's product at all, accelerators will always work incorrectly in languages other than English?

At least if the accelerator text in the source code (the `msgid`) is in a language other than English.
In my case the texts in the source code are in German.

> I looked at your patch, and at a quick glance it seems for the languages `cs`, `nl`, `ro`, each translation is identical to the source text. Do accelerators really fail to work correctly with these languages without the patch applied?

It seems that the accelerator works correctly for these languages, even if there is no translation.
To be on the safe side, I have made the translations from wxWidgets-3.1.6 effective for all languages that are relevant for our software.
But you are right, for these languages it doesn't seem to be absolutely necessary.

**Comment by vadz** [comment]
Thanks, I'll apply this patch, but I guess we really need to do the same thing for all the other languages too before 3.2.0 (if not before 3.1.7). @lanurmi Please let me know if you plan to do it, TIA!

**Comment by lanurmi** [comment]
I haven't quite understood yet what is happening and how to reproduce it, and I may not have time to look at it in the coming weeks. But still:
* I don't think accelerators working correctly should not be dependent on certain strings to be translated, or on translations existing at all. No other functionality of the library breaks if translations are missing, right?
* If the non-English `msgid`s are the fundamental cause here, could and should the library users themselves ensure that all accelerator translations exist by listing them with `wxTRANSLATE()` in their own code, and having them translated in their own translation files?

**Comment by vadz** [comment]
I didn't test it myself, but I think the OP uses German strings, i.e. `Strg+N` in their source code, which works when `Strg+` is correctly recognized as corresponding to `WXK_CONTROL` modifier in wx code with the correct translations, but not without them. And, to be honest, I don't really see how can using non-English strings in the sources work without translations, so whether we think it "should not" be the case or not, it clearly _is_.

And these translations are not different from any other ones used by wx, i.e., sure, all applications could provide their own, but it's much better if wx provides them on its own once.

**Comment by taler21** [comment]
> Thanks, I'll apply this patch, but I guess we really need to do the same thing for all the other languages too before 3.2.0 (if not before 3.1.7).

In my opinion, all previously effective translations of keyboard key names should be effective again in the new context in order to avoid any regression in 3.1.7.

The following patch does exactly that for **all keyboard key names** (not only `ctrl`, `alt`, `shift`) and for **all languages**.

Patch to make accelerators work again (in all languages): [keyboard-key-translations_patch.zip](https://github.com/wxWidgets/wxWidgets/files/8639743/keyboard-key-translations_patch.zip)

**Comment by vadz** [comment]
Thanks a lot for this patch, this is indeed the best thing to do and I'll merge it in a moment.

Thanks again for fixing this!
