### ISSUE TITLE
AUI Panel's caption title is not shown properly

### ISSUE THREAD

**Issue by Kumazuma** [wxWidgets/wxWidgets#22386]
**Describe the bug**
Aui Panel's caption title is not shown properly.

**Expected vs observed behaviour**
I expect aui panel's caption show title any time. but not now.

**Patch or snippet allowing to reproduce the problem**

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
![Screenshot_20220503_095842](https://user-images.githubusercontent.com/12020335/166391259-7ad77e58-5610-4e55-98b0-2ae6814a7ce6.png)

But 3.0.5 (installed using apt) is show aui panel title properly
![Screenshot_20220503_101531](https://user-images.githubusercontent.com/12020335/166391329-9fc15306-8e67-450f-8099-50767eed6109.png)

**Platform and version information**
 - wxWidgets version you use: 3.1.6, master
 - wxWidgets port you use: wxGTK
 - OS and its version:  Kubuntu 20.04
 - For wxGTK only:
   + GTK version:  gtk3 3.24.20
   + Which GDK backend is used: X11
   + If relevant, i.e. for appearance-related problems: [current theme]

**Comment by vadz** [comment]
I don't see any such problems in the aui sample, so could you please tell us what if there is anything special about your configuration? E.g. do you use high DPI, do you use some non-default theme (and, if so, can you check if you still see the problem with the default one)?

**Comment by Kumazuma** [comment]
@vadz Kubuntu's GTK3 theme was breeze, so I changed to 'default' then solve problem. but I don't know why that result the problem. thank you!

**Comment by vadz** [comment]
Thanks for testing, but it would still be great to understand what the problem is with the "Breeze" them and fix it, if possible. I suspect it could be another problem with the colours but I'm not sure...

**Comment by vadz** [comment]
Could you please check if the problem is still reproducible with this theme using the current master? TIA!

**Comment by Kumazuma** [comment]
In Kubuntu 22.04, Wayland, auidemo is shown properly with the breeze theme in the master branch.
