### ISSUE TITLE
Documentation for wxUILocale::wxUILocale is wrong

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#22389]
**Describe the bug**
The documentation for the constructor says you can create a wxUILocale by:
```
const wxUILocale loc(wxLocaleIdent("fr"));
```

**Expected vs observed behaviour**
Trying to use that results in a compile error.

**Correct documentation**
```
const wxUILocale loc(wxLocaleIdent::FromTag("fr"));
```

**Comment by vadz** [comment]
Thanks for noticing!

I think it should actually be
```
const wxUILocale loc(wxLocaleIdent().Language("fr"));
```
but it's a minor issue, of course. @utelle Do you prefer `FromTag()` or should I modify it like this?

**Comment by utelle** [comment]
> I think it should actually be
> ```
> const wxUILocale loc(wxLocaleIdent().Language("fr"));
> ```
> but it's a minor issue, of course. @utelle Do you prefer `FromTag()` or should I modify it like this?

Well, the most generic form would be `wxLocaleIdent::FromTag()`, but `wxLocaleIdent().Language()` is a legitimate alternative. Maybe showing both forms would be the best option:
```C++
const wxUILocale loc(wxLocaleIdent().Language("fr"));
const wxUILocale loc(wxLocaleIdent::FromTag("fr-FR"));
```

**Comment by utelle** [comment]
Another alternative is

```C++
const wxUILocale loc(wxUILocale::FromTag("fr"));
```
