### ISSUE TITLE
wxGetTimeZone give wrong values with DST

### ISSUE THREAD

**Issue by tohammer** [wxWidgets/wxWidgets#22399]
**Describe the bug**
Calling wxGetTimeZone gives an offset of -3600 (+1h) in TZ CEST. Correct would be +2h beause documentation says:
" Returns the difference between UTC and local time in seconds."

**Patch or snippet allowing to reproduce the problem**
Reproduce by having local TZ set to e.g. CEST and call wxGetTimeZone.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxGTK

**Cause**
wxGetTimeZone in my setup has  WX_GMTOFF_IN_TM set and uses wxLocaltime_r. This gives struct tm with following values:
tm_gmtoff = 7200
tm_isdst = 1
tm_zone = CEST

that means localtime already includes offset for DST but wx is adding it again leading to off by one (hour) issue.

**Comment by tohammer** [comment]
After reviewing the implementations for the other platforms, i think the current behavior is intended but the documentation is misleading because it is not the difference between local and UTC whenever DST is in effect.
Not sure what the current implementation can be used for but maybe it would make sense to also have a function that calculates the diff including dst. 

My current workaround is to use this snippet instead
```cpp
    const auto local = wxDateTime::Now();
    local.ToUTC().Subtract(local).GetSeconds().GetValue();
````

**Comment by vadz** [comment]
Sorry, I didn't have time to look at this yet, but we do have this comment
https://github.com/wxWidgets/wxWidgets/blob/b6fb5109c0500da6b10a6c3c1727a7030caed332/src/common/time.cpp#L142-L144
so it's indeed not supposed to take DST into account.

The documentation should mention this, of course, and we need to make it clear there.
