### ISSUE TITLE
include folder not installed when ./configure in SOURCE DIRECTORY - Fixed, and clarification kindly asked

### ISSUE THREAD

**Issue by Laurent-777** [wxWidgets/wxWidgets#22406]
**Describe the problem**
When I build wxWidgets inside the source directory, and simply running first ./configure, the make install process DOES NOT create AND install the wxWidgets include folder : only bin, lib, and share folders are present. So, no wx subfolder in particular (with wx.h and many others header files) is present, and wxWidgets consequently is misintalled one the one hand, and wxWidgets cannot be properly used on the other.
First, I simply tried to create the include folder inside the installation root directory, and simply glide the include folder inside the source directory to it. But it fails too, as, for example, some header file(s) is (are) missing, such as setup.h.
But this morning -intuition... -, I tried another way that is largely used, namely : to create a BUILD DIRECTORY different from the source one (and NOT in /usr/local, almost 100% are in a non-standard location), and run configure and make install from it. Hopefully, now, I found the include folder inside the installation root directory, and even smaple applications run now pretty fast. Even under Mac OS X Lion ... 

Describe how exactly do you build wxWidgets, including the full `configure`
command line and/or `make` command line if relevant.
N/A

Please attach the full build log, but feel free to quote the relevant parts of
it here.
N/A

When using `configure`, please also attach `config.log` file.
N/A

**Platform and version information**
 - wxWidgets version you use: currently, 2.9.5
 - wxWidgets port you use: Mac OS X Cocoa
 - OS and its version: 10.6.x (Snow Leopard), 10.7.x (Lion, now, 10.7.5), probably beyond (NB XCode 4.6.x for Lion has the Mountain Lion - 10.8.x - SDK).
 - Compiler being used: Clang (XCoded 4.6.x), and to be verified (in progress this weekend) with GCC from 4.9.x to 11.3.0 (the last one : April 2022).

The request : in a/the README or INSTALL file, and after wxWidgets programmers/developers have tested what they may have notice my comments above, please GIVE detailed informations about building wxWidgets in order that  users could build and install correctly and fully your software.

Kind regards,

**Comment by oneeyeman1** [comment]
The official supported way, which is described in documentation is to create a dedicated build directory and run the configure + make + make install from it.

E.g:

cd wxwidgets 
mkdir buildCocoa
cd buildCocoa
../configure && make -j3 && sudo make install.

BTW, the OS version you are using will not be supported with 3.1+. And 10.6 support is dropped in 3.0. I suggest to upgrade to at least 10.10.

This ticket probably should be closed and all future discussion should go on the mailing list.

**Comment by vadz** [comment]
Our CI builds check `make install` and compiling a test application using the installed wx version, so I'm more or less sure that this does work correctly with the current wx version, even if it's possible that it didn't work with (9 year old) 2.9.5.

Please let us know if you still have any problems with any recent wx versions, ideally 3.1.6.
