### ISSUE TITLE
Documentation of predefined colors with wrong description

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22402]
The description of the function `bool wxFromString( const wxString& string, wxColour* colour )` is also displayed as the description for all predefined colors.

This issue appears to exist since wxWidgets-3.1.4 (or maybe 3.1.3, did not check this version).
Anyway, the documentation of wxWidgets-3.1.2 does not display a wrong description.

It can also be seen in the latest [documentation](https://docs.wxwidgets.org/trunk/colour_8h.html#a28c9e9208c4907063eb9869ff2332776).

**Comment by vadz** [comment]
Probably could be fixed by providing some documentation for these objects, but it's really weird that Doxygen copies the description of a function occurring later in a file to the objects before it.

I'd like to switch to Doxygen 1.9 soon (see #18849), will need to check if this fixes it too.
