### ISSUE TITLE
SetCursor() fails during dragging on Mac wxListCtrl

### ISSUE THREAD

**Issue by oneeyeman1** [wxWidgets/wxWidgets#22401]
**Describe the bug**
Setting the cursor for list control on Mac during item dragging does not work - cursor is changing to the ARROW cursor.
Note that setting cursor outside dragging ( during creation) succeeds.

**Expected vs observed behaviour**
Expect to see a cursor that was set

**Patch or snippet allowing to reproduce the problem**
```diff
diff --git a/samples/listctrl/listtest.cpp b/samples/listctrl/listtest.cpp
index 4b2aae9e57..82306846ec 100644
--- a/samples/listctrl/listtest.cpp
+++ b/samples/listctrl/listtest.cpp
@@ -288,7 +288,7 @@ MyFrame::MyFrame(const wxString& title)
     m_logOld = wxLog::SetActiveTarget(new wxLogTextCtrl(m_logWindow));
 
     RecreateList(wxLC_REPORT | wxLC_SINGLE_SEL);
-
+    m_listCtrl->SetCursor( wxCursor( wxCURSOR_HAND ) );
 #ifdef __WXMSW__
     // this is useful to know specially when debugging :)
     wxLogMessage("Your version of comctl32.dll is: %d",
@@ -1156,7 +1156,7 @@ void MyListCtrl::OnColEndDrag(wxListEvent& event)
 void MyListCtrl::OnBeginDrag(wxListEvent& event)
 {
     const wxPoint& pt = event.m_pointDrag;
-
+    SetCursor( wxCursor( wxCURSOR_COPY_ARROW ) );
     int flags;
     wxLogMessage( "OnBeginDrag at (%d, %d), item %ld.",
                   pt.x, pt.y, HitTest(pt, flags) );
```

Patch against list control sample.

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. Run the modified sample
2. Move the cursor in the list control. Observe the cursor is changed to HAND cursor
3. Start dragging the item. Observe that the mouse cursor is changed to ARROW cursor 
and not to DRAG cursor.

On Windows it works as expected (native control)
Didn't try GTK yet.

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 10.13.6
 - For wxGTK only:
   + GTK version: [e.g. 3.24.5]
   + Which GDK backend is used: [X11 or Wayland] Cocoa
   + If relevant, i.e. for appearance-related problems: [current theme] default theme

library configured with:
../configure --enable-debug --with-cocoa --enable-debug_gdb --with-cxx=11

**Comment by oneeyeman1** [comment]
I just tested GTK port and it looks like it is OSX-specific.
At least on GTK + Wayland it works fine (in y program and in the sample).

Thank you.

**Comment by vadz** [comment]
Is this just about `wxCURSOR_COPY_ARROW` being the same as `wxCURSOR_ARROW` (in which case I don't see it as much of a problem) or something else?

[Also edited the report to format the diff properly]

**Comment by oneeyeman1** [comment]
@vadz ,
Yes, apparently they are the same.

OSX have a dedicated cursor for doing the DnD operation (visible in wxDVC), so I thought they are the same.

Sorry for the noise.

Please close.

**Comment by oneeyeman1** [comment]
Is it possible to include the little bitmaps in the https://docs.wxwidgets.org/trunk/gdicmn_8h.html#a90a1eb6d85b5044a99b706fd979f27f5 for cursor table?

Thank you.

**Comment by vadz** [comment]
I have no idea what is this cursor supposed to be, but I'm not too fond of idea of having any cursors that work only under Mac anyhow.

As for the cursor bitmaps, yes, it would be nice to show them just for illustration, but somebody would need to actually do it.
