### ISSUE TITLE
wxToolBar icons  displayed incorrectly under Windows 10 (app without manifest)

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22419]
**Describe the bug**
The page-icons in the wxPropertyGrid not shown under Windows. Under Linux and Wine-Emulation it is working.

**Expected vs observed behaviour**
Page-Icons should be shown vs Black rects are drawn now.

**Patch or snippet allowing to reproduce the problem**

Just create a wxPropertyGrid with at least 2 pages and build for Windows.

**Platform and version information**
 - wxWidgets version you use: 3.1.6 (and GIT devel variant at least from 2022-05-10)
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10

**Comment by vadz** [comment]
Can the problem be seen in the propgrid sample? If not, could you please [make a minimal patch](https://www.wxwidgets.org/develop/how-to-report-issues/) to it allowing to reproduce the problem? TIA!

**Comment by roenck** [comment]
Tried to strip down everything to a minimum.

[MinimalSample.zip](https://github.com/wxWidgets/wxWidgets/files/8672170/MinimalSample.zip)

![PropGrid_Win10](https://user-images.githubusercontent.com/100382302/167910662-26bf7faf-d8b6-4c50-9968-1af04b475b81.png)

![PropGrid_Wine](https://user-images.githubusercontent.com/100382302/167910677-966d5ba4-05ce-47ce-90c6-3fe035faf9fd.png)

**Comment by a-wi** [comment]
This issue can be reproduced even with propgrid sample when application manifest is not present.
So it seems it's not related to wxPropertyGrid itself but probably to wxBitmapBundle/wxImageList.
![pg_test_2](https://user-images.githubusercontent.com/7330332/167951632-057fe1f2-cec3-4a8d-9ee4-bc5238a958ac.png)

With manifest present everything looks good:
![pg_test_3](https://user-images.githubusercontent.com/7330332/167952182-4f56d437-0542-43ad-a196-957f445327b1.png)

**Comment by vadz** [comment]
@a-wi Have you tested with the latest master, i.e. is this the case even with 6feeed9fe9 (Handle transparency to the best of our ability in wxImageList, 2022-05-05)?

**Comment by a-wi** [comment]
Yes. tested with latest master. The issue is seen also with toolbar sample (without manifest):
![toolbar_test_no_manifest](https://user-images.githubusercontent.com/7330332/168013085-5ea51bd9-f55a-4e75-8aaf-7918c057a8c3.png)

**Comment by PBfordev** [comment]
FWIW, without the manifest, the toolbar always had the issue, see e.g. the report with 3.1.1 [here](https://forums.wxwidgets.org/viewtopic.php?t=44550).

**Comment by roenck** [comment]
It's okay for me to link against wx.rc to solve the issue. 

Marginalia: But that is hard to find, especially if it is working with older version without this resource and if the app developer just looks into the example-cpp-source to understand how a widget must used.

**Comment by vadz** [comment]
FWIW this requirement is [documented here](https://docs.wxwidgets.org/3.1/page_port.html#page_port_wxmsw_resources) but it's admittedly not very prominent...
