### ISSUE TITLE
wxDocManager::OnCreateFileHistory won't be called, even not if overriden 

### ISSUE THREAD

**Issue by lhksoft** [wxWidgets/wxWidgets#22410]
I've coded a derived class of wxFileHistory, my goal was to force the FileHistory store/load the MRU using a section like in MyApp.INI 

```
[MRU]
file1=E:\\Video\\Movies.sqlite
...

```
By default all entries are stored in the INI without a section header (like [MRU]).

I thought by deriving a new class from wxDocManager and adding an overriden virtual funtion of 
`virtual wxFileHistory* wxDocManager::OnCreateFileHistory()
`
would do the thrick, I let it return a newly created class I derived from wxFileHistory.
But when I debug the code I saw the original code of wxDocManager gets called and not from my own overridden class..

Maybe it's because it gets called from the Constructor of wxDocManager ??

I've solved it by adding/changing this code in my own, derived class of wxDocManager :

```
lkDocManager::lkDocManager() : wxDocManager(0, false)
{
	m_fileHistory = OnCreateFileHistory();
}

wxFileHistory* lkDocManager::OnCreateFileHistory()
{
	return new lkFileHistory();
}

```

**Patch or snippet allowing to reproduce the problem**
By calling `lkDocManager::lkDocManager() : wxDocManager()` you can see my own derived `OnCreateFileHistory` won't be called.

original located in <wx/common/docview.cpp> at line 977

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.1.5]
 - wxWidgets port you use: wxMSW (and wxGTK)
 - OS and its version: Microsoft Windows [Version 10.0.19044.1645]

**Comment by vadz** [comment]
Yes, calling a virtual function from the base class ctor calls the version present in the already constructed class according to the usual C++ rules.

But the documentation says:

https://github.com/wxWidgets/wxWidgets/blob/b6fb5109c0500da6b10a6c3c1727a7030caed332/interface/wx/docview.h#L356-L360

So I think the current behaviour is already documented sufficiently well and it's difficult to see how to change it without breaking compatibility, so I think there is not much to do here and hence there is no need to keep this issue open.
