### ISSUE TITLE
wxPropertyGrid + Hidden Properties not working after make them 'visible' again

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22425]
**Describe the bug**
I use a wxPropertyGrid, add a page with hidden and non-hidden properties. After an user interaction all properties set to non-hidden and the wxPropertyGridManager->refresh() method is call to made it visible to the user. Mostly the properties are shown (but not all times), but if not enough place within the frame the scrolling area is not updated. Especially the needed size of all properties not recalculated also - which results in drawing errors.

**Expected vs observed behaviour**
Expected: all properties visible after unhide, accessible and scrollable 
Observed: drawing errors, real needed size not recalculated, not scrollable, have to call 'RecalculateVirtualHeight()' by hand to get the needed size recalculated

**Patch or snippet allowing to reproduce the problem**
See attachment, minimalGridSample.
[MinimalSamplePropGrid.zip](https://github.com/wxWidgets/wxWidgets/files/8683089/MinimalSamplePropGrid.zip)

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. Start application (PropGrid already created within the MainWindow-constructor with 100 hidden properties)
2. Go to menu 'Help->About' ... that's unhide all properties
3. Try to scroll down to entry 99 (that is not working until you resize the sub-frame by hand)

**Platform and version information**
 - wxWidgets version you use: 3.1.5 and GIT version (3 days old)
 - wxWidgets port you use: wxMSW and wxGTK
 - OS and its version: Windows 10 and  Ubuntu 20.04

**Comment by a-wi** [comment]
You use wxPGProperty::ChangeFlag() method to hide properties but its [documentation](https://docs.wxwidgets.org/trunk/classwx_p_g_property.html#a8cebe6f162709ab46c878f9c4e7b53a4) says: `"Setting a property flag never has any side-effect, and is intended almost exclusively for internal use."`
To change property state you need to call a dedicated method, e.g. to hide property you need to call wxPGProperty::Hide() method.
