### ISSUE TITLE
Width of choice box for zoom in print preview too small

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22439]
Is there a good reason why the width of the `wxChoice` with the zoom levels is hardcoded?
In my opinion `wxDefaultSize` should be used, so that the `wxChoice` is sized according to its content.

```patch
diff --git "a/src/common/prntbase.cpp" "b/src/common/prntbase.cpp"
index 3089d00202..d44e99da15 100644
--- "a/src/common/prntbase.cpp"
+++ "b/src/common/prntbase.cpp"
@@ -1614,7 +1614,7 @@ void wxPreviewControlBar::CreateButtons()
         };
         int n = WXSIZEOF(choices);
 
-        m_zoomControl = new wxChoice( this, wxID_PREVIEW_ZOOM, wxDefaultPosition, wxSize(FromDIP(70),wxDefaultCoord), n, choices, 0 );
+        m_zoomControl = new wxChoice( this, wxID_PREVIEW_ZOOM, wxDefaultPosition, wxDefaultSize, n, choices, 0 );
         sizer.Add(m_zoomControl);
         SetZoomControl(m_printPreview->GetZoom());
 

```

Currently on some systems the box is too small.
For example under openSUSE 42.3 (KDE desktop with 'Adwaita' theme for GTK applications):
![print-preview-zoom-box-orig](https://user-images.githubusercontent.com/99262969/169275844-790a575e-db7c-4b73-80f4-d30e6854e4ba.png)

With my proposed changes it looks like this:
![print-preview-zoom-box-fixed](https://user-images.githubusercontent.com/99262969/169275882-049188c9-3e2b-471d-a8a8-44348b030fab.png)

By the way, what can also be seen is that the default width of the entire `wxPreviewControlBar` is too small, although sizers are used.
Any idea why?

**Comment by vadz** [comment]
Yes, hard-coded `70` here is clearly wrong, I'll remove it, thanks! Amazingly, it seems to have survived since 9dff851556 (Use sizers, not constraints, 2003-04-17) which added this code...

As for the total size being too small, it's due to hard-coding it again, this time in the sample code. However just removing the hard-coded size is not enough, so I had to also make a couple of other changes to let the frame have a reasonable size by default.

All of those are part of #22441, please let me know if you see any problems with it. TIA!

**Comment by taler21** [comment]
No problems, looks good now. Thanks!
There is only one minor thing, I am nitpicking now.
In case the `wxPreviewControlBar` needs more space than the default width of the preview window, there is no space between the last two buttons.
![print-preview-PR-orig](https://user-images.githubusercontent.com/99262969/169474737-2550dd6b-bf32-4143-93e7-868557fd1b72.png)

Therefore I suggest to ensure a minimum space before the Close button.

This can be achieved by at least adding a border on its left side as well:
```patch
diff --git "a/src/common/prntbase.cpp" "b/src/common/prntbase.cpp"
index 48413c05d1..f2dce3fe30 100644
--- "a/src/common/prntbase.cpp"
+++ "b/src/common/prntbase.cpp"
@@ -1530,7 +1530,7 @@ public:
     {
         m_sizer->AddStretchSpacer();
         m_sizer->Add(win,
-                     wxSizerFlags().Border(wxTOP | wxBOTTOM | wxRIGHT).Center());
+                     wxSizerFlags().Border(wxALL).Center());
     }
 
     // Indicates the end of a group of buttons, a separator will be added after

```
![print-preview-PR-CloseBtn-border-space](https://user-images.githubusercontent.com/99262969/169474791-e71b3d2b-4b01-40b2-b1f3-0127d53d6904.png)

Or, to make it perfect, the same space as between the other groups should be used as the minimum space:
```patch
diff --git "a/src/common/prntbase.cpp" "b/src/common/prntbase.cpp"
index 48413c05d1..23562d6ece 100644
--- "a/src/common/prntbase.cpp"
+++ "b/src/common/prntbase.cpp"
@@ -1528,9 +1528,10 @@ public:
     // as everything else added after it will be added on the right side too.
     void AddAtEnd(wxWindow *win)
     {
+        m_sizer->AddSpacer(2*wxSizerFlags::GetDefaultBorder());
         m_sizer->AddStretchSpacer();
         m_sizer->Add(win,
-                     wxSizerFlags().Border(wxTOP | wxBOTTOM | wxRIGHT).Center());
+                     wxSizerFlags().Border(wxALL).Center());
     }
 
     // Indicates the end of a group of buttons, a separator will be added after

```
![print-preview-PR-CloseBtn-group-space](https://user-images.githubusercontent.com/99262969/169474833-720a1a41-3d67-405b-9760-b47c41a42f80.png)

**Comment by vadz** [comment]
Thanks, I've updated #22441 with your border fix.

**Comment by taler21** [comment]
Isn't it wrong to call `wxPreviewFrame::Centre()` before `wxPreviewFrame::Initialize()`, as done in both the printing sample and the example code in the documentation?

The elements of the `wxPreviewFrame` are not created until `wxPreviewFrame::InitializeWithModality()` is called directly or indirectly via `wxPreviewFrame::Initialize()`.
How can the preview window be centered when its elements have not yet been created?

So I think the order of the two function calls should be reversed, right?

```patch
 docs/doxygen/overviews/printing.h | 2 +-
 samples/printing/printing.cpp     | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/docs/doxygen/overviews/printing.h b/docs/doxygen/overviews/printing.h
index 9444464e31..caecda75ac 100644
--- a/docs/doxygen/overviews/printing.h
+++ b/docs/doxygen/overviews/printing.h
@@ -56,8 +56,8 @@ case WXPRINT_PREVIEW:
     wxPrintPreview *preview = new wxPrintPreview(new MyPrintout, new MyPrintout);
     wxPreviewFrame *frame = new wxPreviewFrame(preview, this,
                                                "Demo Print Preview");
-    frame->Centre(wxBOTH);
     frame->Initialize();
+    frame->Centre(wxBOTH);
     frame->Show(true);
     break;
 }
diff --git a/samples/printing/printing.cpp b/samples/printing/printing.cpp
index f2516eed61..a9d847b7b5 100644
--- a/samples/printing/printing.cpp
+++ b/samples/printing/printing.cpp
@@ -391,8 +391,8 @@ void MyFrame::OnPrintPreview(wxCommandEvent& WXUNUSED(event))
     }
 
     wxPreviewFrame *frame = new wxPreviewFrame(preview, this, "Demo Print Preview");
-    frame->Centre(wxBOTH);
     frame->InitializeWithModality(m_previewModality);
+    frame->Centre(wxBOTH);
     frame->Show();
 }
 
@@ -425,8 +425,8 @@ void MyFrame::OnPrintPreviewPS(wxCommandEvent& WXUNUSED(event))
     wxPrintDialogData printDialogData(* g_printData);
     wxPrintPreview *preview = new wxPrintPreview(new MyPrintout(this), new MyPrintout(this), &printDialogData);
     wxPreviewFrame *frame = new wxPreviewFrame(preview, this, "Demo Print Preview");
-    frame->Centre(wxBOTH);
     frame->Initialize();
+    frame->Centre(wxBOTH);
     frame->Show();
 }
 

```

**Comment by vadz** [comment]
You're right, thanks, I'll add this to the PR too.
