### ISSUE TITLE
wxGrid: assertion when dragging row/col 0 to corner label window

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/wxWidgets#22432]
This can be reproduced in the grid sample:
 - enable row or col moving
 - drag the first row or col to the corner label window
 - an assertion is triggered

I think this is due to PR #22292 enabling mouse capture when dragging a row or col.
Previously drag moving was ended when the label window was left and therefore a LeftUp with row or col == -1 would not have occurerd.

I will work on this. It needs to be fixed for 3.1.7.

**Comment by vadz** [comment]
Thanks for finding it and working on it!

**Comment by DietmarSchwertberger** [comment]
PR is prepared.

I found the issue while looking for a better solution of the drop position check.
Currently a `DoEndMove` is called even for situations where finally no row is moved, e.g. when dragging a row to the first half of the next one or the second half of the previous one.
Still haven't found a nice implementation for this....

**Comment by vadz** [comment]
FWIW I think we do need to call `DoEndMove()` in any case, as it resets `m_dragMoveRowOrCol`. But we probably shouldn't send the event, nor call `Set{Row,Col}Pos()` if the position didn't really change, should we?

**Comment by DietmarSchwertberger** [comment]
Maybe.
Currently it's not called if `line == m_dragMoveRowOrCol`.
The check whether a move will happen is also required for deciding whether the insertion marker needs to be blue or grey. Currently it will often be drawn blue if the mouse is outside the original row/col.
