### ISSUE TITLE
wxWidgets 3.1.6 linker error in Xcode / wxcocoa.xcodeproj / core target

### ISSUE THREAD

**Issue by eb1** [wxWidgets/wxWidgets#22445]
**Describe the problem**
Using Xcode 13.3.1 on Apple silicon (macOS 12.3.1), the core target gets linker errors for a few `wxFSVolume` and `wxFSVolumeBase` methods.

[Build target core_2022-05-20T17-22-58.txt](https://github.com/wxWidgets/wxWidgets/files/8744821/Build.target.core_2022-05-20T17-22-58.txt)

```
> Undefined symbols for architecture x86_64:
  "wxFSVolume::InitIcons()", referenced from:
      wxFSVolume::wxFSVolume(wxString const&) in dirctrlg.o
  "wxFSVolumeBase::GetVolumes(int, int)", referenced from:
      wxGetAvailableDrives(wxArrayString&, wxArrayString&, wxArrayInt&) in dirctrlg.o
  "wxFSVolumeBase::wxFSVolumeBase(wxString const&)", referenced from:
      wxFSVolume::wxFSVolume(wxString const&) in dirctrlg.o
  "wxFSVolumeBase::GetKind() const", referenced from:
      wxGetAvailableDrives(wxArrayString&, wxArrayString&, wxArrayInt&) in dirctrlg.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure if this is related to the build issue that @guzmanpaco ran into here: https://github.com/wxWidgets/wxWidgets/issues/22173#issuecomment-1075737208

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 12.3.1, running on Apple silicon (M1 Pro / MB Pro) 
 - Compiler being used: clang IIRC (whatever's the default for the wxcocoa Xcode project)

**Comment by vadz** [comment]
I think this should have been fixed by 533958be10 (recreating Xcode project files with new script, 2022-04-16), please check the latest Git or 3.1.7 when it's released.

**Comment by eb1** [comment]
Just verified that the latest Git source does fix the linker errors in the wxcocoa.xcodeproj / core target. Thanks for the quick turnaround!

**Comment by DmitriyyyyS** [comment]
I faced the same problem, the solution worked for me too.
