### ISSUE TITLE
First and last point of a polygon are not closed correctly (GTK3)

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22440]
Drawing a rectangle with `wxDC::DrawPolygon(...)` does not lead to a clean result with GTK3.

With GTK2 the result is as expected:
![rectangle-polygon-gtk2](https://user-images.githubusercontent.com/99262969/169302641-458939f2-28d2-41a2-9962-c7a4598d888a.png)

But with GTK3 the result looks like this:
![rectangle-polygon-gtk3](https://user-images.githubusercontent.com/99262969/169302694-ce32ddbd-c035-4002-b6a9-ef090349c6ff.png)

This issue can be reproduced with the **drawing sample** using the following modifications:

<details>
  <summary>patch for drawing sample</summary>
  
```patch
diff --git "a/samples/drawing/drawing.cpp" "b/samples/drawing/drawing.cpp"
index f6a102dd23..190959c430 100644
--- "a/samples/drawing/drawing.cpp"
+++ "b/samples/drawing/drawing.cpp"
@@ -604,6 +604,29 @@ void MyCanvas::DrawTestPoly(wxDC& dc)
     int count[2] = {5, 5};
 
     dc.DrawPolyPolygon(WXSIZEOF(count), count, star2, dc.FromDIP(450), dc.FromDIP(150));
+
+    wxPen pen( *wxBLACK, 30, wxPENSTYLE_SOLID );
+    pen.SetCap( wxCAP_BUTT );
+
+    dc.SetBrush( *wxTRANSPARENT_BRUSH );
+
+    wxPoint rect[4];
+    rect[0] = dc.FromDIP(wxPoint(0, 0));
+    rect[1] = dc.FromDIP(wxPoint(0, 100));
+    rect[2] = dc.FromDIP(wxPoint(100, 100));
+    rect[3] = dc.FromDIP(wxPoint(100, 0));
+
+    pen.SetJoin( wxJOIN_BEVEL );
+    dc.SetPen( pen );
+    dc.DrawPolygon( WXSIZEOF(rect), rect, dc.FromDIP(50), dc.FromDIP(300) );
+
+    pen.SetJoin( wxJOIN_MITER );
+    dc.SetPen( pen );
+    dc.DrawPolygon( WXSIZEOF(rect), rect, dc.FromDIP(200), dc.FromDIP(300) );
+
+    pen.SetJoin( wxJOIN_ROUND );
+    dc.SetPen( pen );
+    dc.DrawPolygon( WXSIZEOF(rect), rect, dc.FromDIP(350), dc.FromDIP(300) );
 }
 
 void MyCanvas::DrawTestLines( int x, int y, int width, wxDC &dc )

```
</details>

**To Reproduce**
1. Start the sample.
2. Press F5 to display the Polygons screen.

**Platform and version information**
 - wxWidgets version you use: Latest master ([754aed4](https://github.com/wxWidgets/wxWidgets/commit/754aed4d7b9afc94e7db43b4bff97d3562013fd6))
 - wxWidgets port you use: wxGTK
 - OS and its version: openSUSE Leap 42.3
 - For wxGTK only:
   + GTK version: 3.20.10
   + Which GDK backend is used: X11

**Comment by vadz** [comment]
Didn't have time to test yet, but I wonder if adding a call to `CloseSubpath()` to `wxGraphicsContext::DrawLines()` in `src/common/graphcmn.cpp` could help?

**Comment by vadz** [comment]
I've tested it now and adding it does fix the problem, so I'm going to push this.

Thanks for providing a nice patch for testing!

**Comment by taler21** [comment]
Great. Many thanks for this quick fix!
