### ISSUE TITLE
Errors while compiling Xcode

### ISSUE THREAD

**Issue by DmitriyyyyS** [wxWidgets/wxWidgets#22446]
Hello, please tell me, during the compilation of wxcocoa.xcodeproj I catch errors, how to deal with them?

<img width="1103" alt="1" src="https://user-images.githubusercontent.com/49454993/169647197-34cd2f0c-6956-4392-828c-d835513aa6e5.png">

**Comment by vadz** [comment]
See #22445.

Please search for your issue before opening a new one and *please* don't post images but copy and paste the errors text instead. TIA!
