### ISSUE TITLE
Crash on ribbon sample

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#22459]
**Describe the bug**
Ribbon sample crashes always when following a simple click sequence.

**Expected vs observed behaviour**
No crash vs crash

**Patch or snippet allowing to reproduce the problem**
Not needed

**To Reproduce**
1. Select "Another page"
2. Click on Remove, then on Hide, then on Show and finally on +/-
3. Crash - segmentation fault on OnPlusMinus()

**Platform and version information**
 - wxWidgets version you use: 3.1.5 and yesterday master
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 7 SP1 64 bits

**Comment by wh11204** [comment]
Just clicking on Remove and then on +/- is enough...

**Comment by wh11204** [comment]
Other crash, now on OnChangeLabel(), when clicking on Remove and then on Short.

**Comment by MaartenBent** [comment]
I can reproduce this. Apparently `m_mutable_button_bar` is not mutable. Replacing it with `evt.GetBar()` fixes it. I can create a PR to fix this.

**Comment by wh11204** [comment]
Thank you for testing.

So, if I understand correctly, deleting the last page invalidates the saved pointers to members of other pages?. This is unexpected and IMHO it should be documented.
