### ISSUE TITLE
Command line help ambiguous?

### ISSUE THREAD

**Issue by MortenMacFly** [wxWidgets/wxWidgets#22454]
If you define a command line parameter like:
`{ wxCMD_LINE_OPTION, "f", "file", "Specify a file", wxCMD_LINE_VAL_STRING, wxCMD_LINE_PARAM_OPTIONAL | wxCMD_LINE_NEEDS_SEPARATOR },`

...the command:
`wxCmdLineParser::GetUsageString()`

Shows as help:
```
Usage: Tool [/f <str>]
  /f, --file=<str> 	Specify a file
```
...which IMHO is somewhat ambiguous. It's unclear if equal signs are allowed, disallowed, or required.

Wouldn't it be better to show that help in a more consistent manner?
And what is the expected/recommended syntax actually? :-)

(wxWidgets MSW v3.1.6 on Windows 10)

**Comment by vadz** [comment]
This is a pretty standard way to show the options, e.g. GNU programs do about the same thing. I'm not really sure how could this be improved.

And the syntax is flexible, i.e. `=` is allowed but not required, so it's not like it really matters this much anyhow.

I don't think it's useful to keep this open, as I don't think we're going to do anything about it, but please let me know if you disagree.
