### ISSUE TITLE
Artifacts in wxStyledTextCtrl with wxGTK 3.0.5

### ISSUE THREAD

**Issue by janp20** [wxWidgets/wxWidgets#22469]
Hi,

I am using wxgtk 3.0.5 on Arch (the package supplied by the distribution). The apps using it often show green squares somewhere inside the window.
I am attaching an example from codelite but there are other apps that link WX that show the same problem so I guess that the problem is there. All the other apps behave correctly.  
Maybe it's unrelated, but I add that I am using a Radeon RX5600 XT graphics card, and had similar problems, related to this specific card, that has been solved by fixes in the Mesa Opengl software.
Thanks
![codelite_artifacts3](https://user-images.githubusercontent.com/63359862/170841217-be8a6541-3ca5-49cd-9b61-4eedb792d46b.gif)

.

**Comment by vadz** [comment]
Sorry, really no idea what could be causing this. The first steps towards debugging this would be to

1. Build the sample using the problematic `wxStyledTextCtrl` control (`samples/stc` in wx source tree) and check if it happens in it.
2. If it does, check if it also still happens with wx 3.1.6 or current Git master.

Could be also worth checking if it only happens with X11 (which you probably use with wx 3.0) or if it also happens with Wayland.

**Comment by janp20** [comment]
> Sorry, really no idea what could be causing this. The first steps towards debugging this would be to
> 
>     1. Build the sample using the problematic `wxStyledTextCtrl` control (`samples/stc` in wx source tree) and check if it happens in it.
> 
>     2. If it does, check if it also still happens with wx 3.1.6 or current Git master.
> 
> 
> Could be also worth checking if it only happens with X11 (which you probably use with wx 3.0) or if it also happens with Wayland.

Hi, 

I built the sample both under 3.1.6 and 3.0.5 and had no problems. I noticed that 3.0.5 version uses gtk2 (libwx_gtk2u_core-3.0.so.0 ...) and not gtk3. 
I am using X11 but managed to test Codelite under Wayland (launching the application from inside Weston) and works fine (no artifacts).
I add that the artifacts can be seen in Filezilla and Codeblocks but not in wxMaxima and Audacity. 
Moreover they appear also in the print dialog in Libreoffice which, AFAIK, is not a wxWidgets based application.
So it could be that, while is more frequent in wx apps, the problem is in the gtk3 subsystem and maybe tied to the hardware.

Thank, you

**Comment by vadz** [comment]
Thanks for the update, this is definitely not a wx problem then as the print dialog is not a wx one. I don't know if it's hardware (looks likely to me) or video driver or something else, but it's clearly not something related to what we do.
