### ISSUE TITLE
wxSocket Server debug alert - failed

### ISSUE THREAD

**Issue by alex290** [wxWidgets/wxWidgets#22463]
**Describe the bug**

When the server starts **[example](https://github.com/wxWidgets/wxWidgets/blob/master/samples/sockets/server.cpp)**, a message is displayed

`wxWidgets/include/wx/private/sckaddr.h(299): assert = static_cast<int>(m_familу) == AddressFamily<T>::value = failed in Get(): socket address family mismatch`

![](https://i.imgur.com/oC9mH4o.png)

After this error continues to work

![](https://i.imgur.com/x0GbhZk.png)

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.1.6]
 - OS and its version: [e.g. Windows 10.0.19042.867]

**Comment by vadz** [comment]
Thanks, I see this too, will push a fix soon.
