### ISSUE TITLE
wxWizard crash on MacOS second screen (DPI switch issue?)

### ISSUE THREAD

**Issue by whalley** [wxWidgets/wxWidgets#22471]
**Describe the bug**
Crash when attempting to center wxWizard on MacOS second screen. Failure occurs in WXHandleDPIChanged, the monitors do indeed have different DPIs. See dump attached.

[error_dump.txt](https://github.com/wxWidgets/wxWidgets/files/8795873/error_dump.txt)

**Expected vs observed behaviour**
Works fine on the primary monitor, but when invoked on the second monitor it fails. Should work on all monitors.

Using empty wxBitmapBundle() on wxWizard creation works but if an image is supplied the bug occurs.

**Patch or snippet allowing to reproduce the problem**

The following change to the `samples/wizard/wizard.cpp `will produce this.

```
--- a/samples/wizard/wizard.cpp
+++ b/samples/wizard/wizard.cpp
@@ -424,6 +424,7 @@ MyWizard::MyWizard(wxFrame *frame, bool useSizer)
         // allow the wizard to size itself around the pages
         GetPageAreaSizer()->Add(m_page1);
     }
+    CentreOnParent();
 }
 
 // ----------------------------------------------------------------------------
```

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 12.4 (same on 12.3 also)

**Comment by vadz** [comment]
Thanks for reporting this!

It looks like `m_page` is null in `wxWizard::WXHandleDPIChanged()`, so I'll add a check for this.

**Comment by whalley** [comment]
Thanks, that fixed it.
