### ISSUE TITLE
Display glitches while drawing on wxGCDC in wxScrolled window

### ISSUE THREAD

**Issue by a-wi** [wxWidgets/wxWidgets#22480]
**Describe the bug**
The output of drawing on `wxGCDC` in `wxScrolled<wxWindow>` is damaged while scrolling the content of the window.
Git bisect shows the issue is introduced in 4f9186f1a15986ed3390c3e8a024d21157030222.
 
**Patch or snippet allowing to reproduce the problem**
The issue can be reproduced in the scroll sample with applied this patch:
```diff --git a/samples/scroll/scroll.cpp b/samples/scroll/scroll.cpp
--- a/samples/scroll/scroll.cpp
+++ b/samples/scroll/scroll.cpp
@@ -25,6 +25,7 @@
 // ----------------------------------------------------------------------------
 // a trivial example
 // ----------------------------------------------------------------------------
+#include "wx/dcgraph.h"
 
 // MySimpleCanvas: a scrolled window which draws a simple rectangle
 class MySimpleCanvas : public wxScrolled<wxWindow>
@@ -61,6 +62,10 @@ private:
         dc.SetPen( *wxRED_PEN );
         dc.SetBrush( *wxTRANSPARENT_BRUSH );
         dc.DrawRectangle( 0, 0, WIDTH, HEIGHT );
+
+        wxGCDC gdc(dc);
+        gdc.SetBrush(wxBrush(wxColour(0, 255, 0, 64)));
+        gdc.DrawRectangle(wxRect(20, 20, 100, 100));
     }
 };
 
```

**To Reproduce**
While opening the scrolled window (Test -> Simple scroll window) the rectangle is drawn properly:
![gcdc_initial](https://user-images.githubusercontent.com/7330332/171284093-25f240cd-7001-40a3-ae7e-4ca66a3c3b90.png)
After scrolling the content down and up, drawn rectangle is displayed improperly:
![gcdc_scrolled](https://user-images.githubusercontent.com/7330332/171284583-dbc04681-56e2-48ee-b333-1e1aecd016ee.png)

**Platform and version information**
 - wxWidgets version you use: master
 - wxWidgets port you use: wxMSW
 - Windows 10

**Comment by vadz** [comment]
Thanks, I can reproduce it too. It seems to be related to not setting the device origin correctly for `wxGCDC`, but I'm not sure what's the best way to fix this yet...

**Comment by vadz** [comment]
It looks like there is more than one problem here because even inserting `PrepareDC(gdc);` doesn't fix the problem. I thought it could be due to something being wrong with clipping, but this doesn't seem to be the case neither.

Right now I have no idea at all about what is going wrong here, but we may need to revert 4f9186f1a15986ed3390c3e8a024d21157030222 if I can't find how to fix it because this is a really bad problem. Any ideas/help would be very welcome.

For the record, `git revert -n c0b7240dfb 7eb5e99cac 4f9186f1a` does fix the problem with GDI+, but using Direct2D renderer is still broken, even after reverting, as can be seen by using
```cpp
        wxGCDC gdc(wxGraphicsRenderer::GetDirect2DRenderer()->CreateContext(dc));
```
instead of `gdc(dc)` ctor.

**Comment by vadz** [comment]
The weirdest thing is that this:
```diff
diff --git a/src/msw/graphics.cpp b/src/msw/graphics.cpp
index 360d570c27..359ccfb0c2 100644
--- a/src/msw/graphics.cpp
+++ b/src/msw/graphics.cpp
@@ -1865,6 +1865,10 @@ wxGDIPlusContext::wxGDIPlusContext( wxGraphicsRenderer* renderer, const wxDC& dc
     HDC hdc = (HDC) dc.GetHDC();
     wxSize sz = dc.GetSize();
 
+    const wxPoint origin = dc.GetDeviceOrigin();
+    if ( origin.x || origin.y )
+        ::SetViewportOrgEx(hdc, origin.x, origin.y, NULL);
+
     Init(new Graphics(hdc), sz.x, sz.y);
 }
 
```
works (but is limited to 2^27, of course), but this
```diff
diff --git a/src/msw/graphics.cpp b/src/msw/graphics.cpp
index 360d570c27..ffdf64a6f6 100644
--- a/src/msw/graphics.cpp
+++ b/src/msw/graphics.cpp
@@ -1866,6 +1866,10 @@ wxGDIPlusContext::wxGDIPlusContext( wxGraphicsRenderer* renderer, const wxDC& dc
     wxSize sz = dc.GetSize();
 
     Init(new Graphics(hdc), sz.x, sz.y);
+
+    const wxPoint origin = dc.GetDeviceOrigin();
+    if ( origin.x || origin.y )
+        m_context->TranslateTransform(origin.x, origin.y);
 }
 
 wxGDIPlusContext::wxGDIPlusContext( wxGraphicsRenderer* renderer,
```
does not, i.e. it's still easily possible to have gaps in the green rectangle by scrolling up and down. Apparently GDI+ does something different if the DC is shifted originally, but I have no idea what.

Doing the former is still better than nothing and should fix the regression, but there is still something I don't understand here.
