### ISSUE TITLE
Using the wxID_SAVE in wxLogWindow can prevent saving log

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#22486]
**Describe the bug**
Since wxLogWindow uses the standard menu id, you can only save the log if the associated program allows saving.

**Expected vs observed behaviour**
The log should always be able to be saved

**Fix**

Add EVT_UPDATE_UI handler that sets Enable(true). (Patch attached)

[logg.txt](https://github.com/wxWidgets/wxWidgets/files/8838367/logg.txt)

**Comment by vadz** [comment]
I think a better fix is to use `wxWS_EX_BLOCK_EVENTS` (which arguably should be the default...) for this frame, i.e.
```diff
diff --git a/src/generic/logg.cpp b/src/generic/logg.cpp
index 61700202bb..3e7102cc97 100644
--- a/src/generic/logg.cpp
+++ b/src/generic/logg.cpp
@@ -488,6 +488,9 @@ class wxLogFrame : public wxFrame
 wxLogFrame::wxLogFrame(wxWindow *pParent, wxLogWindow *log, const wxString& szTitle)
           : wxFrame(pParent, wxID_ANY, szTitle)
 {
+    // We don't want our parent frame getting any events from us.
+    SetExtraStyle(GetExtraStyle() | wxWS_EX_BLOCK_EVENTS);
+
     m_log = log;
 
     m_pTextCtrl = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition,
```

I'll commit this soon.

**Comment by dconnet** [comment]
Ah, didn't know about that style. I agree, that's better.
