### ISSUE TITLE
Weird MinGW64 GCC 12.1.0 and wxString usage in std::vector wx app build bug

### ISSUE THREAD

**Issue by stahta01** [wxWidgets/wxWidgets#22483]
I discovered an GCC 12.1.0 wxWidgets application silent build failure while Building KiCAD 6.0 or 6.99.

I was able to duplicate the problem using wxWidgets minimal sample by including the kicad headers that trigger the silent build error. GCC fails to build the object file; but, reports no error.
gcc.exe (Rev2, Built by MSYS2 project) 12.1.0

[KICAD's bitmaps/bitmap_info.h](https://github.com/KiCad/kicad-source-mirror/blob/master/include/bitmaps/bitmap_info.h)
[KICAD's bitmaps/bitmaps_list.h](https://github.com/KiCad/kicad-source-mirror/blob/master/include/bitmaps/bitmaps_list.h)

The problem only happens because the number of entries in std::vector is so many.
Cutting the number to about 1/3 fixed the issue.
Replacing wxString with std::string fixed the issue.
I consider this an issue that could be fixed just by documentation.
For that matter it might already be documented somewhere.

Tim S.

**Comment by vadz** [comment]
I don't think it's a wx problem. The compiler is probably running out of some resource (memory would be the most likely candidate, although I have no idea why would it need so much of it to compile something relatively simple like this) and fails to handle the error properly, which is a compiler bug and so should be reported to MinGW project (or gcc if it can be reproduced with gcc under Linux too). But I really don't think there is anything to be done here on our side, sorry.

**Comment by stahta01** [comment]
Sounds like a likely possible cause.
