### ISSUE TITLE
wxImage fails to load certain bitmaps

### ISSUE THREAD

**Issue by adrianlopezroche** [wxWidgets/wxWidgets#22499]
Using wxWidgets 3.1.7, wxImage::LoadFile() fails to load some bitmaps that used to load without any problems under wxWidgets 3.0.4. I am attaching a program and sample images below. The output under wxWidgets 3.0.4 is as follows:

```
test1.bmp ok
test2.bmp ok
test3.bmp ok
test4.bmp ok
test5.bmp ok
test6.bmp ok
test7.bmp ok
test8.bmp ok
```
The output under wxWidgets 3.1.7 is as follows:

```
test1.bmp ok
test2.bmp ok
test3.bmp ok
test4.bmp ok
test5.bmp failed
test6.bmp failed
test7.bmp failed
test8.bmp failed
```
Environment:
Linux Mint 20
wxWidgets 3.1.7
wxGTK
GTK 3.24.20

Attachments: [wxImageLoadTest.zip](https://github.com/wxWidgets/wxWidgets/files/8856868/wxImageLoadTest.zip)

**Comment by Randalphwa** [comment]
I opened up test5.bmp in 4 different non-wxWidgets apps, and none of them reported a problem. I opened it up with an app built on wxWidgets 3.1.5, and it failed as did another app built on 3.1.7, but an app built on wxWidgets 3.0 (I know for certain it uses wxWidgets to load bitmaps) loaded the bitmap without a problem. This was all done on Windows, so it doesn't appear to be on OS specific issue, or specific to the app adrianlopezroche is using.

**Comment by MaartenBent** [comment]
caused by https://github.com/wxWidgets/wxWidgets/commit/cccda9ef6bc7f6ee0ff47e4e9da634e762ccabb3 but I know nothing about bitmap headers so I can't fix this myself.

**Comment by MaartenBent** [comment]
Oh, Eric replied in the mailing list as well, but that is not visible here: https://groups.google.com/g/wx-dev/c/oHiaF1YpoVs/m/0rRRrQZLAQAJ

**Comment by vadz** [comment]
Thanks for reporting this, it definitely needs to be fixed. In the worst case we can always revert cccda9ef6bc7f6ee0ff47e4e9da634e762ccabb3 (we'd need to revert bcb0d42d7a2a9a76c2d52fa75f1f57447f2aab3c and ca065c500436679fc4c15d2170716df24dcfd1ab too in this case), but perhaps we could instead just make it conditional on `comp != BI_BITFIELDS`? As the palette is not used in this case, it shouldn't be necessary to do this `SeekI()`, should it? Eric, what do you think?

**Comment by vadz** [comment]
Please test the linked PR #22504 if you can, it fixes the issue with reading `BI_BITFIELDS` bitmaps, but also changes quite a few things, so please let me know if anybody sees any new regressions with it. TIA!

**Comment by adrianlopezroche** [comment]
PR #22504 fixes the problem for me.
