### ISSUE TITLE
Property Grid c++20 and MSVC build error

### ISSUE THREAD

**Issue by reid-p** [wxWidgets/wxWidgets#22505]
MSVC generates an error bout combining enums with this code.
```cpp
wxPG_ITERATE_VISIBLE = wxPG_ITERATE_PROPERTIES
                       wxPG_PROP_CATEGORY |
                       wxPG_IT_CHILDREN(wxPG_PROP_AGGREGATE),
```
Not sure the best way to solve it. 

But this works:
```cpp
wxPG_ITERATE_VISIBLE = static_cast<int>(wxPG_ITERATE_PROPERTIES) |
                       wxPG_PROP_CATEGORY |
                       wxPG_IT_CHILDREN(wxPG_PROP_AGGREGATE),
```

wxPG_ITERATE_VISIBLE  and wxPG_ITERATE_PROPERTIES are enum wxPG_ITERATOR_FLAGS
wxPGPropertyFlags is enum wxPGPropertyFlags

So using wxALLOW_COMBINING_ENUMS without forward declaring the enum is a problem.

**Comment by vadz** [comment]
Could we just add a cast to `wxPGPropertyFlags` to `wxPG_IT_CHILDREN` definition?

If not, then the only thing I see is to do something like `wxALLOW_COMBINING_ENUMS(wxPGPropertyFlags, int)`. This would be not ideal from type-safety point of view, but we really seem to need to allow it here...

@a-wi Do you know if there are any restrictions here or should anything at all be allowed?
