### ISSUE TITLE
Opening project in version 3.16

### ISSUE THREAD

**Issue by chris12342534** [wxWidgets/wxWidgets#22507]
**Describe the bug**
Hello so I had a problem with version 3.0 because the boarder was changing so I was suggested in previous issue to use version 3.16 to fix that. I created a new project with version 3.16 and everything worked fine. My problem now that I open the old project in newer version of wxwidgets. It doesn't want to compile it gives errors that are missing stuff. How can i fix that I have attached a text file with the errors and the way I have set up my compiler and global variables

**Expected vs observed behaviour**
Expected it to combile

**Patch or snippet allowing to reproduce the problem**

Skip this step if the problem can be reproduced in one of the samples without any changes.

**To Reproduce**

**Platform and version information**
 - wxWidgets version you use: 3.1.6
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 120.2212.4170.0
-For wxGTK only:
--GTK version:
--Which GDK backend is used:
--If relevant, i.e. for appearance-related problems:
   
[buildLogErrors.txt](https://github.com/wxWidgets/wxWidgets/files/8870801/buildLogErrors.txt)
![Screenshot (8)](https://user-images.githubusercontent.com/105078299/172859979-fb5a1ff2-caef-46c3-aadd-2e2539e5e1e4.png)
![Screenshot (9)](https://user-images.githubusercontent.com/105078299/172859983-ab02103a-7ef9-4e2c-90f1-d8bdf3e65235.png)
![Screenshot (10)](https://user-images.githubusercontent.com/105078299/172859984-b7511aa1-19c9-4d2e-a74e-48242b3e7a51.png)

**Comment by vadz** [comment]
You're not linking with several required Windows libraries. This is documented in the change log

https://github.com/wxWidgets/wxWidgets/blob/5e1f4910b252c9aabb31882f1ca422ab5d0dd313/docs/changes.txt#L158-L162

and I strongly advise you to read the rest of the "incompatible changes" section of this document too.

**Comment by vadz** [comment]
You search for the missing symbol in the documentation, which [shows you](https://docs.microsoft.com/en-us/windows/win32/api/oleacc/nf-oleacc-createstdaccessibleobject) the library to link with at the bottom.

**Comment by chris12342534** [comment]
So I am trying what you have explain I am looking for wxDynamicLibrary on documentation to see if I need to add a library but I don't see any link that gives information about the library. In addition I have another question I am using 3.16 wxwidets as I was suggested in this issue "Border line of GUI not working on different scale and resolutions #22405". When I create a new project and I select a wxDEFAULT_DIALOG_STYLE I get the same problem as using version 3.0. When I use wxDEFAULT_DEFAULT_STYLE it works correctly so I know the librar is built correctly. The problem is that i open a project that I created in 3.0 wxwidgets and I have a wxDEFAULT_DIALOG_STYLE but I don't not see any of the problems happening how is that possible?

https://docs.wxwidgets.org/trunk/search.php?query=wxDynamicLibrary

**Comment by vadz** [comment]
Sorry, but you're mixing up too many different things here and answering all of your questions here would be confusing because this is not the best place for discussions. Please use the mailing lists, forum, IRC etc for the questions and please try to ask them one at a time.
