### ISSUE TITLE
MSW: Expose "put_AdditionalBrowserArguments" in wxWebViewEdge through a public API

### ISSUE THREAD

**Issue by beENABLED** [wxWidgets/wxWidgets#22506]
The behavior of the Chromium component can be controlled through various command line switches. In my case i'd like to pass "--autoplay-policy=no-user-gesture-required" to enable the autoplay of video. 

But i think there could be other use cases as well.

**Comment by TcT2k** [comment]
While I wouldn't mind a dedicated API, please not that as a workaround you can call:

````C++
    wxSetEnv("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--autoplay-policy=no-user-gesture-required");
````

This has to be called before creating the first `wxWebView` using the edge backend

**Comment by beENABLED** [comment]
Thanks for the quick answer, that's very neat.

How would i pass multiple arguments, additional wxSetEnv() calls, or one call with arguments separated by a space?

**Comment by TcT2k** [comment]
Separated by space should be the correct way. Multiple calls would just overwrite the environment variable.

**Comment by beENABLED** [comment]
In that case a public API might not be needed at all. It might be worth mentioning your solution in the documentation.

Thanks!
