### ISSUE TITLE
Missing wx/filedlgcustomize.h after install

### ISSUE THREAD

**Issue by aaronw2** [wxWidgets/wxWidgets#22516]
While attempting to build Phoenix it fails because it cannot find wx/filedlgcustomize.h.  It appears that this is missing from Makefile.in.

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. Do a clean build and install
2. Attempt to build Phoenix

**Platform and version information**
 - wxWidgets version you use: 3.1.7 e7785ac224f59909e2f3b0c14cf62b4af71ed282
 - wxWidgets port you use: wxGTK 3
 - OS and its version: OpenSUSE 15.3
 - For wxGTK only (**remove** this if not using wxGTK)
   + GTK version: 
   + Which GDK backend is used: X11
   + If relevant, i.e. for appearance-related problems: [current theme]

**Comment by vadz** [comment]
Oops, thanks for noticing (and reporting) this, I've completely forgotten to add the new header to the files list, will do now.
