### ISSUE TITLE
Generic virtual wxListCtrl is no longer updated when EnsureVisible() is directly called after SetItemCount()

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22511]
This change in behavior was introduced with commit d8fe06891ea47fabc48f3d66afb18280641f3421.

Since the commit message states "No real changes.", I assume that this change in behavior was unintentional.

**To Reproduce**
It can be reproduced in the **listctrl sample** using the following changes:
```patch
diff --git "a/samples/listctrl/listtest.cpp" "b/samples/listctrl/listtest.cpp"
index 4b2aae9e57..348e6e8d7e 100644
--- "a/samples/listctrl/listtest.cpp"
+++ "b/samples/listctrl/listtest.cpp"
@@ -1422,6 +1422,7 @@ void MyListCtrl::OnListKeyDown(wxListEvent& event)
                 if ( GetWindowStyle() & wxLC_VIRTUAL )
                 {
                     SetItemCount(GetItemCount() + 1);
+                    EnsureVisible(GetItemCount() - 1);
                 }
                 else // !virtual
                 {

```
1. Start the listctrl sample
2. Press keyboard key 'F8' to switch to the "Small virtual view"
3. Click on an item to set the focus into the list
4. Press keyboard key 'I'.
   An item is appended but the displayed list is not updated.

**To Fix**
I think the way to fix this change in behavior is as follows:

```patch
diff --git "a/src/generic/listctrl.cpp" "b/src/generic/listctrl.cpp"
index d8434a6960..8997b6277e 100644
--- "a/src/generic/listctrl.cpp"
+++ "b/src/generic/listctrl.cpp"
@@ -4224,14 +4224,14 @@ void wxListMainWindow::RecalculatePositions()
             );
         }
     }
-
-    m_dirty = false;
 }
 
 void wxListMainWindow::RecalculatePositionsAndRefresh()
 {
     RecalculatePositions();
 
+    m_dirty = false;
+
     Refresh();
 
     wxListHeaderWindow *headerWin = GetListCtrl()->m_headerWin;

```

**Platform and version information**
 - wxWidgets version you use: 3.1.7
 - wxWidgets port you use: wxGTK

**Comment by vadz** [comment]
This definitely wasn't intentional, thanks for noticing this and for the fix, I agree that this is the right thing to do and will push it soon.
