### ISSUE TITLE
wxFileDialog customize hook not firing when using old fallback under MSW

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#22521]
wxFileDialogCustomize hooks currently do not fire `TransferDataFromCustomControls` on "Accept" of the dialog. 
They only fire once the wxFileDialog object goes out of scope / gets destructured.

Is this intentional behavior?

**Platform and version information**
 - wxWidgets version you use: 3.1.7
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0.19044.1706

**Comment by marekr** [comment]
This might be because `wxUSE_IFILEOPENDIALOG` is coming up 0 for some reason on my build chain for kicad.
So it's using the old style Windows dialog instead of the vista+ one.

But the customize hook does build the ui on the older dialog, it just has no handling for accepting the dialog invoking `TransferDataFromCustomControls`

**Comment by vadz** [comment]
No, definitely not intentional, this is supposed to be called when "Open" button is pressed.

Can the problem be reproduced in the dialogs sample?

**Comment by vadz** [comment]
> This might be because `wxUSE_IFILEOPENDIALOG` is coming up 0 for some reason on my build chain for kicad.

Ah, this could explain it. It's defined here

https://github.com/wxWidgets/wxWidgets/blob/1a5bb42407fb98e1520e9e01676d981ea9ff1e29/include/wx/msw/private/filedialog.h#L24-L29

so normally it should be 1 unless you set some of the options tested here to 0 explicitly or use an SDK which doesn't define `__IFileOpenDialog_INTERFACE_DEFINED__` (FWIW all MinGW-w64 versions since at least 4.8 do define it).

> But the customize hook does build the ui on the older dialog,

Yes, it falls back on the old implementation in this case.

> it just has no handling for accepting the dialog invoking `TransferDataFromCustomControls`

And this is indeed still a bug, I'll fix it. But you should check why is the new code not used at all.

**Comment by marekr** [comment]
Yea I'm the MSYS2/mingw hating KiCad dev that does all MSVC ;)

I need to dig into why that define is broken, since this is entirely on Windows 10, MSVC and a normal Windows SDK

**Comment by vadz** [comment]
> Yea I'm the MSYS2/mingw hating KiCad dev that does all MSVC ;)

I only mentioned MinGW because it's the one which might conceivably have a problem with such things, the official Microsoft SDK should be fine too, of course. I really have no idea how could it be not defined for you, maybe you do set `wxUSE_DYNLIB_CLASS` or whatever to 0 somehow?

**Comment by marekr** [comment]
@vadz Question, that define is only included in `shobjidl_core.h` on Windows. I can't grep a include for that file anywhere in wx.

Did you test it on MSVC or only MINGW? MinGW does not follow the same include hierarchy as Windows .....

**Comment by vadz** [comment]
Yes, I did test it with MSVC (2019 but it really shouldn't matter). This header is/should be included from `<shlobj.h>` included from `"wx/msw/wrapshl.h"` itself included from `"wx/msw/private/filedialog.h"`.

Did you confirm that the symbol was really undefined for you?

**Comment by vadz** [comment]
This is more difficult to fix than I thought. We need to call `TransferDataFromCustomControls()` while the controls still exist, which means that we have to do it before the dialog is destroyed, but we don't know if it's being accepted or cancelled when it's being destroyed, so it's not clear what should we do. I'll try to think more about this, but this is not going to be trivial to fix.

Using the new version should be much simpler, however...

**Comment by marekr** [comment]
> This is more difficult to fix than I thought. We need to call `TransferDataFromCustomControls()` while the controls still exist, which means that we have to do it before the dialog is destroyed, but we don't know if it's being accepted or cancelled when it's being destroyed, so it's not clear what should we do. I'll try to think more about this, but this is not going to be trivial to fix.
> 
> Using the new version should be much simpler, however...

The other alternative is to block it's usage with the old dialog somehow and force use of the old api.

I'm still digging into why the IFILEOPENDIALOG detection is failing. I do all my work under vcpkg so it's unusual since it's all msvc anyway.

**Comment by vadz** [comment]
I've forgotten about `CDN_FILEOK`, using it we may easily fix the problem with the wrong order, please see the PR above.

I still have no idea about the other/main issue but I'm afraid you're really the only one who can debug it. Please check whether `__IFileOpenDialog_INTERFACE_DEFINED__` is really not defined, e.g. by adding
```cpp
#ifndef __IFileOpenDialog_INTERFACE_DEFINED__
#error Not defined
#endif
```
and then

- If it is, please do the same for `wxUSE_DYNLIB_CLASS` and `wxUSE_OLE`.
- If it isn't, please check whether the expected headers are included using `cl /showIncludes`

Hopefully this will provide enough information to find the problem. Good luck!

**Comment by marekr** [comment]
Ah, the define is fine after debugging, just was looking at things very wrong with how MSVC jumped around.

My actual issue is `CoCreateInstance(CLSID_FileOpenDialog)' failed with error 0x80004002 (No such interface supported).` so I need to dig into that.

**Comment by marekr** [comment]
Ah I see the problem.
```

wxIFileDialog::wxIFileDialog(const CLSID& clsid)
{
    HRESULT hr = ::CoCreateInstance
                 (
                    clsid,
                    NULL, // no outer IUnknown
                    CLSCTX_INPROC_SERVER,
                    wxIID_PPV_ARGS(IFileOpenDialog, &m_fileDialog)
                 );
    if ( FAILED(hr) )
    {
```

IFileOpenDialog is hardcoded in dirdlg.cpp but I'm requesting a CLSID_FileSaveDialog

**Comment by vadz** [comment]
Oops, how embarrassing. Let me fix this quickly.

**Comment by vadz** [comment]
I've pushed more changes to the same PR #22522, could you please test it and confirm that it works for you? There is now an example of customizing a "Save" file dialog in the dialogs sample too and it actually works now.

Sorry again for a really bad bug!

**Comment by marekr** [comment]
> I've pushed more changes to the same PR #22522, could you please test it and confirm that it works for you? There is now an example of customizing a "Save" file dialog in the dialogs sample too and it actually works now.
> 
> Sorry again for a really bad bug!

No problem, I updated kicad's nightlies to 3.1.7 just so we can catch up on catching any wx bugs before 3.2 happens ;)
