### ISSUE TITLE
wxMenuItem bitmaps not working in specific use case since 3.1.6

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#22530]
**Describe the bug**
In KiCad, we have a scheme where we create a wxMenu with wxMenuItems "virtually" without ever displaying it. We then copy said virtual wxMenu with relevant wxMenuItems when we want to actually display the context menu on right click and pass the copy to `wxWindow::PopUpMenu`. It's mainly because we use dervived classes from wxMenu and wxMenuItem to track some additional metadata and we don't want it to get destructed by wxWidgets automatically.

During the copy process which is done in KiCad, we `GetBitmap` on the "source" `wxMenuItem` and `SetBitmap` with that provided bitmap on the new copy of the menu item. IsOk() validates on the returned wxBitmap and appears to have the 24x24 pixel icon visible in the gdi ref data struct.

In 3.0 up to 3.1.5, this worked fine. Something changed in 3.1.6 and 3.1.7 and it no longer works.

I have debugged deep into wxWidgets and it seems returning valid bitmaps and setting them via `SetBitmap`.
It even invokes `::SetMenuItemInfo` with a valid looking gdi handle to a bitmap when `PopUpMenu` is passed the menu to display. But no bitmap renders in the context menu.

Now, if I invoke `PopUpMenu` with the "virtual" `wxMenu` rather than the copy, then the bitmap appears just fine. 

Another test was I passed a new copy of the `wxBitmap` into the `SetBitmap` call of the copy, rather than using the `GetBitmap`, and it also did not display. 

So I'm a bit lost on what is going wrong and/or changed between wx 3.1.5 and 3.1.6. In both cases, original and "copy" wxMenuItem, we simply use `SetBitmap`, so its not like we are touching internal class state directly.

**Expected vs observed behaviour**
The bitmap displays just fine.

**Patch or snippet allowing to reproduce the problem**

I am currently also unable to reproduce the bug in a test app where I made it do the same process, i.e. build a wxMenu and wxMenuItem with bitmap but never display it. Then on action, copy those items including bitmap and invoke `PopUpMenu` on the window. It works in this case even if I feed it the same image files we use.

**Platform and version information**
 - wxWidgets version you use: 3.1.7
 - wxWidgets port you use: wxMSW

**Comment by marekr** [comment]
>Do note that GetBitmap() now returns a wxBitmap object, not a reference, and you need to keep this bitmap alive somewhere, somehow, as it's not stored inside wxMenuItem itself any more. But if you immediately pass it to SetBitmap(), it should still be fine.

Yes it's just immediately passed to SetBitmap.

Is there an API to retrieve the whole wxBitmapBundle by the way? I don't see it and future wise it would probably be ideal for our copying scheme. Right now we only have fixed 24x24 bitmaps since wxBitmapBundle is new but in the future we may leverage it.

**Comment by marekr** [comment]
Ok, I finally have a repro case after finding out our code does far more things under the hood.

What is actually happening is when we show the menu, we hook `wxEVT_MENU_OPEN`

In wxEVT_MENU_OPEN...we proceed to wipe the menu clean of children and then rebuild it yet again (only the wxMenuItems), this time evaluating additional conditions. Yes this is a nutty system to conditional change 50 possible context menu options depending on what is on screen in CAD and what CAD tool is running :/

[wxtest4.zip](https://github.com/wxWidgets/wxWidgets/files/8895614/wxtest4.zip)

In this repro I have two buttons. On one of them I flag it to do the repro case where it will Clear the menu and readd a wxMenuItem with the same global bitmap reference the working case menu item bitmap is set from.

**Comment by vadz** [comment]
Thanks, the key is indeed doing this in the `wxEVT_MENU_OPEN` handler. The problem should be fixed in the PR above, which also adds `wxMenuItem::GetBitmapBundle()`.
