### ISSUE TITLE
Sample 'widgets' crashes when handling bitmaps

### ISSUE THREAD

**Issue by whalley** [wxWidgets/wxWidgets#22540]
**Describe the bug**
I've had some crashes with the latest wxWidgets code (works fine with wx3.1.5) when handling bitmaps, so reverted to the sample code and can see that the 'widgets' sample app also crashes. 

**Expected vs observed behaviour**
Expected sample apps to work but encounter crashes

**To Reproduce**

- Run 'widgets' sample application
- Select 'button' or 'toggle button'
- select 'Bitmap only' or 'Text and bitmap'

Other widgets in the sample also crash e.g. 'notebook', 'Generic/Choicebook'

**Platform and version information**
 - wxWidgets version you use: master / head
 - wxWidgets port you use: wxOSX
 - OS and its version: MacOS 12.4

**Comment by vadz** [comment]
I'll try to test this myself a.s.a.p. but in the meanwhile it would be useful if you could please show the stack at the moment of the crash (this requires building wx with debug info, of course). TIA!

**Comment by whalley** [comment]
Apologies, I thought I had attached - Doh
[crashdump1.txt](https://github.com/wxWidgets/wxWidgets/files/8920610/crashdump1.txt)
!

**Comment by vadz** [comment]
Unfortunately I can't reproduce this, can anybody else? I've just spent a couple of minutes clicking "Bitmap only" and "Text and bitmap" checkboxes on the "Button" and "Toggle button" pages of the widgets sample and I don't see anything untoward happening and ASAN doesn't notice anything bad going on neither.

I'm under 12.0.1 and not 12.4, but it would be really weird if this depended on minor OS version change.

Could it be just a problem with your build, i.e. could you please try cleaning everything and rebuilding?

**Comment by whalley** [comment]
Apologies for wasting your time. Yes,  a `make clean` and rebuild fixed it. Not sure what happened there, but all good now.

Thanks for the speedy investigation.
