### ISSUE TITLE
Add support for `IFileDialog::AddPlace`

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#22543]
`IFileDialog::AddPlace` exists in IFileDialog and allows you to add folders to the Navigation pane on the left hand side of the file dialogs for users to quickly jump to. Very useful for application folders that are always reused by users.

GTK has `gtk_file_chooser_add_shortcut_folder`

I don't know if macOS has an equivalent because their docs are horrible to read.

**Comment by vadz** [comment]
I don't see anything allowing to do this in [Apple docs](https://developer.apple.com/documentation/appkit/nssavepanel?language=objc) but we could indeed do this relatively easily for MSW and GTK.

**Comment by vadz** [comment]
Please check the linked PR, it seems to work fine for me under both MSW and GTK. If no problems are found with it, it can also be backported, with minor adjustments, to 3.2.

cc @imciner2 @sethhillbrand

**Comment by vadz** [comment]
Backported to 3.2 too now.

**Comment by marekr** [comment]
> Backported to 3.2 too now.

Thanks
