### ISSUE TITLE
wxBitmap is not correct under wxMSW using a depth of 32

### ISSUE THREAD

**Issue by BrutalSoloH** [wxWidgets/wxWidgets#22548]
Since 3.1.6 or either 3.1.5 when creating a bitmap using:

`wxBitmap * bmp = new wxBitmap(someImageWithMask, 32, 1.0);`

The displayed bmp is showing in the incorrect size (too narrow) and color distorted like it is not supporting 32-bit. Looks like it is skipping 1 every 4 pixels.

Using:

`wxBitmap * bmp = new wxBitmap(someImageWithMask, wxBITMAP_SCREEN_DEPTH, 1.0);`

will show the bitmap correctly.

Also using 3.1.4 and before will show correctly. Also wxMac will always show correctly, so it's a wxMSW problem.

I have not tested it on 3.1.5.

**Platform and version information**
 - 3.1.5 or 3.1.6
 - wxMSW
 - Windows 11

**Comment by PBfordev** [comment]
FWIW, I tried something similar with the current master on Win10 with
```patch
diff --git a/samples/image/canvas.cpp b/samples/image/canvas.cpp
index 9a634fed4f..d894b52c26 100644
--- a/samples/image/canvas.cpp
+++ b/samples/image/canvas.cpp
@@ -105,7 +105,11 @@ MyCanvas::MyCanvas( wxWindow *parent, wxWindowID id,
     }
     else
     {
-        my_toucan = wxBitmap(image);
+        if ( !image.ConvertAlphaToMask() )
+            wxLogError("Could not convert alpha to mask.");
+        if ( !image.HasMask() )
+            wxLogError("Image should have mask but does not.");
+        my_toucan = wxBitmap(image, 32);
     }
```
The resulting bitmap looks like this
![toucan_32](https://user-images.githubusercontent.com/12495521/174347351-c2b92c2e-da99-44b5-bd9f-3275668b6c42.png)

When I change the depth when creating the bitmap, i.e., to `my_toucan = wxBitmap(image, wxBITMAP_SCREEN_DEPTH);`, the bitmap looks like this
![toucan_wxBITMAP_SCREEN_DEPTH](https://user-images.githubusercontent.com/12495521/174347579-e3e529e8-04df-4d62-bdc6-986ea283558e.png)

So there may be an issue but what I get is quite different than what @BrutalSoloH  described, e.g. the bitmap size did not change.

**Comment by BrutalSoloH** [comment]
It looks pretty similar, except that it didn't change the width. I create the image from different sources and attach a mask to it.

```
	// attach mask
	wxImage facewithmask = face.ConvertToImage();
	facewithmask.SetMaskFromImage(mask, 255, 255, 255);

	// store the card
	wxBitmap * bmpCard = new wxBitmap(facewithmask, 32, 1.0);

```

Correctly drawn
![Correctly drawn](https://user-images.githubusercontent.com/32673704/174426681-21b036e7-8bd0-4501-a369-8638717f2cb5.png)

Incorrectly drawn
![Incorrectly drawn](https://user-images.githubusercontent.com/32673704/174426702-551afc80-a24c-47c4-9581-ae1283b6266b.png)

**Comment by BrutalSoloH** [comment]
Here is an image.
[someImageWithMask.zip](https://github.com/wxWidgets/wxWidgets/files/8933127/someImageWithMask.zip)

**Comment by vadz** [comment]
Thanks, I do see the problem too and the PR above fixes it for me and I'll merge it soon if there are no objections.
