### ISSUE TITLE
‘wxURL’ was not declared in this scope?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [wxWidgets/wxWidgets#22554]
**Describe the problem**
I installed  wxWidgets  by the following:
```
./configure --with-gtk
make
sudo make install
```
When I try to build my code 
```
g++ main.cpp `wx-config --cxxflags --libs std`-o program`
```
I got the error:
```
main.cpp:27:17: error: ‘wxURL’ was not declared in this scope
```
anything wrong with my installation?

**Platform and version information**
 - wxWidgets version you use: **3.1.7**
 - wxWidgets port you use: **wxGTK**
 - OS and its version: Ubuntu 20.04.4 LTS
 - Compiler being used: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by vadz** [comment]
You can't really open a bug like this without showing what does your `main.cpp` contain. In particular, please check that it includes `wx/url.h` -- I assume it doesn't, as this is the most straightforward explanation. If you do include it, please reduce the code as much as possible and attach your `main.cpp` here.

**Comment by pigLoveRabbit520** [comment]
It seems `wxURL` don't support https.
