### ISSUE TITLE
wxWidget 3.1.7: samples/webview$ ./webview shows assertions and has to be killed

### ISSUE THREAD

**Issue by PMaff** [wxWidgets/wxWidgets#22550]
I have to CTRL-C this sample:
```
samples/webview$ ./webview 
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(963): assert ""IsOk()"" failed in GetHeight(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(963): assert ""IsOk()"" failed in GetHeight(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
Killed
```

Reproducable: always.
With newest 3.1.7 from github.

Ubuntu 22.04 'jammy'
uname -a
Linux machinename 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadz** [comment]
Thanks, this is due to `wxART_STOP` and `wxART_REFRESH` not being available in wxGTK, we need to:

1. Add them
2. Handle missing bitmaps better in wxGTK `wxToolBar`.

I'm not sure why do you have to kill the sample however, if you uncheck the "Show this dialog the next time" checkbox (or just click through all of them), it seems to work just fine -- except for not showing the images for these 2 toolbar tools, of course.

**Comment by PMaff** [comment]
> Thanks, this is due to `wxART_STOP` and `wxART_REFRESH` not being available in wxGTK, we need to:
> 
>     1. Add them
> 
>     2. Handle missing bitmaps better in wxGTK `wxToolBar`.
> 
> 
> I'm not sure why do you have to kill the sample however, if you uncheck the "Show this dialog the next time" checkbox (or just click through all of them), it seems to work just fine -- except for not showing the images for these 2 toolbar tools, of course.

Yes of course, if I uncheck the "Show this dialog the next time" then it would run through.
But if you do not use this, then the application hangs at the end with one blurry last assertion dialog.
You have to kill it then:
![webviewexamplehangs](https://user-images.githubusercontent.com/93879362/174387420-176dcb77-576d-442a-9bcd-2aedb1ba1678.jpg)

**Comment by vadz** [comment]
I don't see the latter problem and I have absolutely no idea how/why could it be happening, which is rather worrisome. Could you please run the sample under gdb, break into it when it hangs and show the output of `bt` command?

**Comment by vadz** [comment]
The originally reported problem is fixed now (thanks Paul) and I've also added the missing bitmaps, but if you have any information into why the asserts resulted in the application hanging, please open a new issue for this because this is still definitely not expected. TIA!
