### ISSUE TITLE
Undocumented wxBitmapBundle-related change resulting in build error

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22566]
As reported on wxForum, the reporter run into issue when building their application after switching from 3.1.4 to 3.1.7.

They used `wxToolBar::AddTool()` overload where they passed as `wxBitmap` a` char*` array (an XPM). In the older version, this matched the `wxBitmap (const char *const *bits)` ctor, so `wxBitmap` was constructed and passed to toolbar. 
```cpp
#include <wx/wx.h>

static const char *const align_left_xpm[] = {
"16 15 2 1",
". c black",
"  c None",
"                ",
"                ",
" ..........     ",
"                ",
" ......         ",
"                ",
" ..........     ",
"                ",
" ......         ",
"                ",
" ..........     ",
"                ",
" ......         ",
"                ",
"                "
};

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        wxFrame*   frame   = new wxFrame(nullptr, wxID_ANY, "Test");
        wxToolBar* toolBar = frame->CreateToolBar();

        toolBar->AddTool(wxID_ANY, "Test", align_left_xpm);
        toolBar->Realize();

        frame->Show(true);
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```

However, this is not possible in the versions using `wxBitmapBundle` and results in build errors:
```
D:\Dev\Desktop\wxPokusy\_forum\test-toolbar-bmp-xpm\minimal.cpp(32,1): error C2664: 'wxToolBarToolBase *wxToolBarBase::AddTool(int,const wxString &,const wxBitmapBundle &,const wxString &,wxItemKind)': cannot convert argument 3 from 'const char *const [18]' to 'const wxBitmapBundle &'
1>D:\Dev\Desktop\wxPokusy\_forum\test-toolbar-bmp-xpm\minimal.cpp(32,1): message : Reason: cannot convert from 'const char *const [18]' to 'const wxBitmapBundle'
1>D:\Dev\Desktop\wxPokusy\_forum\test-toolbar-bmp-xpm\minimal.cpp(32,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>D:\Dev\Desktop\!Lib\wxWidgets-GIT\include\wx\tbarbase.h(311,24): message : see declaration of 'wxToolBarBase::AddTool'
```
As I wrote in the forum, I am not a fan of writing the code like this but it used to work before, so that it does not any more should perhaps at least be documented. Or may be it already is and I just did not found it?

BTW, there is no issue template for application build error, only wxWidgets build error (the other two templates are for run-time errors and enhancements).

**Comment by vadz** [comment]
We probably should indeed add a compatibility ctor from XPM (i.e. `char const* const*`) to `wxBitmapBundle`. But if we do this, should we add a ctor from `wxString, wxBitmap type = wxBITMAP_DEFAULT_TYPE` too? It looks like there is no good reason for not doing it, but this would make things even more confusing...
