### ISSUE TITLE
[MSW] Issue with font size on high dpi when using chained wxMemoryDCs

### ISSUE THREAD

**Issue by beENABLED** [wxWidgets/wxWidgets#22567]
**Describe the bug**
I'm not 100% sure if this is a bug, or if i'm just missing something.

When rendering text into a wxMemoryDC, and then drawing the bitmap into an wxBufferedPaintDC, the result is different than drawing the text directly into the wxBufferedPaintDC.

**Expected vs observed behaviour**
The text should look the same in both cases.

**Patch or snippet allowing to reproduce the problem**
```
wxFont bigfont(14, wxFONTFAMILY_ROMAN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, false, wxT("Lucida Sans Unicode"));

wxPanel *panel = new wxPanel( this, wxID_ANY );
panel->SetFont( bigfont );

panel->Bind(wxEVT_PAINT, [=](wxPaintEvent &event) {
  wxBufferedPaintDC dc(panel);
  dc.Clear();
  dc.DrawText("text drawn directly into wxBufferedPaintDC", 10, 10 );
  wxLogDebug("wxBufferedPaintDC font info: %s", dc.GetFont().GetNativeFontInfoDesc() );

  wxBitmap bmp(400, 100, 24);
  {
    wxMemoryDC mdc;
    mdc.CopyAttributes( dc );
    wxLogDebug("wxMemoryDC font info: %s", mdc.GetFont().GetNativeFontInfoDesc() );

    mdc.SelectObject( bmp );
    mdc.Clear();
    mdc.DrawText("text drawn into wxMemoryDC", 10, 10 );
  }
  dc.DrawBitmap( bmp, 10, 50, false);
});
```

**Platform and version information**
 - wxWidgets version you use: Trunk
 - wxWidgets port you use: wxMSW
 - OS and its version:  Windows 10.0.19044.1766
 

If you ask, "Why do you draw into a wxMemoryDC, when you're using a wxBufferedPaintDC anyway?":

In my case it happened in a OnDrawItem() method of a wxVListBox. I wasn't aware wxVListBox already uses a wxAutoBufferedPaintDC internally until i single-stepped through the code.

LogDebug output:
[9104] wxBufferedPaintDC font info: 1;14;-28;0;0;0;400;0;0;0;1;0;0;2;16;Lucida Sans Unicode 
[9104] wxMemoryDC font info: 1;14;-19;0;0;0;400;0;0;0;1;0;0;2;16;Lucida Sans Unicode 

The lfHeight property of the font is different.

Display scaling 100%
<img width="292" alt="minimal_scale_100" src="https://user-images.githubusercontent.com/107193603/175637785-f2ae1000-08ec-4868-af26-68059246823a.png">

Display scaling 150%
<img width="361" alt="minimal_scale_150" src="https://user-images.githubusercontent.com/107193603/175637976-556c0bdf-57ea-466e-9559-2b0e34822807.png">
.

**Comment by vadz** [comment]
We probably need to copy the scale factor in `CopyAttributes()` too. This still wouldn't help if you just call `mdc.SetFont()` yourself, but there is nothing we can do in this case -- `wxMemoryDC` on its own just doesn't know which scale factor to use, so it defaults to 1, for compatibility.

But if you call `CopyAttributes()`, we can make it work. Could you please check that adding
```cpp
m_contentScaleFactor = dc.GetContentScaleFactor();
```
there fixes the problem and doesn't introduce any new ones? TIA!

**Comment by beENABLED** [comment]
> m_contentScaleFactor = dc.GetContentScaleFactor();

I had to add new SetContentScaleFactor() methods to wxDC and wxDCImpl to access that member, but it didn't change anything.

Maybe because it doesn't affect the font properties?

**Comment by MaartenBent** [comment]
Hi,
You should create the bitmap like this, so it (and the memoryDC using it, knows about the scale:
```
        wxBitmap bmp;
        bmp.CreateWithDIPSize(400, 100, GetDPIScaleFactor(), 24);
```

**Comment by vadz** [comment]
Yes, this should work, but it would be nice if `CopyAttributes()` worked too, it looks like the scale factor could reasonably be considered just another attribute.

**Comment by vadz** [comment]
> I had to add new SetContentScaleFactor() methods to wxDC and wxDCImpl to access that member

I'm not sure if having such method makes sense generally speaking, i.e. you just can't change the scale factor of a DC associated with a window. But we can add some virtual `CopyScalingFactor()` function that would do it for `wxMemoryDC` only.

> Edit: It does work, when i call CopyAttributes() _after_ selecting the bitmap into the wxMemoryDC.

I think this is the best we can hope for, i.e. make
```cpp
    wxMemoryDC mdc(bmp);
    mdc.CopyAttributes( dc );
```
work even if the original
```cpp
    wxMemoryDC mdc;
    mdc.CopyAttributes( dc );
    mdc.SelectObject( bmp );
```
still doesn't. This is because the bitmap scale factor should really be taken into account and so should override whichever scale factor was used before.

But I don't know if it's worth doing it any more, to be honest. On one hand, this would avoid surprises such as the one you've got, but OTOH using effective bitmap size different from the one specified in its ctor could be a pretty bad surprise on its own too. In this example it doesn't really matter because the bitmap is big enough anyhow, but in other cases it could result in things not fitting into it.

So maybe we should just mention `CreateWithDIPSize()` in `SelectObject()` docs, what do you think?

**Comment by beENABLED** [comment]
> So maybe we should just mention `CreateWithDIPSize()` in `SelectObject()` docs, what do you think?

Purely based on the fact that the method CopyAttributes() exists, i think it should copy that attribute.

**Comment by MaartenBent** [comment]
IMO the scale factor is part of the selected object, not the `wxMemoryDC`. Things that `CopyAttributes()` copies are things that you can configure for the DC, like fonts and colours.

**Comment by vadz** [comment]
Yes, more I think about it, more I agree with Maarten: `CopyAttributes()` copies things that you can `Set()` and you can't do this with the scale factor. Of course, we could add `SetScaleFactor()` but it wouldn't actually work for most (all except this one?) `wxDC` kinds, so this would be backwards.

Instead I've just updated the docs to document the current behaviour and show an example of initializing `wxMemoryDC` correctly.

**Comment by beENABLED** [comment]
Good enough for me. I'll close this. Thanks.
