### ISSUE TITLE
Online documentation, "Functions and Macros by Category" - sub pages are mainly empty

### ISSUE THREAD

**Issue by beENABLED** [wxWidgets/wxWidgets#22572]
All sub pages linked from the page "Functions and Macros by Category" are basically empty.
https://docs.wxwidgets.org/trunk/group__group__funcmacro.html

It was still ok in the 3.1.5 docs:
https://docs.wxwidgets.org/3.1.5/group__group__funcmacro.html

**Comment by PBfordev** [comment]
This is already covered in the "umbrella ticket for broken doxygen" #22288, see the last post there.

**Comment by beENABLED** [comment]
Sorry, my bad. Closing this one.

**Comment by vadz** [comment]
Let's keep it open as the other one will be closed soon because the problem there is/will be fixed -- but not this one, unfortunately.

**Comment by tierra** [comment]
I think Xavier has discovered why this is broken:
https://groups.google.com/g/wx-dev/c/FEv-HjdD4dY/m/KvBW6NtOAgAJ

**Comment by vadz** [comment]
Xavier has indeed found the solution and I think the commit above solves it (for master), see the commit(s) above, see e.g. [this page](https://docs.wxwidgets.org/latest/group__group__funcmacro__appinitterm.html).

If nobody sees any new problems due to this in the latest docs, I'm going to backport these changes to 3.2 too.

**Comment by beENABLED** [comment]
Thanks for the fix and the info.

BTW: Shouldn't https://docs.wxwidgets.org/trunk/ also use the new styling? Or is this an obsolete page?

**Comment by vadz** [comment]
It's indeed an obsolete page, which I kept just in case we had to return to this docs version if there were some bad problem with the new theme, but this doesn't seem to be the case, so I've just linked `/trunk` to `/latest` now (it will probably take some time to propagate however, as it's cached by Cloudflare).
