### ISSUE TITLE
Query: Why are the automated intel Mac builds building for 10.12 instead of the minimum requirement, 10.10?

### ISSUE THREAD

**Issue by hamishmb** [wxWidgets/wxWidgets#22578]
Hi there,

Just happened to notice that your automated builders are building with: `--with-macosx-version-min=10.12` instead of `--with-macosx-version-min=10.10`, even though your minimum requirement is meant to be 10.10. I'm referring to the YML script shown at: [https://github.com/wxWidgets/wxWidgets/actions/runs/2570648891/workflow](https://github.com/wxWidgets/wxWidgets/actions/runs/2570648891/workflow)

Has the minimum requirement changed to 10.12?

Hamish

**Comment by vadz** [comment]
The minimum version is still 10.10 but it requires having 10.11 SDK installed which is probably not available on the machines where these builds are running.

Also, please ask any questions like this on wx mailing lists rather than using the issue tracker for them. TIA!

**Comment by MaartenBent** [comment]
Also, that build uses  C++17, that might not be available in 10.10.
