### ISSUE TITLE
wxNotebook can't handle wxGLCanvas correctly on Wayland

### ISSUE THREAD

**Issue by tamasmeszaros** [wxWidgets/wxWidgets#22580]
**Bug description**
When a wxGLCanvas is inserted as one of the pages of a wxNotebook, the OpenGL window is visible on other pages as well.

**Expected vs observed behaviour**
The wxGLCanvas content with properly initialized OpenGL context and some rendered content is expected to be visible only when the appropriate page -- into which the canvas was inserted -- is selected.
The observation is that the OpenGL content is visible on other pages too. This is only happening in a Wayland session with EGL support enabled. Setting `GDK_BACKEND=x11` in such environment will hide the issue. 

**Screenshots**
Expected (also when `GDK_BACKEND=x11`): ![Screenshot from 2022-06-28 17-33-12](https://user-images.githubusercontent.com/4021217/176220479-cbd8703e-9eca-4b01-808a-895bb5817dbc.png)

Observed: 
![Screenshot from 2022-06-28 17-32-25](https://user-images.githubusercontent.com/4021217/176220691-86f686cb-85d3-4f70-844e-51e7573500ee.png)

**Patch or snippet allowing to reproduce the problem**
```c++
#include <iostream>
#include <utility>
#include <memory>
#include <vector>

// For compilers that support precompilation, includes "wx/wx.h".
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/tglbtn.h>
#include <wx/combobox.h>
#include <wx/msgdlg.h>
#include <wx/glcanvas.h>
#include <wx/notebook.h>

class Renderer {
protected:
    wxGLCanvas *m_canvas;
    std::unique_ptr<wxGLContext> m_context;
public:
    
    Renderer(wxGLCanvas *c): m_canvas{c} {
        m_context = std::make_unique<wxGLContext>(m_canvas);
    }
    
    wxGLContext * context() { return m_context.get(); }
    const wxGLContext * context() const { return m_context.get(); }

    // OpenGL example from https://cs.lmu.edu/~ray/notes/openglexamples/
    // section: Tetrahedron
    
    void set_active()
    {
        m_canvas->SetCurrent(*m_context);
        
        glClearColor(0.1, 0.39, 0.88, 1.0);
        glColor3f(1.0, 1.0, 1.0);

        glEnable(GL_CULL_FACE);
        glCullFace(GL_BACK);

        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glFrustum(-2, 2, -1.5, 1.5, 1, 40);

        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        glTranslatef(0, 0, -3);
        glRotatef(50, 1, 0, 0);
        glRotatef(70, 0, 1, 0);
    }

    void draw_scene(long w, long h)
    {
        glViewport(0, 0, GLsizei(w), GLsizei(h));
        glClear(GL_COLOR_BUFFER_BIT);

        // Draw a white grid "floor" for the tetrahedron to sit on.
        glColor3f(1.0, 1.0, 1.0);
        glBegin(GL_LINES);
        for (GLfloat i = -2.5; i <= 2.5; i += 0.25) {
            glVertex3f(i, 0, 2.5); glVertex3f(i, 0, -2.5);
            glVertex3f(2.5, 0, i); glVertex3f(-2.5, 0, i);
        }
        glEnd();

        // Draw the tetrahedron.  It is a four sided figure, so when defining it
        // with a triangle strip we have to repeat the last two vertices.
        glBegin(GL_TRIANGLE_STRIP);
        glColor3f(1, 1, 1); glVertex3f(0, 2, 0);
        glColor3f(1, 0, 0); glVertex3f(-1, 0, 1);
        glColor3f(0, 1, 0); glVertex3f(1, 0, 1);
        glColor3f(0, 0, 1); glVertex3f(0, 0, -1.4);
        glColor3f(1, 1, 1); glVertex3f(0, 2, 0);
        glColor3f(1, 0, 0); glVertex3f(-1, 0, 1);
        glEnd();

        glFlush();
    }

    void swap_buffers() { m_canvas->SwapBuffers(); }
};

// The top level frame of the application.
class MyFrame: public wxFrame
{
    wxGLCanvas     *m_canvas;
    std::unique_ptr<Renderer> m_renderer;
    
public:
    MyFrame(const wxString &       title,
            const wxPoint &        pos,
            const wxSize &         size);

    wxGLCanvas * canvas() { return m_canvas; }
    const wxGLCanvas * canvas() const { return m_canvas; }
};

class App : public wxApp {
    MyFrame *m_frame = nullptr;
    wxString m_fname;
public:
    bool OnInit() override {

        m_frame = new MyFrame("Wayland wxNotebook issue", wxDefaultPosition, wxSize(1024, 768));
        m_frame->Show( true );
        
        return true;
    }

};

wxIMPLEMENT_APP(App);

MyFrame::MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size):
    wxFrame(nullptr, wxID_ANY, title, pos, size)
{
    wxMenu *menuFile = new wxMenu;
    menuFile->Append(wxID_OPEN);
    menuFile->Append(wxID_EXIT);
    wxMenuBar *menuBar = new wxMenuBar;
    menuBar->Append( menuFile, "&File" );
    SetMenuBar( menuBar );

    auto notebookpanel = new wxPanel(this);
    auto notebook      = new wxNotebook(notebookpanel, wxID_ANY);
    auto maintab       = new wxPanel(notebook);

    m_canvas = new wxGLCanvas(maintab,
                              wxID_ANY,
                              nullptr,
                              wxDefaultPosition,
                              wxDefaultSize,
                              wxWANTS_CHARS | wxFULL_REPAINT_ON_RESIZE);

    m_renderer = std::make_unique<Renderer>(m_canvas);

    wxPanel *control_panel = new wxPanel(maintab);

    auto controlsizer = new wxBoxSizer(wxHORIZONTAL);
    auto console_sizer = new wxBoxSizer(wxVERTICAL);

    std::vector<wxString> combolist = {"One", "Two", "Three"};
    auto combobox = new wxComboBox(control_panel, wxID_ANY, combolist[0],
                                   wxDefaultPosition, wxDefaultSize,
                                   int(combolist.size()), combolist.data());

    auto sz = new wxBoxSizer(wxHORIZONTAL);
    sz->Add(new wxStaticText(control_panel, wxID_ANY, "Choose number"), 0,
            wxALL | wxALIGN_CENTER, 5);
    sz->Add(combobox, 1, wxALL | wxEXPAND, 5);
    console_sizer->Add(sz, 0, wxEXPAND);

    auto btn1 = new wxToggleButton(control_panel, wxID_ANY, "Button1");
    console_sizer->Add(btn1, 0, wxALL | wxEXPAND, 5);

    auto btn2 = new wxToggleButton(control_panel, wxID_ANY, "Button2");
    btn2->SetValue(true);
    console_sizer->Add(btn2, 0, wxALL | wxEXPAND, 5);

    controlsizer->Add(console_sizer, 1, wxEXPAND);
    
    control_panel->SetSizer(controlsizer);
    
    auto maintab_sizer = new wxBoxSizer(wxHORIZONTAL);
    maintab_sizer->Add(m_canvas, 1, wxEXPAND);
    maintab_sizer->Add(control_panel, 0);
    maintab->SetSizer(maintab_sizer);

    notebook->AddPage(maintab, "Main");

    wxTextCtrl* textCtrl1 = new wxTextCtrl(notebook, wxID_ANY, L"Tab 2 Contents");
    notebook->AddPage(textCtrl1, "Dummy");

    auto notebooksizer = new wxBoxSizer(wxHORIZONTAL);
    notebooksizer->Add(notebook, 1, wxEXPAND);
    notebookpanel->SetSizer(notebooksizer);

    auto topsizer = new wxBoxSizer(wxHORIZONTAL);
    topsizer->Add(notebookpanel, 1, wxEXPAND);
    SetSizer(topsizer);
    SetMinSize(size);

    Bind(wxEVT_MENU, [this](wxCommandEvent &) {
        wxFileDialog dlg(this, "Select file",  wxEmptyString,
                         wxEmptyString, "*.*", wxFD_OPEN|wxFD_FILE_MUST_EXIST);
        dlg.ShowModal();
    }, wxID_OPEN);

    Bind(wxEVT_MENU, [this](wxCommandEvent &) {
        Close();
    }, wxID_EXIT);

    Bind(wxEVT_SHOW, [this](wxShowEvent &) {
        m_renderer->set_active();

        m_canvas->Bind(wxEVT_PAINT, [this](wxPaintEvent &){
            wxPaintDC dc(m_canvas);

            const wxSize sz = m_canvas->GetClientSize();
            m_renderer->draw_scene(sz.x, sz.y);
            m_renderer->swap_buffers();
        });
    });
}
```

**To Reproduce**
Switch between the "Main" and "Dummy" tabs.

**Related**
See a potentially related issue here https://github.com/prusa3d/PrusaSlicer/issues/8284

**Platform and version information**
 - wxWidgets version: 3.1.7 or 3.1.6 (where wxGLCanvasEGL is in use)
 - wxWidgets port: wxGTK
 - OS and its version: Manjaro Linux (or any other with a Wayland session)
 - GTK version: 3.24.34
 - GDK backend: Wayland

**Comment by vadz** [comment]
Thanks for reporting this but unfortunately I don't think I'll have time to look at this before 3.2.0.

@swt2c Would you have any idea about this one by chance?

**Comment by swt2c** [comment]
I can reproduce this.  However, it's not immediately obvious to me what we're doing wrong or how to fix it...do we need to somehow tell the wayland surface to hide itself when it's containing wxGLCanvas is hidden?

**Comment by vadz** [comment]
I still have no idea what to do here, but here is the list of things that I've tried doing in "unmap" callback for `wxGLCanvasEGL` (which I've added) that do **not** work:

- Call `wl_surface_attach(surface, NULL)` which looked like the best bet after reading

> If wl_surface.attach is sent with a NULL wl_buffer, the following wl_surface.commit will remove the surface content. 

in [the documentation](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_surface): this had no effect at all.

- Same followed by `wl_surface_commit()`: visible flicker, but no other effect.
- Calling `wl_egl_window_resize(0, 0)`: no effect.
- Calling `wl_egl_window_destroy()`: no effect (!?), followed by a crash when calling it again when destroying the window (as expected).
- Destroy everything on unmap, recreate it on map: EGL contents disappears when switching to another page (yes!), but doesn't appear again when switching back to the first page (oops).

I'm really not sure whether it's a good idea to destroy the surface on unmap, but I don't understand at all why even doing this doesn't work.

**Comment by joanbm** [comment]
Something that is most likely the same issue (but has a simpler reproducer): Calling `canvas->Show(!canvas->IsShown());` on a `wxGLCanvas` will not hide the canvas on Wayland+EGL. It works with `GDK_BACKEND=x11` and on wxMSW.

Reproducer:

```c++
#include <wx/app.h>
#include <wx/glcanvas.h>
#include <wx/dcclient.h>
#include <wx/frame.h>
#include <wx/button.h>
#include <wx/sizer.h>

class MyWxApp : public wxApp
{
public:
	bool OnInit() override {
		auto window = new wxFrame(nullptr, -1, wxT("Test"));

		auto canvas = new wxGLCanvas(window);
		auto context = new wxGLContext(canvas);
		canvas->Bind(wxEVT_PAINT, [context, canvas](wxPaintEvent& e) {
			fprintf(stderr, "Canvas paint\n");
			context->SetCurrent(*canvas);
			wxPaintDC dc(canvas);

			glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT);

			canvas->SwapBuffers();
		});

		auto button = new wxButton(window, wxID_ANY, wxT("Toggle"));
		button->Bind(wxEVT_BUTTON, [window, canvas](wxCommandEvent& evt) {
			fprintf(stderr, "Shown is now %d\n", !canvas->IsShown());
			canvas->Show(!canvas->IsShown());
			window->Layout();
			window->Refresh(true);
		});

		auto sizer = new wxBoxSizer(wxHORIZONTAL);
		sizer->Add(button, 0, wxEXPAND);
		sizer->Add(canvas, 1, wxEXPAND);
		window->SetSizer(sizer);
		window->Layout();

		window->Show(true);
		SetTopWindow(window);
		return true;
	}
};

IMPLEMENT_APP(MyWxApp)
```

**Comment by joanbm** [comment]
I'm not very familiar with the code but that's how I understand it as well. On Wayland [the window created with `wl_egl_window_create` appears to be detached from the GDK window](https://github.com/wxWidgets/wxWidgets/blob/54d44fcb536625b7ba71b81ff8ad6d1cb56db6ba/src/unix/glegl.cpp#L505) so it does not automatically hide along with the GDK window unlike on X11. On the GTK3 code it appears to do what you say, it [registers a handler for the hide event and calls `wl_egl_window_destroy` there](https://gitlab.gnome.org/GNOME/gtk/-/blob/d8190aae3ff2f0a63a8fb72922fb117b5ab34b6a/gdk/wayland/gdkwindow-wayland.c#L3344), and then re-creates the surface when it is shown again.

**Comment by vadz** [comment]
I guess what I don't understand is what should be the actual GTK widget to an EGL surface. Currently we just create a generic `wxWindow` (`wxPizza` at GTK level) and this seems wrong, but I have no idea what would be right.

**Comment by joanbm** [comment]
My attempt at solving the issue so far: https://github.com/joanbm/wxWidgets/commit/535b1b12f94574d944da00234814d2bc4b9135fb, fixes both OP's and my reproducer.

It registers a signal for the GTK widget "map" (~=show) event and moves part of the code from `wxGLCanvasEGL::CreateSurface()` there, and does the corresponding cleanup to destroy the surface on the "unmap" (~=hide) event.

Before submitting a PR I want to do some more research to see if that is indeed the best/only way, plus more testing.

**Comment by vadz** [comment]
> My attempt at solving the issue so far: [joanbm@535b1b1](https://github.com/joanbm/wxWidgets/commit/535b1b12f94574d944da00234814d2bc4b9135fb), fixes both OP's and my reproducer.

Great, thanks a lot!
 
> It registers a signal for the GTK widget "map" (≅show) event and moves part of the code from `wxGLCanvasEGL::CreateSurface()` there, and does the corresponding cleanup to destroy the surface on the "unmap" (≅hide) event.

This seems very close to what I had tried originally, but I think I made the mistake of connecting to map/unmap on `m_widget` rather than `m_wxwindow`...

> Before submitting a PR I want to do some more research to see if that is indeed the best/only way, plus more testing.

TIA!

**Comment by joanbm** [comment]
I submitted a PR (#23835) with a slightly more polished fix.

> I guess what I don't understand is what should be the actual GTK widget to an EGL surface. Currently we just create a generic wxWindow (wxPizza at GTK level) and this seems wrong, but I have no idea what would be right.

I guess any widget would work since we just paint over it, we don't really use it other than for layout and events. Not sure if there's anything more barebones.

> This seems very close to what I had tried originally, but I think I made the mistake of connecting to map/unmap on m_widget rather than m_wxwindow...

Actually, in this case AFAICT, `m_widget == m_wxwindow`, so it must have been something else.

**Comment by imciner2** [comment]
@vadz will you have a chance to include this in the 3.2.3 backports?

**Comment by vadz** [comment]
Yes, thanks for the reminder, I'll add it to #23891 soon.
