### ISSUE TITLE
Casting from wxAny to wxVariant back to wxAny changes value of 64-bit signed integers

### ISSUE THREAD

**Issue by adrianlopezroche** [wxWidgets/wxWidgets#22592]
Casting from `wxAny` containing a 64-bit signed integer value (e.g. `long long`) to `wxVariant` back to `wxAny` changes the contained value as if the 64-bit signed integer were being cast to a 32-bit unsigned integer type.

```
wxAny any1 = (long long)-1;
wxAny any2 = (wxVariant)any1;

printf("%lld\n", any2.As<long long>());
```
Expected output: -1
Actual output: 4294967295

Note that the following code works as expected:

```
wxVariant variant = wxLongLong((long long)-1);
wxAny any3 = variant;

printf("%lld\n", any3.As<long long>());
```
Expected output: -1
Actual output: -1

wxWidgets 3.2.0 RC1 on Linux Mint (wxGTK)

Patch (console sample) showing the problem: [example-patch.txt](https://github.com/wxWidgets/wxWidgets/files/9033342/example-patch.txt)

**Comment by PBfordev** [comment]
FWIW, it works as expected on MSW with MSVS 2022 in 32- and 64-bit builds, i.e., the output is `-1`, The `wxVariant` created from `any1` returns `long` as its type. 

The obvious difference between Linux and MSW, which may or may not be relevant here (I am MSW only so I cannot debug), is that unlike on Linux, `long` on MSW is 32-bit even in 64-bit builds (i.e., LP64 vs LLP64).

**Comment by vadz** [comment]
Thanks, this is fixed by the linked PR.

**Comment by adrianlopezroche** [comment]
I can confirm this fixes the issue.
