### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by mangado** [wxWidgets/wxWidgets#22597]
Do you have any problems with Linux? You keep publishing "apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc"!
This one is bad and causes problems!

**Comment by eranif** [comment]
have u tried using https instead of http?
(I am not near a computer right now)

**Comment by vadz** [comment]
What exactly do you mean by "bad" and which problems does it cause? Please be more precise.

**Comment by mangado** [comment]
When i add this key via apt-key no report any issues..
When i add repository package manager says:
"W: https://repos.codelite.org/wx3.1.5/ubuntu/dists/impish/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."

**Comment by dghart** [comment]
>This one is bad and causes problems!

As it says, it's a _warning_, not 'bad'. Since impish the way keys are managed has changed: see e.g. [this link](https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system) but google will supply many more.

In practice, you don't need to do anything different and the warning can just be ignored.

**Comment by mangado** [comment]
ok, if you think no problem ?...
The "solution" you provided in the link is not very encouraging ...
this "warning only" is very annoying...
And so for consolation. Wayland is coming and black clouds are gathering over wxWidgets ..
There is no "move event".

**Comment by vadz** [comment]
No, there is no problem here and, please, don't use the issue tracker for the poetic remarks about the clouds. If you have any questions, please ask them on the mailing list.
