### ISSUE TITLE
Version 3.2 + Vscode - Cmake could NOT find wxWidgets (missing: net core base)

### ISSUE THREAD

**Issue by alex290** [wxWidgets/wxWidgets#22590]
**Describe the problem**

When connecting the wxWidgets 3.2.0 RC1 version, Cmake does not see the library. Moreover, all previous versions work perfectly

`Could NOT find wxWidgets (missing: net core base)`

![](https://i.imgur.com/ObAIWgS.png)

![](https://i.imgur.com/B1nfeqy.png)

Here is the Cmake code

    cmake_minimum_required(VERSION 3.20.0)
    project(Test VERSION 0.1.0)
    
    set(CMAKE_CXX_STANDARD 17) 
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    
    IF (WIN32)
      set(wxWidgets_ROOT_DIR "c:/wxwidgets/3.2.0")
      set(wxWidgets_LIB_DIR "c:/wxwidgets/3.2.0/lib/gcc1210_x64_dll")
    ENDIF()
    
    
    
    find_package(wxWidgets REQUIRED COMPONENTS net core base)
    include(${wxWidgets_USE_FILE})
    
    file(GLOB project
        src/*
    )
    add_executable(${PROJECT_NAME} ${project})
    
    
    if(wxWidgets_FOUND)
        target_link_libraries(${PROJECT_NAME} ${wxWidgets_LIBRARIES})
        target_include_directories(${PROJECT_NAME} PRIVATE ${wxWidgets_INCLUDE_DIRS})
        message(STATUS "Found wxWidgets ${wxWidgets_VERSION_STRING}")
    else()
        message(STATUS "wxWidgets Not Found")
    endif()

If you switch to the previous version, everything is fine

![](https://i.imgur.com/4F5diJZ.png)

Used an assembly MinGW 12.10

**Comment by vadz** [comment]
You need to use the latest version of `findwxWidgets.cmake` (which is not available in any released CMake versions yet AFAIK) or use `find_package(... CONFIG)` to make this work.

Unfortunately there is not much else/more we can do about this, Maarten has already fixed the CMake file to find 3.2, but now CMake people need to release a new version with it.

**Comment by alex290** [comment]
That is, you need to wait until version 3.24 is released?

**Comment by PBfordev** [comment]
I assume there was a good reason to break the compatibility; however, this incompatible change is not mentioned in the docs at https://docs.wxwidgets.org/trunk/overview_cmake.html#cmake_find_package (i.e., `CONFIG` is not listed) nor in the change log?

If the incompatible change could not be avoided, perhaps it could be mentioned more prominently, as I can see it causing a lot of grievance, regardless of whose "fault" it is.

**Comment by MaartenBent** [comment]
It is tagged for CMake 3.25. I can ask if it can be included in 3.24.

The `findwxWidgets` module used by CMake used hard-coded versions, and therefore did not check for `32` in the filename. It is not a result of an 'incompatible' change.

`CONFIG` mode is only useful if you build and install wxWidgets using CMake, not when using the prebuilt binaries or provided packages, or build with makefiles, msvc solutions, configure. This could be mentioned in the documentation you linked.

**Comment by vadz** [comment]
@PBfordev we can't avoid this change, i.e. the only way to do it is to avoid changing wx version to 3.2.0. It would have been nice if we had noticed that `findwxWidgets.cmake` was so broken earlier (and, in fact, others had already noticed it, but we didn't know about it), but there is not much to do about this any longer. We can document the problem, but it doesn't really help anybody not using CMake 3.25...

**Comment by PBfordev** [comment]
I do understand that the problem is with CMake's module, which apparently does not have a maintainer (e.g., I reported [an issue](https://gitlab.kitware.com/cmake/cmake/-/issues/23519) there a month ago with no response). 

But if I understand correctly, the programs using `find_package(wxWidgets REQUIRED)` in their CMakefile will stop finding wxWidgets v3.2 and newer unless they upgrade their CMake installation to v3.25 (which may not be available upon wxWidgets 3.2 release)? 

IMO, this should be mentioned (and explained it is not wxWidgets fault) somewhere where it would be easy to notice...

**Comment by oneeyeman1** [comment]
@PBfordev ,
It is possible to use wxWidgets with cmake. People will need to use provided code and don't rely on cmake module.
And yes - it should be mentioned somewhere.
Thank you.
