### ISSUE TITLE
wxGrid FreezeTo disable horizontal scrollbar

### ISSUE THREAD

**Issue by Frnalfn** [wxWidgets/wxWidgets#22602]
I use wxWidgets 3.1.5 under Windows, in which I have developed a I have a wxGrid that contains more columns than can be displayed, so a horizontal scroll bar is needed.

The problem arises when I use FreezeTo in a virtual table base through wxGridTableBase: if the wxGrid contains more rows than can be displayed both the horizontal and vertical scroll bars are visible,

To prove it you can use the example provided by wxWidgets **Grid control wxWidgets sample,** modifying the **BigGridFrame** constructor in **griddemo.cpp** like so:
   `// ============================================================================ `
   `// ============================================================================`
    `// BigGridFrame and BigGridTable:  Sample of a non-standard table`
`    // ============================================================================`   
`BigGridFrame::BigGridFrame(long sizeGrid)`
`        : wxFrame(NULL, wxID_ANY, "Plugin Virtual Table")`
    `{`
`        m_grid = new wxGrid(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);`
`        m_table = new BigGridTable(sizeGrid);`
`       // VZ: I don't understand why this slows down the display that much,`
`       //     must profile it...`
`       //m_table->SetAttrProvider(new MyGridCellAttrProvider);`
`       m_grid->AssignTable(m_table);`
`       SetClientSize(FromDIP(wxSize(500, 450)));`
`       //if sizeGrid <12 the horizontal scrollbar will not be displayed, if sizeGrid> = 12 the horizontal scrollbar will be displayed`
`       m_grid->FreezeTo(0, 3);`
`   }`

If sizeGrid <12 the horizontal scrollbar will not be displayed, if sizeGrid> = 12 the horizontal scrollbar will be `displayed`

**Comment by vadz** [comment]
No, I'm afraid it's a bug in `wxGrid` itself, see the fix in the upcoming commit.

I'll backport it to 3.2.1, but for now you will have to either use the current master or patch your wx version.
