### ISSUE TITLE
gtk4 build fails

### ISSUE THREAD

**Issue by antonio-rojas** [wxWidgets/wxWidgets#22609]
**Describe the problem**
GTK 4 build fails with
```
/build/wxwidgets/src/wxWidgets-3.2.0/src/generic/graphicc.cpp: In constructor ‘wxCairoContext::wxCairoContext(wxGraphicsRenderer*, GdkWindow*)’:
/build/wxwidgets/src/wxWidgets-3.2.0/src/generic/graphicc.cpp:2281:11: error: ‘gdk_cairo_create’ was not declared in this scope; did you mean ‘cairo_create’?
 2281 |     Init( gdk_cairo_create( window ) );
      |           ^~~~~~~~~~~~~~~~
      |           cairo_create
```
Full log attached

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: gtk4
 - OS and its version: Linux x86_64
 - Compiler being used: gcc 12.1
[log.txt](https://github.com/wxWidgets/wxWidgets/files/9060975/log.txt)

**Comment by vadz** [comment]
GTK 4 is not supported yet, so I don't think it's useful to keep this one open -- there are many more problems with it than just this one.
