### ISSUE TITLE
Possible doxygen CSS discrepancy between latest and 3.2.0

### ISSUE THREAD

**Issue by TcT2k** [wxWidgets/wxWidgets#22600]
When I look at [latest](https://docs.wxwidgets.org/latest/) there is a CSS issue in the upper right corner (and other issues like the body text right aligned):
![image](https://user-images.githubusercontent.com/5075894/177113810-e84bc63d-d679-4c69-8356-3749074bc7fe.png)

When looking at [3.2.0](https://docs.wxwidgets.org/3.2.0/) everything looks fine (new theme looks much more modern by the way).
Tested in Firefox and Chrome.

If this is just a temporary build issue please close and ignore.

**Comment by vadz** [comment]
It was a Cloudflare cache issue again, somehow purging `https://docs.wxwidgets.org/latest/` (which I had already done) didn't fix it, but purging everything did and it looks fine for me now.

**Comment by TcT2k** [comment]
> It was a Cloudflare cache issue again, somehow purging `https://docs.wxwidgets.org/latest/` (which I had already done) didn't fix it, but purging everything did and it looks fine for me now.

Figured it was something like that, just wanted to make sure.
Looks fine for me too now.
