### ISSUE TITLE
Linker error with x64-windows-static release

### ISSUE THREAD

**Issue by miklosnemeth** [wxWidgets/wxWidgets#22617]
I can compile in Visual Studio + vcpkg dynamic release, dynamic debug, static debug but static release gives me the following error.

```
1>main.obj : error LNK2001: unresolved external symbol "void __cdecl wxOnAssert(char const *,int,char const *,char const *,char const *)" (?wxOnAssert@@YAXPEBDH000@Z)
1>main.obj : error LNK2001: unresolved external symbol "void (__cdecl* wxTheAssertHandler)(class wxString const &,int,class wxString const &,class wxString const &,class wxString const &)" (?wxTheAssertHandler@@3P6AXAEBVwxString@@H000@ZEA)
1>main.obj : error LNK2001: unresolved external symbol "bool wxTrapInAssert" (?wxTrapInAssert@@3_NA)
1>C:\Users\mnemeth\source\repos\wxtest\x64\Release\wxtest.exe : fatal error LNK1120: 3 unresolved externals
```

I have the same issue compiling minimal sample when I remove wx_core and wc_base project

**Comment by vadz** [comment]
This seems like a vcpkg-specific issue, i.e. it looks like they build the static release version with the debugging support totally turned off (`wxDEBUG_LEVEL == 0`). If this is indeed the case, you must predefine it like this for your own projects too.

**Comment by miklosnemeth** [comment]
Thank you.
