### ISSUE TITLE
Memory leak in wxDatePickerCtrl destructor

### ISSUE THREAD

**Issue by cuiguanghui** [wxWidgets/wxWidgets#22616]
Memory leak in wxDatePickerCtrl destructor
--------------

In linux OS, I create many wxDatePickerCtrl in a wxDialog, when the dialog is destructed, memory has increased relative to before the control was created. Tried many times, and each time has some growth.

This is example code:
```
void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
{
    wxDialog dlg(nullptr, wxID_ANY, wxString(_("About")),wxDefaultPosition,{400,300});
    size_t iRow = 20, iCol = 20;
    for (size_t i = 0; i < iRow; i++)
    {
        for (size_t j = 0; j < iCol; j++)
        {
            wxDatePickerCtrl *tmpCtrl  = new wxDatePickerCtrl(&dlg,wxID_ANY,wxDefaultDateTime,wxPoint(130 * j, i * 40),wxSize{120, 40});
        }
    }
    dlg.ShowModal();
}
```
when the dialog is destructed, memory increased:
|process memory(kb) |increased(kb)|
|------|------|
|50776|	
|54536 |             3760|
|54580 |             44|
|56732  |            2152|
|57456  |            724|
|59008  |            1552|
|59440  |            432|
|59764  |            324|
|60392  |            628|
|61456  |           1064|

**Platform and version information**
 - wxWidgets version you use: [e.g. 3.2.0]
 - wxWidgets port you use: [ wxGTK]
 - OS and its version: [linux 5.10.0.3-generic]
 - For wxGTK only (**remove** this if not using wxGTK)
   + GTK version: [3.0]
   + Which GDK backend is used: [X11]

**Comment by paulcor** [comment]
Using `valgrind` on your example, I don't see any leaks attributable to `wxDatePickerCtrl`.

**Comment by cuiguanghui** [comment]
> Using `valgrind` on your example, I don't see any leaks attributable to `wxDatePickerCtrl`.

Using valgrind on my example, no memory leaks are found, but the memory keeps growing. Using the above method, what is the memory situation on your side? Will it grow?

**Comment by cuiguanghui** [comment]
ok, thank you very much!
