### ISSUE TITLE
Symlink installations doesn't homor DESTDIR

### ISSUE THREAD

**Issue by antonio-rojas** [wxWidgets/wxWidgets#22610]
**Describe the problem**
Cmake doesn't honor DESTDIR when creating the symlinks for wxconfig and wxrc during installation. It always tries to install them to the root filesystem instead of the specified DESTDIR, which fails if the filesystem is write-only

```
$ cmake -B build-dir -S wxWidgets-3.2.0 -DCMAKE_INSTALL_PREFIX=/usr
$ cmake --build build-dir
[...]
$ DESTDIR='foo' cmake --install build-dir
[...]
-- Installing: foo/usr/lib/libwx_baseu_xml-3.2.so
-- Installing: foo/usr/bin/wxrc-3.2
-- Set runtime path of "foo/usr/bin/wxrc-3.2" to ""
CMake Error: failed to create symbolic link '/usr/bin/wxrc': Permission denied
```

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: gtk3
 - OS and its version: Linux x86_64
 - Compiler being used: gcc 12.1

**Comment by vadz** [comment]
Sorry, I have no idea how to handle `DESTDIR` with CMake. If you know how it should be done and can propose a patch doing it, please don't hesitate to submit a PR with your changes.

**Comment by antonio-rojas** [comment]
See my downstream patch at https://github.com/archlinux/svntogit-packages/blob/packages/wxwidgets/trunk/destdir.patch

**Comment by vadz** [comment]
Sorry, this [doesn't seem to work](https://github.com/wxWidgets/wxWidgets/runs/7370584921). I've applied your patch manually, but AFAICS faithfully.

Any ideas?

**Comment by MaartenBent** [comment]
I think the added installs are missing `/bin` in the source path.

**Comment by vadz** [comment]
So it should be `${CMAKE_CURRENT_BINARY_DIR}/bin/wx-config` and ``${CMAKE_CURRENT_BINARY_DIR}/bin/wxrc`?

**Comment by MaartenBent** [comment]
In the commit, the first install is changed to use a temporary location `${CMAKE_CURRENT_BINARY_DIR}/bin/wx-config`. The second install should then install this file to the final location. So yes, I think it should be 

```cmake
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/bin/wx-config DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
``` 
and 
```cmake
wx_install(FILES ${CMAKE_CURRENT_BINARY_DIR}/bin/wxrc${EXE_SUFFIX} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
```
But I am not able to test it.

**Comment by vadz** [comment]
Thanks, this makes sense to me, let's try it like this. But I don't understand how could the "downstream patch" work...

**Comment by MaartenBent** [comment]
Not sure why it still fails. Maybe because `${CMAKE_CURRENT_BINARY_DIR}/bin`  does not exist, so creating symlinks in that directory fails. You could try adding
```cmake
install(CODE "execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/bin)"
```
before the `install ... create_symlink` calls.
Otherwise I'll be able to look into it in more detail next week.

**Comment by vadz** [comment]
Perhaps we could also drop `bin` in both steps? I'm not exactly sure what is the value of `${CMAKE_CURRENT_BINARY_DIR}`, but I think this would work too, wouldn't it?

**Comment by antonio-rojas** [comment]
> Perhaps we could also drop `bin` in both steps? I'm not exactly sure what is the value of `${CMAKE_CURRENT_BINARY_DIR}`, but I think this would work too, wouldn't it?

That's what the downstream patch is doing. There is no `bin` there.

**Comment by MaartenBent** [comment]
That should probably work too. There used to be a `bin` in the patch, otherwise it wouldn't show up in https://github.com/vadz/wxWidgets/commit/201fcb025bfe17e77eead05149372409ca18fce5

**Comment by vadz** [comment]
> > Perhaps we could also drop `bin` in both steps? I'm not exactly sure what is the value of `${CMAKE_CURRENT_BINARY_DIR}`, but I think this would work too, wouldn't it?
> 
> That's what the downstream patch is doing. There is no `bin` there.

Damn, sorry, no idea how did I end up with it :-( I really should have known better than to try applying it manually. Anyhow, I'll merge it once the CI builds pass, thanks and sorry again for the confusion.

**Comment by vadz** [comment]
> That should probably work too. There used to be a `bin` in the patch, otherwise it wouldn't show up in [vadz@201fcb0](https://github.com/vadz/wxWidgets/commit/201fcb025bfe17e77eead05149372409ca18fce5)

No, apparently, I've just misapplied it somehow. I really have no idea how did it happen, but I was doing it while being in the middle of something else and not really paying attention, so I must have made a mistake. Sorry.

**Comment by imciner2** [comment]
My concern with creating the symlink in the build tree at the install time like that is, will the link actually resolve the pathing properly in all cases?

If the `create_symlink` script creates it as an absolute symlink, then it may not be a relocatable installation required by packaging systems (e.g. Fedora RPM packages install into a directory like `/builddir/build/BUILDROOT/wxgtk/`in the RPM build tree but expects the installed files to treat the contents of `wxgtk/` as if they are actually at the filesystem root). An absolute symlink would then point to the file in the `/builddir` path.

If instead it is a relative symlink, then the symlink instead encodes the path between the build tree bin folder and the install tree lib folder, and the resulting copy of the symlink into the install tree may not actually point to the proper location depending on its build tree location.

The best way I found to work around this issue was to actually make the symlink a build-time object and then install it later. The example I did is here: https://gitlab.com/kicad/code/kicad/-/blob/5c5dc689cf5da237e7ec0976f6931e7a289cba32/pcbnew/CMakeLists.txt#L863. First it will figure out the relative pathing between the desired instal target location and original files, and then create a symlink in the build directory with that relative pathing. I can't remember exactly why, but I had issues with `create_symlink` in the build directory not liking the pathing I used (maybe it was something to do with dangling links since the link won't resolve at build time, only at install time), so I just have an external command call to `ln -sf` instead.

**Comment by MaartenBent** [comment]
I might have a simpler solution that doesn't create a temporary file. We can just escaped `$ENV{DESTDIR}` in the symlink path, so it is not evaluated when configuring, but only when installing. It didn't seem to work with the `wx_install` macro, so I added a `wxBUILD_INSTALL` check and used `install` directly.

The [documentation ](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html)mentions `DESTDIR` shouldn't be used in Windows, so I'm ignoring it there. I also added quotes around the full paths.

```diff
 build/cmake/install.cmake        |  9 +++++++--
 build/cmake/utils/CMakeLists.txt | 13 +++++++++----
 2 files changed, 16 insertions(+), 6 deletions(-)

diff --git a/build/cmake/install.cmake b/build/cmake/install.cmake
index 9a2ce91d7f..4c40de1484 100644
--- a/build/cmake/install.cmake
+++ b/build/cmake/install.cmake
@@ -40,10 +40,15 @@ else()
         )
 
     install(DIRECTORY DESTINATION "bin")
+    if(WIN32)
+        set(install_path ${CMAKE_INSTALL_PREFIX})
+    else()
+        set(install_path \$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX})
+    endif()
     install(CODE "execute_process( \
         COMMAND ${CMAKE_COMMAND} -E create_symlink \
-        ${CMAKE_INSTALL_PREFIX}/lib/wx/config/${wxBUILD_FILE_ID} \
-        ${CMAKE_INSTALL_PREFIX}/bin/wx-config \
+        \"${install_path}/lib/wx/config/${wxBUILD_FILE_ID}\" \
+        \"${install_path}/bin/wx-config\" \
         )"
     )
 endif()
diff --git a/build/cmake/utils/CMakeLists.txt b/build/cmake/utils/CMakeLists.txt
index 47bca6f34a..c25b6cbbe5 100644
--- a/build/cmake/utils/CMakeLists.txt
+++ b/build/cmake/utils/CMakeLists.txt
@@ -30,17 +30,22 @@ if(wxUSE_XRC)
         BUNDLE DESTINATION "bin"
         )
 
-    if(NOT WIN32_MSVC_NAMING)
+    if(NOT WIN32_MSVC_NAMING AND wxBUILD_INSTALL)
         if(IPHONE)
             set(EXE_SUFFIX ".app")
         else()
             set(EXE_SUFFIX ${CMAKE_EXECUTABLE_SUFFIX})
         endif()
 
-        wx_install(CODE "execute_process( \
+        if(WIN32)
+            set(install_path ${CMAKE_INSTALL_PREFIX})
+        else()
+            set(install_path \$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX})
+        endif()
+        install(CODE "execute_process( \
             COMMAND ${CMAKE_COMMAND} -E create_symlink \
-            ${CMAKE_INSTALL_PREFIX}/bin/${wxrc_output_name}${EXE_SUFFIX} \
-            ${CMAKE_INSTALL_PREFIX}/bin/wxrc${EXE_SUFFIX} \
+            \"${install_path}/bin/${wxrc_output_name}${EXE_SUFFIX}\" \
+            \"${install_path}/bin/wxrc${EXE_SUFFIX}\" \
             )"
         )
     endif()
```

**Comment by vadz** [comment]
@MaartenBent Should I replace #22631 with your patch above? I'm not sure if I can follow all the escapes in it, but if it works, let's use it.

BTW, I think we could avoid `if(WIN32)` tests, as `DESTDIR` is not supposed to be used under Windows at all, it's going to be empty anyhow, so I don't see a problem with simplifying this. And if it happens to be not empty, for whatever reason, it's probably better to still respect it even if it's not used there normally.

**Comment by vadz** [comment]
Thanks, let's see if I managed to apply this patch manually correctly this time...

**Comment by antonio-rojas** [comment]
This will not work. If the target of the symlink includes DESTDIR, then the symlink will be broken when the package is installed, because it will point to a location in the build root. The symlink itself must be installed to DESTDIR, but the symlink target must not include DESTDIR.

**Comment by vadz** [comment]
Yes, I think this should work... I hadn't realized it at first, but we're really just calling `ln -s` here, and using `ln -s /real/path/to/existing/file $DESTDIR/new/path/to/the/link` should work. I've (force-)pushed another update, thanks.
