### ISSUE TITLE
[Intensify on language bindings] Ruby and Python

### ISSUE THREAD

**Issue by rubyFeedback** [wxWidgets/wxWidgets#22613]
I just read that a new wxwidets release was done.

I don't want to use C++ though. Can we get some ruby and python bindings?

I think hanmac was writing the old ruby-bindings. https://github.com/Hanmac/rwx
He has not updated it in a long time but who knows - perhaps people could be
motivated. Perhaps something similar to gobject-introspection for wxwidgets
but easier and simpler to use as well as with more debug-useful information.

**Comment by vadz** [comment]
Sorry, maintaining bindings to the other languages is outside of the scope of wxWidgets project itself. We'd be glad to help any people who want to revive wxRuby and, of course, [wxPython](https://www.wxpython.org/) already is in a very good shape AFAIK, but we don't have the resources to develop such bindings ourselves.

**Comment by Hanmac** [comment]
I really need to revive rwx, especially after wx widgets might have done some other changes like Bitmap Bundle
