### ISSUE TITLE
implement "EnableProofCheck" for  wxRichTextCtrl as already done for wxTextCtrl 

### ISSUE THREAD

**Issue by EckardKlotz** [wxWidgets/wxWidgets#22636]
Dear Developers.

You have added the  support for using native spell checking in wxTextCtrl (iwbnwif) with the release 3.1.6.

Please do the same in wxRichTextCtrl.

In the "wxRichTextCtrl Overview" you write : "... wxRichTextCtrl is largely compatible with the wxTextCtrl API, but extends it where necessary." Thus the implementation of the "EnableProofCheck" functionality would be consequent.

As you may know the use wxTextCtrl on Windows with "MinGW TDM 64 bit" is very problematic since its ["std::streambuf" issue](https://groups.google.com/g/wx-users/c/D9vmQWFKgA8/m/BWIlTA5XAAAJ). Thus it is not possible to use wxTextCtrl without the mentioned modification of the header "wx/textctrl.h".

wxRichTextCtrl would be a good alternative but it provides no spell-check until now as far as I understand it.

Best regards,
                    Eckard Klotz.

**Comment by vadz** [comment]
Sorry, I don't think this is going to realistically happen unless someone contributes support for it and this is not going to be simple because native spell checking works, almost by definition, for the native text controls. So I don't think it's useful to keep this one open, even if any contributions to wxRTC would be welcome, of course.

As an aside, I don't think using `wxTextCtrl` with MinGW is problematic at all, there is no explanation for the issue reported in that mailing list thread, but it's absolutely not ubiquitous and many people, including me, use `wxTextCtrl` with MinGW just fine.

**Comment by EckardKlotz** [comment]
Dear Vadz.

If you think that it is not realistic to implement the spell check with the `wxRichTextCtrl` as done for the `wxTextCtrl`, then this is something you may know better than I.

But it is a fact that the `wxTextCtrl` is not working  "MinGW TDM 64 bit":
Please take look to the ["std::streambuf" issue](https://groups.google.com/g/wx-users/c/D9vmQWFKgA8/m/BWIlTA5XAAAJ). I have provided.
Alternatively you could take a look into your forum: [Abnormal program exit](https://forums.wxwidgets.org/viewtopic.php?f=1&t=46685)

If you build wxWidgets as a monolithic 64 bit DLL by using [TDM-GCC 10.3.0](https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release) you could use in your application not more than on instance of the class `wxTextCtrl`. Otherwise the application is crashing while destroying the instances. You will already face this issue with the official sample. 

It works only if you modify the header "wx/textctrl.h" as Vadim Zeitlin wrote:

>    There is something weird with std::streambuf specifically in this TDM
>    version. In this case you could try editing wx/textctrl.h and setting
>    wxHAS_TEXT_WINDOW_STREAM to 0 there to disable inheriting wxTextCtrl
>    from std::streambuf and see if it helps.

Thus I implemnted the following change:

```
  #if wxUSE_STD_IOSTREAM
    #include "wx/ioswrap.h"
  //    #define wxHAS_TEXT_WINDOW_STREAM 1
      #define wxHAS_TEXT_WINDOW_STREAM 0 // changed by Eckard Klotz 2022.07.10
  #else
      #define wxHAS_TEXT_WINDOW_STREAM 0
  #endif
```

And yes, if you do so before building the DLL and the application it helps.

Do you prefer to have this as an own bug-report?

Best regards,
                     Eckard Klotz.
