### ISSUE TITLE
The class wxTextCtrl is not working while building with "MinGW TDM 64 bit

### ISSUE THREAD

**Issue by EckardKlotz** [wxWidgets/wxWidgets#22639]
Dear Developers.

The class `wxTextCtrl` is not working while building with "MinGW TDM 64 bit.

If you build wxWidgets as a monolithic 64 bit DLL by using [TDM-GCC 10.3.0](https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release) you could use in your application not more than on instance of the class `wxTextCtrl`. Otherwise the application is crashing while destroying the instances. You will already face this issue with the official sample.

Please take look to the ["std::streambuf" issue](https://groups.google.com/g/wx-users/c/D9vmQWFKgA8/m/BWIlTA5XAAAJ). 
In addition you could take a look into your forum: [Abnormal program exit](https://forums.wxwidgets.org/viewtopic.php?f=1&t=46685)

It works only if you modify the header "wx/textctrl.h" as Vadim Zeitlin wrote:

>     There is something weird with std::streambuf specifically in this TDM
>     version. In this case you could try editing wx/textctrl.h and setting
>     wxHAS_TEXT_WINDOW_STREAM to 0 there to disable inheriting wxTextCtrl
>     from std::streambuf and see if it helps.

Thus I implemented the following change:

  #if wxUSE_STD_IOSTREAM
    #include "wx/ioswrap.h"
  //    #define wxHAS_TEXT_WINDOW_STREAM 1
      #define wxHAS_TEXT_WINDOW_STREAM 0 // changed by Eckard Klotz 2022.07.10
  #else
      #define wxHAS_TEXT_WINDOW_STREAM 0
  #endif

And yes, if you do so before building the DLL and the application it helps. But this is only a workaround and hope you are able to provide a more professional solution.

**Platform and version information**
 - wxWidgets version you use: 3.1.5  ... 3.2.0
 - wxWidgets port you use: wxMSW
 - OS and its version: 
> Edition	Windows 10 Home
> Version	21H2
> Betriebssystembuild	19044.1826
> Leistung	Windows Feature Experience Pack 120.2212.4180.0

 - Compiler being used: TDM-GCC 10.3.0

Best regards,
Eckard Klotz.

**Comment by vadz** [comment]
Thanks, but to make this bug report more useful, could you please:

1. Confirm that it only happens in monolithic build. I have a lot of trouble seeing how can it be related to monolithic/multilib, so it would be really great to have a confirmation that the issue does _not_ happen with the normal multilib build, e.g. using the official binaries for 3.2.0.
2. Show the minimal change necessary to actually reproduce the problem. Does it happen in the unmodified text sample? If not, could you please provide a minimal diff to it or the minimal sample showing the problem?

TIA!

**Comment by EckardKlotz** [comment]
Dear Vadz.

Since I only use a monolithic build DLL of wxWidgets I could not confirm that it is not happening with separate DLLs or with static libraries.

The  change I have implemented was done in the wxWidgets header `textctrl.h` located in

-  `[WX_WIDGETS_ROOT]\include\wx\`[textctrl.zip](https://github.com/wxWidgets/wxWidgets/files/9132477/textctrl.zip)
-  The change is done in lines 29  and 30.

I have not modified the text sample but the wxWidgets library code.

- But without modifying the library header the sample is showing the issue.

Actually I thought this issue is already known by you since 2018 since the one who has suggested the workaround "Vadim Zeitlin" seems to be the author of the source-file I have modified.

Best regards,
                     Eckard Klotz.

**Comment by vadz** [comment]
Yes, I suggested the workaround because it clearly bypasses the problem entirely. As you said, this is not a proper solution, but I didn't have time to debug the issue back then -- and, to be honest, don't have much more time to do it now neither. So if you could check whether the issue occurs with the multilib build, it would be helpful.

**Comment by EckardKlotz** [comment]
Dear Vadz.

The big disadvantage of using small part-libraries is the fact that you have to figure out which you really need.

However, as far as I understand you use the same compiler for your official TDM binary release.
Please tell me which DLLs or static libraries from your official TDM binary release I have to use for linking the sample and I will check for you if the same issue occurs.

- Please note that I use [Code::Blocks](https://www.codeblocks.org/) for my development and even it is possible to import your Visual Cpp projects I still have to do some manual configurations.
- Therefore I need your list of DLLs and/or static libraries.

Best regards,
                    Eckard Klotz.

**Comment by vadz** [comment]
OK, thanks, I'll try to debug this.

**Comment by EckardKlotz** [comment]
Hello Vadz.

Thank you in advance for all the effort you will take.

Best regards,
                   Eckard Klotz.

**Comment by PBfordev** [comment]
Just for the record: I think this is a rather old issue, discovered in 2020 with TDM 9.2 (only 64-bit version IIRC) and discussed on [wx-dev](https://groups.google.com/g/wx-users/c/D9vmQWFKgA8/m/BWIlTA5XAAAJ) and [forum](https://forums.wxwidgets.org/viewtopic.php?f=1&t=46685).

And to answer the question from the related PR: [WinLibs](https://winlibs.com/) is a MinGW distribution (unlike [nuwen](https://nuwen.net/mingw.html) not providing some popular prebuilt libraries but being more up-to-date), aiming to fill a hole left by mingw-64 project not providing their own installer anymore. I know it may be hard to believe, but it seems many people do not like / are not familiar with MSYS2 environment and strongly prefer to use non-MSYS2 up-to-date MinGW distro and building wxWidgets with a makefile.

**Comment by vadz** [comment]
Yes, thanks, these links were actually given in #22636 in which I had asked to create a separate issue for this problem, but the context got lost, sorry about this.

As for people preferring building with a makefile, I realize that they exist. This is a problem because I have no idea how to maintain the makefiles for them, but, I guess, we'll have to do it somehow...

**Comment by vadz** [comment]
I've realized that 70c5ec6eff (Move wxTextCtrl constructors out of line in wxMSW, 2022-07-18) still wasn't backported to 3.2. I think it should be safe to do it, but it'd be great if somebody could actually confirm it, i.e. build a program with the current wx 3.2 DLLs, then apply this commit, rebuild the DLLs and confirm that the program still runs when using them (and sorry in advance if anybody has already done it and I just forgot about it, but I couldn't find anything like this in the various bugs/PRs associated with this problem).

**Comment by vadz** [comment]
I've finally tested this myself and as it seems to work fine, I'm backporting this fix to 3.2.
