### ISSUE TITLE
cmake: DESTDIR installation fails to create two symlinks

### ISSUE THREAD

**Issue by 0-wiz-0** [wxWidgets/wxWidgets#22647]
When building wxGTK 3.2.0 with cmake and installing to a DESTDIR (i.e. a temporary installation prefix used for packaging up the installed files), two symlinks creations fail:
```
CMake Error: failed to create symbolic link '/usr/pkg/bin/wx-config': Permission denied
...
CMake Error: failed to create symbolic link '/usr/pkg/bin/wxrc': Permission denied
```

The problem is that it tries to create them in ${PREFIX} instead of ${DESTDIR}${PREFIX}.

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: wxGTK
 - OS and its version: NetBSD, but doesn't matter
 - Compiler being used: gcc 10.3.0, but doesn't matter

**Comment by vadz** [comment]
This seems identical to #22610.

**Comment by 0-wiz-0** [comment]
Yes, sorry, I hadn't seen this. Thanks!
