### ISSUE TITLE
cmake: missing check for curl

### ISSUE THREAD

**Issue by 0-wiz-0** [wxWidgets/wxWidgets#22648]
When using the cmake build system, there is no check for curl, but later the build unconditionally tries to use `curl/curl.h` from `include/wx/private/webrequest_curl.h` and the build fails.

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: wxGTK
 - OS and its version: NetBSD 9.99.98/amd64
 - Compiler being used: gcc 10.3

**Comment by vadz** [comment]
This is strange, we use `find_package(CURL)` which should fail if libcurl is really unavailable.

Perhaps we need to add some variable this call sets to the include (and library) options?

**Comment by MaartenBent** [comment]
Indeed, if `find_package(CURL)` cannot find CURL, it disables `wxUSE_WEBREQUEST_CURL` and `curl.h`  should never be included.

Can you check the result variables here (like `message("CURL_INCLUDE_DIRS=${CURL_INCLUDE_DIRS}")`)? And check if the found directories have a `curl/curl.h`?

**Comment by 0-wiz-0** [comment]
Sorry, this is a local problem.
The build framework I'm using tries to hide libraries that are not explicitly pulled in.
cmake finds the curl library anyway (pulled in indirectly via another dependency), but then the compiler wrapper is good enough to hide the header file and the build fails.
Nothing to do here, sorry for the noise!
