### ISSUE TITLE
cmake: OPENGL_LIBRARIES uses undefined library names

### ISSUE THREAD

**Issue by 0-wiz-0** [wxWidgets/wxWidgets#22649]
The cmake build framework, in `build/cmake/init.cmake`, has:
```
set(OPENGL_LIBRARIES OpenGL::OpenGL OpenGL::GLU OpenGL::EGL)
```

On NetBSD 9.99.98/amd64 with cmake 3.23.2, these library names are undefined and cause build breakage.

I don't know the proper fix for this, but just removing the line makes the build succeed for me, I guess the GL libraries are pulled in via some other library.

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: wxGTK
 - OS and its version: NetBSD 9.99.98/amd64
 - Compiler being used: gcc 10.3.0

**Comment by Journeyman-dev** [comment]
I have this exact issue with Fedora. I commented out the line, and now it generates fine.

**Comment by vadz** [comment]
FWIW under Fedora these libraries must exist, you might just not have them on your system.

For NetBSD, do you know what should be the correct names of the libraries be?

**Comment by MaartenBent** [comment]
I can improve the OpenGL logic a bit and only overwrite `OPENGL_LIBRARIES` if the targets exist.

> I guess the GL libraries are pulled in via some other library.

I suspect they are pulled in here as well. `find_package(OpenGL)` also adds libraries to `OPENGL_LIBRARIES`, but we overwrite them with the EGL targets when `OpenGL_EGL_FOUND` is true.

**Comment by 0-wiz-0** [comment]
NetBSD uses the standard Mesa Library, so there is no difference to Linux here.
I grepped the tree after running cmake, but `OPENGL_LIBRARIES` is not set for me at all (after commenting out the line), at least i had no matches in any cmake cache.

**Comment by MaartenBent** [comment]
This variable is not cached. The easiest way to check its value is adding `
message("OPENGL_LIBRARIES=${OPENGL_LIBRARIES}")` to `build/cmake/lib/gl/CmakeLists.txt` or directly after `find_package(OpenGL)`.

I tested my proposed solution on Ubuntu and Windows and there it still works fine.  I'll create a PR later today so you can try it on NetBSD and/or Fedora.

**Comment by MaartenBent** [comment]
Please have a look at #22677

**Comment by 0-wiz-0** [comment]
Thanks, @MaartenBent, that fixes the problem for me!

**Comment by Journeyman-dev** [comment]
Fixed for me too. Thank you!
