### ISSUE TITLE
-

### ISSUE THREAD

**Issue by roenck** [wxWidgets/wxWidgets#22659]

**Comment by vadz** [comment]
Please make a minimal patch reproducing the problem against the menu sample, which already has a bunch of radio buttons.

**Comment by roenck** [comment]
Unfortunately, I don't have the time to write examples for everything. But I think that the basic problem is clear.

**Comment by vadz** [comment]
Unfortunately, we don't have time to fix all the bugs so we prioritise those that are critically important or which don't require spending much time on reproducing instead of trying to reproduce something that you already have in front of your eyes. Thank you for your understanding.

**Comment by oneeyeman1** [comment]
@roenck ,
Can you at least try and build the menu sample and check if this is true?

**Comment by roenck** [comment]
FYI: I added an example in forum.

**Comment by vadz** [comment]
Sorry, but do you seriously mean that you propose that I go searching for your example in the forum instead of just copy-pasting or attaching it here?

I'm just trying to understand...

**Comment by roenck** [comment]
The link was posted in the very first message of this bug report.  And if this is to much for you, than I stop to find bugs for you. I sacrifice my free time for it and I don't need such reactions.

**Comment by vadz** [comment]
Thank you for clarifying this. You certainly won't get any reactions, such or otherwise, from me in the future, I'm literally speechless.

If anybody else feels like making a reproducible example or, ideally, a unit test from the forum post, please feel free to do it, but I prefer to spend my free time on something else.
