### ISSUE TITLE
wx3.2-i18n missing for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by PMaff** [wxWidgets/wxWidgets#22655]
When installing a program (mmex) compiled with wxWidget 3.2 on Ubuntu 18.04 LTS I get the error:

```
The following packages have unmet dependencies.
 mmex : Depends: wx3.2-i18n but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Where can I find the latest internationalisation file for wxWidget 3.2 ?
This is not really a build problem but I did not find an install category.

**Comment by vadz** [comment]
3.2 packages are only available from [CodeLite repositories](https://docs.codelite.org/wxWidgets/repo320/) but I don't think they provide them for 18.04 and, of course, Ubuntu won't provide it neither considering that 18.04 support must have ended. You may try to manually install the 20.04 i18n package, as it's not really dependent on the OS version, but a better solution would be to either update your OS or to build both wx and the program you use yourself from sources.

But we can't really help you with this, sorry.

**Comment by PMaff** [comment]
I built wxWidget 3.2 and the program mmex from sources.
End of standard support for Bionic is April 2023.
So if CodeLite is not doing anything, all the people who are using Bionic are lost?

**Comment by vadz** [comment]
If you built them from sources, why do you need the package? `make install` should have already installed the message catalogs on your system.

**Comment by PMaff** [comment]
I was trying to install the resulting deb file mmex_1.5.18-Beta.1-1~bionic_amd64.deb .
I know that "make install" would be also possbile, but we try to provide the debs .

**Comment by vadz** [comment]
Sorry, I'm completely lost... Are you building the Debian package yourself? If so, you should be well placed to build wx 3.2 Debian packages for 18.04 too.

The statements "I built wx from sources" and "I need wx package" seem to be incompatible with each other.

**Comment by PMaff** [comment]
wxWidget was compiled from source, then make install, then ldconfig.

Afterwards mmex was compiled from sources.
During this also the mmex*.deb is created.
Maybe the inclusion of the i18n catalogs is missing there?

**Comment by swt2c** [comment]
> wxWidget was compiled from source, then make install, then ldconfig.
> 
> Afterwards mmex was compiled from sources. During this also the mmex*.deb is created. Maybe the inclusion of the i18n catalogs is missing there? Thanks for your patience.

It doesn't seem right that you're building against a non-packaged wxWidgets, but then building a .deb package against that.  You should either use all packages or all not packages.  In any event, the problem is that the mmex deb you've built has a metadata dependency requiring a package called "wx3.2-i18n".  If you REALLY want to use that .deb, you'll have to remove that dependency or actually build a package with that name.
