### ISSUE TITLE
Creating a wxStaticText control in C++20 fails

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#22656]
```
new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE | wxSTATIC_BORDER); 
```

This will fail with "operator '|': deprecated between enumerations of different types"

Need to add "wxALLOW_COMBINING_ENUMS(wxAlignment, wxBorder)" in defs.h

**Comment by dconnet** [comment]
Looks like that one 'allow' wasn't enough (I must have forgotten to unsuppress the warning when testing earlier, sorry!)
In my code, I also needed to add:
```
wxALLOW_COMBINING_ENUMS(wxSizerFlagBits, wxAlignment)
wxALLOW_COMBINING_ENUMS(wxSizerFlagBits, wxDirection)
wxALLOW_COMBINING_ENUMS(wxSizerFlagBits, wxStretch)
```
because of my use of `wxRESERVE_SPACE_EVEN_IF_HIDDEN` on sizers.

**Comment by vadz** [comment]
Thanks, I'll create a new issue for this because I'd actually already backported this one to 3.2 (but it didn't get closed because only commits to master really close issues, argh).
