### ISSUE TITLE
Building wxWidgets by specifying VENDOR="" (which defaults to "custom") will cause an extra underscore "_" at the end of the DLL names

### ISSUE THREAD

**Issue by tomay3000** [wxWidgets/wxWidgets#22662]
When specifying **VENDOR=""** (which defaults to "**custom**") in the make command, will result in the DLL names having an extra underscore "**_**" at the end.

To avoid this we have to either specify **OFFICIAL_BUILD=1** and must set **COMPILER_VERSION** to the actual compiler version, or simply specify **VENDORTAG=""** which defaults to **VENDORTAG = _$(VENDOR)** from the **makefile**.
As you can see the underscore "**_**" is static, and will be always present no matter what for non official builds.

The workaround here is to use **VENDORTAG=""**, but **VENDORTAG** is not publicly exposed.

**Comment by vadz** [comment]
Vendor tag _must_ be not empty, the idea is that it's empty only for the official builds. So what you want to do is intentionally not supported, you have to use some unique suffix for your own builds.
