### ISSUE TITLE
Remove wxMotif and wxGTK 1

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22688]
Nobody uses them any more except @joukj on OpenVMS but their compiler will almost certainly fail to deal with C++14 anyhow, so they will have to stay at 3.2 anyhow.

**Comment by setdebug** [comment]
No, leave wxMotif alone. It isn't hurting anyone.

**Comment by lanurmi** [comment]
> No, leave wxMotif alone. It isn't hurting anyone.

It isn't helping anyone either. Even the minimal sample fails to operate properly with wxMotif.

**Comment by vadz** [comment]
@setdebug Do you use wxMotif? Do you know anybody who does?

**Comment by vadz** [comment]
As an example of why I want -- and will -- do it, there are thousands of occurrences of `NULL` in wxGTK1 and wxMotif sources that I can't replace automatically with clang-tidy and I really don't want to spend hours on replacing them manually.

**Comment by vadz** [comment]
This is done now, so closing.

**Comment by ProfFan** [comment]
Was just trying to use wxMOTIF and it's sad to see this news. Guess I have to use an old commit now.

**Comment by oneeyeman1** [comment]
@ProfFan ,
Motif port is unmaintained since a long time.
Which OS do you have so it comes with the Motif WM?

Thank you.

**Comment by ProfFan** [comment]
@oneeyeman1 macOS, you can just do `brew install openmotif` and it works :)

**Comment by ProfFan** [comment]
* install and run `startx /opt/homebrew/bin/mwm`

**Comment by lanurmi** [comment]
> Was just trying to use wxMOTIF and it's sad to see this news. Guess I have to use an old commit now.

There is absolutely nothing that prevents you from using the 3.2 branch and enjoying wxMotif all day long.
