### ISSUE TITLE
Remove support for older Windows versions

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22689]
Not sure what the new minimum required version should be, i.e. we could decide to still support Windows 7 as it doesn't cost that much or we could require Windows 10 (which build then?), but we definitely don't need to support XP or Vista any more.

- [x] Remove `wxUSE_COMPILER_TLS` option and just always do it.
- [x] Remove `wxHAS_MSW_TASKDIALOG`

**Comment by Kumazuma** [comment]
if wxWidgets does not need any feature of win10, I suggest to keep support for win7, I hope replace joypad api to xinput. what is we need win10 specific api or feature?

**Comment by vadz** [comment]
It does use Windows 10-specific features, see the various uses of `wxDynamicLibrary` in the code, but I think it wouldn't be a big burden to keep them, at least for now. XP support has to go, though (I actually wouldn't be surprised if it's already broken as I don't think anybody has used wx under XP for the last several years).

**Comment by TcT2k** [comment]
I think (at least for now) Win7 is a easy enough to achieve minimum target.
Maybe when the Microsoft compiler default settings change to Win 10 (like when they dropped XP default support a few years back) the situation would be different.

I haven't tested for a long time on XP, but I wouldn't be surprised if the current codebase still works on XP.

**Comment by TcT2k** [comment]
BTW many uses of `wxDynamicLibrary` in MSW code are there for outdated headers of minGW. But there are a few which are there for WinXP availability.

**Comment by utelle** [comment]
Win7 was widely used (and I'm pretty sure it still is). The (unloved) successor Win8.1 is very similar to Win7.  Taking into account that official Win8.1 support ends only in January 2023, I would propose that wx should still support Win7 and Win8 for a couple of years (as was done for XP for which official support ended in 2014).

**Comment by vadz** [comment]
Yes, I think we can do this. OTOH I'd indeed like to drop support for old MinGW. We will require gcc 5 too (see #22684), but this doesn't buy as much, unfortunately.

**Comment by Kumazuma** [comment]
There is no need about old MinGW less 8.1.0...

**Comment by vadz** [comment]
It's really not clear why should 8.1 be the cut-off and not 7 or 10 or something else.

Also, the real problem is not the compiler version but the MinGW vs MinGW-w64 distinction: the latter includes almost everything we need, but the former lacks a lot of things even in the latest releases (unless this changed very recently). I'm not sure if we can just drop support for the classic MinGW, but it would be nice if we could.

**Comment by utelle** [comment]
> It's really not clear why should 8.1 be the cut-off and not 7 or 10 or something else.

For historical reasons I have still MinGW-w64 7.3.0 installed, but I mainly use newer versions (currently 8.1.0 and 10.3.0). That is, I would be fine if only newer versions were supported. For me it wouldn't be a big deal either to upgrade to an even newer version.

> Also, the real problem is not the compiler version but the MinGW vs MinGW-w64 distinction: the latter includes almost everything we need, but the former lacks a lot of things even in the latest releases (unless this changed very recently). I'm not sure if we can just drop support for the classic MinGW, but it would be nice if we could.

I moved away from MinGW to MinGW-w64 several years ago, for the very reasons you mention. So, I'm definitely in favor of dropping support for the classic MinGW. However, I have no idea how large the classic MinGW wxWidgets user base is, but obviously those users stayed silent up to now.

**Comment by vadz** [comment]
@utelle Do wxPdfDocument and wxSQLite3 only support MinGW-w64? If so, and if you've never received any complaints about not support classic MinGW, it would be a good argument in favour of dropping support for the latter.

OTOH the project still seems to be alive, see https://osdn.net/projects/mingw/ and/or https://mingw.osdn.io/ so maybe it's worth checking if we can support at least its latest version(s).

**Comment by utelle** [comment]
> @utelle Do wxPdfDocument and wxSQLite3 only support MinGW-w64?

About 3 or 4 years ago I switched to MinGW-w64 for compiling and testing wxPdfDocument and wxSQLite3. AFAICR I was not able to compile wxSQLite3 successfully with classic MinGW back then. Although the components don't explicitly state to support only MinGW-w64, it is _de facto_ the case.

> If so, and if you've never received any complaints about not support classic MinGW, it would be a good argument in favour of dropping support for the latter.

No, over the last 3 years I did not receive any complaints regarding classic MinGW. All users that contacted me with questions or issues used either MinGW-w64 or some VS version (or used the components on other platforms).

> OTOH the project still seems to be alive, see https://osdn.net/projects/mingw/ and/or https://mingw.osdn.io/ so maybe it's worth checking if we can support at least its latest version(s).

Click on the [Downloads tab](https://mingw.osdn.io/index.html?page=download.html) of the [latter link](https://mingw.osdn.io/) ... and you will know why I don't care any longer about classic MinGW - **error 404** at the time of writing. 🥲

**Comment by PBfordev** [comment]
Regarding classic classic MinGW: I have just downloaded its latest version using the online installer (include files are dated 2021-04-11).

Among else, I still could not find declarations for features used in wxWidgets and introduced more than 15 years ago in Windows Vista, such as `IFileDialog` and related or `TaskDialog()`.

IMO, support for classic MinGW should be dropped.

**Comment by vadz** [comment]
Thanks for testing! It looks like there is unanimous support for dropping it and I'll do it when I finally start cleaning this up.

**Comment by vadz** [comment]
This is done now, but doesn't allow to simplify code nearly as much as I'd like to because we still have to support the old comctl32.dll v5 (see [this thread](https://groups.google.com/g/wx-dev/c/JP4O27KuypA)), so I've opened #22964 for it.
