### ISSUE TITLE
Drop support for pre-C++11 compilers

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22684]
This will require at least gcc 4.8, clang 3.4, MSVS 2015 which seems reasonable.

See https://en.cppreference.com/w/cpp/compiler_support/11

Some of the things to do:

- [x] Remove MSVS < 2015 support, including the checks for it in the code, all `.vcproj` files (and prevent bakefile from regenerating them while we still use it) and CI jobs using it.
- [x] Remove checks for gcc < 4.8 in the code.
- [x] Replace macros such as `wxOVERRIDE`, `wxNOEXCEPT` etc with their values (still keep the macros themselves, however, as somebody is almost surely using them in their code and there is no real reason to break it).
- [ ] Modernize the code base using clang-tidy (`bear -- make` can be used to generate the compilation database for it, note that it has to be done separately for all ports).
  - [x] modernize-use-nullptr 
  - [ ] modernize-loop-convert
  - [ ] modernize-raw-string-literal
  - [ ] modernize-use-using
- [x] Replace `wxConvertibleTo` from `include/wx/meta/convertible.h` with C++11 equivalent.
- [x] Replace calls to `wxShrinkToFit()` with its expansion.
- [x] Update CATCH to 2.x.
- [x] Use `__func__` instead of `__FUNCTION__`
- [x] Grep for `TODO-C++11` comments in the code.

**Comment by Kumazuma** [comment]
There is any plan dropping support for win xp?

**Comment by vadz** [comment]
Yes, see #22689.

**Comment by vadz** [comment]
I'll close this once #22962 is merged. More can, and should, be done, but let's create separate issues for the other tasks.
