### ISSUE TITLE
Add transparent selection capability to wxGrid control

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#22694]
**Describe the proposed addition**

Any modern software nowadays having grid-like control (e.g. **Microsoft Excel**,
**LibreOffice Calc**,...) uses a transparent selection instead of using solid colour
with inversion to denote selections.

In an effort to bring this capability to **wxGrid** control, here is a patch implementing this
feature besides the old way of selection. In other words, **no intention** to replace, remove or deprecate the old mechanism for the short or long term.

Before doing any PR, i would like from the interested people to try the attached patch (which can be applied to master or wx-3.2) and play with the grid sample:

- You can switch between transparent and solid selection by **Ctrl+Shift+T**
- Try some scrolling while selecting
- Try transparent selection with some frozen columns/rows and do some scrolling.

**The general idea behind the implementation:**

Doing a transparent selection (as implemented in the patch) consists of transforming the selected cells/rectangles (only the visible area) into a one rectangle/polygon/poly-polygon shape and draw it using alpha from inside the paint event.
A DC supporting alpha drawing is required for that matter. Otherwise a graphics context will be used for drawing (e.g. **GTK2** and **MSW**)

- The selected rectangles are retrieved by `wxGrid::GetSelectedRectangles()`
- Converted to poly-polygon (represented by `wxGridSelection::PolyPolygon` type) by a helper class `PolyPolygonHelper` (which can implement the **sweep line algorithm**, as done by **LibreOffice**) and finally draw the result using `wxGrid::DrawSelection()`

**The patch:**

[gridsel.zip](https://github.com/wxWidgets/wxWidgets/files/15316337/gridsel.zip)

(Tested under Linux 18.04 X11/Wayland with wxGTK3/2 and wxQt, and under Windows 10)

Regards.
AliKet.

**Comment by AliKet** [comment]
Testing the above patch under wxOSX is really appreciated, TIA!

**Comment by vadz** [comment]
Thanks, I didn't look at this yet but just wanted to say that I don't think there is any barrier to replacing the current selection display with the new one if it works well. We try not to break the API, unless it's really needed, and then preferably with a long lead time, but we didn't commit to preserving the exact same UI look or behaviour in the future wx versions.

**Comment by AliKet** [comment]
@vadz I've updated the patch above (rebased on master [95d1413](https://github.com/wxWidgets/wxWidgets/commit/95d141341a2bb64a34964f4995075372f63ccc31)) and will prepare a PR in a couple of days

https://github.com/wxWidgets/wxWidgets/assets/7704771/d275f328-7fa3-4e88-971b-69cc18f86c67

**Comment by AliKet** [comment]
> Thanks, I didn't look at this yet but just wanted to say that I don't think there is any barrier to replacing the current selection display with the new one if it works well. We try not to break the API, unless it's really needed, and then preferably with a long lead time, but we didn't commit to preserving the exact same UI look or behaviour in the future wx versions.

If it is **ok** to assume that `wxUSE_GRAPHICS_CONTEXT` will always be set to **1** then we can safely remove the old code. because `wxUSE_GRAPHICS_CONTEXT` is required (at least) under `wxMSW` and `wxGTK2` to draw the transparent selection ?

**Comment by vadz** [comment]
I think it's ok to not provide any alternative selection mechanism if `wxUSE_G_C` is off, but as long as it's not too hard to keep it around the code using it, I'd still do it because it would keep the code compilable with wxDFB which doesn't have it.

And if/when we decide to do it, we should make wxGC mandatory part of the build and remove it everywhere, not just here.

The video looks great BTW, thanks!
