### ISSUE TITLE
Event Handlers  ProcessWindowEvent(event) does not work

### ISSUE THREAD

**Issue by alex290** [wxWidgets/wxWidgets#22699]
Hello. I do event processing according to the [documentation](https://docs.wxwidgets.org/3.2.0/overview_events.html#overview_events_custom_ownclass). And the documentation states that when sending an event, there is a **`ProcessWindowEvent(event)`** command; But it is not in the classes.

Maybe I don’t understand what?

If it doesn’t work, it can be changed in the documentation.. And if it works, what I do is fine.

I'm using wx **`wxPostEvent(this, event)`** - I don't know if it's right or not.

**Comment by PBfordev** [comment]
>And the documentation states that when sending an event, there is a **`ProcessWindowEvent(event)`** command; But it is not in the classes.

This is not true, the method exists and is documented: https://docs.wxwidgets.org/latest/classwx_window.html#a0a76891d726ad5f9a729e27e4eab2b57

**Comment by alex290** [comment]
Sorry. You need to inherit from the wxWindow Class. And I inherit from wxEvtHandler.  So it didn't work.

**Comment by oneeyeman1** [comment]
Hi,
Do you have a reproducible code?
Or can you reproduce it in a sample?

Thank you.

**Comment by vadz** [comment]
`ProcessWindowEvent()` only exists in `wxWindow`, it doesn't make sense in `wxEvtHandler` as it doesn't have a separate event handlers chain, unlike a window, so for it you just use `ProcessEvent()` directly.
