### ISSUE TITLE
bool wxRegExImpl::GetMatch(size_t *start, size_t *len, size_t index) always returns true

### ISSUE THREAD

**Issue by JaiSoone** [wxWidgets/wxWidgets#22708]
In the file wxWidgets-3.2.0/src/common/regex.cpp, the aforementioned function can be fixed quite nicely with:

    if ( ( m_Matches->Start(index) == static_cast<size_t>(-1) ) ||
         ( m_Matches->End(index)   == static_cast<size_t>(-1) ) )
         return false;

if placed just before the ending:

    if ( start )
        *start = m_Matches->Start(index);
    if ( len )
        *len = m_Matches->End(index) - m_Matches->Start(index);

    return true;
}

**Comment by vadz** [comment]
Sorry, but could you please provide some context, i.e. what regex do you use, what are you matching and how do you end up with invalid match start and end position in the first place?

FWIW this function is supposed to always return `true` if its preconditions are satisfied.

**Comment by JaiSoone** [comment]
Note the comment at the bottom of this page:
https://docs.wxwidgets.org/3.2.0/classwx_reg_ex.html#a2f0bff22dd31a7f762a677afce2e26b5
where it states:
Returns false if no match or if an error occurred.
Clearly the implementing function only returns true, which is contrary to wxWidgets documentation!

**Comment by JaiSoone** [comment]
First, note that bool wxRegExImpl::Matches(const wxRegChar *str, int flags, size_t len) calls wx_regexec() which in turn calls pcre2_match(). The RegEx pattern that I compile defines 26 capture groups. The first string that I pass to Matches() only creates captures for group 13. 14, and 15. Consequently, pcre2_match() in its minimalist approach to returning starting offset ending offset pairs, only returns values for groups 0 to 15 in this case. As nothing is captured for groups 1 through 12, PCRE2_UNSET values are replaced with a -1. For capture groups greater than >= nmatchActual, in my case that is groups 16 to 26, the code just sets so and eo to static_cast<regoff_t>(-1) for them.

I'm compiling wxWidgets on MS Windows 10 using MSYS2 packaging of the latest GNU gcc compiler. In the attached file 'gdb.h', the wxRegEx() pattern is specified in lines 1237 to 1276, the Matches() call is at line 1310 (wherein '~"Console Stream Output"' is matched), and the failing GetMatch() call is at line 1315.
[test22708.zip](https://github.com/wxWidgets/wxWidgets/files/9274708/test22708.zip)

**Comment by vadz** [comment]
I agree that the documentation is insufficiently clear, but I think it was supposed to mean that this function returns false if there are no matches at all, i.e. `wxRE_NOSUB` was used or `Matches()` hadn't been called. But `wxRegEx` never handled empty matches specifically and always, since the very first version in e7208277c1 (wxRegEx class added, 2001-07-13), returned true for them.

And I've just checked and this behaved the same in 3.0 too, so we're definitely not going to change it -- but I'll improve the documentation to make it more clear.

**Comment by JaiSoone** [comment]
In addition to the comment made in your modified documentation wherein the usage of alternation can produce optional capture groups,, you should also note that usage of a repetition operator of either '?' or '*' allows for the possibility of creating optional capture groups, be they a prefix, an infix, or a suffix. You should also note that the coding of Replace believed the truthfulness of the old documentation. One further observation, as I remember, the counting of the number of capture groups can be a little off in the presence of named capture groups. I got around this by just getting the count from pcre. Certainly not worth fixing the current calculating method!

**Comment by vadz** [comment]
If you have ideas/proposals for improving the documentation, please don't hesitate to submit PRs with the changes to `interface/wx/regex.h`. TIA!
