### ISSUE TITLE
wxEVT_KILL_FOCUS not generated for wxSearchCtrl under Mac

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22702]
#### 2021-12-13 22:56:18: stuart.allie (Stuart Allie) commented

___
I can add that wxEVT_KILL_FOCUS is also not (reliably) sent for wxSearchCtrl on the Mac. It is sent sometimes (eg. changing to a new frame) but not when you simply click away from the wxSearchCtrl. wxEVT_SET_FOCUS seems to work as expected.

_Originally posted by @wxtrac in https://github.com/wxWidgets/wxWidgets/issues/19321#issuecomment-1011322552_

**Comment by sp00ck** [comment]
I have trouble with wxListCtrl
I can click outside and deselect cell, how prevent deselect cell?

before
![Przechwycenie obrazu ekranu_2022-08-06_16-57-48](https://user-images.githubusercontent.com/25770302/183255620-edf23e41-5cda-4417-908c-413de0f2fd45.png)

after click
![Przechwycenie obrazu ekranu_2022-08-06_16-58-44](https://user-images.githubusercontent.com/25770302/183255630-f5bc5639-ab14-44e8-8ef1-71c313deb34d.png)

**Comment by vadz** [comment]
@sp00ck What does this have to do with this issue? Please open new issues for unrelated problems (but in this particular case maybe better start a discussion somewhere because I don't even see how is this an issue).

**Comment by sp00ck** [comment]
this is dependent about event kill focus

**Comment by vadz** [comment]
There is no `wxSearchCtrl` in your screenshot, so it's very clearly a different issue. Please open a new issue and please actually explain what the problem is, including how to reproduce it.
