### ISSUE TITLE
ReplaceWindow not properly working with a wxNotebook on wxSplitterWindow

### ISSUE THREAD

**Issue by skeetor** [wxWidgets/wxWidgets#22731]
I'm running this against the git version of wxWindows running Visual Studio 2019.
According to the documentation ReplaceWindow should be called to replace a managed window inside a splitter. When I do this, using some other splitter or a panel it works as expected. When I do this with a notebook it doesn't seem to take proper ownership. On first glance it looks ok, but when you start resizing the window you can see all kind of  strange artifacts from the previous notebook.
In order to better test this, I modified the splitter.cpp from the sample projects to create a minimal example showing the problem.

I just replaced the original OnReplace test method with the one below, so the sample can be triggered by simply using the existing "Replace right window" menu entry.  If you just use ReplaceWindow with a regular window (i.E. wxPanel), everything work fine.

     #include "wx/notebook.h"

     void MyFrame::OnReplace(wxCommandEvent& WXUNUSED(event) )
     {
        wxWindow *w = m_splitter->GetWindow2();

        wxNotebook *nb = wxDynamicCast(w, wxNotebook);
        if (nb)
        {
            w = nb->GetPage(0);
            nb->RemovePage(0);
            w->Reparent(m_splitter);
            //m_splitter->ReplaceWindow(nb, w);
            nb->Destroy();

            // WORKAROUND to replace not properly working ReplaceWindow function
            int pos = m_splitter->GetSashPosition();
            wxSplitMode mode = m_splitter->GetSplitMode();
            m_splitter->Unsplit(w);
            if (mode == wxSPLIT_HORIZONTAL)
                m_splitter->SplitHorizontally(m_left, w);
            else
                m_splitter->SplitVertically(m_left, w);
            m_splitter->SetSashPosition(pos);
            // END OF WORKAROUND
        }
        else
        {
            nb = new wxNotebook(m_splitter, wxID_ANY, wxPoint(0, 0), wxSize(300, 300), wxNB_TOP);
            w->Reparent(nb);
            m_splitter->ReplaceWindow(w, nb);
            nb->AddPage(w, "Panel", true);    
        }
    }

**Comment by skeetor** [comment]
Is there something wrong with this bug report or why is there no response whatsoever?

**Comment by oneeyeman1** [comment]
@skeetor ,
Nothing is wrong. Just wait - the reply will come in a timely manner.

wxWidgets project unfortunately is understaffed and people are busy with work, life, etc.

Thank you.

**Comment by vadz** [comment]
I think your problem is simply due to not showing the page removed from the notebook (it's hidden after being removed from the notebook). If I add the missing `Show()`, everything seems to be working as expected:

```diff
diff --git a/samples/splitter/splitter.cpp b/samples/splitter/splitter.cpp
index 0a48610d52..e0a1be7450 100644
--- a/samples/splitter/splitter.cpp
+++ b/samples/splitter/splitter.cpp
@@ -34,6 +34,7 @@
 
 #include "wx/splitter.h"
 #include "wx/dcmirror.h"
+#include "wx/notebook.h"
 
 #ifndef wxHAS_IMAGES_IN_RESOURCES
     #include "../sample.xpm"
@@ -484,6 +485,27 @@ void MyFrame::OnSetGravity(wxCommandEvent& WXUNUSED(event) )
 
 void MyFrame::OnReplace(wxCommandEvent& WXUNUSED(event) )
 {
+    wxWindow *w = m_splitter->GetWindow2();
+
+    wxNotebook *nb = wxDynamicCast(w, wxNotebook);
+    if (nb)
+    {
+        w = nb->GetPage(0);
+        nb->RemovePage(0);
+        w->Reparent(m_splitter);
+        m_splitter->ReplaceWindow(nb, w);
+        nb->Destroy();
+        w->Show();
+    }
+    else
+    {
+        nb = new wxNotebook(m_splitter, wxID_ANY, wxPoint(0, 0), wxSize(300, 300), wxNB_TOP);
+        m_splitter->ReplaceWindow(w, nb);
+        w->Reparent(nb);
+        nb->AddPage(w, "Panel", true);
+    }
+    return;
+
     if ( !m_replacewindow )
     {
         m_replacewindow = m_splitter->GetWindow2();
```

So I don't think there is any bug here.
