### ISSUE TITLE
Two more wxTextCtrl crash when close on MinGW

### ISSUE THREAD

**Issue by ThIsJaCk23657689** [wxWidgets/wxWidgets#22735]
**Describe the bug**
I'm using MinGW(TDM-GCC) for developing wxwidget application. I realize that I put two or more `wxTextCtrl` in my `wxFrame`, It will crash when my main frame is closed. There is no problem when I just use only one `wxTextCtrl`. I tested that two `wxStaticText` or two `wxButton` is fine, but two `wxTextCtrl` will cause crash.

And other thing is if I change my develop environment to MSVC, two `wxTextCtrl` is OK, it won't cause any problem.

**Expected vs observed behaviour**
[Expected]
When I put two `wxTextCtrl`  in a `wxFrame`, It should close the application normally and return a 0 value.

[Observed]
It will crash when I closed the application, return value -1073740940 (0xC0000374). GDB report that is a SIGTRAP in `textctrl.h`.

**To Reproduce**
I packed the whole code file into a zip file, the code that cause the problem is inside it.
[wxWidget  - Two wxTextCtrl Bug.zip](https://github.com/wxWidgets/wxWidgets/files/9402247/wxWidget.-.Two.wxTextCtrl.Bug.zip)

**Platform and version information**
[MinGW]
 - wxWidgets version: 3.2.0 (from vcpkg x64-mingw-dynamic)
 - wxWidgets port: wxMSW
 - OS: Windows 10.0.19044
 - TDM-GCC version: 10.3
 - gcc version: 10.3.0
 - mingw64 version: v8.0

[MSVC]
 - wxWidgets version: 3.2.0 (from vcpkg x64-windows)
 - wxWidgets port: wxMSW
 - OS: Windows 10.0.19044
 - MSVC version: 1929

**Comment by ThIsJaCk23657689** [comment]
Thanks for your detailed reply. As you mention that the issue and PR #22641 do fix the problem. The reason I'm still having this issue is that vcpkg hasn't updated their package yet. I will report at the vcpkg repo.

**Comment by FrankXie05** [comment]
Hi @vadz, I am the maintainer of vcpkg, and the issue was resolved and merged. I would like to ask if a new version will be released in the near future? :)

**Comment by vadz** [comment]
I'm closing this one as it's an exact dup of #22639.

@FrankXie05 We plan to release 3.2.1 soon, although I'm not sure if we can make it on 2022-09-09 as originally planned. Please contact me privately (vadim at wxwidgets dot org) if you'd like to be notified about the future releases a bit in advance, I'd appreciate any testing of the packages _before_ the releases are done.
