### ISSUE TITLE
Is it possible to open wxHtmlParser to open https page

### ISSUE THREAD

**Issue by alex290** [wxWidgets/wxWidgets#22736]
Is it possible to open wxHtmlParser to open an https page for example https://www.google.com/search ?q=wxURL .
I looked at the forums and didn't find a single working example anywhere.  

Maybe there are other ways to parse, preferably without a GUI. 
At least one example . Help please

**Comment by beENABLED** [comment]
Do you want to display the page, or download the html and process it yourself?

In the former case, use wxWebView.
In the latter case wxWebRequest

**Comment by alex290** [comment]
> Do you want to display the page, or download the html and process it yourself?
> 
> In the former case, use wxWebView. In the latter case wxWebRequest

I get Html in webview and how can I pass this code to wxHtmlParser?
I couldn't do it in any way

**Comment by vadz** [comment]
You can use [wxHtmlWindow::SetPage()](https://docs.wxwidgets.org/stable/classwx_html_window.html#ac6d0335b1bb749b498598fc5a3b32703) to display HTML retrieved in any way.

Please don't open issues for things that are not actually issues in wxWidgets at all, this is a bug tracker and not a general support channel.
