### ISSUE TITLE
wxWebView GetPageText() I get empty.  I get Linux normally

### ISSUE THREAD

**Issue by alex290** [wxWidgets/wxWidgets#22743]
Hello. Here is the code

### main.cpp

    #include "webframe.h"
    
    class MyApp : public wxApp
    {
    public:
        virtual bool OnInit();
    };
    
    wxIMPLEMENT_APP(MyApp);
    
    bool MyApp::OnInit()
    {
        WebFrame *frame = new WebFrame("http://jsonplaceholder.typicode.com/posts");
        frame->Show(true);
        return true;
    }

### webframe.h

    #ifndef WEBFRAME_H
    #define WEBFRAME_H
    
    #include <wx/wxprec.h>
    #ifndef WX_PRECOMP
    #include <wx/wx.h>
    #endif
    #include <wx/webview.h>
    #if !wxUSE_WEBVIEW_WEBKIT && !wxUSE_WEBVIEW_WEBKIT2 && !wxUSE_WEBVIEW_IE && !wxUSE_WEBVIEW_EDGE
    #error "A wxWebView backend is required by this sample"
    #endif
    #if wxUSE_WEBVIEW_EDGE
    #include "wx/msw/webview_edge.h"
    #endif
    #include <wx/filename.h>
    #include <wx/stdpaths.h>
    #include <iostream>
    #include <string>
    #include <wx/textfile.h>
    
    
    class WebFrame : public wxFrame
    {
    public:
        WebFrame(wxString url);
        ~WebFrame();
    
    private:
        wxString m_url;
        wxWebView *m_browser;
    
        void addGui();
        void onLoad(wxWebViewEvent &event);
    };
    
    #endif

### webframe.cpp

    #include "webframe.h"
    
    WebFrame::WebFrame(wxString url)
        : wxFrame(NULL, wxID_ANY, "P2P Okx", wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE |  wxTAB_TRAVERSAL),
          m_url(url)
    {
        wxSize size(1920, 1080);
        SetSize(size);
    
    #if wxUSE_WEBVIEW_EDGE
        // Check if a fixed version of edge is present in
        // $executable_path/edge_fixed and use it
        wxFileName edgeFixedDir(wxStandardPaths::Get().GetExecutablePath());
        edgeFixedDir.SetFullName("");
        edgeFixedDir.AppendDir("edge_fixed");
        if (edgeFixedDir.DirExists())
        {
            wxWebViewEdge::MSWSetBrowserExecutableDir(edgeFixedDir.GetFullPath());
            wxLogMessage("Using fixed edge version");
        }
    #endif
        // Create the webview
        m_browser = wxWebView::New();
    
        m_browser->Create(this, wxID_ANY, url, wxDefaultPosition, wxDefaultSize);
        m_browser->Bind(wxEVT_WEBVIEW_LOADED, &WebFrame::onLoad, this);
        addGui();
    }
    
    WebFrame::~WebFrame()
    {
        Destroy();
    }
    void WebFrame::addGui()
    {
        wxBoxSizer *size;
        size = new wxBoxSizer(wxVERTICAL);
    
        size->Add(m_browser, 1, wxALL | wxEXPAND, 5);
    
        this->SetSizer(size);
        this->Layout();
    
        this->Centre(wxBOTH);
    }
    
    
    void WebFrame::onLoad(wxWebViewEvent &event)
    {
        // Trying to get data from the page
        std::cout << m_browser->GetPageText() << std::endl;
    
    }

wxWidgets built with wxUSE_WEBVIEW_EDGE 

Everything opens and calls perfectly . But at the same time, when receiving the text from the page, it is empty.. And in linux it shows full data.

**Comment by PBfordev** [comment]
Why is all that code you posted needed (some if it makes no sense, such as creating a sizer when there is a single control)? Does it mean the issue is not reproducible in the webview sample? If it works in the webview sample, you need to assess what is different between the sample and your code.

BTW, at least on Windows, cout is poorly suited for a use in a GUI application, let alone for outputting UTF-16 encoded text.

**Comment by sodevel** [comment]
A Windows GUI application does not have a console attached so your `std::cout` outputs into the void.

**Comment by oneeyeman1** [comment]
@alex290 ,
Can you make a MINIMAL example, reproducing the problem?
Can it be seen in the webview sample?

Thank you.

**Comment by alex290** [comment]
> @alex290 , Can you make a MINIMAL example, reproducing the problem? Can it be seen in the webview sample?
> 
> Thank you.

https://github.com/alex290/wxWebView

Made minimal. The same thing happens with wxWebView by the way::GetPageSource() 

Everything is fine in linux. And in Windows, some kind of suspension. Moreover, the application does not hang at the same time.

MinGW 64 Compiler

**Comment by oneeyeman1** [comment]
@alex290 ,

What do I need to do in order to see a problem in the sample?
Also, I presume the sample is unmodified?

Thank you.

**Comment by PBfordev** [comment]
@alex290: For the third time: Can you reproduce it in the unmodified bundled webview sample? Do not use console output to inspect a `wxString`: use the debugger, `wxLogDebug()` etc.

Run the sample, paste your URL into the address line, press Enter and once the page is done loading click the toolbar menu button and select View source from the menu.

But I am experiencing an issue (unhandled exception crash after closing test app; code below) when querying the page source from the on loaded event handler. Will investigate further.
<details>
  <summary>Code</summary>
```cpp
#include <wx/wx.h>
#include <wx/webview.h>

class MyFrame: public wxFrame
{
public:
    MyFrame() : wxFrame(nullptr, wxID_ANY, "Test")
    {
        m_webView = wxWebView::New(this, wxID_ANY, "https://www.wxwidgets.org/",  wxDefaultPosition, wxDefaultSize, wxWebViewBackendEdge);
        m_webView->Bind(wxEVT_WEBVIEW_LOADED, &MyFrame::OnWebViewLoaded, this);
    }
private:
    wxWebView* m_webView;

    void OnWebViewLoaded(wxWebViewEvent&)
    {
        const wxString pageSource = m_webView->GetPageSource();
    }
};

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        (new MyFrame())->Show();
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```
</details>

**Comment by alex290** [comment]
I'm new to wxwidgets, and I'm just learning C++. I don't quite understand what you need from me.. To show the problem

**Comment by oneeyeman1** [comment]
@alex290 ,

What exactly do I need to do in order to see a problem in the webview sample? Just give a step-by-step instruction.

And you didn't modify the sample, correct?

Thank you.

**Comment by PBfordev** [comment]
@alex290: You have been told exactly what to do, i.e.., test with the bundled webview sample, THREE times. Reproducing the issue with a bundled sample is a crucial step when dealing with a possible bug.

FWIW, you can also check #22744 it it is not the same issue and if so, if the workaround shown there with [CallAfter()](https://docs.wxwidgets.org/latest/classwx_evt_handler.html#a63c7351618fd77330d80a250b3719519) helps.

**Comment by alex290** [comment]
> @alex290: You have been told exactly what to do, i.e.., test with the bundled webview sample, THREE times. Reproducing the issue with a bundled sample is a crucial step when dealing with a possible bug.
> 
> FWIW, you can also check #22744 it it is not the same issue and if so, if the workaround shown there with [CallAfter()](https://docs.wxwidgets.org/latest/classwx_evt_handler.html#a63c7351618fd77330d80a250b3719519) helps.

That's how it works perfectly

    void WebFrame::onLoad(wxWebViewEvent &event)
    {
        CallAfter([this] () {
            const wxString pageText = m_browser->GetPageText();
            wxPuts(pageText);}
        );
        
    }
    
	
![](https://i.imgur.com/fC4LLiF.png)

**Comment by alex290** [comment]
Thank you SO MUCH for your help.

**Comment by alex290** [comment]
>

**Comment by PBfordev** [comment]
BTW, the code in your WebFrame dtor seems odd:

One should not call `delete` on `wxWindow`s but use `Destroy()` instead. But even the latter is usually not needed as the child windows get destroyed when their parent is. You can read more about window destruction at https://docs.wxwidgets.org/latest/overview_windowdeletion.html

I think whole dtor can be safely removed.
