### ISSUE TITLE
Accessing HTML from wxWebViewEdge event handlers causes crash

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22744]
When using wxWebView Edge backend, calling its methods such as `GetPageText()` or `GetPageSource()` from an event handler for an event such as `wxEVT_WEBVIEW_LOADED`, the webview becomes unstable, and the application crashes with unhandled exception when attempting to use the webview or just closing the application immediately.

Just placing `const wxString pageText = m_browser->GetPageText();` in the event handler is enough. Call stack after the crash:

```
'webviewsample.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. 
'webviewsample.exe' (Win32): Unloaded 'C:\Windows\System32\dbghelp.dll'
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: std::length_error at memory location 0x000000A3456FD150.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: std::length_error at memory location 0x000000A3456FF090.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: std::length_error at memory location 0x000000A3456FF090.
Exception thrown at 0x00007FFDD49D4FD9 in webviewsample.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
'webviewsample.exe' (Win32): Unloaded 'D:\Dev\Desktop\!Lib\wxWidgets-PB-build-vc17_x64_DLL\lib\vc_x64_dll\WebView2Loader.dll'
```
I tested that the crash occurs for handlers for `wxEVT_WEBVIEW_LOADED`, `wxEVT_WEBVIEW_NAVIGATED`, and `wxEVT_WEBVIEW_TITLE_CHANGED`.  There is no crash and the string seems correct when I use `CallAfter()`, e.g., in the event handler replace
```cpp
const wxString pageText = m_browser->GetPageText();
```
with
```cpp
CallAfter([this] { const wxString pageText = m_browser->GetPageText(); wxLogMessage("Page source %s", pageText);} );
```

**To Reproduce**
1. Patch the webview sample with
```diff
diff --git a/samples/webview/webview.cpp b/samples/webview/webview.cpp
index b0a71da6a0..8818da6742 100644
--- a/samples/webview/webview.cpp
+++ b/samples/webview/webview.cpp
@@ -865,6 +865,8 @@ void WebFrame::OnNavigationComplete(wxWebViewEvent& evt)
   */
 void WebFrame::OnDocumentLoaded(wxWebViewEvent& evt)
 {
+    const wxString pageText = m_browser->GetPageText();
+
     //Only notify if the document is the main frame, not a subframe
     if(evt.GetURL() == m_browser->GetCurrentURL())
     {
```
2. Build the sample, ensuring it uses `wxWebViewEdge` backend.
3. Run the sample and wait until the page is displayed.
4. Close the sample.
5. Observe the unhandled exception error box.

**Platform and version information**
 - wxWidgets version you use: master, built as 64-bit DLL with MSVS 2022 with CMake
 - wxWidgets port you use: wxMSW
 - OS and its version: Windows 10.0.19044.1889
 - WebView2Loader.dll version: 1.0.705.50
 - Edge version: 104.0.1293.63

**EDIT**
Calling `GetPage*()` results in calling `RunScript()` which waits for `RunScriptAsync()` while `wxYield()`ing. 
https://github.com/wxWidgets/wxWidgets/blob/6ee593c78d082156c4fba2997241e530ba1d24da/src/common/webview.cpp#L232-L236

However, something goes wrong when doing this in a `wxWebviewEdge` event handler and the script execution seems to never end properly, with the application forever stuck in that `while` loop.

**Comment by vadz** [comment]
Thanks for reporting this, but unfortunately this risks being non-trivial to fix, so we might want to just document this as a limitation for now.

Of course, perhaps there _is_ some way to make this work (block all the other events while yielding from an event handler, perhaps?), but I am not going to be able to look into this so I can only hope that @TcT2k might.

**Comment by TcT2k** [comment]
> Thanks for reporting this, but unfortunately this risks being non-trivial to fix, so we might want to just document this as a limitation for now.
> 
> Of course, perhaps there _is_ some way to make this work (block all the other events while yielding from an event handler, perhaps?), but I am not going to be able to look into this so I can only hope that @TcT2k might.

Unfortunately I don't think there is much that can be done about this. `RunScript()` can not be used while the event is processed. It maybe possible that the callback of edge implemented here https://github.com/wxWidgets/wxWidgets/blob/974a7658da8da235b205618924db0df345ab5189/src/msw/webview_edge.cpp#L189

could process later (thinking about `CallAfter()`) and the the `args` object would still be valid. If possible this should be a way to prevent this kind of issues.

**Comment by vadz** [comment]
I think that even simply detecting this situation and complaining about it (with an assert failure?) would be better than silently misbehaving in weird ways. I.e. just set a flag before generating an event and check for it in `RunScript()` perhaps?

**Comment by TcT2k** [comment]
> I think that even simply detecting this situation and complaining about it (with an assert failure?) would be better than silently misbehaving in weird ways. I.e. just set a flag before generating an event and check for it in `RunScript()` perhaps?

I've had a further look into this and the only event currently requiring direct processing is `wxEVT_WEBVIEW_NAVIGATING` (because it can be vetoed). Maybe for other events simply using `AddPendingEvent()` (or `QueueEvent()`) would be a good solution to allow `RunScript()` calls from these callbacks. I'm just not sure if there would be unforeseen consequences?

**Comment by PBfordev** [comment]
Fixed by https://github.com/wxWidgets/wxWidgets/commit/0ace9894c787f7ace607bfe2f4c2ae0f9f5708d2,
