### ISSUE TITLE
Crash in radio box_osx when initialized with null list of strings

### ISSUE THREAD

**Issue by rmpowell77** [wxWidgets/wxWidgets#22751]
**Describe the bug**
When a `wxRadioBox` is created with no `choices`, it will crash when destroyed.

**Expected vs observed behaviour**
I would not expect a segfault on destruction

**Patch or snippet allowing to reproduce the problem**
This program crashes with a segfault on Mac:

```
#include <iostream>
#include <wx/wx.h>

int main() {
    wxFrame frame { nullptr, wxID_ANY, "" };
    auto window = new wxRadioBox(&frame, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0, nullptr, 1, wxRA_SPECIFY_COLS);
    // a crash occurs on frame dtor.
}
```

**To Reproduce**
use the attached sample program (cmake/code) on Mac
[crash.zip](https://github.com/wxWidgets/wxWidgets/files/9440475/crash.zip)

**Platform and version information**
 - wxWidgets version you use: 3.2
 - wxWidgets port you use: wxOSX
 - OS and its version: macOS 12.4

**Comment by rmpowell77** [comment]
possible fix PR here: #22752

**Comment by vadz** [comment]
I agree that we shouldn't crash but I'm not really sure if we should allow creating radio boxes without items -- can this ever be useful? Does it work correctly under the other platforms?

If we do want to allow it, #22752 is probably not sufficient as it's still going to crash at least in `SetFocus()`.

**Comment by rmpowell77** [comment]
Well, we do have this pointy edge in the default constructor:


[wxRadioBox](https://docs.wxwidgets.org/3.0/classwx_radio_box.html#a383386e9dfdb6b73b5356cffec2c253b) ([wxWindow](https://docs.wxwidgets.org/3.0/classwx_window.html) *parent, [wxWindowID](https://docs.wxwidgets.org/3.0/windowid_8h.html#ae8091432cc2cb2485d45f2302fb51133) id, const [wxString](https://docs.wxwidgets.org/3.0/classwx_string.html) &label, const [wxPoint](https://docs.wxwidgets.org/3.0/classwx_point.html) &pos=[wxDefaultPosition](https://docs.wxwidgets.org/3.0/gdicmn_8h.html#af5a90c753eaf3d3e3e5068a19ec3c1d0), const [wxSize](https://docs.wxwidgets.org/3.0/classwx_size.html) &size=[wxDefaultSize](https://docs.wxwidgets.org/3.0/gdicmn_8h.html#a33a012cdb075e9f78c93f63bec2dc27b), int n=0, const [wxString](https://docs.wxwidgets.org/3.0/classwx_string.html) choices[]=NULL, int majorDimension=0, long style=[wxRA_SPECIFY_COLS](https://docs.wxwidgets.org/3.0/defs_8h.html#a5a8469ecd014c152136d774fd5c5b82c), const [wxValidator](https://docs.wxwidgets.org/3.0/classwx_validator.html) &validator=[wxDefaultValidator](https://docs.wxwidgets.org/3.0/validate_8h.html#af1e90d8aa1824fd2ce4024ef7e40703c), const [wxString](https://docs.wxwidgets.org/3.0/classwx_string.html) &name=wxRadioBoxNameStr)


if it shouldn't have an empty set of choices, should it be enforced at creation?

**Comment by vadz** [comment]
> if it shouldn't have an empty set of choices, should it be enforced at creation?

Well, yes, this is the question -- should we assert in `Create()` that `choices` must be non-empty and return false from it refusing to create the window?

After thinking more about it, I guess that probably not, because somebody, somewhere, surely must be creating radio boxes with dynamically-determined set of buttons that can be empty under some circumstances and there is no really compelling reason to break their code. So we do need to handle this case gracefully, including in `SetFocus()`. And having a unit test checking that it doesn't crash would be nice, too.

**Comment by vadz** [comment]
I've tested it under radio boxes without items do work fine under GTK and MSW, so it makes sense to handle them under Mac too and I've created #22755 with my preferred solution now.

This should also be applied to 3.2.

**Comment by rmpowell77** [comment]
Nice fix!

**Comment by vadz** [comment]
Thanks for testing!
