### ISSUE TITLE
HAVE_LARGEFILE_SUPPORT not checked/set when build with cmake

### ISSUE THREAD

**Issue by sl1pkn07** [wxWidgets/wxWidgets#22750]
**Describe the bug**
HAVE_LARGEFILE_SUPPORT is not checked if build wxwidgets with cmake

**Expected vs observed behaviour**
parity between build the wxwidgets iself with cmake and configure

when build wxwidgets (3.2.0 from github tag) with cmake. `HAVE_LARGEFILE_SUPPORT` is not cheked or setted when build

but when if is builded with `./configure`, `HAVE_LARGEFILE_SUPPORT` is checked and set acordigly with the resoults

**Patch or snippet allowing to reproduce the problem**
simply build with cmake and with configure, and see the differences in the `setup.h` file

with ./configure
~~~
lib/wx/include/gtk3-unicode-3.2/wx/setup.h:#define HAVE_LARGEFILE_SUPPORT 1
~~~

with cmake
~~~
lib/wx/include/gtk3-unicode-3.2/wx/setup.h:/* #undef HAVE_LARGEFILE_SUPPORT */
~~~

**To Reproduce**
Steps to reproduce the behaviour, please make them as detailed as possible, e.g.
1. git clone https://github.com/wxWidgets/wxWidgets.git --branch 3.2.0'
2. mkdir -p build-cmake build-configure
3. cd build-cmake && cmake ../wxWidgets
4. cd ../build-configure && ../wxWidgets/configure
5. see the `HAVE_LARGEFILE_SUPPORT` result of genetrated `setup.h` file

**Platform and version information**
 - wxWidgets version you use: 3.2.0
 - wxWidgets port you use: wxBase, wxGTK, wxQt5
 - OS and its version: Archlinux

**Comment by vadz** [comment]
Thanks, this is indeed a problem with the CMake build, it ought to define `HAVE_LARGEFILE_SUPPORT`.

In fact, I wonder if we could just do it unconditionally. Or, IOW, if we could get rid of `HAVE_LARGEFILE_SUPPORT` check and just always assume it is available -- are there any platforms where this wouldn't be the case in 2022?

Of course, it would still be safer to keep this in 3.2, but for 3.3 I think we can take the risk of just removing these checks...

**Comment by sl1pkn07** [comment]
i found this problem when try build amule. so so seems is still use

~~~
checking that wxWidgets has support for large files... no
configure: error: 
        Support for large files in wxWidgets is required by aMule.
        To continue you must recompile wxWidgets with support for
        large files enabled.
~~~

~~~
configure:10695: checking that wxWidgets has support for large files
configure:10709: g++ -E  -I/usr/lib/wx/include/base-unicode-3.2 -I/usr/include/wx-3.2 -DWXUSINGDLL -D__WXBASE__ conftest.cpp
conftest.cpp:30:34: error: #error No LargeFile support!
   30 |                                 #error No LargeFile support!
      |                                  ^~~~~
configure:10709: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "aMule"
| #define PACKAGE_TARNAME "amule"
| #define PACKAGE_VERSION "SVN"
| #define PACKAGE_STRING "aMule SVN"
| #define PACKAGE_BUGREPORT "admin@amule.org"
| #define PACKAGE_URL ""
| #define PACKAGE "amule"
| #define VERSION "SVN"
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE__BOOL 1
| #define HAVE_STDBOOL_H 1
| #define CRYPTOPP_INCLUDE_PREFIX cryptopp
| #define GCC_USES_STRICT_ALIASING 1
| /* end confdefs.h.  */
| 
| 
| 			#include <wx/wx.h>
| 			#include <wx/filefn.h>
| 			#ifndef wxHAS_LARGE_FILES
| 				#error No LargeFile support!
| 			#endif
| 
| 
configure:10717: result: no
configure:10719: error: 
	Support for large files in wxWidgets is required by aMule.
	To continue you must recompile wxWidgets with support for
	large files enabled.
~~~

**Comment by vadz** [comment]
Oh, sorry for not being clear: what I meant was to _always_ predefine `wxHAS_LARGE_FILES` and use large-file aware functions internally, without checking that they're available because AFAIK they always are currently.

**Comment by sl1pkn07** [comment]
for me OK

**Comment by sl1pkn07** [comment]
Hi

any notice? 3.2.2.1 and not fix the issue

greetings

**Comment by MaartenBent** [comment]
I'll have a look at adding this.

I'm not really familiar with these large file defines on Linux, but I suppose it will be like this:

* Add an equivalent to configure's `--disable-largefile` so users can force disable it
* Define `HAVE_LARGEFILE_SUPPORT` in `setup.h` created by CMake when enabled
* Add  `-D_FILE_OFFSET_BITS=64` compile definition when enabled
* Add  `-D_FILE_OFFSET_BITS=64` to wxconfig cppflags
* Define it when running all the checks in `setup.cmake` (with `set(CMAKE_REQUIRED_DEFINITIONS -D_FILE_OFFSET_BITS=64)`) and add a check for `HAVE_FSEEKO`.

If people for some reason need `-D_LARGEFILE_SOURCE=1` or `-D_LARGEFILE64_SOURCE=1`, they can add them via `CMAKE_CXX_FLAGS`.

**Comment by MaartenBent** [comment]
I created #23336 that does the things I listed above.
