### ISSUE TITLE
Trouble with alpha channel in Windows

### ISSUE THREAD

**Issue by extreamsad** [wxWidgets/wxWidgets#22778]
I trying to execute this simple code in Windows and all works correctly except alpha cannel. When i change the variable 'alpha', the transparency doesn't change. Maybe this is a BUG, because I did not find an answer anywhere why this happens.
`
// ....
wxClientDC dc;
unsigned char alpha = 50;
wxColour cc = wxColour(255, 0, 0, alpha);
wxPen pen(cc, 1);
wxBrush brush(cc);
dc.SetPen(pen);
dc.SetBrush(brush);
dc.DrawRectangle(wxRect(10, 10, 10, 10));
// ...
`
PS: Linux doesn't have this problem.

**Comment by PBfordev** [comment]
wxWidgets issues do not serve as the help line, please do not use it as such.

As clearly stated in the docs, `wxDC` on Windows does not support transparency: You need to use another class to draw (see [wxGraphicsContext](https://docs.wxwidgets.org/trunk/classwx_graphics_context.html) or [wxGCDC](https://docs.wxwidgets.org/trunk/classwx_g_c_d_c.html). 

BTW, using `wxClientDC` is usually a bad idea, all drawing should happen in the `wxEVT_PAINT` handler using `wxPaintDC` or its buffered variants.
