### ISSUE TITLE
wxDummyConsoleApp::OnRun() unreachable code when running wxWidgets Example

### ISSUE THREAD

**Issue by MacQuant** [wxWidgets/wxWidgets#22772]
I am looking at this example [EXAMPLE](https://docs.wxwidgets.org/3.0/overview_helloworld.html). I copy past after linking the dlls and all. I get this error after running it:

```wxDummyConsoleApp::OnRun() unreachable code``` thrown in ```wxWidgets/common/init.cpp```.
![wxError](https://user-images.githubusercontent.com/68292580/188289600-ea741ba8-4528-43ad-926f-4fcc81532cf5.PNG)

Could you please help me? I am just starting and want to move on to some other stuff please?

I am using: Visual Studio 2022 (v143)
Thank you!

**Comment by vadz** [comment]
You probably didn't paste copy-pasted correctly and must have omitted the `wxIMPLEMENT_APP(MyApp);` line.

BTW, did you know that you could press `Ctrl-C` to copy the text of the message box and paste it here instead of pasting the images?

**Comment by MacQuant** [comment]
Thanks so much for answering. Sorry I couldn't copy the text from the image, below is the code (I did call ```wxIMPLEMENT_APP(MyApp);``` ) as in the  blow:
```
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif
class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};
class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size);
private:
    void OnHello(wxCommandEvent& event);
    void OnExit(wxCommandEvent& event);
    void OnAbout(wxCommandEvent& event);
    wxDECLARE_EVENT_TABLE();
};
enum
{
    ID_Hello = 1
};
wxBEGIN_EVENT_TABLE(MyFrame, wxFrame)
EVT_MENU(ID_Hello, MyFrame::OnHello)
EVT_MENU(wxID_EXIT, MyFrame::OnExit)
EVT_MENU(wxID_ABOUT, MyFrame::OnAbout)
wxEND_EVENT_TABLE()
wxIMPLEMENT_APP(MyApp);
bool MyApp::OnInit()
{
    MyFrame* frame = new MyFrame("Hello World", wxPoint(50, 50), wxSize(450, 340));
    frame->Show(true);
    return true;
}
MyFrame::MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size)
    : wxFrame(NULL, wxID_ANY, title, pos, size)
{
    wxMenu* menuFile = new wxMenu;
    menuFile->Append(ID_Hello, "&Hello...\tCtrl-H",
        "Help string shown in status bar for this menu item");
    menuFile->AppendSeparator();
    menuFile->Append(wxID_EXIT);
    wxMenu* menuHelp = new wxMenu;
    menuHelp->Append(wxID_ABOUT);
    wxMenuBar* menuBar = new wxMenuBar;
    menuBar->Append(menuFile, "&File");
    menuBar->Append(menuHelp, "&Help");
    SetMenuBar(menuBar);
    CreateStatusBar();
    SetStatusText("Welcome to wxWidgets!");
}
void MyFrame::OnExit(wxCommandEvent& event)
{
    Close(true);
}
void MyFrame::OnAbout(wxCommandEvent& event)
{
    wxMessageBox("This is a wxWidgets' Hello world sample",
        "About Hello World", wxOK | wxICON_INFORMATION);
}
void MyFrame::OnHello(wxCommandEvent& event)
{
    wxLogMessage("Hello world from wxWidgets!");
}
```

**Comment by MacQuant** [comment]
@vadz could you please help? I did actually use ```wxIMPLEMENT_APP(MyApp);``` as in the above, this proble was actually faced by others before me: [here](https://forums.wxwidgets.org/viewtopic.php?t=6950).

**Comment by vadz** [comment]
This should indeed work, so the problem is not with the example itself but rather with the way you build it. What you observe could happen if you somehow link with 2 copies of wxWidgets -- one of which remains uninitialized.

**Comment by MacQuant** [comment]
Thanks so much man!!!! 
I solved it :) :) The problem was because I was doing this in my premake file:
```
	links
	{
		"wxbase33ud.lib",
		"wxregexud.lib",
		"comdlg32.lib",
		"advapi32.lib",
		"msvcprtd.lib",
		"oleaut32.lib",
		"wxexpatd.lib",
		"wxzlibd.lib",
		"wxtiffd.lib", 
		"shell32.lib",
		"wxjpegd.lib", 
		"LIBCMT.lib",
		"rpcrt4.lib",
		"user32.lib",
		"wxpngd.lib",
		"gdi32.lib",
		"ole32.lib",
		"wxpng.lib",	
	}
```

I deleted this and it works!! If you have time could you please explain what I was doing here. Otherwise Thanks so much!!!!!
