### ISSUE TITLE
Remove section wxWidgets 2.8 Compatibility Functions from wxVScrolledWindow docs

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22783]
The methods listed in _wxWidgets 2.8 Compatibility Functions_ section of [the `wxVScrolledWindow` docs](https://docs.wxwidgets.org/latest/classwx_v_scrolled_window.html) are not available in 3.3 anymore and thus the whole section should be removed.

I am not familiar with those classes so I am not sure if just removing the section is enough, so I'd rather not submit a PR.

EDIT: The original message incorrectly stated the functions are not available in 3.2, that was a typo which was corrected to 3.3.

**Comment by tierra** [comment]
I wonder what other 2.8-compat methods/classes are still lingering in the docs after #22692, since it doesn't seem to touch hardly any `interface/wx/*` files (other than `thread.h`).

In any case, I believe it is just that paragraph section in the `wxVScrolledWindow` docs that needs removed.

**Comment by PBfordev** [comment]
I actually did a search for "2.8" in the docs folders and did not find anything else that should be removed.
