### ISSUE TITLE
HitTest behaviour, wxListBox vs. wxVListBox, new for 3.2

### ISSUE THREAD

**Issue by mrxeng** [wxWidgets/wxWidgets#22782]
Sometime after 3.0.5 the behaviour of wxVListBox::HitTest() changed.  it used to behave like wxListBox::HitTest(), i.e., returned the item located at point, or wxNOT_FOUND if there is no item located at point.

Now it returns a wxHitTest enum from wxWindowBase.  It happily compiles, producing incorrect code.  

In particular, instead of returning wxNOT_FOUND when inside a wxEVT_MOTION event, it can return wxHT_WINDOW_OUTSIDE which is disastrous.

**Comment by PBfordev** [comment]
I have never used the class but looking at the docs and the code it seems that `wxVScrolledWindow::HitTest()` was deprecated in 3.0 and is therefore unavailable in 3.2 unless you build wxWidgets with `WXWIN_COMPATIBILITY_2_8` set to 1. Did you?

When the deprecated method is unavailable, you end calling the `wxWindow` method instead. Did you try using the replacement function `VirtualHitTest()`?

**Comment by mrxeng** [comment]
Thank you thank you thank you!!

I missed that it was deprecated.
