### ISSUE TITLE
Mac wxDataViewCtrl::HitTest() doesn't take header into account

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22789]
This issue still happens on the macOS version of wxDataViewCtrl. Patch suggested by https://github.com/prusa3d/wxWidgets/commit/0d2625c2633ff909c3f0de60ac37e15402663d64 seems the correct fix. Hasn't been brought to the main line yet as far as I can tell

_Originally posted by @Tommykrul in https://github.com/wxWidgets/wxWidgets/issues/17561#issuecomment-1237456004_

**Comment by vadz** [comment]
The referenced commit indeed looks correct to me and probably should be cherry-picked to wx if there are no objections (cc @bubnikv)

**Comment by bubnikv** [comment]
@YuSanka is now the responsible person for wxWidgets UI part of our application. @YuSanka ?

Frankly I do not claim to be an macOS expert, this was a quick hack to fix one of our isses. How good a solution it is I don't know.

**Comment by vadz** [comment]
I've tested it and it works fine for me, so I've included it in #22839 which will be merged into both branches soon if there are no objections/problems with it.

Thanks again for the fix, but please don't hesitate to submit them for inclusion in wx, this will make life simpler for both you and us in the future.
