### ISSUE TITLE
MacOS tiff.h error

### ISSUE THREAD

**Issue by BushTrain460615** [wxWidgets/wxWidgets#22784]
<img width="569" alt="Screenshot 2022-09-08 at 10 39 43 PM" src="https://user-images.githubusercontent.com/72326501/189266977-280d0b12-4e14-46bd-ae93-8b023e926a82.png">

**Comment by BushTrain460615** [comment]
<img width="553" alt="Screenshot 2022-09-08 at 10 40 09 PM" src="https://user-images.githubusercontent.com/72326501/189267021-2be21dbd-35cc-4b34-905d-ce6709cc44eb.png">

**Comment by BushTrain460615** [comment]
this is what happens when I try to build on Mac

**Comment by vadz** [comment]
Isn't this due to the same problem as #22779, i.e. just due to missing `src/tiff` submodule? Please reopen if it isn't, i.e. if you do have the submodule and still get this error (also remember to rerun configure after checking out the submodule).

Also, sorry if it wasn't clear, but when I asked you not to submit logs as RTF, I really asked for plain text rather than images, which is even worse than RTF and not better. Please copy and paste the text in the future.

**Comment by BushTrain460615** [comment]
this one is different because I didn't use cmake this time I just did config

**Comment by vadz** [comment]
The cause of your other problem was not checking out the submodules, not using, or not using, CMake. If you don't have (all) the sources, neither build method is going to work for you.

**Comment by BushTrain460615** [comment]
I did this
git clone --recurse-submodules https://github.com/wxWidgets/wxWidgets.git

**Comment by BushTrain460615** [comment]
if you need the config I did this time 
../configure --with-opengl --disable-shared

**Comment by MaartenBent** [comment]
Does configure automatically use buit-in tiff if the system one isn't available?
Seeing you use homebrew you could try installing the system one with `brew install libtiff`.

**Comment by BushTrain460615** [comment]
> Does configure automatically use buit-in tiff if the system one isn't available?
> Seeing you use homebrew you could try installing the system one with `brew install libtiff`.

I can try that and see if that works

**Comment by BushTrain460615** [comment]
that didn't work

**Comment by BushTrain460615** [comment]
[The Errors i get after the homebrew thing.txt](https://github.com/wxWidgets/wxWidgets/files/9536390/The.Errors.i.get.after.the.homebrew.thing.txt)

**Comment by BushTrain460615** [comment]
[The New errors i get after fixing the first one.txt](https://github.com/wxWidgets/wxWidgets/files/9536456/The.New.errors.i.get.after.fixing.the.first.one.txt)

**Comment by vadz** [comment]
Did you rerun configure after getting the submodule? Please delete your build directory entirely, recreate it, rerun configure and then `make`.

You do _not_ need to install libtiff from homebrew (although you can use it if you want to).

**Comment by BushTrain460615** [comment]
ok I will do that now
