### ISSUE TITLE
How to detect relative path in wxWebview?

### ISSUE THREAD

**Issue by Rezakarimi66** [wxWidgets/wxWidgets#22780]
Please take a look at the following minimal code:
```

// ----------------------------------------------------------------------------
// headers
// ----------------------------------------------------------------------------

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWidgets headers)
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// ----------------------------------------------------------------------------
// resources
// ----------------------------------------------------------------------------
#if wxUSE_WEBVIEW_IE
    #include <wx/msw/webview_ie.h>
#endif
#include <wx/webview.h>
#include <wx/filesys.h>
#include <wx/mstream.h>

struct WxHtmlFSHandler : public wxWebViewHandler
{
    std::string html = "<!DOCTYPE html><html><head><meta http-equiv='content-type' content='text/html;"
        "charset=UTF-8'>\n<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
        "</head><body>"
        "<h1>This is a test</h1>"
        "<a href=\"logo?2\"><img width=\"50%\" src=\"../pic1.png\"></a>"
        "<a href=\"logo?4\"><img width=\"50%\" src=\"pic2.png\"></a></body></html>";
    WxHtmlFSHandler( const wxString& scheme ) : wxWebViewHandler( scheme ) {}

    wxFSFile* GetFile( const wxString& uri ) override
    {
        // handle uri here
        if( uri.Contains("test.html") )
            return new wxFSFile( new wxMemoryInputStream( html.data(), html.size() ), uri, wxT( "text/html" ), ""
              #if wxUSE_DATETIME
                , wxDateTime::Now()
              #endif
            );
    };
};

// Define a new application type, each program should derive a class from wxApp
class MyApp : public wxApp
{
public:
    // override base class virtuals
    // ----------------------------

    // this one is called on application startup and is a good place for the app
    // initialization (doing it here and not in the ctor allows to have an error
    // return: if OnInit() returns false, the application terminates)
    virtual bool OnInit() wxOVERRIDE;
};

// Define a new frame type: this is going to be our main frame
class MyFrame : public wxFrame, public wxBitmap
{
public:
    // ctor(s)
    MyFrame(const wxString& title);
    wxWebView* myWeb = nullptr;
};

// Create a new application object: this macro will allow wxWidgets to create
// the application object during program execution (it's better than using a
// static object for many reasons) and also implements the accessor function
// wxGetApp() which will return the reference of the right type (i.e. MyApp and
// not wxApp)
wxIMPLEMENT_APP(MyApp);

// ============================================================================
// implementation
// ============================================================================

// ----------------------------------------------------------------------------
// the application class
// ----------------------------------------------------------------------------

// 'Main program' equivalent: the program execution "starts" here
bool MyApp::OnInit()
{
    // call the base class initialization method, currently it only parses a
    // few common command-line options but it could be do more in the future
    if ( !wxApp::OnInit() )
        return false;

    // create the main application window
    MyFrame *frame = new MyFrame("Minimal wxWidgets App");
    
    // and show it (the frames, unlike simple controls, are not shown when
    // created initially)
    frame->Show(true);

    // success: wxApp::OnRun() will be called which will enter the main message
    // loop and the application will run. If we returned false here, the
    // application would exit immediately.
    return true;
}

// ----------------------------------------------------------------------------
// main frame
// ----------------------------------------------------------------------------

// frame constructor
MyFrame::MyFrame(const wxString& title)
       : wxFrame(NULL, wxID_ANY, title)
{
    myWeb = wxWebView::New( this, wxID_ANY, wxWebViewDefaultURLStr );
    myWeb->RegisterHandler( wxSharedPtr< wxWebViewHandler >( new WxHtmlFSHandler( "myScheme" ) ) );
    if( myWeb && !myWeb->IsBusy() )
        myWeb->LoadURL( "myScheme:test.html" );
}
```
If you set a breakpoint inside "GetFile" function, you can see that I receive "myScheme:pic1.png" instead of "myScheme:../pic1.png". I am wondering why this happens and how I can fix that. Of course I can fix my string but that's the worst case scenario. In addition, you can see that I used "LoadURL" instead of "SetPage". If I use the later, nothing loads!

wxWidget version 3.1.5 and Win 10 and Internet Explorer 11 Engine

**Comment by oneeyeman1** [comment]
@Rezakarimi66 ,
Does this also happens with 3.2.0 or even Git master?
Can you try the other backend (Edge or Chromium)?

**Comment by oneeyeman1** [comment]
@Rezakarimi66 ,
> Currently, I cannot test it on any other backend or with any version. It's on a production. If it's a bug of IE or library version then I need to upgrade.

You are on Windows which means you are not attached to any repository.
What stops you to test the sample code you posted here with the latest version of wx and/or with different back-end?

Thank you.

**Comment by PBfordev** [comment]
Firstly, as its name indicates, wx-dev discussion group is not the user support group, you must have confused it with[ wx-users](https://groups.google.com/g/wx-users).

Secondly, I have no real experience with this so I will not comment on the code but AFAIK, the other backend on Windows - Edge - does not support custom schemes or virtual file systems. I also do not see any relevant changes in the Explorer backend source since 3.1.5. So while oneeyeman1 is correct about nothing preventing you from trying the current wxWidgets version, it may not be of much help here but who knows...

**Comment by Rezakarimi66** [comment]
I tested it with 3.2 and no change. If Windows backend does not supportcustom scheme, so what's the use of wxWebHandler class?

**Comment by PBfordev** [comment]
> If Windows backend does not support custom scheme, so what's the use of wxWebHandler class?

The IE backend you are using does support custom schemes, you can see that in the webview sample.

Moreover, it is not surprising that some backends like Edge do not support some features when those features are not available in the wrapped API.

**Comment by Rezakarimi66** [comment]
Edge backend is based on Chromium so Chrome also does not support it? Right?

**Comment by oneeyeman1** [comment]
Hi,

On Thu, Sep 8, 2022, 12:42 AM Reza Karimi ***@***.***> wrote:

> Edge backend is based on Chromium so Chrome also does not support it?
> Right?
>

Edge is based in the MS Edge browser, not Chromium.
wxEdge is not supporting this feature..
Are you running in compatibility mode?

Thank you.

**Comment by PBfordev** [comment]
I have no idea what Chrome does or does not support but I cannot see how it is relevant here? What matters for the `wxWebViewEdge` backend is what Microsoft's `WebView2` control can or cannot do (and of course someone must implement the features in wxWidgets, as the control is still evolving).

FWIW, I took look at the code. It seems that the custom scheme does allow full paths (e.g., `a/x/pic2.png`) but when the path contains dots, only the file name is passed in `uri` in ` GetFile()`. I can use only Windows so I cannot test other backends to see if the issue is with `wxWebViewHandler` or the IE backend (be it the control limitation or a problem in wxWidgets wrapper).

**Comment by PBfordev** [comment]
As I said before, I have no experience with `wxWebViewHandler` nor `wxFileSystem`.

However, seeing what you wrote, it makes sense that your code did not work. If the html file was in the "scheme root folder" then a path for a file referring to a one folder above the folder with the html file, i.e., above the root cannot be valid. 

Perhaps you expected the paths to be passed in URI as they were and not resolved: I have no idea whether this expectation was realistic, once again I have no knowledge of these parts of wxWidgets.

**Comment by vadz** [comment]
I agree with @PBfordev and this behaviour seems logical to me: if your current (virtual) location is `/`, `../foo` is the same as `/foo` and the same as `foo`, so I don't think there is any real bug here.

Also, `SetPage()` is supposed to take the text of the page and it should work if you pass it the HTML directly. It's not going to work if you just pass it a link using the custom schema, of course.

**Comment by Rezakarimi66** [comment]
> I agree with @PBfordev and this behaviour seems logical to me: if your current (virtual) location is `/`, `../foo` is the same as `/foo` and the same as `foo`, so I don't think there is any real bug here.
> 
> Also, `SetPage()` is supposed to take the text of the page and it should work if you pass it the HTML directly. It's not going to work if you just pass it a link using the custom schema, of course.

Hi @vadz Thanks for your reply. I don't correctly get the idea of how `SetPage` works in this case. Could you please modify my code to work with SetPage?

**Comment by vadz** [comment]
Just doing
```cpp
myWeb->SetPage("<!DOCTYPE html><html><head><meta http-equiv='content-type' content='text/html;"
        "charset=UTF-8'>\n<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
        "</head><body>"
        "<h1>This is a test</h1>"
        "<a href=\"logo?2\"><img width=\"50%\" src=\"myScheme:../pic1.png\"></a>"
        "<a href=\"logo?4\"><img width=\"50%\" src=\"myScheme:pic2.png\"></a></body></html>", {});
```
should work.

**Comment by Rezakarimi66** [comment]
Edge backend is based on Chromium so Chrome also does not support it? Right?
________________________________
