### ISSUE TITLE
Some animated gifs not loadable with wxImage

### ISSUE THREAD

**Issue by dkulp** [wxWidgets/wxWidgets#22799]
**Describe the bug**
We've had several reports over the years of various animated GIF images not working with xLights.   In general we have the user load the gif into a different editor and resave and that usually "fixes" it and it works.   However, it would be great if wxWidgets could be fixed to support the gifs that currently don't load.

**Expected vs observed behaviour**
The image loads and works.  

Using the attached animated gif, a simple "wxImage::GetImageCount("turkey.gif);" returns 0.   image.LoadFile("turkey.gif", wxBITMAP_TYPE_ANY, 0) returns false indicating it couldn't load it.   

I haven't tried to dig into the gif parsing code to figure out what it's trying to do.   

**Patch or snippet allowing to reproduce the problem**

Problematic gif:
![turkey](https://user-images.githubusercontent.com/91569/190228903-47818762-75bf-4eb7-a376-217fece30099.gif)

**Comment by Carnildo** [comment]
The issue isn't unique to animated GIFs, but that's also where I encountered it.

The problem is that the wxWidgets GIF decoder violates the GIF specification.  From the cover sheet to the [GIF89a spec](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) calling out exactly this mistake:

> There has been confusion about where clear codes can be found in the data stream.  As the specification says, they may appear at anytime.  There is not a requirement to send a clear code when the string table is full.
>
> It is the encoder's decision as to when the table should be cleared.  When the table is full, the encoder can chose to use the table as is, making no changes to it until the encoder chooses to clear it.  The encoder during this time sends out codes that are of the maximum Code Size.

wxGIFDecoder::dgif() errors out as soon as it sees a symbol after the string table fills up.

**Comment by vadz** [comment]
It goes without saying that any fixes/improvements to GIF loading code would be very welcome!
