### ISSUE TITLE
wx-config broken after update

### ISSUE THREAD

**Issue by tritao** [wxWidgets/wxWidgets#22806]
**Describe the problem**

After updating my wx revision to the latest, with an out-of-tree CMake build, wx-config started outputting:

```
  *** Error: Directory ''
             no longer exists.
```

Tracked it down to: https://github.com/wxWidgets/wxWidgets/commit/ad75a77bc6deb0e3850b43b3e9384bba819cb3fe 

Without the `    set(abs_top_srcdir ${CMAKE_CURRENT_SOURCE_DIR})` line, then the path is not generated in `wx-config`.

cc @MaartenBent

**Comment by MaartenBent** [comment]
Thanks for reporting this.
I removed those because I couldn't fine any use of them in the CMake files. But they are used in `wx-config-inplace.in` instead. I'll restore them.
