### ISSUE TITLE
No EVT_DATAVIEW_COLUMN_HEADER_RIGHT_CLICK on OSX

### ISSUE THREAD

**Issue by jey5nd6** [wxWidgets/wxWidgets#22833]
### Description
`wxDataViewCtrl` doesn't generate `wxEVT_DATAVIEW_COLUMN_HEADER_RIGHT_CLICK` events on OSX.

Not really a bug (as it states this in the documentation); really more of a feature request.

1. Create a `wxDataViewCtrl`
2. Bind a `wxEVT_DATAVIEW_COLUMN_HEADER_RIGHT_CLICK` event handler to the `wxDataViewCtrl`
3. Run on Mac and right-click in the header
4. Handler doesn't get called

### Platform and version information

- wxWidgets version  you use: 3.1.5
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 12.5.1

**Comment by vadz** [comment]
AFAICS there is no notification about right clicking the column in the native control, so I have no idea about how to do this. If you know of any open source Mac programs reacting to right clicks in the column header, please check how do they do this.

**Comment by vadz** [comment]
I'm not sure why do you think so, but native wxDVC (used by default) does use native header. The generic version does not, but it also should already generate this event.

**Comment by jey5nd6** [comment]
It just didn't look very Mac-like to me.  But I found one in System Preferences > Sharing which appears the same, so that probably is a native header.

**Comment by oneeyeman1** [comment]
@vadz,
Maybe something from here: https://stackoverflow.com/questions/3849728/show-contextual-menu-on-ctrl-click-right-click-on-header-of-nstableview, can help?
Thank you.

**Comment by vadz** [comment]
Yes, thanks, Jakob Egger's answer from that question should work, I don't know why I didn't think of doing it. It's still not quite trivial, as we'd need to subclass the header view, but shouldn't be really difficult if anybody is motivated to do it.

**Comment by vadz** [comment]
I'm going to try to do it myself, finally.

**Comment by vadz** [comment]
This seems to have worked, please see #22839.

**Comment by vadz** [comment]
Applied to master, will backport to 3.2 a bit later.
