### ISSUE TITLE
Please add versioning tot wxwinm.4 (# serial)

### ISSUE THREAD

**Issue by jkraskesis** [wxWidgets/wxWidgets#22848]
Could you please add "# serial" to the wxwin.m4?  If used, aclocal could check/use the serial number  with the option "--install".

**Comment by vadz** [comment]
What's the convention here, can we just add
```
#serial 1
```
below the top comment?

**Comment by jkraskesis** [comment]
Yes, that would be an appropriate location. See https://www.gnu.org/software/automake/manual/html_node/Serials.html

**Comment by vadz** [comment]
Done in master, will backport to 3.2 too soon.
