### ISSUE TITLE
vcpkg linux fails with cmake error  Unknown arguments specified`"CMAKE_BUILD_TYPE" "STREQUAL" "Debug" "OR" "Debug" "IN_LIST" "MAP_IMPORTED_CONFIG_Debug"`

### ISSUE THREAD

**Issue by jleaders** [wxWidgets/wxWidgets#22843]
I added `wxwidgets` to my `vcokg.json` then ran debug in VS Code

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "combustion",
  "version": "1.0.1",
  "dependencies": [
    { "name": "wxwidgets",  "platform": "linux" }
  ]
}
```
### Description

```
[cmake] CMake Error at build/vcpkg_installed/x64-linux/share/wxwidgets/vcpkg-cmake-wrapper.cmake:40 (if):
[cmake]   if given arguments:
[cmake] 
[cmake]     "CMAKE_BUILD_TYPE" "STREQUAL" "Debug" "OR" "Debug" "IN_LIST" "MAP_IMPORTED_CONFIG_Debug"
[cmake] 
[cmake]   Unknown arguments specified
[cmake] Call Stack (most recent call first):
[cmake]   /home/jonny/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake:783 (include)
[cmake]   CMakeLists.txt:31 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

### Platform and version information

- wxWidgets version  you are building: latest from vcpkg
- wxWidgets port  you are building: no idea
- OS  and its version: ubuntu 22 lts
- Compiler  being used: gcc

**Comment by vadz** [comment]
Sorry, I don't think it's a wxWidgets problem at all.

vcpkg recipe for wxWidgets is maintained separately, in vcpkg repository, please report the problem there, as I have no idea what is it due to, but, again, this doesn't seem to be related to anything in wx itself.

**Comment by dg0yt** [comment]
Related: https://github.com/microsoft/vcpkg/issues/27316
