### ISSUE TITLE
[wxMSW] Mouse input is not detected when mouse leaves window

### ISSUE THREAD

**Issue by Journeyman-dev** [wxWidgets/wxWidgets#22844]
Describe the bug:
Mouse input is not detected after the mouse leaves the window. I have only found this bug to occur on Windows 10.

Expected:
If you release mouse buttons outside the window, mouse events should occur accordingly.
Observed:
On windows platform, mouse events don't occur if the mouse cursor is outside of the window.

Patch or snippet allowing to reproduce the problem:
It was reported here for FossSweeper: <https://github.com/Journeyman-dev/FossSweeper/issues/76>
You can download the latest release and see the problem for yourself: <https://github.com/Journeyman-dev/FossSweeper/releases/tag/v0.5.0.0>

Platform and version information:

- wxWidgets version you use: 3.3.0
- wxWidgets port you use:wxMSW
- OS and its version: Windows 10

**Comment by dconnet** [comment]
Were you capturing the mouse? If not, not receiving mouse events outside the window is the expected behavior.

**Comment by Journeyman-dev** [comment]
> Were you capturing the mouse? If not, not receiving mouse events outside the window is the expected behavior.

I was not. In this case, the bug is with Linux. It captures the mouse even if it is not set.

**Comment by oneeyeman1** [comment]
@Journeyman-dev ,
Please try to reproduce the behavior in one of the samples.
Please attach the patch to a sample if you do.

Thank you.

**Comment by Journeyman-dev** [comment]
This is not a bug. I didn't understand how CaptureMouse() is supposed to be used. Thank you for helping me figure that out.
