### ISSUE TITLE
wxWidgets scrolledWindow is blurry when run under Wayland with wxGTK and scaling

### ISSUE THREAD

**Issue by t2b3** [wxWidgets/wxWidgets#22849]
### Description
See original post at [https://github.com/aardappel/treesheets/issues/253#issuecomment-1257140967](https://github.com/aardappel/treesheets/issues/253#issuecomment-1257140967) for details.

wxWidgets scrolledWindow is blurry because drawing does not seem to consider the scale factor (from the compositor) in the first place. Only after having been rendered, it is resized. This results in a blurry output.

### Platform and version information

- wxWidgets version 3.2.1
- wxWidgets port wxGTK
- OS: Arch Linux (latest packages)

+ GTK version: 3.24.34+r156+g812b3930d0-1
+ Which GDK: Wayland (under wlroots 0.16.0.r5754.052ea7b4 / sway 1.7 r6965.04f8a655-1)

Expected vs observed behaviour:
Expected: Scale factor under Wayland is considered while drawing contents within a wxWidgets Scrolled Window with wxGtk. It should be the same as for the menu bars etc.
Observed: wxWidgets Scrolled Window is rendered first and then resized to fit the scale, resulting in a blurry result. This does not happen to the menu bar etc.

To Reproduce:
Steps to reproduce the behaviour, please make them as detailed as possible.
For example:

1. Compile [Treesheets](https://github.com/aardappel/treesheets) with wxGtk under Linux.
2. Run Treesheets under Wayland in sway / wlroots-based compositor.

See original post at [https://github.com/aardappel/treesheets/issues/253#issuecomment-1257140967](https://github.com/aardappel/treesheets/issues/253#issuecomment-1257140967) for details.

**Comment by vadz** [comment]
Sorry but we really need a simple example reproducing the problem. AFAICS there is nothing specific about `wxScrolledWindow`, i.e. I have no idea why would it be scaled and I suspect it might be due to something being done wrong in the application code. It could be a bug in wxGTK too, of course, but, again, then it should be reproducible in a simple example (e.g. in the drawing sample which already uses a scrolled window).

**Comment by t2b3** [comment]
This could be corrected in the Treesheets code. Sorry for the disturbance and thank you for your good work! Have a nice evening!
