### ISSUE TITLE
Update comments in setup.h

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#22855]
During past years I have noticed several outdated comments in `setup.h` (probably generated from `include/wx/setup_inc.h`?).
I have now read the whole file (mostly ignoring `wxUSE_` comments for individual controls) and prepared a list of suggested changes. I did not prepare a PR since I am not sure about many of those.

I understand this is a very low priority, but I believe it should still be considered, as the "outdateness" has accumulated.

**WXWIN_COMPATIBILITY_3_0**
> Default is 1 but please try building your code with 0 as the default will
> change to 0 in the next version and the deprecated functions will disappear
> in the version after it completely.

We have already discussed this but I still believe the comment is incorrect. There is no doubt that the default value is not 1 but 0. Moreover, I do not think that the version part should be identical to that for `WXWIN_COMPATIBILITY_3_2`, as 3.0 compatibility should be abandoned one (stable) version before 3.2 compatibility is.

**wxUSE_EXTENDED_RTTI**
> Recommended setting: 0 (this is still work in progress...)

AFAIK, there has been no progress on this in many years and the feature was even considered for removal?

**wxUSE_COMPILER_TLS**
[The comment](https://github.com/wxWidgets/wxWidgets/blob/8a77fae68b8758bbdcd729e5680e0c4bd874bfb6/include/wx/setup_inc.h#L284) mentions issues with Windows XP but since wxWidgets 3.3 supports only Vista+, not only should the comment be changed but wx/msw/chkconf.h should be modified as well?

**wxUSE_INTL**
> i18n support: _() macro, wxLocale class. Requires wxTextFile.

Does it really require wxTextFile - I cannot see that?

**wxUSE_CONFIG_NATIVE**
>  classes under Windows (using .INI files under Win16 and the registry under Win32)

Remove ".INI files under Win16 and ".

**wxUSE_DIALUP_MANAGER**
> Requires wxUSE_DYNAMIC_LOADER.

This does not seem to be the case.

**wxUSE_DYNAMIC_LOADER**
> experimental, don't use for now

Is it still experimental? Is it even used in wxWidgets code? I found `dynload.h` included in several places (e.g.,` src\msw\gdiplus.cpp`) but AFAICT, the code uses just `wxDynamicLibrary` (`dynlib.h`) and nothing from `dynload.h`?

**wxUSE_REGEX**
> You need to compile regex library from src/regex to use it under Windows.

Remove?

> Recommended setting: 1 if your compiler supports it, if it doesn't please contribute us a makefile for src/regex for it

Remove the part of the sentence after "1"?

**wxUSE_XML**
> XML parsing classes. Note that their API will change in the future, so using wxXmlDocument and wxXmlNode in your app is not recommended.

Is the Note correct?

**wxUSE_STC**
> Use wxStyledTextCtrl, a wxWidgets implementation of Scintilla.

Replace "implementation of Scintilla" with "Scintilla wrapper"?

**wxUSE_ARTPROVIDER_TANGO**
> transparency but the embedded PNG icons add to the library size.

The provider now uses SVGs instead of PNGs.

**wxUSE_HOTKEY**
> Hotkey support (currently Windows only)

According to the docs in `wxWindow::RegisterHotKey(`), hot keys are available also on macOS?
Related: Update the description in "wxUSE Preprocessor Symbols" in the docs and add macOS to the note in `wxWindow::UnRegisterHotKey()` docs.

**wxUSE_GEOMETRY**
> Miscellaneous geometry code: needed for Canvas library

Affine transformation seem to be used by `wx{GC}DC`? See also` wxUSE_DC_TRANSFORM_MATRIX` remark below.

**wxUSE_COMMON_DIALOGS**
> On rare occasions (e.g. using DJGPP) may want to omit common dialogs ...

Update.

**wxUSE_FILEDLG**
> TODO: setting to choose the generic or native one

Remove?

**wxUSE_HTML**
> wxHTML sublibrary allows to display HTML in wxWindow programs

We usually do not use "sublibrary" when referring to individual wxWidgets libraries.
Is "wxWindow" a remnant from wxWindows era, not being replaced with "wxWidgets" due to the missing "s" at its end?

**wxUSE_IPC, wxUSE_HELP, wxUSE_CONSTRAINTS, and others**
I wonder why the comments for these are written like that instead of above the define as usual?

**wxUSE_DC_TRANSFORM_MATRIX**
It seems this is in source code used for detecting availability of `wxAffineMatrix2D`, but `wxAffineMatrix2D` depends on `wxUSE_GEOMETRY`?

**wxUSE_IMAGE**
> Some formats require an extra library which is included in wxWin sources

Replace "wxWin" with "wxWidgets"?

**Comment by vadz** [comment]
Thanks for looking at this, it would be definitely nice to update these comments, but I still think it would be best to make a PR (if you'd like, please include only the changes to `include/wx/setup_inc.h`, i.e. don't include the generated files) as it would make it simpler to leave comments on the changes. As it is, discussing all of them here risks being rather messy...

But if you don't create a PR I'll still try to answer here a bit later.

**Comment by PBfordev** [comment]
Replaced by #22857.
