### ISSUE TITLE
Ambiguous documentation about when a wxEVT_TREE_END_LABEL_EDIT event is processed

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22867]
### Description

The documentation of `wxTreeCtrl::EditLabel` states:
https://github.com/wxWidgets/wxWidgets/blob/9ed1a4ea59de6269ee9a84b2da180694340c661b/interface/wx/treectrl.h#L351-L363

But on the other hand there is `wxTreeEvent::IsEditCancelled` to which the documentation states:
https://github.com/wxWidgets/wxWidgets/blob/9ed1a4ea59de6269ee9a84b2da180694340c661b/interface/wx/treectrl.h#L1149-L1153

At least under MSW, the wxEVT_TREE_END_LABEL_EDIT event seems to always be processed, even if the user canceled editing the label.

Am I correct in assuming that the wxEVT_TREE_END_LABEL_EDIT event is generally (on any platform) always processed and the documentation of `wxTreeCtrl::EditLabel` is incorrect or outdated?

Would be great if the documentation could be clear on this. Thanks!

### Platform and version information

- wxWidgets version  you use: 3.2.0
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by taler21** [comment]
I have now tested it on Linux as well (with both GTK2 and GTK3).
And there the `wxEVT_TREE_END_LABEL_EDIT` event is also always be processed, even if the user canceled editing the label.

However, I have no possibility to test it under macOS.

**Comment by vadz** [comment]
Sorry, do you mean "generated" by "processed" here? Otherwise I don't really understand what do you mean...

FWIW I wouldn't expect `wxEVT_TREE_END_LABEL_EDIT` to be generated if `wxEVT_TREE_BEGIN_LABEL_EDIT` was vetoed, but would expect it in all the other cases. Note that there is a big difference between the program vetoing editing and the user cancelling it: the former doesn't require (and shouldn't result in) an event, while the latter definitely does.

**Comment by taler21** [comment]
> Sorry, do you mean "generated" by "processed" here? Otherwise I don't really understand what do you mean...

Yes, I mean "generated". Sorry for my wrong wording.

> FWIW I wouldn't expect wxEVT_TREE_END_LABEL_EDIT to be generated if wxEVT_TREE_BEGIN_LABEL_EDIT was vetoed, but would expect it in all the other cases. Note that there is a big difference between the program vetoing editing and the user cancelling it: the former doesn't require (and shouldn't result in) an event, while the latter definitely does.

Thanks for the explanation.

To me, the documentation of `wxTreeCtrl::EditLabel` currently states that the `wxEVT_TREE_END_LABEL_EDIT` event will be only sent when editing is not canceled by the user.
But as you say and I have seen so far, the event is generated regardless of whether the user cancels editing, which is important in my use case.

**Comment by vadz** [comment]
I agree that this part is misleading, fixed now, please let me know if you still see any problems.

**Comment by taler21** [comment]
Much clearer now. Thanks.
