### ISSUE TITLE
wxExecute Too many pipes

### ISSUE THREAD

**Issue by floatingloud** [wxWidgets/wxWidgets#22869]
Hi Folks,
I call 
```
ntpProcess = new NtpProcess;
ntpProcess->Redirect();
wxExecute("timedatectl", wxEXEC_ASYNC, ntpProcess); 
```
and read the output and error in the Terminate() function.
However, after about 500 calls the OS throws a system error "Too many pipes".
It seems like the process is not closing the pipes opened for Redirect();
I am running wxWidgets on  Raspbian 9 and 11.
Thanks.

**Comment by vadz** [comment]
Normally the pipe should be closed when the `wxProcess` is destroyed, I think. Could it be that you don't delete it when it terminates? See the `exec` sample for how it does it.

If you do delete them, please try making the [smallest possible patch](https://www.wxwidgets.org/develop/how-to-submit-patches/) to this sample allowing to reproduce the problem, as the code shown above is not enough on its own.

**Comment by floatingloud** [comment]
Thanks for your reply vadz.
Maybe I'm wrong, but I thought the process destroyed itself after OnTerminate()?
`void NtpProcess::OnTerminate(int pid, int istatus)
{
    wxString status;
    wxString error;

    if(IsErrorAvailable())
        error = getOutput(GetErrorStream());

    if(IsInputAvailable())
        status = getOutput(GetInputStream());
    else
    {
//        LogWarning("timedatectl failed");
    }
    CloseOutput();
`
Please could you point me to the exec sample?
Thanks.

**Comment by oneeyeman1** [comment]
@floatingloud ,
Exec sample can be found at the samples directory of the wxWidgets distribution or at https://github.com/wxWidgets/wxWidgets/tree/master/samples/exec.

**Comment by vadz** [comment]
I was indeed wrong, `wxProcess` does destroy itself by default, as [documented here](https://docs.wxwidgets.org/3.2.1/classwx_process.html), but only if in its default `OnTerminate()` implementation. As you override it and don't call the base class version, you must do `delete this;` yourself -- without this, the object is never destroyed and the pipe is never closed.

**Comment by floatingloud** [comment]
@vadz How does one delete a process that has already run its OnTerminate() ? I have tried `wxProcess::Exists(ntpPid)`, but it says that the process no longer exists. Yet it leaves two pipes open.

**Comment by vadz** [comment]
You're mixing up OS processes (identified by PID) and C++ objects (`wxProcess`). You need to delete the latter, using `delete`, not the former.

**Comment by SpareSimian** [comment]
And raw `delete` is rarely a good idea in application code. If you allocated it on the heap, you should store it in a smart pointer.

**Comment by floatingloud** [comment]
@vadz Thanks, I understand now. I left my code running all night and it seems that `delete` does remove the accumulation of pipes.
@SpareSimian Generally what you say is correct, but wxProcess seems designed to be "tidied up" this way. As wxWidgets attempts, pretty successfully, to abstract the programmer from boilerplate C++,  I'm not sure why the wxProcess seems to need manual tidying up.

**Comment by vadz** [comment]
`wxProcess` is needed after the child process exits, so it can't be deleted at this moment and then wxWidgets doesn't know when it can delete it, i.e. when the program doesn't need it any longer, so the only choice is to let the program do it. This is unusual, but this is why it's documented so prominently.

In non-ancient C++ we'd probably use `shared_ptr<wxProcess>` or something like this, but it still wouldn't, and couldn't, be totally automatic because the lifetime of this object depends on what the program needs to do with it.

**Comment by SpareSimian** [comment]
Smart pointers ensure that objects don't leak, and that's fundamentally what's happening in this issue. You can reset() a smart pointer to release resources at the most desired point and the smart pointer's destructor guarantees that the resources are still released in unexpected (exceptional) exit paths. 

My oldest code lacks smart pointers, but now I find that they force me to think more about object lifetimes. Even in garbage-collected languages where I need to work harder to ensure that scarce hardware resources are released promptly.

**Comment by floatingloud** [comment]
@vadz "this is why it's documented so prominently" I must have spent a whole day searching on wxWidgets.org, Google and DDG and I didn't find anything explicitly saying that I might, depending on use, need `delete this` at the end of the `OnTerminate()` function.

**Comment by vadz** [comment]
There is a big "Note" in `wxProcess` documentation explaining how its deletion works. It says that it deletes itself on its own, but this implies, of course, that you're responsible for deleting it if you don't leave it "on its own".
