### ISSUE TITLE
Get rid of `wxStringImpl`

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#22883]
We should just always use `std::[w]string` directly instead, our own implementation is very different (uses COW), almost not tested any longer (as it's disabled by default since a very long time) and there is just no point in avoiding the use of `std::string` any longer.

**Comment by beENABLED** [comment]
FWIW; I have always used and still use the wxStringImpl. I also set wxUSE_STD_CONTAINERS to 0. Mainly because i hate std exceptions and cluttering my code with try/catch everywhere.

**Comment by vadz** [comment]
Sorry, `wxUSE_STD_CONTAINERS==0` won't be supported any longer in master, we're already using `std::vector` and `std::unordered_map` and will probably use more of them soon.

You don't have to put try/catch everywhere, of course, and many/most `std::string` functions don't throw when used with correct parameters (and `wxString` will only use them with the correct values).

**Comment by paulcor** [comment]
> `wxUSE_STD_CONTAINERS==0` won't be supported any longer

Did I miss a discussion where this was decided?
