### ISSUE TITLE
wxBitmapBundle documentation incoherent

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#22891]
Documentation for wxBitmapBundle says:
> The code shown above will use 32 pixel bitmap in normal DPI, 64 pixel bitmap in "high DPI", i.e. pixel-doubling or 200% resolution, and 48 pixel bitmap in 150% resolution. For all the other resolutions, the best matching bitmap will be created dynamically from the best available match, e.g. for 175% resolution, 64 pixel bitmap will be rescaled to 56 pixels.

but the High DPI Support page states:
> Independently of the way in which the bundle was created, it will provide the bitmap closest in size to the expected size at the current DPI, while trying to avoid having scale it. This means that at 175% DPI scaling, for example, the high DPI (i.e. double-sized) bitmap will be used without scaling rather than scaling it by 0.875.

In the same page:
> Such bitmap bundles [created from SVG] will always produce bitmaps of exactly the required size, at any resolution.

This is not what I get, My bundle is created with SVG and I get the same bitmap for 1.00, 1.25 and 1.50 scale factors, and a double size bitmap for 1.75, as described for non-SVG bundles.

**Comment by PBfordev** [comment]
FWIW, when I run this code using the latest master on Windows 10
```cpp
#include <wx/wx.h>

#include <vector>

// from the toolbar sample
static const char svg_data[] =
"<svg version=\"1.1\" viewBox=\"0.0 0.0 360.0 360.0\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns=\"http://www.w3.org/2000/svg\">"
"<g>"
"<path stroke=\"#000000\" fill=\"#ff0000\" d=\"m 10 170 c0 -12 10 -24 24 -24 l100 0 c6 0 12 2 17 7 c4 4 7 10 7 17 l0 100 c0 12 -10 24 -24 24 l-100 0c-12 0 -24 -10 -24 -24 z\"/>"
"<path stroke=\"#000000\" fill=\"#0000ff\" d=\"m100  90 c0 -12 10 -24 24 -24 l100 0 c6 0 12 2 17 7 c4 4 7 10 7 17 l0 100 c0 12 -10 24 -24 24 l-100 0c-12 0 -24 -10 -24 -24 z\"/>"
"<path stroke=\"#000000\" fill=\"#ffff00\" d=\"m210 140 c0 -12 10 -24 24 -24 l100 0 c6 0 12 2 17 7 c4 4 7 10 7 17 l0 100 c0 12 -10 24 -24 24 l-100 0c-12 0 -24 -10 -24 -24 z\"/>"
"</g>"
"</svg>";

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        std::vector<double> scales{ 1.00, 1.25, 1.50, 1.75, 2.00 };
        wxBitmapBundle      bundle{ wxBitmapBundle::FromSVG(svg_data, wxSize(32,32)) };

        for ( const auto& scale : scales )
        {
            const wxSize preferredSize{ bundle.GetPreferredBitmapSizeAtScale(scale) };
            const wxSize bitmapSize{ bundle.GetBitmap(preferredSize).GetSize() };

            wxLogDebug("scale %.2f, preferred size %dx%d, bitmap size %dx%d",  
                scale, preferredSize.x, preferredSize.y, bitmapSize.x, bitmapSize.y);
        }

        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```
I get
```
scale 1.00, preferred size 32x32, bitmap size 32x32
scale 1.25, preferred size 40x40, bitmap size 40x40
scale 1.50, preferred size 48x48, bitmap size 48x48
scale 1.75, preferred size 56x56, bitmap size 56x56
scale 2.00, preferred size 64x64, bitmap size 64x64
```
so the bitmap size matches the requested one exactly here. But perhaps I am missing something...

**Comment by wh11204** [comment]
Thank you for the test code, it works OK here so the problem must be elsewhere. The documentation problem (first two paragraphs of the original post) remains, though.
