### ISSUE TITLE
File save dialog does not show the overwrite prompt if filename is entered without extension

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22898]
### Description

Up to wxWidgets-3.1.7 the overwrite prompt of the `wxFileDialog` works well.
But with wxWidgets-3.2.0 the `wxFileDialog` does not show the overwrite prompt if the filename is entered without an extension.

### To Reproduce

This regression can be reproduced in the dialogs sample.
1. Start the dialogs sample.
2. Press keys `Ctrl` + `S`
3. Enter a filename of an existing file without its extension.
4. Click 'Save'.
5. Bug: The expected overwrite prompt will not be shown by the dialog.

### Platform and version information

- wxWidgets version  you use: 3.2.0
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
Thanks, I indeed see this too and I've committed a fix for it which seems to work for me. Please reopen if you still see any problems with it.

**Comment by taler21** [comment]
The fix works fine. Many thanks.
