### ISSUE TITLE
wxSound link issue on QT

### ISSUE THREAD

**Issue by davidkaroly** [wxWidgets/wxWidgets#22895]
### Description
When I try to build the *sound* sample program for wxQT on Fedora, I get a link issue as there's no wxSound implementation.

Steps for reproducing:
```
mkdir build_qt
cd build_qt/
../configure --with-qt
make -j8
cd samples/sound
make
```

Expected output: compile and linking successful.

Actual output: linking fails, wxSound::* methods are not found. 
Note: I get a similar failure for *joytest*

```
[david@fedora sound]$ make
/home/david/wxWidgets/build_qt/bk-deps g++ -c -o sound_sound.o -I/home/david/wxWidgets/build_qt/lib/wx/include/qt-unicode-3.3 -I../../../include -D_FILE_OFFSET_BITS=64 -I/usr/include/qt5/QtCore -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -DQT_OPENGL_LIB -I/usr/include/qt5/QtOpenGL -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -I/usr/include/qt5/QtTest -DQT_CORE_LIB  -D__WXQT__      -I../../../samples/sound -DWXUSINGDLL -I../../../samples/sound/../../samples -pthread -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -O2 -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libxml2 -I/usr/include/pixman-1  -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -DPIC   ../../../samples/sound/sound.cpp
g++ -o sound sound_sound.o     -L/home/david/wxWidgets/build_qt/lib   -Wl,-rpath,/home/david/wxWidgets/build_qt/lib   -pthread   -lwx_qtu_core-3.3  -lwx_baseu-3.3        -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Test -lQt5Core -lcairo -lpng -lz -ljpeg -ltiff   -lwxexpat-3.3 -pthread   -Wl,--version-script,/home/david/wxWidgets/build_qt/version-script -lz -lcurl -lm -lpcre2-32   -lz -lcurl -lm
/usr/bin/ld: sound_sound.o: in function `MyFrame::TryCreateSound() const':
sound.cpp:(.text+0x1da): undefined reference to `wxSound::wxSound()'
/usr/bin/ld: sound.cpp:(.text+0x1eb): undefined reference to `wxSound::Create(wxString const&, bool)'
/usr/bin/ld: sound_sound.o: in function `MyFrame::OnPlayAsyncOnStack(wxCommandEvent&)':
sound.cpp:(.text+0x2472): undefined reference to `wxSound::wxSound()'
/usr/bin/ld: sound.cpp:(.text+0x2483): undefined reference to `wxSound::Create(wxString const&, bool)'
/usr/bin/ld: sound.cpp:(.text+0x2498): undefined reference to `wxSound::DoPlay(unsigned int) const'
/usr/bin/ld: sound.cpp:(.text+0x24a0): undefined reference to `wxSound::~wxSound()'
/usr/bin/ld: sound_sound.o: in function `MyFrame::OnStop(wxCommandEvent&)':
sound.cpp:(.text+0xa1): undefined reference to `wxSound::Stop()'
/usr/bin/ld: sound_sound.o: in function `MyFrame::CreateSound(wxSound&) const':
sound.cpp:(.text+0x1b0): undefined reference to `wxSound::Create(wxString const&, bool)'
/usr/bin/ld: sound_sound.o: in function `MyFrame::OnPlayAsyncOnStack(wxCommandEvent&) [clone .cold]':
sound.cpp:(.text.unlikely+0x430): undefined reference to `wxSound::~wxSound()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:155: sound] Error 1
[david@fedora sound]$
```

Some more context:
* I did not specify any sound related options to configure so it uses a default value of `wxUSE_SOUND=1`
* there's no wxSound implementation for QT and the Unix implementation is not built
* sound_sdl.cpp is built but it implements only a backend for the Unix sound.cpp which is not built

```
[david@fedora build_qt]$ grep wxUSE_SOUND config.status 
D["wxUSE_SOUND"]=" 1"
[david@fedora build_qt]$ ls -l *sound*.o
-rw-r--r--. 1 david david   952 Oct 19 19:54 coredll_sound_sdl.o
-rw-r--r--. 1 david david 15856 Oct 19 19:50 wxscintilla_LexCsound.o
[david@fedora build_qt]$ 
```

### Platform and version information

- wxWidgets version you are building: 3.2.1
- wxWidgets port you are building: wxQT
- OS and its version: Fedora 36
- Compiler being used: gcc 12.2.1

**Comment by vadz** [comment]
I think we need to compile `src/unix/sound.cpp` as part of wxQt, but I haven't tested it.

In the meanwhile, you could use `--disable-sound` to work around the problem, but we need to solve it properly, of course, i.e. either do the above or disable sound support in wxQt builds unconditionally.

**Comment by davidkaroly** [comment]
Yes, we can use `--disable-sound` but it would be better to have sound available on Qt.

I also tried rebuilding with `src/unix/sound.cpp` and first results are good. However, I'm not entirely sure about rebaking the makefiles and configure script.

**Comment by vadz** [comment]
Please test #22902 and let me know if you have any problems with it, TIA!

**Comment by oneeyeman1** [comment]
Qt have QSound class which could probably be used here
Someone just needs to write a wrapper..

Thank you.

**Comment by davidkaroly** [comment]
> Please test #22902 and let me know if you have any problems with it, TIA!

Thanks for the update.
I can confirm that now all the samples build successfully on Fedora 36.

**Comment by vadz** [comment]
This probably could be safely backported to 3.2 if anybody is interested in using wxQt there.
