### ISSUE TITLE
Dialup manager should be disabled on QT

### ISSUE THREAD

**Issue by davidkaroly** [wxWidgets/wxWidgets#22896]
### Description
Dialup manager should be disabled in wxQT, similarly to Mac.

Current behavior: `wxUSE_DIALUP_MANAGER` is enabled by default but there's no wxDialUpManager implementation for wxQT.
As dialup is not used so widely nowadays, it would make sense to disable it when building for QT.

e.g.

```diff
--- a/configure.in
+++ b/configure.in
@@ -6790,7 +6790,7 @@ if test "$wxUSE_PRIVATE_FONTS" = "yes"; then
 fi
 
 if test "$wxUSE_DIALUP_MANAGER" = "yes"; then
-    if test "$wxUSE_MAC" = 1; then
+    if test "$wxUSE_MAC" = 1 -o "$wxUSE_QT" = 1; then
         AC_MSG_WARN([Dialup manager not supported on this platform... disabled])
     else
         AC_DEFINE(wxUSE_DIALUP_MANAGER)
```

### Platform and version information

- wxWidgets version: 3.2.1
- wxWidgets port: wxQT
- OS: Fedora 36
- Compiler being used: gcc 12.2.1

**Comment by vadz** [comment]
This is more or less the same as #22895, i.e. I think we should compile `src/unix/dialup.cpp` as part of wxQt (I'd also expect `src/unix/joystick.cpp` to need to be part of it, BTW). But if it doesn't work, we could also disable it, of course, you're right that nobody needs this class in 2022.

**Comment by vadz** [comment]
This was fixed in master by the commit above and could be backported to 3.2 if necessary.
