### ISSUE TITLE
Refresh() under Qt is inconsistent with the other ports

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#22899]
### Description

`wxWindow::Refresh()` under `Qt` doesn't refresh child windows like the other ports:

- On `wxMSW`, the `RDW_ALLCHILDREN` flag is specified which includes child windows, if any, in the repainting operation.

- On `wxGTK` which calls `gdk_window_invalidate_rect( , , true /*invalidate_children*/)`
> From GDK 3 Reference Manual:
>
> The invalidate_children parameter controls whether the region of each child window that intersects region will also be invalidated.

- On wxOSX ???

As a consequence, it will prevent this PR #22893 from being merged because of it.

As I'm not a Qt expert I applied the following patch and everything works as expected:
```
diff --git a/src/qt/window.cpp b/src/qt/window.cpp
index e774253d8f..26081bc5c7 100644
--- a/src/qt/window.cpp
+++ b/src/qt/window.cpp
@@ -560,11 +560,32 @@ void wxWindowQt::Refresh( bool WXUNUSED( eraseBackground ), const wxRect *rect )
                        GetName(),
                        rect->x, rect->y, rect->width, rect->height);
             widget->update( wxQtConvertRect( *rect ));
+
+            wxRect parentRect = *rect;
+            ClientToScreen(&parentRect.x, &parentRect.y);
+
+            wxWindowList& children = GetChildren();
+            for ( wxWindowList::iterator i = children.begin(); i != children.end(); ++i )
+            {
+                wxRect childRect = (*i)->GetScreenRect();
+                childRect.Intersect(parentRect);
+                if ( !childRect.IsEmpty() )
+                {
+                    (*i)->ScreenToClient(&childRect.x, &childRect.y);
+                    (*i)->RefreshRect(childRect);
+                }
+            }
         }
         else
         {
             wxLogTrace(TRACE_QT_WINDOW, wxT("wxWindow::Refresh %s"), GetName());
             widget->update();
+
+            wxWindowList& children = GetChildren();
+            for ( wxWindowList::iterator i = children.begin(); i != children.end(); ++i )
+            {
+                (*i)->Refresh();
+            }
         }
     }
 }

```

### Platform and version information

- wxWidgets version  you use: latest
- wxWidgets port  you use: wxQt
- OS  and its version: Ubuntu 18.04

**Comment by vadz** [comment]
If `QtWidget::update()` doesn't update the children (the documentation doesn't say anything one way or the other...), then this seems like the right thing to do, so I this we should just apply this patch, thanks.

FWIW it would be nice to have a test for this, e.g. create a window with a child, call `Refresh()` on the window and check that the child got a `wxEVT_PAINT`.

**Comment by vadz** [comment]
The PR was merged, so closing, thanks again!
