### ISSUE TITLE
Sample applications (like about.exe) fail to find resources when not launched from the application folder.

### ISSUE THREAD

**Issue by lviolette** [wxWidgets/wxWidgets#22906]
### Description
When a sample such as about.exe is launched on the Windows platform and its current directory is not the application directory, the sample fails to locate its resources due to it assuming the resources are relative to the current directory rather than the application directory.
## Expected Behavior
I could launch any of the sample applications from an arbitrary folder and they would run successfully finding their file-based application resources.
## Actual Behavior
When About.exe (and many others) are run from a folder other than the application folder, attempting to show the About dialog displays an error about not being able to load the html and svg files.
## To Reproduce
1.  Build the samples on Windows.
2. Navigate to the samples root folder in Explorer.
3. In the search bar type ```ext:exe``` and press enter.
4. Find About.exe in the resulting list and launch it by double-clicking on it.
5. Select File|About.

Notice the error messages about not being able to find the resources.

## A Possible Fix
When the sample applications use relative paths to retrieve resources, convert those to absolute paths first using the Executable path as the base path.
```
About.cpp->MyFrame::OnAbout
{
    wxString exeFolder = wxFileName(wxStandardPaths::Get().GetExecutablePath()).GetPath();
    auto* parser = html->GetParser();
    if (parser)
    {
        auto* fs = parser->GetFS();
        if (fs)
        {
            fs->ChangePathTo(exeFolder, true);
        }
    }

    html -> SetHTMLBackgroundImage(wxBitmapBundle::FromSVGFile(exeFolder + "/data/bg.svg", wxSize(65, 45)));
}

```

### Platform and version information
- wxWidgets you use:  3.2.0
- wxWidgets port you use: wxMSW
- OS and its version: Windows 10 20H2.

**Comment by vadz** [comment]
Most (all?) of the samples indeed keep things simple by expecting to find their files in their directory. And I'm not sure if it's really worth it to add extra code to do it to all of them, to be honest, they're supposed to be samples, not production-ready applications.

Maybe giving a clear error along the lines of "Please run this sample from the directory containing its data files, i.e. samples/foo" would be a reasonable compromise?

**Comment by lviolette** [comment]
Yeah, I totally understand.  It's tough because most of the time I'm just wanting to run all the samples looking for something close to what I want to do.  Because they're not all built to the same folder, it's painful to navigate to each one to execute it.  Which is why I do the ```ext:exe``` method to list them all together so I can run through them when I'm looking for something.
Anyway.  I get it. they're samples and it may not be worth putting too much effort into them.

**Comment by PBfordev** [comment]
> Yeah, I totally understand. It's tough because most of the time I'm just wanting to run all the samples looking for something close to what I want to do. Because they're not all built to the same folder, it's painful to navigate to each one to execute it. 

If you have disk space to spare, create a CMake build with samples. This build has all the samples in the same folder, which makes them easy to run. Unfortunately, this still has issues as some samples overwrite each other data files with the same name, but I still find this the most convenient.
