### ISSUE TITLE
Hyperlink in the wxDateTime page not working

### ISSUE THREAD

**Issue by nickhofstetter** [wxWidgets/wxWidgets#22912]
The wxDateTime::Format help links to here,
https://cplusplus.com/reference/clibrary/ctime/strftime.html

But the link is no longet valid and needs to point here
https://cplusplus.com/reference/ctime/strftime/

**Comment by PBfordev** [comment]
Thanks for reporting this, should be fixed by #22913.

**Comment by PBfordev** [comment]
This issue should be closed, it was fixed by https://github.com/wxWidgets/wxWidgets/commit/232e161ed63362ce5053f1e147491c780fee2e64.

**Comment by vadz** [comment]
Thanks!
