### ISSUE TITLE
'TreeView_EndEditLabelNow() failed' when renaming a tree item

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22921]
### Description

When renaming an item of a `wxTreeCtrl`, an API error will be logged.

```
..\..\src\msw\treectrl.cpp(2074): 'TreeView_EndEditLabelNow()' failed with error 0x00000000 (The operation completed successfully.).
```

### To Reproduce:
The issue can be reproduced with the **treectrl sample**:
1. Start the treectrl sample with the debugger.
2. Rename an item in the tree and the mentioned error will be logged.

Note: The error is logged both on successful renaming and on cancellation by the user (e.g. by pressing the 'Esc' key).
I assume in both of these cases no error should be logged.

### Platform and version information

- wxWidgets version  you use: 3.2.0
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
We probably should check `::GetLastError()` and do nothing if it's 0. OTOH this function is not documented as setting it at all, so maybe we shouldn't even use it here. OT3H I have no idea why would it fail in the first place.

**Comment by taler21** [comment]
Microsoft's documentation does not state that the used macro [TreeView_EndEditLabelNow](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-treeview_endeditlabelnow) has a return value.
Maybe an indication that the return value has no meaning?

**Comment by PBfordev** [comment]
Actually, Microsoft defines the macro as
```cpp
#define TreeView_EndEditLabelNow(hwnd, fCancel) \
    (BOOL)SNDMSG((hwnd), TVM_ENDEDITLABELNOW, (WPARAM)(fCancel), 0)
```
and `TVM_ENDEDITLABELNOW` docs for _Return value_ states
> Returns TRUE if successful, or FALSE otherwise.

I have no idea why this could fail but I do agree that using `::GetLastError()` here is incorrect.

**Comment by vadz** [comment]
I think I understand what's going on here now and so I've created #23019 fixing this problem -- hopefully without breaking anything else, but any testing to confirming this would be very welcome!

**Comment by taler21** [comment]
I can confirm that the error is no longer logged when editing the label is completed with Enter or canceled with Esc.

But it is still logged if
- editing is completed by clicking outside the text box.
- `wxEVT_TREE_END_LABEL_EDIT` event is vetoed programmatically.

**Comment by vadz** [comment]
OK, thanks, I give up and have removed this message entirely now, it's just not useful enough to warrant spending even more time on it. I'll merge that PR soon unless there are any objections.

Thanks for (re)testing!
