### ISSUE TITLE
Extra line break in wxSysColourChangedEvent documentation

### ISSUE THREAD

**Issue by imciner2** [wxWidgets/wxWidgets#22925]
### Description
The online documentation for the `wxSysColourChangedEvent` class has a weird line break in the middle of the parenthetical clause:

![image](https://user-images.githubusercontent.com/2262453/198588583-e9721047-197e-4c45-bfb4-9abf9ca83482.png)

Looking at the interface header for the class: https://github.com/wxWidgets/wxWidgets/blob/f4d93e5afddd95eecefb87edcf86ba3ada55e42a/interface/wx/event.h#L1905
there isn't a line break in there, so somehow Doxygen is adding a line break when it shouldn't.

### Platform and version information

- wxWidgets version you use: Latest & Stable 3.2 docs
- wxWidgets port you use: N/A (Online documentation)
- OS  and its version: N/A (Online documentation)

**Comment by vadz** [comment]
It's the period which is interpreted as terminating the "brief description". I'll fix this, thanks.
