### ISSUE TITLE
wxTextDataObject adds \0 to passed string (not really expected)

### ISSUE THREAD

**Issue by SyDr** [wxWidgets/wxWidgets#22928]
### Description
When wxTextDataObject is created -> additional '\0' is added to passed string, resulting in different length for the "same" string. 

To Reproduce:
1. Apply patch for samples:
```diff --git a/samples/dataview/dataview.cpp b/samples/dataview/dataview.cpp
index 8b790ed2e7..534d01a8e5 100644
--- a/samples/dataview/dataview.cpp
+++ b/samples/dataview/dataview.cpp
@@ -1479,7 +1479,11 @@ void MyFrame::OnDrop( wxDataViewEvent &event )
                          obj.GetText(), m_music_model->GetTitle(item), event.GetProposedDropIndex());
         }
         else
-            wxLogMessage("Text '%s' dropped on item '%s'", obj.GetText(), m_music_model->GetTitle(item));
+ 	{
+		wxLogMessage("Text '%s' dropped on item '%s'", obj.GetText(), m_music_model->GetTitle(item));
+		wxLogMessage("Text '%s', length %i dropped on '%s', length %i", obj.GetText(), obj.GetText().size(), m_music_model->GetTitle(item), m_music_model->GetTitle(item).size());
+		wxLogMessage("%i", obj.GetText() == m_music_model->GetTitle(item));
+	}
     }
     else
         wxLogMessage("Text '%s' dropped on background (proposed index = %i)", obj.GetText(), event.GetProposedDropIndex());
-- 
2.33.0.windows.2
```
2. Launch sample for dataview
3. Drag and drop item on itself

Expected: same string and same length and 1 on the next line in the log
Actual result:
```
Text 'Ninth symphony', length 15 dropped on 'Ninth symphony', length 14
0
```

### Platform and version information

- wxWidgets version: 3.2.1 (doesn't work on master either)
- wxWidgets port: wxMSW
- OS: Windows 11 (22000.1098)

**Comment by vadz** [comment]
Thanks for reporting this, it took me some time to understand what exactly we're doing wrong here, but I think I've finally found it and so made PR #23018 with the fix (only the last commit there is really significant).

This fixes your test case (thanks for providing it too!) and hopefully shouldn't break anything else.

**Comment by vadz** [comment]
I'm pushing the fix to master but this is probably sufficiently important to be backported to 3.2 too (after some testing).

**Comment by SyDr** [comment]
Thanks. Works correctly for me.
