### ISSUE TITLE
wxID_CUT active with no wxTextCtrl selection, even though wxID_COPY is correctly greyed-out

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#22938]
### Description
Create a simple app with an Edit menu containing default copy/cut/paste items, a wxTextCtrl, and a ProcessEvent override for propagating menu events to the currently focused control.

When running the app on Mac OS, the clipboard works correctly. As far as I understand, the default Edit menu commands are handled natively on Mac OS X.

On Windows and Linux, copy and paste commands work as expected. The problem is with the wxID_CUT menu item. It works well when a text is selected, but when there's no selection, it's not greyed out (and it should be). If the user clicks wxID_CUT with no text selected, nothing changes: the clipboard still contains previously copied/cut text.

Expected behavior: when there's no selection, wxID_CUT should be greyed out, just as wxID_COPY is.

```
// wxWidgets "Hello world" Program
// For compilers that support precompilation, includes "wx/wx.h".
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif
class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};
class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size);

private:
    bool ProcessEvent(wxEvent &event) override;
};

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame("Hello World", wxDefaultPosition, wxDefaultSize);
    frame->Show(true);
    return true;
}
MyFrame::MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size)
    : wxFrame(NULL, wxID_ANY, title, pos, size)
{
    wxMenu *fileMenu = new wxMenu();

    fileMenu->Append(wxID_EXIT);

    wxMenu *editMenu = new wxMenu();
    editMenu->Append(wxID_COPY);
    editMenu->Append(wxID_CUT);
    editMenu->Append(wxID_PASTE);

    wxMenuBar *menuBar = new wxMenuBar();

    menuBar->Append(fileMenu, "&File");
    menuBar->Append(editMenu, "Edit");

    SetMenuBar(menuBar);

    auto textCtrl = new wxTextCtrl(this, wxID_ANY);

    CreateStatusBar();
    SetStatusText("Welcome to wxWidgets!");
}

bool MyFrame::ProcessEvent(wxEvent &event)
{
    static wxEvent *lastEvent = nullptr;

    if (event.GetEventType() == wxEVT_MENU || event.GetEventType() == wxEVT_UPDATE_UI)
    {
        if (lastEvent != &event)
        {
            lastEvent = &event;

            auto focusedChild = wxFindFocusDescendant(this);
            if (focusedChild && focusedChild->GetEventHandler()->ProcessEvent(event))
            {
                return true;
            }

            lastEvent = nullptr;
        }
    }

    return wxFrame::ProcessEvent(event);
}

```

BTW: is this the recommended way to implement ProcessEvent if one wants to make the default Edit commands work with the currently focused text control (I've found similar implementations in the samples directory and the wx book)? It sure does look like a hack, especially with the static variables that break wxCommandEvent propagation... 

### Platform and version information

- wxWidgets version  you use: 3.1.4
- wxWidgets port  you use: wxMSW, wxGTK
- OS  and its version: Windows 10, Ubuntu 22.04.1 LTS

+ GTK version: 3.24.33
+ Which GDK  backend is used: ?
+ Current theme:  ?

**Comment by lszl84** [comment]
Ok, forget about it. It was a silly bug on my part: forgot to reset `lastEvent = nullptr;` before `return true;`

Interesting that this produces inconsistent behavior for wxID_CUT vs wxID_COPY though.

**Comment by vadz** [comment]
The recommended way is to use `wxEVT_UPDATE_UI` and it is much better to use it for the menu than doing it manually.

**Comment by lszl84** [comment]
No problem. Thanks for the clarification! 🙂
