### ISSUE TITLE
Documentation for FindMenu() is wrong/missing

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#22955]
Describe the bug:
The documentation on the website for version 3.2 and trunk documents this function:

```
virtual int | FindItem (const wxString &itemString) const
```

URL: https://docs.wxwidgets.org/3.2/classwx_menu.html#a7e8bf27fe85df1e81905b544cbf2021a

Expected vs observed behaviour:
That function doesn't exist, I believe it should be `FindMenu()` which is not documented but in the header.

To Reproduce:
Go to website and search for `FindMenu` or attempt to implement `FindItem(_("test"));`

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: NA
- OS  and its version: NA

**Comment by vadz** [comment]
`wxMenuBar::FindMenu()` is [documented here](https://docs.wxwidgets.org/3.2/classwx_menu_bar.html#a459b49b70c955145fbb202c258188309). `wxMenu::FindItem()` is a different function. What exactly is the problem?

**Comment by willco007** [comment]
Bah, indeed I was looking in the completely wrong location. Sorry for the noise.
