### ISSUE TITLE
wxWindowQt::ClientToScreen() gives incorrect results

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#22968]
### Description

Take this example:
```
auto frame = new wxFrame(nullptr, wxID_ANY, ...)
auto panel = new wxPanel(frame, wxID_ANY, wxPoint(0, 50), wxSize(100, 50));

const wxPoint frameScreenPos = frame->ClientToScreen(wxPoint(0, 0));
const wxPoint panelScreenPos = panel->ClientToScreen(wxPoint(0, 0));
```
the following is currently failing:

`wxASSERT( frameScreenPos == panelScreenPos )`

but this succeeds:

`wxASSERT( frameScreenPos == panelScreenPos - wxPoint(1, 1) )`

Due to this, the following wx tests are also failing:

https://github.com/wxWidgets/wxWidgets/blob/f8ce99bf66d640ef8573bdcd4cc44ffe2c01084b/tests/misc/guifuncs.cpp#L120-L140

https://github.com/wxWidgets/wxWidgets/blob/f8ce99bf66d640ef8573bdcd4cc44ffe2c01084b/tests/controls/gridtest.cpp#L1468-L1513

https://github.com/wxWidgets/wxWidgets/blob/f8ce99bf66d640ef8573bdcd4cc44ffe2c01084b/tests/controls/gridtest.cpp#L1515-L1565

Unless someone finds a better solution, I suggest applying the following patch which seems to make all of the above work correctly:
```
diff --git a/src/qt/window.cpp b/src/qt/window.cpp
index d1f38af5d1..3413f44dca 100644
--- a/src/qt/window.cpp
+++ b/src/qt/window.cpp
@@ -966,17 +966,23 @@ void wxWindowQt::SetExtraStyle( long exStyle )
 
 void wxWindowQt::DoClientToScreen( int *x, int *y ) const
 {
-    QPoint screenPosition = GetHandle()->mapToGlobal( QPoint( *x, *y ));
+    QPoint screenPosition = GetHandle()->mapToParent( QPoint( *x, *y ));
     *x = screenPosition.x();
     *y = screenPosition.y();
+
+    if ( GetParent() )
+        GetParent()->ClientToScreen(x, y);
 }
 
 
 void wxWindowQt::DoScreenToClient( int *x, int *y ) const
 {
-    QPoint clientPosition = GetHandle()->mapFromGlobal( QPoint( *x, *y ));
+    QPoint clientPosition = GetHandle()->mapFromParent( QPoint( *x, *y ));
     *x = clientPosition.x();
     *y = clientPosition.y();
+
+    if ( GetParent() )
+        GetParent()->ScreenToClient(x, y);
 }
```
i.e. map child coordinates to parents (recursively), and the last parent will
map to/from global because from **Qt** documentation [`QWidget::mapToParent()`]:
> Same as [mapToGlobal](https://doc.qt.io/archives/qt-4.8/qwidget.html#mapToGlobal)() if the widget has no parent.

### Platform and version information

- wxWidgets version  you use: latest [HEAD f8ce99bf66d640ef8573bdcd4cc44ffe2c01084b]
- wxWidgets port  you use: wxQt (5.9.5)
- OS  and its version: Ubuntu 18.04

**Comment by vadz** [comment]
Could this be due to 1px wide border around `wxPanel`?

**Comment by AliKet** [comment]
> Could this be due to 1px wide border around `wxPanel`?

I'm not sure but this PR #22969 also solves all the above.

**Comment by vadz** [comment]
Closing this as it should be fixed by the PR above, which was merged.
