### ISSUE TITLE
DrawText does not display UTF8 characters correctly

### ISSUE THREAD

**Issue by SSTBert** [wxWidgets/wxWidgets#22970]
### Description

When trying to display the degree symbol on a dialog it is not being shown correctly with UTF8 encoded strings. Debugging the problem points to the DrawText function not interpreting the string as UTF8 when using the wxDC to display the data. When using the wxGCDC the output is correct. 

The app is built with the following:
Building with these flags: stdc++17, utf-8
Build with a manifest file to start app in UTF8 encoding.

Options that have been tried:
- Setting the font encoding to UTF8 prompts the user when opening the dialog to select a font that is UTF8 compatible but still makes no change to the problem. Creating a compatible font also does not work.

Code snippet:
```
	wxPaintDC paintDC(this);
	wxClientDC dc(m_panel);

	dc.SetFont(*wxNORMAL_FONT);
	dc.SetTextForeground(*wxBLACK);
	dc.SetTextBackground(wxTransparentColor);

	dc.DrawText("15.0 °C", 5, 5);

	wxGCDC gc(dc);
	gc.SetFont(*wxNORMAL_FONT);
	gc.SetTextForeground(*wxBLACK);
	gc.SetTextBackground(wxTransparentColor);

	gc.DrawText("15.0 °C", 5, 30);
```
![image](https://user-images.githubusercontent.com/118352495/202194198-88320018-8d71-498b-a42f-a631657fef03.png)

### Platform and version information

- wxWidgets version: 3.2.1
- wxWidgets port: wxMSW
- OS: Windows 10 Pro version 21H2

### Build command
nmake f makefile.vc BUILD=debug SHARED=0 UNICODE=0 USE_GDIPLUS=1 TARGET_CPU=X86 CXXFLAGS=stdc++17 utf-8

[wxTestApp.zip](https://github.com/wxWidgets/wxWidgets/files/10022195/wxTestApp.zip)

**Comment by vadz** [comment]
I don't know what's going on with the your application and the build settings (some slashes seem to have disappeared from your description), but the following works fine:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 501caf9096..ddf26d7a4d 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -26,6 +26,7 @@
     #include "wx/wx.h"
 #endif
 
+#include "wx/dcgraph.h"
 // ----------------------------------------------------------------------------
 // resources
 // ----------------------------------------------------------------------------
@@ -175,6 +176,27 @@ bool MyApp::OnInit()
     CreateStatusBar(2);
     SetStatusText("Welcome to wxWidgets!");
 #endif // wxUSE_STATUSBAR
+
+    auto p = new wxPanel(this);
+
+    p->Bind(wxEVT_PAINT, [p](wxPaintEvent&) {
+        wxPaintDC dc(p);
+
+        dc.Clear();
+        dc.SetFont(*wxNORMAL_FONT);
+        dc.SetTextForeground(*wxBLACK);
+        dc.SetTextBackground(wxTransparentColor);
+
+        dc.DrawText(wxString::FromUTF8("15.0 °C"), 5, 5);
+
+        wxGCDC gc(dc);
+
+        gc.SetFont(*wxNORMAL_FONT);
+        gc.SetTextForeground(*wxBLACK);
+        gc.SetTextBackground(wxTransparentColor);
+
+        gc.DrawText(wxString::FromUTF8("15.0 °C"), 5, 30);
+    });
 }
 
 
```

without any special build settings. Without `wxString::FromUTF8()` it doesn't work for me but then I don't use `/utf-8` option.

If you still think there is a problem with wxWidgets itself and not your build options, please reproduce the problem in the sample by providing a patch similar to the following.
