### ISSUE TITLE
Ambiguous overload error when using /wx/filename.h, depends on wxSIZE_T_IS_UINT.

### ISSUE THREAD

**Issue by carlo-bramini** [wxWidgets/wxWidgets#23004]
When using `wx/filename.h`, I'm constantly getting this error:

```
/usr/i686-w64-mingw32/sys-root/mingw/include/wx-3.2/wx/filename.h: In static member function 'static wxUniChar wxFileName::GetPathSeparator(wxPathFormat)':
/usr/i686-w64-mingw32/sys-root/mingw/include/wx-3.2/wx/filename.h:493:43: error: ambiguous overload for 'operator[]' (operand types are 'wxString' and 'unsigned int')
  493 |         { return GetPathSeparators(format)[0u]; }
      |                                           ^
```

The error seems to be related to the definition of `wxSIZE_T_IS_UINT` inside `platform.h`, which causes this function:

https://github.com/wxWidgets/wxWidgets/blob/58f5a885ec20ea518f94e16d2fcff6d0b8decd17/include/wx/string.h#L213

to be not declared.
This error happens when using i686-mingw-w64 compiler, but it is not printed when using x86_64-mingw-w64 compiler, which is what I expected from the definitions inside `platform.h`.

I had posted a patch for fixing this issue:

https://github.com/wxWidgets/wxWidgets/pull/23000

but it has been rejected, so the problem still exists in the current MASTER.
Another solution can be to provide this operator (and perhaps other types) indipendently by the presence of `wxSIZE_T_IS_UINT`, but actually the reasons because this conditional compilation exists are unknown to me.

**Comment by vadz** [comment]
What is your compiler version and which compilation flags do you use? It looks like `size_t` is not defined as `unsigned int` but this is unexpected, all MinGW versions I know about do have `size_t == unsigned`.

**Comment by carlo-bramini** [comment]
> What is your compiler version and which compilation flags do you use? It looks like `size_t` is not defined as `unsigned int` but this is unexpected, all MinGW versions I know about do have `size_t == unsigned`.

I'm using official MinGW-w64 cross compilers provided by CYGWIN.
However, into `platform.h` there is this line:

https://github.com/wxWidgets/wxWidgets/blob/fc9e1881165ba9d7c0ffa996666cbd2df1f7ded2/include/wx/platform.h#L299

The `!defined(__WIN64__)` is the tricky part, because it makes the difference between x86_64 and i686 compilers, which doesn't seem to happen elsewhere.
However, in my opinion, here:

https://github.com/wxWidgets/wxWidgets/blob/fc9e1881165ba9d7c0ffa996666cbd2df1f7ded2/include/wx/filename.h#L493

the second argument is not a type but a literal. It's different.
And, as the the compiler says in its error message, the `0u` is recognized as `unsigned int` which is not the same thing of `size_t` even if they have same size and same sign. 
This is the cause of the problem that I'm getting.
Besides changing `0u` to `0` for recognizing the literal as `int`, the best solution may be to add for completeness two extra operators using `unsigned int` and `unsigned long`, indipendently by the declaration of `wxSIZE_T_IS_UINT`, but I don't know exactly why this has been done in this way then compiling for Windows.
Perhaps, this is an inheritance for supporting ancient version of W32API, when `size_t` was defined as a macro rather than using a `typedef`. In that case, this line:

https://github.com/wxWidgets/wxWidgets/blob/58f5a885ec20ea518f94e16d2fcff6d0b8decd17/include/wx/string.h#L209

and this line:

https://github.com/wxWidgets/wxWidgets/blob/58f5a885ec20ea518f94e16d2fcff6d0b8decd17/include/wx/string.h#L213

were the same thing and they will cause an error at compile time.
If this is the origin of the choice, and you still would like to support such deprecated stuff, probably it would be worth to evaluate if `size_t` is a macro or a type at configure time, I think.

However, using an `int` literal into `GetPathSeparator()` instead of an `unsigned int` also solves this issue at the root.

**Comment by vadz** [comment]
`__WIN64__` shouldn't be defined in Win32 build that you use. If it is defined for you, you need to track down where does it come from and fix this.

For the rest, please try doing what you suggest and you will see that you can't overload a function on `size_t`/`unsigned int`. Contrary to what you write, they _are_ the same type.
