### ISSUE TITLE
wxTaskBarIcon GetPopupMenu not called before CreatePopupMenu on macOS

### ISSUE THREAD

**Issue by williamln** [wxWidgets/wxWidgets#23008]
The [documentation for wxTaskBarIcon](https://docs.wxwidgets.org/3.2/classwx_task_bar_icon.html) states that `CreatePopupMenu()` is "Called by the library when the user requests popup menu if `GetPopupMenu()` is not overridden." And regarding `GetPopupMenu()` states that "On Windows and Unix platforms this happens when the user right-clicks the icon, so overriding this method is the simplest way to implement the standard behaviour of showing a menu when the taskbar icon is clicked." But the behaviour is ambiguous for macOS.

I would expect the `GetPopupMenu()` to be called before `CreatePopupMenu()` on macOS because there appears to be no reason against this behaviour, other than the fact that this is not explicitly stated in the documentation. If this is not the intended behaviour I would expect that to be stated, preferably along with a reason, in the documentation.

The behaviour I observe is that `GetPopupMenu()` is _only_ called before `CreatePopupMenu()` if the `wxTaskBarIcon` is constructed with `wxTBI_DOCK`, i.e when the menu is spawned from the dock icon as opposed to the task bar icon. If the `wxTaskBarIcon` is constructed with `wxTBI_CUSTOM_STATUSITEM` or `wxTBI_DEFAULT_TYPE` the `GetPopupMenu()` method is never invoked.

One can clearly see [in the code here](https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/cocoa/taskbar.mm#L274) that `GetPopupMenu()` is called before `CreatePopupMenu()`, however this is _only_ the behaviour, as described above, for `wxTBI_DOCK`. [This is the code](https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/cocoa/taskbar.mm#L337) that is invoked when the task bar object is `wxTBI_CUSTOM_STATUSITEM` or `wxTBI_DEFAULT_TYPE`, where it's clear that `GetPopupMenu()` is _not_ called before `CreatePopupMenu()`.

I observe this behaviour in versions 3.1.6 and 3.2 and specifically on macOS. I'd be happy to attempt a PR to solve this myself but I'm unsure whether this is a problem with the code or documentation.

**Comment by vadz** [comment]
Thanks for reporting this!

The code here

https://github.com/wxWidgets/wxWidgets/blob/af3db51d71c91ff8b37c57d68e26fa1bf40c8ed0/src/osx/cocoa/taskbar.mm#L334-L343

is indeed wrong as it doesn't call `GetPopup()` first and should be fixed. If you could please make (and test) a PR doing this, it would be welcome, TIA!
