### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by cedricowen91** [wxWidgets/wxWidgets#23009]
codeblocks-20.03:

**I've just seen that I have posted to wrong project! Abject apologies - I should have sent this to Codeblocks.
Please feel free to delete!**

After successfully running  ./configure --with-contrib-plugins=all, make produced the following error:

main.cpp: In member function ‘bool MainFrame::OnDropFiles(wxCoord, wxCoord, const wxArrayString&)’:
main.cpp:2682:22: error: ‘wxPaintEvent::wxPaintEvent(wxWindowBase*)’ is private within this context
         wxPaintEvent e;
                      ^
In file included from /usr/include/wx-3.1/wx/wx.h:24:0,
                 from /usr/include/wx-3.1/wx/wxprec.h:42,
                 from ./sdk_common.h:24,
                 from ./sdk_precomp.h:13,
                 from ./sdk.h:17:
/usr/include/wx-3.1/wx/event.h:2396:14: note: declared private here
     explicit wxPaintEvent(wxWindowBase* window = NULL);
              ^~~~~~~~~~~~
make[3]: *** [Makefile:795: main.o] Error 1

I will see if I can change the visibility later and try again.

**Comment by vadz** [comment]
This is definitely not a wx bug and C::B should not use `wxPaintEvent` ctor but call `wxWindow::Refresh()` instead.
