### ISSUE TITLE
Qt License (question)

### ISSUE THREAD

**Issue by top-master** [wxWidgets/wxWidgets#23011]
Some wxWidgets's sources seem to use Qt.

Is Qt now under wxWidgets's license-exception as well,
or does that force us to use one of Qt's license options (LGPLv3 or GPLv3 or Commercial) ?

**Comment by vadz** [comment]
Nothing wxWidgets does can possibly affect Qt licence. wxQt is under wxWidgets licence, but you still have to respect Qt licence too when using it, of course.

Please post future questions to the mailing lists/forum/etc.
