### ISSUE TITLE
Unable to set `Ctrl-TAB` has menu item keyboard shortcut (when inside a wxMenuBar)

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23014]
Adding a menu item to a menu in the menu bar with the shortcut set to `Ctrl-TAB` is not working.
i.e. the menu item is there, but the keyboard shortcut is empty (non existing)

Setting it to anything else other than `Ctrl-TAB` works.

To Reproduce:

- Apply this patch to the `minimal` sample:
```diff
--- ../../../samples/minimal/minimal.cpp.orig   2022-12-04 01:16:09.509232923 +0200
+++ ../../../samples/minimal/minimal.cpp        2022-12-04 01:15:51.899232949 +0200
@@ -150,7 +150,7 @@

     // the "About" item should be in the help menu
     wxMenu *helpMenu = new wxMenu;
-    helpMenu->Append(Minimal_About, "&About\tF1", "Show about dialog");
+    helpMenu->Append(Minimal_About, "&About\tCtrl-TAB", "Show about dialog");

     fileMenu->Append(Minimal_Quit, "E&xit\tAlt-X", "Quit this program");
```
- Compile and run the `minimal` executable
- Go to the `Help` menu and observe that there is no shortcut for the `About` menu item

---

+ GTK version: `3.24.20`
+ X11
+ WSL2, Ubuntu 20.04
+ wxWidgets 3.2.0, self compiled with `../configure --disable-debug_flag --with-gtk=3`

Thanks,
Eran

**Comment by vadz** [comment]
You shouldn't disable debugging completely when developing/testing -- if you hadn't, you would have seen a debug message saying that Tab is not supported as an accelerator in wxGTK because of a GTK limitation. And unfortunately I don't think there is anything we can do about it, it's just GTK policy to not allow using Tab (and quite a few other keys) for any accelerators.

**Comment by eranif** [comment]
FYI: removing the menu entry with this accelerator, fixes the issue. i.e. I am able to set `Ctrl-TAB` as accelerator on GTK (using `wxAcceleratorTable`). It only fails to work when a `wxMenu` is involved

**Comment by vadz** [comment]
Yes, but you can't show it in the menu. You can see in GTK sources that they explicitly forbid using TAB for the accelerators there.
