### ISSUE TITLE
Reduce number of "skipping test" messages in the MSW GUI tests

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23020]
@a-wi Would you know of some nice way to avoid seeing so many
```
Skipping test because RTL layout direction is not supported on this platform
```
messages when running the GUI tests? They completely swamp all the rest of the output, making it difficult to find anything else in it.

Personally I'd rather avoid these messages entirely than having so many of them, but I guess ideal would be to give this message only once, what do you think?

**Comment by a-wi** [comment]
I will try to do something with this.
