### ISSUE TITLE
Maximum Length is not being respected

### ISSUE THREAD

**Issue by todinaca** [wxWidgets/wxWidgets#23033]
In the latest version of wxWidgets, please look at line 2040 of editors.cpp - the value returned from GetMaxLength() is passed in parameter 5.

 return GenerateEditorTextCtrl(pos,sz,text,but,property->GetMaxLength());

GenerateEditorTextCtrl has the following signature, though, defined on line 1876 of editors.cpp
wxWindow* wxPropertyGrid::GenerateEditorTextCtrl( const wxPoint& pos,
                                                  const wxSize& sz,
                                                  const wxString& value,
                                                  wxWindow* secondary,
                                                  int extraStyle,
                                                  int maxLen,
                                                  unsigned int forColumn )

Note the maxLen is parameter 6, which is a mismatch in parameters.  Thus, the value for the maximum length in this case is being applied to the extra style.  

Thanks

**Comment by vadz** [comment]
Should this be backported to 3.2 too?
