### ISSUE TITLE
Crash / _XError Linux Mint 21

### ISSUE THREAD

**Issue by mxwendler** [wxWidgets/wxWidgets#23043]
Hi all,

thank you for creating and maintaining this great library! I have a crash in my application with the following call stack:

```
_XError (@_XError:3)
___lldb_unnamed_symbol1644 (@___lldb_unnamed_symbol1644:36)
___lldb_unnamed_symbol1645 (@___lldb_unnamed_symbol1645:37)
_XEventsQueued (@_XEventsQueued:41)
_XGetRequest (@_XGetRequest:29)
XTranslateCoordinates (@XTranslateCoordinates:30)
___lldb_unnamed_symbol3172 (@___lldb_unnamed_symbol3172:42)
gdk_window_get_origin (@gdk_window_get_origin:39)
wxWindow::DoClientToScreen(int*, int*) const (@wxWindow::DoClientToScreen(int*, int*) const:32)
SendSetCursorEvent (@SendSetCursorEvent:27)
gtk_window_motion_notify_callback (@gtk_window_motion_notify_callback:153)
___lldb_unnamed_symbol18621 (@___lldb_unnamed_symbol18621:33)
g_closure_invoke (@g_closure_invoke:111)
___lldb_unnamed_symbol1078 (@___lldb_unnamed_symbol1078:584)
g_signal_emit_valist (@g_signal_emit_valist:644)
g_signal_emit (@g_signal_emit:29)
___lldb_unnamed_symbol18073 (@___lldb_unnamed_symbol18073:121)
___lldb_unnamed_symbol15066 (@___lldb_unnamed_symbol15066:106)
gtk_main_do_event (@gtk_main_do_event:831)
___lldb_unnamed_symbol2569 (@___lldb_unnamed_symbol2569:35)
___lldb_unnamed_symbol3018 (@___lldb_unnamed_symbol3018:14)
g_main_context_dispatch (@g_main_context_dispatch:159)
___lldb_unnamed_symbol2709 (@___lldb_unnamed_symbol2709:136)
g_main_loop_run (@g_main_loop_run:36)
gtk_main (@gtk_main:41)
wxGUIEventLoop::DoRun() (@wxGUIEventLoop::DoRun():14)
wxEventLoopBase::Run() (@wxEventLoopBase::Run():18)
wxAppConsoleBase::MainLoop() (@wxAppConsoleBase::MainLoop():35)
wxEntry(int&, wchar_t**) (@wxEntry(int&, wchar_t**):23)
main (/media/veracrypt1/dc/tec/mxw_repo/MXwendler_01.cpp:31)
__libc_start_call_main (@__libc_start_call_main:29)
__libc_start_main_impl (@__libc_start_main@@GLIBC_2.34:43)
_start (@_start:15) 
```

It happens when i drag from inside of the frame across the border. But there is none of my code involved at a first look. Can i do something to help tracking this down?

Best regards

**Comment by vadz** [comment]
The most likely reason for a crash like this would be using an invalid (e.g. already destroyed) window, but it's really difficult to say anything more without having any way of reproducing the problem. Please try making a minimal patch to one of the samples reproducing the problem (see https://www.wxwidgets.org/develop/how-to-submit-patches/ if you hadn't done this before).

You should also try setting `GDK_SYNCHRONIZE=1` in the environment before running the program (under debugger) as this can give more/better information about the problem.

**Comment by mxwendler** [comment]
Thank you for the prompt reply - actually the problems disappeared after proper OpenGL context setting, so from our side we can close this issue. Thank you also for the tip with GDK_SYNCHRONIZE=1, this will result in a much more useful stack trace.
