### ISSUE TITLE
Though  SHARED=1  was set ，still built out lib****.a.

### ISSUE THREAD

**Issue by Innocence** [wxWidgets/wxWidgets#23051]
Pretty sure SHARED=1 was set,  same number of  librarys  were built out (**lib******.a  and **wxmsw32u_xxxxx_gcc_custom.dll**)  
**mingw32-make -j4 -f makefile.gcc SHARED=1 UNICODE=1 BUILD=release**
And they are in WX\lib\gcc_dll
![2022-12-19_165430](https://user-images.githubusercontent.com/1294867/208387000-edd3be6f-5827-4952-9810-bbb2d95df3ab.png)

### Platform and version information

- wxWidgets version  you are building:         **3.2.1**
- wxWidgets port  you are building:   **wxMSW**
- OS  and its version:   **Windows 10**
- Compiler  being used:    **Mingw-w64-ucrt-x86_64    gcc  12.2**

**Comment by asmwarrior** [comment]
So, what is the expect library name you want to get?

Maybe, you want

~~~~
libwxbase32u.dll.a
~~~~

?

**Comment by PBfordev** [comment]
The .a libraries are the import libraries for the DLLs. What exactly is the problem here?

BTW, library naming scheme is described at https://github.com/wxWidgets/wxWidgets/blob/master/docs/contributing/about-platform-toolkit-and-library-names.md

**Comment by Innocence** [comment]
> 

Apparently I assumed when I set SHARED=1,there would be only ***.dll**  exported out. 
Awkward,  I'm new to this field. Thanks a lot anyway.
@PBfordev @asmwarrior
