### ISSUE TITLE
Cannot use wxGenericHyperlinkCtrl  unless wx/hyperlink.h #included before wx/generic/hyperlink.h

### ISSUE THREAD

**Issue by Randalphwa** [wxWidgets/wxWidgets#23060]
### Description

The file `wx/generic/hyperlink.h` has the following:

```c++
class WXDLLIMPEXP_ADV wxGenericHyperlinkCtrl : public wxHyperlinkCtrlBase
```

However, it does not include `wx/hyperlink.h` so you get an error if you just include `wx/generic/hyperlink.h` (missing `wxHyperlinkCtrlBase`). The obvious solution, however, has a problem:

```c++
#include <wx/hyperlink.h>
#include <wx/generic/hyperlink.h>
```

The problem is those two files are not in alphabetical order -- and a dev that uses something like `clang-format` may well find the order reversed, and you can no longer compile the program again due to the missing `wxHyperlinkCtrlBase` class.

Adding `#include <wx/hyperlink.h>` to the top of `wx/generic/hyperlink.h` should resolve the problem, but I'm not sure if there are other ramifications to adding the #include?

### Platform and version information

- wxWidgets version  you use: 3.3.0

**Comment by vadz** [comment]
We can't do this as easily as that because the generic header can be included from wx/hyperlink.h too. Of course, it could be done by predefining some symbol and then checking for it, but I'm not sure if it's really worth it.

clang-format understands header groups, so I'd just put a blank line between these headers to avoid the problem and, more generally, include all wx/foo.h before including wx/something/bar.h.

**Comment by Randalphwa** [comment]
Like all designers, my tool writes out a list of header files that users will need for the controls they have specified, and the user cannot modify that list since it gets regenerated every time they make a change. That said, I believe I'm the only designer that actually generates code for wxGenericHyperlinkCtrl (it's required to remove the underline and change the link colors on Windows), so it only affects my users. I already write just those two files out of order -- I was just hoping that someday I could write those two in alphabetical order like the rest of the header files I generate and avoid the potential bug report when some observant user reports a bug to me about them being out of order. It's not a big deal, so I'm closing the issue -- and if I do get a bug report on my tool, I'll just link it to this one... :-)

Just in case this ever comes up again, hyperlink.h already has a symbol indicating if it has been #included or not, so presumably adding

```c++
#if !defined(_WX_HYPERLINK_H_)
    #include "wx/hyperlink.h"
#endif
```

to wx/generic/hyperlink.h would prevent any recursive #including.

**Comment by vadz** [comment]
The trouble is that if we support including this one directly, we should also support including all the other generic headers directly too and we don't, currently. So I'd rather not create a precedent by allowing doing it for this one only...
