### ISSUE TITLE
Ubuntu 22/XOrg/GTK3 wxPanel repaint issues if happened together with frame title change

### ISSUE THREAD

**Issue by elfmz** [wxWidgets/wxWidgets#23069]
Hi, i have long standing bug with randomly missing repaints. The bug was first noted when using Ubuntu 22 (XOrg) with xrdp server however later it was confirmed to be reproduced with simple forwarded RDP and even on local system. I was able to create minimal reproduction snipped it can be found in wxtest.cpp in attached archive. I also created similar functionality code with plain GTK (also can be found in attached archive) and problem NOT happen there, so highly suspecting now WX/GTK3 causing this. 
Key factor that causing problem to happen - is that frame's title changed coupled in time with window Refresh/Update. Removing title change completely eliminates reproduction. Playing with Refresh/Update also reduces reproduction but it still happen form time to time. Best i was able to achieve is to queue additional repaint after any title change using half-second timer, buts its not good for performance and looks badly.
Attached snippets:
[bug.zip](https://github.com/wxWidgets/wxWidgets/files/10295175/bug.zip)
..compile, run and press any key - each pressing toggles amount of drawn text lines between one and many and title respectively. Problem visible as sometimes lines amount not changed by keypress, but title changed. However in such situation attempt to drag window or just click it with mouse triggers missing repaint.
Related issues in other projects:
https://github.com/elfmz/far2l/issues/1453
https://github.com/elfmz/far2l/issues/1303
https://github.com/neutrinolabs/xrdp/issues/2361

**Comment by elfmz** [comment]
The bug happens in default ubuntu's desktop and XOrg (so not in Wayland).
Removing Update indeed reduces reproduction. It actually eliminates reproduction when running locally but still it happens over xrdp session. I've already tried many things. Empirically found that SetBackgroundStyle wxBG_STYLE_PAINT and SetDoubleBuffer(false) looks to eliminate reproduction both in local and xrdp session in real app, but its still doesn't cure  completely attached minimal test app.

**Comment by vadz** [comment]
How many tests do you typically need to reproduce this? I couldn't do it locally (Debian Bookworm) and I'm not sure how to set up xrdp.

BTW, even though it probably doesn't matter under GTK 3, doing nothing in `wxEVT_ERASE_BACKGROUND` handler and not erasing the background in `wxEVT_PAINT` one is wrong, you're supposed to do it at least one of these places (or use a different background style).

**Comment by elfmz** [comment]
In xrdp - 50% keypresses causing mispaint, local session - usually ten presses more than enough to see at least one missing repaint.
Note that reproduction is symmetrical in terms of one/many chars not printed. Sometimes only one line printed while many expected and sometimes many printed when only one expected. Missing background erasing would not explain missing lines. Also in the app where bug was noticed initially background is 'erased' by filling area before printing stuff.

**Comment by elfmz** [comment]
Actually my impression that this bug is caused by some race condition in XOrg but not WX/GTK but i cannot prove this by test apps.. May be wx doing something special that makes X to misbehave..

**Comment by vadz** [comment]
FWIW I've tried using it with a remote X server (not the same thing as RDP, but I thought that this could be related to latency) and couldn't reproduce it neither.

It does seem very weird that we are not getting paint events, I don't see how could they be "lost". If you'd like to debug this further, I'd start by adding some `wxLogTrace()` calls to `wxWindow::GTKSendPaintEvents()` to see if it's getting called as expected (you can set `WXTRACE=foo` to enable `wxLogTrace("foo", ...)` calls).

**Comment by elfmz** [comment]
The trick that paint events are not lost, they're arrived, but not 'displayed'. The weird thing that when i click or sometimes even move mouse - then correct content being displayed _without_ getting OnPaint - so it displayed by itself without getting OnPaint event.
I'll try to capture video

**Comment by elfmz** [comment]
here it is
https://user-images.githubusercontent.com/20957349/209393561-85f1e578-613d-49a6-8a41-52e026a378aa.mp4

**Comment by vadz** [comment]
I get "can't play the video because the file is corrupt" message here, but in any case I don't think I'm going to have any superhuman insights just from watching a video, sorry...

**Comment by unxed** [comment]
Transcoded video to WebM, maybe this one will open okay: [out.webm](https://user-images.githubusercontent.com/1151423/209433190-82963386-bcdb-4dc5-8667-959d5ba009d9.webm)

**Comment by vadz** [comment]
Thanks, I can see the video now but I still have no idea what's going on. My only idea is to try adding more trace messages to wxGTK to see what happens (and what doesn't) but right now I just don't understand how can this happen, sorry :-(

**Comment by elfmz** [comment]
After some hustling wit plain X11 test app to achieve similar timings of events processing and similar events count i've finally got reproduction there. That means its not wx, nor GTK to blame. Likely something wrong with that XWayland layer used in that ubuntu instead of normal XOrg. It looks like that when title being updated together with other window area - then title update causes compositing manager (or window manager?) to 'forget' to copy content of window from offscreen surface to screen but it does then whenever later window being dragged by mouse (and this doesnt cause any repaint event to arrive to client at all).

**Comment by oneeyeman1** [comment]
@elfmz ,
You can try to report this as a bug in Wayland and see if its a generic one or Ubuntu-specific...

**Comment by elfmz** [comment]
Created bug in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/xwayland/+bug/2002456

**Comment by vadz** [comment]
Thanks for following up on this!
