### ISSUE TITLE
wxRichToolTip broken by the use of `WS_EX_COMPOSITED` too

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23076]
Using "Dialogs > Rich tip dialog..." menu of the dialogs sample and showing the tooltip for the button there shows black background now. Setting `wx_msw_window_no_composited=1` fixes this, so it's due to `WS_EX_COMPOSITED` too.

**Comment by AliKet** [comment]
Cannot reproduce under my : 
Windows 10 Professionnel (Build 19044.2364)
Windows Feature Experience Pack 120.2212.4190.0

Am I missing something ?

**Comment by PBfordev** [comment]
I cannot reproduce this either, tried Win10 and VirtualBox VM Win11. Both types of backgrounds are displayed the same as in 3.2.1.

**Comment by vadz** [comment]
I hadn't realized it, but it's only a problem under Windows 7, it indeed (still) works correctly under 10.

**Comment by PBfordev** [comment]
FWIW, I cannot reproduce in a VirtualBox VM Windows 7 (where `wxGenericNotificationMessage` issue can be observed).
