### ISSUE TITLE
wxGenericNotificationMessage on Windows broken by the use of `WS_EX_COMPOSITED`

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23078]
When using `wxGenericMessage` on Windows 10, the message window is briefly (under 1 sec) displayed correctly, but then all its parts (icon, title, message, and close button) are displayed just as black rectangles.
![wx-generic-user-notification](https://user-images.githubusercontent.com/12495521/209475329-99ed744e-bd9b-40bf-ae34-71d2fcc3ca86.png)
Just before the message disappears, it is again very briefly displayed properly. Setting system environment variable `wx_msw_window_no_composited` to `1` makes the issue disappear, so it appears to be caused by `WS_EX_COMPOSITED`.

To Reproduce:
1. Run dialogs sample.
2. Click on menu Dialogs/User notifications/User Notification.
3. In the User Notification Test Dialog check "Use generic notifications".
4. Press Show button.
5. See error.

### Platform and version information

- wxWidgets version: GIT master
- wxWidgets port you use: wxMSW
- OS and its version: Windows 10 21H2, OS build 19045.2364, Windows Feature Experience Pack 120.2212.4190.0
- Other: light mode, DPI scaling 125% on the primary (2560x1440) and 100% on the secondary (1680x1050) display.

**Comment by vadz** [comment]
Thanks, I can indeed see it too.

We probably need to turn off `WS_EX_COMPOSITED` for the popup windows, I'll try doing this soon.

**Comment by PBfordev** [comment]
Closing as as completed in https://github.com/wxWidgets/wxWidgets/commit/b4dd25ee3f6033126030821d7e8d30d4076d23ac, the issue was for some reason not closed automatically.
