### ISSUE TITLE
[wxMSW] When dark mode is forced, wxNotebook selected tab seems incomplete

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23089]
I am using the latest wxMSW dark support.
When dark mode is forced, the `wxNotebook` selected tab looks "truncated"

See screenshots below (same dialog, in dark and light themes)

Dark notebook (BAD):
![nb-dark](https://user-images.githubusercontent.com/3677711/209792543-de4e6818-f66d-477f-96c6-a066573b585f.png)

For comparison, this is how it looks like with "Light" notebook (OK):
![nb-light](https://user-images.githubusercontent.com/3677711/209792546-04da1da9-d953-4bac-80cf-9d366c3e2a8c.png)

Windows: 10
Compiler: clang 15.0.2

**Comment by vadz** [comment]
This is definitely not how it's supposed to look, the top line is missing (clipped?) somehow.

Does the notebook sample look the same on your system or is it specific to this notebook/this dialog? In the latter case, can you please show how do you create it? TIA!

**Comment by eranif** [comment]
All the notebooks in my code (with dark mode is enabled) are truncated

This is also true for the samples. Here is the "widgets" sample (without any code modification from my side):
![nb-samples](https://user-images.githubusercontent.com/3677711/209853907-1bbfe16d-24ca-4c33-87d3-28218dd210e6.png)

**Comment by vadz** [comment]
Notebook metrics must have changed :-( What is your full Windows version (mine is 10.0.19043.2251)? And, if you can do it under debugger or by inserting `wxLogDebug()` in the code, could you please check what does `GetTabRect()` return for you in `wxNotebook::MSWNotebookPaint()`? Normally it should use offset of 2,2 for the first tab, but I suspect it's 1 or even 0 for the vertical component in your case, is it?

**Comment by eranif** [comment]
My Windows version `Version 10.0.19044.2364`, I will debug it

**Comment by eranif** [comment]
From the debugger:

```lldb
Process 10160 stopped
* thread #1, stop reason = step over
    frame #0: 0x00007ff8da2820c4 wxmsw330ud_clang_x64_custom.dll`wxNotebook::GetTabRect(this=0x0000017b2277d5e0, page=0) const at notebook.cpp:541:5
   538          RECT rect;
   539          if (TabCtrl_GetItemRect(GetHwnd(), page, &rect))
   540              r = wxRectFromRECT(rect);
-> 541      }
   542
   543      return r;
   544  }
(lldb) p page
(size_t) $3 = 0
(lldb) p r
(wxRect) $4 = (x = 2, y = 2, width = 133, height = 35)
```

**Comment by vadz** [comment]
Wait, I think I might know what's going on: do you use high DPI? If so, it looks like this 2 is not actually scaled by it at all, i.e. the `FromDIP()` in `selectedOffset` definition is wrong and removing it should fix it.

Or am I totally off the mark again?

**Comment by eranif** [comment]
Yes, I have DPI (big screen). I am actually trying to change the mentioned variable `selectedOffset` from `win->FromDIP(2)`
to use `win->FromDIP(1)` (it will still be bigger, but "less")

**Comment by vadz** [comment]
Yes, in many cases Windows doesn't actually apply DPI scaling to margins/indents, and this seems to be another one of those, so we should simply remove `FromDIP()` entirely. I should have tested this myself in high DPI, sorry...

**Comment by eranif** [comment]
I can confirm, this fixes the issue

![nb](https://user-images.githubusercontent.com/3677711/209876690-57012eaf-3e26-4d85-8bc6-e33c4dfce389.png)

**Comment by vadz** [comment]
Thanks, will push this fix soon.
