### ISSUE TITLE
wxEntry(): Memory leak of 226 bytes in CommandLineToArgv(..)

### ISSUE THREAD

**Issue by Sridhar-k-k** [wxWidgets/wxWidgets#23081]
### Description
Describe the bug:
Found a memory leak of 226 bytes at CommandLineToArgv(..) in wxEntry() when IBM Purift is run on the product.
To demonstrate the memory leak, I have create a sample test dialog program.
```
[W] MLK: Memory leak of 226 bytes from 1 block allocated in CommandLineToArgvW [SHELL32.DLL]
        Distribution of leaked blocks
        Allocation location
            LocalAlloc     [c:\Windows\SysWOW64\KERNELBASE.DLL]
            CommandLineToArgvW [C:\Windows\SysWOW64\SHELL32.DLL]
            ?A0x3bc8119c::pthread_signon_main_dialog(void *) [u:\secure-client\ui\signon\src\ui_main.cpp:191]
                        HANDLE h_signon_main_thread_cond = *(static_cast<HANDLE*>(event));
                        SetEvent(h_signon_main_thread_cond);
                        /* Run the app: */
             =>         wxEntry(hInstance, NULL, NULL, SW_SHOW);
                
                clean_exit:
                        wxEntryCleanup();
            endthreadex    [F:\dd\vctools\crt_bld\SELF_X86\crt\src\build\INTEL\dll_obj\threadex.obj]
            endthreadex    [F:\dd\vctools\crt_bld\SELF_X86\crt\src\build\INTEL\dll_obj\threadex.obj]
```

Expected vs observed behaviour:

We have a third party Java/MFC application which loads our dll library and call a function to show the dialog and it works as follows:

1. It initializes the wxwidgets in a separate thread which keeps running until the dialog/event loop is closed (as described in my_dll.cpp in samples in wxwidgets)
2. Shows the wxwidgets dialog.
3. Closes the thread when dialog is closed.

When the steps 1-3 are done only once per process, then I don't see any memory leak. However, if the steps 1-3 are done more than once, then a memory leak of 226 bytes is shown and it keep increasing x number of times it is run.

I suspect some CommandLineToArgs values passed to wxEntry() are not properly deallocated when event loop is closed. Hence, it is causing this memory leak.

Patch or snippet allowing to reproduce the problem:

Please find attached are two project files from sample folder which work as follows to reproduce the issue:
 1. CSTBsample_ui - This project contains files to generate the dll
 2. CSTtest - This project is a console project which load the CSTBsample_ui.dll and calls PromptForSampleDialog() multiple times to load the dll and dynamically call ShowSampleDialog() function in CSTBsample_ui.dll library.
 3. When the test.c code in CSTBtest is changed to call PromptForSampleDialog() more than once,  then the sample dialog is shown more than once. You need to press "ok" button each time to gracefully close the dialog each time. When the dialog is closed, the ExitEventLoop() is called to close the event loop and close the dialog.
 4. When the executable is run 10-20 times without close the executable, then you will see a spike in memory of 226 bytes each time as the memory allocated for command line arguments in wxEntry() are not cleared when exit event loop is called.

The wxwidgets project samples are found here: [wxWidget_Project_Samples.zip](https://github.com/wxWidgets/wxWidgets/files/10303459/wxWidget_Project_Samples.zip)

### Platform and version information

- wxWidgets version  you use: 3.1.7
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
I think I indeed see the leak and so I've created #23082 to fix it, please test it and report if you see any problems with it.

For the future submissions please notice that we don't have the resources for debugging your entire project. Please see [the instructions](https://www.wxwidgets.org/develop/how-to-report-issues/) for reporting issues and try to make a minimal reproducible test case as otherwise it risks being difficult to do anything about it (this particular case notwithstanding).

**Comment by Sridhar-k-k** [comment]
Thanks Vadz.

I run the memory leaks tests using 3.2.1 source with the patch and found the memory leak issue fixed.
