### ISSUE TITLE
wxDCClipper doesn't restore original clipping region in some circumstances

### ISSUE THREAD

**Issue by a-wi** [wxWidgets/wxWidgets#23083]
### Description
Original clipping region is not restored properly when `wxDC` coordinates are changed during `wxDCClipper` lifetime.
The issue can be reproduced with this patch to minimal sample:
```diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -63,6 +63,7 @@ public:
     // event handlers (these functions should _not_ be virtual)
     void OnQuit(wxCommandEvent& event);
     void OnAbout(wxCommandEvent& event);
+    void OnPaint(wxPaintEvent&);
 
 private:
     // any class wishing to process wxWidgets events must use this macro
@@ -175,10 +176,23 @@ MyFrame::MyFrame(const wxString& title)
     CreateStatusBar(2);
     SetStatusText("Welcome to wxWidgets!");
 #endif // wxUSE_STATUSBAR
+    Bind(wxEVT_PAINT, &MyFrame::OnPaint, this);
 }
 
 
 // event handlers
+void MyFrame::OnPaint(wxPaintEvent&)
+{
+    wxPaintDC dc(this);
+    dc.SetBackground(*wxYELLOW_BRUSH);
+    dc.Clear();
+    {
+        wxDCClipper clipper(dc, 10, 10, 50, 50);
+        dc.SetDeviceOrigin(30, 40);
+    }
+    dc.SetBackground(*wxBLUE_BRUSH);
+    dc.Clear();
+}
 
 void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
 {

```

Entire background should be filled with blue but instead we have this:
![wxDCClipper_invalid](https://user-images.githubusercontent.com/7330332/209644534-c0aa0fb2-8412-41b2-91e3-964c119be167.png)

### Platform and version information

- wxWidgets version: 3.3.0
- wxWidgets port: all

**Comment by paulcor** [comment]
`wxDCClipper` wasn't meant to restore any possible change you can make to a DC, and I don't think the documentation implies that it will. If you want to do that, I think it would be better to add something equivalent to `wxGraphicsContext::PushState()/PopState()`.

**Comment by a-wi** [comment]
I think `wxDCClipper` should always properly restore clipping region, regardless of what was done to `wxDC` in the meantime. Doc just says "Since 3.1.1 wxDCClipper restores the previously active clipping region when it is destroyed."
