### ISSUE TITLE
OS info provided by cmake config report can be misleading

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23086]
wxWidgets CMakefile provides a brief overview of build configuration, for example, this is output for `MinGW Makefiles` generator on Windows:
> Configured wxWidgets 3.3.0 for **Windows-10.0.19045**
>     Min OS Version required at runtime:                **Windows XP / Windows Server 2003 (x64 Edition)**
>     Which GUI toolkit should wxWidgets use?            msw  
>     Should wxWidgets be compiled into single library?  OFF
>     Should wxWidgets be linked as a shared library?    ON
>     Which wxWidgets API compatibility should be used?  3.2
> Configuring done

There are two Windows versions mentioned (10 and XP); however, neither is actually correct as AFAIK, the master supports Windows 7-11.

The first mention ("Configured for") is the target platform (`${CMAKE_SYSTEM}`) but it seems overly specific and AFAICT, unless cross-compiling, it is just the host platform.  IMO, here it should be just "Windows", if possible.

"Min OS Version required at runtime" is deduced like this
https://github.com/wxWidgets/wxWidgets/blob/1d3d0ae49693d59dc6b86a2128997df211d17675/build/cmake/main.cmake#L57-L75
I am not sure we can (should) actually reliably figure out the minimum required OS version like this, at least not on Windows where it is the core developers decision independent of the build system...

**Comment by MaartenBent** [comment]
I think the first line is supposed to be similar to configure, which for example has: `Configured wxWidgets 3.3.0 for 'x86_64-w64-mingw32'`.
I am fine with simplifying it. Using only `CMAKE_SYSTEM_NAME` in the first line, but adding the architecture (32/64 bit, arm?) to it. And removing the second line.

**Comment by PBfordev** [comment]
Resolved by 10d09ec2b2e60efde00ca06e23f8b6b64375900c.
