### ISSUE TITLE
[wxMSW] wxCollapsiblePane button does not support dark mode

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23096]
The button for `wxCollapsiblePane` does not use dark mode

@vadz  if you can point me to the correct location in the code, I might be able to fix this

![cp](https://user-images.githubusercontent.com/3677711/209881694-3433d6cc-4ad9-402e-9c39-bac9cd840dd0.png)

**Comment by vadz** [comment]
This is painted in `wxGenericCollapsibleHeaderCtrl::OnPaint()` which uses `wxRendererNative::DrawCollapseButton()` which, as all the other native renderer methods, doesn't work in dark mode :-(

We could try overriding `MSWShouldUseAutoDarkMode()` to return true in this class to just invert the colours, it might work not too badly for it. If not, we're going to have to delegate to `wxRendererGeneric` when using dark mode in this (and probably many other, but maybe not all, functions).

**Comment by eranif** [comment]
I just debugged this and it goes into `wxRendererXP::DrawCollapseButton` which in turn calls WinAPI:

```c++
        ::DrawThemeBackground
            (
            hTheme,
            GetHdcOf(dc.GetTempHDC()),
            TDLG_EXPANDOBUTTON,
            state,
            &r,
            nullptr
            );
```

so yes, delegating to the the generic one sounds like a good idea
I will look into this

**Comment by eranif** [comment]
1. I tried overriding `MSWShouldUseAutoDarkMode()` and returning `true`, however, the control did not draw the buttons at all
2. I used the generic version only for this control and it worked as expected, the [patch is attached][1]

Let me know what do you think

 [1]: https://github.com/wxWidgets/wxWidgets/files/10316910/collpane.patch

**Comment by eranif** [comment]
This is how it looks now:

![cp](https://user-images.githubusercontent.com/3677711/209885230-d476a93e-d3b5-4839-952a-804b4b31b1ad.png)

**Comment by vadz** [comment]
I think it would make more sense to do this in `wxRendererNative` itself, wouldn't it? I.e. I don't think we ever want to use the light collapsible button in the dark theme.

We could just always fall back to the generic version there but IMHO it looks a bit ugly under MSW and I think #23098 is better, even though it's not ideal neither. What do you think?

**Comment by eranif** [comment]
Yes, I agree that the generic looks a bit ugly. I did not have time to check this new code, but I would guess that it can't be worse than the generic version :)
