### ISSUE TITLE
[wxQt] Question about wxPalette

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#23099]
### Description

I see that `wxQt` port defines its own `wxPelette` class ( but without any actual implementation at all ?) instead of using the generic implementation as `wxGTK` port does.

I don't know the motivation behind this decision, but (unless there is an intention to provide a real implementation in the near future) I plan to remove this dummy implementation in favor of using the generic implementation like the `wxGTK` port, just for the `ImageTestCase` test to pass there.

Any objection to this decision ?

TIA!

**Comment by vadz** [comment]
Frankly, I don't think anybody cares about `wxPalette` nowadays, as 8bpp video modes are just not used any longer. So I'm sure using the generic implementation should be fine. But I suspect that so would be deprecating this class entirely...

**Comment by oneeyeman1** [comment]
@AliKet , why not adapt this: https://doc.qt.io/qt-6/qpalette.html?

**Comment by AliKet** [comment]
> @AliKet , why not adapt this: https://doc.qt.io/qt-6/qpalette.html?

Besides the lack of motivation, I just tested the image sample using the generic implementation and it seems to work correctly. so I don't see any advantage in adapting `QPalette` (which I'm not even sure would work at all), and just use the generic version (like `wxGTK`) under `wxQt` too.
