### ISSUE TITLE
[wxMSW] Dark Mode enabled: fix wxStaticLine drawing

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#23108]
When dark mode is enabled, the static line is using white colour which is, again, too shiny
This small patch fixes this:

```diff
diff --git a/src/msw/statline.cpp b/src/msw/statline.cpp
index 8e9ac28875..037edc0c91 100644
--- a/src/msw/statline.cpp
+++ b/src/msw/statline.cpp
@@ -28,6 +28,8 @@
     #include "wx/msw/missing.h"
 #endif

+#include "wx/msw/private/darkmode.h"
+
 // ============================================================================
 // implementation
 // ============================================================================
@@ -63,6 +65,10 @@ WXDWORD wxStaticLine::MSWGetStyle(long style, WXDWORD *exstyle) const
     msStyle |= SS_SUNKEN | SS_NOTIFY | WS_CLIPSIBLINGS;
     msStyle |= SS_GRAYRECT ;

+    if ( wxMSWDarkMode::IsActive() )
+    {
+        msStyle &= ~SS_SUNKEN;
+    }
     return msStyle ;
 }

```
It's not perfect, but it fixes the main problem

Before:
![static-line-white](https://user-images.githubusercontent.com/3677711/210185820-cfa9a733-e9df-43f9-a0ae-0d023ad62b10.png)

After:
![static-line-grey](https://user-images.githubusercontent.com/3677711/210185818-5eb499e7-cd07-44d2-88b8-e816858bb73c.png)

Patch:
[statline.patch](https://github.com/wxWidgets/wxWidgets/files/10329534/statline.patch)

**Comment by vadz** [comment]
Thanks, I agree that it looks better like this, so I've applied a slightly modified version of your patch.
