### ISSUE TITLE
wxIPV4address::Hostname(unsigned long) is too slow

### ISSUE THREAD

**Issue by SMMB-DEV** [wxWidgets/wxWidgets#23109]
### Description
I have a program with an FTP connection that checks certain folders for new files periodically. (**Not running on the main thread!**)

```
wxFTP ftp = new wxFTP;
//...
while (...)
{
    wxString dir = ...;
    if (ftp->ChDir(dir))
    {
        wxArrayString files;
        if (ftp->GetFilesList(files))
        {
            //...
        }
    }
}
```

I noticed that wxFTP::GetFilesList takes too long most of the time even with an empty directory (~1700ms - min ~100ms). Finally I narrowed it down to this section in the source code:

#### src/common/ftp.cpp:
```
wxSocketBase *wxFTP::GetPassivePort()
{
    //...

    // get the port number and address
    int a[6];
    wxString straddr(m_lastResult, addrStart + 1, addrEnd - (addrStart + 1));
    wxSscanf(straddr, wxT("%d,%d,%d,%d,%d,%d"),
             &a[2],&a[3],&a[4],&a[5],&a[0],&a[1]);

    wxUint32 hostaddr = (wxUint16)a[2] << 24 |
                        (wxUint16)a[3] << 16 |
                        (wxUint16)a[4] << 8 |
                        a[5];
    wxUint16 port = (wxUint16)(a[0] << 8 | a[1]);

    wxIPV4address addr;
    addr.Hostname(hostaddr);    //<-- this is taking too long
    addr.Service(port);

    //...
}
```

which is using `wxIPV4address::Hostname(unsigned long addr)` but if I replace it with `wxIPaddress::Hostname(const wxString& name)` it works fine and sets the hostname almost immediately.
```
addr.Hostname(wxString::Format("%hhu.%hhu.%hhu.%hhu", a[2], a[3], a[4], a[5]));
```

### Platform and version information
- wxWidgets version 3.2.1 (wxMSW)
- Windows 10 Version 10.0.19044 Build 19044

**Comment by SpareSimian** [comment]
First, I suggest reducing the issue title to "wxIPV4address(unsigned long addr) is slow".

The code that's slow is doing some kind of address-to-name lookup using Windows gethostbyaddr, possibly DNS. Your patch eliminates this lookup and tells the FTP code to use use the address without a lookup.

What is the network environment you're using this with? How is the address being converted to a hostname? A local hosts file? DNS? 

It's not clear to me why a hostname lookup is even happening in wxIPV4address::Hostname(unsigned long addr). I don't see any code that tries to use that name, once discovered. Let the client code do that lookup if desired. Maybe in OrigHostname(). I'd suggest always clearing the hostname and eliminating the lookup at line 866 in sockaddr.cpp.  I think this should work:

```
bool wxIPV4address::Hostname(unsigned long addr)
{
   m_origHostname.clear();
   return GetImpl().SetHostAddress(addr);
}
```

**Comment by vadz** [comment]
I agree with [the previous comment](https://github.com/wxWidgets/wxWidgets/issues/23109#issuecomment-1369223781) but I think we should fill `m_origHostname` with the quad-dot representation of the address instead of just leaving it empty. This would be fast and more useful.

If anybody feels like making the simple PR fixing this, please do.

**Comment by SMMB-DEV** [comment]
@SpareSimian
> What is the network environment you're using this with? How is the address being converted to a hostname? A local hosts file? DNS?

I was testing the program on my own computer. The FTP server is running on another computer on my LAN. I'm not sure what you mean by "How is the address being converted to a hostname?". I haven't done anything to change the default for that so however the OS handles that normally I guess.
