### ISSUE TITLE
`wxGLCanvas` can't be created with default attributes inside a VM

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23121]
As mentioned in [this comment](https://github.com/wxWidgets/wxWidgets/issues/23112#issuecomment-1373893963_), neither `WGL_SAMPLE_BUFFERS_ARB` nor `WGL_SAMPLES_ARB` seem to be supported by VMware OpenGL driver, meaning that creating OpenGL window fails by default inside the VM.

**Comment by PBfordev** [comment]
I assume this is a similar but different issue from the one we discussed [here](https://github.com/wxWidgets/wxWidgets/commit/e11ea1b737e91ab23481655a2aea2ed5b90fbbd6#comments)?

**Comment by vadz** [comment]
Thanks for the link! I thought this had come up before, but couldn't find it, but that was because I forgot it was a discussion in a commit and not an issue.

Anyhow, it might be the same or similar issue, but the fix is almost certainly the same either way: we need to stop requesting multisampling by default.

I'm confused as to why did we start doing it, to be honest, I thought we did what @Manolo-ES recommended (as this code comes from his bdc95f5766 (Improve wxGLCanvas to be more type safe and better support modern OpenGL, 2016-02-23) originally) but now he says that he was against this from the beginning, so I just don't know whose idea it was to do it like this (not mine, in any case, or at least not intentionally). If Manolo can make a PR with his proposed changes, it would be nice, otherwise I'll try to bring this back closer to 3.2 or maybe even 3.0 behaviour...

**Comment by Manolo-ES** [comment]
FYI multisampling was added to wx by https://github.com/wxWidgets/wxWidgets/commit/c39d2e0a3822e695efdfb2ead77a09defd6ed8c1 in  Jun 2008,  long before I learned OpenGL ;).

When I did the wx-OGL rework I tried top-hard efforts to keep previous behaviour, 'default multisampling' and some platform defaults included.

**Comment by vadz** [comment]
I might be misunderstanding something but hadn't this commit added support for multisampling, as opposed to using it by default? The commit I linked to added `wxGLAttributes::Defaults()` which enabled it there.

And, of course, it's perfectly fine to provide support for multisampling, it's just enabling it by default which seems to be a bad idea. Do we all agree with this? If yes, does anybody plan to do something about it by chance (i.e. make a PR changing this)?

**Comment by Manolo-ES** [comment]
The 2008 patcthnot only added multisample support, but, at least in MSW, failed if the driver didn't allow it. And in fact added this flag when no attributes list was passed. See msw/glcanvas.cpp::ChoosePixelFormatARB().

I decided to add Defaults() for user easier-life. And decided to set this flag in Defaults() (despite of I don't agree) because that was the case, at least for MSW.

The PR to remove this flag from Defaults() is one-line long, Anyhow, I can not promise to do it in the next weeks.

**Comment by vadz** [comment]
> The 2008 patcthnot only added multisample support, but, at least in MSW, failed if the driver didn't allow it. And in fact added this flag when no attributes list was passed. See msw/glcanvas.cpp::ChoosePixelFormatARB().

It indeed looks like this, but now I don't understand at all why did the samples work before in the VMs but don't any longer. I thought I remembered running there, but I could be remembering wrong or (worse?) remembering things that had happened before 2008. But there is also [this comment](https://github.com/wxWidgets/wxWidgets/commit/e11ea1b737e91ab23481655a2aea2ed5b90fbbd6#commitcomment-85472927) which seems to indicate that they worked even in 3.2, but don't work any longer. What has changed?

> I decided to add Defaults() for user easier-life. And decided to set this flag in Defaults() (despite of I don't agree) because that was the case, at least for MSW.
> 
> The PR to remove this flag from Defaults() is one-line long,

Yes, I can do this if we all agree that it's the right thing to do. Again, I thought you disagreed with this, but I realize now that I was wrong and I was just confused by you adding it to `Defaults()`, as I didn't realize it had already been default before, even if it wasn't called like this.

One remaining question is whether we want to remove it from all `Defaults()` implementations, including the Unix ones. It's possible that EGL or OpenGL under Mac always support this, but it's probably better to use the same attributes under all platforms, isn't it?
