### ISSUE TITLE
wxPrintPreview to large icons on High DPI Display

### ISSUE THREAD

**Issue by sz5000** [wxWidgets/wxWidgets#23127]
Tested wxPrintPreview recently and noticed that the Icons in the toolbar are to large. Seems to b another High DPI issue. Screenshot is attached. Code is below, copied from an example.

![image](https://user-images.githubusercontent.com/33447587/211370045-eb779e79-9b1d-485a-90b6-6ad4c4400712.png)

```
wxPrintPreview* preview = new wxPrintPreview(printout1, printout2);
wxPreviewFrame* frame = new wxPreviewFrame(preview, GetCtrl(),
	"Demo Print Preview",
	wxPoint(100, 100),
	wxSize(600, 650));
frame->Centre(wxBOTH);
frame->Initialize();
frame->Show(true);
```

**Comment by MaartenBent** [comment]
I can reproduce this in the printing sample. Using `wxBitmapBundle` seems to fix it, but I didn't test thoroughly:
```diff
diff --git "a/src/common/prntbase.cpp" "b/src/common/prntbase.cpp"
index c616438ffe..9e93ed5bcd 100644
--- "a/src/common/prntbase.cpp"
+++ "b/src/common/prntbase.cpp"
@@ -1517,7 +1517,7 @@ public:
         // We don't use (smaller) images inside a button with a text label but
         // rather toolbar-like bitmap buttons hence use wxART_TOOLBAR and not
         // wxART_BUTTON here.
-        wxBitmap bmp = wxArtProvider::GetBitmap(artId, wxART_TOOLBAR);
+        wxBitmapBundle bmp = wxArtProvider::GetBitmapBundle(artId, wxART_TOOLBAR);
         wxBitmapButton * const btn = new wxBitmapButton(m_parent, btnId, bmp);
         btn->SetToolTip(tooltip);
```

**Comment by vadz** [comment]
Thanks Maarten, I agree that this is the right thing to do, but I wonder why do we get the icons of wrong size by default. I wouldn't be surprised if the bitmaps ended up being scaled, but using the wrong size for them doesn't seem right... I'll try to understand why does this happen, even if I'm almost certain that the above is the correct fix in any case.

**Comment by vadz** [comment]
As I suspected, there was indeed another problem, which should be fixed by the first commit in the PR I've just opened (with the 2nd one being just Maarten's fix from above).

**Comment by sz5000** [comment]
Found another problem related to this:

Printing window is not updating correctly if we do not call wxYield in our printout, see image,
![image](https://user-images.githubusercontent.com/33447587/212078507-46cd91df-bd0f-49ee-b283-bc6acc15a621.png)

`printer.Print(GetCtrl(), printout.get(), false);`

Currently we add wxYield in out printout to fix this, but this fix breaks usage of wxPrintPreview/wxPreviewFrame. If we yield in our printout and if we use the control icons in wxPreviewFrame (zoom, prev/next page, ...) then the app crashes sporadically because of an invalid internal object in wxPrintPreview.

**Comment by vadz** [comment]
@sz5000 Something weird has happened here, I've seen a notification from GitHub about your comment mentioning another problem, but I don't see it here. Have you deleted it intentionally? If not, i.e. if there is still some other problem, please open another issue for it. TIA!
