### ISSUE TITLE
message: 'gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar'

### ISSUE THREAD

**Issue by Ricky-Tigg** [wxWidgets/wxWidgets#23129]
### Description
Hello. Issue in the _wxWidgets_ code used by _poedit_, in Wayland and X11 sessions. Expected | No reason for production of _Gtk-CRITICAL_ message .

### Platform and version information
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gcc gtk? wxGTK | column
gcc 12.2.1	gtk2 2.24.33	gtk3 3.24.36	gtk4 4.8.3	wxGTK 3.2.1
```
**OS:** Fedora v. 37

### To reproduce:

1. Execute `poedit` v. 3.2.2
2. In the _Welcome_ window | Select _Browse files_
3. Select a _*.po_ file
4.  See issue as output in terminal

Resulting output:
```
(net.poedit.Poedit:17997): Gtk-CRITICAL **: 13:23:51.211: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```
Creating a stack for serving the creation of a back-trace
```
$ G_DEBUG=fatal-criticals gdb /usr/bin/poedit
(...)
Enable debuginfod for this session? (y or [n]) y
(...)
(gdb) run
```
Output triggered by the selection of a _*.po_ file
```
(net.poedit.Poedit:19859): Gtk-CRITICAL **: 13:49:27.759: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

Thread 1 "poedit" received signal SIGTRAP, Trace/breakpoint trap.
g_log_writer_default (log_level=<optimized out>, fields=0x7fffffffa330, n_fields=6, user_data=0x0) at ../glib/gmessages.c:563
Downloading 0.03 MB source file /usr/src/debug/glib2-2.74.1-2.fc37.x86_64/redhat-linux-build/../glib/gmessages.c
563	    G_BREAKPOINT ();
(gdb) bt
```
`bt`'s resulting output: [gdb_back-trace_poedit.txt](https://github.com/wxWidgets/wxWidgets/files/10393132/gdb_back-trace_poedit.txt)

Undone investigation aimed to determine whether the exhibition of this message is cause of an underlying malfunction of the application run.

**Comment by vadz** [comment]
In spite of GTK shouting "CRITICAL", this message can be safely ignored and it's unfortunately not simple to avoid it in all situations, so while it would be nice to fix this, it's not really a problem and is almost certainly not the explanation for the "underlying malfunction", even though it's hard to be sure about the latter without knowing what this malfunction is.

**Comment by Ricky-Tigg** [comment]
Then no one could be in better position than the developer of the involved program to indicate without doubt what the malfunction(s) are if any. We must therefore hope that wxGTK gets rid of his bad habit of shouting for no pertinent reason. However, as one can easily imagine given the number of open tickets, this could take more than six years.

**Comment by vadz** [comment]
I'm sorry, I don't understand what are you saying. In fact, I might have misinterpreted your sentence here:

> Undone investigation aimed to determine whether the exhibition of this message is cause of an underlying malfunction of the application run.

I thought this meant that you had some other problem ("malfunction") that you thought was related to this and I just wrote that it almost surely wasn't.

**Comment by Ricky-Tigg** [comment]
Well, no doubt that it makes sense to assume that a program would not shout without pertinent reason, otherwise the message shouted would not be credible. That can reasonably lead me to conceive that there might exist at least one malfunction to justify the mention _CRITICAL_.

**Comment by vadz** [comment]
This is the same as #23499 which describes the problem better, so closing this one in favour of the other issue, even if it's older.
