### ISSUE TITLE
AUI sample shows artefacts when running under X with fwvm or Openbox

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23135]
See [this thread](https://groups.google.com/g/wx-users/c/vjHVCnHyyp8) but, briefly, running the aui sample in some environments, notably (because ease to use for testing) on the X display created by running
```
$ startx /usr/bin/fvwm -- /usr/bin/Xvnc -depth 24 -geometry 1920x1080
```
results in visual artefacts as shown here:

![wx-artifacts](https://user-images.githubusercontent.com/146917/212106400-4e777a3d-c02b-4809-a10c-dfcbc010c240.png)

To avoid wasting time of people looking to reproduce this, please notice that

1. You need to set `GDK_BACKEND=x11` if you have a Wayland server running too, as otherwise the sample will use it by default.
2. You need to run the sample from an Xterm inside fvwm and not from another terminal (probably due to some differences in the environment, but I didn't really check).

**Comment by GyrosGeier** [comment]
The main reason I run it from xterm is that you can see how to reproduce it, and that it makes fvwm place the window at an offset.

The artifacts always appear at the top left of the root window, so you can see them only when the window is somewhere else. The video I posted in the thread was taken with the ratpoison window manager, and kicad started from the WM.

**Comment by vadz** [comment]
Ah, ok, so actually it's enough to just _open_ an xterm, you don't even need to run the sample from it. I wonder if there is any way to make fvwm respect the supplied window position hint? This would make testing more convenient... But at least I can indeed position even a simple GTK program not at (0,0) if I give it a sufficiently big size so that it doesn't fit above the xterm. It still doesn't show any such artefacts but then neither does the minimal sample, so it's clearly something AUI-specific.

**Comment by GyrosGeier** [comment]
You can set up fvwm to use `ManualPlacement`, which will always ask where to put windows.

**Comment by vadz** [comment]
I've returned to this and I think I've managed to fix it in a rather obvious way, please see the upcoming commit. This will definitely need to be backported to 3.2 too, so please comment here if you still have any problems with the latest master (or, worse, have new problems that didn't exist before).

**Comment by GyrosGeier** [comment]
My feeling is that the problem isn't wxClientDC itself, but for some reason the root window gets addressed instead of the application window -- could it be that the `Repaint()` is invoked before the window is shown?

**Comment by GyrosGeier** [comment]
The patch does seem to resolve the problem for me though.

**Comment by vadz** [comment]
`wxClientDC` clearly doesn't work correctly, but it really shouldn't be used anyhow in wxGTK (because it doesn't and can't work with Wayland), so I don't want to spend time on fixing it.

We probably also need to stop using `wxAuiManager::UpdateButtonOnScreen()` which uses it in wxGTK3 and wxOSX...

**Comment by pierretom** [comment]
The patch also fix the issue on my side, thanks.
