### ISSUE TITLE
Broken handling of EVT_UPDATE_UI

### ISSUE THREAD

**Issue by oneeyeman1** [wxWidgets/wxWidgets#23150]
### Platform and version information

- wxWidgets version 
+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by oneeyeman1** [comment]
I'll try to make patch to mdi sample showing the problem in the next couple of days.

**Comment by vadz** [comment]
I'd just like to note that all GitHub text zones have a "Preview" tab and that it would be great if you could use it to avoid the completely broken markup, mixing up your text with the comments from the original placeholder, as above. For now it would be nice if you could at least edit the first comment above and remove all the junk from it and/or delete it entirely and move its contents into the description, where it should have been from the very beginning.

**Comment by oneeyeman1** [comment]
As promised, here is the patch to the sample that shows the problem.
I also included a workaround that makes it work.

diff -bru docview/view.cpp /c/wxWidgets/samples/docview/view.cpp
--- docview/view.cpp    2022-12-25 11:47:20.706171600 -0600
+++ /c/wxWidgets/samples/docview/view.cpp       2023-01-22 02:14:41.735526900 -0600
@@ -22,9 +22,13 @@
 #endif

 #include "docview.h"
+#include "wx/docmdi.h"
+#include "wx/artprov.h"
 #include "doc.h"
 #include "view.h"

+#define MYID 10001
+
 // ----------------------------------------------------------------------------
 // DrawingView implementation
 // ----------------------------------------------------------------------------
@@ -33,21 +37,25 @@

 wxBEGIN_EVENT_TABLE(DrawingView, wxView)
     EVT_MENU(wxID_CUT, DrawingView::OnCut)
+    EVT_UPDATE_UI(MYID, DrawingView::OnUpdateUI)
 wxEND_EVENT_TABLE()

 // What to do when a view is created. Creates actual
 // windows for displaying the view.
 bool DrawingView::OnCreate(wxDocument *doc, long flags)
 {
+    flag = true;
     if ( !wxView::OnCreate(doc, flags) )
         return false;

     MyApp& app = wxGetApp();
+    wxFrame* frame = nullptr;
     if ( app.GetMode() != MyApp::Mode_Single )
     {
         // create a new window and canvas inside it
-        wxFrame* frame = app.CreateChildFrame(this, true);
+        frame = app.CreateChildFrame(this, true);
         wxASSERT(frame == GetFrame());
+        frame->SetSize( 50, 50, 100, 100 );
         m_canvas = new MyCanvas(this);
         frame->Show();
     }
@@ -61,7 +69,10 @@
         doc->GetCommandProcessor()->SetEditMenu(app.GetMainWindowEditMenu());
         doc->GetCommandProcessor()->Initialize();
     }
-
+    auto toolbar = new wxToolBar( wxStaticCast( wxTheApp->GetTopWindow(), wxDocMDIParentFrame )->GetClientWindow(), wxID_ANY, wxDefaultPosition, wxDefaultSize );
+    toolbar->AddTool( MYID, "Check", wxArtProvider::GetBitmapBundle( wxART_FLOPPY ) );
+    toolbar->Realize();
+//    frame->SetToolBar( toolbar );  // workaround - uncomment to mae it work
     return true;
 }

@@ -114,7 +125,7 @@
     {
         m_canvas->ClearBackground();
         m_canvas->ResetView();
-        m_canvas = nullptr;
+        m_canvas = NULL;

         if (GetFrame())
             wxStaticCast(GetFrame(), wxFrame)->SetTitle(wxTheApp->GetAppDisplayName());
@@ -124,7 +135,7 @@
         if ( deleteWindow )
         {
             GetFrame()->Destroy();
-            SetFrame(nullptr);
+            SetFrame(NULL);
         }
     }
     return true;
@@ -137,6 +148,14 @@
     doc->GetCommandProcessor()->Submit(new DrawingRemoveSegmentCommand(doc));
 }

+void DrawingView::OnUpdateUI(wxUpdateUIEvent &event)
+{
+    if( flag )
+        event.Enable( false );
+    else
+        event.Enable( true );
+}
+
@@ -66,18 +66,18 @@
 class DrawingView : public wxView
 {
 public:
    DrawingView() : wxView(), m_canvas(NULL) {}

    virtual bool OnCreate(wxDocument *doc, long flags) wxOVERRIDE;
    virtual void OnDraw(wxDC *dc) wxOVERRIDE;
    virtual void OnUpdate(wxView *sender, wxObject *hint = NULL) wxOVERRIDE;
    virtual bool OnClose(bool deleteWindow = true) wxOVERRIDE;
+    void OnUpdateUI(wxUpdateUIEvent &event);
     DrawingDocument* GetDocument();

 private:
     void OnCut(wxCommandEvent& event);
-
+    bool flag;
     MyCanvas *m_canvas;

     wxDECLARE_EVENT_TABLE();

**Comment by vadz** [comment]
Replaced by #23166.
