### ISSUE TITLE
wxListView item padding on Mac OS

### ISSUE THREAD

**Issue by ryanseghers** [wxWidgets/wxWidgets#23155]
I am using wxListView in a cross-platform app. On Windows and Linux it looks fine, but on Mac OS the text rendered in the columns has no padding, which looks odd.

Here is a screenshot on windows:
![win-wx-list-view](https://user-images.githubusercontent.com/18274283/213302773-596aa1c8-6a8a-485b-9fc6-d99a32443a22.png)

Here it is on mac os:
![mac-wx-list-view](https://user-images.githubusercontent.com/18274283/213302813-3b97e3c6-ba84-4931-b654-cb8a81db5f83.png)

The text box is just for comparison, to show that both platform have padding in the text box. I changed the parent control background to grey to make it clear where the edges of the text box and listview are.

I'm on Mac OS X Ventura 13.1, using Clang 14.0.0 arm64-apple-darwin22.1.0, wxWidgets from vcpkg list says:
wxwidgets:arm64-osx 3.2.1#2 Widget toolkit and tools library for creating gr...
wxwidgets[debug-support]:arm64-osx Enable wxWidgets debugging support hooks even fo...
wxwidgets[sound]:arm64-osx Build wxSound support

Here is the code:

```cpp
// Demo of mac wxListView padding issue.
// Based on sample: https://docs.wxwidgets.org/trunk/overview_helloworld.html
#include <string>
#include <fmt/core.h>
#include <wx/wxprec.h>

#ifndef WX_PRECOMP
    #include <wx/wx.h>
    #include <wx/sizer.h>
    #include <wx/listctrl.h>
#endif

class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};

class MyFrame : public wxFrame
{
public:
    MyFrame();

private:
    wxListView* listView;
    void Build();
    void AddListViewItems();
};

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame();
    frame->Show(true);
    return true;
}

MyFrame::MyFrame()
    : wxFrame(NULL, wxID_ANY, "Hello World", wxDefaultPosition, wxSize(640, 480))
{
    Build();
    AddListViewItems();
}

void MyFrame::Build()
{
    auto sizer = new wxBoxSizer(wxVERTICAL);

    wxTextCtrl* textBox = new wxTextCtrl(this, wxID_ANY, "Text box");
    sizer->Add(textBox, 0, wxALL, 8);

    listView = new wxListView(this);
    listView->AppendColumn("Col0");
    listView->AppendColumn("Col1");
    listView->AppendColumn("Col2");
    listView->SetColumnWidth(0, 90);
    listView->SetColumnWidth(1, 100);
    listView->SetColumnWidth(2, 150);

    sizer->Add(listView, 1, wxALL | wxEXPAND, 8);

    // accentuate the issue by setting darker background
    wxColour grey("grey");
    this->SetBackgroundColour(grey);

    this->SetSizerAndFit(sizer);
}

void MyFrame::AddListViewItems()
{
    for (int i = 0; i < 10; i++)
    {
        listView->InsertItem(i, fmt::format("The {} item", i));
        listView->SetItem(i, 1, "col 1");
        listView->SetItem(i, 2, "col 2");
    }
}
```

**Comment by vadz** [comment]
We should tweak the margins used in the generic `wxListCtrl` implementation, I guess... There is even a comment about it in the code:

https://github.com/wxWidgets/wxWidgets/blob/08301b1b4ae6b54ee0f0a5dc6eb1f4468635954d/src/generic/listctrl.cpp#L82-L89

so I guess just removing the check for `__WXGTK__` should help. Can you test if it does, i.e. apply this patch:
```diff
diff --git a/src/generic/listctrl.cpp b/src/generic/listctrl.cpp
index 62a2a33df6..987c2f141e 100644
--- a/src/generic/listctrl.cpp
+++ b/src/generic/listctrl.cpp
@@ -63,30 +63,14 @@
 static const int LINE_SPACING = 0;
 
 // extra margins around the text label
-#ifdef __WXGTK__
 static const int EXTRA_WIDTH = 6;
-#else
-static const int EXTRA_WIDTH = 4;
-#endif
-
-#ifdef __WXGTK__
 static const int EXTRA_HEIGHT = 6;
-#else
-static const int EXTRA_HEIGHT = 4;
-#endif
 
 // margin between the window and the items
 static const int EXTRA_BORDER_X = 2;
 static const int EXTRA_BORDER_Y = 2;
 
-#ifdef __WXGTK__
-    // This probably needs to be done
-    // on all platforms as the icons
-    // otherwise nearly touch the border
-    static const int ICON_OFFSET_X = 2;
-#else
-    static const int ICON_OFFSET_X = 0;
-#endif
+static const int ICON_OFFSET_X = 2;
 
 // offset for the header window
 static const int HEADER_OFFSET_X = 0;
```

?

**Comment by vadz** [comment]
If you prefer, you could also test the linked PR instead of applying the patch above, as the patch is included in that PR.

**Comment by ryanseghers** [comment]
I did see your PR first, but went ahead and put mine up too because it is a bit different and because I had already tested it on Mac (not other platforms). Please feel free to incorporate my change into yours and we can just drop my PR, if the change seems good, or however you want to handle it is fine with me. I am not sure I can do a good review and/or test of all of your changes as I am not very familiar with the code.
