### ISSUE TITLE
wxGrid does not obey wxBoxSizer's proportion

### ISSUE THREAD

**Issue by pwiecz** [wxWidgets/wxWidgets#23159]
### Description
When I add two widgets to the same wxBoxSizer, both with proportion of 1, I expect both to accupy the same space.
But when I add a wxGrid it will take as much space as it needs for displaying its content.
In the example below it dependes on the number of rows passed to `wxGrid::CreateGrid`.
Also the grid widget size is not decreasing when the windows is being resized to a smaller size.

### Platform and version information
- wxWidgets version you use: 3.2 (on Windows) and 3.0 (bundled with Ubuntu 20.04)
- wxWidgets port you use: wxMSW, wxGTK
- OS and its version: Windows 10, Ubuntu 20.04

+ GTK version: I can't tell right now (default Ubuntu)
+ Which GDK backend is used: I can't tell right now (default Ubuntu)
+ Current theme:  I can't tell right now (default Ubuntu)

Code below.
Compiled on Ubuntu 20.04 via:  `wx-config --cxx` test_wx_grid.cpp `wx-config --static=no --cxxflags --toolkit=gtk3 --unicode=yes --version=3.0 --libs adv,core,base`
Compiled on Windows by creating custom MSVC project.

```#include <wx/app.h>
#include <wx/frame.h>
#include <wx/sizer.h>
#include <wx/grid.h>
#include <wx/panel.h>
#include <wx/textctrl.h>

class MyApp: public wxApp
{
public:
	virtual bool OnInit();
};

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
  wxFrame *frame = new wxFrame(nullptr, wxID_ANY, "Hello World", wxPoint(50, 50), wxSize(450, 340) );
  wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);

  wxPanel* panel = new wxPanel(frame, wxID_ANY);
  mainSizer->Add(panel, 1, wxEXPAND);
 
  wxBoxSizer* panelSizer = new wxBoxSizer(wxVERTICAL);

  wxGrid* grid = new wxGrid(panel, wxID_ANY);
  grid->CreateGrid(8, 1);
  panelSizer->Add(grid, 1, wxEXPAND);

  wxTextCtrl* text = new wxTextCtrl(panel, wxID_ANY, "test\ntest", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
  text->SetValue("test\ntest");
  panelSizer->Add(text, 1, wxEXPAND);

  panel->SetSizer(panelSizer);

  frame->SetSizer(mainSizer);  
  frame->Show( true );
  return true;
}
```

**Comment by pwiecz** [comment]
Ok, but when I resize the window down. It does not leave any space for the bottom widget. Evem if I call SetMinSize on it.
Is it expected, as well?

**Comment by vadz** [comment]
I don't see this, the text control does grow (even if starting from a smaller size) if I expand the window vertically. I don't remember (and didn't test) if it was a bug in 3.0, but this shouldn't happen with 3.2. Does the text really not grow at all for you with it?

**Comment by pwiecz** [comment]
@vadz 
What's unexpected to me is that the text control shrink to zero when I shrink the window.
I even start getting some gtk or X warnings on the console at that moment.
My expectations was that the grid will start shrinking at some point before the height of the text control shrinks to zero.
And colling text->SetMinClientSize does not prevent this shrinking to zero.

**Comment by vadz** [comment]
Yes, this is expected too. There is no magic solution for making everything fit if there is not enough space and setting the min size of the text doesn't help -- it's the min size of the grid which matters. If you reduce it to something very small, then wx will happily shrink the grid for you. But it will not make the first control smaller than its min size to respect the min size of the second one -- it's clear that this doesn't always result in a good layout and could be even more unexpected.

**Comment by pwiecz** [comment]
@vadz , apparently the think that confused me was that `wxGrid`'s min size depends on its column- and row-count.
The text control grows ok, it was the shrinking logic that was perplexing.
I think that the issue can be closed.
Thanks for the explanations.
