### ISSUE TITLE
wxStaticBitmap scales image unnecessarily on Windows

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#23168]
### Description
wxStaticBitmap and wxGenericStaticBitmap tend to upscale images on Windows. This does not reproduce on Mac or on Linux.

Here's simple code with wxStaticBitmap, wxGenericStaticBitmap, and a custom control that draws the bitmap using GC. On windows only the custom control draws correct size (as compared to the system image viewer with 100% zoom).

```
#include <wx/wx.h>
#include <wx/generic/statbmpg.h>
#include <wx/graphics.h>
#include <wx/dcbuffer.h>

class BufferedBitmap : public wxWindow
{
public:
    BufferedBitmap(wxWindow *parent, wxWindowID id, const wxBitmap &b, const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxDefaultSize, long style = 0)
        : wxWindow(parent, id, pos, size, wxFULL_REPAINT_ON_RESIZE)
    {
        this->SetBackgroundStyle(wxBG_STYLE_PAINT); // needed for windows

        this->Bind(wxEVT_PAINT, &BufferedBitmap::OnPaint, this);
        this->SetBitmap(b);
    }

    void OnPaint(wxPaintEvent &evt)
    {
        wxAutoBufferedPaintDC dc(this);
        dc.Clear();

        wxGraphicsContext *gc = wxGraphicsContext::Create(dc);

        if (gc)
        {
            const wxSize drawSize = GetClientSize();

            const wxSize bmpSize = bitmap.GetSize();

            double w = bmpSize.GetWidth();
            double h = bmpSize.GetHeight();

            double x = (drawSize.GetWidth() - w) / 2;
            double y = (drawSize.GetHeight() - h) / 2;

            gc->DrawBitmap(bitmap, x, y, w, h);

            delete gc;
        }
    }

    void SetBitmap(const wxBitmap &bitmap)
    {
        this->bitmap = bitmap;
        this->Refresh();
    }

    const wxBitmap &GetBitmap()
    {
        return bitmap;
    }

private:
    wxBitmap bitmap;
};

class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};

class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size);

private:
    wxStaticBitmap *staticBitmap;
    wxGenericStaticBitmap *genericBitmap;
    BufferedBitmap *bufferedBitmap;

    wxImage image;
};

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();

    MyFrame *frame = new MyFrame("Hello World", wxDefaultPosition, wxDefaultSize);
    frame->Show(true);
    return true;
}

wxIMPLEMENT_APP(MyApp);

MyFrame::MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size)
    : wxFrame(NULL, wxID_ANY, title, pos, size)
{
    if (!image.LoadFile("/Users/lukasz/Desktop/OIP.jpg"))
    {
        wxLogError("Failed to load image file");
        return;
    }

    auto sizer = new wxBoxSizer(wxVERTICAL);

    auto tvStatic = new wxStaticText(this, wxID_ANY, "Static Bitmap");
    staticBitmap = new wxStaticBitmap(this, wxID_ANY, wxBitmap(image), wxDefaultPosition, FromDIP(wxSize(500, 200)));
    staticBitmap->SetScaleMode(wxStaticBitmap::Scale_None);

    auto tvGeneric = new wxStaticText(this, wxID_ANY, "Generic Bitmap");
    genericBitmap = new wxGenericStaticBitmap(this, wxID_ANY, wxBitmap(image), wxDefaultPosition, FromDIP(wxSize(500, 200)));
    genericBitmap->SetScaleMode(wxStaticBitmap::Scale_None);

    auto tvBuffered = new wxStaticText(this, wxID_ANY, "Buffered Bitmap");
    bufferedBitmap = new BufferedBitmap(this, wxID_ANY, wxBitmap(image), wxDefaultPosition, FromDIP(wxSize(500, 200)));

    std::initializer_list<wxWindow *> controls = {tvStatic, staticBitmap, tvGeneric, genericBitmap, tvBuffered, bufferedBitmap};

    for (const auto c : controls)
    {
        sizer->Add(c, 0, wxALIGN_CENTER | wxLEFT | wxRIGHT | wxTOP, FromDIP(10));
    }

    this->SetSizerAndFit(sizer);
}

```

The offending image and the screenshots for the platforms are attached.

### Platform and version information

- wxWidgets version  you use: current master; also reproduces on 3.1.7
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10
<img width="1379" alt="Screenshot 2023-01-22 at 16 18 38" src="https://user-images.githubusercontent.com/42072702/213923871-b5193175-d228-4c78-acdb-2e1853510fb6.png">

<img width="1712" alt="Screenshot 2023-01-22 at 16 16 45" src="https://user-images.githubusercontent.com/42072702/213923882-dfb422fa-0b45-436c-8d0e-f31dffd439f4.png">
<img width="1712" alt="Screenshot 2023-01-22 at 16 14 17" src="https://user-images.githubusercontent.com/42072702/213923890-161e86ca-7544-4a74-b552-3544a09013bf.png">

![OIP](https://user-images.githubusercontent.com/42072702/213923954-03ecbd96-3d2b-434f-9953-a545a55e1c55.jpg)

**Comment by MaartenBent** [comment]
Looks like you have 200% scaling?
When drawing on a `wxDC` or `wxGraphicsContext` you'll also need to used `FromDIP()`.
I would change it to this:
```c++
const wxSize drawSize = ToDIP(GetClientSize());
```
so the w/h/x/y calculations are all dpi independent, and then when drawing use:
```c++
gc->DrawBitmap(bitmap, gc->FromDIP(x), gc->FromDIP(y), gc->FromDIP(w), gc->FromDIP(h));
```

**Comment by lszl84** [comment]
That would make the scaling consistent with the wxStaticBitmap, but what throws me off is that the System Image Viewer shows the small image at 100%.

The same goes for GIMP (see screenshot).

So if it's not a bug in wxWidgets, then it means both the Windows Image Viewer and GIMP are broken.

What do you think?
<img width="1712" alt="Screenshot 2023-01-22 at 17 08 51" src="https://user-images.githubusercontent.com/42072702/213926304-569dd8d4-f10c-479a-bf98-9c3b85b3dbe9.png">

**Comment by MaartenBent** [comment]
I don't think it is a bug, just a matter of choice.

GIMP and Image viewer show the image/pixels as they are, we choose to scale them so the size remains consistent with other gui elements.
Same on macOS and Ubuntu. The image viewer says 474x316 pixels, when you measure the image it is 948x632 pixels.

**Comment by lszl84** [comment]
Alright, this explanation makes sense to me. Closing the issue. Thanks!
