### ISSUE TITLE
Using wx with warnings-as-errors results in and error with radiobox.h

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#23161]
The following `ifdef` should be changed to an `if`

```
>git diff
diff --git a/include/wx/msw/radiobox.h b/include/wx/msw/radiobox.h
index 08ed60fc2e..4fe85151ec 100644
--- a/include/wx/msw/radiobox.h
+++ b/include/wx/msw/radiobox.h
@@ -116,7 +116,7 @@ public:


     // Non-portable MSW-specific functions.
-#ifdef WXWIN_COMPATIBILITY_3_2
+#if WXWIN_COMPATIBILITY_3_2
     wxDEPRECATED_MSG("Does nothing, don't use")
     void SetLabelFont(const wxFont& WXUNUSED(font)) {}
     wxDEPRECATED_MSG("Use portable SetFont() instead")
```

**Comment by vadz** [comment]
Thanks, will fix soon.

Weird that this warning didn't show up in our CI builds, which compiler and options (and `WXWIN_COMPAT_3_2` value) did you see it with?

**Comment by dconnet** [comment]
VS2022, v17.4.4. I haven't compiled against dev for quite a while, but I suspect it's due to a compiler update.

And I see it with both '0' and '1'.

**Comment by dconnet** [comment]
Oh, I forgot to mention - this happens when using wx, not when compiling it. I have my warning level set high (/Wall), with warnings-as-errors.
