### ISSUE TITLE
Broken handling of EVT_UPDATE_UI

### ISSUE THREAD

**Issue by oneeyeman1** [wxWidgets/wxWidgets#23166]
### Description
I am writing an MDI based application.
In the MDIParentFrame I create a "managed" toolbar.
When I the MDIChildFrame is created I also create an "unmanaged" toolbar with the parent of MDIParentFrame. In the child frame view I add EVT_UPDATE_UI events. However, those events never arrive.
There is a simple workaround - call SetToolbar() on the childframe. However, only one toolbar can be managed.
In the OnInternalIdle() function, there is a check for GetToolbar(), and the events are sent only when it succeeds.

### Expected behavior
Event is arrived and handled

### Observed behavior
Event is not arrived

### Patch to the sample
```
diff -bru docview/view.cpp /c/wxWidgets/samples/docview/view.cpp
--- docview/view.cpp    2022-12-25 11:47:20.706171600 -0600
+++ /c/wxWidgets/samples/docview/view.cpp       2023-01-22 02:14:41.735526900 -0600
@@ -22,9 +22,13 @@
 #endif

 #include "docview.h"
+#include "wx/docmdi.h"
+#include "wx/artprov.h"
 #include "doc.h"
 #include "view.h"

+#define MYID 10001
+
 // ----------------------------------------------------------------------------
 // DrawingView implementation
 // ----------------------------------------------------------------------------
@@ -33,21 +37,25 @@

 wxBEGIN_EVENT_TABLE(DrawingView, wxView)
     EVT_MENU(wxID_CUT, DrawingView::OnCut)
+EVT_UPDATE_UI(MYID, DrawingView::OnUpdateUI)
 wxEND_EVENT_TABLE()

 // What to do when a view is created. Creates actual
 // windows for displaying the view.
 bool DrawingView::OnCreate(wxDocument *doc, long flags)
 {
+flag = true;
     if ( !wxView::OnCreate(doc, flags) )
         return false;

     MyApp& app = wxGetApp();
+ wxFrame* frame = nullptr;
     if ( app.GetMode() != MyApp::Mode_Single )
     {
         // create a new window and canvas inside it
-wxFrame* frame = app.CreateChildFrame(this, true);
+frame = app.CreateChildFrame(this, true);
         wxASSERT(frame == GetFrame());
+frame->SetSize( 50, 50, 100, 100 );
         m_canvas = new MyCanvas(this);
         frame->Show();
     }
@@ -61,7 +69,10 @@
         doc->GetCommandProcessor()->SetEditMenu(app.GetMainWindowEditMenu());
         doc->GetCommandProcessor()->Initialize();
     }
-
+auto toolbar = new wxToolBar( wxStaticCast( wxTheApp->GetTopWindow(), wxDocMDIParentFrame )->GetClientWindow(), wxID_ANY, wxDefaultPosition, wxDefaultSize );
+toolbar->AddTool( MYID, "Check", wxArtProvider::GetBitmapBundle( wxART_FLOPPY ) );
+toolbar->Realize();
+//    frame->SetToolBar( toolbar );  // workaround - uncomment to mae it work
     return true;
 }

@@ -114,7 +125,7 @@
     {
         m_canvas->ClearBackground();
         m_canvas->ResetView();
-m_canvas = nullptr;
+m_canvas = NULL;

         if (GetFrame())
             wxStaticCast(GetFrame(), wxFrame)->SetTitle(wxTheApp->GetAppDisplayName());
@@ -124,7 +135,7 @@
         if ( deleteWindow )
         {
             GetFrame()->Destroy();
- SetFrame(nullptr);
+SetFrame(NULL);
         }
     }
     return true;
@@ -137,6 +148,14 @@
     doc->GetCommandProcessor()->Submit(new DrawingRemoveSegmentCommand(doc));
 }

+void DrawingView::OnUpdateUI(wxUpdateUIEvent &event)
+{
+    if( flag )
+        event.Enable( false );
+    else
+        event.Enable( true );
+}
+

diff -bru docview/view.h /c/wxWidgets/samples/docview/view.h
--- docview/view.h      2022-12-25 11:47:20.712177600 -0600
+++ /c/wxWidgets/samples/docview/view.h 2023-01-22 01:38:31.251074700 -0600
@@ -66,18 +66,18 @@
 class DrawingView : public wxView
 {
 public:
    DrawingView() : wxView(), m_canvas(NULL) {}

    virtual bool OnCreate(wxDocument *doc, long flags) wxOVERRIDE;
    virtual void OnDraw(wxDC *dc) wxOVERRIDE;
    virtual void OnUpdate(wxView *sender, wxObject *hint = NULL) wxOVERRIDE;
    virtual bool OnClose(bool deleteWindow = true) wxOVERRIDE;
+    void OnUpdateUI(wxUpdateUIEvent &event);
     DrawingDocument* GetDocument();

 private:
     void OnCut(wxCommandEvent& event);
-
+    bool flag;
     MyCanvas *m_canvas;

     wxDECLARE_EVENT_TABLE();
@@ -92,11 +92,11 @@

```

### To reprodce:
Build and run the docview sample.
Observe that the toolbar button is still enabled

### Platform and version information

- wxWidgets version  latest release
- wxWidgets port  reproducible on MSW, GTK and OSX does not have this isse
- OS  I use Wndows 8.1

+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by oneeyeman1** [comment]
This "proper submission" supersedes the 23150.
You can close that one and keep this one open.

**Comment by vadz** [comment]
Why do you expect these events to be handled in the child frame? AFAICS there is no relationship between the toolbar and it.

AFAICS this works as expected.

**Comment by oneeyeman1** [comment]
Vadim,

On Wed, Jan 25, 2023 at 7:42 AM VZ ***@***.***> wrote:

> Why do you expect these events to be handled in the child frame? AFAICS
> there is no relationship between the toolbar and it.
>

Because the condition to turn the button on//off is in the view
The event is handled based on the flag variable, which is a member of the
view
And so its natural to handle them in the view

Moreover, I can have 3 or 4 toolbars but only one can be set using
SetToolbar()

How do I handle those events in the ones that are not managed (if needed)?

> AFAICS this works as expected.
>

No it doesn't.
See above.

How would you handle those?


Thank you.

**Comment by vadz** [comment]
You're explaining what you'd like to do. I'm explaining that there is no reason for this to work like this because there is no link between these toolbars (which are just some random windows in the parent frame) and the child frame. If you need such link, you need to associate them in some way.

But I don't think it's a good idea to forward all update UI events for all windows to the child frame.

**Comment by oneeyeman1** [comment]
Vadim,


On Wed, Jan 25, 2023 at 8:57 AM VZ ***@***.***> wrote:

> You're explaining what you'd like to do.
>

No, I'm not.
Please re-read what I wrote - the flag to enable/disable the button  is in
the view
(in my case its in the document class - I just placed it in the view to
make things easier)

Now, i can call SetToolbar() o the chil frame and it will make the code
work, but
a its not required on GTK/OSX
b only one toolbar can be set

I'm explaining that there is no reason for this to work like this because
> there is no link between these toolbars (which are just some random windows
> in the parent frame) and the child frame. If you need such link, you need
> to associate them in some way.
>

How?


> But I don't think it's a good idea to forward all update UI events for all
> windows to the child frame.
>

Not to all of them - just for toolars.
Because if you add a menu - it will work.
And other windows will have their parent set..

Thank you.

**Comment by vadz** [comment]
You're creating your toolbar as a child of the client window, not of the frame so, once again, there is absolutely no relationship between them.

The fact that the main toolbar is handled differently is a special case warranted by the fact that we know that the commands in it apply to the current child. We do not know anything about all the other windows that may exist.

**Comment by oneeyeman1** [comment]
Vadim,
> You're creating your toolbar as a child of the client window,

[code]

+auto toolbar = new wxToolBar( wxStaticCast( wxTheApp->GetTopWindow(),
wxDocMDIParentFrame )->GetClientWindow(), wxID_ANY, wxDefaultPosition,
wxDefaultSize );

[/code]

I think GetTopWindow(), will give the MDIParentFrame pointer and not a
client window, is it not?
Besides I explicitly ask for it by casting.

Only difference between working and non-working solutions is
call to SetToolbar().

> not of the frame so, once again, there is absolutely no relationship
between them.

Are you talking about MDIChildFrame here?

It makes sense to do it on OSX, but not on Wndows/*nix...

Thank you.

**Comment by vadz** [comment]
You're really not understanding what I'm saying. It's to be expected that `SetToolbar()` is the difference because we explicitly route the events from *the* toolbar to the active child. We don't do it for any other arbitrary windows that are not the children of the child frame (events from children do bubble up, of course, as usual) and I think it's the right thing to do.

Also, it's weird that you can't read what your own code does. Cast or no cast you're using the client window, returned by `GetClientWindow()`, as the parent here.

Anyhow, I think there is nothing more to add here, so closing.
