### ISSUE TITLE
--disable-gtktest configure option no longer working

### ISSUE THREAD

**Issue by Amanda-M-UK** [wxWidgets/wxWidgets#23171]
I am attempting to cross compile wxWidgets 3.2.1 for _aarch64_ and _armhf_ on _x86-64_ Linux using custom built compilers that target a specific glibc version. However, I am unable to do this because the --disable-gtktest parameter no longer works.

I use the following configure

`../configure --prefix=/usr/local/wx/wx-aarch64-3.2.1 --disable-shared --disable-debug --with-opengl --host=aarch64-2.28_nm_64-linux-gnu --disable-gtktest --with-gtk=3`

the _configure_ output is normal until it attempts to run the gtktest and then fails with the following message:

**Configure output**

Checking for GTK+ version... 
checking for aarch64-2.28_nm_64-linux-gnu-pkg-config... /x-tools/aarch64/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GTK+ - version >= 3.0.0... no
*** Could not run GTK+ test program, checking why...
*** The test program failed to compile or link. See the file config.log for the
*** exact error that occurred. This usually means GTK+ is incorrectly installed.
configure: error: 
The development files for GTK+ were not found. For GTK+ 2, please
ensure that pkg-config is in the path and that gtk+-2.0.pc is
installed. For GTK+ 1.2 please check that gtk-config is in the path,
and that the version is 1.2.3 or above. Also check that the
libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
--libs' are in the LD_LIBRARY_PATH or equivalent.

**This procedure has worked perfectly up to 3.1.4 and from then on,  it seems to have stopped working.** 

If I amend pkgconfig / CXXFLAGS then  I can get the gtktest program to build but it fails to run. It's logical to assume that when cross compiling, the gtktest program is being built as an aarch64 or armhf binary and, of course, this cannot run on an x86-64 machine. 

Can anybody help with this problem?

Amanda

**Comment by vadz** [comment]
I don't think this is related to that option at all, which should be still honoured, it rather looks like this is the same problem as #22886 (but you should really check your `config.log` to see what's really going on and not rely on my guesses).

If it's indeed the same problem, it has been fixed in master since then and will be also fixed in 3.2.2, but in the meanwhile you should be able to work around it by setting `PKG_CONFIG_LIBDIR` to the directory appropriate for your cross-pkg-config.

**Comment by vadz** [comment]
I believe this should be fixed in both master and 3.2 now, please let us know if you still have problems.

**Comment by Amanda-M-UK** [comment]
Hi Vadz,

I can confirm that this problem has been fixed. 

Kind regards
Amanda
