### ISSUE TITLE
wxGetKeyState doesn't support Caps/Num/Scroll lock state under non-X11 GTK (Wayland for example)

### ISSUE THREAD

**Issue by elfmz** [wxWidgets/wxWidgets#23195]
### Description
wxGetKeyState raises error when invoked with WXK_CAPITAL/WXK_NUMLOCK/WXK_SCROLL under Wayland -bases system.
Its because current wxGetKeyStateGTK implementation fails when invoked with above keys, however it must be possible to detect them using gdk_keymap_get_caps_lock_state/gdk_keymap_get_num_lock_state/gdk_keymap_get_scroll_lock_state with proper GTK version

### Platform and version information
- wxWidgets - any (including master)
- wxWidgets port - wxGTK
Ubuntu 22.04, Wayland login

GTK version: any

**Comment by vadz** [comment]
Sorry, forgot to mention this in the commit message of 228bae0d91739fb3d405d9d6801e998ea55bad31 but the fix was applied to master and I'll also push it to 3.2 soon.
