### ISSUE TITLE
macOS: wxUILocale::GetLocalizedName() returns localized names when asked to return English names

### ISSUE THREAD

**Issue by utelle** [wxWidgets/wxWidgets#23199]
### Description

On _macOS_ calling method `wxUILocale::GetLocalizedName()` always returns localized names, even when asked to return English names. For example for a German locale

`wxUILocale::GetLocalizedName(wxLOCALE_NAME_LOCALE, wxLOCALE_FORM_ENGLISH)`

returns **"Deutsch (Deutschland)"** instead of the expected **"German (Germany)"**.

This problem can be seen in the _internat_ sample application.

Additionally, for English names always the locale name is returned instead of the language or the country.

### Platform and version information

- wxWidgets version you use: 3.2.1
- wxWidgets port you use: wxOSX
- OS and its version: macOS Ventura 13.2

**Comment by vadz** [comment]
This should have been fixed by 60e67de06ee4b0da2da1ec777d23b6cd7c026042, so closing.
