### ISSUE TITLE
Including `wx/msw/msvcrt.h` breaks in-place `new` use

### ISSUE THREAD

**Issue by zyxgis** [wxWidgets/wxWidgets#23194]
- wxWidgets version :  3.2.1 
- wxWidgets port :  wxMSW
- OS : Windows 10

i add momery leak check code as follow: 

```cpp
// ......
#include <crtdbg.h>
#include <iostream>

#ifdef __WXMSW__
#include <msvc/wx/setup.h>
// #include <wx/compiler.h>
#include <wx/msw/msvcrt.h>
#endif

inline void EnableMemLeakCheck()
{
  // _CrtSetReportMode( _CRT_ERROR, _CRTDBG_MODE_FILE );
  // _CrtSetReportFile( _CRT_ERROR, _CRTDBG_FILE_STDERR );
  _CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);
  std::cout<<"---------------------------- " <<__VISUALC__<<std::endl;
}

class AppMain : public wxApp
  {
  public:
    AppMain()
    {
      EnableMemLeakCheck();    
      //
      frame = nullptr;
    }

// ......
}

// ......

```

i get the error info as follow when i compile

```
[build] E:\bigdata\wxWidgets\3.2.1\include\wx/vector.h(471,15): error C2061: 语法错误: 标识符“place” 

```

**Comment by vadz** [comment]
Please provide a self-contained, complete, reproducible example. In particular, the code above is not complete and doesn't even include `wx/vector.h` at all, so it can't result in this error.

Also, translating the error message to English would be appreciated. Thank you!

**Comment by zyxgis** [comment]
@vadz , thank you for your reply.  i have upload my code to [](https://github.com/zyxgis/ZZDebugWx)

**Comment by MaartenBent** [comment]
A simpler way to reproduce:
```diff
 samples/minimal/minimal.cpp | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 501caf9096..b00001c478 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -12,6 +12,9 @@
 // declarations
 // ============================================================================
 
+#include <wx/compiler.h>
+#include <wx/msw/msvcrt.h>
+
 // ----------------------------------------------------------------------------
 // headers
 // ----------------------------------------------------------------------------
```

So a simple fix would be to include `wx/wxprec.h`/`wx/wx.h` before including these headers.

I don't know if they are supposed to be incuded stand-alone?

**Comment by PBfordev** [comment]
> I don't know if they are supposed to be incuded stand-alone?

I very much doubt that. I also think that `<crtdbg.h>` is MSVC-specific, I have no idea where `wxApp` declaration is supposed to come from, and I believe that `<msvc/wx/setup.h>` is not to be included like this, it is included by the main `setup.h` when the MSVC include folder is in the compiler include folders. In conclusion, the code in the OP cannot demonstrate anything.

**Comment by vadz** [comment]
Thanks for the simple repro case, Maarten! (and, to the OP: this is what is meant by [SSCCE](http://sscce.org/)).

The fundamental problem here is that including this header breaks placement new. We can work around this in `wx/any.h`, but I don't think there is any way to make this work in general, so my advice would be to simply not include `wx/msw/msvcrt.h` in the application code.
