### ISSUE TITLE
Ownerdraw doesn't measure wxMenuItem(s) that are type wxITEM_NORMAL and have set a bitmap

### ISSUE THREAD

**Issue by jacobean** [wxWidgets/wxWidgets#23230]
### Description

Ownerdrawn wxMenuItem(s) are not measured at all when the type is wxITEM_NORMAL and a bitmap is set.

Reproduction steps:
1. In the ownerdrw sample, change line 162/163 from wxITEM_CHECK to wxITEM_NORMAL. Also change "So&und" to something much longer for a more obvious result.
2. Run the edited ownerdrw sample.
3. Under the file menu look at the Sound menu item.

Expected Result:
The menu and menu item are sized correctly.

Actual result:
Everything is sized correctly except for this menu item.

I have checked using the debugger and it is not receiving an OnMeasureItem for this menu item.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by vadz** [comment]
For the record, here is a diff to reproduce the problem:
```diff
diff --git a/samples/ownerdrw/ownerdrw.cpp b/samples/ownerdrw/ownerdrw.cpp
index 00ca423ed3..52d58dc95b 100644
--- a/samples/ownerdrw/ownerdrw.cpp
+++ b/samples/ownerdrw/ownerdrw.cpp
@@ -159,8 +159,7 @@ void OwnerDrawnFrame::InitMenu()
     pItem->SetBitmaps(bmpBell);
     file_menu->Append(pItem);
 
-    pItem = new wxMenuItem(file_menu, Menu_Bitmap2, "So&und",
-                           "icon changes!", wxITEM_CHECK);
+    pItem = new wxMenuItem(file_menu, Menu_Bitmap2, "So&und with a very very very very very very long label");
     pItem->SetFont(fontBmp);
     pItem->SetBitmaps(bmpSound, bmpNoSound);
     file_menu->Append(pItem);
```

Removing the line changing the font doesn't help, which is weird because without setting the font, the item is not owner-drawn at all.

**Comment by jacobean** [comment]
I can't find it documented anywhere but it seems like setting mii.hbmpItem to an HBITMAP doesn't work when the menu item is owner-drawn.

Changing line 784 of src/msw/menuitem.cpp to this solves the problem:
`-    mii.hbmpItem = GetHBitmapForMenu(Normal);
+    mii.hbmpItem = IsOwnerDrawn() ? HBMMENU_CALLBACK : GetHBitmapForMenu(Normal);`

**Comment by vadz** [comment]
Thanks a lot for noticing this! It indeed fixes the problem and I wanted to apply your fix initially, but thinking more about this, it actually doesn't make sense to call `::SetMenuItemInfo()` for owner-drawn items at all -- it's simply not needed and we can skip doing it in this case, see 1e98812a56a494dce60384ba01b7c0a77b4fd651.

Please let me know if you see any problems with this and thanks again!
