### ISSUE TITLE
wx-3.2 Ubuntu ...Sigh

### ISSUE THREAD

**Issue by jhngrn** [wxWidgets/wxWidgets#23231]
Hello, I have successfully built wxWidgets-3. on CentOS and RHEL 7, 8 and 9 yet for Ubuntu 22.04 as denoted below, either I am doing something wrong, the vanilla Ubuntu system is toasted charcoal, or the m4 autogen script is overly unbaked. I don't really know where to publish or share this information, yet it should be removed, please let me know or remove it yourself. 

As root, I go to /usr/include and wget this bzip2, deflate, mv wxWidgets-3.2.1 wx-3.2 and go to wx-3.2/ 

/usr/bin/m4:/tmp/auNkxjiX/input.m4:6330: ERROR: end of file in string
autoupdate: error: /usr/bin/m4 failed with exit status: 1
root@frenchy:/usr/include/wx-3.2# uname -a
```
Linux frenchy 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@frenchy:/usr/include/wx-3.2# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
```

--
root@frenchy:/usr/include/wx-3.2# ./autogen.sh
```
configure.in:1100: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.in:1100: You should run autoupdate.
[snip]
autoconf_inc.m4:10: warning: The macro `AC_TRY_COMPILE' is obsolete.
autoconf_inc.m4:10: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
build/aclocal/bakefile.m4:577: AC_BAKEFILE_PRECOMP_HEADERS is expanded from...
build/aclocal/bakefile.m4:679: AC_BAKEFILE is expanded from...
autoconf_inc.m4:10: the top level
root@frenchy:/usr/include/wx-3.2# autoupdate
autoupdate: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:2944: warning: AC_PROG_CC_C99 is obsolete; use AC_PROG_CC

/usr/bin/m4:/tmp/auNkxjiX/input.m4:6330: ERROR: end of file in string
autoupdate: error: /usr/bin/m4 failed with exit status: 1
```
root@frenchy:/usr/include/wx-3.2#

**Comment by swt2c** [comment]
First of all, untarring the tarball in /usr/include is *not* the recommended way to build wx.  In fact, that could likely cause problems.  Untar it somewhere else (e.g., your home directory, a temp directory, etc.) but not in a system path.

Second, you don't need to run autogen.sh (and autoupdate).  The standard:
```
./configure
make
make install
```
should work just fine, assuming you have the appropriate dependencies installed.

**Comment by jhngrn** [comment]
./configure && make && make install is a native response most times and ./autogen.sh rarely.

I have this error and thank you for clarifying this above.
```
checking for pkg-config... no
checking for GTK+ - version >= 3.90.0... no
*** A new enough version of pkg-config was not found.
*** See http://pkgconfig.sourceforge.net
checking for gtk-config... no
checking for GTK - version >= 1.2.7... no
*** The gtk-config script installed by GTK could not be found
*** If GTK was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the GTK_CONFIG environment variable to the
*** full path to gtk-config.
checking for gtk-config... (cached) no
checking for GTK - version >= 1.2.3... no
*** The gtk-config script installed by GTK could not be found
*** If GTK was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the GTK_CONFIG environment variable to the
*** full path to gtk-config.
configure: error:
```

This is Ubuntu - what is missing?

**Comment by lanurmi** [comment]
> either I am doing something wrong
> As root, I go to

There is no reason to build wxWidgets as root, not on Ubuntu nor any other platform. Doing unnecessary things as root is dangerous and sometimes causes trouble, like in this case.
