### ISSUE TITLE
wxOSXDrawNSImage ignores the current wxCompositionMode

### ISSUE THREAD

**Issue by krZll** [wxWidgets/wxWidgets#23240]
Composition mode `wxCOMPOSITION_XOR ` has no effect if an image is drawn using function `wxMacCoreGraphicsContext::DrawBitmap( const wxBitmap &bmp, wxDouble x, wxDouble y, wxDouble w, wxDouble h )` in grahics.cpp with `wxOSX_USE_COCOA `enabled.
You can see this in the sample '**drawing**' if you select '**Mask screen**' under '**Screen**'. The image declared as `wxXOR` is the same as `wxCOPY`. The relevant function in the example is `MyCanvas::DrawImages(wxDC& dc, DrawMode mode)`. Images are drawn onto a `dc `with various raster operations, including `wxXOR`. When the old branch of `wxMacCoreGraphicsContext::DrawBitmap` is called the view is fine.

Tested with v3.1.5 and v3.2.1 on macOS Big Sur

**Comment by vadz** [comment]
`wxOSXDrawNSImage()` hardcodes `operation:NSCompositeSourceOver` in its call to `[NSImage drawInRect:...]`, see

https://github.com/wxWidgets/wxWidgets/blob/620e02c568bb7cc410b10ede1b592c20c02dfb9f/src/osx/carbon/utilscocoa.mm#L307

so I think we need to pass it the correct composition mode to use to fix this.

@csomor What do you think?

**Comment by csomor** [comment]
@vadz, thanks I'll add a composition parameter

**Comment by csomor** [comment]
@krZll could you please test with #23245
