### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by Carluccio** [wxWidgets/wxWidgets#23247]
I have listed the wxWidgets-3.2.2 dynamic libraries in the environment variables but it doesn't work.

Carlo Sala

**Comment by PBfordev** [comment]
Carlo, it seems you forgot to provide the issue description (including the OS you are using), in other words: What did you do and what exactly was not as you expected it to.

**Comment by Carluccio** [comment]
I am using windows 10.
The program compiled with wxWidgets-3.2.2 exists but it doesn't work because it doesn't find the dynamic libraries that I inserted in the environment variables.

**Comment by vadz** [comment]
Sorry, this is almost surely not a wxWidgets issue. You probably need to contact the program developer. If/when you do it, I strongly recommend providing the actual error message instead of just saying "it doesn't work".
