### ISSUE TITLE
wxFlexGridSizer ignores proportion in the Flexible Direction if NonFlexibleGrowMode is set 

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#23251]
### Description

Not sure if this is a bug, or just something not mentioned in the documentation... but does look like a bug to me.

Consider this example:

```cpp
#include <wx/wx.h>

class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};

wxIMPLEMENT_APP(MyApp);

class MyFrame : public wxFrame
{
public:
    MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size);
};

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame("Hello World", wxDefaultPosition, wxDefaultSize);
    frame->Show(true);
    return true;
}

MyFrame::MyFrame(const wxString &title, const wxPoint &pos, const wxSize &size)
    : wxFrame(nullptr, wxID_ANY, title, pos, size)
{
    const int COLS = 4;
    const int ROWS = 3;

    auto sizer = new wxFlexGridSizer(ROWS, COLS, 0, 0);

    sizer->AddGrowableRow(1, 1);
    sizer->AddGrowableRow(2, 4);

    sizer->AddGrowableCol(1, 1);
    sizer->AddGrowableCol(3, 3);

    sizer->SetFlexibleDirection(wxHORIZONTAL);
    sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);

    for (int i = 0; i < ROWS; i++)
    {
        for (int j = 0; j < COLS; j++)
        {
            auto square = new wxCheckBox(this, wxID_ANY, wxString::Format("%d, %d", i, j), wxDefaultPosition, wxDefaultSize);

            bool isDark = i % 2 == j % 2;

            square->SetBackgroundColour(isDark ? *wxBLACK : *wxBLUE);
            sizer->Add(square, 1, wxEXPAND);
        }
    }

    this->SetSizer(sizer);
}
```

This looks good: the rows and cols are resized and the proportions are respected.

<img width="512" alt="Screenshot 2023-02-11 at 13 56 27" src="https://user-images.githubusercontent.com/42072702/218259423-177ae92d-6787-4556-8cc9-e9418abac9f7.png">

Now if we change the non-flexible grow mode:

```cpp
sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_ALL);
```

The non-flexible direction (vertical) grows proportionally, and this is expected. However, the flexible direction **ALSO** grows proportionally, ignoring the proportions!

<img width="512" alt="Screenshot 2023-02-11 at 13 56 44" src="https://user-images.githubusercontent.com/42072702/218259577-2e67e35a-ef02-4e62-b13a-07083c9bd17e.png">

I guess the `SetNonFlexibleGrowMode` should only affect the non-flexible direction. If that's the case, it's a bug.

Similarly for  `wxFLEX_GROWMODE_NONE` -- the proportions for the flexible direction are ignored.

### Platform and version information

- wxWidgets version  you use: current master
- wxWidgets port  you use: wxMSW, wxGTK, wxOSX

**Comment by vadz** [comment]
Thanks for reporting this, this is indeed clearly a bug (although the fact that nobody has noticed it until now ever since this feature was added back in 5d76f46282 (added support for non flexible (in one direction only) flexible sizers, 2003-01-26) probably shows that it isn't a very important one...) and it should be fixed in the linked PR.

**Comment by lszl84** [comment]
@vadz I was thinking what was the purpose of `SetFlexibleDirection` and `SetNonFlexibleGrowMode` to begin with? If I want my grid to grow only in the horizontal direction, I can simply refrain from adding growable rows. Am I missing something?

If nobody uses it, maybe it's better to make this functionality obsolete and remove it in the future. A small change to make the project a bit easier to maintain.

**Comment by vadz** [comment]
To be honest, I have no idea what are these functions for. Someone must have asked for them 20 years ago and maybe they even provided some rationale for wanting this, but I have absolutely no memories of either. But at this stage it seems simpler to just leave this code as is than dealing with deprecating/removing it and forcing all the projects using these functions(and, to my surprise, there are quite a few of those) to update their code.
