### ISSUE TITLE
Missing tree icons in wxTreeCtrl

### ISSUE THREAD

**Issue by funnydog** [wxWidgets/wxWidgets#23255]
### Description
After Arch Linux upgraded wxWidgets to version 3.2.2 the icons in the main KiCad window aren't shown anymore (bugreport: https://bugs.archlinux.org/task/77476).

![Screenshot of the problem](https://i.imgur.com/UpySDhn.png)

Looking at the commits between v3.2.1 and v3.2.2 the only relevant one seems to be 8dd1375565f258e206cdd14ee333c10b49da36ae.

I tried to partially revert it (the part regarding wxTreeCtrl) and the issue goes away.

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxGTK
- OS  and its version: Arch Linux rolling x86_64

+ GTK version:  gtk3 1:3.24.36-1
+ Which GDK  backend is used: X11/xorg
+ Current theme: any

**Comment by vadz** [comment]
Fixed now in [3.2.2.1](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.2.1).
