### ISSUE TITLE
OSX: Adding text control to the toolbar

### ISSUE THREAD

**Issue by oneeyeman1** [wxWidgets/wxWidgets#23250]
Hi,

Add following 2 lines to the toolbar sample:

```cpp
    // up for the current DPI, if necessary.
    toolBar->SetToolBitmapSize(FromDIP(sizeBitmap));
+    wxTextCtrl *test = new wxTextCtrl( toolBar, wxID_ANY, "" );
+   toolBar->AddControl( test );
    toolBar->AddTool(wxID_NEW, "New",
                     toolBarBitmaps[Tool_new], wxNullBitmap, wxITEM_DROPDOWN,
                     "New file", "This is help for new file tool");

```

Build and run the toolbar sample on all 3 platforms.

On both Windows and GTK control will have some reasonable sizes.

However, on OSX text control will be very small.

I use OSX 10.13.6 High Sierra and Xcode 9.4 with wxWidgets previous release. (Didn't tried the latest one yet).

![Screen Shot 2023-02-10 at 3 34 10 PM](https://user-images.githubusercontent.com/5044312/218204240-4199dd1f-27d9-4876-9cab-b51289773975.png)

**Comment by oneeyeman1** [comment]
![table](https://user-images.githubusercontent.com/5044312/218204715-7a6d4b21-6eb4-4da5-bc55-d7715649fa7e.svg)

**Comment by oneeyeman1** [comment]
![Screenshot onGTK](https://user-images.githubusercontent.com/5044312/218204809-67453ae1-394e-4a46-91ee-f261a9dfebb1.png)

**Comment by vadz** [comment]
Probably can be worked around by giving some default size to the control but it would, of course, be better if a reasonable size was used by default.

P.S. I've edited the description to use proper markup for text. Could you please think to check the "Preview" button before submitting the next time?

**Comment by oneeyeman1** [comment]
@vadz,
This is actually a regression.
I just built the sample on wx-3.1.3 and ran it on OSX 10.8.5.

The text control has reasonable size.

**Comment by vadz** [comment]
It would be useful to bisect the history to find out when this got broken, if you can do it.

**Comment by oneeyeman1** [comment]
@vadz ,
Doing bisection shows this commit:

```
commit dc2ff0d6b42b93dc84b886571bc6008393721f1e
Author: Stefan Csomor <csomor@advancedconcepts.ch>
Date:   Sat Apr 30 20:34:28 2022 +0200

    wxOSX: Rewiring GetBestSize for single line text control again
    
    see #22374

```

Hopefully Stefan could take a look at this.

**Comment by vadz** [comment]
Thanks!

@csomor Do you think we should impose some minimal size in `wxNSTextFieldControl::GetBestSize()`, e.g. add `IncTo(...)` at the end?

**Comment by csomor** [comment]
@oneeyeman1 thanks for your work, @vadz yes, I'll try to find the best way to have reasonable defaults while not breaking the rest ...

**Comment by oneeyeman1** [comment]
@csomor ,
No problem.
It would be nice if the sizing is restored to be the same as before this commit.

Thank you.

**Comment by csomor** [comment]
please test with #23295

**Comment by csomor** [comment]
> Do you think we should impose some minimal size in `wxNSTextFieldControl::GetBestSize()`, e.g. add `IncTo(...)` at the end?

@vadz I found a more central place to fix this, the default-width trigger was not working anymore, because the native best width of an empty field was 3 pixels, and I was still comparing to 0 when deciding whether to use default width

**Comment by oneeyeman1** [comment]
@csomor ,
Just tried it - works as expected.
However, I don't have Retina display and so can't try it there.

If you can also ask the author of the original issue test this to confrm the change didn't break that - we can apply it and close this ticket.

Thank you for the fast reply.
