### ISSUE TITLE
wxRadioBox is too small

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23267]
### Description

This can be seen in the widgets sample, e.g. on the Button page.
![wxRadioBox](https://user-images.githubusercontent.com/99262969/219365598-c4237038-b92c-401d-9851-cb0778499ea4.png)

### Platform and version information

- wxWidgets version  you use: current master for upcoming 3.3.0
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
Thanks, it looks like something has broken this recently because I think it worked correctly before. I guess it could have been ce1ee46b0c (Use wxRadioButton in MSW wxRadioBox implementation, 2022-12-24)...

**Comment by taler21** [comment]
Yes, I can confirm that this commit is the culprit.

Before:
![wxRadioBox-Before](https://user-images.githubusercontent.com/99262969/219569121-16c20eb8-cddb-441c-9b4a-584f6dcfe4fa.png)

After:
![wxRadioBox-After](https://user-images.githubusercontent.com/99262969/219569147-015d27df-2120-4467-bf0f-69a9dd1d0e95.png)

**Comment by vadz** [comment]
I've fixed this by doing
```diff
diff --git a/src/msw/radiobox.cpp b/src/msw/radiobox.cpp
index 473f9df8bb..91834a7904 100644
--- a/src/msw/radiobox.cpp
+++ b/src/msw/radiobox.cpp
@@ -172,8 +172,11 @@ bool wxRadioBox::Create(wxWindow *parent,
     int borderTop, borderOther;
     GetBordersForSizer(&borderTop, &borderOther);

-    sizerBox->AddSpacer(borderTop);
-    sizerBox->Add(sizerButtons, wxSizerFlags().Border(wxLEFT, borderOther));
+    if ( borderTop > borderOther )
+        sizerBox->AddSpacer(borderTop - borderOther);
+
+    borderOther += wxSizerFlags::GetDefaultBorder();
+    sizerBox->Add(sizerButtons, wxSizerFlags().Border(wxALL, borderOther));

     SetSizer(sizerBox);

```

This actually results in bigger horizontal margins than before now, but IMHO it looks better and there doesn't seem to be any standard for the margins inside the box, so I'm going leave it like this.

**Comment by taler21** [comment]
Looks good. Thanks.
