### ISSUE TITLE
The link in release section of wxWidgets 3.2.2.1 is broken

### ISSUE THREAD

**Issue by asmwarrior** [wxWidgets/wxWidgets#23266]
Hi, in the page:

https://github.com/wxWidgets/wxWidgets/releases

The latest section is 3.2.2.1, in its text, it said:

`Instead, download one of [wxWidgets-3.2.2.zip](https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.zip) or [wxWidgets-3.2.2.7z](https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.7z),`

But I don't see those 7zip or zip files in the link, so is this broken links?

**Comment by asmwarrior** [comment]
It looks like the correct link is

`https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.1.7z`

and

`https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.1.zip`

**Comment by vadz** [comment]
Fixed, thanks!
