### ISSUE TITLE
wxConfigBase::Get() is no longer creating parent folders if needed

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#23263]
Describe the bug:
After upgrading to wxWidgets 3.2.1 we've noticed wxConfigBase::Get() is no longer creating the parent folder path to the file if the path doesn't exist. In prior versions, it would create the path to the file if it didn't exist. I'm not sure if this is a bug per se, but it is an unexpected change in behavior.

Expected vs observed behaviour:
wxConfigBase::Get()/Flush() no longer creates the file if the parent folder doesn't exist causing an error.

Patch or snippet allowing to reproduce the problem:
```
//UserLocalDataDir doesn't exist
 wxString iniDirName = wxStandardPaths::Get().GetUserLocalDataDir();
 wxFileName iniFileName(iniDirName, wxString(APP_NAME) + ".ini");

config = new wxFileConfig(wxEmptyString, wxEmptyString, iniFileName.GetFullPath(), wxEmptyString, wxCONFIG_USE_LOCAL_FILE);
delete wxConfigBase::Set(config);

//write pref to config file
 wxConfigBase::Get()->Write("key", "hello");
 wxConfigBase::Get()->Flush(); //NOW FAILS, used to work in prior versions
```

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxMSW/wxGTK
- OS  and its version: Fedora 37, Windows 11

**Comment by vadz** [comment]
I didn't actually know that `wxFileConfig` created the directory for its file, but I guess it makes sense. The curious thing is that I don't see at all when this was changed.

What was the last version in which this used to work?

**Comment by willco007** [comment]
We went from 3.1.5 to 3.2.1, 3.1.5 worked.

**Comment by oneeyeman1** [comment]
@willco007 ,
Can you try to do a bisection?

Thank you.

**Comment by willco007** [comment]
Oy, I have people to feed. 🙂 We're using the package from vcpkg and an unruly build system; it's all a bit ridiculous. The short answer is I can't easily bisect wxWidgets in my project. 😕

**Comment by willco007** [comment]
I was bisecting my own code and figured out I had removed code that was making this folder for a different file that is no longer is being created. This API never made the folder, sorry for the false alarm. Although it may be a nice addition? :)

**Comment by vadz** [comment]
Yes, as I wrote above I think it could be useful if it did it, so please feel free to make a PR adding this, it should be pretty simple to just use `wxFileName::Mkdir(wxPATH_MKDIR_FULL)` if necessary.

**Comment by willco007** [comment]
There are a number of places this addition could land. Seems like `Flush()` is the place, before the temp file creation, seem OK to you?

**Comment by vadz** [comment]
Yes, this looks like a good place.

I wonder if it could make sense to create the directory containing the file in `wxTempFile` itself. This would make `wxTempFileOutputStream` work in this situation too, which could perhaps be useful?

**Comment by willco007** [comment]
I thought about `wxTempFile` but that _may_ lead to unintended side effects. For example, a user out there may not want a temp file created if the parent directory doesn't exist or they may want the error to bubble up to the user. Say if the application user accidentally moves/deletes the folder out from under the application.  

All that said, now that I've typed it out I'm not sure I agree with automatically creating the folder in any case. :)

**Comment by willco007** [comment]
I was thinking about this more, it might be a nice feature flag to pass into `wxFileConfig` to you can opt-in/out of the behavior.

**Comment by vadz** [comment]
Sorry, I don't think it's a good idea to have a flag for this. Either we consider that it's something that should always be done (which I think is probably right) and then we should enable it or we decide that shouldn't be always done and then any application which does need it can always just create the directory on its own. Having a flag for this doesn't seem to be the right solution in neither the former nor the latter case.
