### ISSUE TITLE
wxCollapsiblePane background color does not match parent's background

### ISSUE THREAD

**Issue by pwiecz** [wxWidgets/wxWidgets#23274]
### Description
On MSW, when you have a CollapsiblePane inside a Notebook page, the background color of the CollapsiblePane contrasts with the background color of the Notebook

![image](https://user-images.githubusercontent.com/136140/219944666-2444e4de-69b2-4e6d-a5a3-22c060d34e15.png)

Expected vs observed behaviour:
I would expect that the colors would match, or at least there would be an easy way to set the background colors to match, but I cannot do it.
I've found a similar problem described here: https://forums.wxwidgets.org/viewtopic.php?t=45014 , but no easy solution can be found there.

Patch or snippet allowing to reproduce the problem:
```#include <wx/wx.h>
#include <wx/frame.h>
#include <wx/notebook.h>
#include <wx/collpane.h>

class MyApp : public wxApp
{
public:
    virtual bool OnInit() {
	wxFrame* frame = new wxFrame(nullptr, wxID_ANY, "Main");
	wxNotebook* notebook = new wxNotebook(frame, wxID_ANY);
	wxPanel* panel = new wxPanel(notebook, wxID_ANY);
	notebook->AddPage(panel, "Page", true);
	wxCollapsiblePane * pane = new wxCollapsiblePane(panel, wxID_ANY, "Collapsible pane");
	wxWindow *paneWindow = pane->GetPane();
    wxSizer *paneSizer = new wxBoxSizer(wxVERTICAL);
    paneSizer->Add(new wxStaticText(paneWindow, wxID_ANY, "Text inside pane"), 1, wxGROW|wxALL, 2);
    paneWindow->SetSizer(paneSizer);
    paneSizer->SetSizeHints(paneWindow);

	frame->Show(true);
	return true;
    }
};
wxIMPLEMENT_APP(MyApp);
```

To Reproduce:
Compare background color under the "Collapsible pane" text with the surrounding background color.

### Platform and version information

- wxWidgets version you use: current master (0c321cd039ce0e04afc3a63fc17f82339cc45bdc) from GitHub (just after 3.2.2.1 release)
- wxWidgets port you use: wxMSW
- OS and its version: Windows 10

**Comment by vadz** [comment]
Do you intentionally use the classic theme? It's still supported, but it's really not supposed to be used without some awfully good reason. And I suspect your problem is specific to it and doesn't happen if you [include a proper manifest](https://docs.wxwidgets.org/3.2/plat_msw_winxp.html).

**Comment by vadz** [comment]
Hmm, actually I take my words back, the problem can also be seen when using themes.

You still should use the manifest unless you have a good reason not to do it, but the bug must be fixed. I think it's a regression, but I'm not sure what could have broken (it's not `WS_EX_COMPOSITING`, for once).

**Comment by pwiecz** [comment]
Thanks. :) In fact, the program for which I've noticed the issue is being build using MSVC. So the manifest is added automatically. Here I wanted to make a minimal reproducer of the issue, and I wasn't aware that lack of a manifest can make a difference.
