### ISSUE TITLE
wxAuiToolBar::AddTool()  client_data parameter is discarded in code

### ISSUE THREAD

**Issue by CBtiger** [wxWidgets/wxWidgets#23271]
Describe the bug:
The wxAui function
 `  wxAuiToolBarItem* wxAuiToolBar::AddTool( int toolId, ...., wxObject *  client_data ) 	`
is described on the documentation as able to store a client_data pointer of type `wxObject*`- similar to `wxToolBar`. Here is the link to that documentation  https://docs.wxwidgets.org/trunk/classwx_aui_tool_bar.html#aa52bcc769ee06a6267b4ee030f76972a

Expected vs observed behaviour:
Thecode should store this pointer. But the source code (trunk) has this function listed as
   ` wxAuiToolBarItem* wxAuiToolBar::AddTool(int tool_id, .... , wxObject* WXUNUSED(client_data))	`
Here the source link. https://github.com/wxWidgets/wxWidgets/blob/master/src/aui/auibar.cpp#988
Also there is no function given to retrieve this `wxObject*` pointer

Patch or snippet allowing to reproduce the problem:
n/a

### Description
The wxAuiToolBar::AddTool() parameter "`client_data`" is ignored in the source code. That is not mentioned in the documentation.
* least fix should be to update the documentation and tell the user that the parameter `client_data` is discarded at this time.
*  better fix is to save that parameter and provide a way to retrieve that data again (this is missing). That would make sense, because he same principle is used by the native `wxToolBar`.

### Platform and version information
wxAui - All versions, all ports.

**Comment by vadz** [comment]
There is indeed no support for the client data in this class, I'll mention it in the (equally non existent...) documentation.

Any PRs implementing this would be welcome, of course,

**Comment by wh11204** [comment]
I have just created a PR fixing this. It is my first PR, I hope it it OK.

**Comment by wh11204** [comment]
I deleted the branch and the PR has closed itself, that is not what I intended to do. Lesson learned...
