### ISSUE TITLE
wxPropertyGridManager::GetVIterator is broken

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23273]
### Description
The behavior of the iterator returned from `wxPropertyGridManager::GetVIterator` is broken.
After deleting all properties in the active page of the grid manager by calling `m_pPropGridManager->GetGrid()->Clear()` the iterator will stop iterating when it encounters the page that has been cleared.
I.e. if the first page in the manager has been cleared the iterator will iterate NONE of the properties from the other pages, if the second page is cleared the iterator will iterate the properties of the first page but NONE of any pages following the second page etc.

The issue can be reproduced by updating and using the `samples/propgrid/propgrid` example app.

I added the following code to the app:

In samples/propgrid/propgrid.h:
- add the following declaration to the FormMain class:
```
    void OnCountAllProp( wxCommandEvent& event );
```

In samples/propgrid/propgrid.cpp:
- append an extra ID enum `ID_COUNT_ALL_PROP` to the menu IDs enum
- add the following entry to the event table:
```
EVT_MENU( ID_COUNT_ALL_PROP, FormMain::OnCountAllProp )
```
- add the code to add a menu entry to trigger the `OnCountAllProp` method in the `FromMain::FormMain` ctor method (I added just below the menu item for 'Delete All':
```
    menuTools1->Append(ID_COUNT_ALL_PROP, "Count All" );
```
- add the implementation for the `OnCountAllProp` method:
```
void FormMain::OnCountAllProp( wxCommandEvent& WXUNUSED(event) )
{
  wxPGVIterator it = m_pPropGridManager->GetVIterator(wxPG_ITERATOR_FLAGS_ALL | wxPG_IT_CHILDREN(wxPG_ITERATOR_FLAGS_ALL));
  size_t n = 0;
  for ( ; !it.AtEnd(); it.Next() ) ++n;
  wxString s;

  s.Printf("Counted %lu properties", n);
  wxMessageBox(s);
}
```

Testing:

- start the app
- select the `[Basic]` -> `[Count All]` menu item which will display a message box displaying "Counted 233 properties"
- select the `[Basic]` -> `[Delete All]` menu item
- select the `[Basic]` -> `[Count All]` menu item which will display a message box displaying "Counted 0 properties"

Alternatively:
- start the app
- select the second page of the property grid (`wxWidgets Library Config`)
- select the `[Basic]` -> `[Count All]` menu item which will display a message box displaying "Counted 233 properties"
- select the `[Basic]` -> `[Delete All]` menu item
- select the `[Basic]` -> `[Count All]` menu item which will display a message box displaying "Counted 60 properties"

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE 15.4

 
+ GTK version: 2.24.33
+ Which GDK  backend is used:  X11
+ Current theme:  NA

**Comment by a-wi** [comment]
Please reopen if the issue still stands.
