### ISSUE TITLE
wxEditorDialogProperty : editor dialog broken with potential SEGFAULT

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23272]
### Description
The editor dialog for `wxEditorDialogProperty` (and derived) properties is partially broken.
More specifically clicking the right mouse button outside an item that is being edited in the dialog causes a problem when the area where is clicked is beyond the listed items, i.e. if 2 items are shown and one of those is edited clicking in the area below the listed items triggers an assert popup. 
It actually seems there are two different (related probably) issues as the message shown in the assert popup is different when clicking in area of the first item beyond the listed ones from the message shown when clicking  further below that.
Clicking `[Continue]` on the first assert popup (from clicking directly below the items) seems pretty benign in that it does not seem to cause permanent harm and the app continues working. Clicking `[Continue]` on the second assert popup however always causes harm leading up to memory corruption sometimes SEGFAULT-ing directly after.

The issue can be reproduced using the `samples/propgrid/propgrid example app.

- start the app
- select one of the list item properties like the `ArrayDoubleProperty` under the  `More Examples` category ('Standard Items' page)
- press the `[...]` button
- in the editor dialog edit the first item `-1`
- now click in the area below the last item `1` 
- an assert popup is shown

This will happen with any of the properties derived from wxEditorDialogProperty.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE 15.4

 
+ GTK version: 2.24.33
+ Which GDK  backend is used:  X11
+ Current theme:  NA

**Comment by a-wi** [comment]
Please reopen if the issue still stands.

**Comment by vadz** [comment]
@a-wi Should this be backported to 3.2?

**Comment by mcorino** [comment]
> Please reopen if the issue still stands.

No need, this fixes the issue nicely. Thx.

**Comment by a-wi** [comment]
> Should this be backported to 3.2?

Yes, I think so.
