### ISSUE TITLE
wxPropertyGridInterface::Insert has inconsistent results

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23270]
### Description
Inserting new properties using `wxPropertyGridInterface::Insert(parent, index, newprop) ` gives inconsistent and unpredictable results.
Sometimes the property is inserted at the position specified as expected (rarely it seems) but mostly not.
When not, the new property is either appended or it seems to be randomly inserted.
The only consistent behavior seems to be that the new property is inserted under the specified parent.

The problem can be demonstrated simply by building the provided sample/propgrid/propgrid example app and
insert new properties using the menu option `[Basic] -> [Insert New Property]`.

As far as I can tell the sample code seems to be correct in providing the parent and index for inserting the new property.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE 15.4

 
+ GTK version: 2.24.33
+ Which GDK  backend is used:  X11
+ Current theme:  NA

**Comment by a-wi** [comment]
Properties are sorted by labels (names) by default. Isn't inserted property located in the right place in the alphabetical order?

**Comment by mcorino** [comment]
Ha, right! I knew I must have been missing something. Thanks for the clarification.

**Comment by mcorino** [comment]
Done.
