### ISSUE TITLE
Shaped windows don't appear correctly in dark mode under Mac

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23286]
While debugging another problem in the dialogs sample, I've noticed that the shaped rich tooltip window doesn't look right in dark mode (it's fine, i.e. really shaped, in light one), as it has grey background in the "transparent" parts, see this screenshot:

![mac_dark_shaped](https://user-images.githubusercontent.com/146917/220440454-a41107db-b710-4993-b8b3-e959fa03b60c.png)

I have no idea why using `[NSColor clearColor]` as background colour in `wxNonOwnedWindowCocoaImpl::SetShap()` doesn't work in dark mode, unfortunately, so I don't know how to fix this.

**Comment by csomor** [comment]
ok, we are overriding the background color of the toplevel window with a solid color, that's why our previous clearColor gets changed ... I'll try to find a way to change the colour on the background view but not on the NSWindow ...
