### ISSUE TITLE
Self documenting

### ISSUE THREAD

**Issue by alex-rass-88** [wxWidgets/wxWidgets#23281]
Many modern editors and development environments support documentation in the doxygen format. But most of this documentation is in the interface directory, which is not included in the developer package. Maybe we should move the documentation to the include directory? Then the hints to the methods will contain documentation.

**Comment by vadz** [comment]
No, sorry, we're not going to do it for a couple of reasons:

1. Having that much documentation inline would make the headers unreadable and unusable.
1. Public documented API is sometimes different from the actually used one as it hides implementation details.

We could, of course, include `interface/wx` headers in the dev package if it could help, but I don't know if it would.

**Comment by alex-rass-88** [comment]
OK, I understand.
