### ISSUE TITLE
wxString::FromCDouble doesn't work properly, if the locale was changed via C++ STL

### ISSUE THREAD

**Issue by utelle** [wxWidgets/wxWidgets#23287]
### Description

If an application uses for example
```C++
std::locale::global(std::locale("norwegian"));
```
to change the current locale, the static method `wxString::FromCDouble()` doesn't work properly any longer. The reason is that `wxString::FromCDouble()` calls internally `wxString::FromDouble()` (which now uses a comma as the decimal separator), but `wxUILocale::GetCurrent().GetInfo(wxLOCALE_DECIMAL_POINT, wxLOCALE_CAT_NUMBER);` returns a point, because it thinks that the current locale is still the C locale (since `wxUILocale::UseDefault()` was not called). Therefore the replace operation searches for points (to replace them by points) and the actually used comma is not found (and not replaced).

A user of my component [wxPdfDocument](https://github.com/utelle/wxpdfdoc) experienced this problem (see https://github.com/utelle/wxpdfdoc/issues/86). I informed the user that `wxUILocale::UseDefault()` should be used to change the locale. And as expected doing so solves the problem.

However, I wanted to bring this issue to your attention, because existing code or third-party libraries might use the C++ STL to manipulate the locale for whatever reason. And that should not break `wxString::FromCDouble` resp `wxString::ToCDouble`, if possible.

One possible way to do it would be to use in `wxString::FromCDouble()` a call to `wxString::FromDouble(1.0, 1)` and extract the separator from the result string, instead of calling `wxUILocale::GetCurrent().GetInfo(wxLOCALE_DECIMAL_POINT, wxLOCALE_CAT_NUMBER);`.

### Platform and version information

- wxWidgets version: 3.2.1
- wxWidgets port: wxMSW
- OS and its version: Windows 10/11

**Comment by vadz** [comment]
In principle we could just always replace `,` with `.` as there are no other decimal separators in use (and if there were, we could always replace any characters outside `[0-9.+eE-]` range with a period).

**Comment by dconnet** [comment]
That might not be a good idea... unless by "any" you actually mean "any punctuation". Otherwise "0B1" will result in a very unexpected valid number.

**Comment by vadz** [comment]
We're speaking about `wxString::FromDouble()`, so there is never going to be any `B` in the string.

**Comment by dconnet** [comment]
(that's what I get for not reading the whole thread!)

**Comment by utelle** [comment]
> In principle we could just always replace `,` with `.` as there are no other decimal separators in use (and if there were, we could always replace any characters outside `[0-9.+eE-]` range with a period).

According to [Wikipedia](https://en.wikipedia.org/wiki/Decimal_separator) either comma or point are used as decimal separator in most countries of the world. Exceptions seem to be some Arabic countries, where the _Arabic decimal separator_ (**U+066B**) is used. To be on the safe side it is probably advisable to replace any characters outside the `[0-9.+eE-]` range with a period.

**Comment by vadz** [comment]
#23422 solves this problem in 2 different ways:

- For C++17, it now uses `std::{to,from}_chars()` which were exactly the missing functions that we didn't have before.
- Otherwise it implements the hack above, i.e. just falls back on comma if the current locale doesn't use period.
