### ISSUE TITLE
No Georgian locale update in tarballs

### ISSUE THREAD

**Issue by NorwayFun** [wxWidgets/wxWidgets#23292]
Hello,
I've updated Georgian translation of wxWidgets back in August 2022, but in all .tar.bz2 sources released after that are having old locale/ka.po file anyway, while git repo has correct file (https://github.com/wxWidgets/wxWidgets/blob/master/locale/ka.po).
Could you please fix it?

Temuri

**Comment by vadz** [comment]
I'll backport the changes from #22673 to 3.2 branch, so they will be included in the next release (3.2.3).
