### ISSUE TITLE
error on compiling wxWidgets  under cywin

### ISSUE THREAD

**Issue by hjbortol** [wxWidgets/wxWidgets#23293]
iam trying to compile wwidgets under cywin. the compilation stops with this error:
```
nclude/wx/hashmap.h:667:5: note: in expansion of macro '_WX_DECLARE_HASH_MAP'
  667 |     _WX_DECLARE_HASH_MAP( KEY_T, VALUE_T, HASH_T, KEY_EQ_T, CLASSNAME, class )
      |     ^~~~~~~~~~~~~~~~~~~~
./include/wx/private/webrequest_curl.h:177:5: note: in expansion of macro 'WX_DECLARE_HASH_MAP'
  177 |     WX_DECLARE_HASH_MAP(CURL*, curl_socket_t, wxPointerHash, \
      |     ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:27512: netdll_webrequest.o] Error 1
```

![image](https://user-images.githubusercontent.com/7694624/220976129-c6824685-4d7c-452f-ada9-d1a024cc5094.png)

**Comment by vadz** [comment]
Please:

1. Don't attach screenshots with the error messages, copy and paste _full_ message as text instead (using correct formatting to prevent it from being mangled).
2. Always specify the version of wx you use.
3. Show the full configure command line.
