### ISSUE TITLE
May be an error in a settings.h

### ISSUE THREAD

**Issue by gerard-durand** [wxWidgets/wxWidgets#23298]
I see 2 files settings.h, one in include/wx/ and an other in interface/wx.
I have the feeling that only the first one is used, so it's not really a problem.
The second one, has probably an error at line 118 because this line is not ended by a comma, so the enum is probably not correct. In the first one, the corresponding line (85) is ended by a comma.

### Platform and version information
wxWidgets version 3.2.2 or 3.3.0

**Comment by vadz** [comment]
The second file is used for the documentation generation, so its syntax doesn't really matter, but I'll remove `wxSYS_COLOUR_MAX` from there, thanks.
