### ISSUE TITLE
libregex Undefined symbols for architecture x86_64 on maxos x86_64

### ISSUE THREAD

**Issue by yifan513** [wxWidgets/wxWidgets#23302]
### Description

On maxos, i9, not arm64, libregex Undefined symbols for architecture x86_64 on maxos x86_64. Seems it is for x86, just 32 bit version.
It is good foe windows 10.

link error message as below:
Undefined symbols for architecture x86_64:
  "_pcre2_code_free_32", referenced from:
      wxRegExImpl::~wxRegExImpl() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegExImpl::~wxRegExImpl() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegExImpl::Compile(wxString, int) in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegEx::~wxRegEx() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegEx::Compile(wxString const&, int) in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_compile_32", referenced from:
      wxRegExImpl::Compile(wxString, int) in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_config_32", referenced from:
      wxRegEx::GetLibraryVersionInfo() in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_get_error_message_32", referenced from:
      (anonymous namespace)::wx_regerror(int, (anonymous namespace)::regex_t const*, wchar_t*, unsigned long) in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_get_ovector_pointer_32", referenced from:
      wxRegExImpl::Matches(wchar_t const*, int, unsigned long) const in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_match_32", referenced from:
      wxRegExImpl::Matches(wchar_t const*, int, unsigned long) const in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_match_data_create_from_pattern_32", referenced from:
      wxRegExImpl::Compile(wxString, int) in libwx_baseu-3.2.a(baselib_regex.o)
  "_pcre2_match_data_free_32", referenced from:
      wxRegExImpl::~wxRegExImpl() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegExImpl::~wxRegExImpl() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegExImpl::Compile(wxString, int) in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegEx::~wxRegEx() in libwx_baseu-3.2.a(baselib_regex.o)
      wxRegEx::Compile(wxString const&, int) in libwx_baseu-3.2.a(baselib_regex.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Platform and version information

- wxWidgets version  you use:  3.2.2.1
- wxWidgets port  you use: wxOSX
- OS  and its version: 2.4 GHz 8-Core Intel Core i9, 13.2.1 (22D68)

+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by vadz** [comment]
This is almost certainly a user error because macOS builds definitely work correctly, they're being tested automatically and also used by many people.

In case you still believe this is a problem with wxWidgets, you need to provide full information about your build, starting with the full configure command line.

**Comment by yifan513** [comment]
In the configure.in I see 
```
AC_DEFINE(wxUSE_REGEX)

    dnl Find the PCRE library we need.
    if test "$wxUSE_UNICODE" = "yes"; then
        if test "$wxUSE_UNICODE_UTF8" = "yes"; then
            pcre_suffix=8
        else
            if test "$ac_cv_sizeof_wchar_t" = 2; then
                pcre_suffix=16
            elif test "$ac_cv_sizeof_wchar_t" = 4; then
                pcre_suffix=32
            else
                AC_MSG_ERROR([unknown sizeof(wchar_t)])
            fi
        fi
    else
        pcre_suffix=8
    fi

    if test "$wxUSE_REGEX" != "builtin"; then
        PKG_CHECK_MODULES(LIBPCRE, [libpcre2-$pcre_suffix],
            [
                PCRE_LINK=$LIBPCRE_LIBS
                CXXFLAGS="$LIBPCRE_CFLAGS $CXXFLAGS"
                wxUSE_REGEX=sys
            ],
            [
                wxUSE_REGEX=builtin
            ]
        )
    fi
```
I am not sure if this stop to create the 64 bit version.
I built steps:
```
cd wxWidgets-3.2.2.1
mkdir mac_lib
cd maclib
../configure --disable-shared --enable-unicode --prefix="$(pwd)" --with-macosx-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --with-macosx-version-min=12.3 --with-libtiff=no
make
```

There was no errors while compiling and building.
Thanks.

**Comment by yifan513** [comment]
BTW, other libs are good on this macos. Only when add code of wxregex and then got such error.

**Comment by vadz** [comment]
Configure probably picks up an existing (but somehow incompatible) PCRE2 system library. Please check `config.log` for the result of the check and/or do `grep REGEX config.status`.

You can also use `--disable-sys-libs` to ensure this doesn't happen.

**Comment by yifan513** [comment]
Great job.
I use --disable-sys-libs and then everything is good now.
Thanks so much.
