### ISSUE TITLE
wxFRAME_TOOL_WINDOW is not working in mac osx (wxDialog) 

### ISSUE THREAD

**Issue by michfiel** [wxWidgets/wxWidgets#23306]
### Description

The flags for wxOK and wxFRAME_TOOL_WINDOW are identical and so masking out the former makes it impossible to create a modeless palette.

```
bool wxDialog::Create( wxWindow *parent,
{
    ...
    // ...but not these styles
    style &= ~(wxYES | wxOK | wxNO); // | wxCANCEL
    ...
}
```
### Platform and version information

- wxWidgets version 3.2.1
- wxWidgets port wxOSX
- macOS 10.15

**Comment by vadz** [comment]
`wxFRAME_TOOL_WINDOW` is specifically documented as being for `wxFrame` only, not `wxDialog`, so I'm not sure why do you expect this to work. Does it work in some other port?

**Comment by michfiel** [comment]
That makes sense. I am sorry for the false alarm. It did work in my (modified) port of an earlier wxWidget version.
