### ISSUE TITLE
Documenting width parameter when adding columns to wxDataViewListCtrl

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#23307]
### Description
Documentation for column management functions in wxDataViewListCtrl says the default value for the width parameter is -1.
It would be better to say that the default value is wxCOL_WIDTH_DEFAULT, and remark that wxCOL_WIDTH_AUTOSIZE also exists.

BTW, the 'real' dataview.h also uses -1 in some prototypes, see p.e. AppendTextColumn().

**Comment by vadz** [comment]
Yes, indeed, we should also use `wxCOL_WIDTH_DEFAULT` in the actual header. If you can make a PR doing this, both in `include` and `interface` headers, it would be welcome. TIA!

**Comment by wh11204** [comment]
Done in #23325, , I hope it is OK.

**Comment by vadz** [comment]
Forgot to mention this in the commit message, but fixed in cf3dcb230a009c6748dc9eb986df805edfac84b4
