### ISSUE TITLE
Incorrect color value (inverted) of columns headers after switching System DPI when WX_MSW_DARK_MODE is active

### ISSUE THREAD

**Issue by k-serg** [wxWidgets/wxWidgets#23322]
### Description

Switching System DPI provokes some colors of columns headers have an incorrect color value (invert) when WX_MSW_DARK_MODE is active

Steps to reproduce:
1. Enable wxMSWDarkMode by set env var SET WX_MSW_DARK_MODE=2
2. Open affected samples (widgets.exe, dataview.exe, treelist, probably affected any ctrl that use column header)
3. Change system DPI from Windows Control Panel from
4. Column header foreground (text) color revert from normal (WHITE in dark mode) to revert (BLACK)

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10.0.19044 64 bit

![dark_mode_header_color](https://user-images.githubusercontent.com/76852271/223394415-baa7ef83-3a93-4fa3-b548-d25279849285.gif)

**Comment by vadz** [comment]
Thanks for noticing this, I'll push the fix soon.
