### ISSUE TITLE
macOS CMake build produces lots of implicit conversion loses integer precision warnings

### ISSUE THREAD

**Issue by TcT2k** [wxWidgets/wxWidgets#23329]
### Description

When building with CMake and XCode on macOS I get lots of these warnings:
`Development/OpenSource/wxWidgets/include/wx/stc/stc.h:5769:30: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]`
(Just an example)

This seems a relatively recent change to me. I'm not sure if it's a change on wxWidgets side or if XCode simply added this warning as default in recent versions (Haven't checked XCode only build). 

Adding `-Wno-shorten-64-to-32` to the cmake compiler flags obviously silences this warning. I could do a PR doing this just wanted to make sure if it's the right thing to do.

Compiler command line looks like this:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.10 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Debug\" -DWX_PRECOMP -D__WXOSX_COCOA__ -D__WXMAC__ -D__WXOSX__ -DWXUSINGDLL -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/user/Library/Developer/Xcode/DerivedData/wxWidgets-fonwnhhmlkxoejbelqrozyumfjoi/Index.noindex/DataStore -I/Users/user/Development/OpenSource/wxbuild_macos/lib/Debug/include -I/Users/user/Development/OpenSource/wxWidgets/samples -I/Users/user/Development/OpenSource/wxbuild_macos/lib/wx/include/osx_cocoa-unicode-3.3 -I/Users/user/Development/OpenSource/wxWidgets/include -I/Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/DerivedSources-normal/x86_64 -I/Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/DerivedSources/x86_64 -I/Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/DerivedSources -F/Users/user/Development/OpenSource/wxbuild_macos/lib/Debug -fPIE -Wall -Wundef -Wunused-parameter -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-ctor-dtor-privacy -Woverloaded-virtual -pthread -std\=gnu++11 -MMD -MT dependencies -MF /Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/Objects-normal/x86_64/webview.d --serialize-diagnostics /Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/Objects-normal/x86_64/webview.dia -c /Users/user/Development/OpenSource/wxWidgets/samples/webview/webview.cpp -o /Users/user/Development/OpenSource/wxbuild_macos/build/webviewsample.build/Debug/Objects-normal/x86_64/webview.o -index-unit-output-path /webviewsample.build/Debug/Objects-normal/x86_64/webview.o`

### Platform and version information

- wxWidgets version 3.3.0
- wxWidgets port wxOSX
- OS macOS 12
- Compiler XCode 14.2

**Comment by vadz** [comment]
It looks like it's due to a change in Xcode because this code (passing `long y` to `LineLength()` taking `int`) was there since quite some time.

Unfortunately confusion between `int` and `long` in wx is so widespread that it's going to be difficult to do anything other than suppressing the warning to fix it...
