### ISSUE TITLE
cmake build problem on windows using mingw

### ISSUE THREAD

**Issue by wxmeng04** [wxWidgets/wxWidgets#23330]
### Description

 I'm using cmake and mingw64 on windows. Just use cmakegui.exe as recommended to configure the build and I select a new path for CMAKE_INSTALL_PREFIX other than the default which is "C:\Program Files (x86)". Then click "configure" and "generate". after that I change into the build directory and run "cmake --build ." and "cmake --install.". Everything is fine and the static lib is installed in the directory as I expected.  But from then on disaster comes. I prepere a first project which includes `CMakeList.txt`. The problem is with the following instruction in the `CMakeList.txt` file I've prepared:
```
find_package(wxWidgets REQUIRED COMPONENTS net core base CONFIG)
message("wxWidgets_FOUND ${wxWidgets_FOUND}")
message("wxWidgets_USE_FILE ${wxWidgets_USE_FILE}")
include(${wxWidgets_USE_FILE})
```
the error is quite wierd.
```
wxWidgets_FOUND=1
wxWidgets_USE_FILE=
```
when calling `include` there is error reporting wrong number of args because wxWidgets_USE_FILE is null. 
Everthing seems correct at the beginning but suddenly goes out of control. I don't know if the tool chain is supported by the project.

### Platform and version information

- wxWidgets version  you are building: 3.2.1.1
- wxWidgets port  you are building: wxMSW
- OS  and its version: Windows 10
- Compiler  being used: gcc in mingw64 package.

**Comment by vadz** [comment]
I hope someone else has some idea about this, because I have no idea where is `wxWidgets_USE_FILE` even supposed to be defined.

One thing I can say is that using paths with spaces (such as "C:\Program Files (x86)") is just asking for trouble and that I'd recommend not doing it unless you want to make your life more interesting.

**Comment by wxmeng04** [comment]
> I hope someone else has some idea about this, because I have no idea where is `wxWidgets_USE_FILE` even supposed to be defined.
> 
> One thing I can say is that using paths with spaces (such as "C:\Program Files (x86)") is just asking for trouble and that I'd recommend not doing it unless you want to make your life more interesting.

it's documented in `wxWidget\docs\doxygen\overviews\cmake.md`. i copied from it.

**Comment by vadz** [comment]
Yes, I know that it's documented there, but it's not clear where is this variable supposed to be set. I _think_ it's done in the standard CMake `findwxWidgets.cmake` module, so you'd probably need to debug it there. Also, try using the latest CMake version if you are not using it yet.

**Comment by wxmeng04** [comment]
> Yes, I know that it's documented there, but it's not clear where is this variable supposed to be set. I _think_ it's done in the standard CMake `findwxWidgets.cmake` module, so you'd probably need to debug it there. Also, try using the latest CMake version if you are not using it yet.

It's the latest version downloaded yesterday. I build again with makefile.gcc and get below folder. By every mean the build is correct. FindwxWidgets.cmake as I remember doesn't works if CONFIG is set in the find_package() function. It's pointed out in the document `cmake.md` mentioned above.
```
$ dir
libwxbase33u.a      libwxmsw33u_core.a      libwxmsw33u_webview.a
libwxbase33u_net.a  libwxmsw33u_gl.a        libwxmsw33u_xrc.a
libwxbase33u_xml.a  libwxmsw33u_html.a      libwxpng.a
libwxexpat.a        libwxmsw33u_media.a     libwxregexu.a
libwxjpeg.a         libwxmsw33u_propgrid.a  libwxscintilla.a
libwxlexilla.a      libwxmsw33u_ribbon.a    libwxtiff.a
libwxmsw33u_adv.a   libwxmsw33u_richtext.a  libwxzlib.a
libwxmsw33u_aui.a   libwxmsw33u_stc.a       mswu
```

**Comment by vadz** [comment]
Sorry, I don't understand what are you trying to say. Just to be clear, I don't know what the problem is, so I'm just trying to help you to try to solve it yourself. To summarize:

1. Try not using a path with spaces.
2. Try using the latest CMake version.
3. If it still fails, try debugging `FindwxWidgets.cmake` to see why is `wxWidgets_USE_FILE` not set there.

Good luck!

**Comment by PBfordev** [comment]
I don't have any experience with it, but CMake provides command line parameters [--debug-find](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-debug-find) and various --trace-* options. Perhaps running CMake with those parameters could shed a light on the issue.

I will try later to see if it works for me.

**Comment by wxmeng04** [comment]
> If you use `CONFIG` mode, then there is no `wxWidgets_USE_FILE`. This is only something that CMake's [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) provides. `CONFIG` mode does not use `FindwxWidgets`, instead it checks the install directory for configuration files. In `CONFIG` mode you only need `target_link_libraries(${PROJECT_NAME} ${wxWidgets_LIBRARIES})`, like the [minimal sample](https://github.com/wxWidgets/wxWidgets/blob/master/samples/minimal/CMakeLists.txt) does.
> 
> `CONFIG` mode is only available when you build and install wxWidgets yourself using CMake, because we generate and install the required config files. When you build using `makefile.gcc` there won't be any config files.
> 
> Probably should update `cmake.md` and remove `include(${wxWidgets_USE_FILE})` and use `target_include_directories(myapp PRIVATE ${wxWidgets_INCLUDE_DIRS})` instead. Since the former also has some side effects like modifying the global `CMAKE_CXX_FLAGS`.

Fully agree with you. I think not only myself thinking `include(${wxWidgets_USE_FILE})` as mandatory. The normal users even don't know how to debug the `CMakeLists.txt` file like me.

**Comment by wxmeng04** [comment]
> > If you use `CONFIG` mode, then there is no `wxWidgets_USE_FILE`. This is only something that CMake's [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) provides. `CONFIG` mode does not use `FindwxWidgets`, instead it checks the install directory for configuration files. In `CONFIG` mode you only need `target_link_libraries(${PROJECT_NAME} ${wxWidgets_LIBRARIES})`, like the [minimal sample](https://github.com/wxWidgets/wxWidgets/blob/master/samples/minimal/CMakeLists.txt) does.
> > `CONFIG` mode is only available when you build and install wxWidgets yourself using CMake, because we generate and install the required config files. When you build using `makefile.gcc` there won't be any config files.
> > Probably should update `cmake.md` and remove `include(${wxWidgets_USE_FILE})` and use `target_include_directories(myapp PRIVATE ${wxWidgets_INCLUDE_DIRS})` instead. Since the former also has some side effects like modifying the global `CMAKE_CXX_FLAGS`.
> 
> Fully agree with you. I think not only myself thinking `include(${wxWidgets_USE_FILE})` as mandatory. The normal users like me even don't know how to debug the `CMakeLists.txt` file.

As you said, I correct the `CMakeLists.txt` file and the compile go through. Issue is closed. Thank you so much!
```
find_package(wxWidgets REQUIRED COMPONENTS net core base CONFIG)
add_executable(main bombs.cpp bombs1.cpp game.cpp bombs.rc)
target_include_directories(main PRIVATE ${wxWidgets_INCLUDE_DIRS})
target_link_libraries(main PRIVATE ${wxWidgets_LIBRARIES})
```
