### ISSUE TITLE
cannot find wx/setup.h

### ISSUE THREAD

**Issue by wieniawski-lai** [wxWidgets/wxWidgets#23346]
hi,

I have downloaded wxWidgets3.0.5 source file and build, which install to /opt/wxWidgets on linux.
- make
- make install
- ldconfig

And I am using codeblocks to create a demo project for wxWidgets, however, it reported while building:
cannot find wx/setup.h in platform.h

I resolved this error on windows by changing `#include "wx/setup.h"` to `#include "wx/msw/setup.h"` in platform.h

However, in linux (OpenSuse15.4), there is no file named setup.h under wx folder.

How can I solve this problem?

thx.

**Comment by vadz** [comment]
Your "fix" under Windows is wrong, please don't do it, this will result in worse problems in the future. You need to use the correct `wx/setup.h` located under the `lib` directory. The exact path depends on the compiler/build you use.

Under Linux it's much simpler and you just need to use wx-config as [explained in the docs](https://docs.wxwidgets.org/3.2/plat_gtk_install.html#gtk_new_project).

Also consider using 3.2 instead of the very old 3.0 for new development.

**Comment by wieniawski-lai** [comment]
> Your "fix" under Windows is wrong, please don't do it, this will result in worse problems in the future. You need to use the correct `wx/setup.h` located under the `lib` directory. The exact path depends on the compiler/build you use.
> 
> Under Linux it's much simpler and you just need to use wx-config as [explained in the docs](https://docs.wxwidgets.org/3.2/plat_gtk_install.html#gtk_new_project).
> 
> Also consider using 3.2 instead of the very old 3.0 for new development.

Under windows, do you mean I should use
- wxWidgets-3.0.5\lib\gcc_dll\mswu\wx\setup.h, while dynamic link using MinGW in release version
- wxWidgets-3.0.5\lib\gcc_dll\mswud\wx\setup.h while dynamic link using MinGW in debug version
- wxWidgets-3.0.5\lib\gcc_lib\mswu\wx\setup.h while static link using MinGW in release version
- wxWidgets-3.0.5\lib\gcc_lib\mswud\wx\setup.h while static link using MinGW in debug version

**Comment by vadz** [comment]
Yes, you need to use `-I` option with the appropriate path so that the correct `wx/setup.h` is found.

**Comment by PBfordev** [comment]
> Under windows, do you mean I should use

As described in [the docs](https://docs.wxwidgets.org/3.2/plat_msw_install.html#msw_build_apps), you need to add two folders to the compiler include folders:
1. The generic include folder, e.g., `c:\wxWidgets-3.0.5\include`.
1. The build specific folder, e.g., `c:\wxWidgets-3.0.5\lib\gcc_dll\mswud` (for the dynamic debug build) or `c:\wxWidgets-3.0.5\lib\gcc_lib\mswu` (for the static release build).

Then, your command line for the dynamic debug build could look like this
`g++.exe  -Ic:\wxWidgets-3.0.5\include -Ic:\wxWidgets-3.0.5\lib\gcc_dll\mswud <...more parameters>`

This guarantees the correct setup.h will be picked.

**Comment by wieniawski-lai** [comment]
> Yes, you need to use `-I` option with the appropriate path so that the correct `wx/setup.h` is found.

great thx

**Comment by wieniawski-lai** [comment]
> Your "fix" under Windows is wrong, please don't do it, this will result in worse problems in the future. You need to use the correct `wx/setup.h` located under the `lib` directory. The exact path depends on the compiler/build you use.
> 
> Under Linux it's much simpler and you just need to use wx-config as [explained in the docs](https://docs.wxwidgets.org/3.2/plat_gtk_install.html#gtk_new_project).
> 
> Also consider using 3.2 instead of the very old 3.0 for new development.

I am trying on linux now.

### hello world example
First of all, I tried the [hello world example](https://docs.wxwidgets.org/latest/overview_helloworld.html). And I saved it in hello.cpp. I am using
```shell
g++ hello.cpp `wx-config --cxxflags --libs` -o hello
```
Then I can successfully build, and `./hello` is OK to run.

### codeblocks setting
Then I changed to codeblocks(linux), as [wxWidgets wiki](https://wiki.wxwidgets.org/CodeBlocks_Setup_Guide) said, I add 2 options in codeblocks' build option:
![image](https://user-images.githubusercontent.com/70927596/224987482-26bfd398-65ce-4338-bd8f-57b35523351d.png)

However, it seems not effect. while the build log is
`g++ -Wall -g -I../../../../../opt/wxWidgets/include/wx-3.0 -c /home/schoenberg/work/wxWidgets/demo/demoApp.cpp -o obj/Debug/demoApp.o`

You can see the command `wx-config --cxxflags --libs` is not added.

what is wrong?

### wx-config
I guess wx-config is a small tool to align the setup.h file. Then where can I find the source code?
I searched `wxWidgets/utils` and without success.

### wx-config windows
[wxWidgets wiki](https://wiki.wxwidgets.org/Wx-config_Windows_port) also said that there is an windows porting of wx-config.
And it is saved on [google](https://sites.google.com/site/wxconfig/). However I failed to download from the [link](http://wx-config-win.googlecode.com/svn/binary/wx-config.exe). I guess it is too old.
Have you ever use it?
How can I find the correct download path?

thx

**Comment by vadz** [comment]
There is nothing wrong with not using the libraries when _compiling_.

There is no official `wx-config` for MSW. You need to enter the build paths on your own there.

**Comment by wieniawski-lai** [comment]
> There is nothing wrong with not using the libraries when _compiling_.
> 
> There is no official `wx-config` for MSW. You need to enter the build paths on your own there.

en, thx
1. where is the official source code of wx-config?
2. I found someone write a [windows wx-config](https://github.com/stahta01/cb_projects_for_wxWidgets/)

**Comment by asmwarrior** [comment]
https://github.com/eranif/wx-config-msys2

This project supply a more recent wx-config, it has a `wx-config.exe` and `wx-config-msys2.exe` for different usage.

**Comment by MaartenBent** [comment]
And the source of `wx-config` is https://github.com/wxWidgets/wxWidgets/blob/master/wx-config.in
