### ISSUE TITLE
Error when trying to work with shapefusion 

### ISSUE THREAD

**Issue by noisetta** [wxWidgets/wxWidgets#23348]
I'm trying to get shapefusion 0.6 to run but I need wxwidgets (which I have, version 3.0.5). 
I'm on linux mint 21.1

**when i try to compile shapefusion 0.6 i get various errors, for example:** 
PhysicsDocument.cpp:39:38: error: class ‘PhysicsDocument’ does not have any field named ‘wxDocument’
   39 | PhysicsDocument::PhysicsDocument() : wxDocument(), PhysicsElement(true)
      |                                      ^~~~~~~~~~
PhysicsDocument.cpp: In member function ‘bool PhysicsDocument::DoOpenDocument(const wxString&)’:
PhysicsDocument.cpp:50:23: error: ‘wxDocument’ has not been declared
   50 |         bool wxOpen = wxDocument::DoOpenDocument(file);
      |                       ^~~~~~~~~~
make[2]: *** [Makefile:257: PhysicsDocument.o] Error 1
make[2]: Leaving directory '/home/buns/Downloads/Marathon Sounds/shapefusion-0.6/Physics'
make[1]: *** [Makefile:417: all-recursive] Error 1
make[1]: Leaving directory '/home/buns/Downloads/Marathon Sounds/shapefusion-0.6'
make: *** [Makefile:282: all] Error 2

**I'm trying to compile wxwidgets 3.2.2.1 but I'm getting the following errors as well:**
make: /home/buns/Downloads/Marathon: No such file or directory
make: *** [Makefile:37244: gldll_glcmn.o] Error 127

(the "Marathon" directory does exist, I'm not sure why it's saying that)

(_I know this forum is about wxwidgets and I'm posting about another program as well but I don't know where to find support for that (I don't believe they have a channel_))

If someone could help me resolve this , it would be greatly appreciated.

**Comment by vadz** [comment]
We can't provide support for all programs using wxWidgets, even if it's unfortunate that they don't provide support themselves.

All I can say is that `wxDocument` is declared in `wx/docview.h` header, so the error most likely means that it hasn't been included, but beyond this you're really on your own, sorry.
