### ISSUE TITLE
Incorrect positioning and graphical artifacts of wxStaticBoxSizer with empty text label when WX_MSW_DARK_MODE is active (wxMSW))

### ISSUE THREAD

**Issue by k-serg** [wxWidgets/wxWidgets#23342]
### Description

Incorrect positioning and graphical artifacts of wxStaticBoxSizer with empty text label when WX_MSW_DARK_MODE is active.

**Steps to reproduce:**

1. Enable wxMSWDarkMode by set env var SET WX_MSW_DARK_MODE=2.
2. Edit any samples that uses wxStaticBoxSizer by replacing "Some Label" with wxEmptyString (wrapsizer for example).
3. Seeing incorrect positioning (extra space at top side wxStaticBoxSizer).
4. Seeing graphical artifacts at normally (non empty) label place.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10.0.19044 64 bit

Screenshots attached:

![Image 2023-03-13 01 56 06](https://user-images.githubusercontent.com/76852271/224576831-cc9da1de-c596-41e6-9f12-55f5d5ff7a96.png)
![Image 2023-03-13 01 57 27](https://user-images.githubusercontent.com/76852271/224576838-b8abaa2b-1f90-4c30-a5e7-51cf338375c1.png)

**Comment by vadz** [comment]
Thanks, I indeed see both problems and they're fixed by the PR above for me. Please let me know if you still see anything wrong with it.

**Comment by k-serg** [comment]
> Thanks, I indeed see both problems and they're fixed by the PR above for me. Please let me know if you still see anything wrong with it.

Thanks for quick respond, it looks much better for now, but still looks different, in terms of positioning (extra space are too small in Dark Mode). Screenshot attached. Should I use extra code (different border values for normal/dark modes), to fixing this, or we have any chance to similar behaviour in both modes?
![Image 2023-03-13 13 54 09](https://user-images.githubusercontent.com/76852271/224669311-5b783664-e482-4bcc-bd81-528b83c97d02.png)

**Comment by vadz** [comment]
I've updated the PR with the fix for the problem above.

@eranif I've removed the extra `LABEL_VERT_BORDER` margin you used in the original version of the code as it seems to be unnecessary and inconsistent with the default appearance, but please let me know if I'm missing something (e.g. perhaps it's only needed under Windows 11?).
