### ISSUE TITLE
wxMessageDialog does show wrong icon (or not showing at all)

### ISSUE THREAD

**Issue by nourgaliev** [wxWidgets/wxWidgets#23353]
wxMessageDialog does not show icons correctly, on Mac and some Linux systems (I am using RedHat toss3). See forum discussion at 

https://forums.wxwidgets.org/viewtopic.php?f=23&t=50220&p=217951#p217951

Note, that wxRichMessageDialog is fine.

**Comment by nourgaliev** [comment]
So why wxRichMessageDialog, which derived from this, is working properly? It does show appropriate icons on both Mac and Linux.

**Comment by vadz** [comment]
On these platforms `wxRichMessageDialog` uses a generic implementation not using the native dialog.

**Comment by nourgaliev** [comment]
On related issue: I started using wxRichMessageDialog, something like this: 

            wxRichMessageDialog dialog (this,
                                        wxT("Mesh file exists! Proceed to overwrite?"),
                                        wxT("Please confirm"),
                                        wxYES_NO|wxCENTRE|wxICON_HAND);


dialog.ShowModal()  returns 5103 on YES and 5104 on NO, while I thing the values should be 2 (wxYES) and 8 (wxNO). This is on both Mac and Linux. I could hard code these - but is it a bug - or I am doing something wrong here?

**Comment by vadz** [comment]
No, this is not a bug, the dialog returns `wxID_YES` and `wxID_NO`, just as `wxMessageDialog` does.

This is already documented:

https://github.com/wxWidgets/wxWidgets/blob/8ad0f52da034b1295b7cabf278e833a4941694d2/interface/wx/msgdlg.h#L266-L267

which just goes to show that documenting things is not always enough...

But yes, it should still be done for the icons.

P.S. Please open separate issues for other problems.
