### ISSUE TITLE
dedup_flags in configure is wrong

### ISSUE THREAD

**Issue by pietvo** [wxWidgets/wxWidgets#23356]
### Description

I discovered this problem when installing wxPython on MacOS with macports.

`dedup_flags` is supposed to eliminate duplicate `-arch xxx` or `-framework xxx` entries in compiler options. For example, if 
`CFLAGS='-arch arm64 -arch x86_64 -arch  x86_64 -framework IOKit'`,

`dedup_flags $CFLAGS` should return 

`-arch arm64 -arch x86_64 -framework IOKit'` (the second ` -arch  x86_64` removed).

However, instead it returns `-arch arm64 -arch x86_64 -arch  -framework IOKit'`, which is an error. 

Here is a patch. I applied the patch directly to `configure`, but it should of course be applied to `configure.in`.

```
--- configure.~1~
+++ configure
@@ -45456,8 +45456,11 @@
 dedup_flags()
 {
     printf "%s " "$@" |
-        awk 'BEGIN { RS=" "; ORS=" " }
-            { if ($0=="-arch" || $0=="-framework" || !seen[$0]++) print }'
+        awk '{for (i=1; i<=NF ; i++)
+    if ($i=="-arch" || $i=="-framework") {
+        ++i; if (seen[$i]++) {$i = ""; $(i-1) = ""}
+    }
+    print}'
 }
 
 WX_CPPFLAGS=`dedup_flags "$CPPFLAGS"`


```
### Platform and version information

- wxWidgets version  you are building: 3.2.2
- wxWidgets port  you are building: wxOSX
- OS  and its version: MacOS 13.2.1 (Ventura)
- Compiler  being used: clang

**Comment by vadz** [comment]
Thanks to Paul for fixing this in master, I've also pushed it to 3.2 now.
