### ISSUE TITLE
build lib installed in lib64

### ISSUE THREAD

**Issue by wieniawski-lai** [wxWidgets/wxWidgets#23351]
### Description
while using
```shell
./configure --prefix=/opt/wxWidgets
make
make install
```
the library files will be installed to `/opt/wxWidgets/lib64` instead of `/opt/wxWidgets/lib64` 
However, if I `./configure --prefix=/opt/wxWdigets --build=i386-pc-linux`, the library files still installed to lib64.

My questions, why it is installed in lib64, not lib?
How can I install to lib?

### Platform and version information

- wxWidgets version 3.2.2.1
- OS OpenSuse15.4
- Compiler gcc7.5

**Comment by oneeyeman1** [comment]
@wieniawski-lai ,
Why do you want them inside lib? What difference does it make?
When you build your code you should use wx-config which should correctly identify the placement of the library.

Thank you.

**Comment by wieniawski-lai** [comment]
> @wieniawski-lai , Why do you want them inside lib? What difference does it make? When you build your code you should use wx-config which should correctly identify the placement of the library.
> 
> Thank you.

en,
first of all, you are right, it doesnot matter where they are located. I just need to use wx-config to set the correct path of lib.

to be honest, the first time I build wxWidgets, the lib files are installed under lib folder.
However, when I debug sth. in codeblocks, and I need to rebuld it. Then I found the lib files are installed under lib64.
And I can not repeat the first time's result.
I just wanna make clear what happens and why.

**Comment by vadz** [comment]
Using `--build=i386-pc-linux` doesn't make much sense, you probably wanted to use `--host`, as this option still produces 64-bit binaries.

As for `lib64`, this is what openSUSE uses for 64-bit systems. Other Linux distributions use `lib`, wxWidgets just uses the default.

There is really no problem here in any case.

**Comment by wieniawski-lai** [comment]
> Using `--build=i386-pc-linux` doesn't make much sense, you probably wanted to use `--host`, as this option still produces 64-bit binaries.
> 
> As for `lib64`, this is what openSUSE uses for 64-bit systems. Other Linux distributions use `lib`, wxWidgets just uses the default.
> 
> There is really no problem here in any case.

thx
