### ISSUE TITLE
wxPropertyGrid tab traversal issue under wxGTK

### ISSUE THREAD

**Issue by adrianlopezroche** [wxWidgets/wxWidgets#23354]
### Description
Summary: Tab traversal from wxPropertyGrid doesn't work across wxPanel instances. It also fails when the property grid is followed by a static control such as wxStaticText or wxStaticLine.

### Detailed Description
Ordinarily a user may navigate between controls, even across different panels, by pressing the tab key. However, adding a property grid can sometimes break the navigation chain such that pressing the tab key won't advance keyboard focus past the property grid. The problem is that to get around peculiarities in GTK's handling of keyboard focus the property grid is programmed to find its next sibling and set focus to it directly, which is fine when the grid is followed by a focusable control but otherwise leads to incorrect behavior.

The file propgrid.cpp (inside src/propgrid) includes the following code (wxWidgets 3.2.2.1):

```
// Tab traversal workaround for platforms on which
// wxWindow::Navigate() may navigate into first child
// instead of next sibling. Does not work perfectly
// in every scenario (for instance, when property grid
// is either first or last control).
#if defined(__WXGTK__)
    wxWindow* sibling = mainControl->GetNextSibling();
    if ( sibling )
        sibling->SetFocusFromKbd();
#else
    Navigate(wxNavigationKeyEvent::IsForward);
#endif
```

This code has two problems. First, the code doesn't check whether the sibling accepts focus or not. So if the property grid is followed by a wxStaticText or wxStaticLine control, for example, it will focus on that instead of the next focusable control. Second, navigation is confined to the current parent; focus may transfer between siblings, but it will never leave the parent control.

The first of these issues can be fixed by iterating through the siblings until either a sibling is found that accepts keyboard focus or the list is exhausted, but that doesn't help with the second issue. What I have found in testing possible fixes is that calling Navigate() on the property grid with no rows selected will work as desired, but calling Navigate() after a row has been selected will either transfer focus to the edit control (which is desirable) or transfer focus from the edit control back to the property grid (which is not desirable, hence the need for a special case for wxGTK in the code above).

Calling SetFocus() on the property grid followed by Navigate() allows focus to proceed as expected:

```
// Tab traversal workaround for platforms on which
// wxWindow::Navigate() may navigate into first child
// instead of next sibling. Does not work perfectly
// in every scenario (for instance, when property grid
// is either first or last control).
#if defined(__WXGTK__)
    SetFocus();
    Navigate(wxNavigationKeyEvent::IsForward);
#else
    Navigate(wxNavigationKeyEvent::IsForward);
#endif
```

... or, more simply:

```
// Tab traversal workaround for platforms on which
// wxWindow::Navigate() may navigate into first child
// instead of next sibling. Does not work perfectly
// in every scenario (for instance, when property grid
// is either first or last control).
#if defined(__WXGTK__)
    SetFocus();
#endif

Navigate(wxNavigationKeyEvent::IsForward);
```

With the code above wxGTK appears to behave as expected, but I haven't tested whether this has any undesired side effects so I'm submitting this as an issue rather than a pull request (which would basically consist of the second or third snippet above together with its counterpart for backwards navigation). I can confirm that the propgrid sample that comes with wxWidgets still works as expected after this change, but I otherwise don't know enough about wxWidgets to know if this would cause any new issues.

### Test program
Patch against samples/propgrid/propgrid_minimal.cpp: 
[propgrid_minimal.cpp.txt](https://github.com/wxWidgets/wxWidgets/files/10998538/propgrid_minimal.cpp.txt)

### Platform and version information

- wxWidgets version 3.2.2.1.
- wxGTK.
- Linux Mint 20
- GTK 3.24.20-0ubuntu1.1.

**Comment by vadz** [comment]
Thanks for exploring this. Ideally we wouldn't need to call `SetFocus()` neither (perhaps `Navigate()` should do it in wxGTK?), but it's not a huge problem, so if this is enough to fix TAB navigation, I'd just apply this -- but I'll let @a-wi decide.

**Comment by a-wi** [comment]
The patch looks good and seems to do the job.
@adrianlopezroche Could you also fix Shift-Tab handling just like you did with Tab?  And please to get rid of no longer used `mainControl` variable. Please feel free to create a PR with your fixes - it's the easier way to proceed.

**Comment by adrianlopezroche** [comment]
I've submitted a pull request (https://github.com/wxWidgets/wxWidgets/pull/23358) for this issue.

**Comment by vadz** [comment]
This will need to be backported to 3.2 if we don't find any problems with it in master.
