### ISSUE TITLE
Ensure that clipping is enabled when SetDeviceClippingRegion() is called

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#23357]
### Description

![Screenshot_20230317_181246](https://user-images.githubusercontent.com/7704771/225979222-54df8a7e-4d83-4782-80e1-a69114f2ef0f.png)

From the image above you can see that the multicells (**Big box!** for example) is not rendered correctly!
and the correct rendering should look like this:

![Screenshot_20230317_182054](https://user-images.githubusercontent.com/7704771/225981235-81d34291-76da-45ff-8dfc-863f3b01b280.png)

I still don't know what's causing it, maybe a bug in the `wxGrid` implementation?
but with this patch:
```
diff --git a/src/qt/dc.cpp b/src/qt/dc.cpp
index 62b2b80fc8..40352045c8 100644
--- a/src/qt/dc.cpp
+++ b/src/qt/dc.cpp
@@ -477,6 +477,8 @@ void wxQtDCImpl::DoSetDeviceClippingRegion(const wxRegion& region)
     }
     else
     {
+        m_qtPainter->setClipping( true );
+
         QRegion qregion = region.GetHandle();
         // Save current origin / scale (logical coordinates)
         QTransform qtrans = m_qtPainter->worldTransform();

```
the problem is gone.

In fact, there is another bug related to clipping a multicells to be correctly rendered, by applying a second patch:
```
diff --git a/src/generic/grid.cpp b/src/generic/grid.cpp
index ec5b579a42..2e0ba1a827 100644
--- a/src/generic/grid.cpp
+++ b/src/generic/grid.cpp
@@ -6841,6 +6841,10 @@ void wxGrid::DrawAllGridWindowLines(wxDC& dc, const wxRegion & WXUNUSED(reg), wx
                 {
                     case CellSpan_Main:
                         rect = CellToRect(j,i);
+#ifdef __WXQT__
+                        rect.width -= 1;
+                        rect.height -= 1;
+#endif
                         rect.Offset(-gridOffset);
                         CalcScrolledPosition( rect.x, rect.y, &rect.x, &rect.y );
                         clippedcells.Subtract(rect);
@@ -6848,6 +6852,10 @@ void wxGrid::DrawAllGridWindowLines(wxDC& dc, const wxRegion & WXUNUSED(reg), wx
 
                     case CellSpan_Inside:
                         rect = CellToRect(j + cell_rows, i + cell_cols);
+#ifdef __WXQT__
+                        rect.width -= 1;
+                        rect.height -= 1;
+#endif
                         rect.Offset(-gridOffset);
                         CalcScrolledPosition( rect.x, rect.y, &rect.x, &rect.y );
                         clippedcells.Subtract(rect);

```
Otherwise, the **griddemo** would look like this:

![Screenshot_20230317_181653](https://user-images.githubusercontent.com/7704771/225992284-a42d9e12-1052-40cd-a41e-8bba0b15d983.png)

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxQt (Qt version 5.5)
- OS  and its version: Ubuntu 18.04

**Comment by vadz** [comment]
I don't know Qt API, so if it requires calling `setClipping()` even if we already call `setClipRegion()`, we need to do it. I'm surprised the existing unit tests haven't detected this problem -- or are they not run for wxQt?

For the second problem, I'd prefer to also find the problem in wxQt code and fix it there as it seems like there should be one if the existing code works correctly in the other ports but is off by 1 there.

**Comment by vadz** [comment]
Should I already apply the `setClipping()` change or will you make it part of a later PR? Please let me know what would be more convenient for you.

**Comment by AliKet** [comment]
> Should I already apply the `setClipping()` change or will you make it part of a later PR?

There are other issues found when running the test suite locally that I also want to fix in a few days and do a PR for that, thanks.
