### ISSUE TITLE
Documentation including source files

### ISSUE THREAD

**Issue by CBtiger** [wxWidgets/wxWidgets#23350]
A famous wxForum user features the sentence "Use the source, Luke!". I have done that many times and it takes hours to find out where certain structs or classes are situated and where dependent classes are - at least when doing that manually with a file manager between the include and src folders with with no links. 

AFAIK Doxygen allows to include also the source files (CPP). The default setting is NO. 

So my suggestion is to provide a second CHM file with headers _and_ sources (much larger obviously) for people to download. It would allow while searching for answers to check the implementation of things directly in the CHM file. I think many people would benefit from that. My IDE would get such CHM file as default "F1" help for wxWidgets.

**Comment by PBfordev** [comment]
> it takes hours to find out where certain structs or classes are situated

Sorry, but I cannot agree with this. In my experience, it usually takes just a few seconds to locate the class implementation when using a file manager (using its search). If using an IDE, it is almost instant, with any decent IDE providing "Go to definition" or similar command. Very rarely, it could take minutes, if I did not know what I was really looking for. 

Moreover, Doxygen files are not generated from the actual source, as the documentation for various reasons often does not match actual implementation (not only due to different implementations between platforms using derived classes or PIMPL) but from the interface folder.

**Comment by CBtiger** [comment]
@PBforddev  thanks for your feedback and Interesting that you disagree about the problem. 

I should have said it takes _me_ hours. My experience is as normal wxWidgets user just knowing a bit about the wx internals. Searching in "include" for "wxChar" just got me 100 entries. Checking wxString the other day I went through 30 files
Working with MSVS in MSW may provide all you say. Maybe also in OSX with xCode. On Linux you don't get a ready IDE project to just open. There might not even be sources on the machine when only the repository dev version is used. Leaves FMs & text editors. Works, but not not quick and no logic support. 
Imho, quite an effort for a single function check on a class. Compared to 2 clicks in a such an CHM file. Thats my whole point.




I kind of expected that the different local versions would make it a bit difficult, but are you saying is technically not possible at all the way its setup today? 
Did you mean with "interface folder", the "include" folder?
There is a wide span from "perfect and fully consistent" to "not useful all all", e.g. all platform files could be omitted and it still would be very useful.

**Comment by SpareSimian** [comment]
My editor has an integrated grep function. I'd just do a word search for that string in all files matching "**/*.{cpp,h}" (** matches an arbitrary depth of directories in the glob expression). Lacking that, I could probably use a combination of find and grep on the command line. 

But if you really wanted a full Doxygen build, you could provide a patch with a suitable Doxyfile.

**Comment by CBtiger** [comment]
OK, I found the wxWidgets/doc/contributing and wxWidgets/doc/doxygenfile sections with some info about how the documentation is created. Maybe I can find out how it works or why not.


@PBforddev I saw you document on CB and MinGwW64 in Windows. Really nice. Do you happen to know how to setup a wxProject that can actually build wxWidgets? I could not come up with something that actually compiles?

**Comment by vadz** [comment]
Sorry, we're not doing this. It won't be helpful at all for what you want to do anyhow. What you really want is "Go to definition" function of your IDE.

**Comment by CBtiger** [comment]
@vadz 

Well, its fine that you do not support this. 

But "Go To definition" in my IDE does not bring me to the source file, just to the header (I'd be surprise if its different in others). "Go To Implementation" would but it does not as the wxSources are not included in the project, like in the minimal sample.

**Comment by PBfordev** [comment]
Sorry, I was wrong about Go to Definition for the library code, in MSVS 2020, it still goes to the header for `wxString`. But in hindsight, it seems obvious that I must have been wrong.

I think that an IDE generally has no idea where the source code for a library is. It probably only cares about location of headers for the compiler and code-completion and libraries for the linker. The debugger may know where the library sources are when debugging an application, as this information can (but may not) be stored somewhere (e.g., I suppose it is in the PDB files for MSVC).

Moreover, library sources are often not available, even for the OSS libraries, for example when using pre-built libraries from a package manager (such as MSYS2) or a CMake-installed library.

Lastly, it can be hard even to differentiate between the location of declaration and definition of a class, as the definition is often split into multiple files (e.g., some methods are defined inline in the .h file while some are defined in the .cpp file).
