### ISSUE TITLE
wxKill wxSIGTERM unit tests fail in Windows 11 in Head

### ISSUE THREAD

**Issue by MetalPlateMage** [wxWidgets/wxWidgets#23365]
I mentioned this figured I'd document it (feel free to remove if not important).

Results:
```
tests\exec\exec.cpp(202): FAILED:
  CHECK( rc == 0 )
with expansion:
  -1 == 0
exec.cpp(275): FAILED:
  CHECK( rc == 0 )
with expansion:
  -1 == 0
```

It has to do with how Notepad and some modern presentation apps work. EnumWindows fails completely to find a window, going through the process threads finds you a window with EnumThreadWindows (patch attached, I wouldn't apply it its just for show as what I hacked around with on Friday), but then Notepad - or the launching process - ignores WM_QUIT.

This goes into the deeper issue where when you launch a process on windows with modern presentation apps it only launches a hooking process. I'm not sure how to get the right process to kill, so to speak.

EDIT: Also, forgot to mention the wxSIGKILL test doesn't actually close Notepad either.. it remains open despite that test reporting success

**Comment by MetalPlateMage** [comment]
Also, forgot to mention the wxSIGKILL test doesn't actually Notepad either.. it remains open despite that test reporting success

**Comment by vadz** [comment]
This is pretty important and thanks for reporting it, but I'm not sure what to do about it. Do you have more information about the "modern presentation apps" way by chance? There must be _some_ way to terminate the process we launch ourselves, but perhaps we need to switch to using process handles instead of PIDs in order to do it?

**Comment by MetalPlateMage** [comment]
OK, so it's been a while since I've researched how "optimized" WPF apps work... specifically how Microsoft uses them. I mean my main hobby is working on a pet app for Mac system 6+7, which means I can't even use templates most of the time (though Retro68 is a thing now). Anyways....

So, when you launch notepad for the first time, it generally (and I say generally because it is murky and dependent on some algorithm is uses) creates 3 other notepad processes for what I believe is caching - sort of like how 4 socket servers serve a lot of clients these few processes service all notepad windows. The problem is these processes have no valid parent processes because they are launched by something else which doesn't exist anymore, so we can't enumerate them normally. I recall a way to do it in .Net from like 10 years ago, but I never used .Net/WPF in any of the apps I did so I dumped all that knowledge.

The other case (which is easier to handle) is that it spawns a single child process which is the gui process. However, the process launched by wxExec has no message loop so PostMessage won't do anything and killing that process will not kill notepad. Here's what it looks like:
https://imgur.com/qghKBxq

And here's what is looks like if wxKill does it on the parent, it just branches off:
https://imgur.com/8CqkkPt

After hacking around a bit I basically killed all the child processes of it, which isn't really correct, and the patch is awful but I've attached it just for demonstration; but at least it killed the notepad processes. The closing messages will kill notepad usually, so at least there aren't 100s of them open from unit tests :).
[wxkill.patch](https://github.com/wxWidgets/wxWidgets/files/11045753/wxkill.patch)

PostThreadMessage seems to help, it's what Windows does - it doesn't send it to a window just the thread's message queue. Usually WM_CLOSE/WM_ENDSESSION is enough though.

It walks through the processes and sees which is, or is a child of, the launched notepad process. Then it sends WM_CLOSE/WM_ENDSESSION to its top level window then a WM_QUIT to the thread queue, then waits for the first process it finds via OpenProcess. It's oldschool toolhelp traversal so it isn't super nice looking.

**Comment by vadz** [comment]
Using `PostThreadMessage()` looks like a good idea, but it still requires the thread to dispatch messages so, if I understand you correctly, using it in the current code isn't going to help, is it? If it does help, I'd be glad to merge a PR with this change if you could please make one.

> EDIT: It's imgur - if its small just right click open image in new window for the full size :)

It's probably just as simple (and better) to attach the images here, isn't it?

**Comment by MetalPlateMage** [comment]
> Using `PostThreadMessage()` looks like a good idea, but it still requires the thread to dispatch messages so, if I understand you correctly, using it in the current code isn't going to help, is it? If it does help, I'd be glad to merge a PR with this change if you could please make one.
> 

Nope still wouldn't help as the "real" notepad process(es) is something it spawns. It is the technically correct thing to do though as it is what Windows itself does.
