### ISSUE TITLE
XRC - wxRichTextCtrlXmlHandler missing from wxXmlResource::InitAllHandlers

### ISSUE THREAD

**Issue by bbronk01** [wxWidgets/wxWidgets#23381]
### Description
Using an XRC resource with `class="wxRichTextCtrl"` fails when trying to access the wxRichTextCtrl object.

```
// Line Below Fails as a null object is returned.
wxRichTextCtrl* pRichText = XRCCTRL(*this, "RICH_TEXT", wxRichTextCtrl);
```

### Workaround:
Manually add wxRichTextCtrlXmlHandler after calling InitAllHandlers.

```
#include "wx/xrc/xh_richtext.h"

//----------------------- Initializing XRC
wxXmlResource::Get()->InitAllHandlers();

//Manually add wxRichTextCtrlXmlHandler as it's missing from InitAllHandlers
wxXmlResource::Get()->AddHandler(new wxRichTextCtrlXmlHandler());
```
### Platform and version information

- wxWidgets version  you use: 3.1.4 (also present in trunk)
- wxWidgets port  you use:  wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
As explained in the note [in its docs](https://docs.wxwidgets.org/3.2/overview_xrcformat.html#xrc_wxrichtextctrl) you need to add it yourself because doing it in `InitAllHandlers()` would create a dependency on the richtext library in all applications using XRC.
