### ISSUE TITLE
VS Code can't include wx/wx.h file?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [wxWidgets/wxWidgets#23394]
### Description
I have compiled the wxWidgets via `mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=debug`
```
cannot open source file "../../../lib/vc_lib/mswud/wx/setup.h"
```
![image](https://user-images.githubusercontent.com/16663435/228411930-6623cd57-a35b-4ea1-8d37-ec4ff9c80485.png)
So why vscode can't find `wx/wx.h` file?
here is my c_cpp_properties.json file:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/src/**",
                "${env:WXWIN}/include/**",
                "${env:WXWIN}/lib/gcc_lib/mswud/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "D:\\software\\x86_64-7.3.0-release-win32-seh-rt_v5-rev0\\mingw64\\bin\\g++.exe",
            "cStandard": "c11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

### Platform and version information

- wxWidgets version **3.2.2.1**
- wxWidgets wxMSW
- OS Windows 10
- Compiler: MinGW-w64-x86_64-7.3.0-release-win32

**Comment by oneeyeman1** [comment]
@pigLoveRabbit520 ,
Can you successfully build and execute the project?

Thank you.

**Comment by PBfordev** [comment]
Please do not cross-post or report your problems with your build setup as actual wxWidgets bugs.

FWIW, I answered on the forum, before I noticed the cross-post.
