### ISSUE TITLE
Loading malformed GIF wxImage can cause crash

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23409]
(Just passing [the report](https://forums.wxwidgets.org/viewtopic.php?f=1&t=50271) from the forum)

### Description
When loading a GIF, `wxGIFDecoder::getcode()` does not account for function obtaining the block size, [`stream.GetC()`](https://github.com/wxWidgets/wxWidgets/blob/9b0ebf2c3a81cfddaa4933f5a2ae718638d82b8c/src/common/stream.cpp#L832), in malformed image unexpectedly returning `wxEOF`. `wxEOF` is defined as `-1`, while the variable for the block size `m_restbyte` is an `unsigned int`, resulting in the code attempting to write 4,294,967,295 bytes to a 256-byte `m_buffer`.
https://github.com/wxWidgets/wxWidgets/blob/9b0ebf2c3a81cfddaa4933f5a2ae718638d82b8c/src/common/gifdecod.cpp#L300-L316

### Expected vs observed behaviour:
I would expect the malformed GIF refused to be loaded without the application crashing; however, a crash happens due to overwriting memory. I have tried a couple of programs to view the GIF, none crashed and they all displayed a partial image.

### To Reproduce:
1. Download the attached image.
2. Run the image sample.
3. Press <Ctrl+O> and select the downloaded image.
4. Observe the sample to crash or just quietly close.

### Proposed fix
I think the simplest fix would be the image processing being stopped when `m_restbyte == (unsigned int)wxEOF`. However, I have no idea how should `wxGIFDecoder::getcode()`  tell `wxGIFDecoder::dgif()` that the image is invalid (i.e., what code to return). 

Another/better solution could be to just somehow deal with it and have the partial image as other programs do.

**Edit**
This simple change makes the crash go away and the image displayed in the sample:
```diff
diff --git a/src/common/gifdecod.cpp b/src/common/gifdecod.cpp
index 74d9adfbec..1325e0dd21 100644
--- a/src/common/gifdecod.cpp
+++ b/src/common/gifdecod.cpp
@@ -305,8 +305,11 @@ int wxGIFDecoder::getcode(wxInputStream& stream, int bits, int ab_fin)
              * an end-of-image symbol (ab_fin) they come up with
              * a zero-length subblock!! We catch this here so
              * that the decoder sees an ab_fin code.
+
+               We also need to account for a possibly malformed image,
+               where stream.GetC() unexpectedly returned wxEOF (i.e., -1).
              */
-            if (m_restbyte == 0)
+            if (m_restbyte == 0 || m_restbyte == (unsigned int)wxEOF)
             {
                 code = ab_fin;
                 break;

```
wxWidgets displays an error about GIF data being possibly truncated while none of the programs I tried shown any error. But IMO, showing the error where the image is malformed may not be a bad thing. 

**Malformed image:**
![malformed](https://user-images.githubusercontent.com/12495521/229077757-dfebe7a9-7b2d-4107-a0e2-e5b047df533d.gif)

**Comment by vadz** [comment]
FWIW ImageMagick identify reports:
```
bad.gif GIF 1200x800 1200x800+0+0 8-bit sRGB 256c 33KB 0.016u 0:00.015
identify: Corrupt image `bad.gif' @ error/gif.c/PingGIFImage/964.
```
so I agree that giving an error for it would be enough.

But we definitely need to fix this. The trouble is that I see several other occurrences of `GetC()` where we use it without checking if it returned EOF in this code. We could try fixing them manually but it would be really nice to fuzz this code by adding GIF fuzzer to `tests/fuzz`.

**Comment by PBfordev** [comment]
FWIW, I have found only one other place where the value of `stream.GetC()` is used without checking for `stream.Eof()` first:
https://github.com/wxWidgets/wxWidgets/blob/13ebaee247781b7cde1c830b36145aec9ab91127/src/common/gifdecod.cpp#L862-L867

The same fix as I did above (i.e., checking `bits` both for `0` and `wxEOF`) could be used there. However, I assume that `stream.GetC()` can return `wxEOF` when there was any error reading the stream, not just actually reaching its end.

I am not arguing against fuzzying the code (I have no idea how to do it) and/or any other solution. Since no one ran into this issue before, in all those years the code existed, there is probably no need to fix it ASAP.

BTW, Safari on my iPad is the only software that refused to display this invalid image at all, showing a question mark icon instead.

**Comment by vadz** [comment]
Thanks, I hoped to write more tests for this code, but I didn't have time for it, so finally I'm just going to apply (a slightly modified form of) your patch and include it in 3.2.3, as it's much better than holding on for a better solution, even if fuzzing this code would surely find more problems...

Thanks again!
