### ISSUE TITLE
propgrid.h should include textctrl.h

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#23414]
propgrid.h uses wxTextCtrl but does not include textctrl.h. This generates compilation errors in some circumstances, for example compiling Code::Blocks in Arch with wxWidgets current trunk (see [this forum post](https://forums.codeblocks.org/index.php/topic,25349.msg172686/topicseen.html#msg172686).

Although C::B could be patched to fix this, as proposed in the post, IMHO the best solution is including <wx/textctrl.h> in propgrid.h.

**Comment by vadz** [comment]
Thanks for reporting this, we definitely want to fix such problems (and ideal would be to have an automatic task checking that all headers can be included on their own...), but, as mentioned elsewhere, forward declaring it is a better solution, so I'll do this soon.
