### ISSUE TITLE
[MSW] wxUILocale::GetPreferredUILanguages() does not work as intended pre-Windows 10

### ISSUE THREAD

**Issue by BrianNixon** [wxWidgets/wxWidgets#23416]
[`GetUserDefaultLocaleName()`](https://learn.microsoft.com/windows/win32/api/winnls/nf-winnls-getuserdefaultlocalename) returns 0 on failure, not on success. The `!` should be removed.

https://github.com/wxWidgets/wxWidgets/blob/3.2/src/msw/uilocale.cpp#L459
https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/uilocale.cpp#L274

**Comment by vadz** [comment]
Oops, yes, indeed, thanks for noticing this!

cc @utelle just to let you know, but it really looks like a mistake in the original 8ab635b451c which added it.
