### ISSUE TITLE
Locale/language info minor bugs

### ISSUE THREAD

**Issue by BrianNixon** [wxWidgets/wxWidgets#23419]
Kashmiri (India) has a blank native description (though I don’t know what it should be).

The following are tagged as LTR; I suspect (though am far from certain) they should be RTL:
* Mazanderani
* Northern Luri
* Uzbek (Perso-Arabic)

There are some native descriptions which include mixed-direction text without direction markers:
* Northern Luri (Iran)
* Northern Luri (Iraq)

In some right-to-left layouts, these are rendered wrong because the opening bracket is interpreted in the prevailing right-to-left direction before the direction switches to left-to-right when the English text is encountered. Either ‘Iran’ and ’Iraq’ need translating, or there needs to be left-to-right direction marker for the opening bracket.

That said: my browser gets it right here:
* لۊری شومالی (Iran)
* لۊری شومالی (Iraq)

**Comment by vadz** [comment]
The table in `languageinfo.cpp` is generated from official Unicode consortium data, so I'm not sure why would it be wrong...

cc @utelle this one as well.

**Comment by BrianNixon** [comment]
Could wx be out of date, or have a buggy import?
https://github.com/unicode-org/cldr/blob/release-42/common/main/mzn.xml#L592

**Comment by utelle** [comment]
> The table in `languageinfo.cpp` is generated from official Unicode consortium data, [...]

Actually, `languageinfo.cpp` is generated from `misc/languages/langtabl.txt` (and `misc/languages/scripttabl.txt`) with the Python script `misc/languages/genlang.py`. However, the information in `misc/languages/langtabl.txt` is generated based on data from various sources, among them the [Unicode CLDR](https://cldr.unicode.org/), _Windows 10 locale data_, _ISO 639-3_, and _ISO 3166_.

Currently, the information about the **locale name** (English and native) and the **layout direction** are taken from the _Windows 10 locale data_ (as retrieved via the system functions [`EnumSystemLocalesEx()`](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-enumsystemlocalesex) and [`GetLocaleInfoEx()`](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getlocaleinfoex). 

Unfortunately, the Windows system functions return the **layout direction** as **LTR** for the locales

- Mazanderani (_mzn_)
- Northern Luri (_lrc_)
- Uzbek (Perso-Arabic) (_uz-Arab_)

According to the Unicode CLDR data this is wrong and should be **RTL**.

Regarding the locales

- Northern Luri (Iran) (_lrc-IR_)
- Northern Luri (Iraq) (_lrc-IQ_)

it would certainly be best to translate the country names, but unfortunately the CLDR territory data are incomplete for _Northern Luri_ and therefore the translations are unknown. That's most likely the reason why the Windows system function returns the English country names. The locale names are taken _as is_ from the Windows 10 locale data and don't contain any direction marker.

Regarding the locales

- Kashmiri (India) (_ks_, _ks-IN_)

they are listed only for compatibility with prior wxWidgets versions. The Windows 10 system functions return locale names for Kashmiri that have also an associated script (_Devanagari_ and _Arabic_). Most likely taking the _Devanagari_ description would be the most appropriate approach for the native description.

**Comment by utelle** [comment]
In the meantime I regenerated the list of locales via the system functions [EnumSystemLocalesEx()](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-enumsystemlocalesex) and [GetLocaleInfoEx()](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getlocaleinfoex) under **Windows _11_**. The data for the _layout direction_ for _Kashmiri_, _Mazanderani_, _Northern Luri_, and _Uzbek_ are now correct.

Note that the _Windows 10_ system I used to generate `misc/languages/langtabl.txt` had and has the latest system updates. Obviously, Microsoft decided in its infinite wisdom to **not** update the erroneous locale data in _Windows 10_.

I will regenerate `languageinfo.cpp` based on the _Windows 11_ data and will make a PR. Please allow a couple of days to let that happen.

**Comment by BrianNixon** [comment]
> taken from the _Windows 10 locale data_

Is that not a copyright issue?

> will make a PR

All right; thanks!

> Please allow a couple of days to let that happen

For me there’s no rush to get this fixed; these are just little bugs I happened to notice while tinkering with an application that (for better or worse) enumerates all the locales and displays them to the user to choose from.

**Comment by utelle** [comment]
> > taken from the _Windows 10 locale data_
> 
> Is that not a copyright issue?

No. Microsoft's _Open Specifications_ documentation explicitly allows to use and distribute portions of these data:

>>> **Copyrights**. This documentation is covered by Microsoft copyrights. Regardless of any other terms that are contained in the terms of use for the Microsoft website that hosts this documentation, you can make copies of it in order to develop implementations of the technologies that are described in this documentation and can distribute portions of it in your implementations that use these technologies or in your documentation as necessary to properly document the implementation. You can also distribute in your implementation, with or without modification, any schemas, IDLs, or code samples that are included in the documentation. This permission also applies to any documents that are referenced in the Open Specifications documentation.

The same is true for the ISO codes:

>>> **Using ISO Codes**. ISO allows free-of-charge use of its country, currency and language codes from ISO 3166, ISO 4217 and ISO 639, respectively.

Besides that items like English and native names of languages and countries can be extracted equally well from other sources like the ISO codes and the Unicode CLDR.

> > Please allow a couple of days to let that happen
> 
> For me there’s no rush to get this fixed; these are just little bugs I happened to notice while tinkering with an application that (for better or worse) enumerates all the locales and displays them to the user to choose from.

I doubt that a noteworthy number of users is actually affected by those bugs. Nevertheless, I will do my best to fix them.
