### ISSUE TITLE
wxGraphicsContext with wxView

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#23429]
### Description

The `wxView` class provides the `OnDraw` method to draw the contents of the associated `wxDocument`. Unfortunately its argument is `wxDC` which makes creating a `wxGraphicsContext` problematic:

```cpp

void DrawingView::OnDraw(wxDC *dc)
{
    dc->SetBackground(*wxWHITE_BRUSH);
    dc->Clear();

    wxGraphicsContext *gc = wxGraphicsContext::Create(*dc); // won't work

    // ...
}
```

One way to work around this is to use `wxDynamicCast` to call the correct method. This is ugly and possibly slow due to RTTI:

```cpp
wxGraphicsContext *DrawingView::GetGraphicsContext(wxDC *dc)
{
    wxWindowDC *windowDC = wxDynamicCast(dc, wxWindowDC);

    if (windowDC)
    {
        return wxGraphicsContext::Create(*windowDC);
    }

    wxMemoryDC *memoryDC = wxDynamicCast(dc, wxMemoryDC);

    if (memoryDC)
    {
        return wxGraphicsContext::Create(*memoryDC);
    }

    wxPrinterDC *printerDC = wxDynamicCast(dc, wxPrinterDC);

    if (printerDC)
    {
        return wxGraphicsContext::Create(*printerDC);
    }

    return nullptr;
}
```

It would be great if there were a way to use `wxGraphicsContext` in `wxView` without resorting to such workarounds.

**Comment by paulcor** [comment]
I think you could use `wxGraphicsContext::CreateFromUnknownDC()`.

**Comment by vadz** [comment]
Yes, `CreateFromUnknownDC()` was added exactly in order to avoid having to write stuff like above in the application code.

Unfortunately it still does exactly the same thing under the hood, i.e. the concern about it being potentially slow remains. I don't know if it's really noticeable compared to the time taken by the other DC operations, however. If somebody could measure it, i.e. whether the difference between using `CreateFromUnknownDC()` and `Create()` directly is noticeable, we could decide whether it's worth doing anything about it, i.e. adding `virtual wxGraphicsContext* CreateGC()` to `wxDC` itself.

**Comment by lszl84** [comment]
Thanks! I completely missed this one!

I did some quick tests on Mac M1 (don't have access to other platforms atm), and while `Create()` is 20% faster, both are very fast, so calling one or the other won't really matter I think.

```cpp

void MyFrame::Test()
{
    constexpr int iterations = 1000000;
    wxMemoryDC dc;

    auto start = std::chrono::steady_clock::now();
    for (int i = 0; i < iterations; i++)
    {
        wxGraphicsContext *gc = wxGraphicsContext::Create(dc);
        // delete gc;
    }
    auto end = std::chrono::steady_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();

    std::cout << "Create() average time: " << duration / static_cast<double>(iterations) << " usec. "
              << "Total time: " << duration << " usec"
              << std::endl;

    start = std::chrono::steady_clock::now();
    for (int i = 0; i < iterations; i++)
    {
        wxGraphicsContext *gc = wxGraphicsContext::CreateFromUnknownDC(dc);
        // delete gc;
    }
    end = std::chrono::steady_clock::now();
    duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();

    std::cout << "CreateFromUnknownDC() average time: " << duration / static_cast<double>(iterations) << " usec. "
              << "Total time: " << duration << " usec" << std::endl;
}
```

Results:

```
Create() average time: 0.218226 usec. Total time: 218226 usec
CreateFromUnknownDC() average time: 0.253936 usec. Total time: 253936 usec
```
