### ISSUE TITLE
Need build wxrc around clang bug : -Xlinker /implib:../myDir/myLib.lib not parsing '../' 

### ISSUE THREAD

**Issue by Khalyutin** [wxWidgets/wxWidgets#23428]
We are  suseful buld  wxWidgets 3.1.4 with  CMake & LLVM   "Unix Makefiles" for all paltform.
when we try buld wxWidgets 3.2.2.1 we have error  lld-link: error: could not open 'C:\TOOLSET\msys64\implib;..\lib\clang_x64_lib\wxrc.lib': no such file or directory.

I`m think that is clang bug : https://github.com/llvm/llvm-project/issues/61997

in 3.2.2.1  liune 104  file D:\source\COMPONENTS\GUI\wxWidgets-3.2.2.1\build\base\utils\CMakeFiles\wxrc.dir\build.make

generated as 	cd D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/utils && C:/TOOLSET/LLVM/bin/clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -Wall -Xclang -flto-visibility-public-std -g -O0 -gno-column-info                   -D_DEBUG -Xclang -flto-visibility-public-std -D_MT -Xclang --dependent-lib=libcmtd -Xlinker /subsystem:console @CMakeFiles/wxrc.dir/objects1.rsp -o ../lib/clang_x64_lib/wxrc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:../lib/clang_x64_lib/wxrc.lib -Xlinker /pdb:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.pdb -Xlinker /version:0.0  @CMakeFiles/wxrc.dir/linkLibs.rsp 

 !!!  -Xlinker /implib:../lib/clang_x64_lib/wxrc.lib   !!!
but in
3.1.4 generate as
 !!!  -Xlinker /implib:.wxrc.lib  !!!

if i`m  handly correct "-Xlinker /implib:../lib/clang_x64_lib/wxrc.lib" 
 to   '-Xlinker /implib:.wxrc.lib'
 or  '-Xlinker /implib:D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build/base/lib/clang_x64_lib/wxrc.lib'
wxrc build suseful 

How  say to  wxWidgets-3.2.2.1 buld system generate  file utils\CMakeFiles\wxrc.dir\build.make
as   genberate in  3.1.4:    -Xlinker /implib:.wxrc.lib ?

### Platform and version information

- wxWidgets version  you are building: 3.2.2.1
- wxWidgets port  you are building: wxMSW]
- OS  and its version: Windows 10, Windows 11
- Compiler  being used: LLVM with "Unix Makefiles"

**Comment by vadz** [comment]
I have no idea why does it even try to generate import library for wxrc (which is an executable, not a DLL) to be honest, so IMHO the solution could be to just get rid of it entirely.

What is your exact CMake invocation command?

**Comment by Khalyutin** [comment]
[//generate import library for wxrc..]

i`m see that in Windows in all my project  myProg.exe file create by myProg.lib object...    

===================================================

source of wxWidgets-3.2.2.1 extract from zip to : 
D:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/base

Executing command: C:\TOOLSET\CMake\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -SD:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1 -Bd:/source/COMPONENTS/GUI/wxWidgets-3.2.2.1/build -G "Unix Makefiles"

=================================================== 

cmake_minimum_required (VERSION 3.15.4)

include(../../../NOTEMATRIX/CMAKE/nm-core-cmake/script/notecore-inventory.cmake)

notecorePREPARE_INVENTORY()
set(CMAKE_INSTALL_PREFIX "../dist/${notecoreCONFIG}/${notecoreCOMPILER}")

project(nmwxWidgets)

if (WIN32 AND "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    add_definitions("-DwxUSE_NO_MANIFEST")
    add_definitions("-D_nmwxUSE_CLANG_FOR_WINDOWS"  )
                set(   _nmwxUSE_CLANG_FOR_WINDOWS ON)                                    
    #        set(   wxUSE_XRC ON)
endif()       

# set(wxBUILD_DEMOS   ON)
# set(wxBUILD_SAMPLES ALL)
set(BUILD_SHARED_LIBS OFF)
add_definitions("-D_UNICODE")

add_subdirectory("base")
================================================

cmake_minimum_required (VERSION 3.15.4)

################################################################################
macro(notecoreINVENTORY_CONFIG)

    cmake_policy(SET CMP0057 NEW)

    
    if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
        add_definitions(-D_DEBUG -DDEBUG -D_DEBUG_)
        set(notecoreDEBUG_OR_RELEASE debug)
    else()
        set(notecoreDEBUG_OR_RELEASE release)
    endif()
    


#    set(CMAKE_BUILD_TYPE         Debug)
    set(notecoreTARGET_OS_BIT       64)
    set(notecoreCOMPILER         clang)

    if    ( ${CMAKE_BINARY_DIR} MATCHES "clang"  )
        set(notecoreCOMPILER clang)
    elseif( ${CMAKE_BINARY_DIR} MATCHES "msvc") 
        set(notecoreCOMPILER msvc)
    elseif( ${CMAKE_BINARY_DIR} MATCHES "gnu") 
        set(notecoreCOMPILER gnu)
    else()
        message(STATUS "build dir mast contain 'clang' or 'msvc' or 'gnu' default '${notecoreCOMPILER}'.")
    endif()

    if    ( ${CMAKE_BINARY_DIR} MATCHES "Debug"  )
        set(CMAKE_BUILD_TYPE Debug)
        set(notecoreDEBUG_OR_RELEASE debug)
        add_definitions(-D_DEBUG -DDEBUG -D_DEBUG_)
    elseif( ${CMAKE_BINARY_DIR} MATCHES "Release") 
        set(CMAKE_BUILD_TYPE Release)
        set(notecoreDEBUG_OR_RELEASE release)
    else()
        message(STATUS "build dir mast contain 'Debug' or 'Release' default '${CMAKE_BUILD_TYPE}'.")
    endif()

    if    ( ${CMAKE_BINARY_DIR} MATCHES "x64")
        set(notecoreTARGET_OS_BIT 64)
        add_definitions(-D__64__)
        add_definitions(-m64 )
    elseif( ${CMAKE_BINARY_DIR} MATCHES "x32") 
        set(notecoreTARGET_OS_BIT 32)
        add_definitions(-D__32__)
        add_definitions(-m32 )
    else()    
        add_definitions(-D__64__)
        add_definitions(-m64 )
        message(STATUS "build dir mast contain 'x64' or 'x32' default '${notecoreTARGET_OS_BIT}'.")
    endif()

    if (WIN32)
        set(notecoreTARGET_OS_TYPE win)
        add_definitions(-DWINDOWS)
    elseif (APPLE)
        set(notecoreTARGET_OS_TYPE osx)
        add_definitions(-DAPPLE)
    elseif (UNIX)
        set(notecoreTARGET_OS_TYPE nix)
        add_definitions(-DLINUX)
    else()    
        set(notecoreTARGET_OS_TYPE nix)
    endif()

    if (WIN32)
    elseif (APPLE)
    elseif (UNIX)
    endif()

    set(notecoreCONFIG       "${notecoreTARGET_OS_TYPE}-x${notecoreTARGET_OS_BIT}.${notecoreDEBUG_OR_RELEASE}")
    set(notecoreTARGET_OS_ID "${notecoreTARGET_OS_TYPE}${notecoreTARGET_OS_BIT}")

    if (NOT CMAKE_INSTALL_PREFIX)
        set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/dist")
    endif()

endmacro()
################################################################################
macro(notecoreINVENTORY_COMPILER)

    set(CMAKE_COLOR_MAKEFILE OFF)


    if (WIN32)
        cmake_policy(SET CMP0091 NEW)
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")


        if (NOT ${CMAKE_BINARY_DIR} MATCHES "msvc")
            set(notecoreLLNM_DIR   "C:/TOOLSET/LLVM/bin"               )
            set(notecoreMAKE_DIR   "C:/TOOLSET/msys64/usr/bin"         )
            ############################################################
            set(CMAKE_C_COMPILER   "${notecoreLLNM_DIR}/clang.exe"     )
            set(CMAKE_CXX_COMPILER "${notecoreLLNM_DIR}/clang++.exe"   ) 
            set(CMAKE_RC_COMPILER  "${notecoreLLNM_DIR}/llvm-rc.exe"   )
            set(CMAKE_AR           "${notecoreLLNM_DIR}/llvm-ar.exe"   )
            set(CMAKE_RANLIB       "")
#            set(rc_flags "/V manifest.rc")
#            set(CMAKE_RC_FLAGS ${rc_flags})
#            set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> <FLAGS> -FO <OBJECT> <SOURCE>")

            set(NM_WARNING_OFF "-Wdeprecated-non-prototype -Winconsistent-missing-override -Wunused-local-typedef")

            set(CMAKE_RC_COMPILE_OBJECT "${CMAKE_RC_COMPILER} -V  <SOURCE>")
            set(CMAKE_C_FLAGS         "-Wall -Xclang -flto-visibility-public-std") 
            set(CMAKE_CXX_FLAGS       "-Wall -Xclang -flto-visibility-public-std") 
            set(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -gno-column-info                  ") 
            set(CMAKE_C_FLAGS_DEBUG   "-g -O0 -gno-column-info                  ") 
            link_directories("${notecoreLLNM_DIR}/lib")
        endif()

#        set(NM_MS_SDK_VER       10.0.19041.0)  
        set(NM_MS_SDK_VER      10.0.22621.0)  

        set(NM_MS_SDK_X64_DIR  "C:/Program Files (x86)/Windows Kits/10/bin/${NM_MS_SDK_VER}/x64")
        set(NM_MS_MT_EXE       "${NM_MS_SDK_X64_DIR}/mt.exe")
        add_definitions(-DWINDOWS)
        add_definitions(-D_CRT_SECURE_NO_WARNINGS) # [-Wdeprecated-declarations]
    elseif (APPLE)
    #    set(notecoreLLNM_DIR   "/Users/khalyutin/WORK/source/COMPONENTS/clang+llvm-8.0.0-x86_64-apple-darwin")
        set(notecoreLLNM_DIR   "/usr/local/opt/llvm")
        set(CMAKE_C_COMPILER   "${notecoreLLNM_DIR}/bin/clang"     )
        set(CMAKE_CXX_COMPILER "${notecoreLLNM_DIR}/bin/clang++"   ) 
        set(CMAKE_AR           "${notecoreLLNM_DIR}/bin/llvm-ar"   )
        set(CMAKE_C_FLAGS         "-fPIC")
        set(CMAKE_CXX_FLAGS       "-fPIC")
        set(CMAKE_C_FLAGS_DEBUG   "-g3 -gdwarf-2")
        set(CMAKE_CXX_FLAGS_DEBUG "-g3 -gdwarf-2")
        add_definitions(-DAPPLE)
     #  add_definitions(  "-L${notecoreLLNM_DIR}/lib -Wl,-rpath,${notecoreLLNM_DIR}/lib")
        include_directories("${notecoreLLNM_DIR}/include")
        link_directories(   "${notecoreLLNM_DIR}/lib")
    elseif (UNIX)
        # set(NM_CMAKE_BIN_DIR  "/usr/local/cmake-3.15.4-Linux-x86_64/bin")
        set(notecoreLLNM_DIR   "/usr/lib64/clang/8.0.1")
        set(CMAKE_C_COMPILER   "${notecoreLLNM_DIR}/bin/clang"     )
        set(CMAKE_CXX_COMPILER "${notecoreLLNM_DIR}/bin/clang++"   ) 
        set(CMAKE_AR           "${notecoreLLNM_DIR}/bin/llvm-ar"   )
        set(CMAKE_C_FLAGS         "-fPIC")
        set(CMAKE_CXX_FLAGS       "-fPIC")
        set(CMAKE_C_FLAGS_DEBUG   "-g3 -gdwarf-2")
        set(CMAKE_CXX_FLAGS_DEBUG "-g3 -gdwarf-2")
        add_definitions(-DLINUX)
        link_directories("${notecoreLLNM_DIR}/lib")
    endif()

    enable_language(C CXX)

endmacro()
################################################################################
macro(notecoreINVENTORY_DISPLAY)
    message(STATUS "|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||")
    message(STATUS "|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||")
    message(STATUS "        config : ${notecoreCONFIG}")
    message(STATUS "       OS name : ${CMAKE_SYSTEM_NAME}")
    message(STATUS "OS pointer len : ${CMAKE_SIZEOF_VOID_P}")
    message(STATUS " debug/release : ${CMAKE_BUILD_TYPE}")
#   message(STATUS "      platform : ${notecoreTARGET_OS_ID}")
    message(STATUS "   generator`s : [${CMAKE_GENERATOR}]")
    message(STATUS "   source from : [${CMAKE_SOURCE_DIR}]")
    message(STATUS "   building in : [${CMAKE_BINARY_DIR}]")
    message(STATUS "   by compiler : [${CMAKE_CXX_COMPILER_ID}]::[${CMAKE_BUILD_TYPE}]")
    message(STATUS "   install  to : [${CMAKE_INSTALL_PREFIX}]")

    
   

    message(STATUS "|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||")
    message(STATUS "|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||")
endmacro()
################################################################################
macro(notecorePREPARE_INVENTORY)
    notecoreINVENTORY_CONFIG()
    notecoreINVENTORY_COMPILER()
    notecoreINVENTORY_DISPLAY()
endmacro()
################################################################################

**Comment by Khalyutin** [comment]
Ok. Setting the environment variable
MSYS2_ARG_CONV_EXCL=/implib:
is fixed problem.
Thank  for  https://github.com/alvinhochunl
