### ISSUE TITLE
wxQT port is missing wxPenInfo constructor

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23474]
### Description

The wxQT wxPen class in missing the ‘wxPen::wxPen(const wxPenInfo&)’ constructor.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxQT
- OS  and its version: OpenSuSE 15.4

**Comment by vadz** [comment]
Unfortunately wxQt is not really maintained currently, so while we welcome any PRs to it (including adding this ctor), I don't promise to do anything about it myself, sorry.

**Comment by mcorino** [comment]
That's ok.
I was just testing the state of wxQT and wanted to at least report some things I found.
It seems though that wxQT is simply not stable enough for any serious development (I also already encountered a segfault running a sample) so I'm going to leave at that as I also do not currently have time (or any real interest) to do much more about that.

**Comment by AliKet** [comment]
Fixed in a38774206d97d2af122a0bbbb9c2a7ede4a9a574

**Comment by AliKet** [comment]
This should be closed.
