### ISSUE TITLE
Why is wxWindow::EnableTouchEvents() protected in wxQT port?

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23473]
### Description

Is there a specific reason `wxWindow::EnableTouchEvents()` is declared protected in wxQT where it is public in `wxWindowBase` and all other ports (wxGTK, wxMSW, wxOSX) supporting this?
If not, should this be changed?

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxQT
- OS  and its version: OpenSuSE 15.4

**Comment by vadz** [comment]
Looks like an oversight, I'll make it public, thanks.
