### ISSUE TITLE
Numpad "5" key generates different codes in Windows and GTK if NumLock is off

### ISSUE THREAD

**Issue by unxed** [wxWidgets/wxWidgets#23478]
This is wx keyboard sample app logs for pressing `NumPad 5` key with NumLock being off.

On Windows:
```
   Hook           CLEAR   305   ----    0 (U+0000)       12    0x004c0001  (  381,  698)  No
KeyDown           CLEAR   305   ----    0 (U+0000)       12    0x004c0001  (  381,  698)  No
   Char           CLEAR   305   ----    0 (U+0000)       12    0x004c0001  (  381,  698)  No
  KeyUp           CLEAR   305   ----    0 (U+0000)       12    0xc04c0001  (  382,  698)  Yes
```

On GTK:
```
   Hook    NUMPAD_BEGIN   383   ----    0 (U+0000)    65437    0x00000054  (  551,  374)  No
KeyDown    NUMPAD_BEGIN   383   ----    0 (U+0000)    65437    0x00000054  (  528,  358)  No
   Char            HOME   313   ----    0 (U+0000)    65437    0x00000054  (  528,  358)  No
  KeyUp    NUMPAD_BEGIN   383   ----    0 (U+0000)    65437    0x00000054  (  462,  306)  No
```

**Comment by vadz** [comment]
Oops. I actually have no idea what should this key be called, I wouldn't expect neither "clear" not "begin" to be associated with it (the latter is pretty confusing as there is also `WXK_NUMPAD_HOME`). So perhaps the simplest fix would be to define some new `WXK_NUMPAD_CENTER` and generate it on both platforms and make both `WXK_CLEAR` and `WXK_NUMPAD_BEGIN` synonyms for it.

In 3.2 we could just add
```cpp
#ifdef __WXMSW__
    WXK_NUMPAD_CENTER = WXK_CLEAR,
#else
    WXK_NUMPAD_CENTER = WXK_NUMPAD_BEGIN,
#endif
```
to `wxKeyCode` enum, which would be backwards compatible but would still allow
to use it in the new code.

If you'd like to make a PR doing this, please do, TIA!

**Comment by vadz** [comment]
P.S. I wanted to test this also under Mac, but couldn't: the keyboard there doesn't have NumPad toggle so it can't be turned off (and the numpad keys don't have the alternative labels). And the virtual keyboard that can be shown there doesn't have numpad at all. If anybody does have a Mac keyboard with NumPad toggle, I'd be curious to know what does it call this key.

**Comment by unxed** [comment]
Maybe test it using external USB PC keyboard?

**Comment by TcT2k** [comment]
As far as I'm aware all apple keyboards (that include a numpad) just have a "clear" key above the 7. And using num lock on a PC keyboard just does nothing.

**Comment by unxed** [comment]
I'll just leave it here. Looks like there is no "common" keypad 5 meaning. So let it be numpad center, ok.

https://superuser.com/questions/1143071/has-the-5-key-on-the-numeric-keypad-ever-had-an-alternate-function-in-hardware

**Comment by unxed** [comment]
Done in #23491, please review.

**Comment by unxed** [comment]
Hm, ScintillaWX and richtextctrl fails to build, could not figure out the reason for now

**Comment by unxed** [comment]
Fixed.
