### ISSUE TITLE
LoadDocument fails if std::istream reaches eof (regression?)

### ISSUE THREAD

**Issue by lszl84** [wxWidgets/wxWidgets#23479]
### Description

`wxDocument` framework fails to load the file if std::istream used in `LoadObject` has `eof` flag set.

```cpp
DocumentIstream &DrawingDocument::LoadObject(DocumentIstream &istream)
{
    wxDocument::LoadObject(istream);

    std::string line;
    while (std::getline(istream, line))
    {
        std::cout << line << std::endl;
    }

    return istream;
}
```

`EOF` is ignored for wx streams but not for standard streams for some reason: 

```cpp
// docview.cpp

#if wxUSE_STD_IOSTREAM
    LoadObject(store);
    if ( !store )
#else
    int res = LoadObject(store).GetLastError();
    if ( res != wxSTREAM_NO_ERROR && res != wxSTREAM_EOF )
#endif
    {
        wxLogError(_("Failed to read document from the file \"%s\"."), file);
        return false;
    }
```

It seems that there was a fix for that, but it got lost somehow: https://github.com/wxWidgets/wxWidgets/issues/5308

### Platform and version information

- wxWidgets version  you use: master, 3.2.2
- wxWidgets port  you use: wxOSX, most likely others too

**Comment by vadz** [comment]
Thanks, the fix from that old patch looks indeed correct to me so I'll push it soon.

I do wonder if we shouldn't try harder to preserve compatibility with the existing code not using `wxUSE_STL=1` but using docview though, as the change to the default `wxUSE_STD_IOSTREAM` value is going to break it... Have you been affected by this?

**Comment by vadz** [comment]
No, wait, sorry, I spoke too soon: it doesn't make sense to check for `!stream && !store.eof()` because `!stream` is the same as `stream.fail()` and `fail()` returns false if `eofbit` is the only error bit set. The stream must actually be in _fail_ state, which actually makes sense for the example above because `getline()` sets `failbit` if it doesn't extract anything.

I am not sure what's the right solution here. We could replace `!store` with `store.bad()`, perhaps? For now you can always call `istream.clear()` to make sure the status is correct.

**Comment by lszl84** [comment]
It seems that the behavior of standard streams and wx streams is a bit different when it comes to setting the error bits.

Consider this example, reading from a ZIP using wx streams:

```cpp
    wxFileInputStream in("file.zip");
    wxZipInputStream zipIn(in);
    std::unique_ptr<wxZipEntry> entry(zipIn.GetNextEntry());

    while (entry)
    {
        wxString entryName = entry->GetName();

        // ... do sth with entry

        zipIn.CloseEntry();
        entry.reset(zipIn.GetNextEntry());
    }

    std::cout << "Stream Ok: " << in.IsOk() << std::endl;
    std::cout << "Stream Eof: " << in.Eof() << std::endl;
    std::cout << "Stream Last Error: " << in.GetLastError() << std::endl;
```

There are no errors and `EOF` is not set:

```
Stream Ok: 1
Stream Eof: 0
Stream Last Error: 0
```

Now let's say I need to read this zip file from a standard stream. I wrap the stream in my `IStreamWrapper` object (kind of the opposite of `wxStdInputStream`) and read it like before:

```cpp
    struct IStreamWrapper : public wxInputStream
    {
        IStreamWrapper(std::istream &stream) : m_stream(stream) {}

        size_t OnSysRead(void *buffer, size_t size) override
        {
            m_stream.read((char *)buffer, size);
            return size;
        }

        std::istream &m_stream;
    };

    std::ifstream fs("file.zip", std::ios::binary);
    IStreamWrapper in{fs};

    wxZipInputStream zipIn(in);
    std::unique_ptr<wxZipEntry> entry(zipIn.GetNextEntry());

    while (entry)
    {
        wxString entryName = entry->GetName();

        // ... do sth with entry

        zipIn.CloseEntry();
        entry.reset(zipIn.GetNextEntry());
    }

    std::cout << "Stream Ok: " << in.IsOk() << std::endl;
    std::cout << "Stream Eof: " << in.Eof() << std::endl;
    std::cout << "Stream Last Error: " << in.GetLastError() << std::endl;

    std::cout << "File Stream Ok: " << fs.good() << std::endl;
    std::cout << "File Stream Eof: " << fs.eof() << std::endl;
    std::cout << "File Stream Last Error: " << fs.rdstate() << std::endl;
    std::cout << "File Stream Fail: " << fs.fail() << std::endl;
```

Now the result is the following:

```
Stream Ok: 1
Stream Eof: 0
Stream Last Error: 0
File Stream Ok: 0
File Stream Eof: 1
File Stream Last Error: 6
File Stream Fail: 1
```

So unless my `IStreamWrapper` implementation is incorrect, the behavior of standard streams and wx streams is different. 

Using `clear()`, as you mentioned, is a workaround, and it helps, but it would be great if that wasn't needed, just as it's not needed for `wxInputStream` in this example.

**Comment by vadz** [comment]
> It seems that the behavior of standard streams and wx streams is a bit different when it comes to setting the error bits.

It's very different, wx streams are (unfortunately) completely unrelated to C++ standard streams. But this, on its own, isn't a problem or at least not something we can do anything about.

But this is just another reason why we can't force people to update the existing code using `wxInputStream` to use `std::istream` instead, this is not a trivial change. So I've created #23481 to restore compatibility here.

I'm not sure if there is anything remaining to do here or if it should be just closed when the associated PR is merged?

**Comment by lszl84** [comment]
If I understand correctly, this PR introduces `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX` and uses it to determine stream type for `Load/SaveObject`. Since the flag by default is `0`, these functions will use wx streams by default, correct?

This will certainly make it easier to work with other wx streams (zip, etc.), but I think at some point somebody will be surprised why when setting `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX=1` and reading their `std::istream` till `EOF` they get an error message "Failed to read document from the file \"%s\"."

**Comment by vadz** [comment]
> If I understand correctly, this PR introduces `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX` and uses it to determine stream type for `Load/SaveObject`. Since the flag by default is `0`, these functions will use wx streams by default, correct?

Yes, correct. And the reason it's 0 by default is to preserve compatibility with the existing default build of wxWidgets -- the switch to using standard streams happened only recently in be7860c766 (Remove wxUSE_STD_STRING and wxUSE_STD_CONTAINERS_COMPATIBLY, 2022-11-16) and wasn't intentional, so I'm undoing it now.

> This will certainly make it easier to work with other wx streams (zip, etc.), but I think at some point somebody will be surprised why when setting `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX=1` and reading their `std::istream` till `EOF` they get an error message "Failed to read document from the file "%s"."

Well, reading it till EOF should work fine. It's reading it _after_ EOF, as `getline()` does, which sets the failbit and results in an error. And it's not clear if it's really wrong: in this simple example it seems to be so, but what if you had encountered some unexpected error instead?

**Comment by lszl84** [comment]
> > If I understand correctly, this PR introduces `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX` and uses it to determine stream type for `Load/SaveObject`. Since the flag by default is `0`, these functions will use wx streams by default, correct?
> 
> Yes, correct. And the reason it's 0 by default is to preserve compatibility with the existing default build of wxWidgets -- the switch to using standard streams happened only recently in [be7860c](https://github.com/wxWidgets/wxWidgets/commit/be7860c7661756e8de36985ade760d5c9a784ab7) (Remove wxUSE_STD_STRING and wxUSE_STD_CONTAINERS_COMPATIBLY, 2022-11-16) and wasn't intentional, so I'm undoing it now.
> 

Wait, so version e.g. 3.1.4 should use wx streams by default? I've just compiled wxWidgets and a docview sample with the following change and it shows that it uses std streams:

```cpp
DocumentOstream& DoodleSegment::SaveObject(DocumentOstream& ostream)
{
#if wxUSE_STD_IOSTREAM
    DocumentOstream& stream = ostream;
    wxLogMessage(wxString("Saving doodle segment using std::ostream. wx ") + wxVERSION_STRING);
#else
    wxTextOutputStream stream(ostream);
    wxLogMessage(wxString("Saving doodle segment using wxTextOutputStream. wx") + wxVERSION_STRING);
#endif
   
    // ...
}
```

<img width="670" alt="Screenshot 2023-04-24 at 11 05 10" src="https://user-images.githubusercontent.com/42072702/233951898-e129942f-8d3b-41ef-ab5f-3ecdcf4e4126.png">

I've compiled it on Mac using the standard procedure:

```sh
mkdir build-cocoa-debug
cd build-cocoa-debug
../configure --enable-debug
make -j
cd samples; make -j
```

> > This will certainly make it easier to work with other wx streams (zip, etc.), but I think at some point somebody will be surprised why when setting `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX=1` and reading their `std::istream` till `EOF` they get an error message "Failed to read document from the file "%s"."
> 
> Well, reading it till EOF should work fine. It's reading it _after_ EOF, as `getline()` does, which sets the failbit and results in an error. And it's not clear if it's really wrong: in this simple example it seems to be so, but what if you had encountered some unexpected error instead?

Yeah, I'm also not sure what would be the best solution here...

**Comment by vadz** [comment]
> Wait, so version e.g. 3.1.4 should use wx streams by default?

Sorry, I've managed to totally confuse myself (but, luckily, not you). I've somehow decided that the default change due to the recent commit referenced above, but in fact it had changed 15 years ago in bb445ba732 (turn wxUSE_STD_IOSTREAM on by default (except for the compilers which are too broken), 2008-02-16), so wx streams are absolutely not used by default since a very long time, sorry again.

I need to change the PR, we don't need this `wxUSE_STD_IOSTREAM_INSTEAD_OF_WX` finally.

As for the original problem of this PR, I think I'm just going to update the documentation to mention that the stream must not have `failbit` set if loading succeeded.

**Comment by lszl84** [comment]
Thanks, the doc update sounds good!

**Comment by vadz** [comment]
Updated now, please let me know if you still see anything wrong, TIA!

**Comment by lszl84** [comment]
Looks good!
