### ISSUE TITLE
The resulting output of a drawing differ between using a GDI+ and using a Direct2D on HiDPI

### ISSUE THREAD

**Issue by Kumazuma** [wxWidgets/wxWidgets#23486]
### Description

When I draw into frame on monitor has 150% DPI, the resulting is differ.

```cpp
#include <wx/wx.h>
#include <wx/graphics.h>

class App: public wxApp
{
public:
    bool OnInit() override;
};

class Frame: public wxFrame
{
    DECLARE_EVENT_TABLE();
public:
    Frame();

protected:
    void OnPaint(wxPaintEvent& evt);
};

bool App::OnInit()
{
    if (!wxApp::OnInit())
        return false;

    auto pFrame = new Frame{};
    pFrame->SetClientSize(800, 800);
    pFrame->Show();
    
    return true;
}

Frame::Frame()
    : wxFrame(nullptr, wxID_ANY,wxS("Transform"), wxDefaultPosition, wxSize{800, 800})
{
}

wxBEGIN_EVENT_TABLE(Frame, wxFrame)
EVT_PAINT(Frame::OnPaint)
wxEND_EVENT_TABLE()

void Frame::OnPaint(wxPaintEvent& evt)
{
    wxPaintDC dc{ this };
    //auto renderer = wxGraphicsRenderer::GetDirect2DRenderer();
    auto renderer = wxGraphicsRenderer::GetGDIPlusRenderer();
    auto context = renderer->CreateContext(this);
    wxGraphicsMatrix mat{ renderer->CreateMatrix(1, 0, 0, -1, 400, 400) };
    wxDouble w;
    wxDouble h;
    wxDouble dpiX;
    wxDouble dpiY;
    context->GetDPI(&dpiX, &dpiY);
    context->GetSize(&w, &h);
    context->SetBrush(renderer->CreateBrush(*wxWHITE_BRUSH));
    context->SetPen(*wxTRANSPARENT_PEN);
    context->DrawRectangle(0, 0, 800, 800);
    context->SetPen(*wxBLACK_PEN);

    context->SetTransform(mat);
    context->StrokeLine(400, 0, -400, 0);
    context->StrokeLine(0, -400, 0, 400);
    delete context;
}

wxIMPLEMENT_APP(App);
```

This is GDI+ Renderer
<img style="display:inline-block;" width="201" alt="image" src="https://user-images.githubusercontent.com/12020335/233999879-06904119-8632-4ee6-ba89-c9b0fc888256.png">

This is Direct2D Renderer
<img style="display:inline-block;" width="201" alt="image" src="https://user-images.githubusercontent.com/12020335/233999979-f52b549c-a3e1-438e-a0ef-c450abef7858.png">

both output of GetDPI is same (144).

It may be related with [msdn](https://learn.microsoft.com/en-us/windows/win32/direct2d/direct2d-and-high-dpi)

I think result should be same.
### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxMSW
- OS  and its version: Win11 22h2

+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by vadz** [comment]
Sorry for wrongly mentioning this issue in f396c8b2b3f22a6c76d067b4783e6383d9ac7133, it was just a typo.
