### ISSUE TITLE
Drawing a bitmap with DPI scaling seems to have an offset

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23485]
### Description

The following patch to the drawing sample draws two rectangles.
The first rectangle is drawn into a `wxBitmap`, which is then drawn on the canvas.
The second rectangle is drawn directly on the canvas.
```patch
diff --git "a/samples/drawing/drawing.cpp" "b/samples/drawing/drawing.cpp"
index f6a102dd23..f5ae642a25 100644
--- "a/samples/drawing/drawing.cpp"
+++ "b/samples/drawing/drawing.cpp"
@@ -696,6 +696,26 @@ void MyCanvas::DrawCrossHair(int x, int y, int width, int heigth, wxDC &dc)
 
 void MyCanvas::DrawDefault(wxDC& dc)
 {
+    wxBitmap bmp;
+    bmp.CreateWithDIPSize( 50, 30, GetDPIScaleFactor() );
+
+    wxMemoryDC memDc;
+    memDc.SelectObject( bmp );
+
+    memDc.SetPen( *wxRED_PEN );
+    memDc.SetBrush( *wxGREEN_BRUSH );
+
+    memDc.DrawRectangle( wxPoint(0, 0), memDc.GetSize() );
+    memDc.SelectObject( wxNullBitmap );
+
+    dc.DrawBitmap( bmp, dc.FromDIP(wxPoint(10, 10)) );
+
+    dc.SetPen( *wxRED_PEN );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 50)), dc.FromDIP(wxSize(50, 30)) );
+
+    return;
+
     // Draw circle centered at the origin, then flood fill it with a different
     // color. Done with a wxMemoryDC because Blit (used by generic
     // wxDoFloodFill) from a window that is being painted gives unpredictable

```

At 100% DPI scaling everything looks fine. Both rectangles are identical.

But at 200% DPI scaling, the bitmap (the first rectangle) is displayed incorrectly.

![drawing_dpi-scale-200](https://user-images.githubusercontent.com/99262969/233994977-7f9a7d7f-c70b-468f-8ca4-2b4254dfd65a.png)

- It's position has an offset of 1 pixel (in both directions, x and y).
  It should have the same x position as the second rectangle.
- The rectangle in the bitmap also seems to have an offset of 1 pixel.
  Note the thinner border on the left and top and the black pixels on the bottom and right.

Same behavior under Linux Mint 20 and Ubunut 22.04 (X11 and Wayland).

### Platform and version information

- wxWidgets version  you use: 3.2.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: Mint20, Ubuntu 22.04

+ GTK version:  3.24
+ Which GDK  backend is used: X11 and Wayland
+ Current theme:

**Comment by taler21** [comment]
Thanks for the quick changes.

The directly drawn rectangle and that via `wxBitmap` now match.
But at 200% DPI scaling, both have an offset of one pixel in horizontal and vertical direction.

```patch
diff --git "a/samples/drawing/drawing.cpp" "b/samples/drawing/drawing.cpp"
index f6a102dd23..7450a7c03f 100644
--- "a/samples/drawing/drawing.cpp"
+++ "b/samples/drawing/drawing.cpp"
@@ -696,6 +696,38 @@ void MyCanvas::DrawCrossHair(int x, int y, int width, int heigth, wxDC &dc)
 
 void MyCanvas::DrawDefault(wxDC& dc)
 {
+    wxBitmap bmp;
+    bmp.CreateWithDIPSize( 50, 30, GetDPIScaleFactor() );
+
+    wxMemoryDC memDc;
+    memDc.SelectObject( bmp );
+
+    memDc.SetPen( *wxRED_PEN );
+    memDc.SetBrush( *wxGREEN_BRUSH );
+    memDc.DrawRectangle( wxPoint(0, 0), memDc.GetSize() );
+    memDc.SelectObject( wxNullBitmap );
+
+    wxPoint pointsTL[3];
+    pointsTL[0] = dc.FromDIP(wxPoint(10,  5));
+    pointsTL[1] = dc.FromDIP(wxPoint(10, 10));
+    pointsTL[2] = dc.FromDIP(wxPoint( 5, 10));
+    wxPoint pointsBL[2];
+    pointsBL[0] = dc.FromDIP(wxPoint(10, 39));
+    pointsBL[1] = dc.FromDIP(wxPoint( 5, 39));
+    dc.SetPen( *wxBLUE_PEN );
+    dc.DrawLines( 3, pointsTL );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(40) );
+    dc.DrawLines( 2, pointsBL );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(40) );
+
+    dc.DrawBitmap( bmp, dc.FromDIP(wxPoint(10, 10)) );
+
+    dc.SetPen( *wxRED_PEN );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 50)), dc.FromDIP(wxSize(50, 30)) );
+
+    return;
+
     // Draw circle centered at the origin, then flood fill it with a different
     // color. Done with a wxMemoryDC because Blit (used by generic
     // wxDoFloodFill) from a window that is being painted gives unpredictable

```

The code above at 200% DPI scaling:

![drawing_dpi-scale-200_new](https://user-images.githubusercontent.com/99262969/234524578-1dbf5c16-604e-485d-8e89-7135e4596608.png)

Maybe the cause of the issue isn't drawing the rectangle, but drawing the bitmap data?
Because before the changes, the directly drawn rectangle looked correct.

![drawing_dpi-scale-200_old](https://user-images.githubusercontent.com/99262969/234524902-dcbf0298-6308-4703-b464-e5346dac5093.png)

**Comment by paulcor** [comment]
> before the changes, the directly drawn rectangle looked correct

It didn't match the position of a rectangle drawn with no pen.

**Comment by taler21** [comment]
Did some more testing.

<details>
<summary>patch for drawing sample</summary>

```patch
diff --git "a/samples/drawing/drawing.cpp" "b/samples/drawing/drawing.cpp"
index f6a102dd23..fca0705af7 100644
--- "a/samples/drawing/drawing.cpp"
+++ "b/samples/drawing/drawing.cpp"
@@ -696,6 +696,88 @@ void MyCanvas::DrawCrossHair(int x, int y, int width, int heigth, wxDC &dc)
 
 void MyCanvas::DrawDefault(wxDC& dc)
 {
+    wxBitmap bmp;
+    bmp.CreateWithDIPSize( 50, 30, GetDPIScaleFactor() );
+
+    wxMemoryDC memDc;
+    memDc.SelectObject( bmp );
+
+    memDc.SetPen( *wxRED_PEN );
+    memDc.SetBrush( *wxGREEN_BRUSH );
+    memDc.DrawRectangle( wxPoint(0, 0), memDc.GetSize() );
+    memDc.SelectObject( wxNullBitmap );
+
+    wxPoint pointsTL[3];
+    pointsTL[0] = dc.FromDIP(wxPoint(10,  5));
+    pointsTL[1] = dc.FromDIP(wxPoint(10, 10));
+    pointsTL[2] = dc.FromDIP(wxPoint( 5, 10));
+    wxPoint pointsBL[2];
+    pointsBL[0] = dc.FromDIP(wxPoint(10, 39));
+    pointsBL[1] = dc.FromDIP(wxPoint( 5, 39));
+    dc.SetPen( *wxBLUE_PEN );
+    dc.DrawLines( 3, pointsTL );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(40) );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(80) );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(120) );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(160) );
+    dc.DrawLines( 2, pointsBL );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(40) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(80) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(120) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(160) );
+
+    dc.DrawBitmap( bmp, dc.FromDIP(wxPoint(10, 10)) );
+
+    dc.SetPen( *wxRED_PEN );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 50)), dc.FromDIP(wxSize(50, 30)) );
+
+    dc.SetPen( wxNullPen );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 90)), dc.FromDIP(wxSize(50, 30)) );
+
+    dc.SetPen( *wxTRANSPARENT_PEN );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 130)), dc.FromDIP(wxSize(50, 30)) );
+
+    dc.SetPen( *wxRED_PEN );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(60, 200)), dc.FromDIP(wxSize(-50, -30)) );
+
+    wxPen penBlue3( *wxBLUE, 3 );
+    penBlue3.SetCap( wxCAP_BUTT );
+    dc.SetPen( penBlue3 );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(200) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(200) );
+    dc.SetPen( wxPen( *wxRED, 3 ) );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 210)), dc.FromDIP(wxSize(50, 30)) );
+
+    dc.SetPen( penBlue3 );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(240) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(240) );
+    dc.SetPen( wxPen( *wxRED, 3 ) );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(60, 280)), dc.FromDIP(wxSize(-50, -30)) );
+
+    wxPen penBlue5( *wxBLUE, 5 );
+    penBlue5.SetCap( wxCAP_BUTT );
+    dc.SetPen( penBlue5 );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(280) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(280) );
+    dc.SetPen( wxPen( *wxRED, 5 ) );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(10, 290)), dc.FromDIP(wxSize(50, 30)) );
+
+    dc.SetPen( penBlue5 );
+    dc.DrawLines( 3, pointsTL, 0, dc.FromDIP(320) );
+    dc.DrawLines( 2, pointsBL, 0, dc.FromDIP(320) );
+    dc.SetPen( wxPen( *wxRED, 5 ) );
+    dc.SetBrush( *wxGREEN_BRUSH );
+    dc.DrawRectangle( dc.FromDIP(wxPoint(60, 360)), dc.FromDIP(wxSize(-50, -30)) );
+
+    return;
+
     // Draw circle centered at the origin, then flood fill it with a different
     // color. Done with a wxMemoryDC because Blit (used by generic
     // wxDoFloodFill) from a window that is being painted gives unpredictable

```
</details>

You are right, a directly drawn rectangle had one pixel offset at 200% DPI scaling already before the changes, when drawn without or with a transparent pen.

But after d43b2862c3c3e8d2ad7eb39b72bdbd4005444c66:
* With a pen width > 1, the rectangle size is now one logical pixel too large, even at 100% DPI scaling.
  Before the changes, the correction of width and height was done for pen width > 0 and now only if pen width == 1.
* The incorrect offset of one pixel at 200% DPI scaling is now also present when using a 1 pixel wide pen.

By the way:
According to the documentation, negative values for width and height are allowed.
In principle, this should be taken into account when correcting the size (and position).
Even if that wasn't done in the previous code either.

Thanks in advance for any further fixes!

**Comment by paulcor** [comment]
Lines drawn with `wxGCDC` using odd-width pens and odd-integer scales are offset half a pixel in order to keep horizontal or vertical lines from appearing blurry. And note that the coordinates for a line specify it's _center_. The width 1 rectangle outline is special-cased to match the appearance with a raster-based `wxDC`. I believe this explains what you are seeing. In general, it is not possible to exactly match the behavior of a raster-based `wxDC` using vector-based drawing, particularly when scaled. Making one thing look right will make something else look wrong. If you really need pixel-exact results on all platforms, your only choice is to use `wxGraphicsContext`, and probably turn off offsetting. So ATM, I don't see anything more to be done here.

> According to the documentation, negative values for width and height are allowed

Should be fixed by 2f95afcc8c

**Comment by taler21** [comment]
> Lines drawn with `wxGCDC` using odd-width pens and odd-integer scales are offset half a pixel in order to keep horizontal or vertical lines from appearing blurry.

Okay, but at 200% DPI, the scaling factor is an even integer value.

> And note that the coordinates for a line specify it's center.

Yes, I know. Therefore, I measure position and size of the rectangle in the middle of the corner points of its border lines.

> The width 1 rectangle outline is special-cased to match the appearance with a raster-based `wxDC`.

The correction of width and height (subtraction by 1) is required for pen width > 0, not only if pen width == 1.
Otherwise the rectangle is too big, even at 100% DPI.
That is definitely a regression and was correct before d43b2862c3c3e8d2ad7eb39b72bdbd4005444c66.

> In general, it is not possible to exactly match the behavior of a raster-based `wxDC` using vector-based drawing, particularly when scaled. Making one thing look right will make something else look wrong.

I understand rounding issues with odd or non-integer scaling values.
But how can something be pixel-exact at 100% DPI but wrong at 200% DPI (using an even integer scaling factor of 2)?

> If you really need pixel-exact results on all platforms, your only choice is to use `wxGraphicsContext`, and probably turn off offsetting.

But the reported issues seem to come from the fact that drawing with `wxDC` under wxGTK is done with `wxGraphicsContext` which apparently is not pixel-exact?

> So ATM, I don't see anything more to be done here.

The regression mentioned above needs to be fixed in any case.

**Comment by taler21** [comment]
The changes of d43b2862c3c3e8d2ad7eb39b72bdbd4005444c66 should be modified at least as follows, to avoid regressions at 100% DPI.

```patch
diff --git "a/src/common/dcgraph.cpp" "b/src/common/dcgraph.cpp"
index 55a96c3566..1720596d83 100644
--- "a/src/common/dcgraph.cpp"
+++ "b/src/common/dcgraph.cpp"
@@ -992,7 +992,7 @@ void wxGCDCImpl::DoDrawRectangle(wxCoord x, wxCoord y, wxCoord w, wxCoord h)
 
     CalcBoundingBox(wxPoint(x, y), wxSize(w, h));
 
-    if (m_pen.IsNonTransparent() && m_pen.GetWidth() == 1)
+    if (m_pen.IsNonTransparent() && m_pen.GetWidth() > 0)
     {
         // Match raster-based wxDC implementations, which draw the line
         // along the inside edge of the solid rectangle
@@ -1023,7 +1023,7 @@ void wxGCDCImpl::DoDrawRoundedRectangle(wxCoord x, wxCoord y,
 
     CalcBoundingBox(wxPoint(x, y), wxSize(w, h));
 
-    if (m_pen.IsNonTransparent() && m_pen.GetWidth() == 1)
+    if (m_pen.IsNonTransparent() && m_pen.GetWidth() > 0)
     {
         OffsetDisabler offsetDisabler(m_graphicContext);
         if (w < 0) { w = -w; x -= w; }

```

As mentioned in the comment above, the size of an outlined rectangle is currently one pixel too large.
In other words: d43b2862c3c3e8d2ad7eb39b72bdbd4005444c66 breaks 4623c5ad9c79e3c21fed575494212e62c0f3931f (`Make rectangle size the same as is drawn by raster-based wxDCs, 2015-08-10`).

**Comment by vadz** [comment]
@paulcor Do you have any objections to the change above?

I also wonder how safe/desirable is it to backport this to 3.2.

**Comment by paulcor** [comment]
I've got some changes in mind, I'll try to spend some time on this soon.

**Comment by taler21** [comment]
Many thanks for your work on this issue!

Did some testing with 6857dc8e63d0d0462e118baab37ebdeee37b1d27 and it looks very good now.

Hope this improvement can also be backported to 3.2. TIA!
