### ISSUE TITLE
Using size with default coord value for height of wxSpinCtrl emits 'Gtk-CRITICAL' messages.

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23499]
### Description

Creating a wxSpinCtrl instance (probably also wxSpinButton) with a wxSize like `wxSize(80, -1)` or `wxSize(80, wxDefaultCoord)` will make app at runtime emit the following GTK messages:

```
(widgets:19458): Gtk-CRITICAL **: 11:59:20.033: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```

Using a default coord value for the width does NOT have the same effect.

I am not sure how this should be fixed but I did notice that although the provided size is checked in `PreCreation()` and updated values assigned to `m_width` and `m_height` these values are not used in the `PostCreation()` call that sets the initial size for the widget.

This behavior can be easily reproduced by changing the construction of wxSpinCtrl widgets in any of the samples using those.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE 15.4

+ GTK version:  3.24.34
+ Which GDK  backend is used: X11
+ Current theme:  NA

**Comment by vadz** [comment]
It would be nice to fix this one, it happens quite often and in many places.

**Comment by paulcor** [comment]
AFAICT, this has nothing to do with a default height, it's caused by specifying a fixed width that is too small. The only way to stop it complaining is to give it the size it wants.

**Comment by mcorino** [comment]
You are correct. I tested with the original code triggering this issue.

**Comment by vadz** [comment]
This looks to be invalid then.
