### ISSUE TITLE
wxTreeItemId is implicitly convertable to pointer or bool.

### ISSUE THREAD

**Issue by alysogorov** [wxWidgets/wxWidgets#23502]
When it is recommended to check wxTreeItemId value with method IsOk(), it is possible the write 

wxTreeItemId id;
....
if (id) {

}
so wxTreeItemId looks like implicitly convertable to pointer, integer or bool.

imho this convertion should be explicitly or banned or allowed in class declaration.
thanks.

**Comment by vadz** [comment]
Sorry, I don't think we're going to change this, existing code relies on this conversion and it makes sense: it's not that it _looks_ like it's implicitly convertible to, but it _is_ actually convertible to a pointer.

If it's a real problem, we could provide something akin to `wxNO_IMPLICIT_WXSTRING_ENCODING`, i.e. some `wxNO_IMPLICIT_ITEMID_CONVERSION` that you could predefine before including wx headers to disable this conversion, but IMO it's not worth it.
