### ISSUE TITLE
wxUniv/wxMSW Crash "access violation at address" on exit application

### ISSUE THREAD

**Issue by Kvaz1r** [wxWidgets/wxWidgets#23513]
### Description
Crash "access violation at address" on exit application

Debug shows that error happen at [wxArtProvider::CleanUpProviders](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/artprov.cpp#L318) on deleting sm_providers.
Reason - attempt to delete artprovider that was already deleted in [theme destructor](https://github.com/wxWidgets/wxWidgets/blob/master/src/univ/themes/gtk.cpp#L539).
I'm not sure should it been replaced with:
`wxArtProvider::Remove(m_artProvider);`
or just removed after std::unique_ptr<> was introduced in https://github.com/wxWidgets/wxWidgets/commit/4a294caacd73a2825a01e2a2a41fbfc719761d89 

### Platform and version information

- wxWidgets version: current master
- wxWidgets port: wxUniv/wxMSW
- OS: Windows 10

**Comment by vadz** [comment]
I've mentioned in that commit message that

    Note that this implies that the only way to delete a wxArtProvider
    registered in the global provider list is by removing it from it,
    instead of deleting it directly, which was apparently allowed before,
    even though it shouldn't have ever been actually done -- but make this
    even more clear in the documentation now.

And the simple fix here is to call `wxArtProvider::Remove()` instead of deleting the provider directly, but perhaps we need some way to keep allowing deleting it directly if our own code does this. I'll try to come up with something...

**Comment by vadz** [comment]
Should be fixed in the linked PR, please let me know if you still see any problems with it, TIA!

**Comment by Kvaz1r** [comment]
> Should be fixed in the linked PR, please let me know if you still see any problems with it, TIA!

Fix works, thanks
