### ISSUE TITLE
treelistctrl behaves odd when resizing the dialog

### ISSUE THREAD

**Issue by FransM** [wxWidgets/wxWidgets#23522]
### Description

I have a wxDialog application with a treelistctrl with 3 columns.
When I run the application the initial window has the tree but only the first column is visible.
There is a scrollbar visible.
When I resize the window (extending it) the 2nd and 3rd column come in view but they move towards the first colum, in the end fully obscuring the first column. 

code snippet
```cpp
MainDialog::MainDialog(wxWindow* parent)
    : MainDialogBaseClass(parent)
{
    auto m_treelist = GetTreeListCtrl22();
    m_treelist->AppendColumn("Component");
    m_treelist->AppendColumn("# Files");
    m_treelist->AppendColumn("Size");

    auto treeparent = m_treelist->GetRootItem();

    wxTreeListItem item1 = m_treelist->AppendItem(treeparent, "item1");
    m_treelist->SetItemText(item1, 1, "11");
    m_treelist->SetItemText(item1, 2, "12");
    wxTreeListItem item2 = m_treelist->AppendItem(treeparent, "item2");
    m_treelist->SetItemText(item2, 1, "21");
    m_treelist->SetItemText(item2, 2, "22");
    wxTreeListItem item3 = m_treelist->AppendItem(item1, "item3");
    m_treelist->SetItemText(item3, 1, "31");
    m_treelist->SetItemText(item3, 2, "32");
    

    m_treelist->Refresh();
    m_treelist->Update();
}
```

Initial screen:
![image](https://user-images.githubusercontent.com/1893299/236298044-167e8a87-cace-4947-9dff-be01cdba968e.png)

After extending the dialog
![image](https://user-images.githubusercontent.com/1893299/236298210-1219728a-1f3a-45d4-8371-6fca8a921528.png)

After extending the dialog more
![image](https://user-images.githubusercontent.com/1893299/236298321-6d3492e9-c44f-439f-a04c-d5220e765b19.png)

and after more resizing I get:
![image](https://user-images.githubusercontent.com/1893299/236298421-f2990ad8-238b-49d0-bcfe-9839051e63fc.png)

### Platform and version information

- wxWidgets version  you use: suspect 3.0.5.1
I installed from the ubuntu feed. These packages
libwxbase3.0-0v5/jammy,now 3.0.5.1+dfsg-4 amd64 [installed,automatic]
libwxbase3.0-dev/jammy,now 3.0.5.1+dfsg-4 amd64 [installed]
libwxgtk3.0-gtk3-0v5/jammy,now 3.0.5.1+dfsg-4 amd64 [installed,automatic]
libwxgtk3.0-gtk3-dev/jammy,now 3.0.5.1+dfsg-4 amd64 [installed]
libwxsqlite3-3.0-0/jammy,now 3.4.1~dfsg-5build1 amd64 [installed,auto-removable]
wx-common/jammy,now 3.0.5.1+dfsg-4 amd64 [installed,automatic]
wx3.0-headers/jammy,jammy,now 3.0.5.1+dfsg-4 all [installed,automatic]

- wxWidgets port  you use:
- OS  and its version: Ubuntu 22.04

+ GTK version: 
+ Which GDK  backend is used: whatever ubuntu gave me, I suspedct wayland
+ Current theme:

**Comment by vadz** [comment]
I suspect this might be already fixed in 3.2, please test your code there. If it's still reproducible, please try making the [minimal changes](https://www.wxwidgets.org/develop/how-to-submit-patches/) to the treelist sample allowing to reproduce the problem, so that it could be debugged easily.

Thanks!

**Comment by FransM** [comment]
I need to correct myself, I did build wxwidgets myself from the git repo, I am using 3.2.2.1 as far as I can  judge.
I'll try to come with a runnable test example later today

**Comment by FransM** [comment]
Ok, withdrawing this PR, I first had installed wxwidgets from the feel but later on cloned, build and installed 3.2.2.1 using the git repo, but did not completely remove 3.0. Apparently codelite picked up the 3.0 headers.
When removing all of 3.0 and rebuilding the problem was gone.
