### ISSUE TITLE
wxBase64Decode rounds up size of output

### ISSUE THREAD

**Issue by kevmac66** [wxWidgets/wxWidgets#23548]
Hi,

I've come across an issue regarding wxBase64Decode and been advised to post it here.
wxBase64Decode appears to round up its output size to a multiple of 3. Now I know base 64 encodes 3 bytes of input into 4 bytes of output and uses 1 or 2 '=' characters to pad the encoded string if required.
But, if I base 64 encode a jpg image and also compute a hash value for the jpg image, then decode it back to a new jpg file and compute a hash value for the new file, it can end up being different.
This makes detecting duplicate images problematic.

I've attached a very simple example of encoding 3 character strings which are 10, 11 & 12 bytes long. Then decode them to file and the files are all 12 bytes.

I'm using: g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
wxWidgets 3.2.2.1

```
#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/base64.h>
#include <iostream>
#include <fstream>

class b64 : public wxApp
{
public:
	b64() {}
	virtual ~b64() {}
	virtual bool OnInit() override;

private:
	const char s1[13] = "123456789012";
	const char s2[12] = "12345678901";
	const char s3[11] = "1234567890";

	void decodeToFile(wxString fileName, wxString s64, size_t len)
	{
		void *buf = malloc(len);

		wxBase64Decode(buf, len, s64, wxBase64DecodeMode_Strict, NULL);
		std::ofstream f(fileName, std::ios::out | std::ios::binary);
		f.write((const char*)buf, len);
		f.close();

		free(buf);
	}
};

bool b64::OnInit()
{
	wxString s1_64 = wxBase64Encode(s1, strlen(s1));
	wxString s2_64 = wxBase64Encode(s2, strlen(s2));
	wxString s3_64 = wxBase64Encode(s3, strlen(s3));

	decodeToFile("s1", s1_64, wxBase64DecodedSize(s1_64.length()));
	decodeToFile("s2", s2_64, wxBase64DecodedSize(s2_64.length()));
	decodeToFile("s3", s3_64, wxBase64DecodedSize(s3_64.length()));

	return false;
}

wxIMPLEMENT_APP(b64);
```

**Comment by vadz** [comment]
Indeed, @PBfordev is absolutely correct. `wxBase64DecodedSize()` just gives you the upper bound on the size needed, i.e. how big a buffer you need. The actual length of the data can be only returned by `wxBase64Decode()` as it depends on the data, so it simply can't be determined by `wxBase64DecodedSize()` which doesn't have this data.

**Comment by kevmac66** [comment]
I changed my test to use the returned value from ``wxBase64Decode()`` rather than ``wxBase64DecodedSize()`` and yes it gives the correct values.
So, my mistake, thanks for correction.
