### ISSUE TITLE
wxAuiManager::GetPane() returns an unstable reference.

### ISSUE THREAD

**Issue by rcane** [wxWidgets/wxWidgets#23545]
The switch to using `wxBaseArray` for `wxAuiManager::m_panes` in 39706e4 makes the `wxAuiPaneInfo&` returned by `GetPane()` become invalid when the array is being reallocated. This is basically the same problem as #23514.

**Comment by vadz** [comment]
I think this should be fixed now and I've pushed this without the usual testing period to avoid more people having problems due to this. Please let me know/reopen if you still see any problems.

And thanks for reporting this!
