### ISSUE TITLE
Printing from a preview window using wxHtmlEasyPrinting can fail on Windows

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#23550]
Post-wx.3.2.2, printing was changed to using PrintDlgEx and PRINTDLGEX, and page ranges were added. In the past, I simply created a wxPrintDialogData data object and passed that into the preview window. This worked with PrintDlg, defaulting to print all pages. It now results in a return code of E_INVALIDARG from PrintDlgEx.

Specifically setting From/To pages (using the preview window's GetMinPage/GetMaxPage) fixed this issue (I did need to do a SetAllPages(true) to get my old behavior, or the dlg would default to selecting the range).

I wasn't able to repro in the 'printing' sample - I think adding a debug log message when E_INVALIDARG is returned from PrintDlgEx would be a good idea. Or maybe an assert. A comment there about From/To pages not being 0 on a PRINTPAGERANGE might give the developer a clue on what to fix.

**Comment by dconnet** [comment]
I found a work around so existing code does not need changes - In printdlg.cpp, after line 892 (head of dev as of 2023-5-15), I just added:
```
if (pd->lpPageRanges[0].nFromPage == 0 || pd->lpPageRanges[0].nToPage == 0)
{
    pd->lpPageRanges[0].nFromPage = pd->lpPageRanges[0].nToPage = 1;
}
```

**Comment by vadz** [comment]
I think this actually worked in the other direction previously, see 3.2 code: https://github.com/wxWidgets/wxWidgets/blob/89dc204bb608c9177ac60ee8e657c9efdeb470ab/src/msw/printdlg.cpp#L909-L910

I.e. if `from` or `to` page wasn't specified, page numbers selection was disabled -- instead of enabling it with just a single page, which doesn't seem particularly useful.

So I think the right fix restoring the old behaviour would be to modify `GetEnablePageNumbers()` to return true iff `m_printFromPage` and `m_printToPage` are valid, i.e.
```diff
diff --git a/include/wx/cmndata.h b/include/wx/cmndata.h
index 101345409d..6be12ceebd 100644
--- a/include/wx/cmndata.h
+++ b/include/wx/cmndata.h
@@ -191,7 +191,11 @@ class WXDLLIMPEXP_CORE wxPrintDialogData: public wxObject
     bool GetEnablePrintToFile() const { return m_printEnablePrintToFile; }
     bool GetEnableSelection() const { return m_printEnableSelection; }
     bool GetEnableCurrentPage() const { return m_printEnableCurrentPage; }
-    bool GetEnablePageNumbers() const { return m_printEnablePageNumbers; }
+    bool GetEnablePageNumbers() const
+    {
+        // We should only enable page numbers selection if we have any pages.
+        return m_printEnablePageNumbers && m_printFromPage && m_printToPage;
+    }
     bool GetEnableHelp() const { return m_printEnableHelp; }

     // Is this data OK for showing the print dialog?
```

David, does this fix the problem for you?

cc @sz5000: please let me know if you have any thoughts about this

**Comment by dconnet** [comment]
No. With 3.2.2, you still get the page number option - which is what I want. What it shows in the page range is just "1", so my (kludge) fix is restoring the old behavior. (Maybe in debug we can add a "warning: you haven't set the range")

**Comment by dconnet** [comment]
Oh, I should note the behavior I'm trying to get: By default "All Pages" is selected, but "Pages" is available in case the user doesn't want all. I wasn't interested in enabling "Selection" or "Current Page" options.

**Comment by vadz** [comment]
> Oh, I should note the behavior I'm trying to get: By default "All Pages" is selected, but "Pages" is available in case the user doesn't want all.

But what can the user enter there if there is no information about the pages? Are you still able to enter something there in 3.2?

Could you please explain what are the values used in your `wxPrintDialogData`? Because I just don't see how would "Pages" be available if `from` or `to` page is 0, looking at 3.2 code above.

**Comment by dconnet** [comment]
I think that's the difference between how PrintDlg and PrintDlgEx work. With "0" I have (with a 4 page document)

![image](https://github.com/wxWidgets/wxWidgets/assets/11083463/c1bd22e3-a48a-469d-a8dc-564d6ac685c8)

**Comment by dconnet** [comment]
From the debugger, my printdialog data is:
```
		m_printFromPage	0	int
		m_printToPage	0	int
		m_printMinPage	0	int
		m_printMaxPage	0	int
		m_printNoCopies	1	int
		m_printAllPages	false	bool
		m_printCollate	false	bool
		m_printToFile	false	bool
		m_printSelection	false	bool
		m_printEnableSelection	false	bool
		m_printEnablePageNumbers	true	bool
		m_printEnableHelp	false	bool
		m_printEnablePrintToFile	true	bool

```

**Comment by vadz** [comment]
> I think that's the difference between how PrintDlg and PrintDlgEx work.

Yes, indeed, the latter seems to validate `lpPageRanges` contents, unless `PD_NOPAGENUMS` is set, while the former doesn't have it at all.

So I think your initial fix is correct and we should apply this:
```diff
diff --git a/src/msw/printdlg.cpp b/src/msw/printdlg.cpp
index 6325c4dc87..1e37fc1356 100644
--- a/src/msw/printdlg.cpp
+++ b/src/msw/printdlg.cpp
@@ -888,12 +888,19 @@ bool wxWindowsPrintDialog::ConvertToNative( wxPrintDialogData &data )
         pd->nPageRanges = 1;
         pd->nMaxPageRanges = 1;
         pd->lpPageRanges = new PRINTPAGERANGE[1];
-        pd->lpPageRanges[0].nFromPage = (DWORD)data.GetFromPage();
-        pd->lpPageRanges[0].nToPage = (DWORD)data.GetToPage();
 
-        // PrintDlgEx returns E_INVALIDARG if nFromPage is greater than nToPage
-        if (pd->lpPageRanges[0].nToPage < pd->lpPageRanges[0].nFromPage)
-            pd->lpPageRanges[0].nToPage = pd->lpPageRanges[0].nFromPage;
+        DWORD nFromPage = data.GetFromPage();
+        DWORD nToPage = (DWORD)data.GetToPage();
+
+        // The page range must be valid, otherwise PrintDlgEx() simply fails
+        // with E_INVALIDARG.
+        if ( !nFromPage )
+            nFromPage = 1;
+        if ( nToPage < nFromPage )
+            nToPage = nFromPage;
+
+        pd->lpPageRanges[0].nFromPage = nFromPage;
+        pd->lpPageRanges[0].nToPage = nToPage;
     }
 
     pd->Flags = PD_RETURNDC;
```

Does this work both for you, @dconnet, and for @sz5000?

**Comment by sz5000** [comment]
Can the page numbers returned by GetFromPage and GetToPage be negative? If so, a simple cast to  a DWORD will cause problems. I think it better work work with ints for the validation part. The cast could then be done here:

```
pd->lpPageRanges[0].nFromPage = (DWORD) nFromPage;
pd->lpPageRanges[0].nToPage = (DWORD) nToPage;
```

**Comment by vadz** [comment]
I'm applying the patch above, please reopen/comment if it doesn't fix the problem.
