### ISSUE TITLE
win32/master/duplicate definition wxStringFormat::Validate

### ISSUE THREAD

**Issue by kfsone** [wxWidgets/wxWidgets#23568]
Commit Hash: (from master)

Build System: CMake 3.24, Windows 11, VS 2019 VisualStudio.16.Release/16.11.25+33423.256, en_US

Build Configuration:
with utf8 set to "ON" or "OFF":
```
    & $cmake -B $BuildDir `
        "$(if ("$Generator") { "${Generator}" })" `
        "-DCMAKE_CONFIGURATION_TYPES=Debug;RelWithDebInfo" `
        -DwxBUILD_BENCHMARKS=OFF `
        -DwxBUILD_CXX_STANDARD=17 `
        -DwxBUILD_DEMOS=OFF `
        -DwxBUILD_INSTALL=OFF `
        -DwxBUILD_MONOLITHIC=ON `
        -DwxBUILD_MSVC_MULTIPROC=ON `
        -DwxBUILD_OPTIMISE=ON `
        -DwxBUILD_PRECOMP=ON `
        -DwxBUILD_SAMPLES=OFF `
        -DwxBUILD_SHARED=OFF `
        -DwxBUILD_STRIPPED_RELEASE=ON `
        -DwxBUILD_TESTS=OFF `
        -DwxUSE_EXPAT=builtin `
        -DwxUSE_LIBJPEG=builtin `
        -DwxUSE_LIBLZMA=OFF `
        -DwxUSE_LIBPNG=builtin `
        -DwxUSE_LIBTIFF=builtin `
        -DwxUSE_MEDIACTRL=OFF `
        -DwxUSE_POSTSCRIPT=OFF `
        -DwxUSE_POSTSCRIPT_ARCHITECTURE_IN_MSW=OFF `
        -DwxUSE_PRINTING_ARCHITECTURE=OFF `
        -DwxUSE_RIBBON=OFF `
        -DwxUSE_SOUND=OFF `
        -DwxUSE_SVG=OFF `
        -DwxUSE_STL=OFF `
        -DwxUSE_ZLIB=builtin `
        -DwxUSE_UNICODE=ON `
        -DwxDEBUG_LEVEL=0 `
        "-DwxUSE_UNICODE_UTF8=${utf8}" `
        $SourceDir
```
(complete script: https://gist.github.com/kfsone/12a9b86ce349ade41879b1a01cc3a28e)

We end up with the following link error:

```
wxmsw33ud.lib(strvararg.obj) : error LNK2005: "public: void __cdecl wxFormatString::Validate(class std::vector<int,class std::allocator<int> > const &)const " (?Validate@wxFormatString@@QEBAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z) already defined in AppLayoutManager.obj
```

(just happens to be the first executable to invoke a string format). This tooling has been building previous versions of wxWidgets without issue.

The problem appears to be this method implementation in strvararg.h:355 (outside of the class):
```
    // Also provide a trivial implementation of Validate() doing nothing in
    // this case.
    inline void
    wxFormatString::Validate(const std::vector<int>& WXUNUSED(argTypes)) const
    {
    }
```

**Comment by kfsone** [comment]
This appears to be caused by a difference between wxDEBUG_LEVEL while building the library (static) and building the executable. Did something change between 3.2.0 and that would affect setting wxDEBUG_LEVEL from CMakeLists?

**Comment by vadz** [comment]
I don't know, but if it did, it would be indeed a problem in our CMakefiles as `wxDEBUG_LEVEL` must have the same value for the application and the library (if they differ, and even if it linked, you'd get a fatal error on startup).

**Comment by MaartenBent** [comment]
Afaik nothing has changed in CMake. It has always been like this:
https://github.com/wxWidgets/wxWidgets/blob/563cc11151ee0d986dae8939c4bb24a3a42c0611/build/cmake/init.cmake#L195-L197
It uses the default value somewhere defined in a header, or you can override it with `wxBUILD_DEBUG_LEVEL`.

**Comment by MaartenBent** [comment]
I see you use `wxDEBUG_LEVEL` directly instead. I don't think this is automatically applied to the projects, then you need to put it in something like `CMAKE_CXX_FLAGS`.
Does CMake not warn about an unused define?

**Comment by kfsone** [comment]
That *was* my mistake, and no it didn't, confident of that because I did notice that it started complaining that wxUSE_UNICODE (sp?) was unused and had to address that (mature codebase, we haven't reached sufficient pain point yet to warrant upgrading all our libraries/code to unicode ;)

**Comment by vadz** [comment]
I guess this can be closed then, right?
