### ISSUE TITLE
Adding CompositeDataObject with BitmapDataObject as first (or only) member data to clipboard causes segmentation faults with WXMSW.

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23564]
### Description
When creating a CompositeDataObject with a BitmapDataObject added as it's first (or only) data member and adding that composite to the clipboard an application will crash with a segmentation fault after a short delay (not immediately but for example when processing another event like a menu click).
This problem seems to be specific to WXMSW. The same code runs flawlessly with WXGTK.

The attached ZIP contains updated code for the standard clipboard sample which demonstrates the problem.
[clipboard.zip](https://github.com/wxWidgets/wxWidgets/files/11554153/clipboard.zip)

To reproduce:

1. Copy the unpacked source file into the samples/clipboard folder and rebuilt the sample on Windows (WXMSW)
2. start the sample app
3. select the menu item [File] -> [Put BAD data on the clipboard]
4. trying to click another menu item will segfault the app (waiting will also cause it to crash automatically after some time)

The menu item [File] -> [Put GOOD data on the clipboard] demonstrates that this only happens when the BitmapDataObject is the
first member of the CompositeDataObject as for this option the composite is created with a TextDataObject as first member and a  BitmapDataObject second. Selecting this menu item will not cause a segfault.

It also does not make a difference if the BitmapDataObject has valid Bitmap data set or not.

### Platform and version information

- wxWidgets version  you use: 3.2.2.1 & 3.3 (master)
- wxWidgets port  you use: WXMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
This is due to the wrong cast here:

https://github.com/wxWidgets/wxWidgets/blob/563cc11151ee0d986dae8939c4bb24a3a42c0611/src/msw/clipbrd.cpp#L586-L589

Should be simple to fix.

<details>
<summary>Diff for reproducing the problem for reference</summary>

```diff
diff --git a/samples/clipboard/clipboard.cpp b/samples/clipboard/clipboard.cpp
index ed865d1a0a..fdb9959b58 100644
--- a/samples/clipboard/clipboard.cpp
+++ b/samples/clipboard/clipboard.cpp
@@ -48,6 +48,8 @@ class MyFrame : public wxFrame
     void OnQuit(wxCommandEvent&event);
     void OnAbout(wxCommandEvent&event);
     void OnFlush(wxCommandEvent &event);
+    void OnSetBad(wxCommandEvent &event);
+    void OnSetGood(wxCommandEvent &event);
     void OnWriteClipboardContents(wxCommandEvent&event);
     void OnUpdateUI(wxUpdateUIEvent&event);
 #if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
@@ -70,13 +72,17 @@ enum
     ID_About  = wxID_ABOUT,
     ID_Write  = 100,
     ID_Text   = 101,
-    ID_Flush  = 102
+    ID_Flush  = 102,
+    ID_SetBad  = 103,
+    ID_SetGood  = 104
 };
 
 wxBEGIN_EVENT_TABLE(MyFrame, wxFrame)
     EVT_MENU(ID_Quit,  MyFrame::OnQuit)
     EVT_MENU(ID_About, MyFrame::OnAbout)
     EVT_MENU(ID_Flush, MyFrame::OnFlush)
+    EVT_MENU(ID_SetBad, MyFrame::OnSetBad)
+    EVT_MENU(ID_SetGood, MyFrame::OnSetGood)
     EVT_BUTTON(ID_Write, MyFrame::OnWriteClipboardContents)
     EVT_UPDATE_UI(ID_Write, MyFrame::OnUpdateUI)
 #if USE_ASYNCHRONOUS_CLIPBOARD_REQUEST
@@ -117,6 +123,8 @@ bool MyApp::OnInit()
     helpMenu->Append(ID_About, "&About\tF1", "Show about dialog");
 
     fileMenu->Append(ID_Flush, "Flush the clipboard" );
+    fileMenu->Append(ID_SetBad, "Put BAD data on the clipboard" );
+    fileMenu->Append(ID_SetGood, "Put GOOD data on the clipboard" );
     fileMenu->Append(ID_Quit, "E&xit\tAlt-X", "Quit this program");
 
     // now append the freshly created menu to the menu bar...
@@ -138,6 +146,39 @@ bool MyApp::OnInit()
     panel->SetSizer( main_sizer );
 }
 
+void MyFrame::OnSetBad(wxCommandEvent &WXUNUSED(event))
+{
+    wxDataObjectComposite *comp = new wxDataObjectComposite;
+    //wxBitmap bmp; bmp.CopyFromIcon(this->GetIcon());
+    comp->Add(new wxBitmapDataObject);
+    comp->Add(new wxTextDataObject("Hello"));
+    if (wxTheClipboard->Open())
+    {
+      if (!wxTheClipboard->AddData(comp))
+      {
+        m_textctrl->AppendText("Failed to put composite on clipboard.\n");
+      }
+  
+      wxTheClipboard->Close();
+    }
+}
+
+void MyFrame::OnSetGood(wxCommandEvent &WXUNUSED(event))
+{
+    wxDataObjectComposite *comp = new wxDataObjectComposite;
+    comp->Add(new wxTextDataObject("Hello"));
+    comp->Add(new wxBitmapDataObject);
+    if (wxTheClipboard->Open())
+    {
+      if (!wxTheClipboard->AddData(comp))
+      {
+        m_textctrl->AppendText("Failed to put composite on clipboard.\n");
+      }
+  
+      wxTheClipboard->Close();
+    }
+}
+
 void MyFrame::OnFlush(wxCommandEvent &WXUNUSED(event))
 {
     wxClipboardLocker clipLock;
```
</details>

**Comment by vadz** [comment]
Looking further at this, this code was added in b1fad4da44 (Convert 0RGB wxBitmaps to RGB when copying them to clipboard, 2017-04-30) and there is no nice way to fix it, i.e. without using dynamic casts. Of course, if there is no other way to do it, we could use the casts, but I wonder why was this bitmap transformation added here, it looks like it would be much more logical to do this in `wxBitmapDataObject::GetDataHere()` instead.

@a-wi Why can't this code be moved there? It would fix this problem and also be potentially more efficient as we'd avoid creating a copy of the bitmap until it's really needed.

**Comment by a-wi** [comment]
> This is due to the wrong cast here:

If there is a problem with casting the same cast for wxDF_BITMAP and wxDF_DIB is done elsewhere:
https://github.com/wxWidgets/wxWidgets/blob/563cc11151ee0d986dae8939c4bb24a3a42c0611/src/msw/clipbrd.cpp#L654-L657

**Comment by vadz** [comment]
Sorry, I hadn't even noticed it, but this code is equally wrong, of course. The saving grace for it is that it's almost never used: normally the branch above, guarded by `#if wxUSE_OLE_CLIPBOARD` is.

Maybe we should just remove all the old code and leave only the `wxUSE_OLE` case... But this is a a separate issue from this one and I still think the best way to fix it would be to do this in `GetDataHere()`. I'll try doing this, if you don't see any objections, I hope the test case from #17640 still works...

**Comment by vadz** [comment]
The first commit of #23659 fixes this without reintroducing the problem of #17640.
