### ISSUE TITLE
Regression in behaviour of wxFileProperty with wxWidgets >= 3.1.3

### ISSUE THREAD

**Issue by StefanBattmer** [wxWidgets/wxWidgets#23565]
The following commit effectively did change the default behaviour of the wxFileProperty of the wxPropertyGrid control: https://github.com/wxWidgets/wxWidgets/commit/37f9c6f0837a9e3ee14c49b1e1eb1f2a756a06a8.

The documented behaviour is:

> "ShowFullPath": Default 1. When 0, only the file name is shown (i.e. drive and directory are hidden).

Since 3.1.3 this is no longer the case. The reason for this is the change from 

`#define wxPG_PROP_ACTIVE_BTN    wxPG_PROP_CLASS_SPECIFIC_3`

to

`#define wxPG_PROP_ACTIVE_BTN    wxPG_PROP_CLASS_SPECIFIC_1`

because here

```
wxFileProperty::wxFileProperty( const wxString& label, const wxString& name,
                                const wxString& value )
    : wxEditorDialogProperty(label, name)
{
    m_flags |= wxPG_PROP_SHOW_FULL_FILENAME;
    m_flags &= ~wxPG_PROP_ACTIVE_BTN; // Property button enabled only in not read-only mode.
    m_indFilter = -1;
    m_wildcard = wxALL_FILES;

    SetValue(value);
}
```

*wxPG_PROP_SHOW_FULL_FILENAME* unfortunately is also defined as *wxPG_PROP_CLASS_SPECIFIC_1*

so what actually is happening now is this:

```
    m_flags |= wxPG_PROP_CLASS_SPECIFIC_1; // Turn on a flag
    m_flags &= ~wxPG_PROP_CLASS_SPECIFIC_1; // Turn off the same flag again
```

**Comment by vadz** [comment]
Thanks for noticing this!

I don't know why did the value of `wxPG_PROP_ACTIVE_BTN` change. This was done in 37f9c6f083 (Implement wxEditorDialogProperty as a base class for wxPG properties with dialog editor, 2019-07-01) but isn't really explained there AFAICS.

@a-wi Would you have an idea about this and, more importantly, how to fix this?
