### ISSUE TITLE
Problem with opengl/penguin sample

### ISSUE THREAD

**Issue by gerard-durand** [wxWidgets/wxWidgets#23579]
I have updated and downloaded yesterday, via git, wxwidgets 3.3. It compiles correctly with last gcc 13.1 found with msys2 packages.
Nevertheless, when I try the penguin opengl sample after rebuilding, it crashes : I obtain a gray empty window for one or 2 seconds, then the window is closed without displaying the penguin. Other opengl samples works as expected.
If I replace dxfrenderer.cpp and .h with previous versions (as distributed with 3.2.2.1 wxwidgets), it's OK. The sample works as expected.
I don't know if it is a new dxfrenderer problem or an incompatibility with gcc 13.1. I think that with gcc 12.2, I had no such problems, but I don't remember if I had verified this sample test with that compiler version.

I'm on Window 10 64 bit, last updated version. I compiled with option CXXFLAGS="-std=gnu++20".

**Comment by oneeyeman1** [comment]
@gerard-durand ,
Can you show a backtrack at the  time of the crash?

Thank you.

**Comment by gerard-durand** [comment]
I'm not familiar with backtracing, but this is what I obtain by modifying my make command with CXXFLAGS="-g -std=gnu++20" CFLAGS="-g" and entering in a command line : gdb penguin.exe. The wxwidgets version 3.3.0 is still the release one, not a debug one.

[Backtrace.txt](https://github.com/wxWidgets/wxWidgets/files/11600777/Backtrace.txt)

**Comment by PBfordev** [comment]
I can confirm the issue, I get an assert, happens with both GCC and MSVC. The output from MSVC is:
> D:\Dev\Desktop\!Lib\wxWidgets-PB\samples\opengl\penguin\dxfrenderer.cpp(320): assert "col >= 0 && col <= 255" failed in ACIColourToRGB().

Relevant call stack:
```
penguin.exe!ACIColourToRGB(int col=1084227584) Line 320	C++	Symbols loaded.
penguin.exe!DXFRenderer::Render() Line 649	C++	Symbols loaded.
penguin.exe!TestGLCanvas::OnPaint(wxPaintEvent & __formal={...}) Line 195	C++	Symbols loaded.
```

It does not happen with 3.2.2.1 so perhaps this is the culprit: https://github.com/wxWidgets/wxWidgets/commit/b76ebc61d9817d286ecb38b9ecacc32c7b92f30c (I did not look into this).

**Comment by vadz** [comment]
Sorry for breaking this and thanks for reporting the problem.

**Comment by gerard-durand** [comment]
It's OK now. Thanks for corrections.

**Comment by vadz** [comment]
Thanks for retesting and sorry for forgetting to mention this issue in the commit message of 885c87d865c2dd71dbe6b78afe40545bc82caf4e.
