### ISSUE TITLE
wxGTK: wxKeyEvent::m_isRepeat undefined (UBSAN Message in keyboard sample)

### ISSUE THREAD

**Issue by jolz** [wxWidgets/wxWidgets#23593]
### Description
This is only a sanitizer warning, not a real bug. I never experienced Problems with this.

rare Message from UBSAN: the bool wxKeyEvent::m_isRepeat  has some undefined value since Pull Request #2414

To reproduce please compile wxWidgets with Sanitizer,e.g.
```sh
mkdir build.asan
cd build.asan
cmake -DwxBUILD_SAMPLES=ALL -DCMAKE_CXX_FLAGS=-fsanitize=address,undefined -DCMAKE_EXE_LINKER_FLAGS=-fsanitize=address,undefined -DCMAKE_SHARED_LINKER_FLAGS=-fsanitize=address,undefined ..
cmake --build . -j$(nproc) --target keyboard
lib/keyboard # then type lots of chars
```
after typing a lot (e.g. press and hold a normal key. or type different keys. UBSAN detects this once in ~100 keystrokes)
```
wxWidgets-master/include/wx/event.h:2308:26: runtime error: load of value 96, which is not a valid value for type 'bool'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior wxWidgets-master/include/wx/event.h:2308:26 in 
```

you may get a Stacktrace with 
```sh
UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 lib/keyboard
```

#### proposed fix
insert  `event.m_isRepeat = false;` in file src/gtk/window.cpp function wxFillOtherKeyEventFields
https://github.com/wxWidgets/wxWidgets/blob/3.2/src/gtk/window.cpp#L1034

**or event better**: proper initialization of members in include/wx/event.h (https://github.com/wxWidgets/wxWidgets/blob/3.2/include/wx/event.h#L2286)
```c++
  # file include/wx/event.h:2286 in class WXDLLIMPEXP_CORE wxKeyEvent
    bool          m_isRepeat{false};
```

### Platform and version information

- wxWidgets version  you use: 3.2.2.1, master
- wxWidgets port  you use: wxGTK
- OS  and its version: openSUSE Leap 

+ GTK version: 3.24.34
+ Which GDK  backend is used: X11

**Comment by vadz** [comment]
Thanks for reporting this, we indeed need to initialize this field, I'll fix it in master and in 3.2.
