### ISSUE TITLE
After upgrading to VS 17.6, including itemid.h breaks

### ISSUE THREAD

**Issue by dconnet** [wxWidgets/wxWidgets#23590]
With warnings as errors, and most warnings turned on (/Wall, with as small a list of possible of warnings that are ignored), VS17.6 now complains:

>d:\devtools\wx\wxWidgets-3.2.2\include\wx\itemid.h(36,5): warning C5266: 'const' qualifier on return type has no effect

Windows 10, wx3.2.2.1.

**Comment by vadz** [comment]
Thanks for reporting this! The code is indeed wrong and we should probably remove `const` from here but I'm not sure about ABI implications of doing this. Normally this function is inline, so there shouldn't be any, but I'm not 100% sure about it. If this doesn't work, we should use compiler-specific pragmas to disable it, I guess...

**Comment by dconnet** [comment]
FYI: I've removed it in my local build, and all seems good. But as you say, there could be ABI issues. (But if it has no effect - according to the msg, maybe not?)
