### ISSUE TITLE
wxTextCtrl inconsistent height in wxGTK

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#23610]
## Description

wxTextCtrl has height that is inconsistent with native GTK apps, and if `SetFont` is called, between wxTreeBook pages.

(GTK app on the left, wxWidgets app on the right, 96 dpi)

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/d1dcdeb6-7ef9-49f8-a41d-2e155cbd6484)

If pages are added as pages to wxTreeBook and `m_treebook->SetFont( m_treebook->GetFont() );` is called, then wxTextCtrl's on the second page change heights:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/e42d7503-a06a-4944-a1fb-a08bc0407e29)

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/3841e624-5fa2-43bf-b221-bd241e3af1a4)

150 dpi:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/be8a469b-e07e-45b9-b543-84e67339215e)

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/345cd469-dc74-41d4-9b21-8d3615f402c6)

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/9e385a70-929d-447d-af67-01a0df600c4d)

## GTK example

<details>
  <summary>hello.c</summary>

```c
#include <gtk/gtk.h>

static void
print_hello (GtkWidget *widget,
             gpointer   data)
{
  g_print ("Hello World\n");
}

static void
activate (GtkApplication *app,
          gpointer        user_data)
{
  GtkWidget *window = gtk_application_window_new (app);
  gtk_window_set_title (GTK_WINDOW (window), "Window");
  gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);

  //GtkWidget *container = gtk_button_box_new (GTK_ORIENTATION_HORIZONTAL);
  GtkWidget *container = gtk_box_new(GTK_ORIENTATION_VERTICAL, 10);
  gtk_container_add (GTK_CONTAINER (window), container);

  //button = gtk_button_new_with_label ("Hello World");
  GtkWidget *item1 = gtk_entry_new();
  gtk_entry_set_text(item1, "Full page text");
  gtk_container_add (GTK_CONTAINER (container), item1);

  GtkWidget *item2 = gtk_entry_new();
  gtk_entry_set_text(item2, "Full page text");
  gtk_container_add (GTK_CONTAINER (container), item2);

  GtkWidget *combo = gtk_combo_box_text_new();
  gtk_combo_box_text_append_text(combo, "Choice 1");
  gtk_combo_box_text_append_text(combo, "Choice 2");
  gtk_combo_box_set_active(combo, 0);
  gtk_container_add (GTK_CONTAINER (container), combo);

  gtk_widget_show_all (window);
}

int
main (int    argc,
      char **argv)
{ 
  GtkApplication *app;
  int status;

  app = gtk_application_new ("org.gtk.example", G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (activate), NULL);
  status = g_application_run (G_APPLICATION (app), argc, argv);
  g_object_unref (app);

  return status;
}
```
</details>

Build/run with
```bash
cc `pkg-config --cflags gtk+-3.0` hello.c -o hello `pkg-config --libs gtk+-3.0` && ./hello
```

## wxWidgets example
<details>
  <summary>notebook.cpp</summary>

```cpp

// For compilers that support precompilation, includes "wx.h".
#include "wx/wxprec.h"

#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

#include <wx/treebook.h>

wxWindow *CreatePage(wxWindow *parent)
{
    wxPanel *panel = new wxPanel(parent);

    wxBoxSizer *bPanelSizer;
    bPanelSizer = new wxBoxSizer(wxVERTICAL);

    wxTextCtrl *text1 = new wxTextCtrl(panel, wxID_ANY, "Full page text",
                                      wxDefaultPosition, wxDefaultSize,
                                      0);
    bPanelSizer->Add(text1, 0, wxDOWN | wxRIGHT | wxLEFT, 5);

    wxTextCtrl *text2 = new wxTextCtrl(panel, wxID_ANY, "Full page text",
                                      wxDefaultPosition, wxDefaultSize,
                                      0);
    bPanelSizer->Add(text2, 0, wxALL, 5);

    wxComboBox *combo = new wxComboBox(panel, wxID_ANY, "Full page text", wxDefaultPosition, wxDefaultSize, {"Choice 1", "Choice 2"});
    bPanelSizer->Add(combo, 0, wxALL, 5);

    panel->SetSizer(bPanelSizer);
    panel->Layout();
    bPanelSizer->Fit(panel);

    return panel;
}

//-----------------------------------------------------------------------------
// MyApp
//-----------------------------------------------------------------------------

class MyApp : public wxApp
{
public:
    bool OnInit() override;
};

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
    if ( !wxApp::OnInit() )
        return false;

#ifdef __WXGTK__
    // Many version of wxGTK generate spurious diagnostic messages when
    // destroying wxNotebook (or removing pages from it), allow wxWidgets to
    // suppress them.
    GTKAllowDiagnosticsControl();
#endif // __WXGTK__

    // wxDialog * dlg = new wxDialog( nullptr, wxID_ANY, "Title", wxDefaultPosition, wxSize(1000, 700),
    //                  wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER );

    wxFrame *dlg = new wxFrame(nullptr, wxID_ANY, "Title", wxDefaultPosition, wxSize(400, 400),
                               wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);

    wxBoxSizer* mainSizer = new wxBoxSizer( wxVERTICAL );
    dlg->SetSizer( mainSizer );

    // Simple test
    if(true)
    {
        mainSizer->Add(CreatePage(dlg), 1, wxEXPAND, 0);
    }

    // wxTreebook test
    if(false)
    {
        wxTreebook* m_treebook = new wxTreebook( dlg, wxID_ANY );
        m_treebook->SetFitToCurrentPage( true );

        m_treebook->SetFont( m_treebook->GetFont() ); // <-------------- Updates the size

        mainSizer->Add( m_treebook, 1, wxEXPAND, 0 );

        m_treebook->AddPage(CreatePage(m_treebook), "Page 1");
        m_treebook->AddPage(CreatePage(m_treebook), "Page 2");
    }

    dlg->Show();

    return true;
}

```
</details>

## Platform and version information

- wxWidgets version: master (https://github.com/wxWidgets/wxWidgets/commit/b9d0541f9ac4d4c356b6ab03772c1fe10a2fd1bc)
- wxWidgets port: wxGTK
- OS and its version: Linux Mint 21.1

+ GTK version: 3.24.33-1ubuntu2
+ Which GDK backend is used: X11
+ Current theme: Adwaita

**Comment by vadz** [comment]
There are probably 2 different bugs here. The inconsistency with GTK must be explained by something we are doing wrong in `wxTextCtrl::DoGetSizeFromTextSize()`, but this doesn't explain the problem with the size being different on different pages.

I feel like I'm missing something fundamental here because I don't understand why are we getting negative margins from GTK (see commit message of 3e0163497614741de83ac64c6aa04c024a0447f5). Should we just ignore the margins here? @paulcor If you have any thoughts, I'd be grateful for them.

As for the other half of the bug, I really have no idea, this needs to be debugged but I don't know when will I have time to do it, so any help would be welcome too.

**Comment by paulcor** [comment]
> The inconsistency with GTK must be explained by something we are doing wrong in `wxTextCtrl::DoGetSizeFromTextSize()`

Mostly it's just getting called too early. In this particular case, `gtk_entry_get_layout_offsets()` doesn't give correct results before the widget has been properly size-allocated.

> but this doesn't explain the problem with the size being different on different pages.

This is because of the `SetFont()`. We have some work-arounds to deal with the font changing before the GTK styles are updated. See #16088.

**Comment by dsa-t** [comment]
Leaving a single wxTextCtrl, here's some logged calls, with the wxTreeBook:

Without SetFont call:
```
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27

<gtk_widget_size_allocate_with_baseline only gets called here>
```

With SetFont call:
```
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27
wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 17, -7 
wxTextCtrl::DoGetSizeFromTextSize resulting height 27

<gtk_widget_size_allocate_with_baseline only gets called here>
...
<switching page>

wxTextCtrl::DoGetSizeFromTextSize preferred height 34
wxControl::GTKGetEntryMargins ret 25, 5 
wxTextCtrl::DoGetSizeFromTextSize resulting height 39
```

In the GTK example, the text entry height is 34. Why is this additional margin needed in wx?

**Comment by vadz** [comment]
> Why is this additional margin needed in wx?

Perhaps due to my misunderstanding of what it means, I thought it made sense to include padding (these margins come from `gtk_style_context_get_padding()` call) into the size of the control, but then I don't understand why is it negative.

However we probably do need to include the padding in horizontal direction, as without this 17 (or 25) the text control would almost certainly be too small. I have no explanation as to why padding should be only used in the horizontal direction but not the vertical one, but if this is what works...

The main problem is that we really need to get the correct value before the allocation happens and I have no idea how to do it.

**Comment by dsa-t** [comment]
It's negative because `priv->text_allocation.height` is 0 and gtk subtracts various things from it
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/941d2f08-b1ea-4b33-adf8-053050ca215c)

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/84ebaf09-7d95-411c-b0bd-7c1b36900dec)

**Comment by vadz** [comment]
Right, thanks, so it's not like we could just ignore negative padding -- we just can't use it at all before the widget is allocated, just as Paul wrote.

Which doesn't help with fixing it, unfortunately. I guess giving it some random initial allocation ourselves wouldn't work neither, would it? Perhaps we could use the same hack that we use for system colours and have a single pre-allocated entry widget somewhere and use it to get the margins? This looks like it should work, actually...

**Comment by vadz** [comment]
Sorry, I don't understand how is this compatible with `-7` for vertical margin from above then.

Anyhow, if you think you can fix, or at least improve something here, please don't hesitate to submit your suggestions as PRs. I don't have time to debug this right now unfortunately.

**Comment by dsa-t** [comment]
The roots of the issue appear to come from [`7a78a93`](https://github.com/wxWidgets/wxWidgets/commit/7a78a9378207266c55b7f4c72fbfb2ae11963d0b#diff-148b28898ee0f590bc00739f5bd0e0cbb751b22a63e10a83ff93bd5a69765382L1821) where wxTextCtrl::DoGetBestSize started using DoGetSizeFromTextSize.
I think it should use wxControl::DoGetBestSize() as before, which doesn't subtract invalid values. Unsure about the magic `80` value. https://github.com/wxWidgets/wxWidgets/commit/3e0163497614741de83ac64c6aa04c024a0447f5 just exposed the issue.
https://github.com/wxWidgets/wxWidgets/issues/23001 needs to be re-evaluated to see if wxTextCtrl::DoGetSizeFromTextSize return invalid values there.

**Comment by vadz** [comment]
`DoGetSizeFromTextSize()` should still work, it's a very useful function. Although typically it's only useful for the width and not height, so perhaps we could use `wxControl::DoGetBestSize()` for the height?
