### ISSUE TITLE
Is wxUIActionSimulator really still "experimental"?

### ISSUE THREAD

**Issue by ojwb** [wxWidgets/wxWidgets#23619]
Describe the bug:

`./configure --help` says:

```
  --enable-uiactionsim    use wxUIActionSimulator (experimental)
```

However there's no mention of it being "experimental" in the [API docs](https://docs.wxwidgets.org/3.2/classwx_u_i_action_simulator.html).  Also this "experimental" marker was [added in 2010](9b7e022676582feadfcce349d66a52be88121ac7) and `git log --grep UIAction` shows quite a lot of changes since then (and may miss some), so I'm wondering if that marker is out of date and should be removed.

The particular motivation for my question is that we've had a request to enable this in the debian packages, which I'm much happier doing if it's no longer actually regarded as experimental by upstream.

Expected vs observed behaviour:

I'd expect "experimental" status to be updated once a feature is no longer regarded as experimental.

To Reproduce:

```
./configure --help|grep experimental
```

I'm happy to provide the trivial patch to drop the marker if that's the appropriate resolution.

**Comment by vadz** [comment]
Thanks for noticing this and I can confirm that this is indeed just an oversight and it hasn't been experimental for a long time and I'll remove it from configure.

But, this being said, this does suffer from some pretty serious problems:

1. It doesn't work reliably (it depends on macOS versions/SDK I think?) under Mac.
2. It doesn't work at all with Wayland and I don't even know if it's possible to make it work there.

I'll mention at least (2) in the docs too.

**Comment by ojwb** [comment]
Thanks.

I'd already spotted and highlighted point (2) but the user requesting this is using X11.

You can at least probably workaround that by forcing use of X11 under wayland via `GDK_BACKEND=x11 myapp` or equivalent.

**Comment by Apteryks** [comment]
@ojwb since reporting https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037164, I've updated the system I used to test from Bullseye to Bookworm, so I now have `libwxgtk3.2-1`, which is already built against `libxtst6`:
```
# apt show libwxgtk3.2-1
Package: libwxgtk3.2-1
Version: 3.2.2+dfsg-2
Priority: optional
Section: libs
Source: wxwidgets3.2
Maintainer: wxWidgets Maintainers <team+wx@tracker.debian.org>
Installed-Size: 14.1 MB
Depends: libc6 (>= 2.33), libcairo2 (>= 1.12.0), libfontconfig1 (>= 2.12.6), libgcc-s1 (>= 3.5), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.49.3), libgtk-3-0 (>= 3.22.25), libjpeg62-turbo (>= 1.3.1), libnotify4 (>= 0.7.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.14.0), libpangoft2-1.0-0 (>= 1.37.2), libpng16-16 (>= 1.6.2-1), libsm6, libstdc++6 (>= 11), libtiff6 (>= 4.0.3), libwxbase3.2-1 (>= 3.2.2+dfsg), libx11-6, libxtst6
Breaks: libwxgtk3.2-0
[...]
```

I've tested the small example script I had attached to that bug report, and it now works!

I had to patch a Python file to avoid a crash in my application though: https://github.com/wxWidgets/Phoenix/commit/5d9f7aa185cd18da3e93ae1d0033fb9172d7a714.patch.  It's on master but not yet in a release.

Thanks for opening this issue!
