### ISSUE TITLE
Inconsistency in setting delta-RLE bitmap background colour

### ISSUE THREAD

**Issue by BrianNixon** [wxWidgets/wxWidgets#23638]
#23599 modified the way wxWidgets sets the background of delta-RLE bitmaps, ostensibly to match the way Windows does it. While that is valid in some cases, it turns out Windows itself is inconsistent.

Given a delta-RLE bitmap, `LoadImage()` with `LR_CREATEDIBSECTION` creates an uncompressed DIB with the same bit depth as the original and with unset pixels given the same colour as the first entry in the colour table. All other bitmap-creation methods (`LoadImage()`/​`LoadBitmap()`/​`CreateDIBitmap()`) create a DDB, which increases the colour depth to 24bpp to match the display device context and makes unset pixels black. 

This difference can be highlighted by adding another image comparison to `CompareBMPImageLoad()` in `tests/​image/​image.cpp`:
```cpp
    wxBitmap bitmap3(filename, wxBITMAP_TYPE_BMP);
    REQUIRE( bitmap3.IsOk() );
    wxImage image3(bitmap3.ConvertToImage());
    REQUIRE( image3.IsOk() );
    INFO("wxBitmap::LoadFile vs wxImage::LoadFile");
    CompareImage(*wxImage::FindHandler(wxBITMAP_TYPE_BMP),
        image3, properties, &image2);
```

In today’s `master`, this test will fail. Before b473163da20c1f36caaf2e4db512bb8fb4d73a93, it would have passed. It is impossible for delta-RLE bitmaps to pass both this test and the existing comparison of `wxDIB::ConvertToBitmap` to `wxImage::LoadFile` (unless the first entry in their colour table happens to be black, which the files in the image tests were presumably deliberately constructed to avoid).

The question is, then: which behaviour should wxWidgets mimic? Both are by some definition ‘correct’. Clearly somebody had made the effort to implement and test the previous version, and that is now broken, so there is a case for undoing the change made in b473163da20c1f36caaf2e4db512bb8fb4d73a93.

**Comment by vadz** [comment]
I have no idea what is the expected or even most useful result in practice, but when in doubt I'd prefer to avoid changing the existing behaviour and so revert the previous change.

If you need the behaviour implemented by it for your use (do you? or was it done just to avoid an inconsistency with Windows in this case?), we should think about providing some way to optionally allow using black for the "undefined" pixels, perhaps via some `wxImage` option.

But we need to either revert it or at least document this is an incompatible change, if we decide that we really want the new behaviour, before the next release.

**Comment by BrianNixon** [comment]
> I have no idea what is the expected or even most useful result in practice

Me neither…

> but when in doubt I'd prefer to avoid changing the existing behaviour and so revert the previous change

Agreed.

> If you need the behaviour implemented by it for your use (do you? or was it done just to avoid an inconsistency with Windows in this case?)

No: I don’t need this. It was just something I noticed while writing the tests for #23573, and I made the change before becoming aware of the precedent for the original behaviour.

> we need to … revert it … before the next release

Yes – I’ll make a PR to undo the change and modify the image tests. (Not today, though…)
