### ISSUE TITLE
CMake 3.18+ seems to be required now

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23632]
I'm getting the following error:
```
CMake Error at build/cmake/config.cmake:50 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LOCATION_RELEASE" is not allowed.
Call Stack (most recent call first):
  build/cmake/config.cmake:165 (wx_get_dependencies)
  build/cmake/config.cmake:204 (wx_write_config)
  build/cmake/main.cmake:51 (include)
  CMakeLists.txt:103 (include)
```
when building using CMake 3.17.5 on a system where a newer version can't be easily installed.

This is due to #23390 (see the changes of 8102958665 (CMake: Add libraries of imported targets to wx-config, 2023-03-28)) which fixed #23373, which doesn't seem worth bumping up CMake requirement so much, and definitely not in 3.2.

Could this fragment be made conditional on CMake version, as apparently only some later version of CMake can set these properties on interface libraries? Or can we somehow whitelist them in the earlier versions too?

I guess we could also try increasing the required CMake version in master, but, again, I definitely don't think we should drop support for older versions in 3.2 without a very good reason, so if we don't find any other solution we need to at least revert e1d8bc89ba (CMake: Add libraries of imported targets to wx-config, 2023-03-28) on this branch.

**Comment by MaartenBent** [comment]
It can indeed be made conditional with something like

```cmake
if(CMAKE_VERSION VERSION_GREATER "3.17")
    ...
endif()
```

I'll have to retry if we could also use `IMPORTED_LOCATION_{DEBUG/RELEASE}`, which might be a white-listed property for imported libraries.
