### ISSUE TITLE
wxChoice widget not usable using a touch screen interface

### ISSUE THREAD

**Issue by Apteryks** [wxWidgets/wxWidgets#23634]
Describe the bug:
When using wxChoice widget (actually, wx.Choice via wxPython, but I don't think this matters) with a touch screen interface, it's not usable.

Expected vs observed behaviour:
I'd expect that it opens on a first press, and allow me to select an option, or alternatively, allow me to drag my pressed finger onto the option I want to select it.

Instead, it briefly flashes open then closes, and I can't change the value.  Long presses keep it open, but it doesn't respond to moving the pressed finger so I still cannot select an item.

The only workaround I've found is to use a pointy object (e.g. a graphite pen), and touch very briefly the down arrow on the right of the widget.  This way I managed to get the widget to open and stay open, but it's very difficult still and near impossible with fingers.

To Reproduce:

Add a Choice widget to a frame.  Run the application drawn to a touch screen interface, and try to select an item.

### Platform and version information

- wxWidgets version: 3.2.2 and wxPython 4.2.0
- wxWidgets port: wxGTK
- OS and its version: Debian Bookworm

+ GTK version: 3.24.37
+ Which GDK backend is used: X11
+ Current theme: Adwaita

**Comment by Apteryks** [comment]
If I run the Combo Box demo from `gtk-demo`, it's similarly difficult: the first dropdown for example, "Items with icons" flickers open then close on most touches.  It sometimes sticks open and this is the only case where I can make a selection.

Curiously, more complicated dropdown such as for the "Where are we ?" one behave correctly (a single touch leaves the dropdown open for selection).

So it seems similar to the situation in wxWidgets but slightly better, perhaps because of the larger size of the elements in that demo app compared to my application.

**Comment by Apteryks** [comment]
Another important note: swiping is equally ineffective, but perhaps this depends on the way my display is configured in Xorg.

**Comment by Apteryks** [comment]
Looks a lot like this GTK upstream bug report: https://gitlab.gnome.org/GNOME/gtk/-/issues/3790

**Comment by vadz** [comment]
I'm afraid we're totally dependent on GTK touch support here, but it also seems very unlikely they're going to improve it in GTK 3, so chances of this being fixed are very slim, unfortunately.

**Comment by Apteryks** [comment]
I see, thanks for checking.  I guess it can be closed now that the defect has been identified to be within GTK and an issue already exists for it.  Thank you!
