### ISSUE TITLE
Change to wxGenericAboutDialog breaks DoAddCustomControls

### ISSUE THREAD

**Issue by Randalphwa** [wxWidgets/wxWidgets#23653]
### Description

PR #23294 which changed wxGenericAboutDialog, added

```c++
    m_contents = new wxPanel(this);
```

Additional controls are now added internally with `m_contents` as the parent. However, that causes problems with any code that implemented `DoAddCustomControls()`. For example, I have:

```c++
    void DoAddCustomControls() override
    {
        AddControl(new wxStaticLine(this), wxSizerFlags().Expand());
```

This now generates an assert in debug builds in existing code because the parent `this` is the wxDialog window, not the new wxPanel window. That means that in existing code, `AddControl()` will no longer work if the control was created with `this` as the parent.

Aside from the issue of the change not being backwards compatible with code the created a class derived from wxGenericAboutDialog, there's also no method to get the correct parent to use without assuming the parent will always be the first child window and/or the first wxPanel. While that's probably true, it seems like adding a method to return whatever the parent should be for controls that will be added via `AddControl()` would be useful.

### Platform and version information

- wxWidgets version  you use: 3.3
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by Randalphwa** [comment]
I think for compatibility, AddControl could look to see if the control's parent is the dialog itself, and if so reparent it to m_contents, and do nothing otherwise. You certainly don't want to reparent all controls since the dev might have created a child parent window (e.g., wxStaticBoxSizer) and used that as the parent for additional controls.

Personally, I think GetCustomControlParent() is the best choice -- it presumably would just return m_contents so the function call would be optimized away in release builds. If the dev really wanted a `parent` variable, they could just make the initial assignment with a call to `auto parent = GetCustomControlParent();` instead of passing the variable via DoAddCustomControls().

**Comment by vadz** [comment]
OK, let's do it like this if nobody else has any better ideas (or objections).

And, I forgot to say, thanks for noticing and reporting this!

**Comment by vadz** [comment]
Please let me know if you have any comments about #23658, TIA!
