### ISSUE TITLE
wxRB_SINGLE does not work in wxGTK

### ISSUE THREAD

**Issue by Newbytee** [wxWidgets/wxWidgets#23652]
### Description
When using the GTK backend for wxWidgets, the `wxRB_SINGLE` style does not work properly. It is impossible to set the radio button to be unchecked (`false`). Sample code:

```cpp
#include <wx/wx.h>

class RadioButtonReproducerApp : public wxApp {
public:
    bool OnInit() override;
};

class RadioButtonReproducerFrame : public wxFrame {
public:
    RadioButtonReproducerFrame();
};

wxIMPLEMENT_APP(RadioButtonReproducerApp);

bool RadioButtonReproducerApp::OnInit() {
    RadioButtonReproducerFrame* frame = new RadioButtonReproducerFrame();
    frame->Show();
    return true;
}

RadioButtonReproducerFrame::RadioButtonReproducerFrame()
    : wxFrame(nullptr, wxID_ANY, "Hello World") {

    wxRadioButton* radio_button = new wxRadioButton(
        this,
        wxID_ANY,
        "Meep 1",
        wxDefaultPosition,
        wxDefaultSize,
        wxRB_SINGLE
    );

    // This should disable the radio button, but it doesn't
    radio_button->SetValue(false);
}
```

I've not specifically tested this on Windows, but the company I work for's internal codebase uses this pattern and it works fine on Windows there.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: Fedora 38

+ GTK version:  3.24.38
+ Which GDK  backend is used: Wayland

**Comment by vadz** [comment]
Unfortunately it looks like a single `GtkRadioButton` can't be turned off: it ensures that there is always an active button in a group and if there are no other buttons in the group it makes itself active even when asked to become inactive.

Searching around a bit it looks like people work around this by creating a hidden radio button and making their "single" buttons members of the same group as this hidden button, and then they can be turned off by turning the hidden button on. I think we should be able to implement support for this (`wxRadioButton::SetValue()` would need to be changed to not ignore `false` argument, but this is minor), however it's not totally trivial and I don't have time to do this right now.

But any PRs doing this would be welcome, of course!
