### ISSUE TITLE
Incorrect settings in Visual studio build files

### ISSUE THREAD

**Issue by antonyvholmes** [wxWidgets/wxWidgets#23676]
After downloading the latest wxWidgets 3.2.2.1 and built the wxWidgets libraries from source in Visual Studio 2019 community.  My app had linker errors.  Checking the settings for the x64 and Win32 settings, release and debug, the builds for the static libraries were configures to use the DLL (dynamic) runtime libraries in the C++ settings, which meant manually changing the settings and rebuilding the libraries again. Can you take a look at this.

**Comment by PBfordev** [comment]
This is not a bug but a feature and is the default for the MSVS solutions, the bundled makefiles, and the cmakefile. Static linking building wxWidgets static libraries, but they still link to the compiler runtimes dynamically (as recommended by Microsoft).

If you really want to build wxWidgets linking with MSVCRT statically using provided MSVS solutions, it would be probably easiest by changing the value of `wxRuntimeLibs` from `dynamic` to `static`, as described [here](https://docs.wxwidgets.org/stable/plat_msw_install.html#autotoc_md21).

**Comment by vadz** [comment]
As @PBfordev wrote (thanks!), this is intentional. Using static CRT libraries is officially not recommended and so is not the default, even if you can still change it.
