### ISSUE TITLE
wxCocoa doesn't catch EVT_KEY_DOWN for ⌘+⎇+Letter

### ISSUE THREAD

**Issue by Upliner** [wxWidgets/wxWidgets#23671]
### Description
Minimal app to reproduce the problem:
```
#include <wx/wx.h>
struct MyApp : wxApp {
    void OnKeyDown(wxKeyEvent& ev) {
        std::cerr << ev.GetKeyCode() << " " << ev.GetModifiers() << std::endl;
    }
    bool OnInit() override {
        auto frame = new wxFrame(nullptr, wxID_ANY, "Hello World");
        new wxPanel(frame);
        Bind(wxEVT_KEY_DOWN, &MyApp::OnKeyDown, this);
        frame->Show(true);
        return true;
    }
};
wxIMPLEMENT_APP(MyApp);
```
When I press Command+Option+L it prints
```
308 2
307 3
```
When I press L alone it prints `76 0`, so for  Command+Option+L it expected to print `76 3`. Other apps such as Key Codes by manytricks display this key combination correctly, and some other apps has this combination as shortcut for some commands, but I can't use it in my app.

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS Ventura 13.4.1

**Comment by vadz** [comment]
308 and 307 are `WXK_CONTROL` and `WXK_ALT` which are both expected (the first is for pressing Command, the second one is for pressing Option), but I don't know why we don't generate any key events for `L` itself.

Running your program with `WXTRACE=keyevent` in the environment might give some clue and debugging this would be welcome, of course -- we need all the help with wxOSX that we can get.

**Comment by Upliner** [comment]
OK I've run it with wxtrace, wxWidgets sees the keypress, but doesn't send KeyDown event to my widgets. Here's log
[wx-keyevent.txt](https://github.com/wxWidgets/wxWidgets/files/11919531/wx-keyevent.txt)

**Comment by vadz** [comment]
Thanks, but I am afraid I still don't know what goes wrong here. AFAICS from looking at the trace messages, we do get to this line, as expected: https://github.com/wxWidgets/wxWidgets/blob/a5c0a817989aa31390ef79a20938f3f3d00473ac/src/osx/cocoa/window.mm#L3885 but `[NSView interpretKeyEvents:]` apparently doesn't do anything with such keys.

@csomor Should we add some test for modifiers above and call `OSXHandleKeyEvent()` for Command+Option keys ourselves?

**Comment by csomor** [comment]
I'll look at things with the keyboard sample, might be that combos with command keys go another route because these probably are keyboard shortcuts

**Comment by vadz** [comment]
From the log attached above it doesn't seem as if they get handled as shortcuts, but I could be wrong and I didn't debug it myself, of course.

TIA in any case!

**Comment by csomor** [comment]
Yes, I think it might also be a problem of impedance mismatch, we are trying to let Cocoa accomplish as much as possible, so we have a high-level Framework and within this trying to catch low-level events. We've gone eg great lengths to support complex input methods by leaving the interpretation of key events to the system. 

So if eg there is a menu with Command-Option-L Shortcut (eg by modifying the clear log shortcut in the keyboards sample) then we get proper handling from within the native menu events (`performKeyEquivalent`) (but no `wxEVT_CHAR_HOOK`, no `wxEVT_KEY_DOWN` only `wxEVT_KEY_UP`) , 

if there's an accelerator table, this is handled in the `wxEVT_CHAR_HOOK` properly, but no `wxEVT_KEY_DOWN` either only `wxEVT_KEY_UP`). If there's nothing around and we're just waiting inside a key event, I think we have to use `wxEVT_CHAR_HOOK` if we want to be notified of every possible keycombo arriving, of something that is not a menu item shortcut

**Comment by vadz** [comment]
As it doesn't seem possible to determine whether `interpretKeyEvents:` did anything or not, I thought about having a (global) flag that would be cleared before calling it and set in sending `insertText:` and `doCommandBySelector:` and anything else that could be called from it. Then if the flag is still not set after it returns, we could generate the key events ourselves.

It looks pretty ugly, but I don't see how to do it otherwise while still keeping the correct priorities/order of different events.

**Comment by csomor** [comment]
With input methods we might have several key down events that get swallowed before a resulting char is inserted, this would mean to issue key down events for every one of them, even though they don't signify anything, wouldn't this lead to other problems ?

**Comment by csomor** [comment]
I've added such an infrastructure a while back in 9be2c371, but basically to solve other problems, but it might be reused for this

**Comment by vadz** [comment]
> With input methods we might have several key down events that get swallowed before a resulting char is inserted, this would mean to issue key down events for every one of them, even though they don't signify anything, wouldn't this lead to other problems ?

I'm not sure what is the order of native notifications when an IME is used. Ideal would probably be to get some notification about it becoming active and suspend key event generation until it's dismissed.
