### ISSUE TITLE
wxDatagramSocket::SendTo forces the repeated input of a character whose code is in the highest byte of the uint16_t being sent, the lowest byte of which is one (???)

### ISSUE THREAD

**Issue by GeorgyStolbovoy** [wxWidgets/wxWidgets#23679]
### Description
Yes, I am also very astonished. I didn't expect to encounter such an incredible bug. I spent several hours debugging, and found the reason for the incorrect operation of the program in SendTo, which spams keyboard input events with my input data only. If you pass a two-byte number to this function as a buffer, specify exactly 2 as the third argument, and at the same time the buffer's lowest byte will be 0x1 (not 0, not 0x2, not 0x3, and most likely not all the others), then SendTo will take the highest byte of the buffer and start flooding by typing a character corresponding to this code, as if I pressed the key and hold it without letting go 🥴
If during this spam you abruptly put the cursor in an arbitrary input field, then a character from the SendTo buffer will be written there. After that, spam will stop, because the window will lose focus.
Here's how to reproduce this miracle:
```c++
#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/socket.h>

struct Frame : public wxFrame
{
	wxDatagramSocket* socket;
	wxIPV4address host;

	Frame();
};

struct App : wxApp
{
	bool OnInit() override;
};

bool App::OnInit()
{
	Frame* frame = new Frame();
	frame->Show(true);
	return true;
}

wxIMPLEMENT_APP(App);

Frame::Frame() : wxFrame(nullptr, wxID_ANY, "SendTo & Hook Problem", wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE | wxWANTS_CHARS)
{
	Bind(wxEVT_CHAR_HOOK, [this](wxKeyEvent& e)
	{
		switch (wchar_t k = e.GetKeyCode(); k)
		{
			case 0x41: // A
			case 0x43: // C
			case 0x42: // B
			case 0x44: // D
			case WXK_LEFT:
			case WXK_RIGHT:
			{
				wxLogDebug(L"You entered: %c", k);
				uint16_t cmd = 0x1 | k << 8; // for example: k is B : 0010 1010 0000 0001
				socket->SendTo(host, &cmd, 2); //	   	      |--0x42-| |--0x1--|
				e.DoAllowNextEvent();
				return;
			}
			default:
				e.Skip();
		}
	});

	host.LocalHost();
	host.Service(16800);
	wxIPV4address addr;
	addr.AnyAddress();
	socket = new wxDatagramSocket(addr);
	socket->SetTimeout(3);
}
```
The program catches the keys with a hook and sends their codes as part of a two-byte number over UDP. The lower byte of this number is needed by the server to determine the type of message. It is expected that after pressing one of the monitored keys, the program will send a message with a code and go to rest, but no - the flood of this message will begin. If you run this code and enter A, B, C or D, the debug console will be flooded with messages from the line
```c++
wxLogDebug(L"You entered: %c", k);
```
I tried varying the size of the variable, the numbers in the upper and lower bytes, and it doesn't work only if the buffer is a two-byte number with one in the lower byte - exactly what I need to send 👌👌👌 If a key code is passed in the highest byte, which is not among those tracked in the hook, then a keyboard input message will also be generated, but the default branch will work. This especially confused me at first.
In debugging inside wxWidgets, I localized the problem place in the 710th line of the file socket.cpp:
```c++
DO_WHILE_EINTR( ret, sendto(m_fd, static_cast<const char *>(buffer), size,
                                0, m_peer.GetAddr(), m_peer.GetLen()) );
```
After debugging passes through it, a symbol is suddenly inserted where the cursor is. Wonders. Nothing like this happens with other input data for SendTo.
Oh, yes, to confuse even more: this does not happen with all keys. For example, there is no spam with the WXK_LEFT and WXK_RIGHT buttons (as in the code) under the same conditions, a false char event is not generated 😐
### Platform and version information

- wxWidgets version: 3.2.2.1
- wxWidgets port: wxMSW
- OS: Windows 10

**Comment by vadz** [comment]
Can anybody else reproduce this? I certainly can't...

I'd be very surprised if it's not some weird build problem. Please check the stack when your handler is executed unexpectedly.

**Comment by GeorgyStolbovoy** [comment]
> Can anybody else reproduce this? I certainly can't...
> 
> I'd be very surprised if it's not some weird build problem. Please check the stack when your handler is executed unexpectedly.

![image](https://github.com/wxWidgets/wxWidgets/assets/71210013/ffea9ccb-c35f-47c2-b203-f5147a242ac0)
SendTo provokes real keyboard input, so the handler's response to this is correct.

![image](https://github.com/wxWidgets/wxWidgets/assets/71210013/ffcb95d5-aeb6-4641-98ab-7c107cf3d7ba)

Slightly missed:
![image](https://github.com/wxWidgets/wxWidgets/assets/71210013/b728ed21-3837-4613-8083-813ecf88be27)

**Comment by vadz** [comment]
Something is clearly wrong with this stack because the frame with `sendto` itself doesn't appear in it. You should set up Microsoft symbols so that you don't get "external code", but I don't think this would actually explain what's going on.

Also, when debugging, switch to the "assembly view" and trace instruction by instruction if you want to really see what's going on.

But for me it's some kind of a local problem. If not a bad build, then maybe some kind of (malfunctioning) malware. But this just can't happen in normal circumstances. I could be wrong, but someone else would need to reproduce this to make me doubt this conclusion.

**Comment by GeorgyStolbovoy** [comment]
> Something is clearly wrong with this stack because the frame with `sendto` itself doesn't appear in it.

Why? On the contrary, there should not be a frame with Send To, it has already been executed, forcing the keyboard to enter a character. The stack, as I understand it, then unwound to the winapi loop, in which the input event was extracted in the following iterations and the hook was launched. Everything is logical in the picture.
Initially, this problem occurred on the build for gcc. And now I have reproduced for msvc. And I am sure that the problem will be reproduced by anyone (why was the repro needed tag removed?)

**Comment by vadz** [comment]
> Why? On the contrary, there should not be a frame with Send To, it has already been executed, forcing the keyboard to enter a character. The stack, as I understand it, then unwound to the winapi loop

This seems to contradict what you wrote before: if by the time you get to the `return ret` line the event has been already handled, it didn't return to the main loop. Anyhow, this is easy to check, just put a breakpoint on `Dispatch()` after you hit `sendto` line.

> in which the input event was extracted in the following iterations and the hook was launched. Everything is logical in the picture. Initially, this problem occurred on the build for gcc. And now I have reproduced for msvc. And I am sure that the problem will be reproduced by anyone

I certainly can't reproduce it here.

> (why was the repro needed tag removed?)

It's removed automatically whenever there is a new comment.

**Comment by GeorgyStolbovoy** [comment]
@vadz , 😁😁😁 Pay attention to the unexpected symbol
![image](https://github.com/wxWidgets/wxWidgets/assets/71210013/c0db9724-94e3-4613-8e8b-0356d4e454be)

I guess you didn't understand: on my message with pictures, a screenshot of the stack and a screenshot with a breakpoint are different moments. In the first, the program stopped on my switch when involuntary input was being processed, and in the second, I wanted to demonstrate when unexpected keyboard input appears!

**Comment by GeorgyStolbovoy** [comment]
> Do you mean that if you manually step out from the function calling `sendto`, then you don't hit `Dispatch()` until you get back to the event loop?

I press the button - a true input event is generated. The program enters the hook, calls SendTo in it. This function internally calls this macro with sendto winapi - and then something bad happens, fake clicks begin to be generated (unexpected characters on the cursor are a vivid confirmation). Meanwhile, the program goes back to the main loop for the following events (in Dispatch()) - and they are right there. The program goes to the hook again, and so on, until you remove the focus or stop the program.

I think someone should definitely reproduce it. I will try on another computer with a different wx build, if suddenly there is no such problem there - of course I will write about it

**Comment by BrianNixon** [comment]
_@GeorgyStolbovoy:_ What does the server program do when it receives a UDP datagram from the wx app? (Is it, or something else you have running, synthesising keypress events?)

**Comment by GeorgyStolbovoy** [comment]
God, this is a wonderful question, thank you so much!!! 🤩🤩🤩 I was debugging interaction with a program on localhost, which should work remotely, do "clicks" and so on...🤡 That's where this magic came from... I'm really, really sorry for wasting your time 🤝
