### ISSUE TITLE
Documentation for wxSearchCtrl is incorrect and misleading (can lead to runtime problems)

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23686]
### Description
There are at least two things seriously wrong with the wxSearchCtrl documentation.

1. Unlike the documentation states the generic wxSearchCtrl implementation is **NOT** derived from wxTextCtrl. AFAICT only the wxMAC implementation currently is.

2.  Not only is the generic implementation **not** derived from wxTextCtrl, it is not even derived from wxTextEntry as the inheritance documentation seems to suggest is true for all implementations. In actuality the generic implementation is derived from wxTextEntryBase. Casting wxSearchCtrl to wxTextEntry in wxMSW (uses generic implementation) therefor gives unpredictable runtime problems.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxMSW, wxGTK
- OS  and its version: Windows 10/OpenSuSE Leap 15.4

**Comment by mcorino** [comment]
I'm willing to create a PR here but am unsure about the correct fix.
I could just update the documentation to make it reflect what I reported above (and partly it definitely should) but on the other hand I feel that the generic implementation of wxSearchCtrl is incorrect. I my opinion the generic implementation should be derived from wxTextEntry and not wxTextEntryBase so that the implementations for all platforms are in sync again and matching that part of the documentation.

**Comment by vadz** [comment]
Yes, it would be best if the generic implementation derived from `wxTextEntry` and not `wxTextEntryBase`. AFAICS there is no reason why it wouldn't work, but I didn't have time to actually try/test it. Please try changing this and, if you don't find any problems, make a PR with this change (and if you do find problems, let's discuss them here or on wx-dev).

TIA!
