### ISSUE TITLE
Errors compiling some samples against installed wxWidgets on Linux

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/wxWidgets#23700]
There appear to be some issues compiling some of the samples against an installed wxWidgets version on Linux (ie, build + install wx 3.2.2 and then use the makefile.unx to compile each sample.)

The console-based samples (archive, console, ipc, sockets) are failing to link with errors like this:
```
`wx-config --cxx` -o console console_console.o     `wx-config --unicode=yes --static=no --toolkit=gtk3 --version=3.2 --libs net,base`
/usr/bin/ld: console_console.o: warning: relocation against `_ZTV17wxMDIClientWindow' in read-only section `.text._ZN17wxMDIClientWindowC2Ev[_ZN17wxMDIClientWindowC5Ev]'
/usr/bin/ld: console_console.o: in function `wxWindowBase::GetBestVirtualSize() const':
console.cpp:(.text._ZNK12wxWindowBase18GetBestVirtualSizeEv[_ZNK12wxWindowBase18GetBestVirtualSizeEv]+0x25): undefined reference to `wxWindowBase::GetBestSize() const'
/usr/bin/ld: console_console.o: in function `wxWindowBase::CanBeFocused() const':
console.cpp:(.text._ZNK12wxWindowBase12CanBeFocusedEv[_ZNK12wxWindowBase12CanBeFocusedEv]+0x31): undefined reference to `wxWindowBase::IsEnabled() const'
/usr/bin/ld: console_console.o: in function `wxWindowBase::HasCapture() const':
console.cpp:(.text._ZNK12wxWindowBase10HasCaptureEv[_ZNK12wxWindowBase10HasCaptureEv]+0xd): undefined reference to `wxWindowBase::GetCapture()'
/usr/bin/ld: console_console.o: in function `wxWindowBase::GetDefaultAttributes() const':
console.cpp:(.text._ZNK12wxWindowBase20GetDefaultAttributesEv[_ZNK12wxWindowBase20GetDefaultAttributesEv]+0x28): undefined reference to `wxWindowBase::GetClassDefaultAttributes(wxWindowVariant)'
/usr/bin/ld: console_console.o: in function `wxWindowBase::DoGetBestClientSize() const':
console.cpp:(.text._ZNK12wxWindowBase19DoGetBestClientSizeEv[_ZNK12wxWindowBase19DoGetBestClientSizeEv]+0xb): undefined reference to `wxDefaultSize'
<snipped>
```

Adding a `-DwxUSE_GUI=0` to the compile phase seems to resolve the issue.

The OpenGL samples fail with a linking error:
```
`wx-config --cxx` -c -o cube_cube.o -I. `wx-config --cxxflags --unicode=yes --static=no --toolkit=gtk3 --version=3.2`   -MTcube_cube.o -MF`echo cube_cube.o | sed -e 's,\.o$,.d,'` -MD -MP cube.cpp
`wx-config --cxx` -o cube cube_cube.o     `wx-config --unicode=yes --static=no --toolkit=gtk3 --version=3.2 --libs gl,core,base`
/usr/bin/ld: cube_cube.o: undefined reference to symbol 'glEnable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:91: cube] Error 1
```

Adding an `-lGL` to the link phase seems to resolve the issue.

Finally, the widgets sample seems to need the GTK header include path:
```
`wx-config --cxx` -c -o widgets_native.o -I. `wx-config --cxxflags --unicode=yes --static=no --toolkit=gtk3 --version=3.2`   -MTwidgets_native.o -MF`echo widgets_native.o | sed -e 's,\.o$,.d,'` -MD -MP native.cpp
native.cpp:146:10: fatal error: gtk/gtk.h: No such file or directory
  146 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:182: widgets_native.o] Error 1
```

### Platform and version information

- wxWidgets version  you are building: 3.2.2
- wxWidgets port  you are building: wxGTK
- OS  and its version: Debian Unstable
- Compiler  being used: gcc 12.3.0

**Comment by vadz** [comment]
I think I can fix the first two relatively easily, see the linked PR, but I don't know what to do about the last one, as not only I don't know how to use `pkg-config --cflags` from makefile, but I also don't know which GTK version to use it for or even whether to use it at all, as the usual `TOOLKIT` variables can't be used in out of tree makefiles which don't have access to them.

I think it might be possible to use a makefile fragment for this somehow, but not sure about it...

**Comment by swt2c** [comment]
On the widgets sample issue, perhaps just use the result of `wx-config --query-toolkit` and if it's gtk2 or gtk3 add the results of `$(shell pkg-config --cflags gtk+-3.0)` to CFLAGS and `$(shell pkg-config --libs gtk+-3.0)` to LDFLAGS (or the appropriate gtk2 pkg names if gtk2)?  I'm no Makefile expert so easier said than done.  :-)

**Comment by vadz** [comment]
I've tried to do this now, please let me know if it works for you.

**Comment by swt2c** [comment]
Thanks, but during my testing earlier, it seems that `$(shell pkg-config --libs gtk+-xyz)` needs to be added to LDFLAGS as well.

**Comment by vadz** [comment]
Sorry, forgot about this. (Force) pushed the update which should fix this.

**Comment by swt2c** [comment]
Sorry, one more tweak needed: the penguin OpenGL sample also needs `-lGLU`.

Also, do you think it is worth add a CI check for this?  It looks like the minimal sample is already checked at the very end of `ci.yml` but it shouldn't be too much more effort to check them all.  Probably just run something like:
```
make -C samples clean
for f in `find samples -name makefile.unx`; do
	mv $f `dirname $f`/Makefile
done
make -C samples
```

**Comment by vadz** [comment]
> Sorry, one more tweak needed: the penguin OpenGL sample also needs `-lGLU`.

Added, but see #23721.

> Also, do you think it is worth add a CI check for this?

I've opened another issue for this as I don't have time to do/test it right now, sorry.
