### ISSUE TITLE
bug: wxDataViewModel::GetAttr will change the color for the whole column, not child nodes only

### ISSUE THREAD

**Issue by asmwarrior** [wxWidgets/wxWidgets#23708]
Hi, in the wxDataViewCtrl sample code, especially in the first page, the "MyMusicTreeModel" model, I would like to change the color of the "child" nodes, not the "Container" nodes. I have add such code:

In the header file, I add this:

~~~~
virtual bool GetAttr( const wxDataViewItem&  item, unsigned int col, wxDataViewItemAttr& attr) const wxOVERRIDE;
~~~~

In the cpp file, I add this:
~~~~
bool MyMusicTreeModel::GetAttr( const wxDataViewItem&  item, unsigned int col, wxDataViewItemAttr& attr) const
{
    if (IsContainer(item))
        return false;

    if (col == 1)
    {
        attr.SetColour(*wxYELLOW);
        attr.SetBackgroundColour(*wxLIGHT_GREY);

        return true;
    }
    else
    {
        return false;
    }
}
~~~~

If you look at the code, I have a condition check that for a "container" like node, I just return "false".

From the document ([wxDataViewModel::GetAttr](https://docs.wxwidgets.org/stable/classwx_data_view_model.html#a28b85b9aca3a1ea803940817d86b0b73))return `false` means it just dose NOT change the color attributes of the input `wxDataViewItemAttr`.

But now, here is the result(see screen shot below)

![image](https://github.com/wxWidgets/wxWidgets/assets/561818/bd248eee-cece-4332-8880-2dcb20b732a5)

You see that in the screen shot, the column "artist" pointed by the two arrows are expected to be white background, not the gray background.

My guess is that the wxDataViewItemAttr is reused when rendering. So, once the child node get gray color rendered, the parent node(the container node) also get rendered by the same color.

I can even change the code like below:

~~~~
bool MyMusicTreeModel::GetAttr( const wxDataViewItem&  item, unsigned int col, wxDataViewItemAttr& attr) const
{
    if (col == 1)
    {
        if (IsContainer(item))
        {
            attr.SetColour(*wxYELLOW);
            attr.SetBackgroundColour(*wxWHITE);
            return true;
        }
        else
        {
            attr.SetColour(*wxYELLOW);
            attr.SetBackgroundColour(*wxLIGHT_GREY);
            return true;
        }
    }
    else
    {
        return false;
    }
}
~~~~

Which means either the container node or child nodes will have different colors, but the result is still the same, the whole column will using the same background gray color.

Any ideas?

Thanks.

**Comment by asmwarrior** [comment]
My guess is that, in datavcmn.cpp, there are some code:

~~~~
bool
wxDataViewRendererBase::PrepareForItem(const wxDataViewModel *model,
                                       const wxDataViewItem& item,
                                       unsigned column)
{
    // This method is called by the native control, so we shouldn't allow
    // exceptions to escape from it.
    wxTRY
    {

    // Now check if we have a value and remember it if we do.
    wxVariant value = CheckedGetValue(model, item, column);

    if ( !value.IsNull() )
    {
        if ( m_valueAdjuster )
        {
            if ( IsHighlighted() )
                value = m_valueAdjuster->MakeHighlighted(value);
        }

        SetValue(value);

        // Also set up the attributes for this item if it's not empty.
        wxDataViewItemAttr attr;
        model->GetAttr(item, column, attr);
        SetAttr(attr);
    }

    // Finally determine the enabled/disabled state and apply it, even to the
    // empty cells.
    SetEnabled(model->IsEnabled(item, column));

    return !value.IsNull();
    }
    wxCATCH_ALL
    (
        // There is not much we can do about it here, just log it and don't
        // show anything in this cell.
        wxLogDebug("Retrieving the value from the model threw an exception");
        return false;
    )
}
~~~~

It looks like the condition check `if ( !value.IsNull() )` is only be called for none empty cell? So that the wxDataViewItemAttr is not used?

**Comment by asmwarrior** [comment]
I use a debug version of wx to see how the cell get rendered.

I see this code:

~~~~
void wxDataViewCustomRendererBase::RenderBackground(wxDC* dc, const wxRect& rect)
{
    if ( !m_attr.HasBackgroundColour() )
        return;

    const wxColour& colour = m_attr.GetBackgroundColour();
    wxDCPenChanger changePen(*dc, colour);
    wxDCBrushChanger changeBrush(*dc, colour);

    dc->DrawRectangle(rect);
}
~~~~
So if the m_attr has no background color information, it just returned. Otherwise, it will use m_attr's background color.

The question is:

If in a column, we have different cell background color.

Another issue is that I see in `void wxDataViewMainWindow::OnPaint( wxPaintEvent &WXUNUSED(event) )`

~~~~
            if (hasValue)
                hasValue = cell->PrepareForItem(model, dataitem, col->GetModelColumn());
~~~~

This means the attr is set when the cell has "value"?

**Comment by vadz** [comment]
I guess we should indeed apply the attribute even if the cell is empty because its background colour still applies (although its foreground colour and font do not).

Have you been able to test your code with wxGTK? Things might be different (and more difficult to change) there.

**Comment by asmwarrior** [comment]
> I guess we should indeed apply the attribute even if the cell is empty because its background colour still applies (although its foreground colour and font do not).
> 

Yes, I agree.


> Have you been able to test your code with wxGTK? Things might be different (and more difficult to change) there.

No, Sorry, I only have Windows OS at hand.
