### ISSUE TITLE
`Stop` function in wxWebView with Edge background does not stop scripts from running

### ISSUE THREAD

**Issue by Rezakarimi66** [wxWidgets/wxWidgets#23709]
When you run a script asynchronously or synchronously in a page and then immediately call Stop for that page, still the script runs which does not make sense. 

Reproducung this bug is so easy. Follow the steps below:

1- Create a webview ctrl with edge backend and use `SetPage` function to set a sample content for your page and add a handler for `wxEVT_WEBVIEW_NAVIGATED` event.
2- Run an async/sync script like this:  
`myWebView->RunScriptAsync('window.open( "blah blah" );')`
3- immediately call Stop function `myWebView->Stop()`
4- You could see that the handler gets called! ( set a breakpoint there or print something )

### Platform and version information

- wxWidgets version 3.2.2.1
- wxWidgets port wxMSW
- OS Windows 10

**Comment by Rezakarimi66** [comment]
> I don't know much about `wxWebView` but you shouldn't expect to be able to stop an async operation synchronously, this just can't work (e.g. because it might have already terminated by the time `Stop()` is called). If you cancel it by calling `Stop()` you should also set some flag telling your handler that it was cancelled, so that it ignores the result if it still gets it.

You are right and I fixed this problem by a flag but I think it does not still make sense to run the async script on a page which its content is not correct and updated. Suppose a situation that you set a new page after stopping. Then the async function runs for that new page which is totally wrong. There should be a way to stop those script from running

**Comment by vadz** [comment]
Consider delaying launching it until the page is updated?

Anyhow, I don't know if it's worth keeping this one open, I don't see what could be done here.

**Comment by TcT2k** [comment]
The underlying APIs don't allow explicit canceling of running scripts.
However I would assume that loading a different URL (or refreshing) would stop all running scripts on a page.

**Comment by Rezakarimi66** [comment]
> The underlying APIs don't allow explicit canceling of running scripts. However I would assume that loading a different URL (or refreshing) would stop all running scripts on a page.

If so, it's not useful to keep this issue open.
