### ISSUE TITLE
Refresh issue with `wxTreeCtrl::DeleteChildren()` in master

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#23719]
### Description

While testing the tree sample of the master branch, I noticed a refresh issue with `wxTreeCtrl::DeleteChildren()`.

1. Start the tree sample.
2. Expand 'root' and 'Folder child 5' items.
3. Select the 'Folder child 5' item.
4. In 'Tree' menu, click on 'Delete children'.
   See the issue: The last child item is still displayed.

In 3.2 branch this works fine.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
I don't know what could have broken this, so if you're able to run git-bisect to find it out, it would be very welcome!

**Comment by taler21** [comment]
Bisection shows that this issue was introduced with commit cd15602378a83f1c05deb930c7a4243a0ace289e (Enable double buffering for all generic windows in wxMSW, 2022-10-06).

**Comment by vadz** [comment]
Thanks, I should have known tree control would also have issues with double buffering if the list one did... Just refreshing the control will probably be enough to fix this, but I need to test.

**Comment by vadz** [comment]
I've finally checked that a simple `Refresh()` does fix this, so I'm pushing the fix for this.

Note that calling `DeleteAllItems()` resulted in the same problem too.
