### ISSUE TITLE
assertion failed on linux when deleting selected item in `wxListView` (assert "idx < m_size")

### ISSUE THREAD

**Issue by docentYT** [wxWidgets/wxWidgets#23729]
### Description
When on Linux (wxGTK) one removes an item from the `wxListView` that is selected then after the user selects (and sometimes selects and deselects) the remaining items the program crashes.

### Assert info and backtrace
```
ASSERT INFO:
../include/wx/vector.h(492): assert "idx < m_size" failed in at().

BACKTRACE:
[1] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[2] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[3] wxEvtHandler::TryHereOnly(wxEvent&)
[4] wxEvtHandler::ProcessEventLocally(wxEvent&)
[5] wxEvtHandler::ProcessEvent(wxEvent&)
[6] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[7] g_closure_invoke
[8] g_signal_emit_valist
[9] g_signal_emit
[10] gtk_main_do_event
[11] g_main_context_dispatch
[12] g_main_loop_run
[13] gtk_main
[14] wxGUIEventLoop::DoRun()
[15] wxEventLoopBase::Run()
[16] wxAppConsoleBase::MainLoop()
[17] wxEntry(int&, wchar_t**)
[18] __libc_start_main
```
### Minimal sample
```cpp
#include <wx/wx.h>
#include <wx/listctrl.h>

class MyApp : public wxApp {
public:
    wxListView* listView;
    virtual bool OnInit() {
        wxFrame* frame = new wxFrame(NULL, wxID_ANY, "Hello world");
        frame->Show(true);

        listView = new wxListView(frame, wxID_ANY);
        listView->Freeze();
        listView->InsertColumn(0, "Column 0");
        listView->InsertItem(0, "Item 0");
        listView->InsertItem(1, "Item 1");
        listView->Select(1, true);
        listView->DeleteItem(1);
        listView->Thaw();

        return true;
    }
};

wxIMPLEMENT_APP(MyApp);
```

Once the program has started, simply select and deselect the only item in the list.

### Platform and version information

- wxWidgets version: 3.2.2.1
- wxWidgets port: wxGTK
- OS: Ubuntu 22.04.2 LTS

+ GTK version: 3.24.33-1ubuntu2
+ Which GDK  backend is used: I don't know.

**Comment by docentYT** [comment]
On windows, this problem does not occur.

**Comment by vadz** [comment]
Strange, I can't reproduce this with neither master nor 3.2.2. And the stack doesn't make much sense to me as there are no subscripts being used in `ProcessEventIfMatchesId()`.

Could you please compile with debug info to get more information?

**Comment by vadz** [comment]
OK, thanks, I see it now and fixed it in master in the commit above and will cherry-pick it to 3.2 too.
