### ISSUE TITLE
Remove GLU dependency

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#23721]
> Sorry one more tweak needed: the penguin OpenGL sample also needs `-lGLU`.

_Originally posted by @swt2c in https://github.com/wxWidgets/wxWidgets/issues/23700#issuecomment-1631086927_

**Comment by vadz** [comment]
I actually think it might be better to drop GLU dependency completely, we don't seem to use it for much right now, in fact the only function from it I can see is `gluPerspective()` used in this sample and it seems like it could be replaced with something like this instead (untested):

```cpp
double fH = tan( M_PI / 8 );
double fW = fH * ClientSize.x / ClientSize.y;
glFrustum(-fW, fW, -fH, fH, 1.0, 100.0);
```

**Comment by Manolo-ES** [comment]
I fully agree with removing GLU, and it's only use at penguin example.
I agree too with the glFustrum replace.

A side note: Some tiff files use GLUT (a small windows api), not GLU. I haven't been able to find the reason.
But I want to warn about a brute "gluXXXX" deletion, as it will affect tiff files.

**Comment by vadz** [comment]
> I fully agree with removing GLU, and it's only use at penguin example. I agree too with the glFustrum replace.

Any PRs doing this would be welcome, I created an issue partially in hope of encouraging people to contribute them!

> A side note: Some tiff files use GLUT (a small windows api), not GLU. I haven't been able to find the reason. But I want to warn about a brute "gluXXXX" deletion, as it will affect tiff files.

Neither GLU nor GLUT are used by libtiff itself, so I don't think there is any danger here, but please correct me if I'm wrong.

**Comment by swt2c** [comment]
> I can't find Bakefile 0.2.13 in https://github.com/vslavik/bakefile

There isn't a release it seems, but you can get from the tags page:
https://github.com/vslavik/bakefile/tags

**Comment by swt2c** [comment]
> checking for LIBSECRET... configure: WARNING: libsecret not found, wxSecretStore won't be available
> checking for GSPELL... configure: WARNING: gspell-1 not found, spell checking in wxTextCtrl won't be available
    wxWebRequest, GStreamer are disabled

BTW, those warnings are normal if you don't have the relevant library development packages installed.

**Comment by Manolo-ES** [comment]
OK. THX.
Should I "make & install" 0.2.13 over 0.2.12?
If not, should I uninstall bakefile by a tool such as CheckInstall?
Can I completely remove bakefile by manually deleting everything related to bakefile at **usr/local** folder?

**Comment by swt2c** [comment]
If you've already installed 0.2.12 previously, yeah it's probably fine to just install over it.

I've never looked into uninstalling it.  I use an RPM package.  If you use Fedora by chance, feel free to use my Copr:
https://copr.fedorainfracloud.org/coprs/swt2c/bakefile/

**Comment by vadz** [comment]
FWIW you can also use 0.12 if this is more convenient, just don't forget to regenerate configure too and leave a note in your PR saying that the makefiles need to be regenerated and I'll do it -- I realize that dealing with bakefile is a pain, sorry...

**Comment by Manolo-ES** [comment]
Sorry, I give up. bakefile 0.2.13 not only lacks "configure" but other files needed to build it.
And I can not cope with git, I use it in very very few cases, so I forget most of it.

I attach here (see the zip file) the .patch for the files I think that cover this "glu removal" thing. I hate to post untested code, but this time another one make the PR and test it all.

[GluRemove.zip](https://github.com/wxWidgets/wxWidgets/files/12188986/GluRemove.zip)
