### ISSUE TITLE
3.2.2.1 build failure on Windows

### ISSUE THREAD

**Issue by FillipMatthew** [wxWidgets/wxWidgets#23738]
### Description
Migrating from 3.2.1 to 3.2.2.1 I found the following no longer works. I did not test in between versions.

nmake /f makefile.vc BUILD=release SHARED=1 UNICODE=0 USE_GDIPLUS=1 TARGET_CPU=X64 VENDOR=SST CXXFLAGS="/std:c++17 /utf-8"

main.cpp
..\..\src\msw\main.cpp(291): error C2039: 'Cleanup': is not a member of '`anonymous-namespace'::wxMSWCommandLineArguments'
..\..\src\msw\main.cpp(207): note: see declaration of '`anonymous-namespace'::wxMSWCommandLineArguments'
..\..\src\msw\main.cpp(301): error C2440: 'return': cannot convert from 'wxChar **' to 'wchar_t **'
..\..\src\msw\main.cpp(301): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
..\..\src\msw\main.cpp(359): error C2665: 'wxEntry': none of the 2 overloads could convert all the argument types
..\..\src\msw\main.cpp(169): note: could be 'int wxEntry(int &,wxChar **)'
..\..\src\msw\main.cpp(359): note: while trying to match the argument list '(int, wchar_t **)'

### Platform and version information

- wxWidgets version: 3.2.2.1
- wxWidgets port: wxMSW
- OS version: Windows 10
- Compiler: MSVC 2019

[wxWidgets-release-build-logs.txt](https://github.com/wxWidgets/wxWidgets/files/12180761/wxWidgets-release-build-logs.txt)

**Comment by PBfordev** [comment]
This is a known regression in 3.2.2, already fixed in the 3.2 branch (which will become 3.2.3): https://github.com/wxWidgets/wxWidgets/commit/89dc204bb608c9177ac60ee8e657c9efdeb470ab

So if you really want to use the non-Unicode build, you will either have to downgrade, fix for yourself (see the commit above), or wait for 3.2.3 (2023-9-9?).

**Comment by vadz** [comment]
For the record, the commit fixing this is cc46425f9f3b371e5b4909d1ec5c48a375302dc4 and you should be able to cherry-pick this easily.
