### ISSUE TITLE
wxStaticBox glitch when DPI changes

### ISSUE THREAD

**Issue by charvey2718** [wxWidgets/wxWidgets#23740]
### Description

When using a control (e.g. wxStaticBox, wxCheckBox) as the label of a wxStaticBox, it glitches when the DPI changes.

This is an example of a wxStaticBox with wxCheckBox label created on a screen with a DPI scale factor of 1:
![1](https://github.com/wxWidgets/wxWidgets/assets/59702518/de5d5fd8-93ff-4a04-868b-e64fab4901ca)

Moving the same window to a second screen with a DPI scale factor of 1.25 causes it to look like this.
![2](https://github.com/wxWidgets/wxWidgets/assets/59702518/d26e7082-ea47-416a-aeec-b7c841cd4925)

The right of the checkbox label is clipped.
In some scenarios, the text breaks on to a newline where it cannot be seen, and the spacing is broken.

Here is an example of a wxStaticBox with wxStaticText label created on a screen with a DPI scale factor of 1.25. It looks fine.
![4](https://github.com/wxWidgets/wxWidgets/assets/59702518/4d3a4753-2b1f-4c12-94c7-ba34381fcf99)

Contrast this with the same window created on a screen with a DPI scale factor of 1.0 and then moved to a screen with a DPI scale factor of 1.25:
![3](https://github.com/wxWidgets/wxWidgets/assets/59702518/9fc64267-6fc9-44d5-b11f-fe257713071d)
One of the words has moved to the next line and been cut off.
The box around the static box has a large gap.
The spacing under the wxStaticText label is not the same.

I'm using
```
#define wxUSE_DPI_AWARE_MANIFEST 2
```

### Minimum working example
```
#include <wx/wx.h>

class MyFrame:public wxFrame {
public:
    MyFrame(wxWindow* parent);
};

class MyApp:public wxApp {
public:
    bool OnInit() {
        wxFrame* frame=new MyFrame(NULL);
        SetTopWindow(frame);
        frame->Show();
        return true;                    
    }
};

DECLARE_APP(MyApp);
IMPLEMENT_APP(MyApp);

MyFrame::MyFrame(wxWindow* parent):wxFrame(parent,wxID_ANY,_("StatBoxMWE"),wxDefaultPosition,wxDefaultSize,wxDEFAULT_FRAME_STYLE) {
	SetClientSize(wxSize(100,100));
	wxBoxSizer* mainSizer=new wxBoxSizer(wxVERTICAL);
	
	wxCheckBox* cb=new wxCheckBox(this,wxID_ANY,_("checkbox"),wxDefaultPosition,wxDefaultSize,wxALIGN_LEFT);
	wxStaticBox* sb=new wxStaticBox(this,wxID_STATIC,cb);
	wxStaticBoxSizer *sbs=new wxStaticBoxSizer(sb,wxVERTICAL);
	
	wxStaticText* text=new wxStaticText(sb,wxID_ANY,_("hello"),wxDefaultPosition,wxDefaultSize,wxALIGN_LEFT);
	sbs->Add(text,0,wxALL,5);
	
	mainSizer->Add(sbs,1,wxEXPAND|wxALL,10);
	SetSizer(mainSizer);
}
```

### Platform and version information

- wxWidgets version : wxWidgets-3.2.2.1
- wxWidgets port : wxMSW
- OS: Windows 10 Enterprise

**Comment by vadz** [comment]
Thanks for reporting this, I don't have time to debug/fix this now, but it could be due to just a missing call to `PositionLabelWindow()` after DPI change, i.e. maybe just inserting this (directly in `wxStaticBox::MSWWindowProc()` to allow backporting it to 3.2 or in overridden `MSWBeforeDPIChangedEvent()` which would be cleaner on master) would be enough to fix it.

**Comment by charvey2718** [comment]
Hi Vadz
No problem. It's just a minor cosmetic issue under specific circumstances.

I had a look at the solutions you suggested though.

- As far as I can see, there is no virtual `MSWBeforeDPIChangedEvent()` to override for wxStaticBox.

Adding
```
virtual void MSWBeforeDPIChangedEvent(const wxDPIChangedEvent& event) override;
```
to `/include/wx/msw/statbox.h` gives
```
In file included from ../include/wx/statbox.h:70,
                 from ../src/msw/statbox.cpp:25:
../include/wx/msw/statbox.h:79:15: error: 'virtual void wxStaticBox::MSWUpdateOnDPIChange(const wxDP
IChangedEvent&)' marked 'override', but does not override
  virtual void MSWUpdateOnDPIChange(const wxDPIChangedEvent& event) override;
```

- I also tried adding `PositionLabelWindow()` to `wxStaticBox::MSWWindowProc()` but this the application to immediately crash and exit.

I'm probably doing something wrong. I'm not familiar with the inner working of wxwidgets. But I would have been amazed if you (or anyone) had seen straight to the problem without detailed troubleshooting!

**Comment by vadz** [comment]
> I had a look at the solutions you suggested though.
> 
>     * As far as I can see, there is no virtual `MSWBeforeDPIChangedEvent()` to override for wxStaticBox.

Sorry for not being clear, this function only exists in master, not in the 3.2 branch, so this solution can't be applied (or even tried) there.

>     * I also tried adding `PositionLabelWindow()` to `wxStaticBox::MSWWindowProc()` but this the application to immediately crash and exit.

Again, sorry for being too brief, what I meant was to add it only when/after handling `WM_DPICHANGED`, you can't call it unconditionally. I.e. doing something like this (the diff is against master, but should apply to 3.2 too):

```diff
diff --git a/src/msw/statbox.cpp b/src/msw/statbox.cpp
index 161d438f39..d4eb45cf3b 100644
--- a/src/msw/statbox.cpp
+++ b/src/msw/statbox.cpp
@@ -363,6 +363,13 @@ WXLRESULT wxStaticBox::MSWWindowProc(WXUINT nMsg, WXWPARAM wParam, WXLPARAM lPar
             Refresh();
     }
 
+    if ( nMsg == case WM_DPICHANGED )
+    {
+        WXLRESULT ret = wxControl::MSWWindowProc(nMsg, wParam, lParam);
+        PositionLabelWindow();
+        return ret;
+    }
+
     return wxControl::MSWWindowProc(nMsg, wParam, lParam);
 }

```

**Comment by charvey2718** [comment]
Ahh I see. Your first answer makes more sense to me now.

Unfortunately, the additions you suggested don't change the issue, although the application no longer crashes.

This can wait. As I said, it's only minor cosmetics. You said you don't have time now, and I want to respect that.

**Comment by MaartenBent** [comment]
> I also tried Binding wxStaticBox to an wxEVT_DPI_CHANGED event, which called PositionLabelWindow(). This had the same effect as adding it to wxStaticBox::MSWWindowProc(), i.e. the application immediately crashes and exits.

You must have made an error. This fixes the label for me in the provided example.
I don't think we can use the lambda expression in wx3.2, there the function has to be defined separately. But I tried to keep the diff as small as possible.

```diff
diff --git "a/src/msw/statbox.cpp" "b/src/msw/statbox.cpp"
index 161d438f39..580d277db0 100644
--- "a/src/msw/statbox.cpp"
+++ "b/src/msw/statbox.cpp"
@@ -93,6 +93,8 @@ bool wxStaticBox::Create(wxWindow *parent,
     if ( ShouldUseCustomPaint() )
         UseCustomPaint();
 
+    Bind(wxEVT_DPI_CHANGED, [=](wxDPIChangedEvent&) { PositionLabelWindow(); });
+
     return true;
 }
```

**Comment by charvey2718** [comment]
Interesting. It works for me too in the example I provided. I was checking my full application instead, which it still crashes out on DPI change. There must be something else going on. I will adapt the MWE until the issue resurfaces.

**Comment by charvey2718** [comment]
I'm now completely confused. I adjusted the MWE and thought I'd found that the fix causes a crash in the MWE when nesting two staticboxes, one with text in the staticbox label and one with a control. I was about to post it here, and then thought I'd check what would happen if I unnested them. At this point, having not touched statbox.cpp again, everything started working, including my own application. I have no idea what silly error I've been making it. But I take this to mean that (1) the fix does seem to be working, and (2) I should get some sleep.

I was relying on `make` to only rebuild what was necessary from my earlier build of 3.2.2.1. I then did a completely fresh compile/link of the MWE and my application each time. Maybe something was going wrong here.

To be clear, in 3.2.2.1, I just added 
```
Bind(wxEVT_DPI_CHANGED, [=](wxDPIChangedEvent&) { PositionLabelWindow(); });
```
to the `Create(wxWindow* parent, wxWindowID id, wxWindow* labelWin, ...)` function (i.e. not the one that takes a `wxString`).

If I problem reoccurs, I will let you know. For now it seems OK.

Many thanks to everyone who helped!

**Comment by vadz** [comment]
So does [my patch above](https://github.com/wxWidgets/wxWidgets/issues/23740#issuecomment-1654470227) work or not finally? If it does, I'd like to commit it. Otherwise I'll have to debug this myself later...

**Comment by charvey2718** [comment]
@vadz Your patch had no effect for me on 3.2. I have the same issue in the pictures in my original post.
```
if ( nMsg == WM_DPICHANGED )
{
    WXLRESULT ret = wxControl::MSWWindowProc(nMsg, wParam, lParam);
    PositionLabelWindow();
    return ret;
}
```
(note that I removed `case` from the `if` condition.

What worked for me (on 3.2) was adding
`Bind(wxEVT_DPI_CHANGED, [=](wxDPIChangedEvent&) { PositionLabelWindow(); });`
to the
`Create(wxWindow* parent, wxWindowID id, wxWindow* labelWin, ...)`
function.

**Comment by vadz** [comment]
Thanks for confirming this. I don't understand how is calling `PositionLabelWindow()` after letting the base class generate `wxDPIChangedEvent` different from doing it in this event handler, so I guess I will have to debug it to understand...

**Comment by MaartenBent** [comment]
I think `wxStaticBox` doesn't get its own `WM_DPICHANGED`, only the top-level window.
