### ISSUE TITLE
DOC: error into how-to-write-unit-tests.md

### ISSUE THREAD

**Issue by carlo-bramini** [wxWidgets/wxWidgets#23745]
### Description

I looked into here:
https://github.com/wxWidgets/wxWidgets/blob/master/docs/contributing/how-to-write-unit-tests.md
for getting the information for building the tests under CMake.
As it is described, I added option `-DwxBUILD_TESTS=ON` to the command line, but I'm getting this error message:

```
CMake Error at build/cmake/functions.cmake:944 (message):
  Invalid value "ON" for option wxBUILD_TESTS.  Valid values are:
  CONSOLE_ONLY ALL OFF
Call Stack (most recent call first):
  build/cmake/options.cmake:15 (wx_option)
  build/cmake/main.cmake:16 (include)
  CMakeLists.txt:103 (include)
```

So, it seems that the documentation file just needs to be updated by changing:

`-DwxBUILD_TESTS=ON` -> `-DwxBUILD_TESTS=ALL`
`-DwxBUILD_TESTS=CONSOLE` -> `-DwxBUILD_TESTS=CONSOLE_ONLY`

Or the CMake script could be fixed for using the switches described into the documentation.
Both solutions would be good.

### Platform and version information

- wxWidgets version  you use: git e8fdb66 
- wxWidgets port  you use: wxGTK
- OS  and its version: Windows

**Comment by PBfordev** [comment]
Thanks, I attempted to fix the issue in #23746.
