### ISSUE TITLE
Use euphemeral NSURLSession?

### ISSUE THREAD

**Issue by Upliner** [wxWidgets/wxWidgets#23743]
With defaultSessionConfiguration NSURLSession uses local caches and cookies and there is very many cases when you don't want it. There is a special [NSURLSessionConfiguration ephemeralSessionConfiguration] that allows to avoid it. And it makes wxWebRequest usage more consistent across different OSes. Can euphemeral NSURLSession be added at least as an option?

**Comment by vadz** [comment]
I don't see why not, but somebody would have to do it. If you volunteer, please post to wx-dev with the proposed new API so that we could all agree on it before you spend time on implementing it.

As usual, it's better to propose an API that could be at least potentially implemented on the other platforms, even if it isn't done immediately (and it's best and if it is implemented for at least one other platforms), so it would be worth checking if Edge/GtkWebView provide anything similar.

TIA!

**Comment by swt2c** [comment]
I think @Upliner is referring to `wxWebRequest` not `wxWebView`, so it would be comparing with `libcurl` and `WinHTTP`.

I agree that it probably makes sense to provide this mode (and perhaps should even be the default?) as I wouldn't expect wxWebRequest to use/save caches and cookies.  libcurl definitely doesn't do that unless you tell it to.

**Comment by vadz** [comment]
Sorry for the mix up, I don't know why did I think about `wxWebView`, please ignore what I wrote and read what @swt2c wrote instead.

**Comment by Upliner** [comment]
I think the easiest way to do it is just use separate backend string. wxWebSessionBackendURLSession currently uses [NSURLSessionConfiguration defaultSessionConfiguration] and wxWebSessionBackendURLSessionEphemeral will use [NSURLSessionConfiguration ephemeralSessionConfiguration]. Is this OK? Or should we use separate parameter in wxWebSession::New for backend-specific configuration?

**Comment by vadz** [comment]
Sorry, I'm not sure to understand the question. How will the public API work, i.e. how would you choose which one to use? And which one would be the default?

**Comment by Upliner** [comment]
Here is small example of public API:
```
class DownloadDialog : public MyDialog {
    wxWebSession sess;
    wxWebRequest req;
    // ... More fields
    DownloadDialog() {
        #if __APPLE__
        sess = wxWebSession::New(wxWebSessionBackendURLSessionEphemeral); // Use ephemeral backend on MacOS. This backend doesn't exist yet.
        #else
        sess = wxWebSession::New(); // Use default backend on other OSes
        #endif
        // No changes here:
        req = sess.CreateRequest(this, "https://example.com/some_big_file"); 
        req.Start();
    }
}
```
Which backend should be default in MacOS is difficult question. On one hand defaultSessionConfiguration is backward-compatible with older versions of wxWidgets, on the other hand ephemeralSessionConfiguration is more consistent with other backends (WinHTTP and CURL).
The problem is that defaultSessionConfiguration stores cached files in some persistent storage which persists even across multiple program runs. And  there is no way to clear this cache and there no way to know whether the request is real request or cached one. It can be avoided if server sends "Cache-control: no-cache" header, but sometimes we can't control the server. So maybe ephemeralSessionConfiguration should even become default one.

**Comment by vadz** [comment]
Sorry, this example doesn't seem very nice, surely we should try to avoid any `#if __APPLE__` checks in the application code.

Especially if we decide that not storing cookies etc should be the default, then it would seem to be natural to use the ephemeral session by default and provide some extra `UseDefaultStorage()` function that could be called on the session to make it use the default session instead -- unless this really needs to be specified when creating it and can't be changed later? In this case we are probably going to need to add some new `wxWebSessionOptions` class and (optionally) pass it to `New()` to configure this, but it would be better if we could avoid it and just add a new function instead (this could also be backported to 3.2 then).
