### ISSUE TITLE
wxGrid memorizes(focus on) old coords when having table changed inside

### ISSUE THREAD

**Issue by CookieLau** [wxWidgets/wxWidgets#23751]
### Description

There is a fixed wxGrid("grid" in the following) and a dynamic wxGridTableBase("table" in the following) inside of it.
The table size would change due to some biz logic, e.g. apply some filter on it.
The bug occurs when 
1. you have **clicked** a cell with large row number
2. the table shrinks 
3. you try to click the cell with smaller row number.
At that time, it tries to select a block using the old coords which you selected before shrink and which is invalid since the row never exist, and lead to the assertion failure.
The assertion fails at [src\generic\grid.cpp:5124](https://github.com/wxWidgets/wxWidgets/blob/a4dec24c6dab69551f5bc1b39c8e32aae9c890d1/src/generic/grid.cpp#L5124).

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxMSW
- OS  and its version: windows 10

### Reproduction
Demo code:
```cpp
#include <wx/wx.h>
#include <wx/scrolwin.h>
#include <wx/grid.h>


class MyTable : public wxGridTableBase
{
public:
    MyTable(int rows) : _rows{ rows }, _cols{ 4 }  {}

    virtual int GetNumberRows() wxOVERRIDE { return _rows; }
    virtual int GetNumberCols() wxOVERRIDE { return _cols; }
    virtual wxString GetValue(int row, int col) wxOVERRIDE
    {
        return wxString::Format("%d", row*col);
    }
    virtual void SetValue(int, int, const wxString&) wxOVERRIDE
    {
        wxFAIL_MSG("shouldn't be called");
    }
    virtual wxString GetColLabelValue(int col) wxOVERRIDE
    {
        // notice that column parameter here always refers to the internal
        // column index, independently of its position on the screen
        static const char* labels[] = { "Name", "Extension", "Size", "Date" };
        return labels[col];
    }
    virtual void SetColLabelValue(int, const wxString&) wxOVERRIDE
    {
        wxFAIL_MSG("shouldn't be called");
    }
private:
    int _rows;
    int _cols;
};

class MyFrame : public wxFrame
{
public:
    MyFrame() : wxFrame(nullptr, wxID_ANY, "Test")
    {
        SetBackgroundColour(*wxBLUE);
        wxBoxSizer* vertical = new wxBoxSizer(wxVERTICAL);
        m_grid = new wxGrid(this, wxID_ANY);
        m_table = new MyTable(20);
        m_grid->SetTable(m_table, true);
        wxButton* halve = new wxButton(this, wxID_ANY, "Halve");
        halve->Bind(wxEVT_BUTTON, [&](wxCommandEvent& event)
            {
                m_table = new MyTable(10);
                m_grid->SetTable(m_table, true);
                m_grid->ForceRefresh();
            });
        vertical->Add(halve, 0, wxCENTER);
        vertical->AddSpacer(20);
        vertical->Add(m_grid, 0, wxEXPAND);
        SetSizer(vertical);
        vertical->SetSizeHints(this);
    }
private:
    wxGrid* m_grid = nullptr;
    MyTable* m_table = nullptr;
};

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        (new MyFrame())->Show();
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```

Steps:
1. select the cell with row larger than 10 to get grid cursor on that
5. click button "halve" to shrink the table size
6. click (or drag) in the cells in the new smaller table
7. Error occurs -> it tried to access the coords in the original big table before thus causing invalid index

**Comment by CookieLau** [comment]
P.S. wxWidgets v3.1.5 has no such problem

**Comment by CookieLau** [comment]
I found the critical problem is caused by GetRowPos in wxGrid::CellToGridWindow added in [this commit](https://github.com/wxWidgets/wxWidgets/commit/3719ab3725c05c16819415680fdd9bc8bab10a27#diff-9cc98f8a208062a88ee5102d3c0252b0d1a6d17c3d78c224e81b5656ccb93850L7950)

Call stack:
![image](https://github.com/wxWidgets/wxWidgets/assets/30521971/ad4f123e-893f-47ca-9b47-141c4248e8c7)

**Comment by vadz** [comment]
In fact looking at the stack trace it seems like we need to just add

```cpp
    m_currentCellCoords = wxGridNoCellCoords;
```

to `wxGrid::SetTable()`. Would this fix the bug?

**Comment by CookieLau** [comment]
@vadz Thanks for your feedback, I believe your logic is truly correct, when the inner table has been changed, the currentCell should also been invalidated, I've committed the latest fix by setting it to NoCellCoords right after invalidateBestSize.

**Comment by vadz** [comment]
Sorry, after thinking more about this, I wonder if we really want to always reset it here: in some circumstances, it could be unwanted, e.g. we probably do _not_ want to lose the current selection if we just extended the table.

So I think that we need to call `UpdateCurrentCellOnRedim()` here instead of just invalidating the current cell. Could you please confirm that this also fixes the bug? If so, I can commit it directly (or you can update the associated PR to do this).

TIA!

**Comment by CookieLau** [comment]
Hi @vadz, sorry for the late reply.
Good news is the `UpdateCurrentCellOnRedim()` can also solve the problem, and in a more elegant way.

https://github.com/wxWidgets/wxWidgets/assets/30521971/72c58575-24f1-4176-9f2b-2066dfd896a4

Here's the recording of the example, when the selected cell is outside of new table, it will be clipped to the boundary and remain valid.

Feel free to commit it directly, glad to help :)
