### ISSUE TITLE
Bug in the events sample

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23767]
### Description
The event sample demonstrates using gesture events by showing a wxFrame-derived `MyGestureFrame`  along with the sample main frame. 

`MyGestureFrame` takes over the log target with
https://github.com/wxWidgets/wxWidgets/blob/3ae3a4e1f519741132c51e5aa8f83d6f05174501/samples/event/gestures.cpp#L26

This is problematic for two reasons:
1. All the log messages (i.e., even those triggered from the main frame menu / buttons) are shown in the `MyGestureFrame` log.
2. When `MyGestureFrame` is destroyed, so is the log target, so any further use of `wxLogxxx()` makes the sample crash.

I am not sure how to best solve it, perhaps the simplest fix would be converting `MyGestureFrame` to a modal dialog and restore the log target when the dialog is closed?

**Comment by vadz** [comment]
The simplest fix is to remember the old log target and restore it when it's destroyed. This is still weird (why should all the logs go to this frame), but anything else would be more complicated.
