### ISSUE TITLE
Crash when pressing [Numpad Enter] to end editing a wxListCtrl item in GTK

### ISSUE THREAD

**Issue by reind33r** [wxWidgets/wxWidgets#23761]
### Description

When editing an item label in wxListCtrl, pressing [Numpad Enter] causes a segmentation fault.

```
(listctrl:25302): GLib-GObject-CRITICAL **: 23:03:43.498: ../glib/gobject/gsignal.c:2678: instance '0x55b0c27bc9e0' has no handler with id '16845107637410547236'
Segmentation fault (core dumped)
```

I once got a warning that an assertion had failed, but after trying to re-run it, I got the segmentation fault before the warning was issued. The assertion is [line 77 in gtk/textentry.cpp](https://github.com/wxWidgets/wxWidgets/blob/d847f3b039f469000e4a0673ae1f88a81e889248/src/gtk/textentry.cpp#L77C1-L77C34).

#### To Reproduce

1. Launch 'listctrl' sample (using wxWidgets GTK port)
3. Click twice on any item of the first column to start editing it
4. Press [Numpad Enter] key
5. The sample program crashes due to segmentation fault

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxGTK
- OS  and its version: Manjaro 23.0.0, Linux 6.0.19-4

+ GTK version:  3.24.38
+ Which GDK  backend is used: X11
+ Current theme: 

### Additional info

I found this bug on FileZilla tracker, that seems to be the same: https://trac.filezilla-project.org/ticket/12762

And this one: https://trac.filezilla-project.org/ticket/12929

The first reporter also runs Manjaro (earlier kernel Linux 5.18.16-1), with earlier wxWidgets version 3.2.0. The second reporter runs Ubuntu 23.04.

Unfortunately my knowledge of wxWidgets internals and GTK is close to non-existant so I cannot find the root cause of the bug myself. If I can help in any way, let me know.

**Comment by swt2c** [comment]
Took a quick look at this and it was super easy to fix:
https://github.com/wxWidgets/wxWidgets/pull/23762
