### ISSUE TITLE
Navigating failed in a popped-up owner drawn combobox 

### ISSUE THREAD

**Issue by Rezakarimi66** [wxWidgets/wxWidgets#23776]
Please take a look at my minimal app below. To reproduce the bug follow these steps:

1- Open the second combobox and pop it up
2- Press Arrow down/up key on your keyboard
3- You see the error! Instead of selecting the next item in the combobox, it gets popped down. 

The behaivour is correct for the first combobox. 
```

/////////////////////////////////////////////////////////////////////////////
// Name:        minimal.cpp
// Purpose:     Minimal wxWidgets sample
// Author:      Julian Smart
// Modified by:
// Created:     04/01/98
// Copyright:   (c) Julian Smart
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////

// ============================================================================
// declarations
// ============================================================================

// ----------------------------------------------------------------------------
// headers
// ----------------------------------------------------------------------------

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"
#include <wx/odcombo.h>

// for all others, include the necessary headers (this file is usually all you
// need because it includes almost all "standard" wxWidgets headers)
#ifndef WX_PRECOMP
    #include "wx/wx.h"
#endif

// ----------------------------------------------------------------------------
// resources
// ----------------------------------------------------------------------------

// the application icon (under Windows it is in resources and even
// though we could still include the XPM here it would be unused)
#ifndef wxHAS_IMAGES_IN_RESOURCES
    #include "../sample.xpm"
#endif

// ----------------------------------------------------------------------------
// private classes
// ----------------------------------------------------------------------------

// Define a new application type, each program should derive a class from wxApp
class MyApp : public wxApp
{
public:
    // override base class virtuals
    // ----------------------------

    // this one is called on application startup and is a good place for the app
    // initialization (doing it here and not in the ctor allows to have an error
    // return: if OnInit() returns false, the application terminates)
    virtual bool OnInit() wxOVERRIDE;
};

// Define a new frame type: this is going to be our main frame
class MyFrame : public wxFrame
{
public:
    // ctor(s)
    MyFrame(const wxString& title);

    // event handlers (these functions should _not_ be virtual)
    void OnQuit(wxCommandEvent& event);
    void OnAbout(wxCommandEvent& event);

private:
    // any class wishing to process wxWidgets events must use this macro
    wxDECLARE_EVENT_TABLE();
};

// ----------------------------------------------------------------------------
// constants
// ----------------------------------------------------------------------------

// IDs for the controls and the menu commands
enum
{
    // menu items
    Minimal_Quit = wxID_EXIT,

    // it is important for the id corresponding to the "About" command to have
    // this standard value as otherwise it won't be handled properly under Mac
    // (where it is special and put into the "Apple" menu)
    Minimal_About = wxID_ABOUT
};

// ----------------------------------------------------------------------------
// event tables and other macros for wxWidgets
// ----------------------------------------------------------------------------

// the event tables connect the wxWidgets events with the functions (event
// handlers) which process them. It can be also done at run-time, but for the
// simple menu events like this the static method is much simpler.
wxBEGIN_EVENT_TABLE(MyFrame, wxFrame)
    EVT_MENU(Minimal_Quit,  MyFrame::OnQuit)
    EVT_MENU(Minimal_About, MyFrame::OnAbout)
wxEND_EVENT_TABLE()

// Create a new application object: this macro will allow wxWidgets to create
// the application object during program execution (it's better than using a
// static object for many reasons) and also implements the accessor function
// wxGetApp() which will return the reference of the right type (i.e. MyApp and
// not wxApp)
wxIMPLEMENT_APP(MyApp);

// ============================================================================
// implementation
// ============================================================================
class mywxComboBox : public wxOwnerDrawnComboBox
{
public:
    mywxComboBox(wxWindow* parent, wxWindowID id, const wxString& value, const wxPoint& pos,
        const wxSize& size, int n = 0, const wxString choices[] = 0, long style = 0)
        : wxOwnerDrawnComboBox(parent, id, value, pos, size, n, choices, style)
    {}

};

mywxComboBox* cb = nullptr;
// ----------------------------------------------------------------------------
// the application class
// ----------------------------------------------------------------------------

// 'Main program' equivalent: the program execution "starts" here
bool MyApp::OnInit()
{
    // call the base class initialization method, currently it only parses a
    // few common command-line options but it could be do more in the future
    if ( !wxApp::OnInit() )
        return false;

    // create the main application window
    MyFrame *frame = new MyFrame("Minimal wxWidgets App");

    auto panel = new wxPanel(frame, -1);
    cb = new mywxComboBox( panel, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize );

    auto page = new wxPanel(panel, -1, wxPoint(0, 50), wxSize( 300, 100 ));
    mywxComboBox* cb2 = new mywxComboBox(page, wxID_ANY, wxT(""), wxPoint(0,0), wxDefaultSize);
    cb->Append("red");
    cb->Append("green");
    cb->Append("blue");

    cb2->Append("red");
    cb2->Append("green");
    cb2->Append("blue");

    // and show it (the frames, unlike simple controls, are not shown when
    // created initially)
    frame->Show(true);

    // success: wxApp::OnRun() will be called which will enter the main message
    // loop and the application will run. If we returned false here, the
    // application would exit immediately.
    return true;
}

// ----------------------------------------------------------------------------
// main frame
// ----------------------------------------------------------------------------

// frame constructor
MyFrame::MyFrame(const wxString& title)
       : wxFrame(NULL, wxID_ANY, title)
{
    // set the frame icon
    SetIcon(wxICON(sample));

#if wxUSE_MENUBAR
    // create a menu bar
    wxMenu *fileMenu = new wxMenu;

    // the "About" item should be in the help menu
    wxMenu *helpMenu = new wxMenu;
    helpMenu->Append(Minimal_About, "&About\tF1", "Show about dialog");

    fileMenu->Append(Minimal_Quit, "E&xit\tShift-Ctrl-Alt-X", "Quit this program");
    wxMenuItem* item = new wxMenuItem(fileMenu, -1, "item");
    fileMenu->Append(item);
    // now append the freshly created menu to the menu bar...
    wxMenuBar *menuBar = new wxMenuBar();
    menuBar->Append(fileMenu, "&File");
    menuBar->Append(helpMenu, "&Help");

    // ... and attach this menu bar to the frame
    SetMenuBar(menuBar);
#else // !wxUSE_MENUBAR
    // If menus are not available add a button to access the about box
    wxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
    wxButton* aboutBtn = new wxButton(this, wxID_ANY, "About...");
    aboutBtn->Bind(wxEVT_BUTTON, &MyFrame::OnAbout, this);
    sizer->Add(aboutBtn, wxSizerFlags().Center());
    SetSizer(sizer);
#endif // wxUSE_MENUBAR/!wxUSE_MENUBAR

    
#if wxUSE_STATUSBAR
    // create a status bar just for fun (by default with 1 pane only)
    CreateStatusBar(2);
    SetStatusText("Welcome to wxWidgets!");
#endif // wxUSE_STATUSBAR
}


// event handlers

void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
{
    // true is to force the frame to close
    Close(true);
}

void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
{
    // here does not work!
    auto currentFont = this->GetFont();
    auto newFont = currentFont.Bold();
    cb->SetFont(newFont);
}

```
### Platform and version information

- wxWidgets version 3.2.2.1 you use:
- wxWidgets port wxMSW
- OS Windows 10

**Comment by PBfordev** [comment]
Just to possibly save someone time going through all that code above:  The issue seems to be control hierarchy, where
 the second panel containing the second od combo is created as a child of the first panel and thus sibling of the first combo.

The shortened code
```cpp
#include <wx/wx.h>
#include <wx/odcombo.h>

class MyApp : public wxApp
{
    bool OnInit() override
    {
        auto frame = new wxFrame(nullptr, wxID_ANY, "Minimal wxWidgets App");

        auto panel = new wxPanel(frame);
        panel->SetBackgroundColour(*wxRED);
        auto panelSizer = new wxBoxSizer(wxVERTICAL);
        auto cb = new wxOwnerDrawnComboBox(panel, wxID_ANY);
        cb->Append("red");
        cb->Append("green");
        panelSizer->Add(cb, wxSizerFlags().Border());

        auto panel2 = new wxPanel(panel);
        panel2->SetBackgroundColour(*wxBLUE);
        auto panel2Sizer = new wxBoxSizer(wxVERTICAL);
        panelSizer->Add(panel2);
        auto cb2 = new wxOwnerDrawnComboBox(panel2, wxID_ANY);
        cb2->Append("red");
        cb2->Append("green");
        panel2Sizer->Add(cb2, wxSizerFlags().Border());
        panel2->SetSizer(panel2Sizer);

        panel->SetSizer(panelSizer);
        frame->Show(true);
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```
The code above works when `wxComboBox` is used instead of `wxOwnerDrawnComboBox`.

It also works with wxOwnerDrawnComboBox` when both combos are children of the same panel or the two panels are siblings but that is probably of no help to the OP.

**Comment by Rezakarimi66** [comment]
@PBfordev I think it could be related to handling key navigation event in containers with tab traversal feature. Normally when owner drawn combo box is poped up, the key events should go there but it seems that navigation keys go to the parent instead and the odcombo lose focus and pops down. Is there any workaround for this?

**Comment by PBfordev** [comment]
Sorry, I have no idea what is going on. Why would a panel be interested in Down key, it should care only about Tab.

When I remove the first combo, the "second" one starts working. When I have two od combos on the first panel, they work too. So it seems that the first combo on the first panel somehow affects the second combo on the second panel, but I do not know why that happens (hopefully it is not one of those tricky focus-related issues)...

**Comment by Rezakarimi66** [comment]
I guessed that the problem may be that `wxVListBoxComboPopup` does not get the focus in Windows thus when it is popped up, the focus still remains on its parent which is wxPanel and it cause the bug. I looked at the code in `odcombo.cc` and I noticed that you don't do anything on the `setFocus` function for MSW port. So I changed the code to the following:

```
void wxVListBoxComboPopup::SetFocus()
{
    // Suppress SetFocus() warning by simply not calling it. This combo popup
    // has already been designed with the assumption that SetFocus() may not
    // do anything useful, so it really doesn't need to be called.
#ifdef __WXMSW__
    wxVListBox::SetFocus(); // **<- this is my change!**
#else
    wxVListBox::SetFocus();
#endif
}
```
and it works :) I don't have the whole picture of this code and not sure that where exactly could create a possible side effect. Could you ( @PBfordev @vadz ) please check it and tell me your feedback

**Comment by PBfordev** [comment]
Could you ( @PBfordev) please check it and tell me your feedback.

Sorry, as I said before, I have no idea. But I would advise against doing blind fixes, believing it would be for the best to establish the cause of the bug (i.e., how can the controls affect each other in the original control hierarchy scenario).

**Comment by Rezakarimi66** [comment]
I don't think it's a blind fix. On the contrary, I think it's a reasonable fix. Why should the popped up window not get the focus? Why should the focus be disabled only for Windows port? The original comment in the code is vague and even unsure about the all possible options. Take a look at it below:

> // Suppress SetFocus() warning by simply not calling it. This combo popup
    // has already been designed with the assumption that SetFocus() may not
    // do anything useful, so it really doesn't need to be called.
   
which warning are you talking about? Is it a compiler warning?

**Comment by PBfordev** [comment]
> I don't think it's a blind fix. 

By blind fix, I meant that we do not know the root of the problem, i.e., why it happens only in some control combination scenarios, see my previous posts. From what I saw, focus-related issues are generally tricky and "fixing" something in one place may break something elsewhere. Sure, one can assume that the missing `SetFocus()` call was omitted by mistake, but I myself prefer facts to assumptions. But that's just me. Just to be sure, I am not a developer, I am just a user like you.

> which warning are you talking about? Is it a compiler warning?

I have not mentioned any warning? If you meant the warning mentioned in the quoted code comment, perhaps it is the one produced by `wxLogApiError()` in `wxWindowMSW::SetFocus()`?

**Comment by vadz** [comment]
This code dates from c0c05e79b2 (Supress SetFocus() warning in wxVListBoxComboPopup, 2010-05-09), i.e. a long time ago and before the rewrite of `wxPopupWindow` in wxMSW in 56c4191168 (Reimplement wxPopupWindow as a WS_POPUP window under MSW, 2018-10-20), so it might well be irrelevant or even harmful by now.

Unfortunately I'm really afraid of touching it because I don't know this code well and while allowing the focus to be set to the popup might fix this (relatively minor) problem, it's not at all impossible that it breaks something else.

Can other people using this control in their program please check and confirm that the fix doesn't break anything for them?

**Comment by Rezakarimi66** [comment]
> This code dates from [c0c05e7](https://github.com/wxWidgets/wxWidgets/commit/c0c05e79b20d6ca372ece6ac5995b0e3db18a29b) (Supress SetFocus() warning in wxVListBoxComboPopup, 2010-05-09), i.e. a long time ago and before the rewrite of `wxPopupWindow` in wxMSW in [56c4191](https://github.com/wxWidgets/wxWidgets/commit/56c419116838045f23f046112960d4e42f98f80d) (Reimplement wxPopupWindow as a WS_POPUP window under MSW, 2018-10-20), so it might well be irrelevant or even harmful by now.
> 
> Unfortunately I'm really afraid of touching it because I don't know this code well and while allowing the focus to be set to the popup might fix this (relatively minor) problem, it's not at all impossible that it breaks something else.
> 
> Can other people using this control in their program please check and confirm that the fix doesn't break anything for them?

@vadz thanks for your response. Just want to inform you that I am using this fix and have not seen any problem so far
