### ISSUE TITLE
wxScrolledCanvas link error 

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#23774]
Related to https://github.com/wxWidgets/wxWidgets/issues/22805

wxScrolledCanvas simple a typedef templated class
```
typedef wxScrolled<wxWindow> wxScrolledCanvas;
```
  that creates problems since MSVC will expand the template in each library it's compiled into and then blows up when MSVC attempts to link them together.

```
LINK: command "C:\BuildTools\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pcbnew_kiface.rsp /out:pcbnew\_pcbnew.dll /implib:pcbnew\pcbnew.lib /pdb:pcbnew\_pcbnew.pdb /dll /version:0.0 /machine:x64 /DEBUG /MANIFEST:NO /debug /INCREMENTAL" failed (exit code 1169) with the following output:
wxmsw32ud_core.lib(wxmsw32ud_core_vc_custom.dll) : error LNK2005: "public: __cdecl wxScrolled<class wxWindow>::wxScrolled<class wxWindow>(class wxWindow *,int,class wxPoint const &,class wxSize const &,long,class wxString const &)" (??0?$wxScrolled@VwxWindow@@@@QEAA@PEAVwxWindow@@HAEBVwxPoint@@AEBVwxSize@@JAEBVwxString@@@Z) already defined in 3d-viewer.lib(appearance_controls_3D_base.cpp.obj)
wxmsw32ud_core.lib(wxmsw32ud_core_vc_custom.dll) : error LNK2005: "public: virtual __cdecl wxScrolled<class wxWindow>::~wxScrolled<class wxWindow>(void)" (??1?$wxScrolled@VwxWindow@@@@UEAA@XZ) already defined in 3d-viewer.lib(appearance_controls_3D_base.cpp.obj)
```

I just had to fix this today in KiCad again 
https://gitlab.com/kicad/code/kicad/-/commit/2e5430a87484e64b33879f46b105b8888a5103eb

The wx 3.2 abi compatible solution is to potentially add a #include <wx/grid.h> inside  wx/scrollwin.h which lets MSVC see that wxScrolledCanvas is already exported externally since wxGrid is a child of wxScrolledCanvas and it won't create a duplicate copy of the wxScrolledCanvas expansion

**Comment by vadz** [comment]
Would the linked PR fix the problem for you? AFAICS it can also be backported to 3.2 as is.
