### ISSUE TITLE
wxListCtrl lines for list and header are mismatched in MSW dark mode

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23772]
### Description
When using `wxListCtrl` in MSW dark mode with rules (e.g., `wxLC_VRULES` style flag), the rules in the list have different color* than those in the header:
![wx-listctrl-dark-lines](https://github.com/wxWidgets/wxWidgets/assets/12495521/f7cb8592-1c52-48f6-b57f-66279a2aada1)
vs
![wx-listctrl-lines](https://github.com/wxWidgets/wxWidgets/assets/12495521/0ce736b6-92da-4df0-9326-25ef5870429a)
_* the original report wrongly stated that they were thicker._

To Reproduce:
1. Make sure Windows is set to dark mode and environment variable `wx_msw_dark_mode` is set to `1`.
2. Run the listctrl sample.
3. From the menu "List" choose "Toggle lines".
4. Observe the difference in the line colour between the header and list.

### Platform and version information
- wxWidgets version: current GIT master
-  wxWidgets port: wxMSW
-  OS: Windows 10 22H2 v19045.3324

**Comment by vadz** [comment]
I don't know how to get the colour used by the native header control in dark mode. We could, of course, just hardcode it but this doesn't look like a great idea...

**Comment by PBfordev** [comment]
I have also only know noticed that in dark mode, the custom font is not set (see serif italics in the item 0 in light mode screenshot).
