### ISSUE TITLE
wxMessageBox and wxMessageDialog throw Exceptions.  wxDialog works, no Exception

### ISSUE THREAD

**Issue by davearesmall** [wxWidgets/wxWidgets#23796]
wxMessageBox and wxMessageDialog throw Exceptions.  wxDialog works, no Exception
Is this a new bug? or has it been already reported?  or, is it a non-issue, something unique only to me?
Or is it something I am doing wrong?

/* Visual Studio Output log:
	'My.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. 
	ERROR Exception thrown at 0x00007FFE2530CF19 (KernelBase.dll) in My.exe: 0x8001010D: An outgoing call cannot be made since the application is dispatching an input-synchronous call.
	onecore\com\combase\dcomrem\giptbl.cxx(1786)\combase.dll!00007FFE25F6ADD7: (caller: 00007FFE25F953D8) ReturnHr(1) tid(85c) 8000FFFF Catastrophic failure
	'My.exe' (Win32): Loaded 'C:\Windows\System32\OneCoreCommonProxyStub.dll'. 

Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: wil::ResultException at memory location 0x000000B4446FC9B0.
Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: wil::ResultException at memory location 0x000000B4446FCE10.
Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
The thread 0x1818 has exited with code 0 (0x0).
Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: wil::ResultException at memory location 0x000000B4446FCAE0.
Exception thrown at 0x00007FFE2530CF19 in My.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
The thread 0x27d4 has exited with code 0 (0x0).
	*/
	

I am using:	
	wxWidgets version 3.2.2.1
	also tried version 3.05 and it produces the same Exceptions
	
I am using:	
Microsoft Visual Studio Community 2022 Version 17.6.5
VisualStudio.17.Release/17.6.5+33829.357

It was compiled in both debug compiler platforms: x64 and win32
	and both produce the same Exception
	
	
I have reduced the program down to the simplest possible window that shows the problem:

#include <wx/wxprec.h>
class MyFrame :  public wxFrame
{
public:
	MyFrame(const wxString& title) : wxFrame(NULL, wxID_ANY, title){ }
};

class MyApp :public  wxApp
{
public:
	bool OnInit()
	{
	MyFrame* myframe = new MyFrame("Hello");
	myframe->Show();
	wxMessageBox("wxMessageBox Text");						// ERROR! Throws Exception
// or
//	wxMessageDialog mydialog(myframe, "wxMessageDialog Text");	// ERROR! Throws Exception
// or
//	wxDialog mydialog(myframe, wxID_ANY, "wxDialog Text");	// WORKS! Does NOT throw an Exception
//	int answer = mydialog.ShowModal();
	return true;
	}
};
wxIMPLEMENT_APP(MyApp);

**Comment by PBfordev** [comment]
There is no such known issue in either wxWidgets version and there is nothing wrong with the code you posted.

Therefore, the issue must be either with your system (not very likely unless you observed other issues there) or with your wxWidgets build or how you use it in your project.

AFAIK, `wxMessageBox()` internally uses `wxMessageDialog` (which uses `::TaskDialog()`) , so it is not surprising that the issue manifests with both.

Did you try building and running one of the samples bundled with wxWidgets (e.g., _minimal_ and/or _dialogs_)?

You should provide the exact way you built wxWidgets and how you added it to your project.

**Comment by vadz** [comment]
There is something exceedingly weird here, wxWidgets doesn't use WIL and so these exceptions can't come from it. The only idea I have is that there is a DLL loaded into your process in some way, but this is something specific to your system and should be reproducible even with a plain Win32 program.

IOW I don't think there is a wxWidgets problem at all, hence closing. Please reopen if you are really sure that this is somehow related to wx (and please explain why).
