### ISSUE TITLE
wxImage::Paste with wxIMAGE_ALPHA_BLEND_COMPOSE relies on undefined NaN to integer conversion

### ISSUE THREAD

**Issue by aurel32** [wxWidgets/wxWidgets#23791]
The following test fails on the riscv64 architecture:
```
-------------------------------------------------------------------------------
wxImage::Paste
  Paste semitransparent image over transparent image
-------------------------------------------------------------------------------
./image/image.cpp:1931
...............................................................................

./image/image.cpp:1945: FAILED:
  CHECK_THAT( actual, RGBSimilarTo(wxImage("image/paste_result_no_background_square_over_circle.png"), 1) )
with expansion:
  image of size 100*100 with alpha doesn't have the same RGB data as image of
  size 100*100 with alpha: first mismatch is at (0, 0) which has value
  0xffffff00 instead of the expected 0x00000000
```

I expect the test to pass like on other architectures.

### Description

I have tracked the bug to an undefined NaN to integer conversion in wxImage::Paste with wxIMAGE_ALPHA_BLEND_COMPOSE, and more precisely in the following code:

```
                        for (int c = 3 * i; c < 3 * (i + 1); c++)
                        {
                            target_data[c] =
                                (unsigned char)(((source_data[c] * source_alpha +
                                    target_data[c] * light_left) /
                                result_alpha) + 0.5f);
                        }
```

When `source_alpha`, `light_left` and `result_alpha` are all `0.0` like in the testcase, the result is a NaN. It is then casted to an `unsigned char`. This is an undefined operation, which happens to give the expected result on x86 and a few other architectures, but not on riscv64.

The correct way is probably to test for a NaN before casting the value.

### Platform and version information

- wxWidgets version 3.2.2
- wxWidgets port wxGTK
- OS Debian GNU/Linux sid on riscv64

+ GTK version: 3.24.38
+ Which GDK X11

**Comment by paulcor** [comment]
GCC's `-fsanitize=undefined` doesn't catch this, at least on x64.

Fixed in 496a9a40a1.
