### ISSUE TITLE
wxFileHistory::Load(const wxConfigBase&) ignores the menu path style

### ISSUE THREAD

**Issue by hwiesmann** [wxWidgets/wxWidgets#23799]
By using wxFileHistory::Load always the full paths are shown. Formatting the labels is not done.

A quick fix is to call DoRefreshLabels() at the end of the method.

AddFileToHistory could also be used instead of the special implementation of adding menus inside Load(). Then there is only one method that is used to add files to the history and there is only one method that can be buggy.

**Comment by vadz** [comment]
Calling `DoRefreshLabels()` looks like a simple fix, so please don't hesitate submitting a PR doing it. TIA!
