### ISSUE TITLE
Wrong return types on the documentation of wxRealPoint and wxPoint

### ISSUE THREAD

**Issue by jank9201** [wxWidgets/wxWidgets#23804]
### Description

The  methods of class wxRealPoint and wxPoint declared in " interface/wx/gdicmn.h"
class wxRealPoint
```
    wxSize operator /(const wxRealPoint& sz, int factor);
    wxSize operator *(const wxRealPoint& sz, int factor);
    wxSize operator *(int factor, const wxSize& sz);
    wxSize& operator /=(int factor);
    wxSize& operator *=(int factor);
```

and class wxPoint

```
    wxSize operator /(const wxPoint& sz, int factor);
    wxSize operator *(const wxPoint& sz, int factor);
    wxSize operator *(int factor, const wxSize& sz);
    wxSize& operator /=(int factor);
    wxSize& operator *=(int factor);
```
These methods are not correct according to the class wxRealPoint  and wxPoint declared in "include/wx/gdicmn.h"

In  "include/wx/gdicmn.h"
the above-menthoned methods in class wxRealPoint are defined as follows :
```
inline wxRealPoint operator/(const wxRealPoint& s, int i)
{
    return wxRealPoint(s.x / i, s.y / i);
}

inline wxRealPoint operator*(const wxRealPoint& s, int i)
{
    return wxRealPoint(s.x * i, s.y * i);
}

inline wxRealPoint operator*(int i, const wxRealPoint& s)
{
    return wxRealPoint(s.x * i, s.y * i);
}

```
the above-menthoned methods in class wxPoint are as follows :

```
inline wxPoint operator/(const wxPoint& s, int i)
{
    return wxPoint(s.x / i, s.y / i);
}

inline wxPoint operator*(const wxPoint& s, int i)
{
    return wxPoint(s.x * i, s.y * i);
}

inline wxPoint operator*(int i, const wxPoint& s)
{
    return wxPoint(s.x * i, s.y * i);
}
```
Compare above methods from different header files,  we can get the conclusion that the return type and some parameter type of these method  listed in " interface/wx/gdicmn.h" are incorrect.

The first three of the class wxRealPoint and wxPoint should be as follows:

class wxRealPoint
 ```
   wxRealPoint operator /(const wxRealPoint& s, int factor);
    wxRealPoint operator *(const wxRealPoint& s, int factor);
    wxRealPoint operator *(int factor, const wxRealPoint & s);
```
and class wxPoint
  ```
  wxPoint operator /(const wxPoint& s, int factor);
    wxPoint operator *(const wxPoint& s, int factor);
    wxPoint operator *(int factor, const wxPoint& s);
```

I do not found others, but I think the correct  should be as follows:
class wxRealPoint
    ```
wxRealPoint& operator /=(int factor);
    wxRealPoint& operator *=(int factor);
```

and class wxPoint
```
    wxPoint& operator /=(int factor);
    wxPoint& operator *=(int factor);
```

### Platform and version information

- wxWidgets version  you use:
- wxWidgets port  you use:
- OS  and its version:

+ GTK version: 
+ Which GDK  backend is used:
+ Current theme:

**Comment by jank9201** [comment]
sorry, I did not make it clear,  the some methods of class wxRealPoint declared in " interface/wx/gdicmn.h",  are different from the methods of class wxRealPoint declared in " include/wx/gdicmn.h"
such as:
`wxSize operator /(const wxRealPoint& sz, int factor);` 
this is declared in  class wxRealPoint in " interface/wx/gdicmn.h";
while in the class wxRealPoint defined in " include/wx/gdicmn.h" is defined as follow:
```
inline wxRealPoint operator/(const wxRealPoint& s, int i)
{
return wxRealPoint(s.x / i, s.y / i);
}
```

The two menthioned-aboved method  should be same thing, while the return type of the first method is wxSize, and the return type of the second method is  wxRealPoint , so logically,  wxSize is not correct,

and one more 

`wxSize operator *(int factor, const wxSize& sz);`  declared in class wxRealPoint whch dec;ared in " interface/wx/gdicmn.h"
should be  same thing with 
```
inline wxRealPoint operator*(int i, const wxRealPoint& s)
{
return wxRealPoint(s.x * i, s.y * i);
}
```  
which defined in " include/wx/gdicmn.h"

in this case, the return type and second parameter type are both incorrect.

the other eight methods of class wxRealPoint and wxPoint listed in the top have same problems.

**Comment by vadz** [comment]
I see, thanks, the return types are indeed wrong (due to copy-and-paste probably). If you can please make a PR fixing `interface/wx/gdicmn.h` it would be welcome, TIA!
