### ISSUE TITLE
Crash when moving wxStaticBoxSizer between displays on MSW 

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23826]
### Description
When moving a frame containing `wxStaticBoxSizer` from a display with a higher DPI to a display with a lower DPI, the application crashes in  `wxWindowBase::GetBestSize()` with `Exception thrown: read access violation. **this** was nullptr.`.

The crash disappears when reverting https://github.com/wxWidgets/wxWidgets/commit/d847f3b039f469000e4a0673ae1f88a81e889248.

Call stack:
```
wxmsw330ud_core_vc_x64_custom.dll!wxWindowBase::GetBestSize() Line 903
wxmsw330ud_core_vc_x64_custom.dll!wxStaticBox::PositionLabelWindow() Line 167
wxmsw330ud_core_vc_x64_custom.dll!wxStaticBox::MSWBeforeDPIChangedEvent(const wxDPIChangedEvent & __formal={...}) Line 372
wxmsw330ud_core_vc_x64_custom.dll!wxWindow::MSWUpdateOnDPIChange(const wxSize & oldDPI={...}, const wxSize & newDPI={...}) Line 5064
wxmsw330ud_core_vc_x64_custom.dll!wxWindow::MSWUpdateOnDPIChange(const wxSize & oldDPI={...}, const wxSize & newDPI={...}) Line 5054
wxmsw330ud_core_vc_x64_custom.dll!wxWindow::MSWUpdateOnDPIChange(const wxSize & oldDPI={...}, const wxSize & newDPI={...}) Line 5054
wxmsw330ud_core_vc_x64_custom.dll!wxWindow::MSWUpdateOnDPIChange(const wxSize & oldDPI={...}, const wxSize & newDPI={...}) Line 5054
wxmsw330ud_core_vc_x64_custom.dll!wxWindow::MSWUpdateOnDPIChange(const wxSize & oldDPI={...}, const wxSize & newDPI={...}) Line 5054
wxmsw330ud_core_vc_x64_custom.dll!wxNonOwnedWindow::HandleDPIChange(const wxSize & newDPI={...}, const wxRect & newRect={...}) Line 284
wxmsw330ud_core_vc_x64_custom.dll!wxNonOwnedWindow::MSWWindowProc(unsigned int message=736, unsigned __int64 wParam=6291552, __int64 lParam=666884890720) Line 253
wxmsw330ud_core_vc_x64_custom.dll!wxTopLevelWindowMSW::MSWWindowProc(unsigned int message=736, unsigned __int64 wParam=6291552, __int64 lParam=666884890720) Line 326
wxmsw330ud_core_vc_x64_custom.dll!wxFrame::MSWWindowProc(unsigned int message=736, unsigned __int64 wParam=6291552, __int64 lParam=666884890720) Line 914
wxmsw330ud_core_vc_x64_custom.dll!wxWndProc(HWND__ * hWnd=0x00000000000a0aa2, unsigned int message=736, unsigned __int64 wParam=6291552, __int64 lParam=666884890720) Line 3030
```
To reproduce:
1. Run the widgets sample.
2. In the control list select "Static" to display page with static boxes.
3. Attempt to move the sample frame from one display to another.
4. Observe the crash as soon as the window crosses the display boundary.

The widgets sample creates controls in the static box with a "wrong" parent (I can fix that in a separate PR) but this is irrelevant here, the issue is with the sizer label. The same happens when the controls have the static box as the parent or when the sizer is empty.

### Platform and version information
- wxWidgets version: the current GIT master
- wxWidgets port: wxMSW built with MSVS 2022
- OS:  Windows 10 v22H2 build 19045.3324, light mode, primary screen 2560x1440@125% DPI, secondary 1680x1050@100%

**Comment by vadz** [comment]
Oops, thanks a lot for noticing this, will push a fix soon.
