### ISSUE TITLE
Document/View Framework examples

### ISSUE THREAD

**Issue by HunterZ** [wxWidgets/wxWidgets#23836]
I can't understand how to use the Document/View framework from the provided samples or the tutorials at https://forums.wxwidgets.org/viewtopic.php?t=20366

Part of the problem is that I want to create a config file editor that presents the settings as various wxWidgets controls, yet all the examples go off on flights of fancy with paint canvases, text editor controls, and other things that have nothing to do with simple wxWidgets controls.

What I'd really really like to see is a simple example that represents the state of a flag in a text file as a checkbox widget, and allows the user to toggle the checkbox and save its state back to a file. This example would ideally avoid highly-customized classes with bespoke tacked-on APIs, and instead stick as much as possible to using just showing off the base APIs provided by wxWidgets,.

**Comment by oneeyeman1** [comment]
@HunterZ ,
Did you look at widgets sample? It seems you question doesn't have anything to do with Document/View framework...

**Comment by vadz** [comment]
The original purpose of docview classes was to develop document-based applications and a single flag is not much of a "document". You can certainly make it fit into this framework by creating a custom view containing just a checkbox, but I don't think this merits a separate sample, sorry.

If you have any concrete questions about how to do it, please ask them on the mailing list/forum/etc.

**Comment by HunterZ** [comment]
> @HunterZ , Did you look at widgets sample? It seems you question doesn't have anything to do with Document/View framework...

Yes. I'm trying to make an application that presents a set of run-of-the-mill GUI controls for modifying settings in a configuration file for another application.

The existing docview examples I've been able to find in the community are not helpful, because one of them is a paint program, and the other completely subverts the MVC model intended by the framework by making a text editor widget be the source of truth instead of the underlying document class.

In the end, I had to search around GitHub for other projects that use docview to find useful examples. Without those, I probably would have given up.

**Comment by oneeyeman1** [comment]
Hi,

On Fri, Sep 29, 2023 at 11:53 AM Ben S. ***@***.***> wrote:

> @HunterZ <https://github.com/HunterZ> , Did you look at widgets sample?
> It seems you question doesn't have anything to do with Document/View
> framework...
>
> Yes. I'm trying to make an application that presents a set of
> run-of-the-mill GUI controls for modifying settings in a configuration file
> for another application.
>
> The existing docview examples I've been able to find in the community are
> not helpful, because one of them is a paint program, and the other
> completely subverts the MVC model intended by the framework by making a
> text editor widget be the source of truth instead of the underlying
> document class.
>

Why do you want to use an outdated framework in the first place?

Take a look at AUI...

Or even better - try the basic tree list control in one doc/one view
scenario

Thank ypio.

**Comment by HunterZ** [comment]
> Why do you want to use an outdated framework in the first place? Take a look at AUI... Or even better - try the basic tree list control in one doc/one view scenario Thank ypio.
Why do you think that someone who doesn't know anything about wxWidgets would open up the documentation site at https://docs.wxwidgets.org/3.0/ and know that anything is outdated, or that anything in particular should be used? wxAUI is barely mentioned on any of the high-level pages there, and the document/view framework documentation doesn't say anything about it being outdated or superseded by wxAUI.

**Comment by vadz** [comment]
@HunterZ Please disregard the nonsensical reply about AUI, it's just completely wrong and I have no idea why was it posted. Docview framework is not deprecated and AUI is completely orthogonal to it, it makes no sense whatsoever to replace the former by the latter.
