### ISSUE TITLE
Support dynamic instantiation of GLX GLCanvas under X11 and EGL under other display systems

### ISSUE THREAD

**Issue by rkitover** [wxWidgets/wxWidgets#23833]
### Background

Some distributions like Fedora and now Gentoo build wxGTK with `--disable-glcanvasegl`.

They made this decision to support some software that does not yet work under EGL, for example:

https://github.com/prusa3d/PrusaSlicer/issues/9774

Unfortunately, this means that a wxGTK program under Wayland lacks any OpenGL support unless run under xwayland.

### Proposal

I'd like to propose a configure option such as `--enable-x11-glcanvasglx`, or perhaps you can think of a better name.

Instead of disabling the EGL GLCanvas and only having the GLX implementation available, like `--disable-glcanvasegl` does, what this option would do is, when creating an instance of GLCanvas, query GDK to check if the program's display is X11, and if so, instantiate the GLX version of GLCanvas, otherwise instantiate the EGL version as usual.

I may be able to work on a PR for this.

**Comment by vadz** [comment]
We'd be very glad to have support for this and we don't even need any configure option, as it should be the default behaviour. Unfortunately, it's not that simple to do it, as discussed in
#22325. If you have time to work on this, any PRs would be definitely very welcome and please don't hesitate to discuss them in that issue or on wx-dev mailing list, but I don't think it's useful to keep this issue open as it's about exactly the same thing.
