### ISSUE TITLE
Impossible to compile with glcanvas

### ISSUE THREAD

**Issue by daerlnaxe** [wxWidgets/wxWidgets#23848]
WxWidgets 3.2.2.1

Hi,

I never worked with wxwidgets before, for c++ i worked with qt and msvs there is a lot of time. I need your help.

I would to use wxwidgets to try to have an opengl part inside a window. 

I can't compile at all, i used the sample to begin but i'm pretty sure it's outdated, because i see more arguments than in the sample but i can't find something new.

i try to inherit from wxGLCanvas
```
MyGl::MyGl(wxFrame *parent) : wxGLCanvas(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, wxT("GLCanvas")            )
```

Compilation with , `g++ *.cpp `wx-config --libs --cxxflags --gl-libs` -o widgetTest3`
fail like this
```


MyGl.cpp: In constructor ‘MyGl::MyGl(wxFrame*)’:
MyGl.cpp:20:124: error: no matching function for call to ‘wxGLCanvas::wxGLCanvas(wxFrame*&, wxStandardID, const wxPoint&, const wxSize&, int, const wchar_t [9])’
   20 | MyGl::MyGl(wxFrame *parent) : wxGLCanvas(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, wxT("GLCanvas")            )
      |                                                                                                                            ^
In file included from /usr/local/include/wx-3.2/wx/glcanvas.h:328,
                 from MyGl.h:2,
                 from MyGl.cpp:1:
/usr/local/include/wx-3.2/wx/gtk/glcanvas.h:42:5: note: candidate: ‘wxGLCanvas::wxGLCanvas(wxWindow*, wxWindowID, const int*, const wxPoint&, const wxSize&, long int, const wxString&, const wxPalette&)’
   42 |     wxGLCanvas(wxWindow *parent,
      |     ^~~~~~~~~~
/usr/local/include/wx-3.2/wx/gtk/glcanvas.h:44:27: note:   no known conversion for argument 3 from ‘const wxPoint’ to ‘const int*’
   44 |                const int *attribList = NULL,
      |                           ^
/usr/local/include/wx-3.2/wx/gtk/glcanvas.h:32:5: note: candidate: ‘wxGLCanvas::wxGLCanvas(wxWindow*, const wxGLAttributes&, wxWindowID, const wxPoint&, const wxSize&, long int, const wxString&, const wxPalette&)’
   32 |     wxGLCanvas(wxWindow *parent,
      |     ^~~~~~~~~~
/usr/local/include/wx-3.2/wx/gtk/glcanvas.h:33:38: note:   no known conversion for argument 2 from ‘wxStandardID’ to ‘const wxGLAttributes&’
   33 |                const wxGLAttributes& dispAttrs,
```

**Comment by vadz** [comment]
Not sure which sample did you mean, but the samples under `samples/opengl` directory of your wxWidgets distribution provide examples of working code, see e.g. the `cube` one.

Your code is wrong because you don't pass the attributes argument to the ctor, not sure why are you surprised that it fails but in any case I don't see any problem here.

If you have any questions, please post them to the mailing list, forum etc.

Good luck!

**Comment by oneeyeman1** [comment]
@daerlnaxe ,
What OS? Toolkit?
Did you build the library yourself or compiled from sources?
What issues you had building the sample? Which one (library have at least 4)..
If you are on *nix - are you using X or Wayland?

Thank you.

**Comment by lanurmi** [comment]
@oneeyeman1 This is an issue tracker, not a support forum.

**Comment by vadz** [comment]
> this one: https://wiki.wxwidgets.org/WxGLCanvas

Please use the maintained samples in the distribution instead of decades old pages on the wiki. Wiki is _not_ an official documentation source.

**Comment by oneeyeman1** [comment]
@lanurmi ,
True, but the OP didn't follow the template to submit the big and so the question was relevant.

Thank you.

**Comment by vadz** [comment]
> @lanurmi , True, but the OP didn't follow the template to submit the big and so the question was relevant.

No, it absolutely was not.
