### ISSUE TITLE
Newly added GTK specific methods for wxTextCtrl interface are incorrectly declared public

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#23843]
The newly listed methods here:

https://github.com/wxWidgets/wxWidgets/blob/8ca3d3bc75e8fa1b851cbaeaef128575fd8af0af/interface/wx/textctrl.h#L1794-L1827

are incorrectly listed as public where they are really protected.

**Comment by vadz** [comment]
Thanks for noticing this.

I think they ought to be public actually, shouldn't they?

cc @Blake-Madden

**Comment by Blake-Madden** [comment]
I'm deriving from `wxTextCtrl` and using them in a protected fashion myself, but...

I could see usefulness in them being public if you wanted to use a `wxTextCtrl` and work with its buffer without needing derivation.

**Comment by vadz** [comment]
I'm going to push a change to make these functions public soon.

**Comment by mcorino** [comment]
That's ok. I'm ignoring them for wxRuby anyway. :wink:
