### ISSUE TITLE
Printing (to PDF) throws exception on Windows 11 from within VS 2022 debugger

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#23850]
### Description

On Windows 11 with the latest wxWidgets

1. Run the "printing" sample from Visual Studio (this appears to the be problem environment)
2. Choose **Print...** from the **File** menu
3. Choose "Microsoft Print to PDF" (this may crash with other printers, but I don't have a real printer to test with).
4. Choose any location to save the PDF and hit OK.

I get this exception in *wx/msw/winundef.h*:

![image](https://github.com/wxWidgets/wxWidgets/assets/66873089/3404e093-5d94-4e5d-802a-19561604a361)

I get the same exception in another program of mine, so I don't think it's anything in the sample that's wrong.

### Platform and version information

wxWidgets 3.3
Windows 11
MS Visual Studio 2022

**Comment by Blake-Madden** [comment]
I reverted the recent "print current page" changes and it still crashes, so that is not the issue.

I can confirm also that it crashes from the VS2022 debugger, but not when I run the EXE directly.  (Both my program and the printing sample.)

**Comment by Blake-Madden** [comment]
This may be a Visual Studio debugger issue, I see others (outside of WX) reporting this exact same error:

https://stackoverflow.com/questions/74747514/print-printsupport-source-dll-exception1-element-not-found-calling-cdcstartd

I'll do some further digging...

**Comment by vadz** [comment]
Does it actually crash? I.e. are you sure this exception is not being caught somewhere? IOW what happens if you continue after getting it?

**Comment by Blake-Madden** [comment]
It's not being caught from what I can tell, the debugger does a hard break into the exception and I can't continue.  But I'm really starting to think this is a VS debugger issue. I've reported it to the VS team (also referencing the stackoverflow conversation that discusses the same issue outside of wxWidgets)...maybe that will go somewhere? Or it may be an issue with the new Window 11 print dialog that the VS debugger is picking up on. Either way, I see others reporting it from just using Win32 (and not wx).  I guess we could close this, or leave it up and I can post any updates if I hear anything more.

**Comment by PBfordev** [comment]
> It's not being caught from what I can tell, the debugger does a hard break into the exception and I can't continue. 

As I wrote before, when I hit the Continue button (green triangle) from the MSVS exception popup, the sample recovered and the PDF was OK.

**Comment by vadz** [comment]
Then it's definitely just a first chance exception (that could be ignored in the MSVS debugger exceptions options) and not a wx problem at all.
