### ISSUE TITLE
Printed image is shifted out of paper bounds on wxGTK.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#23860]
### Description

I've modified the "printing" sample to print a blue rectangle: [printing.cpp.txt](https://github.com/wxWidgets/wxWidgets/files/12565763/printing.cpp.txt)

When printing on GTK, on landscape A4 paper, the image is shifted by 7.87 mm to the right so part of the rectangle is clipped:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/cf7b87bc-9efa-47a0-ac41-86a96675a6dc)

The preview from wxWidgets looks fine:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/7a2839e6-9ae6-4b66-8194-3d511a45446b)

The preview from the OS printing dialog when choosing "Print to File" does **not** look fine:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/45794f59-5405-432f-9306-dbbdadce3f87)

PDF from "Print to File":
[wx_print_bug.pdf](https://github.com/wxWidgets/wxWidgets/files/12565759/wx_print_bug.pdf)

Affects real printers too.

### References
https://gitlab.com/kicad/code/kicad/-/issues/1907
https://forum.kicad.info/t/print-from-schematic-editor-is-not-centered-on-paper/44540

In KiCad's PCB Editor (vs Schematic Editor), the printout rendering is re-implemented using Cairo, similar to wxGtkPrinterDCImpl, but in a way that this problem does not appear.

### Platform and version information

- wxWidgets version: 3.2.2
- wxWidgets port: wxGTK
- OS: Linux Mint 21.1, also reported on Ubuntu 23.04 and others
- GTK version: 3.24.33
- Which GDK: X11

**Comment by vadz** [comment]
Could this be related to using different margins? Just a shot in the dark, of course... I'll try to debug this when I have time.

**Comment by dsa-t** [comment]
I've tried playing with margins in different ways, but no luck.

**Comment by dsa-t** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkpapersize.c#L890

GTK uses default bottom margin of 0.56 inches for Letter, Legal, A4 paper. While all the other margins are 0.25 inches.
(margins are set by `gtk_page_setup_set_paper_size_and_default_margins` in `GetPageSetupFromSettings`)
wx only asks about left and top margins in `wxGtkPrinterDCImpl::StartPage` to change the cairo offset. 

There's `gtk_print_operation_set_use_full_page` that could allow to get rid of offset but I don't know what are the implications.

**Comment by vadz** [comment]
Sorry if I'm missing something obvious here, but why are you using `2970586` as rectangle width even though you pass `2970022` to `FitThisSizeToPaper()`? I.e. considering that the rectangle size is greater than the paper size, isn't it normal for it to be clipped?

**Comment by dsa-t** [comment]
These were just the values KiCad used. If you put 297 and 210, the bug does not disappear.

**Comment by vadz** [comment]
I might be missing something fundamental here but, again, if you call `FitThisSizeToPaper(210)` and then try to draw a rectangle of width 297, it seems perfectly normal that it doesn't fit, as you've asked to set things up so that the total paper size is 210.

Or do you mean that if you use 297 as paper size and 210 as rectangle size it still doesn't work?

**Comment by dsa-t** [comment]
Well it basically does:
```
    wxSize imageSize(297, 210);
    FitThisSizeToPaper(imageSize);
...
    wxRect rect(0, 0, 297, 210);
    dc.DrawRectangle(rect);
```

**Comment by dsa-t** [comment]
Meanwhile, in KiCad I've implemented a workaround that requires adding a custom paper size.

https://gitlab.com/kicad/code/kicad/-/commit/3cd6935acb97d89a6446fb6b3509548610360278
https://gitlab.com/kicad/code/kicad/-/issues/1907#note_1554167241

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/61134f77-77a1-41a3-9e37-1b27ffc0e882)
The name "Custom Size 1" doesn't match the list in GTK, so the bottom margin gets set to 0.25 inches, like on other sides. (The code comment in the commit might be misleading)

**Comment by vadz** [comment]
Strange, but I don't see any problem if I use the same size for the paper and rectangle. Here is a more minimal version of your patch:

```diff
diff --git a/samples/printing/printing.cpp b/samples/printing/printing.cpp
index 7c4d7254db..b0982f0b62 100644
--- a/samples/printing/printing.cpp
+++ b/samples/printing/printing.cpp
@@ -127,6 +127,13 @@ int MyApp::OnExit()
 
 void MyApp::Draw(wxDC&dc)
 {
+    dc.SetBrush( *wxBLUE );
+    dc.SetPen( *wxRED );
+
+    wxRect rect(0, 0, 297, 210);
+    dc.DrawRectangle(rect);
+    return;
+
     // This routine just draws a bunch of random stuff on the screen so that we
     // can check that different types of object are being drawn consistently
     // between the screen image, the print preview image (at various zoom
@@ -580,6 +587,9 @@ bool MyPrintout::IsPageSelected(int pageNum)
 
 void MyPrintout::DrawPageOne()
 {
+    FitThisSizeToPaper(wxSize(297, 210));
+    wxGetApp().Draw(*GetDC());
+    return;
     // You might use THIS code if you were scaling graphics of known size to fit
     // on the page. The commented-out code illustrates different ways of scaling
     // the graphics.
```

where I've also added a red border to allow seeing if the rectangle is clipped or not easily.

And for me it's not clipped neither in wx preview nor in GTK preview nor in the generated PDF.

Do you still see the problem even with this diff?

**Comment by vadz** [comment]
Sorry, I do see the problem if I switch to landscape first.

**Comment by dsa-t** [comment]
Yep, it appears that in landscape mode the bottom margin is at the left.

**Comment by vadz** [comment]
I can get it almost but not quite right with

```diff
diff --git a/src/gtk/print.cpp b/src/gtk/print.cpp
index 6230d16c31..d388aa76e9 100644
--- a/src/gtk/print.cpp
+++ b/src/gtk/print.cpp
@@ -2202,10 +2202,34 @@ void wxGtkPrinterDCImpl::StartPage()
     // corner of the printable area. We need to translate it so that it
     // is in the upper left corner of the paper (without margins)
     GtkPageSetup *setup = gtk_print_context_get_page_setup( m_gpc );
-    gdouble ml, mt;
-    ml = gtk_page_setup_get_left_margin (setup, GTK_UNIT_POINTS);
-    mt = gtk_page_setup_get_top_margin (setup, GTK_UNIT_POINTS);
-    cairo_translate(m_cairo, -ml, -mt);
+
+    // The margins we need change depending on the orientation for some reason
+    // (this doesn't seem to be documented anywhere, but see #23860).
+    gdouble mx = 0, my = 0;
+    switch ( gtk_page_setup_get_orientation(setup) )
+    {
+        case GTK_PAGE_ORIENTATION_PORTRAIT:
+            mx = gtk_page_setup_get_left_margin (setup, GTK_UNIT_POINTS);
+            my = gtk_page_setup_get_top_margin (setup, GTK_UNIT_POINTS);
+            break;
+
+        case GTK_PAGE_ORIENTATION_LANDSCAPE:
+            mx = gtk_page_setup_get_bottom_margin (setup, GTK_UNIT_POINTS);
+            my = gtk_page_setup_get_left_margin (setup, GTK_UNIT_POINTS);
+            break;
+
+        case GTK_PAGE_ORIENTATION_REVERSE_PORTRAIT:
+            mx = gtk_page_setup_get_right_margin (setup, GTK_UNIT_POINTS);
+            my = gtk_page_setup_get_bottom_margin (setup, GTK_UNIT_POINTS);
+            break;
+
+        case GTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE:
+            mx = gtk_page_setup_get_top_margin (setup, GTK_UNIT_POINTS);
+            my = gtk_page_setup_get_right_margin (setup, GTK_UNIT_POINTS);
+            break;
+    }
+
+    cairo_translate(m_cairo, -mx, -my);
 
 #if wxCAIRO_SCALE
     cairo_scale( m_cairo, 72.0 / (double)m_resolution, 72.0 / (double)m_resolution );
```

There is still a _small_ offset in reverse orientations.

It does improve things even for them though, and fixes the problem for landscape, so it might be already worth it to commit this.

Could you please check if it helps KiCad (without your workaround)? TIA!

**Comment by dsa-t** [comment]
I'll check, also have you looked into setting `gtk_print_operation_set_use_full_page` to true so that this `cairo_translate` not needed?

**Comment by dsa-t** [comment]
If I choose a real printer, and select 2 pages per side:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/1ca88fdc-0039-489a-bba5-e844de471ae5)
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/74cf92b3-d324-495f-b306-ccb3a712cd8c)


Your fix:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/c5e67181-247f-437d-a929-731cd1af3336)


`gtk_print_operation_set_use_full_page(printOp, true);`, remove `cairo_translate`:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/fc65886e-8bbf-45cc-bc52-42f97d45680f)

**Comment by vadz** [comment]
I've tried `gtk_print_operation_set_use_full_page()` now and the results are about the same for me when printing to PDF: the page bottom/right is clipped in reverse portrait/landscape orientation. I guess it's still better to do it like this instead of fiddling with the margins though, so I've created #23870 with the proposed change -- again, it's not quite perfect, but it's clearly an improvement, thanks!
