### ISSUE TITLE
Is there any method which allows me set a PNG picture created by Canva as wxListbox's background? 

### ISSUE THREAD

**Issue by owenlin27** [wxWidgets/wxWidgets#23866]
### Description
 I’ve tried to build my own GUI application by wxWidget, but I encountered a trouble with creating a wxListbox. I wanted to set my own PNG image as Listbox’s background, just like the effect the wxBitmap button has. I’ve tried several methods like use staticBitmap, wxPaintDC, or set listbox’s background as transparent, but once wxListbox is focus, its defaulted white background will cover the background which I want to show.
I also changed the STYLE of listbox, but still did not solve the problem. Would you please to give some tips or solutions to figure it out if wxWidget can make this function come true. Thank you very much!!

` wxPanel* BGPanel = new wxPanel(this, ID_BGPANEL, wxPoint(30, 200), wxSize(280, 260));
  wxStaticBitmap* backgroundImage = new wxStaticBitmap(BGPanel, wxID_ANY, wxBitmap(wxT("D:\\picture material\\ListBoxBackground.png"), wxBITMAP_TYPE_ANY), wxDefaultPosition, wxDefaultSize);
  backgroundImage->SetSize(wxSize(BGPanel->GetSize().GetWidth(), BGPanel->GetSize().GetHeight()));`
`TaskListBox = new wxListBox(BGPanel, ID_TASKLISTBOX, wxPoint(0, 0), wxSize(280, 260), 0, 0, wxVSCROLL|wxHSCROLL, wxDefaultValidator, _T("ID_TASKLISTBOX"));
TaskListBox->SetBackgroundColour(wxColour(255, 255, 255, 0));
TaskListBox-> Raise();`

![image](https://github.com/wxWidgets/wxWidgets/assets/23209698/9e253d0a-71aa-4ae6-ba8b-534337e51a08)
![image](https://github.com/wxWidgets/wxWidgets/assets/23209698/c8435fe2-cef9-4b86-b3dd-d3c9e682dc36)

### Platform and version information

wxWidgets version[ 3.2.2.1] 
wxWidgets port [wxMSW]
OS [Windows 10] --> 
Compiler [MSVS 2022, gcc810_x64]

**Comment by vadz** [comment]
Generally speaking, if you want to use custom appearance, you shouldn't be using native controls as wxWidgets doesn't (and can't) make any guarantees about customizing them under all platforms.

In this case it seems like you could find `wxHtmlListBox` useful.

**Comment by vadz** [comment]
`wxBG_STYLE_TRANSPARENT` prevents the background from being erased, but this only really works with generic windows and not native controls as you don't know, and can't change, how the latter handle their painting.
