### ISSUE TITLE
Static Text Widgets Size is Not set correctly on GTK3 platform

### ISSUE THREAD

**Issue by SiFly** [wxWidgets/wxWidgets#23871]
Version 3.2.2.1

I'm trying to use wxwidgets on Alma Linux 8 and the text is not rendered correctly if the font is changed (either enboldened or the font size is changed). It looks like the text size is not calculated correctly. I've tried using LayOut and all the other issues at resolving the issue but it does not render correctly, Windows platforms render correctly.

RPMS are as follows

gtk3-3.22.30-10.el8.x86_64
gtk3-devel-3.22.30-10.el8.x86_64

I've produced a patch for text.cpp which tries and displays some text in bold 20 point font and it does not render correctly.
[text.patch](https://github.com/wxWidgets/wxWidgets/files/12598461/text.patch)

Any information on what i am doing wrong would be greatly appreciated

**Comment by oneeyeman1** [comment]
@SiFly ,
Which sample is the patch against? Can you make in the "unified format - add "-u" option?
Also it seems you never add the static text to the sizer...

Thank you.

**Comment by vadz** [comment]
The question above is completely unnecessary because it's pretty clear that the patch is against the text sample, but it's true that unified patches are more readable and hence preferred. More importantly, if I apply this patch:

```diff
diff --git a/samples/text/text.cpp b/samples/text/text.cpp
index 6e512569f6..0239de5eb4 100644
--- a/samples/text/text.cpp
+++ b/samples/text/text.cpp
@@ -1134,6 +1134,9 @@ MyPanel::MyPanel( wxFrame *frame, int x, int y, int w, int h )
     m_password = new MyTextCtrl( this, wxID_ANY, "",
       wxPoint(10,50), wxSize(140,wxDefaultCoord), wxTE_PASSWORD );
     m_password->SetHint("Don't use 12345 here");
+    m_password->Hide();
+    wxStaticText* tpt = new wxStaticText(this, wxID_ANY, "BigText", wxPoint(10, 50), wxDefaultSize);
+    tpt->SetFont({ 20, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL ,wxFONTWEIGHT_NORMAL });
 
     m_limited = new MyTextCtrl(this, wxID_ANY, "",
                               wxPoint(10, 90), wxDefaultSize);
@@ -1276,6 +1279,7 @@ MyPanel::MyPanel( wxFrame *frame, int x, int y, int w, int h )
     wxBoxSizer *column1 = new wxBoxSizer(wxVERTICAL);
     column1->Add( m_text, 0, wxALL | wxEXPAND, 10 );
     column1->Add( m_password, 0, wxALL | wxEXPAND, 10 );
+    column1->Add( tpt, 0, wxALL | wxEXPAND, 10 );
     column1->Add( m_readonly, 0, wxALL, 10 );
     column1->Add( m_limited, 0, wxALL, 10 );
     column1->Add( upperOnly, 0, wxALL, 10 );
```
to the sample everything works correctly for me. The difference is, of course, that I add the static text to the sizer so that it's laid out correctly. Please check if this patch works for you.

**Comment by SiFly** [comment]
Yes this example works correctly.
I should have read the section on sizers more carefully.
