### ISSUE TITLE
Unable to build on Windows using CMake and Ninja

### ISSUE THREAD

**Issue by TheQuinbox** [wxWidgets/wxWidgets#23875]
### Description

When attempting to build wxWidgets using CMake and Ninja on Windows, I get an error about there being no sources given to the targets.

I'm doing:

```batch
cd wxWidgets
mkdir builddir
cd builddir
cmake -G Ninja ..
```

The build log is around 200000 characters, but I can paste it if really necessary.

### Platform and version information

- wxWidgets version you are building: Latest master branch
- wxWidgets port you are building: wxMSW
- OS and its version: Windows 10 22H2 (AMD64) build 19045.3324
- Compiler being used: GCC 13.1.0,, being used with Ninja.

**Comment by vadz** [comment]
We do need the exact error message to be able to do anything about this.

**Comment by TheQuinbox** [comment]
It repeats something like this over and over and over. CMake Error at build/cmake/functions.cmake:592 (add_library):
  No SOURCES given to target: wxjpeg
Call Stack (most recent call first):
  build/cmake/lib/jpeg.cmake:11 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:27 (include)


CMake Error at build/cmake/functions.cmake:592 (add_library):
  No SOURCES given to target: wxpng
Call Stack (most recent call first):
  build/cmake/lib/png.cmake:21 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:27 (include)


CMake Error at build/cmake/functions.cmake:592 (add_library):
  No SOURCES given to target: wxtiff
Call Stack (most recent call first):
  build/cmake/lib/tiff.cmake:19 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:27 (include)


CMake Error at build/cmake/functions.cmake:592 (add_library):
  No SOURCES given to target: wxscintilla
Call Stack (most recent call first):
  build/cmake/lib/stc/scintilla.cmake:13 (wx_add_builtin_library)
  build/cmake/lib/stc/CMakeLists.txt:10 (include)


CMake Error at build/cmake/functions.cmake:592 (add_library):
  No SOURCES given to target: wxlexilla
Call Stack (most recent call first):
  build/cmake/lib/stc/lexilla.cmake:13 (wx_add_builtin_library)
  build/cmake/lib/stc/CMakeLists.txt:11 (include)


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by vadz** [comment]
Do you have the required submodules?

**Comment by TheQuinbox** [comment]
I could've sworn I did, but apparently I did not. All seems to work now, thanks a ton!
