### ISSUE TITLE
Smart quotes on MacOSX

### ISSUE THREAD

**Issue by sciurius** [wxWidgets/wxWidgets#23887]
### Description

MacOS 10.15 Catalina with WxWidgets 3.2.2.

When text is inserted into a TextCtrl, ASCII quotes and apostrophes are replaced by typographic quotes. This screws up program sources, URLs etc.. See attached program for a demonstration.

According to https://github.com/wxWidgets/wxWidgets/issues/15705 this behaviour should be disabled by default.

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use:  osx_cocoa-unicode-3.2
- OS  and its version: macOS 10.15.7

### Misc

````
% wx-config --cxxflags --libs
-I/usr/local/lib/wx/include/osx_cocoa-unicode-3.2 -I/usr/local/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 
-L/usr/local/lib   -framework IOKit -framework Carbon -framework Cocoa -framework QuartzCore -framework AudioToolbox -framework System -framework OpenGL -lwx_osx_cocoau_xrc-3.2 -lwx_osx_cocoau_html-3.2 -lwx_osx_cocoau_qa-3.2 -lwx_osx_cocoau_core-3.2 -lwx_baseu_xml-3.2 -lwx_baseu_net-3.2 -lwx_baseu-3.2 
% g++ `wx-config --cxxflags --libs` -o smartquotes smartquotes.cpp
In file included from smartquotes.cpp:1:
In file included from /usr/local/include/wx-3.2/wx/wx.h:24:
In file included from /usr/local/include/wx-3.2/wx/event.h:22:
In file included from /usr/local/include/wx-3.2/wx/cursor.h:75:
/usr/local/include/wx-3.2/wx/utils.h:749:35: warning: in-class initialization of non-static data member
      is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
````
[smartquotes.cpp.txt](https://github.com/wxWidgets/wxWidgets/files/12672197/smartquotes.cpp.txt)

**Comment by PBfordev** [comment]
> According to #15705 this behaviour should be disabled by default.

You may have missed my #23885 comments explaining:
1. That the commit you refer to is outdated and does not apply for wxWidgets 3.2 (see also https://github.com/wxWidgets/wxWidgets/commit/3028fd40a07cbb6da694ee76f9090e79c9aaf929).
2. [How to disable the automatic character replacements on macOS](https://github.com/wxWidgets/wxWidgets/issues/23885#issuecomment-1727183929) in wxWidgets 3.2.

**Comment by sciurius** [comment]
The `wxTextCtrl` methods you mentioned are not part of the wxPerl API. I'll try adding them.
