### ISSUE TITLE
wxComboCtrl and its derivatives are broken under wxQt

### ISSUE THREAD

**Issue by AliKet** [wxWidgets/wxWidgets#23894]
### Description

After this commit 7ebb20fb04d9c975a82e71c59bdb75f982aa90b8 popup window can no longer be shown and is dismissed immediately if you try to show the dropdown window by clicking the arrow button. And can be seen in the combo sample.

### Platform and version information

- wxWidgets version  you use: lateset
- wxWidgets port  you use: wxQt
- OS  and its version: Ubuntu 18.04

**Comment by vadz** [comment]
Sorry for breaking this.

If this worked before, it should be possible to implement a generic `wxPopupWindow` using the code from the `USE_TRANSIENT_POPUP` case removed by that commit working at least as well as it used to. If you could please try doing this, it would be great. TIA!

**Comment by AliKet** [comment]
I'll try to fix this in a couple of days!

**Comment by AliKet** [comment]
Fixed in #23904
