### ISSUE TITLE
Surprising file name matching of *.* under wxMSW

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23905]
On Windows, the users are generally used to `*.*` matching all the files, including those without an extension. This can be seen for example with _dir_ in the windows command line or Common File Dialogs (or `wxFileDialog` using `*.*`); same when using Win32 `FindFirstFile()`/`FindNextFile()` API with `*.*`, where files without an extension are returned. 

However, with wxWidgets, files without an extension are not matched with `*.*` (probably because they do not actually have the dot in the name, they are matched with `*`), which can be seen in the unmodified widgets sample, for both FileCtrl and DirCtrl. For example, there are files without an extension in the wxWidgets root folder (e.g., _configure_ and _mkinstalldirs_). `wxMatchWild()` and `wxDir::GetAllFiles()` also behave the same.

Such behavior can be rather unexpected when one wants to get all the files in the folder, not to mention that sometimes the wild card pattern comes from the user. 

Additionally, [the description](https://docs.wxwidgets.org/latest/filedlg_8h.html#a3a48d9b7ad35e6c332acb146f78c1b5d) for `wxFileSelectorDefaultWildcardStr` used by `wxFileCtrl` and `wxFileDialog` has:
> Default wildcard string used in wxFileDialog corresponding to all files. 
> It is defined as `"*.*"` under MSW and `"*"` everywhere else. 

Funnily enough, Microsoft's `FindFirstFile()`/`FindNextFile()` [example](https://learn.microsoft.com/en-us/windows/win32/fileio/listing-the-files-in-a-directory) uses just `*` as the pattern.

For completeness sake: Windows PowerShell’s dir etc. do NOT list files without an extension when called with `*.*` but unlike the default _dir_, they also do not list any folders with this mask.

To conclude, if this oddity (at least to an MSW-only person) cannot be fixed (difficult/incompatible/by design), perhaps it should be at least documented somewhere where there is a chance it can be easily spotted.

**Comment by PBfordev** [comment]
Sorry for not being clear (and not providing TDLR).

AFAICT, it is not just `wxFileCtrl` and `wxDirCtrl`: It seems that no wxWidgets API matches extensionless files with `*.*`. I tried  `wxFind{First|Last}File()`, `wxDir` and `wxMatchWild()`; other wxWidgets parts may be affected (e.g., `wxFileSystem` and related).

`wxFileDialog` just happens to work since the files there are provided by the OS, not a wxWidgets function.

**Comment by vadz** [comment]
This is indeed worse than I thought, sorry for missing it. Apparently I was wrong to think that the low level APIs (`Find{First,Next}File()`) handle `*.*`, so we need to change `wxDir` to use `*` with them instead and even map the former to the latter for compatibility.

BTW, we really ought to deprecate `wxMatchWild()`.

**Comment by PBfordev** [comment]
I think there still may be a confusion.

Win32's `Find{First,Next}File()` do return extensionless files when called with `*.*`.

OTOH, `**wx**Find{First,Next}File()` do not return extensionless files when called with `*.*`, despite using the aforementioned Win32 API. It is because `wxDir` on MSW does also [its own matching](https://github.com/wxWidgets/wxWidgets/blob/df6366ff57371f9d2d41f748514d25259e393203/src/msw/dir.cpp#L68C33-L68C33) on the top of the results returned by the native API, ultimately using `wxString::Match()`.

**Comment by vadz** [comment]
Ah, I see (better late than never), thanks for your patient explanations. So this was apparently broken back in 4daceaacbd (Check that files returned from wxDir::FindXXX() match the filter., 2013-04-08, see #3432) and somehow nobody noticed.

Should be fixed by the PR above, thanks again!

**Comment by PBfordev** [comment]
Thanks, my quick and dirty solution (but perhaps a bit quicker) for `*.*` was
```diff
iff --git a/src/msw/dir.cpp b/src/msw/dir.cpp
index 5b05d23d48..d6c56bdf86 100644
--- a/src/msw/dir.cpp
+++ b/src/msw/dir.cpp
@@ -73,9 +73,9 @@ const wxChar *GetNameFromFindData(const FIND_STRUCT *finddata)
 inline bool
 CheckFoundMatch(const FIND_STRUCT* finddata, const wxString& filter)
 {
-    // If there is no filter, the found file must be the one we really are
-    // looking for.
-    if ( filter.empty() )
+    // If there is no filter or matching all files, the found file
+    // must be the one we really are looking for.
+    if ( filter.empty() || filter == wxS("*") || filter == wxS("*.*") )
         return true;
 
     // Otherwise do check the match validity. Notice that we must do it

```
I think neither solution will return an extensionless file with a mask like `wxdat*.*` but maybe I am wrong and I am not sure if there is an easy and reliable fix for this scenario anyway...

**Comment by vadz** [comment]
You're right, this still doesn't handle `x*.*` case properly. Let me add code (and tests) for this case too.

The annoying thing is that I don't want to add yet another function for checking whether a path matches the pattern, but `wxMatchWild()` really can't be used for this and `wxString::Matches()` is not filename-specific.

**Comment by PBfordev** [comment]
> The annoying thing is that I don't want to add yet another function for checking whether a path matches the pattern

Sorry for the stupid question, but why not use `::PathMatchSpec()` (from `shlwapi.h`) here (i.e., in the internal wxWidgets code, we are already using at least one shell function in the base library anyway)?

I was able to find an old disk with short name generation still on and created a folder with files "foo.bar.baz" (short name `FOOBAR~1.BAZ`) and "test.hml" (`TEST~1.HTM`) in it. Then I created a test program using `::Find{First|Next}File()` for matching `*.htm` and `*.bar`:
<details>
<summary>Test Program</summary>

```cpp
#include <wx/wx.h>
#include <shlwapi.h>

void ListFiles(const wxString& path, const wxString& mask, bool usePathMatchSpec)
{
    wxCHECK_RET(path.EndsWith("\\"), "invalid path");
    wxCHECK_RET(!mask.empty(), "invalid mask");

    const wxString  fileName(wxString::Format("%s%s", path, mask));
    HANDLE          findHandle;
    WIN32_FIND_DATA findData;

    wxLogDebug("Listing '%s' (path matching %s)", fileName, usePathMatchSpec ? "On" : "Off");
    findHandle = ::FindFirstFile(fileName.fn_str(), &findData);
    if ( findHandle == INVALID_HANDLE_VALUE )
    {
        if ( ::GetLastError() == ERROR_FILE_NOT_FOUND )
            wxLogDebug("No files found.");
        else
            wxLogSysError("FindFirstFile");
        return;
    }

    wxArrayString files;

    do
    {
        if ( findData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY )
            continue;
        if ( !usePathMatchSpec || ::PathMatchSpec(findData.cFileName, mask.fn_str()) )
            files.push_back(findData.cFileName);

    } while ( ::FindNextFile(findHandle, &findData) == TRUE );
    ::FindClose(findHandle);

    wxLogDebug("Found %zu files:", files.size());

    if ( !files.empty() )
    {
        files.Sort(wxCmpNatural);
        for ( const auto& f : files )
            wxLogDebug(f);
    }
}

class MyApp : public wxApp
{
    bool OnInit() override
    {
        const wxString path(R"(h:\testfile\)");
        const wxString mask("*.htm");

        ListFiles(path,"*.*", false);

        ListFiles(path, mask, false);
        ListFiles(path, mask, true);

        const wxString mask2("*.bar");

        ListFiles(path, mask2, false);
        ListFiles(path, mask2, true);

        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```

</details>

Without `::PathMatchSpec()`, *.htm` matched `*.html`, with it it did not. The example in the comment for `CheckFoundMatch()` 
> something like "*.bar" matches "foo.bar.baz" too and not only "foo.bar"

seems incorrect as the short name for "foo.bar.baz" is "FOOBAR~1.BAZ" which does not match "*.bar".

Output from the program above:
```
Listing 'h:\testfile\*.*' (path matching Off)
Found 2 files:
foo.bar.baz
test.html
Listing 'h:\testfile\*.htm' (path matching Off)
Found 1 files:
test.html
Listing 'h:\testfile\*.htm' (path matching On)
Found 0 files:
Listing 'h:\testfile\*.bar' (path matching Off)
No files found.
Listing 'h:\testfile\*.bar' (path matching On)
No files found.
```

**Comment by vadz** [comment]
Good idea, thanks, this seems to work, so let's do it like this, it's better than writing our own code.

PR updated.

**Comment by vadz** [comment]
Damn, Wine implementation of `PathMatchSpecEx()` is broken :-(

**Comment by PBfordev** [comment]
Sorry, I was incorrect again, neither `PathMatchSpecEx()` nor` PathMatchSpec()` match extensionless files with `*.`  (or even partial file name mask ending with `.*`). I missed that `PathMatchSpecEx()` does not return `BOOL` but `HRESULT`, which resulted in the false positive in my previous post.

FWIW, here is my test program
```cpp
#include <wx/wx.h>
#include <shlwapi.h>

void ListFiles(const wxString& path, const wxString& mask)
{
    wxCHECK_RET(path.EndsWith("\\"), "invalid path");
    wxCHECK_RET(!mask.empty(), "invalid mask");

    const wxString  fileName(wxString::Format("%s%s", path, mask));
    HANDLE          findHandle;
    WIN32_FIND_DATA findData;

    wxLogDebug("Path: '%s', mask: '%s'", path, mask);
    findHandle = ::FindFirstFile(fileName.fn_str(), &findData);
    if ( findHandle == INVALID_HANDLE_VALUE )
    {
        if ( ::GetLastError() == ERROR_FILE_NOT_FOUND )
            wxLogDebug("No files found.");
        else
            wxLogSysError("FindFirstFile");
        return;
    }

    do
    {
        if ( findData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY )
            continue;
        wxLogDebug("  FindFile: found '%s'", findData.cFileName);
        if ( !::PathMatchSpec(findData.cFileName, mask.fn_str()) )
            wxLogDebug("    PathMatchSpec: '%s' does not match '%s'", findData.cFileName, mask);
        if ( ::PathMatchSpecEx(findData.cFileName, mask.fn_str(), PMSF_NORMAL) != S_OK )
            wxLogDebug("    PathMatchSpecEx: '%s' does not match '%s'", findData.cFileName, mask);

    }
    while ( ::FindNextFile(findHandle, &findData) == TRUE );
    ::FindClose(findHandle);
}

class MyApp : public wxApp
{
    bool OnInit() override
    {
        const wxString path(R"(c:\testfile\)");
        const wxArrayString masks({"*", "*.*", "*.", "j*.", "j*e.*"});

        for ( const auto& m : masks )
            ListFiles(path, m);

        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```
And here are the results of running it on a folder with a file named `justfile`:
```
Path: 'c:\testfile\', mask: '*'
  FindFile: found 'justfile'
Path: 'c:\testfile\', mask: '*.*'
  FindFile: found 'justfile'
Path: 'c:\testfile\', mask: '*.'
  FindFile: found 'justfile'
    PathMatchSpec: 'justfile' does not match '*.'
    PathMatchSpecEx: 'justfile' does not match '*.'
Path: 'c:\testfile\', mask: 'j*.'
  FindFile: found 'justfile'
    PathMatchSpec: 'justfile' does not match 'j*.'
    PathMatchSpecEx: 'justfile' does not match 'j*.'
Path: 'c:\testfile\', mask: 'j*e.*'
  FindFile: found 'justfile'
    PathMatchSpec: 'justfile' does not match 'j*e.*'
    PathMatchSpecEx: 'justfile' does not match 'j*e.*'
```
To conclude, the shell path matching functions seem to work differently than find file ones (or good old dir.exe). But hopefully I am wrong again. :P

I am also sorry for opening this can of worms, it is odd no one else reported this in all these years (besides the person on wxForum now), even if extensionless files are rarely used.

**Comment by vadz** [comment]
This is pretty strange, how do my tests pass, even with `d*.*` if it doesn't match files without the extension? In the test there are 2 files and 2 files without the extension and with the latest version of the PR it finds all 4 of them.

**Comment by PBfordev** [comment]
> This is pretty strange, how do my tests pass, even with `d*.*`

This does pass, perhaps because this mask variant was not used in my example where I used (analogically for `dummy`) either `d*.` or `d*y.*`.

When I add tests for this
```diff
diff --git a/tests/file/dir.cpp b/tests/file/dir.cpp
index 28967b5fdd..da5d4444c4 100644
--- a/tests/file/dir.cpp
+++ b/tests/file/dir.cpp
@@ -170,6 +170,9 @@ TEST_CASE_METHOD(DirTestCase, "Dir::Traverse", "[dir]")
         WARN("PathMatchSpecEx() seems to work under Wine now");
     }
 
+    CHECK( wxDir::GetAllFiles(DIRTEST_FOLDER, &files, "d*.") == 2 );
+    CHECK( wxDir::GetAllFiles(DIRTEST_FOLDER, &files, "d*y.*") == 4 );
+
     // enum all files according to the filter
     CHECK( wxDir::GetAllFiles(DIRTEST_FOLDER, &files, "*.foo") == 1 ); 
```
I get
```
Dir::Traverse
-------------------------------------------------------------------------------
D:\Dev\Desktop\!Lib\wxWidgets-PB\tests\file\dir.cpp(152)
...............................................................................

D:\Dev\Desktop\!Lib\wxWidgets-PB\tests\file\dir.cpp(173): FAILED:
  CHECK( wxDir::GetAllFiles(wxString("dirTest_folder"), &files, "d*.") == 2 )
with expansion:
  0 == 2

D:\Dev\Desktop\!Lib\wxWidgets-PB\tests\file\dir.cpp(174): FAILED:
  CHECK( wxDir::GetAllFiles(wxString("dirTest_folder"), &files, "d*y.*") == 4 )
with expansion:
  2 == 4
```
but I may be missing something here, as usual.

**Comment by Skywise711** [comment]
> I am also sorry for opening this can of worms, it is odd no one else reported this in all these years (besides the person on wxForum now), even if extensionless files are rarely used.

I created an account just so I could reply, being the person in question. Thank you all for your work on wx.

I didn't test for this intentionally. Just chance that my chosen test directories contained these files. My switching between Windows Explorer and my program's wxGenericDirCtrl lead me to eventually noticing the issue.

For me, usage of *.* for "all files" goes back to my DOS days and 8.3 filenames, as discussed in the link mentioned by Pbfordev.

Perhaps in a sense it's deprecated since current code samples don't use it. That may be why it was missed. Younger developers just never learned it the way I did 30+ years ago.

Brian

**Comment by vadz** [comment]
We all agree that `*.*` must match all files (with or without extension) under MSW, this much is clear. And patterns `x*.*` must behave as `*.*` too because they are almost certainly matched left to right and so it's the same as "match `x` and then match `*.*`".

The less clear cases are the following ones:

1. `*x.*`: this one matches files with and without extensions in `cmd.exe` but not with `PathMatchSpecEx()`.
2. `*.`: this one matches the files without extensions in `cmd.exe` but not with `PathMatchSpecEx()`.

I don't know which behaviour is more logical, to be honest. `cmd.exe` might seem better but it can be rather counterintuitive due to short names, e.g. running `dir *e.*` in wx directory finds `config.guess` (because its short form is `CONFIG~1.GUE`, of course) and I don't think we want to emulate this.

To be honest, I'm tempted to merge the current PR and backport it to 3.2 because `*.*` is clearly an important case, and leave the rest of the problem for some future time...

BTW, especially for backporting to 3.2 it's important to avoid changing the existing behaviour without good reason.

**Comment by vadz** [comment]
FYI, I've added a semi-interactive test to the PR which can be used like this (from Cygwin shell prompt):

```
$ WX_TEST_DIR_FILTER='.*' ./tests/vc_x64_mswud/test.exe Dir::Match
```

**Comment by PBfordev** [comment]
I agree that fixing the "all files" scenario is a huge improvement already and I also do not see any solution for extensionless files except (unrealistic) writing own code.
