### ISSUE TITLE
wxComboCtrl does not work properly on Wayland with Plasma and Sway when out of parent window bounds.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#23908]
### Description

When the cursor is over a wxComboCtrl window, but goes out of the parent window bounds, seems like the actual cursor position gets constrained to it and you can resize the parent window this way.

KDE Plasma `4:5.27.8-0ubuntu1~ubuntu23.04~ppa1`:

https://github.com/wxWidgets/wxWidgets/assets/37658952/646edba5-d96a-4d8e-8a3f-1e81e688de0d

Also happens on Sway `1.7-6` (couldn't get OBS to record screen in it).

Not an issue on GNOME Wayland sessions.

### Platform and version information

- wxWidgets version  you use: [3.2.3 (proposed)](https://github.com/wxWidgets/wxWidgets/pull/23891)
- wxWidgets port  you use: wxGTK
- OS  and its version: Ubuntu 23.04
+ GTK version: 3.24.37-1ubuntu1
+ Which GDK  backend is used: Wayland

**Comment by imciner2** [comment]
That is extremely weird, because the choice and combobox controls are literally just wrapping the GTK `gtk_combo_box_*` widget and functions, so all that selection highlighting and cursor handling is being done inside the GTK widget. I don't see any code in the wx tree inside `gtk/choice.cpp` or `gtk/combobox.cpp` that retrieves/modifies/uses the cursor position.

**Comment by vadz** [comment]
But this is about `wxComboCtrl`, not `wxComboBox`. The latter is a native control but the former one is not, so it's not that surprising that it's broken, even if I have no idea why yet.

What I find weird is that it works under GNOME but not Plasma/Sway. Does it mean that there is a bug in some compositor implementation? And, if so, in which one, mutter (which unfortunately seems more probably judging from my personal experience with it) or the two other ones? FWIW I can confirm that I don't see the bug with GNOME -- and I have no idea how to test it with Sway as I believe the windows can't be resized with the mouse there anyhow?

**Comment by dsa-t** [comment]
Windows can be resized. Switch to floating mode:

> Mod + Shift + Space Toggle floating mode 

Also see for hotkeys: https://www.reddit.com/r/swaywm/comments/he9imx/what_are_the_keyboard_shortcuts_for_sway/

**Comment by dsa-t** [comment]
KDE Plasma uses KWin, GNOME uses Mutter compositor.

**Comment by imciner2** [comment]
> But this is about wxComboCtrl, not wxComboBox

Ah, missed there was a separate other owner-drawn one (I recall the wxOwnerDrawnComboBox, but not the ctrl).

@dsa-t can you dig into what is happening inside the event handlers for the control, such as `wxComboCtrlBase::OnPopupMouseEvent` handler? There is quite a bit of logic going on to prevent mouse events from doing stuff, so maybe there is some condition that isn't working properly for the KDE compositor.

**Comment by vadz** [comment]
> Mod + Shift + Space Toggle floating mode

Thanks, will try to check it later. When running Sway inside GNOME this shortcut doesn't work because it's used by GNOME itself for something else.

> KDE Plasma uses KWin, GNOME uses Mutter compositor.

Yes, but the question is which one of them is correct and which one is wrong. Or can they really both be correct if the behaviour is so different?

**Comment by dsa-t** [comment]
btw, a warning appears when it's shown:

>(combo:53409): Gdk-WARNING **: 18:12:20.204: Window 0x55b4acfe47b0 is already mapped at the time of grabbing. gdk_seat_grab() should be used to simultanously grab input and show this popup. You may find oddities ahead.

**Comment by dsa-t** [comment]
Uncommenting
```
gtk_window_set_type_hint( GTK_WINDOW(m_widget), GDK_WINDOW_TYPE_HINT_COMBO );
```
in `wxPopupWindow::Create` appears to fix the issue.

**Comment by dsa-t** [comment]
Not today. I assume Evolution would work properly with GDK_WINDOW_TYPE_HINT_COMBO.
It's strange that the setter was commented out in wx.

**Comment by dsa-t** [comment]
Commenting out all `GDK_WINDOW_TYPE_HINT_COMBO` setters in Evolution does not appear to break it in any way.

**Comment by vadz** [comment]
I'm very sorry, I should really take more time to process the new issues because I had completely misunderstood the situation, I thought that we did already use `GDK_WINDOW_TYPE_HINT_COMBO` and that _removing_ it fixed the problem while it's actually exactly the converse...

So I'd be perfectly fine with merging #23931 if you can confirm that it fixes the problem for you (I'm _almost_ sure it should, but I prefer to double check to avoid any more stupid mistakes).

Thanks for testing and sorry again!
