### ISSUE TITLE
wxAUI panels don't clip properly with Sonoma SDK/Xcode 15

### ISSUE THREAD

**Issue by dkulp** [wxWidgets/wxWidgets#23916]
When wxWidgets is built with the latest Xcode 15 and the Sonoma SDK it ships with, panels within wxAUI miniframes and other things are not clipped properly.    

It can be seen in the wxAUI sample by making the window smaller (or by adding more controls to the panel):
![image](https://github.com/wxWidgets/wxWidgets/assets/91569/aa116ce0-9588-49ad-840c-5ee07c68e7af)
The wxSpinCtrl is not clipped and is over the splitter.  

If you can get ahold of the 13.3 SDK and build with the --with-macosx-sdk= flag to point at the 13.3, then everything displays properly. 

### Platform and version information
- wxWidgets version you use: latest master code
- wxWidgets port  you use: wxOSX
- OS  and its version: Sonoma

**Comment by vadz** [comment]
I suspect this is not wxAUI-specific (at least I don't see any Mac-only code in it that could be responsible for this), but I have no idea what is this due to. Any ideas (or patches) are more than welcome...

**Comment by tonyvsuk** [comment]
I think this is exactly the same thing I'm seeing and reporting in the wx users mailing list.
https://groups.google.com/g/wx-users/c/rf9UfE5ah_o

Here is a patch (I think, I hope) that shows the clipping problem in the aui sample.
[mac_clipping_problem.patch](https://github.com/wxWidgets/wxWidgets/files/13326070/mac_clipping_problem.patch)

@dkulp, how did you get hold of the older SDK? I'm desperate to get this fixed as I've got users struggling with this.

Tony.

**Comment by dkulp** [comment]
@tonyvsuk I still had a Ventura machine with Xcode 14 installed so I grabbed the 13.3 SDK out of there.

**Comment by tonyvsuk** [comment]
I've got an "old" 2017 Mac Air (Monterry/Xcode 14), so hopefully that will work. Downloading Xcode 13.3 as I write this.

@dkulp Did you recompile your entire app with Xcode 13, or just wx? If it's just wx, that would be really handy for me. I usually build wx as a static library (but do intend to go to shared once this problem is out of the way).

**Comment by dkulp** [comment]
For my app, we use LTO and thus everything has to be compiled consistently or all kinds of warnings.   Thus, we do build everything with 13.3.  That said, once the SDK is added to Xcode (a symlink to a location elsewhere works) 
<img width="760" alt="Screenshot 2023-11-11 at 2 13 53 PM" src="https://github.com/wxWidgets/wxWidgets/assets/91569/c778a218-7059-47cb-8fef-4c8cf11bec53">
then it would appear as an option in Xcode and it's easy to select there.

**Comment by dkulp** [comment]
Actually, I read your message wrong....  We still compile with Xcode 15, but we use the MacOS13 SDK.   That works fine.

**Comment by tonyvsuk** [comment]
I understand (I think). Thanks, I'll try and do the same thing.

**Comment by csomor** [comment]
@tonyvsuk The SDK you link your app against is determining "backwards compatibility" modes the OS provides, libraries are not sufficient for this

thanks for the patch

**Comment by vadz** [comment]
It would be really nice to fix this before the next release but I have no idea where even to start looking for this...

**Comment by csomor** [comment]
yes, I'll try to find out what changed ...

**Comment by tonyvsuk** [comment]
Don't know if this helps.

wx3.1.5, MacOS 14.1, Xcode 15.0.1, things are OK in the debug build, release build shows the problem.

wx3.2.3, MacOS 14.1, Xcode 15.0.1, you see the issue in both debug and release builds.

Tony.

**Comment by csomor** [comment]
Ok, reproduced using XCode 15.0.1 running on Sonoma 14.1, Bug appears when linked against macOS 14 SDK and is not present when linked against macOS 13.3 SDK (from Xcode 14.3.1)

The reason is that under 14 SDK the `NSRect` passed into the `drawRect` method of the native `NSView` is not clipped anymore, I'll have to dig around to see whether this was mentioned somewhere in the changes

**Comment by csomor** [comment]
ok, found something

https://developer.apple.com/forums/thread/737838

**Comment by csomor** [comment]
@tonyvsuk @dkulp could you please test (you can also just copy 1 the line added into your sources) Thanks

**Comment by tonyvsuk** [comment]
I'll test within the next hour or so (I'm in front of the Mac right now trying to build with the 13.3 SDK).

Why would the default behaviour change like this? Seems crazy to me.

**Comment by tonyvsuk** [comment]
@csomor Working ok for me in both wx3.1.5 and wx3.2.3 for me.

Thank you so much for this. This has been causing me no end of stress.

**Comment by csomor** [comment]
They are preferring layer backed drawing, where basically a control has its own drawing canvas and the system does the compositing - so perhaps they are trying to have a better/faster integration of this and the 'backwards-compatible' 'windows calls drawRect' version ...
