### ISSUE TITLE
 wxLocale init return failed when i use wxLANGUAGE_CHINESE_CHINA

### ISSUE THREAD

**Issue by haha-wlei** [wxWidgets/wxWidgets#23911]
### I got failed result when i use the following code：
          
    auto pLocale = std::make_unique<wxLocale>();
    wxLogNull log;
    bool res = pLocale->Init(wxLANGUAGE_CHINESE_CHINA);
    std::cout<<"locales Init is "<< res<<std::endl;

### Platform and version information

- wxWidgets version :3.2.1
- wxWidgets port : Macos 10.15
- OS :macOS 10.15.6 (19G73)

**Comment by oneeyeman1** [comment]
@haha-wlei , what language is your Mac? Can you try to use wxUILocale?

**Comment by haha-wlei** [comment]
> @haha-wlei , what language is your Mac? Can you try to use wxUILocale?

I set chinese Simplified on my mac； and I have read some code from intl.cpp, i found that the init function finally use two function, one is setlocale which success retrun ,another is wxUILocale::UseLocaleName(shortName) that return false and leads to the INIT method returning false

**Comment by vadz** [comment]
Please check the latest 3.2 branch from Git, there have been several fixes to locale issues under macOS since 3.2.1 (#23114, #23269, #23454, #23557 and I probably forget more).

So I'm pretty sure this was fixed since 3.2.1, but please reopen if you still see it with the latest 3.2.

**Comment by haha-wlei** [comment]
I found that the issues still exists , I set chinese Simplified on my mac； and I have read some code from intl.cpp, i found that the init function finally use two function, one is setlocale which success retrun ,another is wxUILocale::UseLocaleName(shortName) that return false and leads to the INIT method returning false

**Comment by haha-wlei** [comment]
> Please check the latest 3.2 branch from Git, there have been several fixes to locale issues under macOS since 3.2.1 (#23114, #23269, #23454, #23557 and I probably forget more).
> 
> So I'm pretty sure this was fixed since 3.2.1, but please reopen if you still see it with the latest 3.2.

I found that the issues still exists , I set chinese Simplified on my mac； and I have read some code from intl.cpp, i found that the init function finally use two function, one is setlocale which success retrun ,another is wxUILocale::UseLocaleName(shortName) that return false and leads to the INIT method returning false
