### ISSUE TITLE
我想在其他地方调用窗口控件,于是我把窗口写成了单例模式,但是关闭程序,就会报错,卡在    node = wxPendingDelete.GetFirst();

### ISSUE THREAD

**Issue by chuncai111** [wxWidgets/wxWidgets#23933]
VMQ.exe 已触发了一个断点。

0x76FA6C43 (ntdll.dll)处(位于 VMQ.exe 中)引发的异常: 0xC0000374: 堆已损坏。 (参数: 0x76FE3960)。
0x76FA6C43 (ntdll.dll) (VMQ.exe 中)处有未经处理的异常: 0xC0000374: 堆已损坏。 (参数: 0x76FE3960)。

找不到原因,我只是打开窗口,关闭窗口,没有任何操作,就会报错,不能写成单例模式吗?

怎么才能在其他地方访问窗口的控件呢?

**Comment by asmwarrior** [comment]
Hi, you should wrote your issue in English, so that people around the world  can help you.

Another suggestion is that you should tell use how to reproduce this error, such as a minimal sample code should be supplied, and the steps to reproduce the error.
