### ISSUE TITLE
Parent item in wxDataViewCtrl not showing string data

### ISSUE THREAD

**Issue by UnknownStrain** [wxWidgets/wxWidgets#23934]
### Description
wxDataViewCtrl is not showing parent items properly. For example, there is space for the parent item, expand/collapse button is also there, but, the text/other value type is not visible. With vscode cpptools debugger, I have found that GetValue method is asking for wierd columns and sometimes not even calling the GetValue method for the parent items. Class derived from wxDataViewModel is ok. The dataview sample also running the same issue. This occured when I used the 3.2.1 version. But later I used 3.1.5, and it works without any issues.

### Platform and version information

- wxWidgets version 3.2.1
- wxWidgets port wxMSW
- OS  and its version: Windows 7, 32 bit

**Using visual studio 2019 debug build**

**Comment by vadz** [comment]
Sorry, please describe the problem you see in the dataview sample more precisely as I see nothing obviously wrong in it.

**Comment by oneeyeman1** [comment]
@UnknownStrain ,
The best would be to post a screenshot of the problem as your description is a little vague.

**Comment by UnknownStrain** [comment]
Ok, so I tried to the same, but however, when I changed back from 3.1.5 to 3.2.2.1, the problem was fixed somehow. I feel like there was mixing of headers which caused the problem. Sorry for any discrepancies caused.
