### ISSUE TITLE
wxLocale init return false when i use wxLANGUAGE_CHINESE_CHINA

### ISSUE THREAD

**Issue by haha-wlei** [wxWidgets/wxWidgets#23946]
### I got false  result when i use the following code：

    auto pLocale = std::make_unique<wxLocale>();
    bool res = pLocale->Init(wxLANGUAGE_CHINESE_CHINA);
    std::cout<<"locales Init is "<< res<<std::endl;

and I have read some code from intl.cpp, i found that the init function finally use two function, one is setlocale which success retrun ,another is wxUILocale::UseLocaleName(shortName) that return false and leads to the INIT method returning false
### Platform and version information
+ wxWidgets version :3.2.1
+ wxWidgets port : Macos 10.15
+ OS :macOS 10.15.6 (19G73)

**Comment by vadz** [comment]
You put "3.2.1" as your wxWidgets version but, as already mentioned in #23911, this was a known bug in previous wx 3.2 releases. Please retest with the latest 3.2 branch (which will become 3.2.3 very soon), notably with a44f72fb2f (Fix creating Chinese locales under macOS, 2023-05-19) applied.

**Comment by haha-wlei** [comment]
> You put "3.2.1" as your wxWidgets version but, as already mentioned in #23911, this was a known bug in previous wx 3.2 releases. Please retest with the latest 3.2 branch (which will become 3.2.3 very soon), notably with [a44f72f](https://github.com/wxWidgets/wxWidgets/commit/a44f72fb2ffb6a9dec8a8af8e41e8a174ea5e632) (Fix creating Chinese locales under macOS, 2023-05-19) applied.

I have tried the latest 3.2.3 and the issue does not exists，

**Comment by haha-wlei** [comment]
I have tried the latest 3.2.3 and the issue does not exists，and i think you can close this issue
