### ISSUE TITLE
configure in MSYS2 fails

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#23951]
Disclaimer: I am not familiar with _configure_, I ran into the issue when investigating another issue reported on wxForum, so it may be something I am doing wrong.

I have installed MSYS2 and two group packages:
[mingw-w64-ucrt-x86_64-toolchain](https://packages.msys2.org/groups/mingw-w64-ucrt-x86_64-toolchain) (GCC 13.2.0)
[mingw-w64-clang-x86_64-toolchain](https://packages.msys2.org/groups/mingw-w64-clang-x86_64-toolchain) (clang 17.0.1)

I launched clang64.exe from the MSYS2 root folder, in the MSYS2 shell changed to the build folder and ran `../configure --with-msw`

After a while, I got
```
config.status: creating libpcre2-8.pc
config.status: creating libpcre2-16.pc
config.status: creating libpcre2-32.pc
config.status: creating libpcre2-posix.pc
config.status: creating pcre2-config
config.status: creating src/pcre2.h
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: error: in `/d/Dev/Desktop/Lib/wxWidgets-PB/build-clang-multi/3rdparty/pcre':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
configure: error: ../../../3rdparty/pcre/configure failed for 3rdparty/pcre
```
I am not sure if it is related to the build error but I noticed that in the console there was (long before the error) also
```
checking for a working dd... ../../../3rdparty/pcre/configure: line 7133: cmp: command not found
../../../3rdparty/pcre/configure: line 7133: cmp: command not found
```
After adding `--disable-dependency-tracking` to the configure parameters, the configure finished successfully.

Exactly same problem shows when using the _ucrt64_ environment (i.e., with GCC). I tried other build configurations (e.g., static) but it had no effect.

[config.log](https://github.com/wxWidgets/wxWidgets/files/12840329/config.log)

**Comment by vadz** [comment]
Unfortunately `config.log` for the main configure doesn't contain any details about the failure in the sub-configure, which is probably found in `3rdparty/pcre/config.log`, but it does seem likely that it's due to `cmp` absence. And `cmp` itself is referenced by the libtool m4 macros expansion, so it's not going to be easy to avoid it -- and so the only solution seems to be to make sure it is available, by installing `diffutils` MSYS2 package (and documenting this requirement).

In addition to this, there is at least one other problem: files under `C:/msys64/clang64/include` seem to have DOS EOLs, which breaks all configure tests using them. I'm not sure how did this happen, but it needs to be fixed somehow, and not by us...

**Comment by PBfordev** [comment]
> Unfortunately `config.log` for the main configure doesn't contain any details about the failure in the sub-configure, which is probably found in `3rdparty/pcre/config.log`, but it does seem likely that it's due to `cmp` absence. And `cmp` itself is referenced by the libtool m4 macros expansion, so it's not going to be easy to avoid it -- and so the only solution seems to be to make sure it is available, by installing `diffutils` MSYS2 package (and documenting this requirement).

Sorry, I did not know that, here is the PCRE's [config.log](https://github.com/wxWidgets/wxWidgets/files/12843156/config.log).

It contains:
```
config.status:1196: creating src/config.h
config.status:1410: executing depfiles commands
config.status:1487: cd .       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
./config.status: line 1490: make: command not found
config.status:1492: $? = 127
config.status:1496: error: in `/d/Dev/Desktop/Lib/wxWidgets-PB/build-clang/3rdparty/pcre':
config.status:1498: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).

```
Installing `diffutils` package did not help, but installing `make` did. I don't know why make is not a part of clang or ucrt64 toolchain packages (only mingw32-make is), but I assume everyone who actually uses configure has make installed, so this is probably a non-issue?

**Comment by vadz** [comment]
Yes, I guess so, you're really supposed to have `make` if you use configure -- what's the point of generating a makefile if you can't use it?

It's somewhat surprising that `AC_PROG_MAKE_SET` (which we use in the main configure) doesn't fail in this case, but we could, in principle, check for make availability explicitly if we really wanted...

**Comment by PBfordev** [comment]
> Yes, I guess so, you're really supposed to have `make` if you use configure -- what's the point of generating a makefile if you can't use it?

I successfully used mingw32-make.exe with the configure-generated makefile, just as I do with bundled makefiles.

**Comment by vadz** [comment]
Ah, sorry, I didn't realize that it needed the "real" make, not just mingw32-make. I guess setting `MAKE=mingw32-make` would fix the problem too, wouldn't it?

**Comment by vadz** [comment]
Sorry, I meant just to do `export MAKE=mingw32-make.exe` in the shell before running configure.
