### ISSUE TITLE
wxString::ToCULong() fails for values exceeding LONG_MAX in C++17 mode

### ISSUE THREAD

**Issue by sodevel** [wxWidgets/wxWidgets#23957]
In C++17 mode, this method uses `std::from_chars()` but, according to the source code comment intentionally, passes a `long` reference instead of an `unsinged long` reference to that function. However, that function does actually range check the conversion result and returns an error if the string does exceed the value range of `long`.

A simple example to trigger the bug is to call `wxString("0xFFFFFFFF").ToCULong(ulPtr, 16)`.

**Comment by vadz** [comment]
Thanks for reporting, it definitely needs to be fixed. I am not sure what is the best way to do it, maybe we should try _both_ `std::from_chars<long>()` and `std::from_chars<unsigned long>()`?

**Comment by sodevel** [comment]
I'm not that familiar with the latest C++ additions, but while looking a bit ugly, using the signed variant if the unsigned variant failed seems to be the easiest way to support negative values as required by the method description.

**Comment by vadz** [comment]
Sorry, I've finally looked at this and realized I don't understand what the actual problem is. I thought `ToCULong()` didn't return the correct result when using C++17 but it does work for me, i.e. `wxString("0xFFFFFFFF").ToCULong(&ul, 16)` succeeds and puts `0xffffffff` into `ul`. Also, adding this to the test suite:

```diff
diff --git a/tests/strings/strings.cpp b/tests/strings/strings.cpp
index 30e6082406..b48799f6dc 100644
--- a/tests/strings/strings.cpp
+++ b/tests/strings/strings.cpp
@@ -607,6 +607,8 @@ static const struct ToLongData
     { wxT("0x11"), 17, Number_Ok,       0 },
     { wxT("0x11"),  0, Number_Invalid,  8 },
     { wxT("0x11"), 17, Number_Ok,      16 },
+
+    { wxT("0xFFFFFFFF"), 0xFFFFFFFF, Number_Unsigned | Number_Long },
 };
 
 wxGCC_WARNING_RESTORE(missing-field-initializers)
```

doesn't make it fail.

So what happens in your case? Do I misunderstand the problem or does the above fail for you? If so, which compiler/environment/etc are you using?

**Comment by sodevel** [comment]
The above fails for me, `&ul` does not get modified, in the debugger i see that the `std::from_chars()` call returns the error code `result_out_of_range`.

wxWidgets version: b87a7ab9e76ff5c8ee5e2e05f96432ff1d427bd7
wxWidgets port you use: wxMSW
OS and its version: Windows 10
Compiler: Microsoft Visual Studio 2022 17.5.5
Compiler target: x86
wxWidgets compiled like this: `cmake -S . -B "build\msw\cmake-%LIBRARY_TARGET%-debug_mswdll" -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="%LIBRARY_INSTALL_PREFIX%" -DwxBUILD_MONOLITHIC=OFF -DwxBUILD_SHARED=ON -DwxBUILD_VENDOR= -DwxBUILD_CXX_STANDARD=17 -DwxBUILD_COMPATIBILITY=3.2 -DwxUSE_UNSAFE_WXSTRING_CONV=OFF -DwxUSE_WINSOCK2=ON`

**Comment by vadz** [comment]
Sorry, this was stupid on my part, I should have tested under Windows where `sizeof(long)==4` and not Unix where it's 8 (and where the bug can still be reproduced but just using `0xffffffffffffffff`).

I'll make a PR with the fix soon.
