### ISSUE TITLE
msw: wxDataViewListCtrl column is not resized (3.2.2) 

### ISSUE THREAD

**Issue by basiliscos** [wxWidgets/wxWidgets#23969]
# Description

Column in wxDataViewListCtrl on Windows is wrongly sized: it's siz is not resized to fit content. On Linux it is correctly sized.

# Platform and version information

-  wxWidgets version 3.2.2
-  wxMSW 
- OS: Windows Server 2019 Standard

# code

```cpp
#include <wx/wx.h>
#include <wx/dataview.h>

class MyApp: public wxApp
{
public:
    virtual bool OnInit();
};

class MyFrame: public wxFrame
{
public:
    MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size);
};

wxIMPLEMENT_APP(MyApp);

bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame( "Hello World", wxPoint(50, 50), wxSize(450, 340) );
    frame->Show( true );

    return true;
}

MyFrame::MyFrame(const wxString& title, const wxPoint& pos, const wxSize& size)
    : wxFrame(NULL, wxID_ANY, title, pos, size)
{
    auto list = new wxDataViewListCtrl(this, wxID_ANY);

    list->AppendTextColumn(("Time"));
    list->AppendTextColumn(("Event"));

    wxVector<wxVariant> data;
    data.push_back( wxVariant("13.10.2023 18:30:00.000") );
    data.push_back( wxVariant("Find bug") );
    list->AppendItem( data );
}
```
 
![2023-10-16_10-29](https://github.com/wxWidgets/wxWidgets/assets/3630048/3749abbc-e629-4a7a-add7-9333fad065fe)
![2023-10-16_10-34](https://github.com/wxWidgets/wxWidgets/assets/3630048/316f0ae3-82d0-44c5-a26f-143dc51e26fd)

**Comment by PBfordev** [comment]
It seems you did not ask for the columns to be autosized, using default `wxCOL_WIDTH_DEFAULT` when calling `AppendTextColumn()`).

If the code is changed to
```cpp
list->AppendTextColumn("Time", wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE);
list->AppendTextColumn("Event", wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE);
```
then the column width is fitted to its content as expected.

AFAIK, GTK uses a native and MSW generic implementation of `wxDataViewCtrl`, so perhaps that is the reason of the different interpretation of `wxCOL_WIDTH_DEFAULT` between the two?

**Comment by basiliscos** [comment]
Thank you very much, problem seems solved. Anyway I'd expect the similar behaviour on different OSes )
