### ISSUE TITLE
[wxWebViewEdge] Disable data collection by default

### ISSUE THREAD

**Issue by rcane** [wxWidgets/wxWidgets#23978]
After reading the license of the fixed version WebView2 runtime and this [document](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/data-privacy) I realized that WebView2 is sending data to Microsoft by default. This is bad because it means that any application using WebView2 as-is must make its users aware of this data collection and request consent.

There are three kinds of data WebView2 collects and sends to MS:
* diagnostic data
* URLs are sent to MS to block malicious websites (SmartScreen)
* crash reports

The sending of the diagnostic data can be controlled by a global Windows setting. But the other two can only be set programmatically using the `ICoreWebView2Settings`  and `ICoreWebView2EnvironmentOptions3` interfaces.
Since there is no easy way to access those interfaces from client code I propose to disable the SmartScreen and crash reporting options by default and optionally allow client code to enable them again after asking the user.

**Comment by vadz** [comment]
I agree with disabling them by default, please consider making a PR doing this after testing that it actually works. TIA!

**Comment by mattfeest** [comment]
According to the documentation, "When IsCustomCrashReportingEnabled is set to true, Windows won't send crash data to Microsoft endpoint." This bugfix is setting it to false by default.

[https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.3296.44](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.3296.44)

**Comment by vadz** [comment]
This is very counterintuitive but the documentation indeed seems to indicate that the meaning of this field is contrary to what could be expected. @TcT2k Should we set it to `true` instead?

**Comment by TcT2k** [comment]
Well the documentation seems very clear. But I agree that its very counterintuitive.

**Comment by vadz** [comment]
I hoped that you might have some experience with how it actually works, but if not, let's indeed change this, thanks @mattfeest.
