### ISSUE TITLE
wxSearchCtrl::SetHint() generates an unnecessary assert in 3.3

### ISSUE THREAD

**Issue by Randalphwa** [wxWidgets/wxWidgets#23975]
### Description

Commit 4d76a87 changes srchctrl.h by adding the following:

```C++
#if defined(__WXMSW__) && !defined(__WXUNIVERSAL__)
    private:
        // implement this to return the HWND of the EDIT control
        // can return nullptr here as this TextEntry is just a proxy
        virtual WXHWND GetEditHWND() const override  { wxFAIL_MSG("unreachable"); return nullptr; }
#endif
```

On Windows in a Debug build, if you then call `wxSearchCtrl::SetHint("some text")` you hit the wxFAIL_MSG() assertion. Click continue and the hint is correctly set. That's because wxTextEntry::SetHint uses:

```C++
    if ( wxUxThemeIsActive() )
    {
        if ( ::SendMessage(GetEditHwnd(), EM_SETCUEBANNER,
                             TRUE, (LPARAM)(const wchar_t *)hint.wc_str()) )
            return true;
    }

    return wxTextEntryBase::SetHint(hint);
```

SendMessage will have returned FALSE because the window handle is a nullptr, but that just drops out and calls wxTextEntryBase::SetHint which works fine. All of which means that the assertion makes it _seem_ like you shouldn't call SetHint() under __WXMSW__, but in fact it works fine on 3.3 just as it did in 3.2 which didn't have the assertion. While I see the advantage of providing a virtual method to get the edit control, I don't see why it should generate an assertion dialog if it wasn't overridden.

Of course calling `::SendMessage` with a nullptr for a handle doesn't make sense, but you can't even check for a nullptr first without calling `GetEditHwnd()` which generates the assertion. I.e., without the assertion check, one could write:

```C++
    if ( wxUxThemeIsActive() )
    {
        if ( auto hwnd = GetEditHwnd(); hwnd && ::SendMessage(hwnd, EM_SETCUEBANNER,
                             TRUE, (LPARAM)(const wchar_t *)hint.wc_str()) )
            return true;
    }

    return wxTextEntryBase::SetHint(hint);
```

Or something like that -- I forget which c++ standard allowed that variation of an `if()` statement...

**Comment by vadz** [comment]
Thanks for reporting this!

I think the correct fix is the linked PR, please let me know if you see anything wrong with it.

cc @mcorino
