### ISSUE TITLE
wxAui: visual preview of drag/drop docking operations is hard to see on wxGTK and cannot be customized

### ISSUE THREAD

**Issue by craftyjon** [wxWidgets/wxWidgets#23987]
### Description

It would be great to have a graphical overlay showing the result of a pending dock operation (while the drag is still in process) like is done in some other implementations of AUI-style dockable panes.

If the minimization tab bar is implemented as described in #23986, drag-and-drop should also be used to allow reordering of the tabs, with overlay showing pending result as shown in the example video below (from JetBrains CLion):

![image3](https://github.com/wxWidgets/wxWidgets/assets/116737/518edc1e-20d4-4497-9e40-ae087512ec98)

**Comment by PBfordev** [comment]
I can't say I am familiar with wxAUI but there is a preview of the target area when dragging a window (at least on Windows), looking very similar to that in your screen recording?

It can be tested easily with the AUI sample, provided that in its Option menu, Transparent hint or Venetian blinds hint is set:
![wxaui-docking-preview2](https://github.com/wxWidgets/wxWidgets/assets/12495521/88cb1673-1458-45f1-aa64-1e6cc1255e48)


I can't see anything when Rectangle hint is selected there though.

What did I miss?

**Comment by vadz** [comment]
This is indeed already supposed to work. It doesn't under Wayland (but then AUI floating panes are completely broken there anyhow), but does work with X11 (which is what KiCad uses currently) for me, although the hint is barely visible and might be completely invisible in the dark mode you're using.

So, just to confirm: is this just about making the hint more visible under X11 or something else?

**Comment by craftyjon** [comment]
Indeed I never noticed that it was there but practically invisible in wxGTK! :facepalm: so it seems like maybe just some configurability of the appearance of these hints (especially on GTK) is what is missing?

**Comment by vadz** [comment]
I'll try to improve its appearance, I agree that it is difficult to see.

**Comment by vadz** [comment]
Sorry for the delay, it was a pretty trivial change but I wanted to test it under all 3 platforms (and in light/dark mode under all of them) and just finally did it, please see #24161 and please let me know if you like it better now. TIA!
