### ISSUE TITLE
wxTreeCtrlBase StateImageList needs to support wxBitmapBundle

### ISSUE THREAD

**Issue by craftyjon** [wxWidgets/wxWidgets#23993]
### Description

`wxTreeCtrlBase` inherits `wxWithImages`, which has been upgraded for `wxBitmapBundle`, but the "state" images added in the tree control have not, so it is not possible to set DPI-aware state images.  

Suggestion: basically duplicate the API enhancements done to `wxWithImages`.

### Platform and version information

- wxWidgets version  you use: 3.2.3
- wxWidgets port  you use: all
- OS  and its version: all

**Comment by vadz** [comment]
Yes, I ran out of time and couldn't finish this before 3.2.0 release. I'll do it, it shouldn't be exactly difficult, but I'm not sure it could be backported to 3.2 (without breaking the ABI constraints).

**Comment by vadz** [comment]
Please see the linked PR for the proposed solution. As I mentioned there, it would be great to have some presentable images in both 16x16 and 32x32 resolutions so that we could show that the correct version of them is actually used in the sample -- right now they're just being scaled. If you have any such images in KiCad that you could share with us, please don't hesitate to do so.

Also, this PR could be backported, with some not too big effort, to 3.2, if you need this functionality there. Do you?

**Comment by craftyjon** [comment]
I will check this out later today when I am free.  We can probably provide test images, I'll check on this.

> this PR could be backported, with some not too big effort, to 3.2, if you need this functionality there.

That would be great; I think this and #23994 are the last remaining known HiDPI issues we have in KiCad that are related to wxWidgets.

**Comment by craftyjon** [comment]
[checked_ok.zip](https://github.com/wxWidgets/wxWidgets/files/13169539/checked_ok.zip)

Here's an icon set for you, let me know if you need more.  These are licensed CC-BY-SA 4.0 and credited to Aleksandr Zyrianov.

**Comment by vadz** [comment]
Nice checked icon, thanks, but would you have the unchecked version too?

**Comment by craftyjon** [comment]
Well, this check is not from a checkbox widget so I don't have an "unchecked" version of it, but here are some more in case they are useful:

[more_icons.zip](https://github.com/wxWidgets/wxWidgets/files/13170835/more_icons.zip)

**Comment by vadz** [comment]
Thanks, I've added those as alternate state images.

I've also added `GetStateImageCount()` and `HasStateImages()` member functions for completeness.

Please let me know if you find any problems or see any further enhancements. TIA!
