### ISSUE TITLE
[Wayland] `wxGLCanvas` always repaints continuously since 3.2.3

### ISSUE THREAD

**Issue by joanbm** [wxWidgets/wxWidgets#24012]
Since wxWidgets 3.2.3 (in particular PR #23554 / commit 0ded71ff109daae2baa83cd8e835ec775649d32c), applications using `wxGLCanvas` on Wayland (i.e. using the EGL implementation) receive a continuous stream of `wxEVT_PAINT` events, apparently at the refresh rate of the display, even if the application is not requesting a refresh and the user is not interacting with the application.

This is generally harmless from the point of view of the application functioning correctly, but causes extra CPU usage for applications that do not need to update graphics continuously.

Example application to reproduce the problem:

```c++
#include <wx/app.h>
#include <wx/glcanvas.h>
#include <wx/dcclient.h>
#include <wx/frame.h>
#include <wx/stattext.h>
#include <wx/string.h>

class MyWxApp : public wxApp
{
public:
	bool OnInit() override {
		auto window = new wxFrame(nullptr, -1, wxT("Test"));
		auto counter = window->CreateStatusBar();
		auto canvas = new wxGLCanvas(window);
		auto context = new wxGLContext(canvas);
		canvas->Bind(wxEVT_PAINT, [this, canvas, context, counter](wxPaintEvent &evt) {
			fprintf(stderr, "Canvas paint\n");

			context->SetCurrent(*canvas);
			glClearColor(0.5f, 0.5f, 0.5f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT);
			canvas->SwapBuffers();

			static int frames = 0;
			counter->SetStatusText(wxString::Format(wxT("%d frames"), ++frames));
		});

		window->Layout();
		window->Show(true);
		SetTopWindow(window);
		return true;
	}
};

IMPLEMENT_APP(MyWxApp)
```

**Behaviour under wxWidgets 3.2.2.1:** The frame counter at the status bar is at a low value and is stable when no interactions are happening.
**Behaviour under wxWidgets 3.2.3:** The frame counter continuously increments.

**Comment by vadz** [comment]
Thanks, we need to fix it, of course. Would you have any idea about how to do it, preferably without breaking things fixed before, by chance?

**Comment by vadz** [comment]
I was sure it was due to

```cpp
    SendSizeEvent();
    gtk_widget_queue_draw(m_wxwindow);
```
in `wxGLCanvasEGL::OnWLFrameCallback()`, but this is _not_ the case, even removing these lines doesn't fix the issue (although it does break the repainting, of course).

Removing `wl_callback_add_listener(wl_frame_listener)` call does fix it, but if it's really just registering the listener which results in constant repainting, I don't see how can we fix this...

**Comment by joanbm** [comment]
I think the problem as introduced by PR https://github.com/wxWidgets/wxWidgets/pull/23554 / commit https://github.com/wxWidgets/wxWidgets/commit/0ded71ff109daae2baa83cd8e835ec775649d32c is easy to fix, the problem is that the callback it registers with `wl_callback_add_listener` internally sets `m_readyToDraw=true` and triggers a repaint, so it should be enough to instead register a callback that *only* sets `m_readyToDraw=true` but without triggering a repaint.

However #23998 can *also* cause a continuous repaint loop.

If we call `eglSwapInterval(display, 0)` correctly (see #24014), can we revert the changes inside `wxGLCanvas::SwapBuffers` from #23554 and #23998 without reintroducing the KiCad performance issue (#23512) or any other regression? I believe it should work, but I need to test it.
