### ISSUE TITLE
wx directories for Windows build not created

### ISSUE THREAD

**Issue by ultra-junkie** [wxWidgets/wxWidgets#24029]
### Description

During the first build, all directories have to be created under the lib folder. Until 3.2.2.1, only the wx folders under gcc_lib were missing. With 3.2.3, they are also not created under gcc_dll.

Following happens: the mswu and mswud folders are created if they don't exist. Then the makefile tries to copy steup.h into gcc_dll\mswud\wx (or one of the other subdirectories) which must fail because the destination doesn't exist.

Fix is simple and fast. Just add the following to the makefile:

if not exist ..\\..\lib\gcc_dll mkdir ..\\..\lib\gcc_dll
if not exist ..\\..\lib\gcc_dll\mswu mkdir ..\\..\lib\gcc_dll\mswu
if not exist ..\\..\lib\gcc_dll\mswud mkdir ..\\..\lib\gcc_dll\mswud
if not exist ..\\..\lib\gcc_dll\mswu\wx mkdir ..\\..\lib\gcc_dll\mswu\wx
if not exist ..\\..\lib\gcc_dll\mswud\wx mkdir ..\\..\lib\gcc_dll\mswud\wx

if not exist ..\\..\lib\gcc_lib mkdir ..\\..\lib\gcc_lib
if not exist ..\\..\lib\gcc_lib\mswu mkdir ..\\..\lib\gcc_lib\mswu
if not exist ..\\..\lib\gcc_lib\mswud mkdir ..\\..\lib\gcc_lib\mswud
if not exist ..\\..\lib\gcc_lib\mswu\wx mkdir ..\\..\lib\gcc_lib\mswu\wx
if not exist ..\\..\lib\gcc_lib\mswud\wx mkdir ..\\..\lib\gcc_lib\mswud\wx

### Platform and version information

- wxWidgets version  you are building: 3.2.3
- wxWidgets port  you are building: wxMSW:
- OS  and its version: Windows 11
- Compiler  being used: gcc 12.1

**Comment by vadz** [comment]
Unfortunately this is a well-known but not that simple to fix problem. It's already documented:

https://github.com/wxWidgets/wxWidgets/blob/abfdd186ff540e62d18ef3e3d37ce2015843309a/docs/msw/install.md?plain=1#L232-L237

Of course I realize that nobody reads the installation instructions, but this is the best we can do until #23249 is fixed, so I don't think it's useful to keep this one open.
