### ISSUE TITLE
Logging order mixed up when using threads

### ISSUE THREAD

**Issue by hwiesmann** [wxWidgets/wxWidgets#24025]
Suppose there is something like the following code:

`
activeThread = std::thread([]{wxLogger(wxLog_Debug,__FILE__,__LINE__,"lambda",wxLOG_COMPONENT).Log("Lambda");});
wxUsleep(10000);
wxLogger(wxLog_Debug,__FILE__,__LINE__,"main",wxLOG_COMPONENT).Log("Main");
`

As long as the nothing is going really strange the logging of "Lambda" is done before logging of "Main". Unfortunately, the output is "Main" and then "Lambda". The reason is that the output of "Lambda" is buffered but the output of "Main" is not.

When doing some debugging using logging, the output is not reliable with respect to the order of the log calls.

There are two solutions:
 a) whenever wxUSE_THREADS is set, the logged output should be buffered
 b) introduction of a flag indicating if output should be buffered or not (only taken into consideration when wxUSE_THREADS is set)

PS: I know that wxLogger is not officially released but it does not matter as the issue is inside wxLog::OnLog.

**Comment by vadz** [comment]
There is no defined order for the calls done in different threads and (not) using buffering is not going to change anything here. Besides, buffering is determined by the current log target and not `wxLog` itself, so you can already change it easily if you want to.

IOW I really don't think there is anything which needs to be changed here and IMO it's completely unwise to rely on the logs output order in any case, this is what the timestamps are for.
