### ISSUE TITLE
Last inserted Item in a wxListCtrl is not visible in wxMSW when using dark mode

### ISSUE THREAD

**Issue by rocrail** [wxWidgets/wxWidgets#24024]
Windows 11-64bit
wxWidgets 3.3.0 master

The last inserted item in a wxListCtrl is not visible but you can select it.
This is also the case if only one item is inserted.

This happens only in wxMSW dark mode.

**Comment by vadz** [comment]
Is this reproducible in the listctrl sample? You can run it with `wx_msw_dark_mode=2` in the environment to force it to use dark mode.

**Comment by rocrail** [comment]
Yes you can. The last item is not visible but you can select it and the events are listed but the item remains invisible.

**Comment by PBfordev** [comment]
FWIW, I can always reproduce this on my Windows 11 laptop (single screen, 125% DPI) but never on my Windows 10 desktop (primary screen 125% DPI, secondary 100% DPI). Both W10 and W11 are 22H2 release.

**Comment by vadz** [comment]
What exactly do I need to do in order to see this? I.e. could you please describe the exact sequence of actions which you use to select the last item? I've tried selecting it in a couple of different ways but I only see the correct behaviour, e.g.

![Screenshot from 2023-11-02 19-17-33](https://github.com/wxWidgets/wxWidgets/assets/146917/6a3f683f-79cd-4643-9348-2c862571e222)

(this is under Windows 10 at 200% DPI).

**Comment by rocrail** [comment]
Try to it under Windows 11.
It seems that this problem is not the case under Windows 10 as PBfordev wrote before.
I have only a Windows 11 PC for testing. (Most users have Windows 11...)

**Comment by PBfordev** [comment]
> Try it under Windows 11; Windows 10 is history. It seems that this problem is not the case under Windows 10 as PBfordev wrote before. I have only a Windows 11 PC for testing. (Most users have Windows 11...)

Despite Microsoft pushing Windows 11 very aggressively, Windows 10 is by far the dominant Windows version, with over 75% share. Windows 11 is still broken, including all those infamous taskbar regressions.

Anyway, on W11 I can just launch the unmodified listctrl sample and scroll down to see that the last item is not shown but is there (e.g., has reserved space and responds to input, i.e., the label can be edited).

**Comment by rocrail** [comment]
Testing with wxWidgets v3.2.3 all items are visible, so this is a v3.3.0 issue.

**Comment by cybercop23** [comment]
@vadz have you been able to replicate this in Win 11? Any idea on a potential fix?

**Comment by coolguymatt** [comment]
Is there an update on this?
