### ISSUE TITLE
wxTaskbarIcon not displaying specified tooltip in WXGTK3

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#24028]
### Description
With GTK3 and wxWidgets 3.2(.x) as well as 3.3 (master) the taskbar icon is not displaying the tooltip specified with SetIcon() but rather the app name as collected from the commandline.

This can be easily checked running the standard `taskbar` sample. For WXMSW and WXOSX this sample will display the tooltip as specified in the call to `SetIcon()` while for WXGTK3 (don't know about WXGTK2) it will only display "taskbar" (the basename of the executable).

### Platform and version information

- wxWidgets version : 3.2.x as well as master (3.3)
- wxWidgets port : WXGTK
- OS  and its version: OpenSuSE 15.5

+ GTK version:  3.24.34
+ Which GDK  backend is used: X11

**Comment by vadz** [comment]
Under Gnome 43 I don't have any taskbar support at all so I can't even test this.

And I don't know how useful is `wxTaskbarIcon` going to be under Linux if it's not supported under Gnome...

**Comment by imciner2** [comment]
> And I don't know how useful is wxTaskbarIcon going to be under Linux if it's not supported under Gnome...

From what I can tell, GTK has effectively removed all taskbar parts in GTK 4. The status icon functions used here are deprecated as of 3.14 https://docs.gtk.org/gtk3/method.StatusIcon.set_from_pixbuf.html, and from what I found there doesn't seem to be a coherent replacement system, e.g. this somewhat old discussion https://github.com/nicklan/pnmixer/issues/81.

**Comment by vadz** [comment]
Yes, I know it's deprecated in GTK, sorry for not making it clear. And I don't know what the replacement is neither, it's just to say that it seems pointless to spend any time on it knowing that it's basically dead anyhow.

**Comment by mcorino** [comment]
That's fine by me.
Just wanted to be sure it was a known issue.
Maybe best to clearly document though that this is a feature which is deprecated (and partly non-functional) under GTK3 because currently there is no indication in the wxWidgets docs of this fact.

**Comment by paulcor** [comment]
See #18081

**Comment by vadz** [comment]
Thanks Paul, I forgot that we already had an issue for this.

I'll document the current limitation and close this one.
