### ISSUE TITLE
Problem building an application for "Raspbian Buster 32bit"

### ISSUE THREAD

**Issue by rossanoparis** [wxWidgets/wxWidgets#24020]
### Description

Perhaps what I'm going to report is related to this old issue #22750
Using CMAKE to build wxWidgets works fine for all OSs with 64bit architecture.
I'm facing problems to build an application linked to wxWidgets library built on **Raspbian Buster** which has got **32bit architecture**.

This is the CMAKE command I use to build wxWidgets library for Raspbian Buster 32bit:
```
cmake -S$WXSRC -B$WXBLD -D"wxBUILD_TOOLKIT=gtk3" -D"CMAKE_BUILD_TYPE=Release" -D"BUILD_SHARED_LIBS=OFF"
-D"wxBUILD_USE_STATIC_RUNTIME=ON" -D"wxBUILD_OPTIMISE=ON" -D"wxBUILD_PRECOMP=ON" -D"wxUSE_STL=ON"
-D"wxUSE_OPENGL=ON" -D"wxUSE_SPELLCHECK=OFF" -D"wxUSE_DEBUGREPORT=ON" 
-D"wxUSE_ON_FATAL_EXCEPTION=ON" -D"wxUSE_LIBSDL=ON" -D"wxUSE_UNSAFE_WXSTRING_CONV=OFF" 
-D"wxUSE_ZLIB=builtin" -D"wxUSE_EXPAT=builtin" -D"wxUSE_LIBPNG=builtin" -D"wxUSE_LIBJPEG=builtin" 
-D"wxUSE_LIBTIFF=builtin" -D"wxUSE_NANOSVG=builtin" -D"wxUSE_REGEX=builtin" -D"wxBUILD_COMPATIBILITY=3.1" 
-D"wxBUILD_VENDOR="
```

wxWidgets library build process ends fine, but during my application building procedure I get the following error:
> /media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/include/wx/debug.h:447:62: note: in definition of macro 'wxCOMPILE_TIME_ASSERT'
>          struct wxMAKE_UNIQUE_ASSERT_NAME { unsigned int msg: expr; }
>                                                               ^~~~
> In file included from /media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/include/wx/defs.h:1002,
>                  from /media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/include/wx/wxprec.h:12,
>                  from ./../../sln/Connectors.Db.Sqlite/wx_pch.h:14,
>                  from <command-line>:
> /media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/include/wx/filefn.h:346:68: error: zero width for bit-field 'wxAssert_347::BadFileSizeType'
>          wxCOMPILE_TIME_ASSERT( sizeof(off_t) == sizeof(wxLongLong_t),
>                                                                     ^

I noticed that the file called ".../wx/setup.h" has been created like this:
```
/*
 * Define if large (64 bit file offsets) files are supported.
 */
#define HAVE_LARGEFILE_SUPPORT 1
```

I had to use `configure` in order to build a wxWidgets library able to be linked with an application for Rasbian Buster 32bit
`../../configure --disable-debug_flag --disable-shared --with-gtk=3 --disable-sys-libs --disable-compat30 --enable-backtrace --enable-debugreport --disable-unsafe_conv_in_wxstring --enable-stl --with-sdl --disable-spellcheck --disable-largefile`

Using `configure` the `setup.h` file has been generated like this
```
 * Define if large (64 bit file offsets) files are supported.
 */
/* #undef HAVE_LARGEFILE_SUPPORT */
```
With this option OFF I was able to build my application.

This is not a big deal, but my observation regarding this issue is related to CMAKE building process, which should take in consideration the OS architecture regarding HAVE_LARGEFILE_SUPPORT flag.
Couldn't this option `--disable-largefile ` be kept even for CMAKE ?

### Platform and version information

- wxWidgets version  you are building: 3.2.3
- wxWidgets port  you are building: wxGTK
- OS  and its version: Linux raspberrypi 5.10.103-v7l+ armv7l GNU/Linux
- Compiler  being used: gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

**Comment by MaartenBent** [comment]
CMake has a similar option: `wxBUILD_LARGEFILE_SUPPORT`.

Is your application built with large file support? It might need to use the same defines.
If you use `wx-config --cppflags` I think it should already include the `-D_FILE_OFFSET_BITS=64` define.

**Comment by rossanoparis** [comment]
Thank you @MaartenBent
 I'd try to use -D"wxBUILD_LARGEFILE_SUPPORT=OFF" to build wx on Rasbian buster 32bit ... I'll let you know about it

**Comment by rossanoparis** [comment]
Kind @MaartenBent using -D"wxBUILD_LARGEFILE_SUPPORT=OFF" to build wx libray on Rasbian buster 32bit permits a correct link between the library and applications.

Thank you for your help, I didn't notice the option wxBUILD_LARGEFILE_SUPPORT was present even using CMAKE

Do such an option be kept in the future ?

**Comment by MaartenBent** [comment]
Yes, this option will be kept.

I suppose this issue can be closed now?

**Comment by vadz** [comment]
I don't really understand the issue, it looks like large file support _is_ available on the target system, so why didn't the application compile in the first place? I.e. I understand that disabling it provides a workaround, but why is it needed? Is it just a problem in the application build system? If so, then this can be closed, of course, but I'm not really sure.

**Comment by rossanoparis** [comment]
I'm only able to tell that I build wxWidgets library using the following CMAKE command for Raspbian buster 64bit, Linux mint 19.3 64bit and Raspbian buster 32bit.

> cmake -S$WXSRC -B$WXBLD -D"wxBUILD_TOOLKIT=gtk3" -D"CMAKE_BUILD_TYPE=Release" -D"BUILD_SHARED_LIBS=OFF"
> -D"wxBUILD_USE_STATIC_RUNTIME=ON" -D"wxBUILD_OPTIMISE=ON" -D"wxBUILD_PRECOMP=ON" -D"wxUSE_STL=ON"
> -D"wxUSE_OPENGL=ON" -D"wxUSE_SPELLCHECK=OFF" -D"wxUSE_DEBUGREPORT=ON" 
> -D"wxUSE_ON_FATAL_EXCEPTION=ON" -D"wxUSE_LIBSDL=ON" -D"wxUSE_UNSAFE_WXSTRING_CONV=OFF" 
> -D"wxUSE_ZLIB=builtin" -D"wxUSE_EXPAT=builtin" -D"wxUSE_LIBPNG=builtin" -D"wxUSE_LIBJPEG=builtin" 
> -D"wxUSE_LIBTIFF=builtin" -D"wxUSE_NANOSVG=builtin" -D"wxUSE_REGEX=builtin" -D"wxBUILD_COMPATIBILITY=3.1" 
> -D"wxBUILD_VENDOR="

I had to add wxBUILD_LARGEFILE_SUPPORT=OFF only for Raspbian buster 32bit
I can add that I use CodeLite to build my application with three different set of environment variables ...

How could I help to investigate more this issue. is there something I should provide?

**Comment by vadz** [comment]
You need to check how do you build your application and whether you're using `wx-config --cxxflags` output. If you don't, this is a bug in your build system and this issue should be closed. If you do, then it could be a bug in wx.

**Comment by rossanoparis** [comment]
I buili wx library using this cmkae configuration

wx source folder: `export WXSRC='/media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3-src'`
wx installation folder: `export WXINST='/media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/lib/gtk3-sur-armv7l-buster'`
wx build folder: `export WXBLD='/tmp/build-wx'`

CMAKE command:
```
cmake -S$WXSRC -B$WXBLD -D"wxBUILD_TOOLKIT=gtk3" -D"CMAKE_BUILD_TYPE=Release" -D"BUILD_SHARED_LIBS=OFF" -D"wxBUILD_USE_STATIC_RUNTIME=ON" -D"wxBUILD_OPTIMISE=ON" -D"wxBUILD_PRECOMP=ON" -D"wxUSE_STL=ON" -D"wxUSE_OPENGL=ON" -D"wxUSE_SPELLCHECK=OFF" -D"wxUSE_DEBUGREPORT=ON" -D"wxUSE_ON_FATAL_EXCEPTION=ON" -D"wxUSE_LIBSDL=ON" -D"wxUSE_UNSAFE_WXSTRING_CONV=OFF" -D"wxUSE_ZLIB=builtin" -D"wxUSE_EXPAT=builtin" -D"wxUSE_LIBPNG=builtin" -D"wxUSE_LIBJPEG=builtin" -D"wxUSE_LIBTIFF=builtin" -D"wxUSE_NANOSVG=builtin" -D"wxUSE_REGEX=builtin" -D"wxBUILD_COMPATIBILITY=3.1" -D"wxBUILD_VENDOR="
```

build ok, this is the configuration log file: [config-log.zip](https://github.com/wxWidgets/wxWidgets/files/13235946/config-log.zip)

cxxflags:
```/media/pi/EXTDEVELOP/develop/wxw/wx/wxWidgets-3.2.3/lib/gtk3-sur-armv7l-buster/lib/wx/config/gtk3-unicode-static-3.2 --cxxflags```
```-I/usr/local/lib/wx/include/gtk3-unicode-static-3.2 -I/usr/local/include/wx-3.2 -D__WXGTK3__ -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -pthread```

I checked the include paths regarding my CODELITE settings, and they point to the right folders.
Despite this during building my application I get the errors reported on top of this thread.

**Comment by vadz** [comment]
If `-D_FILE_OFFSET_BITS=64` is used for the compilation, I really don't see how could `sizeof(off_t)` be different from 8.

Sorry, I think there is some problem here, but don't see what it is.

**Comment by MaartenBent** [comment]
Those flags look correct. But does your project also use them?

Is it manually configured in CodeLite? Then you should probably use something like `$(shell wx-config --cxxflags)` in the compiler options.

Or do you use CMake (with `FindwxWidgets` / `find_package(wxWidgets)`) to create your project? Then you should use `wxWidgets_CXX_FLAGS`, like
```cmake
target_compile_options(yourAppName PRIVATE ${wxWidgets_CXX_FLAGS})
```
(if you use `include(${wxWidgets_USE_FILE})` this is already done automatically).
(if you use `FindwxWidgets` in `CONFIG` mode this is not necessary, when you like to the wx-targets it will inherit the flags).

Note that `FindwxWidgets` uses `wx-config` internally, so make sure it uses the correct one.

**Comment by rossanoparis** [comment]
Kind @vadz and @MaartenBent, for sure the problem is inside my application build settings ...
I've been using wxWidgets since its version 2.8 and up to now I thought that including the right setup.h file was enought.
I use the same way based on including setup.h file, for MSW x64, MSW Arm64, Linux x64, Linux Arm64 and Linux Arm32
I never used a way like @MaartenBent is suggesting regarding a manual configuration of CodeLite ... I'll give it a try and I'll let you know.

**Comment by vadz** [comment]
OK, let's close this, please comment/let us know if you find anything wrong. But you definitely do need to use `wx-config --cxxflags` output when using wx.
