### ISSUE TITLE
On Mac Use CMake generate wx-config，wx-config compile c++ file fail to find the system head file

### ISSUE THREAD

**Issue by OpenRay** [wxWidgets/wxWidgets#24035]
### System Env
MacOS: Sonoma 14.1
Apple clang version: 15.0.0 (clang-1500.0.40.1) , Target: x86_64-apple-darwin23.1.0
CMake: V3.27.7
wxWidgets: tag: v3.2.2.1

### Workflow 
First, use cmake build & install the wxWidgets.
```
cd ~/source/wxWidgets
mkdir _build _install
cd _build
cmake .. -DCMAKE_INSTALL_PREFIX=~/source/wxWidgets/_install -DwxBUILD_SHARED=OFF
cmake --build . --target install
```

Then, the wx-config success to install the folder _install.
And, the sample of Dialog can execute successfully.

### Issues
Now, use the wx-config to compile main.cpp , fail to find the system head file

```
#include <cstdio>
int main()
{
    printf("Hello!\n");
    return 0;
}
```

the compile command is:
```
`wx-config --cxx` `wx-config --cxxflags` -o main -c main.cpp
```
the error log is:
```
main.cpp:1:10: fatal error: 'cstdio' file not found
```

by the way, use **configure** to build & install the wxWidgets, the above example can be successfully compiled.
```
../configure --prefix=~/source/wxWidgets/_install --disable-shared
make;make install
```

**Comment by vadz** [comment]
What is the output of `wx-config --cxx` and `wx-config --cxxflags` in your case and, especially because you've already ran both cmake and configure, could you please compare them and tell us how does it differ between them?

**Comment by OpenRay** [comment]
> What is the output of `wx-config --cxx` and `wx-config --cxxflags` in your case and, especially because you've already ran both cmake and configure, could you please compare them and tell us how does it differ between them?

sorry, some things delayed.


In cmake:
```
wx-config --cxx: /Library/Developer/CommandLineTools/usr/bin/c++
wx-confg --cxxflags: -I ~/source/wxWidgets/_install/lib/wx/include/osx_cocoa-unicode-static-3.2 -I ~/source/wxWidgets/_install/include/wx-3.2 -D__wxOSX_COCOA__ -D__WXMAC__ -D__WXOSX__ -pthread
```

In configure：
```
wx-config --cxx: g++ -std=gnu++11 -mmacosx-version-min=10.10
wx-confg --cxxflags: -I ~/source/wxWidgets/_install/lib/wx/include/osx_cocoa-unicode-static-3.2 -I ~/source/wxWidgets/_install/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA __
```

**Comment by vadz** [comment]
It looks like your command line tools installation is broken. I don't really know what can we do about it. As a workaround, you can tell CMake to use whatever `g++` resolves to (i.e. the output of `which g++`) because this compiler, probably from Xcode, seems to be working while the other one does not.

But this doesn't look like a wx problem to me, so closing.

**Comment by OpenRay** [comment]
> It looks like your command line tools installation is broken. I don't really know what can we do about it. As a workaround, you can tell CMake to use whatever `g++` resolves to (i.e. the output of `which g++`) because this compiler, probably from Xcode, seems to be working while the other one does not.
> 
> But this doesn't look like a wx problem to me, so closing.

Thank you for your response!
