### ISSUE TITLE
wxDirTraverser has sorted results on Windows, unsorted on Mac

### ISSUE THREAD

**Issue by furroy** [wxWidgets/wxWidgets#24047]
### Description
Describe the bug:
wxDirTraverser has sorted results on Windows, unsorted on Mac

Expected vs observed behaviour:
Expect to get the same results back in the same order on Windows vs Mac. While it is trivial to fix if you are just gathering a list of files, but if say you're building nested menus to match the file system, it's a hot mess.

### Platform and version information
wxPython-4.1.1\ext\wxWidgets\

**Comment by vadz** [comment]
`wxDirTraverser` doesn't do any sorting, if you get the paths in sorted order under Windows, they might just be in this order on disk but this class doesn't guarantee it at all. It's trivial to sort the paths in the application code but this shouldn't be done unconditionally because the cost of doing this can be non-negligible for large trees, so I really don't think anything needs to be done here at wx level.

**Comment by PBfordev** [comment]
I have just finished testing on Windows using `wxDir::GetAllFiles()` (which uses `wxDirTraverser` which uses Win32 API `Find{First|Next}File()`) as well as using `Find{First|Next}File()` directly.

To my surprise, the files were returned in the alphabetical order in both cases. I have always thought that the native API returns the files "unsorted" (depending on the filesystem driver), usually in the order the file entry was created in the directory (as stored in the filesystem). Its docs say
> The order in which the search returns the files, such as alphabetical order, is not guaranteed, and is dependent on the file system.

While files in many folders are created in the alphabetical order (e.g., when copied), I tested creating new files in existing directories yet the files were still returned (found) in the alphabetical order, just like the order was the same when using command line _dir_ with and without _/oN_.

**Comment by furroy** [comment]
My issue is with creating deep nested menus to match folder/files on disk. I guess I'll have to build up a tree structure on the fly during traversal, then sort my own tree, and then make the menus from that instead of making the nested menus inside the traverser.

**Comment by vadz** [comment]
Well, yes, you do have to do this, but someone has to do it and, as I said, I don't think wxWidgets should do this unconditionally.

PB: thanks for testing, I was wondering about whether Win32 API could be doing it too and it's good to have the confirmation that it does but, considering the language in MSDN we still can't rely on this being the case even under Windows.
