### ISSUE TITLE
Line spacing for wxTextAttr for a wxTextCtlr under MSW has no effect. Is this expected?

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#24045]
Line spacing for `wxTextAttr` for a `wxTextCtlr` under MSW has no effect.

### Description

I create a `wxTextCtrl` with RICH2 support, but when I apply a `wxTextAttr` with line spacing, the line spacing has no effect:

```
m_style.SetLineSpacing(wxTEXT_ATTR_LINE_SPACING_TWICE);
m_textEntry->SetDefaultStyle(m_style);
m_textEntry->SetStyle(0, m_textEntry->GetLastPosition(), m_style);
```

The docs don't mention this not being supported for `wxTextCtrl`, but I'm wondering if this is by design. Looking at "msw/textctrl.cpp," there is no mention of line spacing at all (just spacing before/after paragraphs, which is a different flag).

I believe `PARAFORMAT2::bLineSpacingRule` is the field to control this (https://learn.microsoft.com/en-us/windows/win32/api/richedit/ns-richedit-paraformat2). I would be happy to make a patch for this, but wanted to confirm that this isn't by design first.

### Platform and version information

- wxWidgets version 3.3
- wxMSW

**Comment by vadz** [comment]
No, this is definitely not by design, so adding support for it would be welcome.

It would be also nice to update the documentation to mention which attributes are supported where...

**Comment by Blake-Madden** [comment]
Fixed in referenced PR
