### ISSUE TITLE
wxSystemSettings::GetMetric() returns negative width of scrollbar

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24057]
With wxGTK3 on openSUSE Leap 15.5 with its default theme _**Breeze**_, `wxSystemSettings::GetMetric( wxSYS_VSCROLL_X )` returns a negative scrollbar width.

The reason is a large negative margin (-9 on both sides left and right) that makes the summed total value negative.

https://github.com/wxWidgets/wxWidgets/blob/945ee28afca15e75accec1f81c6463d649a10f85/src/gtk/settings.cpp#L966-L974

What would be the correct result?
- Should the margin only be included in the calculation of the scrollbar width if it is positive?
- Should the scrollbar width at least be the `"min-width"`?

A negative margin is also used by other themes (e.g. Adwaita). 

|                       | Breeze | Adwaita |
| -------------- | ------- | -------- |
| min-width             | 6      | 8       |
| border (left, right)  | 5, 5   | 4, 4    |
| padding (left, right) | 0, 0   | 0, 0    |
| margin (left, right)  | -9, -9 | -1, -1  |

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: openSUSE Leap 15.5

+ GTK version:  3.24.34
+ Which GDK  backend is used: X11
+ Current theme:  Breeze

**Comment by paulcor** [comment]
TBH I don't remember why the code does exactly what it does. It probably gives the right result for Adwaita, but is apparently not generally correct. I'll have to do some further investigation.

**Comment by vadz** [comment]
I remember that at least for `GtkEntry` using just padding + border but _not_ margins turned out to be correct, see 17b72d372f1b33bd8aec8dc6844b29389bff4732 (cc @dsa-t).

**Comment by taler21** [comment]
Great, thanks for the quick fix.

This improvement should also be backported to 3.2. TIA!
