### ISSUE TITLE
wxDropSource::GiveFeedback() is not called with GTK3

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24051]
This issue can be reproduced in the dataview sample using the **generic** `wxDataViewCtrl`.
To reproduce this issue in the dataview sample you would have to build wxWidgets using the `configure` option `--disable-nativedvc`.

With GTK2 an image of the dragged item is visible at the mouse pointer.
![dataview-sample-drag-GTK2](https://github.com/wxWidgets/wxWidgets/assets/99262969/de4bb0cb-1af7-40dd-aee9-4553f37561d0)

With GTK3 no image is visible because `wxDropSource::GiveFeedback()` is not called.
![dataview-sample-drag-GTK3](https://github.com/wxWidgets/wxWidgets/assets/99262969/5b6ccbc2-6a5c-4821-8b95-b0faa49ae4fb)

Note that this issue is not specific to the generic `wxDataViewCtrl`, but a general issue.
The generic `wxDataViewCtrl` is just a use case where the issue becomes visible in wxWidgets itself.

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: openSUSE Leap 15.5

+ GTK version:  3.24.34
+ Which GDK  backend is used: X11

**Comment by vadz** [comment]
This is supposed to be called from `configure-event` signal callback, so it looks like it's not generated but I have no idea why. Of course, it doesn't help that I can't reproduce the issue (the item is still drawn for me) with the same GTK version under Debian 12 (and it even works with both X11 and Wayland).

What DE does openSUSE use?

**Comment by taler21** [comment]
I use openSUSE with KDE desktop but I can reproduce the issue also on Ubuntu 22.04 with GNOME desktop (with both X11 and Wayland).

Did you really test with the **generic** `wxDataViewCtrl`?
As mentioned above, to reproduce this issue in the unmodified dataview sample, you need to build wxWidgets using the `configure` option `--disable-nativedvc`.

Thanks for looking at this issue!

**Comment by vadz** [comment]
Sorry, I did miss the part about this being only a problem in the generic version of class.

It would be nice to have an example showing the use of `GiveFeedback()` in `samples/dnd/dnd.cpp` to allow testing it without rebuilding the library with non-default options (and also because it would be good to demonstrate it somewhere).

**Comment by taler21** [comment]
I figured out that there already exists a sample where the issue can be reproduced with wxWidgets' default options.
Namely the **richtext sample**, because `wxRichTextDropSource` uses `GiveFeedback()` to display a caret while dragging.

Anyway, here is a patch for the **dnd sample**:

<details>
<summary>Patch for using GiveFeedback() in dnd sample</summary>

```patch
diff --git "a/samples/dnd/dnd.cpp" "b/samples/dnd/dnd.cpp"
index 1d3b4f11ea..f290620d2d 100644
--- "a/samples/dnd/dnd.cpp"
+++ "b/samples/dnd/dnd.cpp"
@@ -334,6 +334,7 @@ public:
 
     // to implement in derived classes
     virtual Kind GetKind() const = 0;
+    virtual DnDShape* Clone() const = 0;
 
     virtual void Draw(wxDC& dc)
     {
@@ -375,6 +376,12 @@ public:
     }
 
     virtual Kind GetKind() const override { return Triangle; }
+
+    virtual DnDTriangularShape* Clone() const override
+    {
+        return new DnDTriangularShape(*this);
+    }
+
     virtual void Draw(wxDC& dc) override
     {
         DnDShape::Draw(dc);
@@ -412,6 +419,12 @@ public:
     }
 
     virtual Kind GetKind() const override { return Rectangle; }
+
+    virtual DnDRectangularShape* Clone() const override
+    {
+        return new DnDRectangularShape(*this);
+    }
+
     virtual void Draw(wxDC& dc) override
     {
         DnDShape::Draw(dc);
@@ -448,6 +461,12 @@ public:
     }
 
     virtual Kind GetKind() const override { return Ellipse; }
+
+    virtual DnDEllipticShape* Clone() const override
+    {
+        return new DnDEllipticShape(*this);
+    }
+
     virtual void Draw(wxDC& dc) override
     {
         DnDShape::Draw(dc);
@@ -714,6 +733,11 @@ public:
         return wxFrame::SetShape( region );
     }
 
+    const DnDShape* GetShape() const
+    {
+        return m_shape;
+    }
+
     // callbacks
     void OnNewShape(wxCommandEvent& event);
     void OnEditShape(wxCommandEvent& event);
@@ -737,6 +761,101 @@ private:
     wxDECLARE_EVENT_TABLE();
 };
 
+// ----------------------------------------------------------------------------
+// A canvas for displaying a bitmap, used to display the dragged shape within a
+// shaped frame at the mouse position while dragging
+// ----------------------------------------------------------------------------
+
+class DnDShapeBitmapCanvas : public wxWindow
+{
+public:
+    DnDShapeBitmapCanvas( wxWindow *parent, const wxBitmap &bitmap ) :
+    wxWindow( parent, wxID_ANY, wxPoint(0, 0), bitmap.GetSize() )
+        , m_bitmap(bitmap)
+    {
+        Bind(wxEVT_PAINT, &DnDShapeBitmapCanvas::OnPaint, this);
+    }
+
+    void OnPaint( wxPaintEvent &WXUNUSED(event) )
+    {
+        wxPaintDC dc(this);
+        dc.DrawBitmap( m_bitmap, 0, 0 );
+    }
+
+    wxBitmap m_bitmap;
+};
+
+// ----------------------------------------------------------------------------
+// wxDropSource derivation for DnDShapes
+// ----------------------------------------------------------------------------
+
+class DnDShapeDropSource : public wxDropSource
+{
+public:
+    DnDShapeDropSource( DnDShapeDataObject& data, DnDShapeFrame *win ) :
+        wxDropSource( data, win )
+    {
+        m_win = win;
+        m_shape = win->GetShape()->Clone();
+        m_hint = nullptr;
+    }
+
+    ~DnDShapeDropSource()
+    {
+        delete m_shape;
+        delete m_hint;
+    }
+
+    virtual bool GiveFeedback( wxDragResult WXUNUSED(effect) ) override
+    {
+        wxPoint pos = wxGetMousePosition();
+
+        // To allow dragging into another application (instance), the hot spot
+        // of the mouse pointer must not be within the frame that displays the
+        // bitmap of the dragged shape.
+        pos += wxPoint(1, 1);
+
+        if (!m_hint)
+        {
+            m_shape->Move( wxPoint(0, 0) );
+
+            wxBitmap bitmap( m_shape->GetSize() );
+            wxMemoryDC dc;
+            dc.SelectObject( bitmap );
+            dc.SetBackground( *wxWHITE_BRUSH);
+            dc.Clear();
+            m_shape->Draw( dc );
+            dc.SelectObject( wxNullBitmap );
+
+            m_hint = new wxFrame( m_win, wxID_ANY, wxEmptyString,
+                                  wxPoint(pos.x, pos.y),
+                                  bitmap.GetSize(),
+                                  wxFRAME_TOOL_WINDOW |
+                                  wxFRAME_FLOAT_ON_PARENT |
+                                  wxFRAME_NO_TASKBAR |
+                                  wxFRAME_SHAPED |
+                                  wxNO_BORDER );
+            new DnDShapeBitmapCanvas( m_hint, bitmap );
+            m_hint->SetShape( wxRegion( bitmap, *wxWHITE ) );
+            m_hint->Show();
+        }
+        else
+        {
+            m_hint->Move( pos.x, pos.y );
+            m_hint->SetTransparent( 128 );
+
+            m_win->Refresh();
+        }
+
+        return false;
+    }
+
+private:
+    DnDShapeFrame  *m_win;
+    DnDShape       *m_shape;
+    wxFrame        *m_hint;
+};
+
 // ----------------------------------------------------------------------------
 // wxDropTarget derivation for DnDShapes
 // ----------------------------------------------------------------------------
@@ -1796,7 +1915,7 @@ void DnDShapeFrame::OnDrag(wxMouseEvent& event)
 
     // start drag operation
     DnDShapeDataObject shapeData(m_shape);
-    wxDropSource source(shapeData, this);
+    DnDShapeDropSource source(shapeData, this);
 
     wxString msg;
     switch ( source.DoDragDrop(true) )

```
</details>


### To reproduce the issue:
1. Start the dnd sample.
2. Click on 'File' > 'New frame' or press `Ctrl+N` to open a 'Shape frame' window.
3. Click on 'Shape' > 'New default shape' or press `Ctrl+S` to create a shape.
4. Drag the shape.

   With GTK2 it works correct and you will see the dragged object at the mouse pointer.
  ![dnd-shape-GTK2](https://github.com/wxWidgets/wxWidgets/assets/99262969/23ae5993-dab7-4c8d-a881-846d0c1db909)

   But not with GTK3 because `wxDropSource::GiveFeedback()` is not called there.

   Note that with GTK3 there also seems to be an issue with `wxDC::FloodFill()` filling the entire client area and not just the shape.
   For this reason, I commented out the `FloodFill()` call when creating the screenshot.
   ![dnd-shape-GTK3](https://github.com/wxWidgets/wxWidgets/assets/99262969/7a80f9f8-12a9-45fb-aea8-55f9ad006154)

**Comment by taler21** [comment]
Many thanks for these fixes!

I still have a problem or a question.

I am showing the following `wxFrame` via `wxDropSource::GiveFeedback()` at the mouse pointer position while dragging.
The generic `wxDataViewCtrl` does this in exactly the same way.

```cpp
    m_hint = new wxFrame( m_win, wxID_ANY, wxEmptyString,
                          wxPoint(pos.x, pos.y),
                          bitmap.GetSize(),
                          wxFRAME_TOOL_WINDOW |
                          wxFRAME_FLOAT_ON_PARENT |
                          wxFRAME_NO_TASKBAR |
                          wxFRAME_SHAPED |
                          wxNO_BORDER );
    new DnDShapeBitmapCanvas( m_hint, bitmap );
    m_hint->SetShape( wxRegion( bitmap, *wxWHITE ) );
    m_hint->Show();
```

This works well with GTK3 and X11.

![Shape-Frame-Dragging-X11](https://github.com/wxWidgets/wxWidgets/assets/99262969/21753bb1-d077-4f38-b089-398a473f2a61)

But with GTK3 and **Wayland** the position of the `wxFrame` is wrong and cannot be changed via `Move()`.

![Shape-Frame-Dragging-Wayland](https://github.com/wxWidgets/wxWidgets/assets/99262969/bbd3c8a2-de43-4c76-8da5-8e9380409e05)

I know that positioning a TLW is not possible under Wayland.
But is every `wxFrame` a TLW, even one with **`wxFRAME_TOOL_WINDOW`** style?

If so, is there any alternative that works on every platform?

**Comment by paulcor** [comment]
Positioning/moving TLWs under Wayland is an unsolved problem.
