### ISSUE TITLE
it won't compile with samples on. error: ‘FromSVGFile’ is not a member of ‘wxBitmapBundle’.

### ISSUE THREAD

**Issue by ferdna** [wxWidgets/wxWidgets#24068]
building in slackware current 5.18.3 using cmake 3.23.2, It happens in latest wxWidgets stable and master branches. It fails basically everything with "FromSVGFile". I cloned repository with --recursive.

```
/tmp/SBo/wxWidgets-3.2.4/samples/html/about/about.cpp: In member function ‘void MyFrame::OnAbout(wxCommandEvent&)’:
/tmp/SBo/wxWidgets-3.2.4/samples/html/about/about.cpp:154:52: error: ‘FromSVGFile’ is not a member of ‘wxBitmapBundle’
  154 |     html -> SetHTMLBackgroundImage(wxBitmapBundle::FromSVGFile("data/bg.svg", wxSize(65, 45)));


/tmp/SBo/wxWidgets-3.2.4/samples/wizard/wizard.cpp: In constructor ‘wxValidationPage::wxValidationPage(wxWizard*)’:
/tmp/SBo/wxWidgets-3.2.4/samples/wizard/wizard.cpp:122:36: error: ‘FromSVGFile’ is not a member of ‘wxBitmapBundle’
  122 |         m_bitmap = wxBitmapBundle::FromSVGFile("wiztest2.svg", wxSize(116, 260));
      |                                    ^~~~~~~~~~~
/tmp/SBo/wxWidgets-3.2.4/samples/wizard/wizard.cpp: In constructor ‘MyWizard::MyWizard(wxFrame*, bool)’:
/tmp/SBo/wxWidgets-3.2.4/samples/wizard/wizard.cpp:383:36: error: ‘FromSVGFile’ is not a member of ‘wxBitmapBundle’
  383 |                    wxBitmapBundle::FromSVGFile("wiztest.svg", wxSize(116, 260)),
```

**Comment by vadz** [comment]
Please read the bug reporting guidelines and in particular show your full CMake command line and (the relevant parts of) its output. This will probably explain why you don't have SVG support in your build.

**Comment by ferdna** [comment]
sorry for not following the guidelines. I compiled with nanosvg and it works perfect. However not with my systems svg library.

https://packages.slackware.com/?r=slackware-current&p=librsvg-2.56.4-i586-1.txz

here is the actual cmake line:
cmake -B build-gtk3 \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DwxBUILD_TOOLKIT=gtk3 \
    -DwxBUILD_DEMOS=ALL \
    -DwxBUILD_SAMPLES=ALL \
    -DwxUSE_OPENGL=ON \
    -DwxUSE_REGEX=sys\
    -DwxUSE_ZLIB=sys \
    -DwxUSE_EXPAT=sys \
    -DwxUSE_LIBJPEG=sys \
    -DwxUSE_LIBPNG=sys \
    -DwxUSE_LIBTIFF=sys \
    -DwxUSE_LIBLZMA=sys \
    -DwxUSE_LIBMSPACK=ON \
    -DwxUSE_IPC=ON \
    -DwxUSE_STREAMS=ON \
    -DwxUSE_TARSTREAM=ON \
    -DwxUSE_NANOSVG=OFF \
    -DwxUSE_SVG=sys \
    -DwxUSE_STL=$stl \
    -DwxUSE_WEBVIEW_WEBKIT=OFF\
    -DwxUSE_PRIVATE_FONTS=ON \
    -DCMAKE_BUILD_TYPE=Release .
cmake --build build-gtk3 -j8

**Comment by vadz** [comment]
If you use `wxUSE_NANOSVG=OFF` you turn off SVG support, you need to set it to `sys` instead. `wxUSE_SVG` is about something completely different.
