### ISSUE TITLE
"Assert failure" triggered in "Checkbox" page of standard widgets sample

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#24074]
### Description

It is possible to trigger an Assert Failure in the "Checkbox" page standard widgets sample by doing the following:
1. start the sample
2. change to the Checkbox page
3. check "user-settable 3rd state"
4. put the checkbox in the third state (either by clicking it 3 times or clicking the "Put in 3rd state" button)
5. next click the "Uncheck it" button

This sequence seems to leave the checkbox in an invalid state which will result in the "Assert failure" if you next click the checkbox again.

I am not sure if this is a bug in the sample code or in the library code as the documentation is not really illuminating on how the checkbox is supposed to function when wxCheckBox::SetValue(false) is called for a user settable 3state button.

What is also unclear to me is whether there ought to be a distinct visual representation of the 3rd state.
Weirdly, changing the state from unchecked -> checked -> undetermined (either by clicking or by pressing the buttons) does not provide a third visual checkbox state BUT pressing "Uncheck it" when the checkbox is in the 'undetermined' 3rd state not only leaves the checkbox in the state that results in the assert failures but also displays the checkbox in a distinctly different visual state (showing a 3 dots instead of a check mark).

### Platform and version information

- wxWidgets version  you use: master (3.3.0)
- wxWidgets port  you use: wxGTK3
- OS  and its version: OpenSuSE 15.5
   
  + GTK version:  3.2.4
  + Which GDK  backend is used: X11
  + Desktop environment : KDE

**Comment by vadz** [comment]
I think this should also be backported, so labelling as such.

**Comment by mcorino** [comment]
I do not believe this to be the complete fix needed.

The fix above corrects the programmatic state change behavior of the 2-state `SetValue() ` method but leaves flaws in the 3-state `DoSet3StateValue()` and `gtk_checkbox_toggled_callback` .

Based on my own tests and the change above I surmise the correct 3-state combinations are:

-  CHECKED = active && !inconsistent
-  UNDETERMINED = !active && inconsistent
-  UNCHECKED = !active && !inconsistent

Based on this I created an additional patch in #24079.

With this patch I get exactly the behavior and visual representation I would expect for either programmatic or user driven (clicks) state changes.

**Comment by paulcor** [comment]
What behavior are you getting that is unexpected?

**Comment by mcorino** [comment]
It is actually simple logic.

From my earlier tests when I found the assert issue I noticed that 3-state checkboxes have a distinct 3rd visual representation (as I would have expected for a GUI element with 3 states): a square with 3 dots ('...').
The logical conclusion is that this should represent the UNDETERMINED state.
That visual representation turned up when the checkbox was put in the state that triggered the assert (see description above) looking at the code (before your change) I could deduce this must have been the `!active && inconsistent` state.

Looking at the code in `wxCheckBox::DoSet3StateValue`, which you left unchanged, it became clear this does not what it is expected to do. When this method was called with `wxCHK_UNDETERMINED` it would result in the state `active && inconsistent` which did not seem right and testing it also showed that the resulting visual representation was not the 'square with 3 dots' but the 'square with checkmark'.

Changing the code to:
```
    SetValue(state == wxCHK_CHECKED);
    gtk_toggle_button_set_inconsistent(GTK_TOGGLE_BUTTON(m_widgetCheckbox),
                                       state == wxCHK_UNDETERMINED);
```

results in a behavior that changes states and visual representations as follows:

- wxCHK_CHECKED => active && !inconsistent => square with checkmark
- wxCHK_UNCHECKED => !active && !inconsistent => empty square
- wxCHK_UNDETERMINED => !active && inconsistent => square with 3 dots

The changes to `gtk_checkbox_toggled_callback` are such to make the behavior on user clicks for a user-settable 3-state checkbox comply with the above.

**Comment by paulcor** [comment]
The 3rd state is shown whenever `inconsistent` is set, regardless of the value of `active`.
The code comments
https://github.com/wxWidgets/wxWidgets/blob/8ea22b5e92bf46add0b20059f6e39a938858ff97/src/gtk/checkbox.cpp#L44
clearly indicate the order was intended to be checked -> undetermined -> unchecked. This is also how wxMSW behaves.

**Comment by mcorino** [comment]
> The 3rd state is shown whenever `inconsistent` is set, regardless of the value of `active`. 

It most definitely does **NOT** (at least in my environment with GTK3 3.24).

When running the widgets sample's checkbox page **without** my changes this is shown when setting the 3rd state:
![incorrect-3rd-state](https://github.com/wxWidgets/wxWidgets/assets/230834/fc6a4a04-44bf-40b0-bceb-75760ce2bc9e)

and this is shown **with** my changes:
![correct-3rd-state](https://github.com/wxWidgets/wxWidgets/assets/230834/e1906e37-3267-411d-be3b-412f943ddc84)

How does it look like when you run the sample in your environment?

> The code comments
> 
> https://github.com/wxWidgets/wxWidgets/blob/8ea22b5e92bf46add0b20059f6e39a938858ff97/src/gtk/checkbox.cpp#L44
> 
> clearly indicate the order was intended to be checked -> undetermined -> unchecked. This is also how wxMSW behaves.

My changes still maintain this behavior. Only with the correct visual representations.

**Comment by paulcor** [comment]
> How does it look like when you run the sample in your environment?

It works properly for me. I can see in the GTK source code that it should work that way. Maybe the theme is somehow overriding it. Ugh.

**Comment by mcorino** [comment]
Are you also using GTK3?Personally I find it more logical for the combo '! active && inconsistent' to map to the UNDETERMINED state instead of 'active && inconsistent'.On 24 Nov 2023 18:56, paulcor ***@***.***> wrote:

How does it look like when you run the sample in your environment?

It works properly for me. I can see in the GTK source code that it should work that way. Maybe the theme is somehow overriding it. Ugh.

**Comment by mcorino** [comment]
> > How does it look like when you run the sample in your environment?
> 
> It works properly for me. I can see in the GTK source code that it should work that way. Maybe the theme is somehow overriding it. Ugh.

What code did you look at?

If I look at this code from 'gtkcheckbutton.c' (3.24 branch)

```
static void
gtk_check_button_update_node_state (GtkWidget *widget)
{
  GtkCheckButtonPrivate *priv = gtk_check_button_get_instance_private (GTK_CHECK_BUTTON (widget));
  GtkCssImageBuiltinType image_type;
  GtkStateFlags state;

  state = gtk_widget_get_state_flags (widget);

  /* XXX: This is somewhat awkward here, but there's no better
   * way to update the icon
   */
  if (state & GTK_STATE_FLAG_CHECKED)
    image_type = GTK_IS_RADIO_BUTTON (widget) ? GTK_CSS_IMAGE_BUILTIN_OPTION : GTK_CSS_IMAGE_BUILTIN_CHECK;
  else if (state & GTK_STATE_FLAG_INCONSISTENT)
    image_type = GTK_IS_RADIO_BUTTON (widget) ? GTK_CSS_IMAGE_BUILTIN_OPTION_INCONSISTENT : GTK_CSS_IMAGE_BUILTIN_CHECK_INCONSISTENT;
  else
    image_type = GTK_CSS_IMAGE_BUILTIN_NONE;
  gtk_builtin_icon_set_image (GTK_BUILTIN_ICON (priv->indicator_gadget), image_type);

  gtk_css_gadget_set_state (priv->indicator_gadget, state);
}
```

it sure looks like my assumption of the states was right. This code will only update for the inconsistent state if the checked state is OFF.

**Comment by mcorino** [comment]
> In both `gtk_css_image_builtin_draw_check()` and `gtk_do_render_check()` the `inconsistent` state takes precedence, so their handling of it is, umm, not consistent. 

Not necessarily. This would only matter in case we assume the correct setting combinations were: 

- '!active && !inconsistent'
- 'active && !inconsistent'
- 'active && inconsistent'

If however (as I feel is right) the correct setting combinations are:

- '!active && !inconsistent'
- 'active && !inconsistent'
- '!active && inconsistent'

the order in which 'active' and 'inconsistent' are checked does not matter and there is no inconsistency in the code.
