### ISSUE TITLE
wxWidgets not building due to wxGTK

### ISSUE THREAD

**Issue by Beijing-corn87** [wxWidgets/wxWidgets#24077]
### Build System Used

I build wxWidgets and/or my application using:

- [ ] CMake
- [x] configure
- [ ] mingw32-make with makefile.gcc
- [ ] MSBuild (Microsoft Visual Studio solution file)
- [ ] nmake with makefile.vc
- [ ] Xcode

### Description

When I was to install Amulet on my Pi it failed when building wxWidgets so i tried to install it using [this guide](https://wiki.wxpython.org/BuildWxPythonOnRaspberryPi) and it all went well (with pagkages not being found) until this command
`python3 build.py build bdist_wheel` it did its checks and when it comes to check that GTK version is >= 3.0.0 it says no and everything else falls from there. I dont have a log file cause i cant fiind one but i do have the command line output in a gist https://gist.github.com/Beijing-corn87/8cf2462cec518974528fa492a2078ff8

### Platform and version information

- wxWidgets version: 4.0.7
- wxWidgets port: wxGTK
- OS: Raspberry Pi Bookworm
- Compiler configure being used:
- Non-default compiler options, if any : none?

**Comment by imciner2** [comment]
Are you trying to build wxWidgets or wxPython Phoenix? Using build.py and the version number 4.0.7 sounds like the latter, which is better discussed at their issue tracker https://github.com/wxWidgets/Phoenix.

**Comment by vadz** [comment]
You need to check `config.log` file in the directory where configure ran, it will have the explanation for the problem. As this is due to not detecting GTK, and as it's clearly specific to your system, it really isn't a wxWidgets bug, so closing.

**Comment by Beijing-corn87** [comment]
I found the problem. wxGTK3 does not install automatically and there is no documentation on this (for the new version).
What I did was i ran
`$ apt search libgtk`
and i found the package
`libgtk-3-dev/oldstable,now 3.24.24-4+rpt12+deb11u3 arm64
  development files for the GTK library`
and installed the package 
`$ sudo apt install libgtk-3-dev`
and ran the config file and everything worked
(The people should update the docs too)
