### ISSUE TITLE
Remove Bakefiles

### ISSUE THREAD

**Issue by generic-pers0n** [wxWidgets/wxWidgets#24083]
### Description
Edit: Looks like I accidentally used the wrong template. This isn't a feature, really. I apologize for the inconvienence :(

wxWidgets uses many build systems, including CMake, autotools, and Bakefile to name a few. Maintaining several build systems can be challenging, especially with limited resources. Therefore, I find it important to consider what build systems are going to be maintained for wxWidgets.

As far as I can tell, Bakefile appears to be similar to CMake in that it generates platform-specific build files (e.g., Makefiles for Linux). While I have not read much into Bakefile, my guess is that it's extremely simpler than CMake. While this sounds like a selling point, I find an important problem. Bakefile has not seen a commit since 2022, which indicates dying activity. Furthermore, it appears that [Python 3 won't be supported unless someone contributes Python 3 support](https://github.com/vslavik/bakefile/issues/109#issuecomment-1594570649). Given the activity record, or lack thereof, I believe that Bakefile won't see Python 3 support anytime soon. Thus, with the lack of updates and maintenance, using Bakefile in the future might become more cumbersome. Therefore, I propose that wxWidgets should drop the Bakefile build system for 3.3.0.

Removing the Bakefile build system would help push wxWidgets forward as wxWidgets would no longer rely on a legacy build system, especially since wxWidgets uses the legacy Bakefile branch. Additionally, it can open the way to simplifying file addition to wxWidgets. Inevitably, files will be added to wxWidgets, and reducing the complexity of adding new files can help potential contributors as they wouldn't have to spend extra time setting up Bakefile.

My proposal comes as more than a suggestion. I'm willing, and quite desiring quite frankly, to put in the effort to remove all Bakefiles from wxWidgets. However, after a search of the source tree for the string "Bakefile", I realize that wxWidgets has different build systems generated from Bakefile. Therefore, I believe that there might be more of an impact if we remove Bakefile from wxWidgets. Alternatively, we could go even further and remove those build systems if desired, but I do not believe that we would go that far, especially as I'm not proposing to remove build systems other than Bakefile. Nevertheless, if we choose to go that far for any reason, I am willing to put the work.

**Comment by paulcor** [comment]
See #23249

**Comment by vadz** [comment]
The problem is not removing bakefile, it's replacing it with something else which preserves the simple ways of building wxWidgets (and no, CMake is not really that simple). E.g. we have tons of places where we tell people to just open a `.sln` file and build, or run `nmake -f makefile.vc` from command line. And, of course, we want to preserve `configure && make` way of building too.

I don't think it's useful to keep this one open, the ticket linked by Paul has more details/links about what needs to be done.
