### ISSUE TITLE
wxAuiNotebook broken tab visibility

### ISSUE THREAD

**Issue by bkerec** [wxWidgets/wxWidgets#24096]
When you add a new tab to wxAuiNotebook, the tab is selected and visible, but if you create a notebook with wxAUI_NB_CLOSE_ON_ALL_TABS the "visible" part of an action is not correct anymore. It's like that the X button is not taken into consideration when calculating the offset of a current tab to make sure that it is visible. The behavior is easily reproducible on auidemo.
Just use wxAUI_NB_CLOSE_ON_ALL_TABS  style and add a new tab on some button click. The more tabs are in notebook, the bigger the error.

**Comment by vadz** [comment]
I've created #24159 fixing this, please test it and let me know if you still see any problems (or any regressions).

**Comment by bkerec** [comment]
Fix failed. Create a bunch of tabs by spamming the following code (maybe 40 tabs) and eventually you will notice discrepancy.
`notebookCtrl->AddPage(new wxTextCtrl(notebookCtrl, wxID_ANY, "Some more text"), "wxTextCtrl 8", true);`
Buttons at the end (move right, drop down) are also not properly used in the offset calculation. Fix partially works when the window is in windowed state so make sure to check in maximized state.
Here you can see the result where in first case (windowed state) the tab is behind the buttons and in the second case (maximized window) the selected tab is not visible at all.
![tabs](https://github.com/wxWidgets/wxWidgets/assets/127097097/9ac9338c-ff42-4baa-a752-ac6ba84ef485)

**Comment by vadz** [comment]
Could you please attach the diff with the changes to the sample you use to reproduce this? TIA!

**Comment by bkerec** [comment]
[auiTabIssue.zip](https://github.com/wxWidgets/wxWidgets/files/13830904/auiTabIssue.zip)

**Comment by vadz** [comment]
Thanks for the patch, but I can't reproduce the problem using it. I got tired of pressing the mouse so many times, so I've mapped the new page addition to `F1` instead:

```diff
diff --git a/samples/aui/auidemo.cpp b/samples/aui/auidemo.cpp
index f8fd21cca1..9f78e56258 100644
--- a/samples/aui/auidemo.cpp
+++ b/samples/aui/auidemo.cpp
@@ -173,6 +173,7 @@ private:
     wxMenu* m_perspectives_menu;
     long m_notebook_style;
     long m_notebook_theme;
+    wxAuiNotebook* notebookCtrl;
 
     wxDECLARE_EVENT_TABLE();
 };
@@ -676,7 +677,7 @@ MyFrame::MyFrame(wxWindow* parent,
     SetIcon(wxIcon(sample_xpm));
 
     // set up default notebook style
-    m_notebook_style = wxAUI_NB_DEFAULT_STYLE | wxAUI_NB_TAB_EXTERNAL_MOVE | wxNO_BORDER;
+    m_notebook_style = wxAUI_NB_DEFAULT_STYLE | wxAUI_NB_TAB_EXTERNAL_MOVE | wxNO_BORDER | wxAUI_NB_CLOSE_ON_ALL_TABS;
     m_notebook_theme = 0;
 
     // create menu
@@ -753,7 +754,7 @@ MyFrame::MyFrame(wxWindow* parent,
     m_perspectives_menu->Append(ID_FirstPerspective+1, _("All Panes"));
 
     wxMenu* help_menu = new wxMenu;
-    help_menu->Append(wxID_ABOUT);
+    help_menu->Append(wxID_ABOUT, "Test\tF1");
 
     mb->Append(file_menu, _("&File"));
     mb->Append(view_menu, _("&View"));
@@ -1589,6 +1590,9 @@ void MyFrame::OnExit(wxCommandEvent& WXUNUSED(event))
 
 void MyFrame::OnAbout(wxCommandEvent& WXUNUSED(event))
 {
+    static int s_page = 8;
+    notebookCtrl->AddPage(new wxTextCtrl(notebookCtrl, wxID_ANY, "Some more text"), wxString::Format("wxTextCtrl %d", s_page++), true);
+    return;
     wxMessageBox(_("wxAUI Demo\nAn advanced window management library for wxWidgets\n(c) Copyright 2005-2006, Kirix Corporation"), _("About wxAUI Demo"), wxOK, this);
 }
 
@@ -1691,6 +1695,7 @@ wxAuiNotebook* MyFrame::CreateNotebook()
                                     m_notebook_style);
    ctrl->Freeze();
 
+   notebookCtrl = ctrl;
    wxBitmapBundle page_bmp = wxArtProvider::GetBitmapBundle(wxART_NORMAL_FILE, wxART_OTHER, wxSize(16,16));
 
    ctrl->AddPage(CreateHTMLCtrl(ctrl), "Welcome to wxAUI" , false, page_bmp);
```

and I got up to 200 tabs, with maximized window, without ever seeing the problem.

Are you sure you have the commit from the PR applied?

If yes, what platform do you test under and is there anything else particular to your environment?

**Comment by bkerec** [comment]
Sorry for the confusion. It was my bad since git decided to check out master instead of your branch and I didn't realize that before. Fix is now confirmed.
