### ISSUE TITLE
`wxGauge` is not created with the specified height (GTK3)

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24107]
### Description

With GTK3, a `wxGauge` is not created with the height specified via its constructor, but much thinner.

This can be reproduced in the widgets sample with the following modifications:

```patch
diff --git "a/samples/widgets/gauge.cpp" "b/samples/widgets/gauge.cpp"
index d8a247784d..18e11c9baa 100644
--- "a/samples/widgets/gauge.cpp"
+++ "b/samples/widgets/gauge.cpp"
@@ -248,7 +248,8 @@ void GaugeWidgetsPage::CreateContent()
 
     // right pane
     wxSizer *sizerRight = new wxBoxSizer(wxHORIZONTAL);
-    m_gauge = new wxGauge(this, GaugePage_Gauge, m_range);
+    m_gauge = new wxGauge(this, GaugePage_Gauge, m_range,
+                          wxDefaultPosition, FromDIP(wxSize(-1, 25)));
     sizerRight->Add(m_gauge, 1, wxCENTRE | wxALL, 5);
     sizerRight->SetMinSize(150, 0);
     m_sizerGauge = sizerRight; // save it to modify it later

```

With **GTK2** the `wxGauge` is created correctly with the specified height.

![gauge-gtk2](https://github.com/wxWidgets/wxWidgets/assets/99262969/de935116-201f-4317-bb3d-fa04583930d2)

But with **GTK3** it is created much thinner.

![gauge-gtk3](https://github.com/wxWidgets/wxWidgets/assets/99262969/3c382628-f250-422b-b157-ce8362ac82ed)

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: Ubuntu 22.04
  
  + GTK version: 3.24.33
  + Which GDK  backend is used: X11
  + Desktop environment : Gnome
  + Current theme:  Yaru

**Comment by paulcor** [comment]
In theory, the `min-width`/`min-height` CSS properties could be used to get the indicator to be drawn thicker.

**Comment by taler21** [comment]
Thanks for the hint.

I have now tried the following modifications:

```patch
diff --git "a/src/gtk/gauge.cpp" "b/src/gtk/gauge.cpp"
index 52c8690ff0..735803d8f5 100644
--- "a/src/gtk/gauge.cpp"
+++ "b/src/gtk/gauge.cpp"
@@ -50,6 +50,19 @@ bool wxGauge::Create( wxWindow *parent,
 #endif
     }
 
+#ifdef __WXGTK3__
+    // If a size is explicitly specified, we set it as the minimum size
+    // so that the indicator does not appear thinner.
+    wxString sizeStyle;
+    if ( style & wxGA_VERTICAL && size.x != wxDefaultCoord )
+        sizeStyle = wxString::Format("*{ min-width:%dpx }", size.x);
+    else if ( size.y != wxDefaultCoord )
+        sizeStyle = wxString::Format("*{ min-height:%dpx }", size.y);
+
+    if ( !sizeStyle.IsEmpty() )
+        GTKApplyCssStyle( sizeStyle.c_str() );
+#endif
+
     // when using the gauge in indeterminate mode, we need this:
     gtk_progress_bar_set_pulse_step(GTK_PROGRESS_BAR (m_widget), 0.05);
 

```

Indeed, that seems to work as intended.

![gauge-gtk3_modified](https://github.com/wxWidgets/wxWidgets/assets/99262969/27a0bcaf-0957-4742-ac2c-e6230bce145a)

However, I don't know if my changes to fix this issue are completely correct.
So please review them carefully. TIA!
