### ISSUE TITLE
wxHeaderCtrl  and wxSimpleHeaderCtrl broken, multiple assertions in widgets sample

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#24108]
#### Bug description:

The current implementation of wxHeaderCtrl and wxSimpleHeaderCtrl do not conform to documentation and when used as advertised can cause assertions and failing functionality. This currently happens in the standard widgets sample.

The documentation for wxHeaderCtrl describes two protected virtual methods that  (according to docs) must be overridden in derived classes if called (which will be the case if column reordering and/or hiding is allowed): 

- `virtual void UpdateColumnVisibility(unsigned int idx, bool show)`
- `virtual void UpdateColumnsOrder(const wxArrayInt &order)`

The first problem here is that the documentation states that an override of `UpdateColumnVisibility` does not need to call `UpdateColum()` as that would be done by default by the library code. This is incorrect. The current implementation of wxHeaderCtrl does no such thing. This causes failures to refresh the displayed header when hiding/showing  columns through the popup menu/dialog.

The next problem lies with the default implementation of these methods in wxHeaderCtrl and the missing overrides of those methods in wxSimpleHeaderCtrl.
The default implementations in wxHeaderCtrl trigger assertions to warn the developer that overrides are required. Since wxSimpleHeaderCtrl lacks these overrides using this class underived (as is advertised in the docs and which the standard widgets sample does) will lead to assertions when attempting to reorder or hide columns through the popup menu/dialog.

Reordering through header column dragging does not suffer from this issue as the `UpdateColumnsOrder` is not called in this case. This is another inconsistency which would force a developer to implement either multiple methods to handle associated data changes (above mentioned callbacks and event handling) or forego the callbacks and use event handling only.
The latter would however currently require providing empty overrides for the callbacks as otherwise the assertions will still be triggered for certain user actions.

I am not sure what the best way to fix this would be.
It is clear at least wxSimpleHeaderCtrl needs updates to be usable without derivatives which is it's advertised use.
The changes to this are relatively straight forward as far as fixing suppressing the assertions and the missing trigger for column refreshing (UpdateColumn()) is concerned.
This will however leave the inconsistency between reordering through popup and dragging.
On the one hand the option of handling associated data control changes through the callbacks is an easy way for simple use cases but it always will require using derivatives.
On the other hand the option of handling the same through event handling is more generic and should probably be preferred. In this case It would be best to deprecate the callbacks (possibly marked for internal use only as wxGridHeaderCtrl actually uses them). The assertions should than be removed from the base (so developers of derived classes can ignore them but still keeping backward compatibility) and the implementation of wxSimpleHeaderCtrl updated to reflect this.

#### To Reproduce:

The assertions can be reproduced from the standard widget sample:

1. start sample
2. activate HeaderCtrl page
3. check 'Allow hide' alongside 'Allow reorder'
4. popup the context menu on the header control
5. select a column to hide

Alternatively:

1. start sample
2. activate HeaderCtrl page
3. check 'Allow hide' alongside 'Allow reorder'
4. popup the context menu on the header control
5. choose 'Customize ...'
6. reorder the columns in the dialog
7. select 'Ok'

Checking 'Allow hide' is necessary because otherwise the popup menu and dialog cannot be triggered. Without 'Allow hide' the only way to reorder is dragging which does not trigger an assertion.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE 15.5
  
  + GTK version:  3.24
  + Which GDK  backend is used: X11
  + Desktop environment : KDE

**Comment by mcorino** [comment]
@vadz Could you maybe have a short look at this if you have some time?

**Comment by vadz** [comment]
I don't, but I'll try...

**Comment by mcorino** [comment]
Just need your 2 cts input. I'm willing to make the changes.

**Comment by vadz** [comment]
Thanks for looking at this!

1. I agree that the comment/docs about not needing to call `UpdateColumn()` from `UpdateColumnVisibility()` is wrong/misleading. It was probably supposed to say that it needs to do whatever is necessary to update the display, which may (but, in theory, might not?) include calling `UpdateColumn()`. But I also think that we could always just call `UpdateColumn()` from `wxHeaderCtrlBase` code ourselves, as I don't see how could this ever result in any problems and then this comment would be made retroactively correct.
2. The simplest way to fix `wxHeaderCtrlSimple` would be to forbid reordering/toggling columns in it interactively (maybe by asserting that `wxHD_ALLOW_HIDE` is not used with it), but I agree that implementing support for doing this would be even better. It looks like it ought to be relatively easy to do it, so if you can do the latter, it would, of course, be very welcome -- TIA!
3. Events vs callbacks: we can't really use the existing `wxEVT_HEADER_END_REORDER` for reordering columns in arbitrary order, as possible through the dialog (we'd have to decompose an arbitrary permutation into transpositions which is doable, of course, but is not how anybody would want this to work), so to replace the callback we'd need to add a new event, and personally I don't think it's worth it. What I think we should do is to call `UpdateColumnsOrder()` from `wxHeaderCtrl::EndReordering()` if the event was not processed, to let people to only override this function if they don't care about the extra details provided by the event. What do you think?

**Comment by mcorino** [comment]
> 
>     1. I agree that the comment/docs about not needing to call `UpdateColumn()` from `UpdateColumnVisibility()` is wrong/misleading. It was probably supposed to say that it needs to do whatever is necessary to update the display, which may (but, in theory, might not?) include calling `UpdateColumn()`. But I also think that we could always just call `UpdateColumn()` from `wxHeaderCtrlBase` code ourselves, as I don't see how could this ever result in any problems and then this comment would be made retroactively correct.

Ok, let's do that.

> 
>     2. The simplest way to fix `wxHeaderCtrlSimple` would be to forbid reordering/toggling columns in it interactively (maybe by asserting that `wxHD_ALLOW_HIDE` is not used with it), but I agree that implementing support for doing this would be even better. It looks like it ought to be relatively easy to do it, so if you can do the latter, it would, of course, be very welcome -- TIA!

I will make the changes to `wxHeaderCtrlSimple` to override the asserts.

> 
>     3. Events vs callbacks: we can't really use the existing `wxEVT_HEADER_END_REORDER` for reordering columns in arbitrary order, as possible through the dialog (we'd have to decompose an arbitrary permutation into transpositions which is doable, of course, but is not how anybody would want this to work), so to replace the callback we'd need to add a new event, and personally I don't think it's worth it. What I think we should do is to call `UpdateColumnsOrder()` from `wxHeaderCtrl::EndReordering()` if the event was not processed, to let people to only override this function if they don't care about the extra details provided by the event. What do you think?

Yes, I think this could work (even on MSW with some more changes). I'll look into it.
