### ISSUE TITLE
wxQt: button state looks odd

### ISSUE THREAD

**Issue by davidkaroly** [wxWidgets/wxWidgets#24129]
#### Bug description:

In wxQt, Button state is reported as State_Current when it should be State_Normal i.e. not hovering.

This also results in 'empty buttons' e.g. in the life demo program as the bitmap is not refreshed.

#### Expected vs observed behaviour:

* Bitmap button e.g. in the widgets sample show hover mode instead of  normal mode bitmap.
* Life demo program should show a navigation mini-window with arrow buttons. However, it shows empty buttons.

#### Stack trace:

n/a, no crash

#### Patch or snippet allowing to reproduce the problem:

Build demos and samples with wxQt.

Run demos/life/life. Navigation mini-window shows empty buttons.

Run samples/widgets/widgets.
* Select widget: Button, Set style: Bitmap only. Sample button shows up in hover state even though it should show normal state when we're not hovering.
* Select widget: EditableListbox, Set style: Allow new items, Allow editing items, Allow deleting items. Some of the little buttons on the top right side of the editable list box show up empty.

### Platform and version information

- wxWidgets version: latest master
- wxWidgets port: wxQt (on Wayland)
- OS version: Fedora 39

I've seen similar behavior on previous versions of Fedora as well as on Haiku (just to mention something completely different, which does not rely on Wayland)

### Note:

Commenting out `hasMouseTracking` in `wxAnyButton::QtGetCurrentState()` gives me much better results:

```diff
diff --git a/src/qt/anybutton.cpp b/src/qt/anybutton.cpp
index c1d9e77ce7..fa62660dc4 100644
--- a/src/qt/anybutton.cpp
+++ b/src/qt/anybutton.cpp
@@ -158,7 +158,7 @@ wxAnyButton::State wxAnyButton::QtGetCurrentState() const
         return State_Pressed;
     }
 
-    if ( HasCapture() || m_qtPushButton->hasMouseTracking() || m_qtPushButton->underMouse() )
+    if ( HasCapture() /* || m_qtPushButton->hasMouseTracking() */ || m_qtPushButton->underMouse() )
     {
         return State_Current;
     }
```

![image](https://github.com/wxWidgets/wxWidgets/assets/92124087/3e4bf979-5dd3-4aac-9828-750073b48275)

![image](https://github.com/wxWidgets/wxWidgets/assets/92124087/3e402a4a-a6be-476b-8403-6dd086d22c3b)

**Comment by vadz** [comment]
Sorry, I'm not sure why it was done like this, @catalinr would you remember anything about that PR by chance? I'd expect `hasMouseTracking()` to be the same as `HasCapture()`, but apparently this is not the case?

Also cc'ing @AliKet who is the de facto wxQt maintainer.

**Comment by AliKet** [comment]
AFAICT, testing for `m_qtPushButton->hasMouseTracking()` is not needed because we have mouse tracking enabled by default (and hence the test will always be true) for any widget derived from `wxQtEventSignalHandler` at this line: https://github.com/wxWidgets/wxWidgets/blob/5ef4c1062a74ec31f9ae5f0701d5bc5d7ec716e3/include/wx/qt/private/winevent.h#L97-L99

Mouse tracking needs to be enabled in order to generate `wxEVT_MOTION` events because **Qt** emits mouse move events ONLY IF a mouse button is pressed while the mouse is being moved if mouse tracking is off.  `wxWidgets` doesn't require this.
(see https://doc.qt.io/qt-6/qwidget.html#mouseMoveEvent)

So the patch above looks good to me and should be applied.

Regards.

**Comment by catalinr** [comment]
Unfortunately I don't remember anything about it. I probably thought that `hasMouseTracking()` and `HasCapture()` were the same, and they were at most redundant. But indeed they are not, and the use of `hasMouseTracking()` there looks wrong.

**Comment by davidkaroly** [comment]
thank you all for the clarification, therefore I'll prepare a PR for this issue
