### ISSUE TITLE
wxPropertyGridManager crash when calling 'SetExtraStyle( someFlags | wxPG_EX_INIT_NOCAT)' on a grid with expanded categories (regression from 3.1.4 to 3.2.2.1 (and still in 3.2.4))

### ISSUE THREAD

**Issue by StefanBattmer** [wxWidgets/wxWidgets#24145]
#### Bug description:

When calling

`wxPropertyGridManager::SetExtraStyle(wxPropertyGridManager::GetExtraStyle());`

on a property grid with an already expanded category the redraw function messes up the display and later a memory corruption will happen. This is due to the fact that by default the **wxPG_EX_INIT_NOCAT** flag is set and when this flag is set AND the tree is redrawn (caused by the 'SetExtraStyle' call) something is happening, that did not happen in wxWidgets 3.1.4.
[propgrid.patch](https://github.com/wxWidgets/wxWidgets/files/13705041/propgrid.patch)

#### Expected vs observed behaviour:

When the issue occurs the properties are no longer drawn properly. Only clicking on them causes a redraw. When closing the application / destroying the grid the application crashes with a memory corruption.

#### Patch or snippet allowing to reproduce the problem:

Please see attached patch for a modified version of wxWidgets-3.2.2.1/samples/propgrid/propgrid.cpp (only one line is different)

#### To Reproduce:

Simply patch the standard propgrid example with the attached patch. Only one line of code has been added:

`pgman->SetExtraStyle(pgman->GetExtraStyle()|wxPG_EX_INIT_NOCAT);`

Moving this line ABOVE the 
`PopulateGrid();`

call makes the issue disappear. When called AFTER 

`PopulateGrid();`

call crashes and incorrect redraw behaviour will occur. The reason for that is somewhere related to this code:

```
void wxPropertyGridPageState::InitNonCatMode()
{
    if ( !m_abcArray )
    {
        m_abcArray = new wxPGRootProperty(wxS("<Root_NonCat>"));
        m_abcArray->SetParentState(this);
        m_abcArray->SetFlag(wxPG_PROP_CHILDREN_ARE_COPIES);
    }

    // Must be called when state::m_properties still points to regularArray.
    wxPGProperty* oldProperties = m_properties;

    // Must use temp value in state::m_properties for item iteration loop
    // to run as expected.
    m_properties = &m_regularArray;

    if ( m_properties->GetChildCount() ) // <-- Stefan: This only gets executed when a category is already expanded and only then the bug can be seen!
    {
        //
        // Prepare m_abcArray
        wxPropertyGridIterator it( this, wxPG_ITERATE_PROPERTIES );

        for ( ; !it.AtEnd(); it.Next() )
        {
            wxPGProperty* p = it.GetProperty();
            wxPGProperty* parent = p->GetParent();
            if ( parent->IsCategory() || parent->IsRoot() )
            {
                m_abcArray->DoAddChild(p);
                p->m_parent = &m_regularArray;
            }
        }
    }

    m_properties = oldProperties;
}
```

### Platform and version information

- wxWidgets version 3.2.2.1 - 3.2.4 shows the behaviour, 3.1.4 did not (checked on Windows 10)

**Comment by vadz** [comment]
Thanks for reporting this!

I think the patch is just

```diff
diff --git a/samples/propgrid/propgrid.cpp b/samples/propgrid/propgrid.cpp
index a47e2801b2..7dbec786da 100644
--- a/samples/propgrid/propgrid.cpp
+++ b/samples/propgrid/propgrid.cpp
@@ -1922,6 +1922,8 @@ void FormMain::CreateGrid( int style, int extraStyle )
 
     PopulateGrid();
 
+    pgman->SetExtraStyle(pgman->GetExtraStyle()|wxPG_EX_INIT_NOCAT);
+
     m_propGrid->MakeColumnEditable(0, m_labelEditingEnabled);
     m_pPropGridManager->ShowHeader(m_hasHeader);
     if ( m_hasHeader )
```

but it's difficult to be sure with non-unified patches without context (which is why patches done with `diff -u` are preferred).

I don't know this code well, so I'm not sure what happens here, but if it's a crash due to memory corruption, it might be immediately obvious in ASAN-enabled build. Running `git bisect` between 3.1.4 and 3.2.2 to find the commit which broke this might also be useful.

**Comment by a-wi** [comment]
What is interesting I'm able to reproduce this issue with v3.1.4 too. The output is the same like for latest master:
![obraz](https://github.com/wxWidgets/wxWidgets/assets/7330332/f2285e06-f184-4483-ad99-df21e3ef43d3)

The problem indeed seems to have something to do with `wxPropertyGridPageState::InitNonCatMode()` - main suspect is `wxPropertyGridIterator` but it needs some investigations.
What is definitely needed is preventing from initializing alphabetic mode multiple times but this is not enough (however this helps with particular case reported):
```diff --git a/src/propgrid/propgrid.cpp b/src/propgrid/propgrid.cpp
--- a/src/propgrid/propgrid.cpp
+++ b/src/propgrid/propgrid.cpp
@@ -1145,7 +1145,7 @@ void wxPropertyGrid::SetExtraStyle( long exStyle )
 
     wxControl::SetExtraStyle( exStyle );
 
-    if ( exStyle & wxPG_EX_INIT_NOCAT )
+    if ( exStyle & wxPG_EX_INIT_NOCAT && !m_pState->m_abcArray )
         m_pState->InitNonCatMode();
 
     if ( exStyle & wxPG_EX_HELP_AS_TOOLTIPS )
```
