### ISSUE TITLE
Scroll bars are not visible on MacOS 

### ISSUE THREAD

**Issue by mahotz** [wxWidgets/wxWidgets#24151]
### Description

Scroll bars do not appear on MacOS application

#### Bug description:

After experiencing the same scroll artifacts issue resolved in #24067 I cloned and built libraries from the 3.2 branch. When testing my application, I noted the the problem solved by that issue was indeed fixed... however now the scroll bars do not appear at all. The space where the scroll bar should appear is visible, but empty. No bar, no slider, no buttons at either end. The underlying functionality is there, as the contents can be scrolled with two fingers dragging on the magic mouse, there is just no scroll bar visually.

#### Expected vs observed behaviour:

I would expect to see the scroll bar and be able to interact with it.

#### To Reproduce:

1. Checkout the 3.2 branch
2. Compile the libraries
3. Build the samples
4. Run the scroll sample
5. Shrink window to smallest size and observe space on the right side of both windows for the scroll bar, but no actual scroll bar
6. Scroll via mouse touch surface and see contents scroll as expected. Just no bar.

### Platform and version information
- wxWidgets version 3.2.5 (compiled 3.2 branch)
- wxWidgets port wxOSX
- OS MacOS Sonoma 14.2.1
- Xcode 15.1

**Comment by vadz** [comment]
Sorry, no idea what's going on here. Is it the same on master?

cc'ing @csomor just in case you missed it

**Comment by csomor** [comment]
@vadz thanks for the notice, yes, could you please test with master, and indicate whether you are using dark mode.

**Comment by BrutalSoloH** [comment]
I tested the master and it is showing the scrollbars BUT the 3.2 branch is NOT showing scrollbars.

**Comment by csomor** [comment]
@mahotz could you please retest with master ?

**Comment by BrutalSoloH** [comment]
@csomor I compiled against the master (3.3) and now the scrollbars are NOT visible anymore.. So now both master and 3.2 branch have invisible scrollbars.

**Comment by csomor** [comment]
@BrutalSoloH thanks, what is the appearance visibility of the scrollbars on your system ?

https://support.apple.com/guide/mac-help/mchlp1225/mac 

could you post screenshots of the window in its original and its smaller size ?

**Comment by BrutalSoloH** [comment]
Here are 2 screenshots. One with both scrollbars "visible" and 1 with only the vertical "visible". You can see that there is room reserved for the scrollbar to be drawn. If I resize the window, this room will appear or disappear
when scrollbars should appear.

The appearance is set to 'always'. But even if I trie the other settings, the wxWidgets windows and lists behave as if set to alway on. So even when set on "when scrolling", it will make room for the scrollbars to be drawn, if not scrolling at all.

<img width="743" alt="Screenshot 2024-03-03 at 08 54 22" src="https://github.com/wxWidgets/wxWidgets/assets/32673704/822364a2-3156-4fee-b6b6-7f4600b662d3">
<img width="531" alt="Screenshot 2024-03-03 at 08 54 05" src="https://github.com/wxWidgets/wxWidgets/assets/32673704/62eb308f-dd61-4e8d-b249-e347ef90676d">

**Comment by csomor** [comment]
@BrutalSoloH thanks a lot, but I see this is from your application. "Always" is the same settings as I have.

OP described this from the scroll sample. Could you please give me hints on how to reproduce this using the scroll sample. I need this to properly debug things. 

Also: could you please try with light appearance as well ? the rendering on the OS-side unfortunately is not the same for both modes .

**Comment by BrutalSoloH** [comment]
I am sorry, I made a huge mistake... I compiled against the wrong version...

Now compiled against the master and scrollbars ARE visible....

**Comment by csomor** [comment]
> I am sorry, I made a huge mistake... I compiled against the wrong version...
> 
> Now compiled against the master and scrollbars ARE visible....

Oh, ok, then things align perfectly, thanks a lot :-)
