### ISSUE TITLE
`DateValidator::Validate` doesn't understand ISO8601

### ISSUE THREAD

**Issue by b1f6c1c4** [wxWidgets/wxWidgets#24173]
#### Bug description:

`DateValidator::Validate` rejects the date picker's output.
![shot-2023-12-30_01-32-54](https://github.com/wxWidgets/wxWidgets/assets/9152961/26f3ca49-cdc3-4e76-9425-9681b20fbb75)

I was using KiCad (which uses wxWidgets-gtk3) and came across a form with a date picker inside. The date picker was pre-filled with a date value, and was formatted according to my locale (which dictates `yyyy-MM-dd`, the ISO8601 format.) However, when I tried to submit the form, I the above error message showed up (likely from `DateValidator::Validate`,) preventing me from submitting the form.

Changing the date to any other date doesn't solve the problem, as the date picker always formats the date to ISO8601 format, cannot (https://github.com/wxWidgets/wxWidgets/blame/master/src/generic/datectlg.cpp#L83)

I uploaded my ISO8601 locale file as a [gist](https://gist.github.com/b1f6c1c4/bf079c770bc08d074d5910d00dc7f96e).

An obvious workaround is to invoke `LC_ALL=en_US.UTF-8 kicad` but *I do NOT feel comfortable* dealing with any date format other than ISO8601.

#### Expected vs observed behaviour:

Expected:
- ISO8601 inputs should always be accepted.
- If not, the program should accurately inform the user of what inputs will be accepted.
- Date generated by the date picker should always be acceptable by validator.

Observed bahviour:
- ISO8601 are not accepted.
- Validator's error message tells me to use ISO8601, which will be rejected anyhow.
- The date picker generats ISO8601, which will be rejected by the validator.

### Platform and version information

- KiCad 7.0.10
- wxWidgets version you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: Arch Linux
  
  + GTK version:   GTK+ 3.24
  + Which GDK  backend is used: X11
  + Desktop environment : Enlightenment
  + Current theme:

**Comment by vadz** [comment]
Thanks for reporting it!

I'll look at this, as someone who always uses ISO8601 myself I'm really disappointed that this doesn't work.

**Comment by vadz** [comment]
I think this is "just" due to not recognizing the "new" (C99) `%F` format specifier, i.e. this should already work in your version if you use `%Y-%m-%d` in the locale file, but I've also created the linked PR which adds support for `%F` and should fix this for you.

Could you please test it? TIA!

**Comment by vadz** [comment]
No feedback since 2 weeks, so I'm going to assume that this does work.
