### ISSUE TITLE
What is the real status of WxQt?

### ISSUE THREAD

**Issue by malix0** [wxWidgets/wxWidgets#24181]
### Description
Looking at Git, there are several developments on the Qt folder recently, but wiki pages are really outdated
https://wiki.wxwidgets.org/WxQt
especially this
https://wiki.wxwidgets.org/WxQt/Status

It is possible to have a more updated situation?

**Comment by vadz** [comment]
Community wiki is maintained by the community, so please update these pages if you can. AFAIK the port mostly works fine but there are, of course, some problems (as in all the other ports too).

Also please don't use the issue tracker for the questions, please post to the mailing list or the forum instead.
