### ISSUE TITLE
Cell editors no longer appear in wxGrid (macOS)

### ISSUE THREAD

**Issue by dkulp** [wxWidgets/wxWidgets#24201]
#### Bug description:

With the changes introduced in bcbc31e97f246564e4b19ea2d060ae859c302b44 , the grid cell editors no longer appear when editing cells in a wxGrid on OSX.    This can easily be shown with the grid sample.    Trying to edit any cell will display the text "Cell editor shown.", but the editor never appears visible.   Typing text and hitting enter does enter the text, but the user cannot see what they are typing. 

#### Expected vs observed behaviour:

Users would expect to be able to see what they are typing. 

#### Patch or snippet allowing to reproduce the problem:

The grid sample "as is" can be used to reproduce.

### Platform and version information

- wxWidgets version  you use:  latest master code
- wxWidgets port  you use:   macOS
- OS  and its version:   macOS Sonoma in dark mode

**Comment by vadz** [comment]
Does the problem only happen under Sonoma or can it be seen in the previous versions too?

**Comment by dkulp** [comment]
I don't have a non-Sonoma machine available right now, but it was originally reported to me from someone running Ventura so I know it's ocuring there as well.    I'm not sure if it's building with Xcode 15/Sonoma SDK related or not.

**Comment by dkulp** [comment]
Note that if I revert  5dffb76d0a4e15bcede71748e3edee478bf61d73 and bcbc31e97f246564e4b19ea2d060ae859c302b44 then the cell editors work fine (but then we see the scroll bar clipping issue.

**Comment by vadz** [comment]
I was thinking that we could at least restrict the changes to Sonoma to prevent them from breaking this under older systems, but it's just a workaround, of course. Unfortunately I don't know absolutely anything about this myself, so I can only hope @csomor might have some idea about how to solve it properly.

**Comment by vadz** [comment]
Could you please check if the changes of #24342 fix this?
