### ISSUE TITLE
Translation not usefull

### ISSUE THREAD

**Issue by rainer-sharp** [wxWidgets/wxWidgets#24206]
If an XRC file is imported e.g. with a menu in which the accl is set as follows '\tctrl+a', an error occurs when importing the XRC, as ctrl is translated to strg at the point in accelcmn.cpp from which the constant e.g. ctrl is used.

But a constant for a comparison must not be translated and there is no _() there either (lock at line 186)

After this has happened, all entries in text fields of a in this frame are ignored or replaced by ctrl+a.

de.po file

`#: ../src/common/accelcmn.cpp:186
msgctxt "keyboard key"
msgid "ctrl"
msgstr "strg"

#: ../src/common/accelcmn.cpp:188
msgctxt "keyboard key"
msgid "alt"
msgstr "alt"

#: ../src/common/accelcmn.cpp:190
msgctxt "keyboard key"
msgid "shift"
msgstr "Umschalt"

#: ../src/common/accelcmn.cpp:192
msgctxt "keyboard key"
msgid "rawctrl"
msgstr "strg"`

**Comment by vadz** [comment]
Sorry, I'm not sure what the actual problem is. Could you please explain what do you have in the XRC, what do you have in your own .po file and what happens, i.e. which translation is the program looking for?

**Comment by rainer-sharp** [comment]
The translations are not complete in wxWidgets from version 3.2.4 there is a context translation. This is now also used in accelcmn.cpp. 
In wxWidgets 3.0.2 everything worked correctly now I get an error message: Unknown accel modifier: 

But what do I have to set in the application or XRC so that the constants are also translated correctly in accelcmn?

Extract from the XRC   
```
               <object class="wxMenuItem" name="wxID_CUT">
                    <label>Cut\tCtrl+X</label>
                </object>
                <object class="wxMenuItem" name="wxID_COPY">
                    <label>Copy\tCtrl+C</label>
                </object>
                <object class="wxMenuItem" name="wxID_PASTE">
                    <label>Paste\tCtrl+V</label>
                </object>
```

**Comment by rainer-sharp** [comment]
Sorry, I found the error, an outdated .mo file was copied into the project directory.
