### ISSUE TITLE
Invalid memory read on nanosvgrast.h

### ISSUE THREAD

**Issue by levinsv** [wxWidgets/wxWidgets#24213]
### Description

Good afternoon!
My application crashes due to an error. Error in this line
https://github.com/wxWidgets/nanosvg/blob/ccdb1995134d340a93fb20e3a3d323ccb3838dd0/src/nanosvgrast.h#L1285

The error has been fixed in this comit
https://github.com/memononen/nanosvg/commit/55b64b5070f937ddb65a8dc5985f9948d3c52d37
This is a different fork and I do not know if you can fix this annoying little mistake.

### Platform and version information

- wxWidgets version  you use: 3.2.2
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
Thanks, there is indeed clearly a bug here and we should apply the upstream fix for it. There were also a few other recent changes in nanosvg, which it seems sensible to pull in too, so I've just done this. Could you please test if your application works correctly with the latest version and let us know if you see any new problems? Thanks!
