### ISSUE TITLE
wxLog* dialog shows up under a wxMessageDialog and blocks interaction on wxGTK

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24228]
Consider this example:

```cpp
    wxLogError("Logged Error");

    wxMessageDialog dlg( nullptr, "Message Dialog", "Information",
                         wxOK | wxCENTRE | wxRESIZE_BORDER | wxICON_INFORMATION | wxSTAY_ON_TOP );
    dlg.ShowModal();
```

Two dialogs will appear at the same time, the `wxLogError` dialog will be below the `wxMessageDialog`, stealing focus and blocking any interaction with the `wxMessageDialog` on top.

On MSW, for example, `wxMessageDialog` appears first, then after closing, the `wxLogError` dialog.

### Platform and version information

- wxWidgets version  you use: 3.2; master
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 21.1
  
  + GTK version: 3.24.33-1ubuntu2
  + Which GDK  backend is used: X11
  + Desktop environment : XFCE
  + Current theme:  Mint-Y-Aqua

**Comment by vadz** [comment]
The current behaviour is indeed not great. However I think it's even _worse_ under MSW, as the log dialog might contain pertinent information that should be seen before the message box is shown.

So I think that we actually need to flush the log before showing any other modal dialog. This is easy to do, of course, but am I missing some reason not to do it?

**Comment by vadz** [comment]
Please test the associated PR if you'd like to see how this works in practice.
