### ISSUE TITLE
warning C4275: non dll-interface class 'wxImageListBase' used as base for dll-interface class 'wxImageList'

### ISSUE THREAD

**Issue by Randalphwa** [wxWidgets/wxWidgets#24232]
### Description
Commit #24033 changed `wxImageList` in wx/msw/imaglist.h to inherit from `wxImageListBase` instead of `wxObject`. For me that results in the following warning:

`wxWidgets\include\wx\msw\imaglist.h(13,45): warning C4275: non dll-interface class 'wxImageListBase' used as base for dll-interface class 'wxImageList'`

That's because `wxObject` is declared with `WXDLLIMPEXP_BASE` whereas `wxImageListBase` simply inherits from wxObject. Adding `WXDLLIMPEXP_BASE` to the wxImageListBase declaration removes the warning though I wasn't sure whether it should be `WXDLLIMPEXP_CORE` instead. Either of them removes the warning and I can build the shared dll without any warnings. Note that I'm compiling with MSVC set to c++20 and /W4 level warnings for my own code, so it's possible that's why I'm seeing the warning and others aren't.

### Platform and version information

- wxWidgets version  you use: 3.3.0 from master
- wxWidgets port  you use: wxMSW

**Comment by vadz** [comment]
Thanks, I'm pretty sure the warning is harmless in this particular case, but I'll add `WXDLLIMPEXP_CORE` to this class declaration as it shouldn't harm (this will DLL-export all of its functions, of which it has none) and is better than suppressing the warning using pragmas.

I do wonder why we're not seeing this warning in the CI builds, we should be using /W4 for them and /std:c++20 shouldn't really affect this AFAICS...
