### ISSUE TITLE
Implicitly-declared copy constructor errors with GCC 14

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/wxWidgets#24248]
GCC 14 hasn't been released yet, but Fedora Rawhide has started building with the pre-release of it.  When building the all headers test, a number of these errors are seen.  Full list attached.  How to best fix this?  Explcitly declare the relevant constructors and operators?

```
/home/fedora/swt2c/wxWidgets/bld/bk-deps g++ -c -o test_allheaders_allheaders.o  -I/home/fedora/swt2c/wxWidgets/bld/lib/wx/include/gtk3-unicode-3.3 -I../../include -D_FILE_OFFSET_BITS=64 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/cloudproviders -I/usr/include/webp -I/usr/include/blkid -I/usr/include/at-spi-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/pixman-1 -I/usr/include/libxml2 -I/usr/include/fribidi -I/usr/include/sysprof-6 -pthread -I/usr/include/libpng16 -DWITH_GZFILEOP  -D__WXGTK__      -I../../tests -DWXUSINGDLL -I../../tests/../samples -I../../3rdparty/catch/single_include -pthread -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -O2 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libmount -I/usr/include/libxml2 -I/usr/include/sysprof-6 -I/usr/include/libpng16 -DWITH_GZFILEOP -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/cloudproviders -I/usr/include/at-spi-2.0 -I/usr/include/gio-unix-2.0  -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -DPIC   ../../tests/allheaders.cpp
In file included from ../../include/wx/evtloop.h:13,
                 from ../../tests/testprec.h:5,
                 from ../../tests/allheaders.cpp:369:
../../include/wx/event.h: In copy constructor ‘wxSetCursorEvent::wxSetCursorEvent(const wxSetCursorEvent&)’:
../../include/wx/event.h:1943:11: error: implicitly-declared ‘wxCursor::wxCursor(const wxCursor&)’ is deprecated [-Werror=deprecated-copy-dtor]
 1943 |           m_cursor(event.m_cursor)
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../include/wx/cursor.h:51,
                 from ../../include/wx/event.h:21:
../../include/wx/gtk/cursor.h:37:13: note: because ‘wxCursor’ has user-provided ‘virtual wxCursor::~wxCursor()’
   37 |     virtual ~wxCursor();
      |             ^
../../include/wx/event.h: In member function ‘void wxSetCursorEvent::SetCursor(const wxCursor&)’:
../../include/wx/event.h:1949:57: error: implicitly-declared ‘wxCursor& wxCursor::operator=(const wxCursor&)’ is deprecated [-Werror=deprecated-copy-dtor]
 1949 |     void SetCursor(const wxCursor& cursor) { m_cursor = cursor; }
      |                                                         ^~~~~~
../../include/wx/gtk/cursor.h:37:13: note: because ‘wxCursor’ has user-provided ‘virtual wxCursor::~wxCursor()’
   37 |     virtual ~wxCursor();
      |             ^
```

[errors.txt](https://github.com/wxWidgets/wxWidgets/files/14047021/errors.txt)

**Comment by vadz** [comment]
In this particular case I think the best would be to remove the (trivial) `wxCursor` dtor. But adding defaulted copy ctor and assignment operator would be fine too and would probably need to be done for 3.2 if we want to fix this there (or could removing dtor be ABI-compatible, actually?).

**Comment by vadz** [comment]
@swt2c Do I understand correctly that we can't backport this fix (nor similar fix for #25132 which I'll push soon) because it breaks ABI compatibility? I'm afraid these warnings will be a problem in 3.2 too, but I'm not sure what to do about them... Maybe add some preprocessor check to at least to allow to opt-in into it? In fact, we could probably hide these dtors from the outside code while still having them in the library, this would be a horrible hack but it looks like it should be safe and would avoid the warnings...

**Comment by swt2c** [comment]
Yes, I'm pretty sure it breaks ABI to remove them.

It looks like I just disabled the warning in Fedora to work around:
https://src.fedoraproject.org/rpms/wxGTK/blob/rawhide/f/tests-no-deprecated-copy-dtor.patch

**Comment by vadz** [comment]
Thanks for confirming this!

Unfortunately it doesn't help with the user code, which is the real problem, especially if they're compiling with `-Werror`. I think we're going to need to put in place one of the suggestions above...

**Comment by vadz** [comment]
Just for the record: as Debian testing (Trixie) has updated g++-mingw-w64-x86-64 package to gcc 14, we now have these warnings/errors in 3.2 CI builds, so I've pushed a commit adding `wxDECLARE_DEFAULT_COPY` to the affected classes.
