### ISSUE TITLE
On mac, m_web_view = wxWebView::New(this, winid, url); Unlinked library

### ISSUE THREAD

**Issue by huixiaouy** [wxWidgets/wxWidgets#24256]
d: Undefined symbols:
  wxWebView::New(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, wxString const&, long, wxString const&), referenced from:
      WebPanel::WebPanel(wxWindow*, int, wxString const&) in liblibslic3r_gui.a[118](WebPanel.o)
  _wxWebViewBackendDefault, referenced from:
      WebPanel::WebPanel(wxWindow*, int, wxString const&) in liblibslic3r_gui.a[118](WebPanel.o)
  _wxWebViewNameStr, referenced from:
      WebPanel::WebPanel(wxWindow*, int, wxString const&) in liblibslic3r_gui.a[118](WebPanel.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by asmwarrior** [comment]
Can you change all your titles and messages in English, because not everyone here understand Chinese.

Also, please show more details, such as what exactly link error do you see.

**Comment by vadz** [comment]
You really need to explain what the problem is.
