### ISSUE TITLE
I can't build an example in Visual Studio 2022

### ISSUE THREAD

**Issue by wmurw** [wxWidgets/wxWidgets#24250]
### Visual Studio 2022
I build wxWidgets and/or my application using:

- [ ] CMake
- [ ] configure
- [ ] mingw32-make with makefile.gcc
- [X] MSBuild (Microsoft Visual Studio solution file)
- [ ] nmake with makefile.vc
- [ ] Xcode

### Description
Opened C:\wxWidgets-3.2.4\samples\minimal\minimal_vc17.sln  in Visual Studio 2022
Started the build.
I got an error:
Error C1083 Cannot open file inclusion: ../../../lib/vc_x64_lib/mswu/wx/setup.h: No such file or directory, base C:\wxWidgets-3.2.4.4\include\msvc\wx\setup.h 144		

### Platform and version information

- wxWidgets version you are building: 3.2.4
- wxWidgets port  you are building: wxMSW
- OS  and its version: Windows 10
- Compiler being used: MSVS 2022
- Non-default compiler options, if any:

**Comment by vadz** [comment]
You need to open and build `build/msw/wx_vc17.sln` solution first to build the library itself, before building the samples.

**Comment by wmurw** [comment]
I have built build/msw/wx_vc17.sln.
Now running minimal_vc17.sln gives an error:
Error LNK1104 cannot open file "wxbase32u_net.lib"	

Searching for wxbase32u_net.lib in the C:\wxWidgets-3.2.4 directory yielded the absence of such a file.

**Comment by wmurw** [comment]
Figured it out.
The file wxbase32u_net.lib was found in wxMSW-3.2.4_vc14x_x64_Dev.7z

**Comment by vadz** [comment]
Just for the record, this is not exactly wrong -- as you can use precompiled binaries too, of course -- but not correct neither because you would have got the release libraries too if you had built `wx_vc17.sln` in "Release" configuration. You must have built it in debug one only, if you didn't get this file (but only `wxbase32ud_net.lib`).
