### ISSUE TITLE
wxEnumProperty::SetChoiceSelection( -1 ) no longer works

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24279]
In wxWidgets-3.0 it was possible to set the selection of a `wxEnumProperty` to `-1` to get an empty `wxEnumProperty`, i.e. without any of the choices being selected.

Unfortunately, with wxWidgets-3.2 this is no longer possible. Instead, a debug alert is now triggered.

The `wxCHECK_RET` was introduced with commit 29bf859fae9116f591907af36ee04cb07459ba0b (`Check if new index is in range before selecting new value in wxPGProperty::SetChoiceSelection, 2014-11-29`).
Maybe it was unintentional to also consider `-1` to be invalid!?

Why should the selection `-1` be supported?
* To be consistent with the normal `wxChoice`, which does support it.
* Use case:
  You can edit the attributes of several selected differently configured objects in a `wxPropertyGrid`.
  No selection is displayed for attributes that are different for the selected objects.
  If you select something, it will be applied to all objects that are being edited.
  If you do not select anything (selection remains `-1`), the attribute remains unchanged for all these objects.

If preventing the `-1` selection from working was unintentional, please fix the issue in wxWidgets-3.2.
If it was intended, I hope to have convinced you of the usefulness of the `-1` selection and that wxWidgets should support it again at least in version 3.3.

Thanks in advance!

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by a-wi** [comment]
Definitely `wxPGProperty::SetChoiceSelection(-1)` was not intended and shouldn't be used to deselect all choices of`wxEnumProperty` and derived properties.
Function dedicated for this purpose is `wxPGProperty::SetValueToUnspecified()` and you should use it in your case.
If you find any issues with using it, please report it.

**Comment by vadz** [comment]
> Definitely `wxPGProperty::SetChoiceSelection(-1)` was not intended and shouldn't be used to deselect all choices of`wxEnumProperty` and derived properties.

I don't really see any problem with allowing `-1` to mean "no selection" here, especially if it worked before. What problem does it create, exactly?

If this really can't be done, I think it would be nice to add something like

```c++
wxCHECK_RET( newValue != -1, "Use SetValueToUnspecified() to unset the selection" );
```

to this function.

**Comment by a-wi** [comment]
This sanity check is in the code for 8 years. If you see a reason to relax it now, please do it. Good luck!

**Comment by vadz** [comment]
If there is indeed no real harm in allowing it, I'd be tempted to relax it because, as you see, people are still updating from 3.0 to 3.2 and I don't want to create unnecessary barriers for this. I also find the argument of consistency with `wxChoice::SetSelection()` compelling.

So I'll indeed do this.

**Comment by vadz** [comment]
Done in #24281, @taler21 please let me know if you still see any problems with this.

**Comment by taler21** [comment]
Thanks for the prompt fix. Works fine!
