### ISSUE TITLE
Expand wxFont wxFontWeight options

### ISSUE THREAD

**Issue by willco007** [wxWidgets/wxWidgets#24275]
### Description

Currently, `wxFontWeight` options consist of these values:

```
wxFONTWEIGHT_NORMAL
wxFONTWEIGHT_LIGHT 
wxFONTWEIGHT_BOLD
wxFONTWEIGHT_MAX
```

While macOS, for example, has an expanded level of options for font weight:

```
NSFontWeightUltraLight
NSFontWeightThin
NSFontWeightLight
NSFontWeightRegular 
NSFontWeightMedium
NSFontWeightSemibold
NSFontWeightBold
NSFontWeightHeavy
NSFontWeightBlack
```

It would be great to have an expanded set of options in WX widgets to be able to tune the weight more precisely.

**Comment by PBfordev** [comment]
I think that `wxFontWeight` has more values than those four:
https://github.com/wxWidgets/wxWidgets/blob/a01c870dbb24407575337ea0477374dec909e531/include/wx/font.h#L60-L74

And they also seem to be offered in the font sample, at least on Windows. No idea, if they work as expected...

**Comment by vadz** [comment]
> I think that `wxFontWeight` has more values than those four:

Yes, and you can use `wxFont::SetNumericWeight()` if even this is not enough and you want a font of slightly less than medium boldness with weight of 423.

> And they also seem to be offered in the font sample, at least on Windows. No idea, if they work as expected...

They should, at least I had tested this back when this was added on all platforms.

Closing as this is already available, please open new issues for any bugs.

**Comment by willco007** [comment]
Ugh, the great Google brought me to the old documentation. Apologies.
