### ISSUE TITLE
Crash when closing a `wxColourDialog` (wxMSW)

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24288]
This issue was introduced with commit 9befda5c26d478b3acfd03acc74ea3426fbfc60c (`Only use AutoSystemDpiAware when displays have different DPI, 2024-01-14`).

I have a single monitor system with 100% DPI and it makes no difference whether the application is 'DPI unaware' or 'System DPI aware' (did not test 'per monitor DPI aware').

#### To Reproduce:

This regression can be reproduced in the dialogs sample.

1. Start the dialogs sample.
2. Open the native `wxColourDialog` dialog ('Dialogs' > 'Choices and selectors' > 'Choose fg colour').
3. Close the dialog.
   Bug: The application crashes in `wxMSWImpl::AutoSystemDpiAware::~AutoSystemDpiAware()`.

### Platform and version information

- wxWidgets version  you use: master (36583f13e1c6534c8b2a7c048835fcdceaad3611)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by MaartenBent** [comment]
Oops. I see the problem. This happens because `ms_pfnSetThreadDpiAwarenessContext` is initialized as `-1`, so the `nullptr` check succeeds. 

This should fix it. I can create a PR later, if a maintainer hasn't committed the fix in the mean time.
```diff
diff --git "a/include/wx/msw/private/dpiaware.h" "b/include/wx/msw/private/dpiaware.h"
index eb5df72484..f122af4bdc 100644
--- "a/include/wx/msw/private/dpiaware.h"
+++ "b/include/wx/msw/private/dpiaware.h"
@@ -61,7 +61,7 @@ public:
 
     ~AutoSystemDpiAware()
     {
-        if ( ms_pfnSetThreadDpiAwarenessContext )
+        if ( ms_pfnSetThreadDpiAwarenessContext && ms_pfnSetThreadDpiAwarenessContext != (SetThreadDpiAwarenessContext_t)-1 )
         {
             ms_pfnSetThreadDpiAwarenessContext(m_prevContext);
         }
)
```

**Comment by vadz** [comment]
Thanks Maarten, I'll apply this soon.
