### ISSUE TITLE
wxEVT_ENTER_WINDOW events not generated for wxChoice under GTK

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#24295]
I have a similar issue with wxEVT_ENTER_WINDOW events not captured on a wxChoice under GTK:
```
      wxString myChoices[] = { wxT("Choice1") };
      wxChoice* choice = new wxChoice( panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, myChoices);
      choice->Bind(wxEVT_ENTER_WINDOW, [&](wxMouseEvent& event) {
        wxLogDebug("Enter Window2");
      });
```
The message is never printed, although the callback gets triggered for other UI elements (tried buttons and check buttons).

Originally discussed at https://forums.wxwidgets.org/viewtopic.php?f=1&t=51065.

----

_Originally posted by @dizcza in https://github.com/wxWidgets/wxWidgets/issues/24245#issuecomment-1935579661_

**Comment by vadz** [comment]
I've extracted this from the original issue because it's due to a different problem (but the original one still needs to be fixed first).

**Comment by vadz** [comment]
@dizcza Please see #24339 for the proposed fix and test it if you can. TIA!

**Comment by dizcza** [comment]
Sorry, I don't have time at the moment to test the fix. You can close the issue as resolved and if not, I'll reopen it.
Thanks.
