### ISSUE TITLE
Generic `wxListCtrl` does not deselect a single selected but not focused item

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24312]
A generic multi-select `wxListCtrl` does not deselect a single selected item that does not have focus when the user single-selects another item.

This is a regression introduced in wxWidgets-3.1.5 with commit fedc80eee3c449cec894f3bdfacd8ef01e41f71b (`Improve selection and focus events generation in wxGenericLisCtrl, 2020-10-10`).

### To Reproduce:

This issue can be reproduced in the listctrl sample.

1. Start the listctrl sample.
2. Enable multi-select mode via 'List' > 'Multiple selection' in the menu.
3. Press and hold the `Ctrl` button.
4. Click the first item to select it.
5. Click the second item to select it.
6. Click the second item again to deselect it.
7. Release the `Ctrl` button.
8. Click the third item to select it.
   Bug: The first item has not been deselected, it is still selected.

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: openSUSE Leap 15.5
  
  + GTK version:  2.24.33
  + Which GDK  backend is used: X11
  + Desktop environment : KDE

**Comment by AliKet** [comment]
Yes I can reproduce it under Ubuntu 18.04

**Comment by taler21** [comment]
@AliKet, what do you think about these changes to fix this issue?

```patch
diff --git "a/src/generic/listctrl.cpp" "b/src/generic/listctrl.cpp"
index 341b256cc7..06d2f9ff18 100644
--- "a/src/generic/listctrl.cpp"
+++ "b/src/generic/listctrl.cpp"
@@ -2207,7 +2207,7 @@ void wxListMainWindow::HighlightAll( bool on )
 
 void wxListMainWindow::HighlightOnly( size_t line, size_t oldLine )
 {
-    const unsigned selCount = GetSelectedItemCount();
+    unsigned selCount = GetSelectedItemCount();
 
     if ( selCount == 1 && IsHighlighted(line) )
     {
@@ -2216,11 +2216,16 @@ void wxListMainWindow::HighlightOnly( size_t line, size_t oldLine )
 
     if ( oldLine != (size_t)-1 )
     {
-        IsHighlighted(oldLine) ? ReverseHighlight(oldLine)
-                               : RefreshLine(oldLine); // refresh the old focus to remove it
+        if ( IsHighlighted(oldLine) )
+        {
+            ReverseHighlight(oldLine);
+            selCount--;
+        }
+        else
+            RefreshLine(oldLine); // refresh the old focus to remove it
     }
 
-    if ( selCount > 1 ) // multiple-selection only
+    if ( selCount > 0 ) // multiple-selection only
     {
         // Deselecting many items at once will generate wxEVT_XXX_DESELECTED event
         // for each one of them. although this may be inefficient if the number of

```

**Comment by vadz** [comment]
Sorry, still didn't have time to look at this yet but it bothers me that the "multiple-selection only" comment would become wrong with the proposed change because the code inside this `if` would be now executed for single selection case too and may not be executed in multiple selection one.

**Comment by AliKet** [comment]
This line https://github.com/wxWidgets/wxWidgets/blob/7150e6ecb385f6b76c7e2d81ff030305db51b344/src/generic/listctrl.cpp#L2223
should be changed to:
` if ( selCount >= 1 ) // multiple-selection only 
`
because it is never `true` for **single selection** mode.

Could you please open a PR with this change and preferably with adding a test for it. TIA!

**Comment by taler21** [comment]
You are right, even if it's unexpected for me that `GetSelectedItemCount()`returns `0` while changing the selection in single selection mode.

That is because the implementation of `GetSelectedItemCount()` looks like this

https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/generic/listctrl.cpp#L3758-L3762

and `m_current` is changed to the new selection before `HighlightOnly()` is called.

https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/generic/listctrl.cpp#L2692-L2696


I created a PR and added a test, even though it probably won't run for the generic `wxListCtrl` in the automatic tests.

https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/tests/controls/listbasetest.cpp#L182-L187

**Comment by AliKet** [comment]
> I created a PR and added a test, even though it probably won't run for the generic `wxListCtrl` in the automatic tests.
> 
> https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/tests/controls/listbasetest.cpp#L182-L187

Thanks for the PR. I tried to run it in my fork with the above removed and it failed only under `wxGTK2` with this message
```
./controls/listbasetest.cpp:220: FAILED:
  REQUIRE( 4 == list->GetSelectedItemCount() )
with expansion:
  4 == 1
```
So I think we can enable this automatic test for all ports now, but `wxGTK2`.

TIA.

**Comment by taler21** [comment]
Okay, I have now enabled this test in the PR for all ports except `wxGTK2`.
