### ISSUE TITLE
wxGrid drop marker missing with double buffering on

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#24310]
I think I found a problem with double buffering (on Windows).
When dragging a row or col, the drop marker is missing now.

E.g. in the grid sample with "Grid -> Row drag move".
In the screenshot it's between lines 6 and 7:

Before merging this branch:
![grafik](https://github.com/wxWidgets/wxWidgets/assets/5512021/dfeae12e-31e5-45c0-a1a0-785f7a6c7306)

After:
![grafik](https://github.com/wxWidgets/wxWidgets/assets/5512021/af3e612e-8443-48ac-bb60-6c86c2c6db46)

I can work around by commenting out `exstyle |= WS_EX_COMPOSITED;`.

The relevant code for drawing the marker is in `wxGrid::ProcessRowColLabelMouseEvent`.
I would guess that some additional action is required around the ClientDC, but could not see what is missing. Other code like "pressing" the row label looks similar, but does not have problems.
```
if ( markerPos != m_dragLastPos || markerColour != m_dragLastColour )
{
    wxClientDC dc( headerWin );
    oper.PrepareDCForLabels(this, dc);

    int markerLength = oper.Select(headerWin->GetClientSize());

    // Clean up the last indicator if position has changed
    if ( m_dragLastPos >= 0 && markerPos != m_dragLastPos )
    {
        wxPen pen(headerWin->GetBackgroundColour(), 2);
        dc.SetPen(pen);
        oper.DrawParallelLine(dc, 0, markerLength, m_dragLastPos + 1);
        dc.SetPen(wxNullPen);

        int lastLine = oper.PosToLine(this, m_dragLastPos, nullptr, false);

        if ( lastLine != -1 )
            oper.DrawLineLabel(this, dc, lastLine);
    }

    // Draw the marker
    wxPen pen(*markerColour, 2);
    dc.SetPen(pen);
    oper.DrawParallelLine(dc, 0, markerLength, markerPos + 1);
    dc.SetPen(wxNullPen);

    m_dragLastPos = markerPos;
    m_dragLastColour = markerColour;
}
```

_Originally posted by @DietmarSchwertberger in https://github.com/wxWidgets/wxWidgets/issues/22851#issuecomment-1939732120_

**Comment by vadz** [comment]
@DietmarSchwertberger Thanks for reporting, I can't look at this right now but I've created a new issue to do it later.

FWIW I guess using `wxOverlay` would be the best thing to do here too, but it's indeed weird that this is different from the other similar places.

**Comment by DietmarSchwertberger** [comment]
I think, the marker needs to be added to the normal Paint method. Currently it's only drawn using ClientDC.
I will check.

**Comment by DietmarSchwertberger** [comment]
I don't fully understand why it was necessary, but PR #24314 adds the markers to the label drawing methods.
