### ISSUE TITLE
wxAuiNotebook should call UpdateTabCtrlHeight on DPI change

### ISSUE THREAD

**Issue by sz5000** [wxWidgets/wxWidgets#24348]
The height of the notebook could have been changed with a DPI change. So I would assume that notebook should call `UpdateTabCtrlHeight` internally on DPI changes. Otherwise we get strange effects with `wxAuiSimpleTabArt`. If I include a handler and call `UpdateTabCtrlHeight`, then these strange effects do not occur.

What happens when windows is moved from one screen to another with different DPI:
![screen1](https://github.com/wxWidgets/wxWidgets/assets/33447587/b72eb573-b30c-479f-96f4-4d15c88cb812)
![screen2](https://github.com/wxWidgets/wxWidgets/assets/33447587/873b77cc-2ab6-49f0-a94b-51106fd2ae30)

**Comment by vadz** [comment]
Thanks for reporting this! Could you please check if the linked PR fixes the problem?

**Comment by sz5000** [comment]
Yes, seems to be good now. Height is now updated on DPI change. Thanks vadz.
