### ISSUE TITLE
New wxSplitterWindow::GetLastPosition() method documented to return `const wxPoint&` but implemented to return `wxPoint`

### ISSUE THREAD

**Issue by mcorino** [wxWidgets/wxWidgets#24347]
### Description

@vadz The new "wxSplitterWindow::GetLastPosition()" method is documented to return `const wxPoint&` but in fact is implemented to return `wxPoint` (by value).

This breaks wxRuby3 (and will most likely break wxPython) builds.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: all
- OS  and its version: NA

**Comment by vadz** [comment]
Oops, sorry about this, will fix soon.
