### ISSUE TITLE
Update the lexilla and scintilla submodules / forks

### ISSUE THREAD

**Issue by antonvw** [wxWidgets/wxWidgets#24346]
### Description

It would be nice if these repo's are synced with the origins, to keep in pace with new features / development

**Comment by vadz** [comment]
I'm not sure how useful is to have this issue, it can never be really closed (well, for as long as Scintilla keeps being developed). Maybe you should at least state which version of Scintilla you want to update to (and maybe why) to have some fixed target.

**Comment by antonvw** [comment]
Well, for lexilla, the current wxWidgets version relates to tag 5.0.1 (from  Apr 9, 2021), while the official lexilla has released 5.3.0, offering more lexers. 
Same for scintilla, current wxWidgets relates to 500,  the official one has version 540. 
So I should suggest upgrade to lexilla 5.3.0 and scintilla 540. 
The main reason is the extra lexers offered by lexilla (and likely updates for existing ones, I did not check), and the longer this is postponed, the more work it probably will be.

**Comment by MaartenBent** [comment]
What I remember from upgrading to 5.0.0 is that the upgrade to 5.0.1 will be the most difficult one because there are lots of api changes.
And in addition to that, Scintilla/Lexilla uses c++17 while wxWidgets should support c++11. So all the c++17/c++14 features need to be ported to c++11.

**Comment by antonvw** [comment]
So you say this is blocked until wxWidgets uses c++17/c++14, to prevent doing backport to c++11, and later on undo the backport when the standard in wxWidgets is updated. 
Perhaps that is the most practical and less effort intense solution. Is there a roadmap  for adopting a c++17 standard, or c++20?

**Comment by MaartenBent** [comment]
The update to 5.0.0 already has lots of backports, so doing it for newer versions isn't impossible. It's just someone needs to have the time and energy to do this.

I think 3.3 (development) and 3.4 (stable) will be c++11. As far as I know there is no date, but expect a couple of years.

**Comment by MaartenBent** [comment]
Actually updating only Lexilla seems straight forward. I tried 5.3.0 (in c++17 mode) and that already works. So it just needs a few `string_view` replacements to work in c++11.

Scintilla has the interface changes for rendering stuff, so that will be a lot more work.

**Comment by antonvw** [comment]
I will be glad with updating the Lexilla only, it you could do that, of course I will help in testing it.

**Comment by MaartenBent** [comment]
Done in #24369
