### ISSUE TITLE
Julia support in StyledTextCtrl

### ISSUE THREAD

**Issue by sshiraiwa** [wxWidgets/wxWidgets#24350]
I have no clue how hard it is, but I wonder if we can edit Julia and use syntax highlighting in a widget 
built on wx. Is it conceivable to add supporting Julia in StyledTextCtrl, so that we can use SetLexer(STC_LEX_JULIA)?

**Comment by MaartenBent** [comment]
Lexilla 5.3.0 supports Julia. It seems doable to update to this version, see #24346.

**Comment by MaartenBent** [comment]
This should now be available in the master branch, see #24369 
It won't be available in 3.2 because it cannot be backported to c++98.
