### ISSUE TITLE
wxOSX: wxDataViewCustomRenderer has undesirable tooltip with debug info

### ISSUE THREAD

**Issue by craftyjon** [wxWidgets/wxWidgets#24370]
When using a dataview with a custom cell renderer, in certain situations a tooltip will be displayed when hovering over the cell that contains debug output of the form `wxCustomRendererObject: <pointer>`

To see this, there must not be a global tooltip set on the wxDataViewCtrl.
To reproduce, take the dataview sample, and comment out the line that sets a tooltip (line 902 on my sources):

```cpp
m_ctrl[Page_Music]->SetToolTip("You may edit most of the cells here!");
```

Then build and run the sample, and hover over one of the custom renderer cells (last column)

If you do not see the tooltips, you may need to make the column smaller; it is not always triggered and I cannot figure out why.

This came from a KiCad report where the column does not need to be small to show the problem: https://gitlab.com/kicad/code/kicad/-/issues/17197

I suspect the problem is that the custom renderer does not define a tooltip override, and so the default provided by macOS is used, which is the `description` property, which is intended as debug output and has the form `class name: memory address`.  However I'm not sure, and I'm also not comfortable enough with the macOS sources to know how to add suitable overrides if this is indeed the problem.

### Platform and version information

- wxWidgets version  you use: 3.2.1
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 12+

**Comment by vadz** [comment]
Thanks for reporting this! I can reproduce it here, although I indeed only see the tooltip if the column is very narrow and I don't really understand why.

I thought this would be easy to fix by overriding [NSOutlineViewDelegate outlineView:toolTipForCell:rect:tableColumn:item:mouseLocation:](https://developer.apple.com/documentation/appkit/nsoutlineviewdelegate/1527695-outlineview?language=objc) to return empty string, as recommended by Apple documentation, but it couldn't be that simple, of course.

But I think I've finally found the right thing to do, please see #24371. With this, I can't see the problem any more and I hope I understood correctly where it was coming from -- but please let me know if you still see anything wrong.
