### ISSUE TITLE
wxImage::LoadFile should accept buffer with image

### ISSUE THREAD

**Issue by ukoz** [wxWidgets/wxWidgets#24380]
Please, allow to load `wxImage` from buffer.
Is it really necessary to save downloaded image or MIME, gzip decoded to disk to show?

[wxImage::LoadFile](https://docs.wxwidgets.org/2.8/wx_wximage.html#wximageloadfile)
`bool LoadFile( const unsigned char *data, const size_t sz, wxBitmapType type = wxBITMAP_TYPE_ANY, int index = -1 );`
`bool LoadFile( const std::string_view & s, wxBitmapType type = wxBITMAP_TYPE_ANY, int index = -1 );`
`bool LoadFile( const const char *s8, size_t sz, wxBitmapType type = wxBITMAP_TYPE_ANY, int index = -1 );`

```
wxImage i;
std::vector<unsigned char> v; // contain actual image

wxStreamBuffer w(wxStreamBuffer::read);
w.SetBufferIO(v.data(), v.size(), false);
i.LoadFile(*w.GetInputStream(), wxBITMAP_TYPE_ANY, -1); // crash

auto m = new wxMemoryInputStream(v.data(), v.size()); // extra object for already in-memory array
i.LoadFile(*m, wxBITMAP_TYPE_ANY, -1); // do I really have to serialize buffers
```

would be

```
wxImage i;
std::vector<unsigned char> v; // contain actual image

i.LoadFile(v.data(), v.size(), wxBITMAP_TYPE_ANY, -1);
```

curl actually download to std::string buffers

```
wxImage i;
std::string s = curl("https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png");

i.LoadFile(s.c_str(), s.length(), wxBITMAP_TYPE_ANY, -1);
```

**Comment by vadz** [comment]
>  Is it really necessary to save downloaded image or MIME, gzip decoded to disk to show?

Of course not. You can load it from `wxMemoryInputStream` perfectly fine and out test suite does it, so if it crashes for you the problem is almost certainly in your code.

If you still think there is a problem here, please provide a simple self-contained example showing it.

**Comment by ukoz** [comment]
```
wxImage i;
wxString s; // contain image

wxStringInputStream ss(s);
i.LoadFile(ss, wxBITMAP_TYPE_ANY, -1); // error: Unknown image data format.

wxMemoryInputStream m(s.data(), s.length());
ttl.LoadFile(m, wxBITMAP_TYPE_ANY, -1); // works, should work for wxStringInputStream too
```

**Comment by vadz** [comment]
Sorry, this is not a self contained example, notably it doesn't show what is in the stream nor does it show the full application. If the image data is correct, and if the image handlers have been initialized, this should work.

But please do read our [issue reporting guide](https://www.wxwidgets.org/develop/how-to-report-issues/).

**Comment by MaartenBent** [comment]
A reply on wx-dev, that is sadly not visible here, suggested you can't use `s.lenght()` because it will be the length to the first `\0` in the data. Not the length of the data stream.
https://groups.google.com/g/wx-dev/c/C_7LYm-3HAs/m/IJigUUAhBAAJ

**Comment by vadz** [comment]
To be precise, `wxString::length()` does work correctly _if_ the string has the correct length, even if it has `NUL` bytes inside it. However it's all too easy to truncate the data containing such bytes when creating the string -- and then, of course, its length won't be right.

IOW I'm 99% sure that the problem is in the not shown code represented by this line above

```cpp
wxString s; // contain image
```
