### ISSUE TITLE
In wxGTK, wxTextEntry autocomplete interferes with the wxTE_PROCESS_ENTER style for comboboxes

### ISSUE THREAD

**Issue by Carnildo** [wxWidgets/wxWidgets#24394]
### Description

In wxGTK, wxTextEntry autocomplete interferes with the wxTE_PROCESS_ENTER style for comboboxes.  If autocomplete is active for a combo box, then the wxTE_PROCESS_ENTER style will be cleared the first time the autocomplete dropdown is shown.

Note that this does not happen with wxTextCtrl.

The issue appears to be that `wxTextAutoCompleteData::ToggleProcessEnter()` cannot be safely called twice in a row with `toggleOff` set to true.  The second time it's called, `m_hadProcessEnterFlag` will be unconditionally set to "false" regardless of what it was originally.

In my testing, `wxTextAutoCompleteData::ToggleProcessEnter()` is called twice in a row with `toggleOff` set to true when showing the autocomplete dropdown for a combobox, and twice with it set to false when hiding it.  For a text control, it's called once with it set to true, and once with it set to false. 

#### Expected vs observed behaviour:

1. Run the sample program.
2. Type the letter "a" in the combo box.
3. Hit "Enter".

Expected result: a dialog box pops up.

Actual result: nothing happens.

#### Patch or snippet allowing to reproduce the problem:

[combotest.cpp.gz](https://github.com/wxWidgets/wxWidgets/files/14551973/combotest.cpp.gz)

### Platform and version information

- wxWidgets version you use: Git head ( @66ea0b2 )

- wxWidgets port you use: wxGTK
- OS and its version: Gentoo Linux
  + GTK version: 3.24.39
  + Which GDK backend is used: X11
  + Desktop environment: XFCE

**Comment by vadz** [comment]
Thanks for reporting, should be fixed by the linked PR, please let me know if you see any problems with it.
