### ISSUE TITLE
Active window becomes unfocused when a wxWebSessionCURL instance is destroyed

### ISSUE THREAD

**Issue by b-fission** [wxWidgets/wxWidgets#24401]
#### Bug description:

The active window becomes unfocused when a wxWebSessionCURL instance is destroyed.

#### Expected vs observed behaviour:

The current window is expected to remain in focus when a wxWebSession is destroyed in a different window.

On the current stable 3.2.4 as well as latest git code, I am seeing the active window lose focus when wxWebSession uses curl as the backend. Also note, this issue does not occur when using WinHTTP as the backend.

#### Snippet allowing to reproduce the problem:

```c++
#include "wx/wx.h"

class Frame2 : public wxFrame
{
public:
    wxStaticText textctrl;

    Frame2() : wxFrame(nullptr, wxID_ANY, "Frame 2"), textctrl(this, wxID_ANY, "wait for it...")
    {
        Bind(wxEVT_TIMER, &Frame2::TimerFunc, this);
        wxTimer *timer = new wxTimer(this);
        timer->Start(200, true);
    }

    void TimerFunc(wxTimerEvent &event)
    {
        textctrl.SetLabel(this->IsActive() ? "window is already focused. GOOD." : "window is not focused. BAD.");
    }
};

class Frame1 : public wxFrame
{
public:
    wxWebSession session;

    Frame1() : wxFrame(nullptr, wxID_ANY, "Frame 1")
    {
#if 1
        session = wxWebSession::New(wxWebSessionBackendCURL); //this one unfocuses during destroy
#else
        session = wxWebSession::New(wxWebSessionBackendWinHTTP); //this one works ok
#endif
        wxButton *btnDoNext = new wxButton(this, wxID_ANY, "click me");
        Bind(wxEVT_BUTTON, &Frame1::ButtonClicked, this);
    }

    void ButtonClicked(wxCommandEvent &event)
    {
        Frame2 *frame2 = new Frame2();
        frame2->Show();
        this->Close();
    }
};

class MyApp : public wxApp
{
public:
    bool OnInit() override
    {
        Frame1 *frame1 = new Frame1();
        frame1->Show();
        return true;
    }
};

wxIMPLEMENT_APP(MyApp);
```

#### To Reproduce:

1. Build and run the test code above, which uses wxWebSessionBackendCURL
2. When Frame1 appears, click the button
3. Observe if Frame2 appears and is not focused. The window text will also describe the result.
4. Modify the test code to use wxWebSessionBackendWinHTTP and observe if Frame2 appears with focus

### Platform and version information

- wxWidgets version  you use: 3.2.4, also tested latest git master-b03c3416
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10 21H1, Windows 7

**Comment by b-fission** [comment]
It appears to be caused by this line : https://github.com/wxWidgets/wxWidgets/blob/dc65e4b7d2ff2e52f7e34b3103d47f14a5b030d9/src/common/webrequest_curl.cpp#L587

Casually changing it to `DestroyWindow` seems to fix the unfocusing issue.
Any ideas if that's the only change needed to correctly resolve this?

**Comment by NewPagodi** [comment]
It looks like DestroyWindow  is the correct function to call.  I missed the fact that that CloseWindow doesn't actually destroy the window with the associated hwnd.

**Comment by vadz** [comment]
FWIW it would be really better to use `wxCreateHiddenWindow()` here, I think we discussed it back when `wxWebRequest` was added but decided to do it later... If anybody has time for this, it would be nice to do it, but otherwise we should at least apply the change here, thanks!
