### ISSUE TITLE
GTKSuppressDiagnostics() not work in version 3.2.4

### ISSUE THREAD

**Issue by ZhipengShi** [wxWidgets/wxWidgets#24432]
### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: Ubuntu22.10, 
  
  + GTK version: 2.0
  + Which GDK  backend is used:X11
  + Desktop environment :Gnome
  + Current theme: 

I tested GTKSuppressDiagnostics(), it works well when I used wxWidgets-3.1.6. But with wxWidgets-3.2.4, it not works. It still shows GTK-Warning message.

**Comment by jmoraleda** [comment]
I can confirm the same issue on Debian bookworm

**Comment by vadz** [comment]
This was fixed by 0efd803f30 (Make GTKSuppressDiagnostics() work again, 2023-10-01) in master and I'll backport it to 3.2 too.

**Comment by vadz** [comment]
Closing this now, as it won't be closed automatically when merging into 3.2, and I don't want to forget about it later, but this will be really fixed only when #24375 is merged.

**Comment by ZhipengShi** [comment]
Hi Vadz,

    Thank you very much.
