### ISSUE TITLE
Showing prompt when printing resets orientation and number of copies

### ISSUE THREAD

**Issue by Solosigi** [wxWidgets/wxWidgets#24439]
I have a problem in Printing! I modify the original Sample Code:

```cpp
void MyFrame::OnPrint(wxCommandEvent& WXUNUSED(event))
{
    // My modification
    g_printData->SetOrientation(wxLANDSCAPE);
    g_printData->SetNoCopies(2);
    // End of my modification

    wxPrintDialogData printDialogData(* g_printData);
    wxPrinter printer(&printDialogData);
    MyPrintout printout(this, "My printout");

    // "Noice printing" - ask prompt
    if (!printer.Print(this, &printout, true /*prompt*/))

    // "Quite Orubtubg" - do not als prompt
//    if (!printer.Print(this, &printout, false /*prompt*/))

    {
        if (wxPrinter::GetLastError() == wxPRINTER_ERROR)
        {
            wxLogError("There was a problem printing. Perhaps your current printer is not set correctly?");
        }
        else
        {
            wxLogMessage("You canceled printing");
        }
    }
    else
    {
        (*g_printData) = printer.GetPrintDialogData().GetPrintData();
    }
}
```

My modification is marked!
If i print "quite" (without prompt) it is ok: Landscape an two copies:
If i print "noice" (with prompt) i get only one copy in Portrait!

**Comment by oneeyeman1** [comment]
@Solosigi , what platform and wxWidgets version?

**Comment by vadz** [comment]
I've tried to make the subject of this issue more intelligible, hopefully I understand the problem correctly (but it would still be indeed useful to know which platform do you use).

Unfortunately I don't have time to debug it now, but it looks like print data is getting overwritten somewhere. It shouldn't be hard to find (and hopefully not hard to fix neither) if somebody can look into it.

**Comment by Solosigi** [comment]
I use wxWidgets-2.3.4, Windows 11, Visual Studio 2022/64 Bit V. 17.9.5.
The problem is: 
I have a Form. In this form i determin: number of copies, portrait/landscape, paper size (A4/A5...) and duplex.
If i do a preview or i print without prompt ("quite") all the prints are ok!
But if i print with prompt ("noice") the print is allways standard: number of copy = 1, allways protrait, no duplex.
It seems the guidelines from my form are not carried over.
In the prompt the user have to change all this predefind values.

**Comment by dconnet** [comment]
Issue #24130

**Comment by vadz** [comment]
Thanks David, this does look like the same bug, so closing.

**Comment by Solosigi** [comment]
Problem solved, thank you.
It was Win11 Bug!
