### ISSUE TITLE
Relative paths in makefiles

### ISSUE THREAD

**Issue by stephendgilbert** [wxWidgets/wxWidgets#24430]
### Description

Hello. I may have an unusual use-case. I teach college students how to use wxWidgets as part of my C++ class. In our labs, we use Visual C++ from the command line. wxWidgets is installed on a shared drive and students copy the samples to their desktops to compile. 

Currently, all of the windows makefiles (gcc or vc) for the samples use relative paths like `../../build/msw/config.vc` or `.\..\..\lib\$(COMPILER_PREFIX)`. For he minimal program, there are 17 of these, which of course, don't work unless you are building it from the specific location where it was created (in the wxWidgets source tree).

Currently, I spend some class time explaining to the students that they need to replace each of these relative paths, with an absolute path containing $(WXWIN). What I'd like, though, is for the windows makefiles to work independent of the location of the source code.

**Comment by PBfordev** [comment]
> What I'd like, though, is for the windows makefiles to work independent of the location of the source code.

I am just curious, how should that work? The makefiles certainly cannot use `WXWIN` system environment variable: Not only using it is not mandatory, more importantly, it may point to an entirely different folder than the one from which I want to build as I have a bunch of independent wxWidgets builds/folders.

Unfortunately, I have no solution for your problem, aside from providing the students the makefiles you already modified, so they don't have to do it by themselves, only you do it once for all (or provide a batch/powershell file for them to run).

**Comment by vadz** [comment]
Samples makefiles are not very human-friendly, so I wouldn't recommend using them, especially for the students. FWIW I do have a simple GNU makefile which I used for testing simple programs, consisting of a single source file only, that I'm including below in case it can be helpful, but it's made for the rather unusual case of using MSVC from Cygwin. It probably can be used as a basis for creating your own make/CMake/nmake/whatever file that you could provide to your students -- this is what I'd do.

<details>
<summary>My makefile</summary>

This can be used to compile and run the program:

```console
> make PROG=myprog run
```

And here is the `GNUMakefile` itself:
```make
INCLUDES := /I$(WXWIN)/include/msvc /I$(WXWIN)/include
DEFINES := /D__WXMSW__ /D_CRT_SECURE_NO_WARNINGS

ifeq ($(PROG),)
    $(error Must define PROG)
endif

GUI ?= 1
DEBUG ?= 1
UNICODE ?= 1
CRTDLL ?= 1

ifneq ($(COMPILER_VERSION),)
    DEFINES += /DwxMSVC_VERSION=$(COMPILER_VERSION)
endif
COMPILER_PREFIX := vc$(COMPILER_VERSION)

ifneq ($(GUI),1)
    DEFINES += /DwxUSE_GUI=0
endif

ifeq ($(DEBUG),1)
    DEFINES += /D_DEBUG
else
    DEFINES += /DNDEBUG
endif

ifeq ($(UNICODE),1)
    DEFINES += /D_UNICODE
endif

ifeq ($(DLL),1)
    DEFINES += /DWXUSINGDLL
endif

ifeq ($(CRTDLL),1)
    CRTFLAG := /MD
else
    CRTFLAG := /MT
endif

CLFLAGS := /nologo /W4 /Zi /EHsc $(INCLUDES) $(DEFINES) $(CPPFLAGS)
ifeq ($(DEBUG),1)
    CRTFLAG := $(CRTFLAG)d
    CLFLAGS += /Od
else
    CLFLAGS += /O2
endif

CLFLAGS += $(CRTFLAG)

ifeq ($(DLL),1)
    LIBPATH := /libpath:$(WXWIN)/lib/$(COMPILER_PREFIX)_dll
else
    LIBPATH := /libpath:$(WXWIN)/lib/$(COMPILER_PREFIX)_lib
endif

LIBS := \
    advapi32.lib \
    kernel32.lib \
    ole32.lib \
    shell32.lib \
    user32.lib \
    wsock32.lib \

ifeq ($(GUI),1)
LIBS := $(LIBS) \
    comctl32.lib \
    comdlg32.lib \
    gdi32.lib \
    oleaut32.lib \
    rpcrt4.lib \
    winmm.lib \

endif

ifeq ($(GUI),1)
    SUBSYSTEM=windows
else
    SUBSYSTEM=console
endif

$(PROG).exe: $(PROG).cpp $(lastword $(MAKEFILE_LIST))
        cl $(CLFLAGS) $< /link /subsystem:$(SUBSYSTEM) $(LIBPATH) $(LIBS) $(LDFLAGS)

.PHONY: run
run: $(PROG).exe
        PATH="`cygpath -u $(WXWIN)/lib/$(COMPILER_PREFIX)_dll`:$(PATH)" ./$(PROG).exe

.PHONY: clean
clean:
        $(RM) -f $(PROG).exe $(PROG).ilk $(PROG).obj $(PROG).pdb vc*.pdb
```

</details>

**Comment by stephendgilbert** [comment]
Thank you both. I'll look into modifying your makefile, since it will be easier for the students to work with. In the meantime, I'll just modify the samples if I give them out to the students. Thanks again.
