### ISSUE TITLE
Should generic listctrl's DTOR be calling DoDeleteAllItems()?

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#24440]
In the generic list control's DTOR (`~wxListMainWindow()`), it calls `DoDeleteAllItems()`. I don't think this is right because under GTK+ I noticed this behavior:

- I derive from `wxListView` and `Bind` a function in my derived class to `wxEVT_LIST_DELETE_ALL_ITEMS`.
- In my function bound to `wxEVT_LIST_DELETE_ALL_ITEMS`, I do something like read from virtual data.
- When my control is destroyed, the DTOR in my derived class is called. In there, I might delete and/or disconnect from my virtual data.
- Then the base class DTORs are called in reverse order.
- When it gets down to `~wxListMainWindow()`, it calls `DoDeleteAllItems()`.
- This call to `DoDeleteAllItems()` will fire a `wxEVT_LIST_DELETE_ALL_ITEMS` event.
- This event will cause re-entrance into the function I bound to this event in my derived class (that was just destroyed and probably in a suspect state).

I don't think this should be happening and I don't experience this behavior in MSW's native control.

Also, I don't see any sort of necessary DTOR-style cleanup being done in `DoDeleteAllItems()`, so it may not even need to be called here.

======================
Platform: GTK+ (Linux)
wx: 3.3

**Comment by vadz** [comment]
I wonder if the fact that you're not getting `wxEVT_LIST_DELETE_ALL_ITEMS` under Windows is not just another bug, I thought you were supposed to get it there, but looking at the code now it seems that by the time the native control gets `LVN_DELETEALLITEMS`, `wxListCtrl` is already destroyed and its `MSWOnNotify()` is not called any longer...

This, of course, would just confirm that sending events from dtor is not great, but I don't see where else could we do it. From the control's own `wxWindowDestroyEvent` handler, perhaps? This is called just before it is destroyed.

In any case, in your particular case, I think the obvious solution is to unbind your event handler in your derived class dtor.

**Comment by Blake-Madden** [comment]
But if I don't bind to `wxEVT_LIST_DELETE_ALL_ITEMS`, then my derived function that handles clearing out my virtual data never gets called (when explicitly calling `DeleteAllItems()`).

I'll see if moving the event from the DTOR into the destroy event is an option.

**Comment by vadz** [comment]
You should bind to it, but unbind the handler in your class dtor -- this will ensure it's not called from the base class dtor executed later.

**Comment by Blake-Madden** [comment]
Oh, I see, thanks.

I'll still work on a PR to see if calling `DoDeleteAllItems()` from a destroy event appears safer.

**Comment by Blake-Madden** [comment]
Actually, calling `DoDeleteAllItems()` from a `wxWindowDestroyEvent` handler in the base class has the same issue and results in a crash by calling a pure virtual function. It appears that the `wxWindowDestroyEvent` handler is called *after* the base DTOR. So, the only solution is to call `Unbind` in my derived DTOR as you suggested.

I'll explain this workaround in a PR.

**Comment by vadz** [comment]
Sorry, I forgot to mention that you need to call `SendDestroyEvent()` from `wxGenericListCtrl` dtor to ensure it's generated early enough. As the comments elsewhere say, it's a good idea to call this function in the most derived class -- but unfortunately few classes do it currently.

**Comment by Blake-Madden** [comment]
Updated documentation
