### ISSUE TITLE
wxGrid GetDropTarget method always returns null

### ISSUE THREAD

**Issue by gsxruk** [wxWidgets/wxWidgets#24447]
### Description
I think this is a bug. I noticed GetDropTarget() of wxGrid always returns null even after setting the drop target using the SetDropTarget method.

A quick look at the source code appears to show that the SetDropTarget method is overridden in wxGrid and this calls SetDropTarget on the window returned by the GetGridWindow method. However, the GetDropTarget method does not appear to be overridden to do the same.

I assume the GetDropTarget method should also be overridden to retrieve the one set by SetDropTarget?

I am currently getting around this by calling GetGridWindow()->GetDropTarget() in my application.

Didn't think a how to reproduce etc was necessary for this. Let me know if I'm wrong and I'm happy to add one.

### Platform and Version Information

- wxWidgets version  you use: v3.2.4
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10 v22H2 (Build: 19045.4170)

**Comment by vadz** [comment]
Thanks, I agree that it's a bug and should be fixed by overriding `GetDropTarget()` to match. If you can make a PR fixing this, please do. TIA!

**Comment by gsxruk** [comment]
I will take a look at this tomorrow and see what I can do. I've not created PR's before.

**Comment by vadz** [comment]
Fixed by 5a2e25251556ed86b82e66342cbc07403046c8a8, thanks.
