### ISSUE TITLE
Add support for Intel C++

### ISSUE THREAD

**Issue by philmb3487** [wxWidgets/wxWidgets#24451]
Hi, here is a patch for adding support for Intel C++ compiler.
There's two intel compilers, but the old one is going to be deprecated, so I only bothered to test with 'icx'.

```patch
diff --git a/build/cmake/init.cmake b/build/cmake/init.cmake
index ed0cb89f7c..7ee134644b 100644
--- a/build/cmake/init.cmake
+++ b/build/cmake/init.cmake
@@ -178,6 +178,8 @@ if(WIN32)
         set(wxCOMPILER_PREFIX "gcc")
     elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
         set(wxCOMPILER_PREFIX "clang")
+    elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "IntelLLVM")
+        set(wxCOMPILER_PREFIX "icx")
     else()
         message(FATAL_ERROR "Unknown WIN32 compiler type")
     endif()
```

**Comment by sinetek** [comment]
I think the value should be `vc` instead of `icx` to make cmake happy.

**Comment by vadz** [comment]
We used to support icc in the past but I have no idea if it's still supported, i.e. if the code actually compiles/works correctly with it. Any serious effort to revive support for it should include adding a CI build testing it, otherwise it will just inevitably bit rot away again.

If you can do this, please open a PR adding a CI job using icc and the necessary changes to make it work. TIA!

**Comment by imciner2** [comment]
icc is different from icx. icx is the newer LLVM-based Intel compiler and icc is their older one that is now deprecated (to be removed in a year or two actually).

When I tried compiling wx with icx in August of last year it worked.

**Comment by sinetek** [comment]
Yes, I don't know what a CI is. So someone feel free to take this issue.

**Comment by vadz** [comment]
CI is "continuous integration" and refers to the builds done automatically on every push and, even more importantly, every PR done in this repository. It ensures that new changes at least don't break the build and it's even more crucial to have it for rarely used compilers like this one.

It's not difficult to add a new CI job, see `.github/workflows/ci.yml`, but someone needs to do it.

**Comment by ethindp** [comment]
I would love if this were added. Particularly since to my knowledge the Intel C/C++ compilers are better at codegen for x86/x86-64 than MSVC is.
