### ISSUE TITLE
Adding ability to change size of the text control in wxTextEntryDialog

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#24465]
I am showing a multiline `wxTextEntryDialog` for my users to enter a large block of text. However, the default size for this dialog isn't very tall (maybe enough space vertically for two lines of text). You always have to manually resize it to see larger text blocks. The CTOR doesn't have a size param (the control is hard-coded to `wxSize(300, wxDefaultCoord)`) and I don't see any way to change the size of the text control in the current API other than deriving from `wxTextEntryDialog` and accessing its `m_textCtrl` (which is protected).

That's easy enough, but would there be an in interest in having an API for this. For example, adding a `SetTextEntrySize(wxSize)` function?

**Comment by vadz** [comment]
It would make sense to add `wxSize` parameter to the dialog ctor, for consistency with just about everything else. This wouldn't allow precisely setting the text entry size, but do we really need this? IMHO just making the dialog "big enough" should be sufficient, in practice.
