### ISSUE TITLE
Update build to VS2022 (wx_vc17.sln)

### ISSUE THREAD

**Issue by derwin12** [wxWidgets/wxWidgets#24469]
Seems the last one is wx_vc17.sln  - which works - but is it worth going thru and updating things to VS2022?
Or is there nothing there to update?

**Comment by vadz** [comment]
Sorry what is exactly the issue here? You've already discovered that MSVS 2022 is supported, yet you open an issue about... what exactly?

**Comment by derwin12** [comment]
An enhancement not an issue.. .. wondered if there is something that should be updated to 2022.  There is a build for 15, 16,17 so I would presume there is some reason to have different versions. If not, fine .. just gets confusing to new users when you look for 2022 version.

**Comment by vadz** [comment]
An enhancement of what? I'm sorry but I genuinely have no idea what the problem is, please try to explain it.

There are different solution files for the different MSVS versions because each of them needs their own solution, obviously.

**Comment by derwin12** [comment]
I don't know the differences in 2017 and 2022. Perhaps its as simple as saving/committing a new wx_vc22.sln file. Just to keep things in sync with the newer version of VS that people are using.
If not fine .. close the feature request - just figured it should be atleast considered to see if there is a need to make this current.

**Comment by MaartenBent** [comment]
Visual Studio 2022 is version 17: https://en.wikipedia.org/wiki/Visual_Studio#History
