### ISSUE TITLE
[Nuget] package provided by https://www.nuget.org/packages/wxWidgets/ is not usable for 32 bits

### ISSUE THREAD

**Issue by Jarod42** [wxWidgets/wxWidgets#24470]
### Description

package provided by https://www.nuget.org/packages/wxWidgets/ is not usable for 32 bits

platform should be Win32 instead of x86 i.e

lib\native\x86 should be lib\native\Win32

and in build\wxWidgets.targets

- `..\lib\native\x64\$(Configuration);` should be `..\lib\native\$(Platform)\$(Configuration);`
- `'$(Platform)'!='x86'` should be `'$(Platform)'!='Win32'`

#### To Reproduce:

Use above nuget's package in visual studio 2019/2022 with any minimal wxWidgets sample targeting Win32 platform.

Build result in link error.

**Comment by vadz** [comment]
Sorry, we don't maintain this package and I don't know who does, so we can't do anything about it.
