### ISSUE TITLE
Dropdowns showing half a screen away from where they were clicked (on linux wayland and ultrawide screen)

### ISSUE THREAD

**Issue by JacekP1** [wxWidgets/wxWidgets#24473]
When hovering over the main dropdown dialogs while using wayland, the dropdown menu will not be under the menu item.

Recording:
[Screencast_20240413_213139.webm](https://github.com/wxWidgets/wxWidgets/assets/97543477/4caa5982-a1cc-4eca-87d4-906799c94a5f)

# Steps to reproduce:
1.Run linux and wayland (in my case fedora KDE wayland)
2.Have an ultrawide screen (works fine on my second normal screen)
3.Move the window so that the dropdowns should show up on the left half of the screen
4.Hover over the dropdown menu

# Tested apps:
KiCad (wxWidgets 3.2.4)
Audacity

**Comment by vadz** [comment]
This really looks like a kwin bug to me, there is absolutely no reason for it to show menus on an ultrawide display differently than on a normal one.

Can you run GTK demo example on your system? You should see the same thing with its menus.

**Comment by JacekP1** [comment]
Apologies for the long delay in my response.

I have finally managed to compile a menu example using gtk3 toolkit. It does not show the same bug, the menu dropdowns show up in their proper place. Does that mean it's a kwin bug?

Regards,
Jacek Pawlik

**Comment by JacekP1** [comment]
Hi,
[menu.zip](https://github.com/user-attachments/files/15858728/menu.zip)

I used the sample literally called menu. I'm attaching the compiled file here. 

Link to the github location of used sample:
https://github.com/wxWidgets/wxWidgets/tree/master/samples/menu

**Comment by vadz** [comment]
Sorry, there was apparently a misunderstanding. I thought you tested a pure GTK example, as I had asked, but you tested using our own `menu` sample, using wxGTK, right? I.e. we know that:

1. `menu` sample with GTK 3 works correctly.
2. KiCad doesn't work correctly.

Is this correct? And, if so, does your KiCad build use GTK 2 or GTK 3?

**Comment by JacekP1** [comment]
That is correct, sorry for my misunderstanding.

I'm using KiCad 8.0.2-1 which uses GTK+ 3.24

Full kicad version info:
```
Application: KiCad x86_64 on x86_64  
Version: 8.0.2-1.fc40, release build  
Libraries:  
    wxWidgets 3.2.4
    FreeType 2.13.2
    HarfBuzz 8.3.0
    FontConfig 2.15.0
    libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.3.0.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.10.6/openssl/zlib nghttp2/1.59.0 OpenLDAP/2.6.7
Platform: Fedora Linux 40 (KDE Plasma), 64 bit, Little endian, wxGTK, X11, KDE, wayland
Build Info:
    Date: Apr 27 2024 00:00:00
    wxWidgets: 3.2.4 (wchar_t,wx containers) GTK+ 3.24
    Boost: 1.83.0
    OCC: 7.6.3
    Curl: 8.6.0
    ngspice: 42
    Compiler: GCC 14.0.1 with C++ ABI 1019
```

Could you point me to some info on running the requested GTK demo? I'm not quite sure what I should be looking for.

**Comment by JacekP1** [comment]
That is correct, sorry for my misunderstanding.

I'm using KiCad 8.0.2-1 which uses GTK+ 3.24

Full kicad version info:
```
Application: KiCad x86_64 on x86_64  
Version: 8.0.2-1.fc40, release build  
Libraries:  
    wxWidgets 3.2.4
    FreeType 2.13.2
    HarfBuzz 8.3.0
    FontConfig 2.15.0
    libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.3.0.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.10.6/openssl/zlib nghttp2/1.59.0 OpenLDAP/2.6.7
Platform: Fedora Linux 40 (KDE Plasma), 64 bit, Little endian, wxGTK, X11, KDE, wayland
Build Info:
    Date: Apr 27 2024 00:00:00
    wxWidgets: 3.2.4 (wchar_t,wx containers) GTK+ 3.24
    Boost: 1.83.0
    OCC: 7.6.3
    Curl: 8.6.0
    ngspice: 42
    Compiler: GCC 14.0.1 with C++ ABI 1019
```

Could you point me to some info on running the requested GTK demo? I'm not quite sure what I should be looking for.

**Comment by vadz** [comment]
Sorry for the delay with the reply, but I don't think it's useful to run the GTK demo: if our `menu` sample works correctly, it means that the problem must be due to something KiCad is doing and not `wxMenu` per se.

But I have no idea what could it be, there are really not that many ways to create the menus. I'll try to check KiCad code where they're constructed, but if any KiCad developers have any ideas, i.e. if they already know of anything unusual that KiCad does with its menus, please let me know.

**Comment by imciner2** [comment]
I can't think of anything in KiCad that would be messing with the showing of a menubar menu. While we do override the menubar, that is just to change labels and remove the accelerator table, so everything else underlying it is the same. We just add our individual menus to the wxMenuBar object, and then it should process the events (and on GTK use the actual gtk menubar object).

That isn't to say there might be a platform-specific bug lurking in there somewhere - we had an odd one on macOS where the menu events from the menubar menu were percolating down into our event handling framework (https://gitlab.com/kicad/code/kicad/-/issues/16844), so anything is possible.

**Comment by vadz** [comment]
Thanks Ian, I agree that it seems pretty unlikely that KiCad breaks this in some way (and I definitely couldn't find anything suspicious looking at/searching in its code), but I just don't know why would the menu sample and KiCad behave differently, on the same system...

**Comment by vadz** [comment]
After posting the previous comment I had another idea: is it possible that KiCad is using XWayland somehow? If you just launch the menu sample from the terminal, it should definitely be using Wayland natively, but I'm not 100% sure about KiCad.

**Comment by imciner2** [comment]
Yes, we do force x11 backend on GTK by default, so thqt could be a difference. It would be god to test the menus sample under x11 as well using `GDK_BACKEND=X11` before the command.

**Comment by JacekP1** [comment]
Setting `GDK_BACKEND=X11` does not resolve the issue.

However, I have finally been able to test it on a laptop with both fedora and ubuntu. However I have not been able to reproduce the issue with my laptop connected via hdmi to the same screen.

Tested:
nvidia laptop - fedora gnome - wayland - no issue
nvidia laptop - fedora kde - wayland - no issue
nvidia laptop - ubuntu gnome - wayland & x11 - no issue
nvidia laptop - ubuntu kde - wayland & x11 - no issue

At this point I want to run the same OSs on my desktop to see if I can reproduce the issue on a fresh install.

**Comment by dsa-t** [comment]
> Setting `GDK_BACKEND=X11` does not resolve the issue.

`GDK_BACKEND=X11` is wrong, it should actually be `GDK_BACKEND=x11` (with lowercase `x`)
Setting it should **break** the `menu` sample, not fix KiCad.

**Comment by JacekP1** [comment]
Ah, thank you for pointing that out.

Sadly setting `GDK_BACKEND=x11` also doesn't break the menu sample.

I'll attempt to reproduce on another OS install with the same hardware today or tommorow, I'll let you know of the results.

**Comment by dsa-t** [comment]
> Sadly setting `GDK_BACKEND=x11` also doesn't break the menu sample.

Which exact commands do you use to set `GDK_BACKEND` and run the `menu` sample?

**Comment by dsa-t** [comment]
Does the window icon switch from the Wayland logo to wxWidgets logo?

**Comment by JacekP1** [comment]
Thank you for the question, thanks to that I realized I missed `export`.

With `export GDK_BACKEND=x11` the menu sample does indeed break. And it's logo in the menu bar does change to the wxWidgets logo.

Here is a screenshot showing how I start the menu sample, how I export GDK_BACKEND=x11, and the wxWidgets logo on the menu bar:
![image](https://github.com/user-attachments/assets/75e326c6-472a-4f10-8aae-6fe80b4f0379)

**Comment by vadz** [comment]
OK, thanks, so this is not at all KiCad-related, finally, which is nice to know — there is still some logic in the world. The issue is, then, that wxGTK menus don't seem to work correctly with the KDE XWayland server. I'm relatively confident that the issue is not in wxGTK itself but rather in KDE XWayland itself, could you please check if running any other application using GTK, if you have any on your system, shows the same problem if you do it by launching it with

```console
$ GDK_BACKEND=x11 /path/to/gtk/app
```

?

**Comment by JacekP1** [comment]
Sure.

Test apps installed from flathub:
GIMP 2.10.38 - GTK 2 - no issue normally - no issue when run with GDK_BACKEND=x11
GtkAtlantic 0.6.3 - GTK 3 - same issue even when run normally
efax-gtk 3.2.15 - GTK 3 - same issue even when run normally
qalculate 5.2.0 - GTK+ 3 - no issue normally - was unable to make it launch under xWayland
MyPaint 2.0.1+git.478280f.dirty - GTK 3.24.42 - same issue even when run normally
GtkStressTesting 0.7.6 - unknown GTK version - no issue, but there also isn't really a menu dropdown

I also tried to test gnome-terminal (installed via dnf) but was unable to make it launch under xWayland.

It seems that `GDK_BACKEND=x11` sadly doesn't work on flatpaks. 

This does show a pattern, which I think would be even more clear if I was actually able to force launch apps under xWayland. Do you know how I could achieve that? I found this:
`flatpak run --socket=x11 io.github.Qalculate`
But it doesn't seem to affect it, as there is still a wayland logo and the issue is still not there.

**Comment by dsa-t** [comment]
Why not install native rpm versions instead of flatpaks?

**Comment by JacekP1** [comment]
Mostly because I'm more used to flatpak and the cleanup is easier, but it is a fair question. I'll check out which of these have a fedora rpm.

**Comment by JacekP1** [comment]
RPM native apps:
GIMP - same result, no issue
Qalculate 4.9.0 - GTK+ 3 - no issue normally - issue present under xWayland

So qalculate was cleared up.

**Comment by vadz** [comment]
Well, it certainly looks like the problem is not wx-specific, so it's between GTK and KDE XWayland server (my money is on the latter).

We really can't do anything about this as we just use GTK, so I think this can be closed.

**Comment by JacekP1** [comment]
Agreed. I'll check out if the issue is present on GNOME and probably go report it to KDE. Thank you all for your assistance and have a nice day!
