### ISSUE TITLE
F39: wxWebView draws text with the background color -> "invisible" page

### ISSUE THREAD

**Issue by JoergHW** [wxWidgets/wxWidgets#24496]
#### Bug description:
The rendering of wxWebView per default has either ForegroundColour = BackgroundColour set or does not respect color.
Additionally I tried to convince the renderer to use a colour, but failed.
Using
 ```
   m_browser->SetPage
               (
                "<html><title>New Page</title>"
                "<body><h1 style=\"color:skyblue\">Page header</h1><p style=\"color:red;\">Created </p>using <tt>SetPage()</tt> method.</body></html>",  
                wxString()
               );
```
or
```
    m_browser->SetPage
               (
                "<html><title>New Page</title>"
                "<body><font color=\"red\">Created </font>using <tt>SetPage()</tt> method.</body></html>",
                wxString()
               );
```
instead of the original plain text, it did not make anything visible either. Just black on black.

#### Expected vs observed behaviour:
Expected: Text from a "web page" is visible.
Observed: Text is there (check with copy & paste), but the foreground and background are identical, so it is invisible.

#### Stack trace:
not relevant

#### Patch or snippet allowing to reproduce the problem:
samples/webview

#### To Reproduce:
1. start samples/webview/webview
2. Click on 'menu -> Set Page'
3. Observe

### Platform and version information
- wxWidgets version: 3.2.4
- wxWidgets port: wxGTK
- OS and its version: Fedora 39
  + GTK version: 3.24.41
  + Which GDK backend is used: X11
  + Desktop environment: Gnome
  + Current theme: Default + Dark

**Comment by JoergHW** [comment]
Downloaded wxWidgets-3.2.4 and build locally:
../configure --with-gtk --disable-tests --enable-webview --enable-webviewwebkit --disable-webviewedge --disable-webviewie --without-nanosvg --enable-debug_gdb --enable-debug

**Comment by vadz** [comment]
I don't see the problem running `GTK_THEME=Adwaita:dark ./webview` in master: the page is visible, but it also still uses the light mode, i.e. black on white text:

![image](https://github.com/wxWidgets/wxWidgets/assets/146917/91b88278-9734-492b-9b1a-1d0cf11c831e)

This might be due to WebViewGtk version difference, I wonder which one does Fedora 39 use?

**Comment by JoergHW** [comment]
@vadz Tried it your way, did not change anything. But I don't get the details about the render backend. I have installed:
webkit2gtk4.1-2.44.0-2.fc39.x86_64.rpm
webkit2gtk4.1-devel-2.44.0-2.fc39.x86_64.rpm
webkitgtk6.0-2.44.0-2.fc39.x86_64.rpm

![image](https://github.com/wxWidgets/wxWidgets/assets/17495690/0262e6b8-33b9-440d-b9fb-514aef8f8d85)

**Comment by vadz** [comment]
It could be that WebKitGtk 2.44 has implemented support for dark mode missing in my 2.42 and this breaks this somehow... Sorry, I really don't have time to debug this now.

**Comment by JoergHW** [comment]
light mode does not work better:
![image](https://github.com/wxWidgets/wxWidgets/assets/17495690/72a20b16-bbee-45fa-9025-68d5c768661c)

Take your time ...

**Comment by vadz** [comment]
This is really unexpected, it really looks like 2.44 broke compatibility in some way.

We probably need to start by looking at their changelog.

**Comment by paulcor** [comment]
It works fine for me on Fedora 39 with the exact same `webkit2gtk4.1-2.44.0-2.fc39.x86_64`. Maybe something to do with that "unable to construct a complete frambuffer" message.

**Comment by JoergHW** [comment]
Needed to upgrade to F40 for some reason. Tried the compiled example WITHOUT modification and it works now:

**Comment by JoergHW** [comment]
Just found this bug report for webkit: [https://bugs.webkit.org/show_bug.cgi?id=280210](https://bugs.webkit.org/show_bug.cgi?id=280210)
I can confirm, that "Setting `WEBKIT_DISABLE_DMABUF_RENDERER=1` fixes this issue." I am running with a NVidia card. On a laptop without external graphics card I don't need the workaround.

BTW: In the meantime I upgraded to F41 and the issue came back.

**Comment by vadz** [comment]
So, IIUC, there is nothing we can do about it and so it doesn't seem useful to leave this one open, does it?
