### ISSUE TITLE
nmake - give caller control of LIBOUTDIR

### ISSUE THREAD

**Issue by ncook-hxgn** [wxWidgets/wxWidgets#24492]
I'd quite like to control the output directory of the wxwidgets build as described by makefile.vc for nmake, so that it's easier for me to bundle into a nuget package.

From casual reading over the repo I gather CMake may be the future, but I couldn't find any documentation on the cmake build. Hopefully I can `cmake install` -- including the installation of license information (#24491).

... or maybe WxWidgets could be also-available as a nuget package? 🤞

**Comment by vadz** [comment]
nmake makefiles will probably be removed in some not too distant future because we don't have resources for maintaining them. Please use MSBuild project files instead, they are already quite customizable via the use of the `wx_local.props` file and could be made more flexible if needed.

**Comment by ncook-hxgn** [comment]
Aha I shall have a play around :)

**Comment by PBfordev** [comment]
IMO, CMake is best to build wxWidgets: It allows the best customization (achieved by editing setup.h and build command line arguments when using provided nmakefiles) as well as fine control over the build/installation.

wxWidgets CMake docs are here: https://docs.wxwidgets.org/latest/overview_cmake.html

As for exploring all CMake build options, I recommend using CMake-GUI (and checking "Grouped" and "Advanced" there).

**Comment by ncook-hxgn** [comment]
> IMO, CMake is best to build wxWidgets: It allows the best customization (achieved by editing setup.h and build command line arguments when using provided nmakefiles) as well as fine control over the build/installation.
> 
> wxWidgets CMake docs are here: https://docs.wxwidgets.org/latest/overview_cmake.html
> 
> As for exploring all CMake build options, I recommend using CMake-GUI (and checking "Grouped" and "Advanced" there).

eyyyy.. that's _loads_ better. Got wxwidgets installed somewhere nice and portable in like 5 commands, and didn't have to edit a thing <3
