### ISSUE TITLE
Implement, at least trivially, `NSApplicationDelegate.applicationSupportsSecureRestorableState`

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#24515]
Since updating to macOS 14.x, I'm getting the following warning on wx application startup:

```
WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

From what I can see, we wouldn't lose anything by doing what it wants, i.e. implementing this method and just returning `YES` from it, because I don't think we customize (or even support) restoring state anyhow.

But @csomor please let me know if I'm missing anything.

**Comment by csomor** [comment]
@vadz yes, just returning yes is ok, as we didn't customize state restoration
