### ISSUE TITLE
[macOS] widgets sample crashes immediately

### ISSUE THREAD

**Issue by hwiesmann** [wxWidgets/wxWidgets#24528]
### Description
Try to build the widgets sample on macOS with a newly installed wxWidgets version (configure --enable-debug, followed by make). Afterwards, compile the sample "widgets" using "make" and start the program. It crashes immediately because the pages are not correctly setup.

### Platform and version information

- wxWidgets version you use: today's most up to date developer built
- wxWidgets port you use: macOS 14.4.1

**Comment by vadz** [comment]
Do you have the stack trace please?

**Comment by hwiesmann** [comment]
The program fails because

../../../samples/widgets/widgets.cpp(1383): assert "*it" failed in SetUpWidget(): null widget
