### ISSUE TITLE
[macOS] Alignment of a slider's current value looks strange

### ISSUE THREAD

**Issue by hwiesmann** [wxWidgets/wxWidgets#24531]
### Description
I have set the minimum value of the slider to -100 in the widgets sample (see screenshot attached). 
<img width="1267" alt="Bildschirmfoto 2024-05-14 um 22 33 54" src="https://github.com/wxWidgets/wxWidgets/assets/518892/7729c633-b969-4aaf-9e03-60913febcbca">

The current value is zero. Nevertheless, the label is positioned to the left of the slider's knob. This looks strange. I do not know how it looks like in other OSes  but I prefer a center alignment.
Any objections or should I prepare a fix?

PS: Because of the odd ticks frequency it looks like the slider is not positioned at zero but this is actually the case.

**Comment by vadz** [comment]
Yes, this definitely looks wrong, TIA for fixing this!
