### ISSUE TITLE
Documentation typo - wxListColumnFormat

### ISSUE THREAD

**Issue by aureliencc** [wxWidgets/wxWidgets#24548]
Hello, 

I think I found a typo in the documentation, the description for "wxListColumnFormat" is : 

_Column format (MSW only except wxLIST_FORMAT_LEFT)_

Source : [https://docs.wxwidgets.org/latest/interface_2wx_2listctrl_8h.html#afddccbb0d7cf18f9b205f00efc5738d0](https://docs.wxwidgets.org/latest/interface_2wx_2listctrl_8h.html#afddccbb0d7cf18f9b205f00efc5738d0)

But I guess it should have been : 

_Column format (MSW only **accept** wxLIST_FORMAT_LEFT)_

As none of the others values seems to work on Windows.

Regards,

**Comment by PBfordev** [comment]
Column alignment works in `wxListCtrl` report mode on Windows:
![wx-listctrl-col-alignment](https://github.com/wxWidgets/wxWidgets/assets/12495521/cdedd61f-6779-4c85-8640-cd9f54fa8006)

<details>
<summary>Code</summary>

```cpp
#include <wx/wx.h>
#include <wx/listctrl.h>

class MyApp : public wxApp
{
public:   
    bool OnInit() override
    {
        wxFrame* frame = new wxFrame(nullptr, wxID_ANY, "Test", wxDefaultPosition, wxSize(600, 600));

        wxListCtrl* listCtrl = new wxListCtrl(frame, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT);
        listCtrl->AppendColumn("Left", wxLIST_FORMAT_LEFT);
        listCtrl->AppendColumn("Centre", wxLIST_FORMAT_CENTRE);
        listCtrl->AppendColumn("Right", wxLIST_FORMAT_RIGHT);
            
        listCtrl->InsertItem(0, "Short");
        listCtrl->SetItem(0, 1, "Short");
        listCtrl->SetItem(0, 2, "Short");

        listCtrl->InsertItem(1, "Very looooooong");
        listCtrl->SetItem(1, 1, "Very looooooong");
        listCtrl->SetItem(1, 2, "Very looooooong");

        listCtrl->SetColumnWidth(0, wxLIST_AUTOSIZE);
        listCtrl->SetColumnWidth(1, wxLIST_AUTOSIZE);
        listCtrl->SetColumnWidth(2, wxLIST_AUTOSIZE);
        
        frame->Show();
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```
</details>

**Comment by aureliencc** [comment]
Hello @PBfordev,

Thank you for your reply.

I'm using `wxLC_REPORT | wxLC_VIRTUAL` flags and I was not able to make it work on my system.

**Comment by vadz** [comment]
I think the documentation is indeed wrong, but only because alignment is supported under all platforms and not just in wxMSW.

As for alignment not working for you, please try to reproduce the problem with the minimal changes to the listctrl sample and open a separate issue for it. Thanks!

**Comment by aureliencc** [comment]
The following minimal `wxListCtrl` view example works : 

`
#include <vector>
#include <string>
#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif
#include <wx/listctrl.h>

// =================================
class List : public wxListCtrl {

public:
    List(wxWindow* parent);
    wxString OnGetItemText(long item, long column) const;
    void AddAStr(const std::string& s);

private:
    void Update();

    std::vector<std::string> m_list{};
};

// =================================

List::List(wxWindow* parent)
    : wxListCtrl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT | wxLC_VIRTUAL)
{
    AppendColumn(L"LEFT", wxLIST_FORMAT_LEFT);
    AppendColumn(L"CENTRE", wxLIST_FORMAT_CENTRE);
    AppendColumn(L"RIGHT", wxLIST_FORMAT_RIGHT);
}

wxString List::OnGetItemText(long item, long column) const
{
    if (item < 0 || item >= m_list.size()) {
        return "invalid index";
    }
    switch (column) {
        case 0:
        case 1:
        case 2: { return m_list[item]; } break ;
        default: { return "invalid column"; }
    }
}

void List::Update()
{
    SetItemCount(m_list.size());
    Refresh();
}

void List::AddAStr(const std::string& s)
{
    m_list.push_back(s);
    Update();
}
// =================================

class MyApp : public wxApp
{
        bool OnInit() override
    {
        auto* frame = new wxFrame(nullptr, wxID_ANY, "foo", wxDefaultPosition, wxDefaultSize);

        auto* m_list_view{ new List(frame) };
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        frame->Show(true);

        return true;
    }
}; wxIMPLEMENT_APP(MyApp);

`

Unfortunately, I cannot get it to work in my project. I only have one column, I want it to be centered.

**Comment by vadz** [comment]
Sorry, but you really need to provide a simple example showing what does _not_ work to allow understanding what the problem is, I don't see any point in showing a working example.

If you can do it, please create a new issue with such example. Thanks!

**Comment by aureliencc** [comment]
The following minimal `wxListCtrl` view example works : 

```
#include <vector>
#include <string>
#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif
#include <wx/listctrl.h>

// =================================
class List : public wxListCtrl {

public:
    List(wxWindow* parent);
    wxString OnGetItemText(long item, long column) const;
    void AddAStr(const std::string& s);

private:
    void Update();

    std::vector<std::string> m_list{};
};

// =================================

List::List(wxWindow* parent)
    : wxListCtrl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT | wxLC_VIRTUAL)
{
    AppendColumn(L"LEFT", wxLIST_FORMAT_LEFT);
    AppendColumn(L"CENTRE", wxLIST_FORMAT_CENTRE);
    AppendColumn(L"RIGHT", wxLIST_FORMAT_RIGHT);
}

wxString List::OnGetItemText(long item, long column) const
{
    if (item < 0 || item >= m_list.size()) {
        return "invalid index";
    }
    switch (column) {
        case 0:
        case 1:
        case 2: { return m_list[item]; } break ;
        default: { return "invalid column"; }
    }
}

void List::Update()
{
    SetItemCount(m_list.size());
    Refresh();
}

void List::AddAStr(const std::string& s)
{
    m_list.push_back(s);
    Update();
}
// =================================

class MyApp : public wxApp
{
        bool OnInit() override
    {
        auto* frame = new wxFrame(nullptr, wxID_ANY, "foo", wxDefaultPosition, wxDefaultSize);

        auto* m_list_view{ new List(frame) };
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        m_list_view->AddAStr("A long str");
        frame->Show(true);

        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```

Unfortunately, I cannot get it to work in my project. I only have one column, I want it to be centered.

**Comment by PBfordev** [comment]
After testing, it seems that the right or center alignment does not work in the very first column, which is always aligned to the left, regardless of requested alignment.

**Comment by aureliencc** [comment]
This is a known issue : [https://forums.wxwidgets.org/viewtopic.php?t=6675](https://forums.wxwidgets.org/viewtopic.php?t=6675)

I'm sorry, I did not found this topic while debugging.

Thank you for your help,

**Comment by PBfordev** [comment]
Ah, sorry, this is the limitation of the native control, but as noted, can be worked around:
https://learn.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-lvcolumna#remarks
![wx-listctrl-col-alignment](https://github.com/wxWidgets/wxWidgets/assets/12495521/33350dc0-1902-406e-92bf-81df94fce983)

<details>
<summary>Minimal Code</summary>

```cpp
#include <wx/wx.h>
#include <wx/listctrl.h>

class List : public wxListCtrl
{
public:
    List(wxWindow* parent)
        : wxListCtrl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT | wxLC_VIRTUAL)
    {
        AppendColumn("LEFT", wxLIST_FORMAT_LEFT);
        AppendColumn("CENTRE", wxLIST_FORMAT_CENTRE);

        DeleteColumn(0);
        SetItemCount(5);
    }

    wxString OnGetItemText(long item, long column) const override
    {
        return wxString::Format("C%ld I%ld", column, item);
    }
};

class MyApp : public wxApp
{
    bool OnInit() override
    {
        wxFrame* frame = new wxFrame(nullptr, wxID_ANY, "Test Frame");
        new List(frame);
        frame->Show();
        return true;
    }
}; wxIMPLEMENT_APP(MyApp);
```
</details>
