### ISSUE TITLE
wxGridBagSizer item clipping when vgap/hgap are different and some items span multiple rows/cols

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24550]
### Description

If:
- vgap and hgap are different in wxGridBagSizer
- It has items spanning multiple rows (buttons in the example)

then row heights are not calculated correctly, clipping the buttons:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/06a8789f-f998-4836-89e3-c28dadedd578)

If the hgap is set to 0, equal to vgap, it looks normal:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/532df99d-9232-4da4-9678-1a8563b26894)

wxFormBuilder 4.1.0 project: [manager_icons.fbp.txt](https://github.com/wxWidgets/wxWidgets/files/15404861/manager_icons.fbp.txt)
Merged cpp+header file: [noname.cpp.txt](https://github.com/wxWidgets/wxWidgets/files/15404891/noname.cpp.txt)

---

Looks like these lines are wrong:

https://github.com/wxWidgets/wxWidgets/blob/7d47bc0e71558d5edff51203f98b5baab310d08b/src/common/gbsizer.cpp#L605

https://github.com/wxWidgets/wxWidgets/blob/7d47bc0e71558d5edff51203f98b5baab310d08b/src/common/gbsizer.cpp#L644

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by vadz** [comment]
So is the problem fixed by exchanging the `H` and `V` gaps (I don't know this code at all but it would seem to be more logical to subtract vertical gap from the height and horizontal gap from the width rather than vice versa)?

**Comment by dsa-t** [comment]
Yes, it does seem to fix the issue:

![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/71bc7550-9a26-46f8-af89-2f8c19d24650)

**Comment by vadz** [comment]
Thanks for testing, will push the fix soon.
