### ISSUE TITLE
wxBitmapComboBox bitmaps are rendered at x4 size at x2 window scaling on wxGTK

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24563]
#### To Reproduce:
1. Set window scaling to 200%
2. Open `widgets` sample, `BitmapCombobox` page
3. Insert image from file
4. Select "cursor.png" from wx

As can be seen on the screenshot, one bitmap pixel takes 4 pixels on screen:
![Screenshot 2024-05-27 190406](https://github.com/wxWidgets/wxWidgets/assets/37658952/e535dfc9-a950-4b64-8a58-0a4c5899fcc6)

Reference, 100% window scaling:
![Screenshot 2024-05-27 190503](https://github.com/wxWidgets/wxWidgets/assets/37658952/2fd420e3-1b44-4b01-842e-c8aab9c1dac7)

---

What appears to be happening is, in `wxBitmapComboBox::SetItemBitmap`:
1. `bitmap.GetBitmapFor(this);` upscales the original bitmap (32x32) to 64x64 and sets the scale factor to 2
2. It is converted to `GdkPixbuf`
3. `GtkCellRendererPixbuf` doesn't receive the scale factor, so assumes it's 1, which causes it to render at x4 scale

`GtkCellRendererPixbuf` also has [`surface` property](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.10.6/gtk/gtkcellrendererpixbuf.c#L345) where it would be possible to pass `cairo_surface_t *` with correct device scale, e.g.:
```cpp
            double scaleFactor = bmp.GetScaleFactor();
            cairo_surface_t *surface = gdk_cairo_surface_create_from_pixbuf(pixbuf, 1, NULL);
            cairo_surface_set_device_scale(surface, scaleFactor, scaleFactor);
```
, but it's a boxed type, not an object type (like a `GdkPixbuf`), so I don't know how to wrap it properly.

Specifically, trying to use
```с
    store = gtk_list_store_new( 2, G_TYPE_BOXED, G_TYPE_STRING );
```

fails with
```
(widgets:1599530): Gtk-WARNING **: 20:11:31.464: ../../../../gtk/gtkliststore.c:436: Invalid type GBoxed
```

The checks are here: https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.41/gtk/gtkliststore.c#L434, https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.41/gtk/gtktreedatalist.c?ref_type=tags#L65

There's also a `stock-size` property, but it doesn't seem to affect the size.

---

Also see https://gitlab.com/kicad/code/kicad/-/issues/16698

---

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 21.1
  
  + GTK version: 3.24.33-1ubuntu2.1
  + Which GDK  backend is used: X11
  + Desktop environment : XFCE

**Comment by vadz** [comment]
I can indeed see this, thanks, I'll take a look.

**Comment by vadz** [comment]
AFAICS we need to do the same thing we do in wxDVC and use a custom renderer in order to respect the bitmap scale factor.

@paulcor Please let me know if you know of a better way, otherwise I'll try to implement this soon.

**Comment by dsa-t** [comment]
@paulcor Nice commit, thanks!

Though I think it's better pass scale 1 to `gdk_cairo_surface_create_from_pixbuf`,
then call:
```c++
double scaleFactor = bmp.GetScaleFactor();
cairo_surface_set_device_scale(surface, scaleFactor, scaleFactor);
```
to support fractional scale factors.

**Comment by dsa-t** [comment]
And `GetItemBitmap` can be implemented like this:

```patch
diff --git a/src/gtk/bmpcbox.cpp b/src/gtk/bmpcbox.cpp
index bdbc976d3c..e8d27b3448 100644
--- a/src/gtk/bmpcbox.cpp
+++ b/src/gtk/bmpcbox.cpp
@@ -253,11 +253,42 @@ wxBitmap wxBitmapComboBox::GetItemBitmap(unsigned int n) const
         wxGtkValue value;
         gtk_tree_model_get_value( model, &iter,
                                   m_bitmapCellIndex, value );
-        GdkPixbuf* pixbuf = (GdkPixbuf*) g_value_get_object( value );
-        if ( pixbuf )
+
+        GdkPixbuf *pixbuf = nullptr;
+        double scaleFactor = 1.0;
+
+#ifdef __WXGTK3__
+        if (wx_is_at_least_gtk3(10))
         {
-            g_object_ref( pixbuf );
-            bitmap = wxBitmap(pixbuf);
+            cairo_surface_t *surface = (cairo_surface_t *)g_value_get_boxed(value);
+
+            if (surface)
+            {
+                const int w = cairo_image_surface_get_width(surface);
+                const int h = cairo_image_surface_get_height(surface);
+                pixbuf = gdk_pixbuf_get_from_surface(surface, 0, 0, w, h);
+
+                double xscale = 1.0, yscale = 1.0;
+                cairo_surface_get_device_scale(surface, &xscale, &yscale);
+                scaleFactor = (xscale + yscale) / 2.0;
+
+                if ( pixbuf )
+                {
+                    bitmap = wxBitmap(pixbuf);
+                    bitmap.SetScaleFactor(scaleFactor);
+                }
+            }
+        } else
+#endif
+        {
+            pixbuf = (GdkPixbuf *)g_value_get_object(value);
+
+            if ( pixbuf )
+            {
+                g_object_ref(pixbuf);
+                bitmap = wxBitmap(pixbuf);
+                bitmap.SetScaleFactor(scaleFactor);
+            }
         }
     }
 

```
[bmpcbox-getitembitmap.patch](https://github.com/wxWidgets/wxWidgets/files/15463033/bmpcbox-getitembitmap.patch)

**Comment by paulcor** [comment]
> to support fractional scale factors.

I don't think GTK supports fractional scaling for anything except text, but sure, why not.

> And `GetItemBitmap` can be implemented like this:

Yeah, oops, I'm already on that.

**Comment by dsa-t** [comment]
Btw, won't this fail to build against gtk versions older then 3.10 due to missing `gdk_cairo_surface_create_from_pixbuf` definition?

```cpp
#ifdef __WXGTK3__
            if (wx_is_at_least_gtk3(10))
            {
...
                cairo_surface_t* surface = gdk_cairo_surface_create_from_pixbuf(
                    bmp.GetPixbuf(), 1, gtk_widget_get_window(m_widget));
...
            }
#endif
```

Isn't it better to use
```cpp
#if GTK_CHECK_VERSION(3,10,0)
```
?

And if built against gtk 3.10+, then run with gtk 3.9, won't it fail at runtime with "undefined symbol" error in any case?

**Comment by paulcor** [comment]
> Btw, won't this fail to build against gtk versions older then 3.10

Ugh, yes.

**Comment by dsa-t** [comment]
Can this be backported into 3.2.6?

**Comment by vadz** [comment]
This has been fixed in master and I've now also backported the 3 commits above to 3.2 backports branch, so closing.
