### ISSUE TITLE
wxWindow::HasFlag uses int instead of long as a parameter

### ISSUE THREAD

**Issue by hwiesmann** [wxWidgets/wxWidgets#24578]
### Description
The method wxWindow::HasFlag(int) uses int as a parameter although the member variable m_windowStyle that is tested by HasFlag(int) uses long as its type.

Long has to be used as the parameter type because some flags (border flags) use 4 bytes. According to C++ specifications long is guaranteed to have 4 bytes (or better 32 bits) but not int.

PS: For most (almost all?) systems int should be sufficient, though. Nevertheless, it is still wrong, I believe.

### Platform and version information

- wxWidgets version you use: latest master branch
- wxWidgets port you use: macOS 14.4.1

**Comment by vadz** [comment]
Sorry, I just don't think we're going to do anything about this, the confusing between `int` and `long` in wx API is endemic and it just doesn't seem worth to do anything about it. Yes, it was a mistake but it was done 30 years ago and didn't result in anything really catastrophic AFAIK, so we'll just continue ignoring it.
