### ISSUE TITLE
Maximize(true) obscures the taskbar

### ISSUE THREAD

**Issue by hongnod** [wxWidgets/wxWidgets#24570]
#### Bug description:
On Windows 10:
JotFrame::JotFrame(const wxString& title): wxFrame(NULL, wxID_ANY, title, wxDefaultPosition, wxDefaultSize, wxRESIZE_BORDER)

JotFrame *frame = new JotFrame("Minimal");

frame->Maximize();
this Frame will be FullScreen.
as: https://forums.wxwidgets.org/viewtopic.php?t=50634
#### Expected vs observed behaviour:
Expected: Maximal window
observed :Full screen window

### Platform and version information

- wxWidgets version  you use: master 67951782cbe5aadada6c4389097b2387ab88d920
- wxWidgets port  you use:wxMSW
- OS  and its version: Windows 10
  
  + Current theme: Dark

**Comment by PBfordev** [comment]
As I observed [on the forum](https://forums.wxwidgets.org/viewtopic.php?p=220328#p220328), this seems to be caused by a specific combination of window style flags (`wxMAXIMIZE_BOX` not used) and is reproducible with a pure native code.

**Comment by hongnod** [comment]
I just wonder if there a solution without wxMAXIMIZE_BOX.  I have a Qt app with Frameless style without this issue. and I  guess vscode has a workroud.

**Comment by hongnod** [comment]
I found this topic. look like need to hack  using SystemParametersInfo. find this function in qt-base codebase
https://microsoft.public.win32.programmer.ui.narkive.com/HBwKVH0S/sw-maximize-is-same-as-fullscreen

**Comment by hongnod** [comment]
This works for me：
`
JotFrame::JotFrame(const wxString& title)
       : wxFrame(NULL, wxID_ANY, title, wxDefaultPosition, wxDefaultSize, wxRESIZE_BORDER) //wxRESIZE_BORDER for compatible
{
   ....
   wxBoxSizer* mainBoxSizer=new wxBoxSizer(wxVERTICAL);
   titlebar = new TitleBar(this,title);
   mainBoxSizer->Add(titlebar,wxSizerFlags(0).Expand().Border(wxLEFT|wxTOP|wxRIGHT,2)); //Border is important,or frame cannot be resize by mouse
   mainBoxSizer->Add(sizer,wxSizerFlags(1).Expand().Border(wxLEFT|wxBOTTOM|wxRIGHT,2));
   SetSizerAndFit(mainBoxSizer);   
   setResizeable(); //extend frame to client.
   ....
}

void JotFrame::setResizeable(bool resizeable)
{
    bool visible = IsVisible();
    m_bResizeable = resizeable;
#ifdef __WXMSW__
    HWND hwnd = this->GetHandle();
    DWORD style = ::GetWindowLong(hwnd, GWL_STYLE);
    if (m_bResizeable){
           this->SetWindowStyleFlag(GetWindowStyleFlag()|wxMAXIMIZE_BOX);
           ::SetWindowLong(hwnd, GWL_STYLE, WS_CAPTION | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX);
        }else{
            this->SetWindowStyleFlag(GetWindowStyleFlag()&~wxMAXIMIZE_BOX);
            ::SetWindowLong(hwnd, GWL_STYLE, style & ~WS_MAXIMIZEBOX & ~WS_CAPTION);
        }
        const MARGINS shadow = {0,0,0,0};

        DwmExtendFrameIntoClientArea(hwnd, &shadow);
      Show(visible);  //need revise
#endif
}
#ifdef __WXMSW__
WXLRESULT JotFrame::MSWWindowProc(WXUINT nMsg, WXWPARAM wParam, WXLPARAM lParam)
{
        switch (nMsg)
        {
            case WM_NCCALCSIZE:
            {
                wxLogDebug("hit1");
                RECT* client_rect = wParam ?
                &(reinterpret_cast<NCCALCSIZE_PARAMS*>(lParam)->rgrc[0]) :
                reinterpret_cast<RECT*>(lParam);
                HMONITOR monitor = MonitorFromWindow(GetHandle(), MONITOR_DEFAULTTONULL);
                if (!monitor)
                {
                    monitor = MonitorFromRect(client_rect, MONITOR_DEFAULTTONULL);
                    if (!monitor) {return 0;}
                }
                // POINT ptMouse = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam)};
                // PostMessageW(GetHandle(), WM_NCHITTEST, 0, MAKELPARAM(ptMouse.x, ptMouse.y));
               return wParam?WVR_REDRAW : 0;
            }
         case WM_NCHITTEST:
            {
            // Get the point coordinates for the hit test.
            wxLogDebug("hit2");
            POINT ptMouse = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam)};

            // Get the window rectangle.
            RECT rcWindow;
            GetWindowRect(GetHandle(), &rcWindow);

            // Get the frame rectangle, adjusted for the style without a caption.
            RECT rcFrame = { 0 };
            AdjustWindowRectEx(&rcFrame, WS_OVERLAPPEDWINDOW & ~WS_CAPTION, FALSE, NULL);

            // Determine if the hit test is for resizing. Default middle (1,1).
            USHORT uRow = 1;
            USHORT uCol = 1;
            bool fOnResizeBorder = false;

            // Determine if the point is at the top or bottom of the window.
            if (ptMouse.y >= rcWindow.top && ptMouse.y < rcWindow.top + 5/*TOPEXTENDWIDTH*/)
            {
                fOnResizeBorder = (ptMouse.y < (rcWindow.top - rcFrame.top));
                uRow = 0;
            }
            else if (ptMouse.y < rcWindow.bottom && ptMouse.y >= rcWindow.bottom -5 /*BOTTOMEXTENDWIDTH*/)
            {
                uRow = 2;
            }

            // Determine if the point is at the left or right of the window.
            if (ptMouse.x >= rcWindow.left && ptMouse.x < rcWindow.left +5 /*LEFTEXTENDWIDTH*/)
            {
                uCol = 0; // left side
            }
            else if (ptMouse.x < rcWindow.right && ptMouse.x >= rcWindow.right - 5/*RIGHTEXTENDWIDTH*/)
            {
                uCol = 2; // right side
            }

            // Hit test (HTTOPLEFT, ... HTBOTTOMRIGHT)
            LRESULT hitTests[3][3] =
            {
                { HTTOPLEFT,    fOnResizeBorder ? HTTOP : HTCAPTION,    HTTOPRIGHT },
                { HTLEFT,       HTNOWHERE,     HTRIGHT },
                { HTBOTTOMLEFT, HTBOTTOM, HTBOTTOMRIGHT },
            };

            return hitTests[uRow][uCol];
            } //end case WM_NCHITTEST


        default:
            return wxFrame::MSWWindowProc(nMsg, wParam, lParam);
        }
        return 0;
}
#endif
`
