### ISSUE TITLE
a change for pressing enter on unavailable "grade out" context menu options

### ISSUE THREAD

**Issue by HanaDadfar** [wxWidgets/wxWidgets#24587]
### Description
hi.
I reported and wel explaned what is needed hear, it was the incorrect place for it, so people helpped me to be directed hear, because the problem is related to keyboard pressing event
https://github.com/nvaccess/nvda/issues/16638
thanks, i really hope that this gets implemented soon, as nvda and all it's addons are using wx, and this is the correct action for the grade out menu options, which qt already does this, read the complete discription on the link provided above
Thanks

**Comment by MaartenBent** [comment]
Hi,

I think that is just how the Windows context menus work. For example it does the same with the disabled 'paste' option in Windows Explorer context menu.
 
I don't see a win32 API to change this behavior. There is nothing to stop a menu from closing or to detect what triggered the close.

qt likely draws their own menu's, and can deal with it differently. But wxWidgets relies on the native Windows elements.

**Comment by HanaDadfar** [comment]
@MaartenBent yes, all windows context menus and everything except qt is like this which is incorrect for disabled options, qt is the one which does the correct job for these options. So, I wanted to report this and make all frameworks such as wx, mfc, etc, all change this job to how qt does it. So, you aren't able to change this in wx right? and It needs to be changed somewhere else?

**Comment by HanaDadfar** [comment]
@MaartenBent but, I think you can, because,
you said.
I don't see a win32 API to change this behavior. There is nothing to stop a menu from closing or to detect what triggered the close.
but, double klicking on a disabled context menu option doesn't closes the menu and acts as exactly as how it should, like qt. Only pressing enter on them closes the menu. So, can't you check about double klick on those options, and aply the same for the enter key as wel? If this is doable, it would be satisfying. Simple, enter key on disabled context menu options should act as double klick on disabled context menu options.

**Comment by MaartenBent** [comment]
I'm afraid not. This is all handled by Windows internally. wxWidgets just gets an event-message when an item is selected or when the menu is closed.

Even if we try to detect when the enter-key is used on a disabled item, there is no way to prevent the menu from closing.

**Comment by HanaDadfar** [comment]
@MaartenBent what about my last comment? as I said, double klick or left klicking on a disabled option doesn't close the menu and it acts correctly, so, can't you make the enter key to act same as double klick "left klick" for disabled options?

**Comment by MaartenBent** [comment]
No, because wxWidgets does not process the mouse and keyboard events of a menu. This is all done by Windows. And then Windows informs wxWidgets when a menu item is selected and when the menu is closed.

**Comment by HanaDadfar** [comment]
@MaartenBent ok, now I understand. So, Where can we report this so they have the controle of this so they can change this?

**Comment by MaartenBent** [comment]
The Feedback Hub app from Microsoft seems the way to do this. I think this app is preinstalled with Windows. Else you can download it from the Microsoft Store.
https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

**Comment by HanaDadfar** [comment]
@MaartenBent ok, but i'm stil using windows 10, and microsoft is now mainly focused on windows 11. So, even if I report this and it gets implemented, would it reflect windows 10 as wel? or only windows 11 now?

**Comment by MaartenBent** [comment]
I don't know, I cannot speak for Microsoft.
Windows 10 is still receiving updates, so maybe.

**Comment by vadz** [comment]
As Maarten explained, we really can't do anything about this, we just use the native menus as provided by Windows, sorry.
