### ISSUE TITLE
glcanvas.h enum/macro conflict with X.h

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24585]
### Description

When including `glcanvas.h` on Linux, there's a conflict with a macro defined in `X.h`

```cpp
In file included from kicad_dir/common/draw_panel_gal.cpp:41:
In file included from kicad_dir/include/gal/opengl/opengl_gal.h:42:
In file included from kicad_dir/include/gal/hidpi_gl_canvas.h:31:
In file included from wxWidgets_dir/install-vs-qt/include/wx-3.3/wx/glcanvas.h:17:
wxWidgets_dir/install-vs-qt/include/wx-3.3/wx/app.h:690:9: error: expected identifier
        Success,
        ^
/usr/include/X11/X.h:350:21: note: expanded from macro 'Success'
#define Success            0    /* everything's okay */
                           ^
```

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxQT
- OS  and its version: Linux Mint 21.1
  + Which GDK  backend is used: X11

**Comment by vadz** [comment]
Weird, I can't reproduce this for some reason. And looking at `GL/gl.h` on my system I don't see where does it include `X11/X.h`, could KiCad be including it itself from somewhere else?

Anyhow, we can protect against this by just `#undef Success` or we could rename this recently added enum element to something else.

**Comment by dsa-t** [comment]
KiCad doesn't include `X.h` directly anywhere in the source tree. It's probably included via one of the external headers.

**Comment by dsa-t** [comment]
It is included via:

-`include/gal/opengl/kiglew.h`
-`/usr/include/GL/glxew.h`
-`/usr/include/X11/Xlib.h`
-`/usr/include/X11/X.h`

**Comment by dsa-t** [comment]
And due to https://gitlab.com/kicad/code/kicad/-/blob/acec5552c012198ec2f2d497e91b812a183dbbfc/include/gal/opengl/gl_utils.h

we must include both `GL/glxew.h` and `wx/glcanvas.h`

**Comment by vadz** [comment]
Thanks for digging into this, this does explain how it happens.

Upon further thought, I think renaming the constant is better, even if I have to update its name in my own application, so I've create the linked PR to do it.
