### ISSUE TITLE
For wxPoint2DDouble, wxPoint2DInt: operator/= and operator*= for wxDouble, wxInt32 args are undefined

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24604]
### Description
When trying to run this code:

```cpp
wxPoint2DDouble() /= 5.0;
```

I get this error:
```
symbol lookup error: libwx_gtk3u_core-3.3.so.0: undefined symbol: _ZN15wxPoint2DDoubledVEd
```
---
VScode shows these as unimplemented:

wxPoint2DInt:
```cpp
    inline wxPoint2DInt& operator*=(wxDouble n);
    inline wxPoint2DInt& operator*=(wxInt32 n);

    inline wxPoint2DInt& operator/=(wxDouble n);
    inline wxPoint2DInt& operator/=(wxInt32 n);
```

wxPoint2DDouble:
```cpp
    inline wxPoint2DDouble& operator*=(wxDouble n);
    inline wxPoint2DDouble& operator*=(wxInt32 n);

    inline wxPoint2DDouble& operator/=(wxDouble n);
    inline wxPoint2DDouble& operator/=(wxInt32 n);
```

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint

**Comment by vadz** [comment]
I'll add the implementation of the missing operators, thanks, but I am very puzzled by the existence of operator overloads taking 2 points as IMO they makes no sense at all, so I'd prefer to completely delete (well, deprecate for now) those.

@csomor Do you remember why were these added, by chance?

**Comment by csomor** [comment]
> I'll add the implementation of the missing operators, thanks, but I am very puzzled by the existence of operator overloads taking 2 points as IMO they makes no sense at all, so I'd prefer to completely delete (well, deprecate for now) those.
> 
> @csomor Do you remember why were these added, by chance?

I'm sorry, I don't remember. I could have been looking at a 2D geometry library at that point, to find out what they included. The geometrical interpretation could be a scaling on x and y with different factors. But now these would be done using matrices anyway. So yes, go ahead, deprecate and mark for deletion :-)
