### ISSUE TITLE
Documentation for wxString::Pad() is incorrect

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#24627]
The current documentation for [wxString::Pad()](https://docs.wxwidgets.org/latest/classwx_string.html#a86bb40d8f8c1921a8ac881d095c3c27b) says:

> Adds count copies of chPad to the beginning, or to the end of the string (the default).
> Removes spaces from the left or from the right (default).

The first part is correct, the second looks like a residue from Trim(). Looking at the code, Pad() does not remove anything:
```
wxString& wxString::Pad(size_t nCount, wxUniChar chPad, bool bFromRight)
{
    wxString s(chPad, nCount);

    if ( bFromRight )
        *this += s;
    else
    {
        s += *this;
        swap(s);
    }

    return *this;
}
```

**Comment by vadz** [comment]
Yes, looks like a copy-pasto, will fix, thanks.
