### ISSUE TITLE
wxQt: wxFrame paint handler does not account for menu bar.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24629]
### Description

Sample: [touchtest.cpp.txt](https://github.com/user-attachments/files/15924820/touchtest.cpp.txt)

When using `wxPaintEvent` handler in `wxFrame` with a menu bar, the draw origin is above the menu bar:

wxQt:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/aa511d79-9d3d-402b-a2d9-246da430fab7)

wxGTK reference:
![image](https://github.com/wxWidgets/wxWidgets/assets/37658952/a748e3ac-e421-40b9-ac1b-0cdb08f80b6c)

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxQt
- OS  and its version: any

**Comment by AliKet** [comment]
If you don't see any problem applying this patch:
```C++
diff --git a/src/qt/dcclient.cpp b/src/qt/dcclient.cpp
index 9c1d987fbe..19f36a79e6 100644
--- a/src/qt/dcclient.cpp
+++ b/src/qt/dcclient.cpp
@@ -141,5 +141,7 @@ wxPaintDCImpl::wxPaintDCImpl( wxDC *owner, wxWindow *win )
 {
     wxCHECK_RET( m_isWindowPainter || win->QtCanPaintWithoutActivePainter(),
                  "wxPaintDC can't be created outside wxEVT_PAINT handler" );
+
+    m_qtPainter->translate( wxQtConvertPoint(win->GetClientAreaOrigin()));
 }
 
```

Please don't hesitate to create a PR with the required changes.

TIA.

**Comment by dsa-t** [comment]
PR: #24682
