### ISSUE TITLE
wxTreeListCtrl default border (dark mode)

### ISSUE THREAD

**Issue by DueTo250** [wxWidgets/wxWidgets#24624]
wxTreeListCtrl has a thick border in dark mode. This control looks better if you set wxBORDER_SIMPLE by default. 
![dark-tree-list](https://github.com/wxWidgets/wxWidgets/assets/173275846/96bbde74-8e8e-4a69-8cf3-5d2105c79c81)

OS: Windows 11 23H2

**Comment by vadz** [comment]
Thanks for noticing and reporting this!

Checking it, this is not just about `wxTreeListCtrl` but rather about `wxDataViewCtrl`, used internally by it, itself.

It's easy to fix and I'll do it in a moment, but I wonder if we really need all the code added for handling `wxBORDER_THEME` back in a047aff270 (Added wxBORDER_THEME [...], 2007-08-07) or if we could perhaps just remove all of it by now.
