### ISSUE TITLE
touch zoom doesn’t work on bookworm with X11

### ISSUE THREAD

**Issue by mgrouch** [wxWidgets/wxWidgets#24623]
I tried with wxWidgets 3.2.2 and tried with 
3.2.5 compiled from source. 

event example with touch zoom of horse picture as documented here:

https://wiki.wxwidgets.org/GSoC_Multi-touch_Gestures

doesn’t react on touch zoom in bookworm raspberry pi on x11. 

Horse picture doesn’t change size on two finger zoom gestures

**Comment by mgrouch** [comment]
And apps compiled with same wxWidgets do not receive touch zoom events

**Comment by vadz** [comment]
Just to check (I don't think this is the case, but...): there is nothing in #24610 that would fix/help with this?

Also, when you say "with X11", does it mean that you've tested it with Wayland and it works with it or just that you've only tested X11?

**Comment by mgrouch** [comment]
There are reports here that it works on Wayland

https://github.com/OpenCPN/OpenCPN/issues/2057

**Comment by mgrouch** [comment]
See debian bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1073918

**Comment by mgrouch** [comment]
Actually I find it weird that glcanvasegl would have to do anything with touch events.

**Comment by mgrouch** [comment]
> > Actually I find it weird that glcanvasegl would have to do anything with touch events.
> 
> In the Debian case, it is because Debian uses this patch to force use of X11 when wxGLCanvas is used: https://salsa.debian.org/freewx-team/wxwidgets3.2/-/blob/master/debian/patches/force-x11-for-wxgl.patch?ref_type=heads

But the issue is on x11. I’d think forcing use x11 on x11 is safe

**Comment by mgrouch** [comment]
> Are you running it through XWayland or is it directly on top of an Xserver? Asking for the X11 backend will give XWayland if the underlying desktop environment is using Wayland.

I’m running it directly on x11. 
no Wayland, no xWayland

**Comment by mgrouch** [comment]
How missing touch events would be related to egl?

**Comment by mgrouch** [comment]
> > How missing touch events would be related to egl?
> 
> They aren't. They're related to X11.

It’s a regression though. It used to work on x11 a while back. Going to wxwidgets 3.1.5

**Comment by swt2c** [comment]
> > > How missing touch events would be related to egl?
> > 
> > 
> > They aren't. They're related to X11.
> 
> It’s a regression though. It used to work on x11 a while back. Going to wxwidgets 3.1.5

If that's the case, can you bisect wxWidgets and figure out what commit broke it?

**Comment by swt2c** [comment]
> Could it be that the issue is on gtk level? And some gtk upgrade broke it?

Indeed possible.  I would suggest you compile wxWidgets 3.1.5 on your current environment and see if it still works.  That would rule out a wxWidgets change.

**Comment by dsa-t** [comment]
Zoom and rotate gestures in the `event` sample work fine on my system.
- wxWidgets 3.2 tip (https://github.com/wxWidgets/wxWidgets/commit/a2d33fc31e7612e76163c67ebdf05179a96db84f)
- with `wxUSE_GLCANVAS_EGL=OFF`
- X11/Linux Mint 21.1 (based on Ubuntu 22.04, which is based on Debian Bookworm)

Check if your touch panel sends correct events via `evtest` tool.

**Comment by mgrouch** [comment]
Zoom with two finger works fine in chromium so the touch panel is sending events.

Here is my evtest output

````
user@lysmarine:~ $ evtest 
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:	pwr_button
/dev/input/event1:	WingCool Inc. TouchScreen
/dev/input/event10:	vc4-hdmi-1 HDMI Jack
/dev/input/event2:	WingCool Inc. TouchScreen Mouse
/dev/input/event3:	SIGMACHIP Usb Mouse
/dev/input/event4:	SIGMACHIP USB Keyboard
/dev/input/event5:	SIGMACHIP USB Keyboard Consumer Control
/dev/input/event6:	SIGMACHIP USB Keyboard System Control
/dev/input/event7:	vc4-hdmi-0
/dev/input/event8:	vc4-hdmi-0 HDMI Jack
/dev/input/event9:	vc4-hdmi-1
Select the device event number [0-10]: 1
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x27c0 product 0x818 version 0x110
Input device name: "WingCool Inc. TouchScreen"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 330 (BTN_TOUCH)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   7594
      Min        0
      Max    16383
      Resolution      76
    Event code 1 (ABS_Y)
      Value   5907
      Min        0
      Max     9599
      Resolution     106
    Event code 47 (ABS_MT_SLOT)
      Value      1
      Min        0
      Max        9
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max    16383
      Resolution      76
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     9599
      Resolution     106
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
  Event type 4 (EV_MSC)
    Event code 5 (MSC_TIMESTAMP)
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
^C
````


````
Select the device event number [0-10]: 2
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x27c0 product 0x818 version 0x110
Input device name: "WingCool Inc. TouchScreen Mouse"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max    16383
      Resolution      76
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max     9599
      Resolution     106
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)

````

**Comment by mgrouch** [comment]
Ok. It seems issue is on gtk3 layer or lower.

I launched gtk3-demo, selected 'Gestures' in menu and 'run'

Only swipe gesture is working. No two finger gestures are working in gtk3-demo.

**Comment by dsa-t** [comment]
Try to build a newer version of GTK maybe

**Comment by mgrouch** [comment]
Or GDK?Sent from my iPhoneOn Jun 22, 2024, at 2:48 PM, dsa-t ***@***.***> wrote:﻿
Try to build a newer version of GTK maybe

**Comment by dsa-t** [comment]
I haven't seen GDK separate from the GTK package.

**Comment by vadz** [comment]
Unfortunately I don't see what can we do here if GTK doesn't send us the events, so unless I'm missing something this can be closed.
