### ISSUE TITLE
wxCollapsiblePane challenges in a wxBoxSizer

### ISSUE THREAD

**Issue by pieter3d** [wxWidgets/wxWidgets#24628]
Seen on wxWidgets 3.0 + wxGTK from ubuntu 22.04.

I am having some trouble with a `wxCollapsiblePane`. I am trying to create a list of these in a scollable panel, each with a bunch of different controls.

This how I am constructing it:
```c++
  auto *panel = new wxScrolled<wxPanel>(splitter);
  auto *proj_info = new wxCollapsiblePane(panel, wxID_ANY, "Info");
  auto *info_pane = proj_info->GetPane();
  auto *name_sizer = new wxBoxSizer(wxHORIZONTAL);
  name_sizer->Add(new wxStaticText(info_pane, wxID_ANY, "Name:"), /*proportion*/ 0);
  name_sizer->Add(new wxTextCtrl(info_pane, wxID_ANY, "name here"), /*proportion*/ 1, wxEXPAND);
  auto *info_sizer = new wxBoxSizer(wxVERTICAL);
  info_sizer->Add(name_sizer, /*proportion*/ 0, wxEXPAND);
  info_pane->SetSizerAndFit(info_sizer);

  auto *panel_sizer = new wxBoxSizer(wxVERTICAL);
  panel_sizer->Add(proj_info, /*proportion*/ 0, wxEXPAND); // Is this the right proportion?
  panel_sizer->Add(new wxStaticText(panel, wxID_ANY, "foo"));
  panel->SetSizer(panel_sizer);
```

With the above, I get a collapsible header with the "foo" text right under it, so far so good. But when expanding it, the name controls don't appear and I get the following error from the GTK implementaton:
```
Gtk-WARNING **: 23:44:25.310: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node entry, owner GtkEntry)
```
If I set the proportion of `proj_info` to 1, then the `proj_info` panel takes up the full vertical extent of `panel`, pushing the "foo" text all the way to the bottom. Both in a collapsed and uncollapsed state. This is pretty ugly of course.

I've found the following solution. Set the proportion back to 0, but then add this event handler:
```c++
  proj_info->Bind(wxEVT_COLLAPSIBLEPANE_CHANGED, [panel](wxCollapsiblePaneEvent &) { panel->Layout(); });
```

Is this the correct way to do all these things? This was found by trial and error, and some chatGPT help. I've seen nothing in the docs that discuss this approach. In fact, the docs suggest to set the proportion of `wxCollapsiblePane` to 0 when using sizers, but that leads to the above error message, and missing controls when uncollapsed.

**Comment by vadz** [comment]
You do need to call `Layout()` when the size of the control changes, the sizer has no way of knowing it on its own, so there is probably no real issue there, i.e. I don't really see what could we improve. Maybe we should mention this in `wxCollapsiblePane` documentation...

**Comment by pieter3d** [comment]
A documentation update sounds reasonable. Although since it's always required, couldn't this event handler just be defined and bound internally? Why make the user write the extra boilerplate?

**Comment by vadz** [comment]
In wxWidgets layout is only done from top to bottom implicitly, everything else needs to be done by the application itself if necessary. I.e. if the size of the panel changes, it does relayout its children (of course), but if the size of its children changes, this doesn't affect the panel layout by default. This is simple and avoids a lot of surprises that made lives of so many Motif programmers (if any of them still survive...) so miserable.

In this very simple case calling `Layout()` automatically would be helpful, but in more complicated layouts it could easily result in unpredictable resizing of unrelated windows, which would be very difficult to understand. But if you call `Layout()` yourself, you're presumably aware that this changes the layout, so there are no surprises.
