### ISSUE TITLE
wxGTK: wxMessageDialog with wxSTAY_ON_TOP is non-interactive after a wxLog dialog gets shown.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24636]
### Description

When logging a message using `wxLogInfo`, then showing a `wxMessageDialog` with `wxSTAY_ON_TOP` flag set, the user cannot interact with any of the dialogs using the mouse.

### Patch to reproduce

```patch
diff --git a/samples/dialogs/dialogs.cpp b/samples/dialogs/dialogs.cpp
index 21b39fb801..69ad4eb094 100644
--- a/samples/dialogs/dialogs.cpp
+++ b/samples/dialogs/dialogs.cpp
@@ -971,6 +971,8 @@ void MyFrame::OnInfoBarRedo(wxCommandEvent& WXUNUSED(event))
 #if wxUSE_MSGDLG
 void MyFrame::MessageBox(wxCommandEvent& WXUNUSED(event))
 {
+    wxLogInfo("My log message");
+
     wxMessageDialog dialog(this,
                            "This is a message box\n"
                            "This is a long, long string to test out if the message box "
@@ -978,7 +980,7 @@ void MyFrame::MessageBox(wxCommandEvent& WXUNUSED(event))
                            "Message box text",
                            wxCENTER |
                            wxNO_DEFAULT | wxYES_NO | wxCANCEL |
-                           wxICON_INFORMATION);
+                           wxICON_INFORMATION | wxSTAY_ON_TOP);
 
     wxString extmsg;
     if ( dialog.SetYesNoCancelLabels
```

### To Reproduce:

1. Launch the patched `dialogs` sample
2. Press Ctrl+M or Dialogs -> Message box
3. A dialog will appear, but it can't be interacted with with a mouse
4. The invisible logger dialog below can only be closed with a keyboard, then the message dialog on top becomes interactive.

### Platform and version information

- wxWidgets version  you use: 3.2.5+
- wxWidgets port  you use: wxGTK
- OS  and its version: Linux Mint 21.1
  
  + GTK version:  3.24.33
  + Which GDK  backend is used: X11
  + Desktop environment : XFCE

KiCad issue: https://gitlab.com/kicad/code/kicad/-/issues/18242

**Comment by dsa-t** [comment]
Actually this is the same as https://github.com/wxWidgets/wxWidgets/issues/24228.
The issue doesn't reproduce in wx 3.3

I guess it is not backportable to 3.2?

**Comment by vadz** [comment]
In principle, I think adding a virtual dtor to a class which had already had (default, compiler-generated) virtual dtor before should be ABI-compatible, but I'm not 100% sure. If someone could test this, it would be great.

Also, it's possible to do the equivalent of cc0526bb1ee474b45d0079b4c86b6c46697c2667 in the app code (KiCad probably already defines its custom logger?), and although this wouldn't be needed with 3.3, it should do no harm even when using it.
