### ISSUE TITLE
Support the standardized color scheme portal on Linux

### ISSUE THREAD

**Issue by bragefuglseth** [wxWidgets/wxWidgets#24638]
### Description

The [`org.freedesktop.appearance color-scheme`](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html) interface enables Linux apps to automatically switch between light and dark mode depending on what the system has been set to by the user. Modern Linux apps follow this by default thanks to platform libraries such as libadwaita (GNOME) or libgranite (elementaryOS) providing support for it out of the box. However, support for it is not built directly into GTK itself, so wxWidget apps using GTK don't follow the preference as of now (see vslavik/poedit#787, for instance). It seems like wxWidgets itself would be the appropriate layer to make this happen.

**Comment by paulcor** [comment]
Do you have an example of something that does not work as expected? Because support for this feature was added in 3.2.3.

**Comment by bragefuglseth** [comment]
Oh, ok. The version of poedit I use is still on v3.2.2, so I expect that this will be solved on the next update then. Thanks for the clarification!
