### ISSUE TITLE
wxTextFile retruns always 0 on Ubuntu 24.04.

### ISSUE THREAD

**Issue by PatrickHerburger** [wxWidgets/wxWidgets#24631]
### Description

If I'm using the sampe 'font', the content of any .txt can be read but it only returns 0.

I'm used the newest wxWidgets version which I cloned a couple of minutes ago.
On an other test PC I used wxWidgets 3.2. Same issue:

```
    wxTextFile tfile;
    if( tfile.Open( path ) )
    {
        const wxString valueString = tfile.GetFirstLine();
        tfile.Close();
        systemValue = wxAtoi( valueString ); //valueString = 0
    }

```

I can workaround this issue if I'm using: 
 
```
    std:filesystem::path filePath(path.ToStdWstring());
    std::ifstream sysFile(filePath, std::ios::in);
    if (sysFile.good() && sysFile.is_open())
    {
        std::string line;
        std::getline(sysFile, line);
        systemValue = std::stoi(line);
    }
```

### Platform and version information

- wxWidgets version  you use: 3.2 and newest release
- wxWidgets port  you use: wxGTK
- OS  and its version: Ubuntu 24.04. all updates
  
  + GTK version:  4.13
  + Which GDK  backend is used: -
  + Desktop environment : Gnome

**Comment by vadz** [comment]
What is the value of `valueString` in your snippet? Could you please [make a patch](https://www.wxwidgets.org/develop/how-to-report-issues/) to the font sample allowing to reproduce the problem?

**Comment by PatrickHerburger** [comment]
Please excuse the bad description. It was friday :=)
I have attached a font.zip for your convenience. It contains the font.cpp. I have only changed one function so that a predefined .txt file is read. 
Under Windows, the string is output in the text box. Under Ubuntu 24.04. as I said not. But it is displayed correctly in the console. That's why I think it's a bug.
Please have a look at the pictures in the attachment for reference.
Please let me know if you need any further information.

Thank you,
Patrick

[font.zip](https://github.com/user-attachments/files/15952346/font.zip)
![wxErr](https://github.com/wxWidgets/wxWidgets/assets/154236672/18141613-b380-46d1-a18b-233a3319efe9)
![wxNoErr](https://github.com/wxWidgets/wxWidgets/assets/154236672/a4bf0ab7-94b9-4495-8c1d-65fc9f558d95)

**Comment by vadz** [comment]
Your changes (please submit _just_ them, as explained in the instructions linked above) boil down to just this:

```diff
diff --git a/samples/font/font.cpp b/samples/font/font.cpp
index 0101ad65e9..6b4ce9bee9 100644
--- a/samples/font/font.cpp
+++ b/samples/font/font.cpp
@@ -1045,6 +1045,19 @@ void MyFrame::OnTestTextValue(wxCommandEvent& WXUNUSED(event))
 
 void MyFrame::OnViewMsg(wxCommandEvent& WXUNUSED(event))
 {
+    wxTextFile tfile;
+    if (tfile.Open("/home/matrix/Downloads/wxStuff/wxWidgets/gtk-build/samples/font/test.txt"))
+    {
+        int systemValue = -1;
+        const wxString valueString = tfile.GetFirstLine();
+        tfile.Close();
+        systemValue = wxAtoi(valueString);
+        wxMessageBox("Output: " + systemValue,
+            wxString("My sample"),
+            wxOK | wxICON_INFORMATION, this);
+    }
+    return;
+
 #if wxUSE_FILEDLG
     // first, choose the file
     static wxString s_dir, s_file;
```

which shows 2 things:

1. This is useless without having `/home/matrix/Downloads/wxStuff/wxWidgets/gtk-build/samples/font/test.txt` file.
2. You're using `wxString + int` which doesn't make any sense (it's really unfortunate that this compiles, but it's difficult to change).

The net result is that you're passing a random pointer to `wxMessageBox()` which just happens to point to `This` in one case. This is definitely a bug in your code but there is no bug in wxWidgets here.
