### ISSUE TITLE
missing functions when I compile and link with a recent static version of libwxmsw33u.a

### ISSUE THREAD

**Issue by gerard-durand** [wxWidgets/wxWidgets#24646]
I have a test program derived from the penguin sample but modified to use the wxsmith version integrated in Code::Blocks.
Until recently I could compile and run this program with a monolib version of wxWidgets 3.3, using a dll or a static lib.
With my last wxwidgets download, I can still compile, link and run this program with the dll (full rebuilt), but with the static lib version, I have problems with missing entries apparently : here is an extract of the messages :

> ||=== Générer : Release_64_static dans demo_penguin_wxs (compilateur : GNU GCC Compiler) ===|
> C:\msys64\mingw64\bin\..\lib\gcc\x86_64-w64-mingw32\14.1.0\..\..\..\..\x86_64-w64-mingw32\bin\ld.exe: C:\wxWidgets-3.3.0_git\lib\gcc_lib
> ...
> \libwxmsw33u.a(monolib_dc.o):dc.cpp|| undefined reference to '__imp_AlphaBlend'|
> \libwxmsw33u.a(monolib_dc.o):dc.cpp|| undefined reference to '__imp_GradientFill'|
> 
> \libwxmsw33u.a(monolib_nonownedwnd.o):nonownedwnd.cp:||undefined reference to 'GdipCreateRegionPath'|
> \libwxmsw33u.a(monolib_nonownedwnd.o):nonownedwnd.cp:||undefined reference to 'GdipGetRegionHRgn'|
> ...
> \libwxmsw33u.a(monolib_graphics.o):graphics.cpp|| undefined reference to 'GdipDeletePath'|
> \libwxmsw33u.a(monolib_graphics.o):graphics.cpp|| undefined reference to 'GdipFree'|
> ...

I have extracted from my old lib (compiled in may 2024) monolib_dc.o and monolib_gdiplus.o, added them to the linker in my program generation and now my program links and run again in static mode. Apparently, no need to link with monolib_nonownedwnd.o or monolib_graphics.o.
As far as I know, I don't use directly the missing functions. And there are no such problems with the wxwidgets monolib dll.

The strange thing, is that with the original Penguin.cpp sample version, there is not this problem with the static lib.

I am on Windows 11, updated. I use Msys2 version of gcc/g++, last update, and wxWidgets 3.3 updated via git. All libs, static and dlls have been recompiled with the last compiler downloaded.

**Comment by wh11204** [comment]
The GDI+ wrapper has been [removed](https://github.com/wxWidgets/wxWidgets/commit/3b73b68736088bd8fabef965fd0f736dae8e28f8), try linking with libgdiplus.a when using the static libraries.

**Comment by gerard-durand** [comment]
Cool, it's better with libgdiplus.a found in Msys2 (MinGW64/lib), but I have still missing functions : __imp_AlphaBlend and __imp_GradientFill

> ||=== Générer : Release_64_static dans demo_penguin_wxs (compilateur : GNU GCC Compiler) ===|
> C:\msys64\mingw64\bin\..\lib\gcc\x86_64-w64-mingw32\14.1.0\..\..\..\..\x86_64-w64-mingw32\bin\ld.exe: C:\wxWidgets-3.3.0_git\lib\gcc_lib\libwxmsw33u.a(monolib_dc.o):dc.cpp|| undefined reference to '__imp_AlphaBlend'|
> C:\msys64\mingw64\bin\..\lib\gcc\x86_64-w64-mingw32\14.1.0\..\..\..\..\x86_64-w64-mingw32\bin\ld.exe: C:\wxWidgets-3.3.0_git\lib\gcc_lib\libwxmsw33u.a(monolib_dc.o):dc.cpp|| undefined reference to '__imp_GradientFill'|
> ||error: ld returned 1 exit status|
> ||=== Génération de échoué : 3 erreur(s), 0 avertissement(s) (0 minute(s), 4 seconde(s)) ===|
> 
Adding monolib_cd.o is still a workaround.
May be an other lib to add...

**Comment by gerard-durand** [comment]
OK found, it's libmsimg32.a

**Comment by vadz** [comment]
This is [documented here](https://github.com/wxWidgets/wxWidgets/blob/d1506f40c67453ad5ad6799dc6e71a7e71ff56f4/docs/changes.txt#L119-L123) and I don't know what else can we do, so closing.
