### ISSUE TITLE
DrawLines differences between Win and Linux

### ISSUE THREAD

**Issue by parduz** [wxWidgets/wxWidgets#24645]
### Description

The following code in my program draws a sine wave stored in an array of `wxPoint2DDouble` (the axes and the grid are on an already drawn bitmap _FBackBitmap_):
```
dc.DrawBitmap(*FBackBitmap, 0, 0);
wxGraphicsContext *gc = wxGraphicsContext::Create( dc );
gc->SetPen(wxPen(*wxYELLOW, 2,wxPENSTYLE_SOLID));
gc->DrawLines(Ch->pIndex, Ch->GraphPoints);
```
**_Ch->pIndex_** value is **2024**, while the `wxPoint2DDouble` array size is **4000**.

#### Bug description:
The output is different betwwen Windows10 and Debian11
This is how it appears in Windows 10:
![Windows](https://github.com/wxWidgets/wxWidgets/assets/9556348/7c751066-283c-41bf-bbcf-c9515456008e)

and this is how it appears on Debian
![Debian](https://github.com/wxWidgets/wxWidgets/assets/9556348/a876fc64-59f3-492e-a84d-db7c5f95c7e1)

Despite what would be the right result, it should be same for both the OSs

### Platform and version information
- wxWidgets version 3.2.4
- wxWidgets port: wxMSW, wxGTK
- Windows 10 PC, Debian11 armhf
- GTK version: 3, X11
- Desktop environment: OpenBox

**Comment by vadz** [comment]
So the difference is that Cairo-based implementation closes the loop by drawing the line connecting the last point to the first one, right?

This doesn't seem useful to me, so I think we should standardize on MSW behaviour. Any other opinions?

**Comment by doublemax** [comment]
> So the difference is that Cairo-based implementation closes the loop by drawing the line connecting the last point to the first one, right?
> 
> This doesn't seem useful to me, so I think we should standardize on MSW behaviour. Any other opinions?
The documentation claims that wxGraphicsContext::DrawLines() draws a polygon. If that's true, i think the Cairo version is correct. There is separate StrokeLines() to draw lines only.

**Comment by paulcor** [comment]
It's got nothing to do with Cairo. All the `wxGraphicsContext` implementations other than `wxGDIPlusContext` use the [default DrawLines()](https://github.com/wxWidgets/wxWidgets/blob/d1506f40c67453ad5ad6799dc6e71a7e71ff56f4/src/common/graphcmn.cpp#L829), which does what the documentation says and draws a polygon. The `wxGDIPlusContext` implementation is wrong. If you don't want a polygon, use `StrokeLines()`.

**Comment by vadz** [comment]
The problem must have been fixed by the commit above, so closing.

I thought about backporting this to 3.2 too, but finally decided against it, as this would silently change the behaviour under Windows and even if the new behaviour is more correct, people would still probably not expect such a change in a micro version update.

**Comment by parduz** [comment]
Glad it is fixed, i have some concern about what ppl expect: i see your point, but whoever will use the function in the future MAY expect to have the correct behaviour.

Thanks, anyway.
