### ISSUE TITLE
Check mark of `wxBoolProperty` looks blurry at high DPI

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24651]
As can be seen in the propgrid sample, the check mark of a `wxBoolProperty` looks sharp at 100% DPI scaling but blurry at 200% and 300%.

![wxBoolProperty-check-mark-100-200-300-DPI-scaling](https://github.com/wxWidgets/wxWidgets/assets/99262969/2492dcda-6dfa-4496-aae0-ba6e75f2db09)

The check mark of a `wxCheckBox` looks sharp even at 300% DPI scaling.

![wxCheckBox-check-mark-300-DPI-scaling](https://github.com/wxWidgets/wxWidgets/assets/99262969/e0d9574c-9ce2-41db-b7d5-ba947848432c)

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by dsa-t** [comment]
I haven't looked yet, but could there be some downscaling happening?

In that case, https://github.com/wxWidgets/wxWidgets/pull/24567 should help.

**Comment by dsa-t** [comment]
The actual drawn checkbox size is different to the rect that wx passes to `DrawThemeBackground`.

DrawThemeBackground | Actual | Scale
-|-|-
15x15 | 13x13 | 100%
20x20 | 16x16 (if DPI changed from 100%) | 125%
20x20 | 20x20 (if DPI didn't change) | 125%

**Comment by dsa-t** [comment]
Here are best checkbox sizes for different scales on Win11:

100%: 13
125%: 16
150%: 20
175%: 20

200%: 26
225%: 26
250%: 32

300%: 40
350%: 40

**Comment by dsa-t** [comment]
Seems to be working correctly with this patch:

```patch
diff --git a/src/msw/renderer.cpp b/src/msw/renderer.cpp
index 2a8d013b31..31e884142f 100644
--- a/src/msw/renderer.cpp
+++ b/src/msw/renderer.cpp
@@ -716,7 +716,18 @@ wxRendererXP::DoDrawXPButton(int kind,
     if ( !hTheme )
         return false;
 
-    DoDrawButtonLike(hTheme, kind, dc, rect, flags);
+    wxRect crect = rect;
+
+    if ( kind == BP_CHECKBOX )
+    {
+        if ( ::IsThemePartDefined(hTheme, kind, 0) )
+        {
+            crect = wxRect(hTheme.GetDrawSize(kind, CBS_UNCHECKEDNORMAL));
+            crect.MakeCenteredIn(rect);
+        }
+    }
+
+    DoDrawButtonLike(hTheme, kind, dc, crect, flags);
 
     return true;
 }

```
Maybe makes sense to apply to `BP_RADIOBUTTON` as well.

**Comment by taler21** [comment]
Thanks for looking at this.

I can confirm that with your changes applied, it looks correct.

![wxBoolProperty-check-mark-patched](https://github.com/wxWidgets/wxWidgets/assets/99262969/2afb1f35-fbed-405b-aae3-3d99d9948e73)

**Comment by dsa-t** [comment]
PR: https://github.com/wxWidgets/wxWidgets/pull/24671
