### ISSUE TITLE
3.2.5 regression on macOS: wxListCtrl and wxTreeCtrl no longer get focused on mouse click

### ISSUE THREAD

**Issue by codesquid** [wxWidgets/wxWidgets#24667]
### Description

This is a new regression in wxWidgets 3.2.5 on macOS, this functionality worked correctly in wxWidgets 3.2.4

When left-clicking wxListCtrl or wxTreeCtrl, the control no longer takes focus. Clicking an item in these controls selects said item, but the control itself stays unfocused:
- The background color of the selected items stays grey
- Changing the selected item with the cursor keys on the keyboard is then not possible
- Slowly clicking an item twice no longer starts the label editing

This can be reproduced in the listctrl and treectrl samples: Start the sample, click an item in the list/tree and then try to use the cursor keys to change the selected item. In 3.2.5, it does not work, in 3.2.4 the selection changes as expected.

It is however still possible to give the control focus by navigating to it using the Tab key.

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxOSX
- OS  and its version: macOS 14.5 (23F79) on Apple M2
- Compiler: Apple clang version 15.0.0 (clang-1500.3.9.4) from XCode 15.4 (15F31d)

**Comment by vadz** [comment]
Thanks for reporting this. Unfortunately I don't see any smoking gun, `git log v3.2.4..v3.2.5 src/osx` shows just a few commits none of which seem to be obviously related. If you can run git-bisect to find the commit which actually broke this, it would be great.

**Comment by codesquid** [comment]
It's this commit: https://github.com/wxWidgets/wxWidgets/commit/abab8b43855127c7556e021b8ddb954871fdbcb5

If I reverse it, the focus on left-click is back to normal.

**Comment by codesquid** [comment]
Upon further testing, reversing that commit only fixes it for the listctrl sample, it does nothing for the treectrl sample.

Furthermore, even in the listctrl sample, there is still a small 20x20 in the top left of the list that upon click doesn't give the control focus.

**Comment by codesquid** [comment]
Reverting both https://github.com/wxWidgets/wxWidgets/commit/abab8b43855127c7556e021b8ddb954871fdbcb5 and https://github.com/wxWidgets/wxWidgets/commit/b8744be566195d9adf91be9fd5bb6c2de944c900 makes both the listctrl and treectrl samples work correctly again.

**Comment by vadz** [comment]
Thanks for debugging this! Unfortunately I have absolutely no time to look at it now and I am not sure if I have the expertise to solve this even if I had.

@csomor Any ideas?

**Comment by csomor** [comment]
ok, happens only under macOS 14+, related to our use of the clippingView, also present on master, I'll look into it

**Comment by csomor** [comment]
@codesquid could you please test with the commit from the PR #24678, especially test whether this leads to other anomalies within the listctrl / treectrl, thanks

**Comment by codesquid** [comment]
@csomor: Thank you, the commit from PR #24678 works fine, everything appears to be back to normal.
