### ISSUE TITLE
wxPrinterDC bitmap is drawn at wrong offset on wxMSW.

### ISSUE THREAD

**Issue by dsa-t** [wxWidgets/wxWidgets#24673]
### Description

Using this patch with `printing` sample:

```diff
diff --git a/samples/printing/printing.cpp b/samples/printing/printing.cpp
index 7c4d7254db..541c7f04ee 100644
--- a/samples/printing/printing.cpp
+++ b/samples/printing/printing.cpp
@@ -207,7 +207,7 @@ void MyApp::Draw(wxDC&dc)
 
     wxIcon my_icon = wxICON(sample);
 
-    dc.DrawIcon( my_icon, dc.FromDIP(100), dc.FromDIP(100));
+    dc.DrawIcon(my_icon, 0, 0);
 
     if (m_bitmap.IsOk())
         dc.DrawBitmap( m_bitmap, dc.FromDIP(10), dc.FromDIP(10) );
```

The printed result differs from both the preview and the non-printer DC.

Printed to JPG using clawPDF:

![ClawTest11](https://github.com/wxWidgets/wxWidgets/assets/37658952/9701ab11-550f-42fa-839d-5e6dbe361751)

wxWidgets Preview screenshot:

![wx-preview](https://github.com/wxWidgets/wxWidgets/assets/37658952/92c0fe89-ae52-4c6c-b941-f80cec68316c)

### Platform and version information

- wxWidgets version  you use: 3.3 (master)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by vadz** [comment]
Sorry, I didn't have time to test it yet, but could this be due to missing `XLOG2DEV` and `YLOG2DEV` in this line

https://github.com/wxWidgets/wxWidgets/blob/ba026c21d85a94e2e95034621b4c2b7b087decd6/src/msw/dc.cpp#L1142

which, I guess, is used when printing (but not when previewing)?

**Comment by vadz** [comment]
I've finally returned to this and confirmed that `DrawIconEx()` still doesn't work when printing, so we can't use.

Fixing the position, however, was trivial, as it was just a matter of accounting for the shifted printer DC origin, see the associated PR.

There are more problems when printing icons, however, see #24835 and #24836. Not sure if KiCad is affected by this, please let me know (there) if it is.

**Comment by dsa-t** [comment]
In KiCad we recommend using Plot nowadays, which uses our own PDF writer. 
But even printing with transparent bitmaps from schematic editor seem to work fine on Windows.

There was another problem with arcs being always printed in black on macOS: https://gitlab.com/kicad/code/kicad/-/issues/18710

**Comment by vadz** [comment]
> In KiCad we recommend using Plot nowadays, which uses our own PDF writer. But even printing with transparent bitmaps from schematic editor seem to work fine on Windows.

I wonder why it doesn't work in the sample for me... But not enough to spend time on it if it works for you.
 
> There was another problem with arcs being always printed in black on macOS: https://gitlab.com/kicad/code/kicad/-/issues/18710

I'm not even sure which function is used for drawing this, is this `DrawArc()`? I could try to see if I can reproduce it, at least...

**Comment by dsa-t** [comment]
Actually nowadays we use the cairo context directly, so it might be not a wxWidgets bug (this also explains why bitmaps work correctly):
https://gitlab.com/kicad/code/kicad/-/blob/1ac1a5bb3bb9093802fe5c47253a3154504d6130/common/gal/cairo/cairo_print.cpp#L52

**Comment by vadz** [comment]
It would be interesting to know what prevents you from using `wxDC` or `wxGC`, it looks like we ought to be able to work it out if you already have code working correctly with Cairo, but this is getting very far OT from this issue...
