### ISSUE TITLE
wxFileSystemWatcher::AddTree has inconsistent handling of hidden folders

### ISSUE THREAD

**Issue by Carnildo** [wxWidgets/wxWidgets#24696]
#### Bug description:

wxFileSystemWatcher::AddTree has inconsistent handling of hidden subfolders of a watched folder.  I've confirmed that changes in hidden subfolders are reported on Windows, and are not reported on Linux; I suspect that changes will not be reported on Windows if a filter is passed to AddTree.

The difference appears to stem from not passing the "wxDIR_HIDDEN" option to wxDir::Traverse in the generic implementation of AddTree.

#### To Reproduce:

1. Run the "fswatcher" example program.
2. Use the "Add Tree" button to add a folder tree containing a hidden folder.
3. Create a file in the hidden folder.

#### Expected vs observed behaviour:

Expected: Consistent behavior on both platforms.

Actual: On Windows, creating a file in the hidden folder generates "create" and "modify" events.  On Linux, creating a file in the hidden folder does not generate any events.

### Platform and version information

- wxWidgets version you use: 3.2.5
- wxWidgets port you use: wxGTK and wxMSW
- OS and its version: Windows 10 and Gentoo Linux
  + GTK version: 3.24.41
  + Which GDK backend is used: X11
  + Desktop environment : XFCE

**Comment by vadz** [comment]
So would just adding `wxDIR_HIDDEN` to the code in `wxFileSystemWatcherBase::AddTree()` be enough to fix this? If yes, please feel free to make a PR adding it or I can just push it directly if you can confirm that this works.

Thanks!

**Comment by Carnildo** [comment]
Yes.  Changing `int flags = wxDIR_DIRS;` to `int flags = wxDIR_DIRS|wxDIR_HIDDEN;` produces consistent behavior between Windows and Linux.
