### ISSUE TITLE
All compress files won't open, it stays that file not found file does not exist

### ISSUE THREAD

**Issue by hmiento19** [wxWidgets/wxWidgets#24714]
Good morning y'all,

Below is a compressed file. Unfortunately, I lost access to all my compressed files and am getting this error. I would greatly appreciate any tips or help.

![Screenshot 2024-07-21 102612](https://github.com/user-attachments/assets/bff05a5b-4b3e-4e58-a02f-57cec0d4efd8)
[W10_Hamilton_Sarmiento.zip](https://github.com/user-attachments/files/16322764/W10_Hamilton_Sarmiento.zip)

**Comment by wh11204** [comment]
This looks like an issue with Code::Blocks, not wxWidgets. The project in the zip file opens OK in the current nightly of C::B, but the workspace seems corrupted (the project appears twice).

Delete the workspace and use the project directly, if you have more problems ask in the Code::Blocks [forum](https://forums.codeblocks.org/)

**Comment by vadz** [comment]
Closing as not a wx issue.
