### ISSUE TITLE
wxGTK prints lines and texts in the wrong colour, that of the last used `wxBrush`

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24729]
### To Reproduce:

The issue can be reproduced with the following changes to the printing sample:

<details>

<summary>Patch for printing sample</summary>

```patch
diff --git "a/samples/printing/printing.cpp" "b/samples/printing/printing.cpp"
index 7c4d7254db..84e11c4b49 100644
--- "a/samples/printing/printing.cpp"
+++ "b/samples/printing/printing.cpp"
@@ -125,8 +125,44 @@ int MyApp::OnExit()
     return wxApp::OnExit();
 }
 
+void DrawBlackLine( wxDC& dc, const wxPoint& pos )
+{
+    dc.SetPen( *wxBLACK_PEN );
+
+    dc.DrawLine( pos.x, pos.y, pos.x + dc.FromDIP(60), pos.y + dc.FromDIP(5) );
+}
+
+void DrawBlackText( wxDC& dc, const wxPoint& pos, const wxString& text )
+{
+    dc.SetFont( wxFontInfo(15).Family(wxFONTFAMILY_SWISS) );
+    dc.SetTextForeground( *wxBLACK );
+    dc.SetBackgroundMode( wxTRANSPARENT );
+
+    dc.DrawLabel( text, wxRect( pos, dc.FromDIP(wxSize(100, 0)) ), wxALIGN_LEFT|wxALIGN_TOP );
+}
+
 void MyApp::Draw(wxDC&dc)
 {
+    DrawBlackLine( dc, dc.FromDIP(wxPoint(10, 10)) );
+    DrawBlackText( dc, dc.FromDIP(wxPoint(10, 15)), "Text_1" );
+
+    dc.SetPen( *wxBLACK_PEN );
+    dc.SetBrush( *wxCYAN_BRUSH );
+
+    wxPoint polyPoints[3];
+    polyPoints[0].x = 0;
+    polyPoints[0].y = 0;
+    polyPoints[1].x = dc.FromDIP(20);
+    polyPoints[1].y = 0;
+    polyPoints[2].x = dc.FromDIP(20);
+    polyPoints[2].y = dc.FromDIP(20);
+    dc.DrawPolygon( 3, polyPoints, dc.FromDIP(80), dc.FromDIP(20) );
+
+    DrawBlackLine( dc, dc.FromDIP(wxPoint(10, 40)) );
+    DrawBlackText( dc, dc.FromDIP(wxPoint(10, 45)), "Text_2" );
+
+    return;
+
     // This routine just draws a bunch of random stuff on the screen so that we
     // can check that different types of object are being drawn consistently
     // between the screen image, the print preview image (at various zoom

```

</details>

1. Start the printing sample.
2. Click on 'File' and 'Print...' or press `Ctrl + P` and print to PDF.

On the screen, all lines and texts are correctly black

![On-screen-with-wxgtk](https://github.com/user-attachments/assets/8339b5bc-06c6-47d0-bc99-677fdf2eca7e)

but when printing to a PDF, the line and text drawn after the filled polygon have the colour of the `wxBrush` used to fill the polygon.

![Printed-to-PDF-with-wxgtk](https://github.com/user-attachments/assets/347b417f-6f9a-4c1e-9c92-5e57bdc7361b)

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxGTK
- OS  and its version: Ubuntu 24.04
  
  + GTK version:  3.24.41
  + Which GDK  backend is used: X11
  + Desktop environment : Gnome

**Comment by vadz** [comment]
Thanks, this was due to the faulty logic in colour-related code and is fixed by #24827.

**Comment by taler21** [comment]
Great, thanks!
I can confirm that your PR fixes the issue.

**Comment by vadz** [comment]
Thanks for testing!

Preempting your next request, this can't be backported to 3.2 as is, but it could be done by omitting 2f39d1959c969a389abb7c38acc2c8d84bd3af65 and adjusting the other 2 commits to not rely on it, but I'd appreciate if this could be done by somebody else, as I'd really rather work on 3.3.0 release.
