### ISSUE TITLE
MSW memory leak from application init

### ISSUE THREAD

**Issue by Blake-Madden** [wxWidgets/wxWidgets#24728]
This occurs after b808f4d107c90c6376ded7b5a945a5fb34225d5b.

### Platform:

Windows 11
Built latest wx 3.3 via CMake with the defaults (but with all samples)
Visual Studio 2022

### Issue

Build, run, and close any program (including the samples) and you will get this memory leak:

```
Detected memory leaks!
Dumping objects ->
{4185} normal block at 0x0000021AE10D8910, 77 bytes long.
 Data: <s> 43 3A 5C 55 73 65 72 73 5C 6D 61 64 69 6E 5C 73 
C:\source\wxWidgets\src\common\init.cpp(192) : {4184} normal block at 0x0000021AE10F9BD0, 16 bytes long.
 Data: <                > 10 89 0D E1 1A 02 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
```

This is because blocks of code are wrapped in `__WXMSW__` instead of `__WINDOWS__` in "init.cpp". I'm not sure why, but `__WXMSW__` is not defined for this particular file when you build wx. I honestly cannot figure out why though. I try including "platform.h", but that doesn't help.

It seems like `__WXMSW__` is getting undefined for this file or something; I had a difficult time tracing this.  But if I add this to the top of init.cpp:

```
#if defined(__WINDOWS__)
    /* Select wxMSW under Windows if no other port is specified. */
#   if !defined(__WXMSW__) && !defined(__WXGTK__) && !defined(__WXX11__) && !defined(__WXQT__)
#       define __WXMSW__
#   endif
#endif
```

Then this fixes it.

It may have something to do with this code in "platform.h":

```
/*
    Don't use widget toolkit specific code in non-GUI code in the library
    itself to ensure that the same base library is used for both MSW and GTK
    ports. But keep __WXMSW__ defined for (console) applications using
    wxWidgets for compatibility.
 */
#if defined(WXBUILDING) && defined(wxUSE_GUI) && !wxUSE_GUI
#   ifdef __WXMSW__
#       undef __WXMSW__
#   endif
```

Maybe `__WXMSW__` is turned off for "init.cpp" from this?

Sorry, this was as much as I could figure out.

**Comment by vadz** [comment]
This is the same as #24694.
