### ISSUE TITLE
wxWidgets won't build on macOS 15 due to CGDisplayCreateImage being obsolete

### ISSUE THREAD

**Issue by stephenbonar** [wxWidgets/wxWidgets#24724]
### Build System Used

I build wxWidgets and/or my application using:

- [X] CMake
- [ ] configure
- [ ] mingw32-make with makefile.gcc
- [ ] MSBuild (Microsoft Visual Studio solution file)
- [ ] nmake with makefile.vc
- [ ] Xcode

### Description

Compiling wxWidgets fails when trying to build dcscreen.cpp with the following error message:

```
/Users/stephen/git/programs/c++/MidiMessageViewer/wxWidgets/src/osx/carbon/dcscreen.cpp:73:13: error: 'CGDisplayCreateImage' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
   73 |     image = CGDisplayCreateImage(kCGDirectMainDisplay);
```

It appears CGDisplayCreateImage will no longer available in the upcoming macOS 15 Sequoia release. 

[output.txt](https://github.com/user-attachments/files/16353072/output.txt)

### Platform and version information

- wxWidgets version  you are building: 3.2.5
- wxWidgets port  you are building: wxOSX
- OS  and its version: macOS 15
- Compiler  being used: clang
- Non-default compiler options, if any :

**Comment by vadz** [comment]
Thanks for reporting this.

If anybody knows how to use ScreenCaptureKit instead, PRs would be welcome, but otherwise we probably just need to disable this code and document that `wxScreenDC` doesn't work under macOS (or just about anywhere else AFAIK).
