### ISSUE TITLE
wxWidgets crashs on Windows when load as DLL

### ISSUE THREAD

**Issue by starwing** [wxWidgets/wxWidgets#24730]
#### Bug description:

1. load `wx.dll` with `LoadLibraryA`:
![image](https://github.com/user-attachments/assets/da20e8c0-6102-407b-96b9-6b9e2c28df23)

2. unload dll with `FreeLibrary`
3. call `ExitProcess`

#### Expected vs observed behaviour:

process crashs in `nt.dll`, `RtlpFlsDataCleanup`

#### Stack trace:

![image](https://github.com/user-attachments/assets/349ed8f0-82ad-4c4e-90c7-d602717e3936)

#### Patch or snippet allowing to reproduce the problem:

minimal example:

[example.zip](https://github.com/user-attachments/files/16387540/example.zip)

#### To Reproduce:

unzip the example.zip, and runs `lua54.exe test.lua`

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10
  
  + GTK version: 
  + Which GDK  backend is used:
  + Desktop environment :
  + Current theme:

**Comment by PBfordev** [comment]
AFAICT, this is not a wxWidgets DLL.

Firstly, the name: wx.dll. This does not match the wxWidgets DLL naming pattern.

Secondly, looking at the DLL details in Explorer shows it is a wxLua library:
![wx-dll-lua](https://github.com/user-attachments/assets/72f969be-26ae-4f3b-9acb-f757168ed494)

Lastly, program  Dependencies shows it does not export wxWidgets classes, only wxLua (e.g., `wxLuaModuleApp`) and it depends on lua54.dll.

All this means that you should report the issue to wxLua maintainers, not wxWidgets ones.

BTW, attempting to open this DLL in Dependency Walker (DW) makes DW freeze. I don't think I ever saw that with any other DLL (but I don't open that many in DW).

**Comment by vadz** [comment]
Thanks, I didn't even realize `wx.dll` was the actuall DLL name and not a shortcut for "wxWidgets DLL".

We absolutely need a way to reproduce the problem using wx sources only, we can't do anything about any problems in DLLs that are not built by us.

**Comment by starwing** [comment]
Okay, I will try to build a pure wxWidgets DLL and a pure C program for it. Sorry for the noise from Lua binding (I'm noticing this 
strange behavior when I trying to  make a distro of some Lua bindings).

**Comment by PBfordev** [comment]
FWIW, running this code built with MSVS 2022 as 64-bit console application on Windows 10 
```cpp
#include <windows.h>

int main()
{
    HMODULE wxDLL = LoadLibraryW(L"wx.dll");

    if ( !wxDLL )
    {
        LPVOID msgBuf;
        DWORD  bufLen = FormatMessageW(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM ,
                                       nullptr, GetLastError(), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPWSTR)&msgBuf, 0, nullptr);
        if ( bufLen )
        {
            MessageBoxW(nullptr, (LPCWSTR)msgBuf, L"ERROR", MB_OK | MB_ICONERROR);
            LocalFree(msgBuf);
        }
        else
        {
            MessageBoxW(nullptr, L"LoadLibrary(wx.dll) failed.", L"ERROR", MB_OK | MB_ICONERROR);
        }
    }
    else
    {
        FreeLibrary(wxDLL);
    }
}
```
produces only the message box with an error message _The specified module could not be found_ (probably lua54.dll). This IMO further confirms that the issue is in the lua54.DLL (in its `DllMain()`?) and nothing do with wxWidgets itself.

**Comment by starwing** [comment]
@vadz @PBfordev this is a real minimal example:
[wx-test.zip](https://github.com/user-attachments/files/16398288/wx-test.zip)

Runs host.exe to see the crash in ntdll.dll
to build it, change the `wxdir` in `build.bat` and run. the wxWidgets used built as:
```
mkdir wx-build && cd wx-build
cmake -DwxBUILD_USE_STATIC_RUNTIME=ON -DCMAKE_INSTALL_PREFIX=%CD%/../wx-dist ../wxWidgets-3.2.5
cmake --build . --config Release
cmake --install .
```

**Comment by vadz** [comment]
Is static runtime required to reproduce the problem?

**Comment by starwing** [comment]
> Is static runtime required to reproduce the problem?
> 
> 
> 
> P.S. Also, the ZIP still includes `wx.dll`, what is this and where does it come from? The example can't be really called minimal when it includes external DLLs...

I can try not static linking. I'm just used to doing it this way, so that my dll can run on more systems. 

The wx.dll is built from dll.cpp, I just include all binaries for others could run it directly.

**Comment by starwing** [comment]
> Is static runtime required to reproduce the problem?

I have tried, dynamic linked `MSVCP140D.dll` still crashed in `ntdll.dll`.

![image](https://github.com/user-attachments/assets/bf122dbd-404f-49b9-be7c-b395470011f6)

**Comment by b-fission** [comment]
You might want to change `wxUSE_CMDLINE_PARSER` to 0 in [include/wx/msw/setup.h](https://github.com/wxWidgets/wxWidgets/blob/a8b6fdb7a7d518258a56b6a88262bf8281ddd26e/include/wx/msw/setup.h#L216) and then rebuild wxWidgets. That should get rid of the crash on exit. It might be related to argc/argv being 0/null in the host app.

**Comment by starwing** [comment]
@b-fission Thanks for the reply! it works when build wxWidgets without `wxCmdParser` support!

but `wxLua` uses the `wxCmdParser`, disable it makes `wxLua` build fail :-(

Is there any workaround to pass valid `argc`/`argv` in `entry()` makes me patch the `wxLua` code to work?

**Comment by b-fission** [comment]
Have you tried editing [this line from luamodule.cpp](https://github.com/pkulchenko/wxlua/blob/4d83c8d44eeccf88683ca0146a13b16d0b0d4264/wxLua/modules/luamodule/luamodule.cpp#L140)?

Change it from `return wxApp::OnInit();` to `return true;`

**Comment by starwing** [comment]
> Have you tried editing [this line from luamodule.cpp](https://github.com/pkulchenko/wxlua/blob/4d83c8d44eeccf88683ca0146a13b16d0b0d4264/wxLua/modules/luamodule/luamodule.cpp#L140)?
> 
> Change it from `return wxApp::OnInit();` to `return true;`

change it to `return true` still crashes on exit. I feel like if we call any functions from wxWidgets in DLL, then the `ntdll.dll` will crash on exit, and it's always crashes on `RtlpFlsDataCleanup`, I think the root cause should find out to solve this protblem.

**Comment by vadz** [comment]
Thanks, I think I understand what's going on here, but I don't see a good solution yet, unfortunately.

The problem is that, since e19984e2dd8bfc1a9f96477feb61d6029a7694f8, we use `FlsAlloc()` which calls our function to free memory when the process terminates, but in this case this happens after wx code is not present in memory any more because the DLL got unloaded, and so calling the callback crashes. We need to somehow ensure that we call `FlsFree()` on DLL unload, but I don't know how can we do it when static wx lib is linked as part of another DLL.

Right now my only idea is to revert the commit above (after reverting cf66599eba39810d40da01a03d0ec87a4b03a3d2 too).

cc @nietsu in case you have any ideas about how to fix this

**Comment by starwing** [comment]
@vadz Thanks for the root cause! I can run any code when the DLL unloaded (from DllMain), So it's good for me to add a function which let user call when the DLL unloaded.

**Comment by vadz** [comment]
While it's true that this would be relatively simple to fix once you know you have to call some function on DLL unload, I'm afraid it could still result in a lot of aggravation when the application starts crashing after updating wx and before you find the right function to call, so I'm reverting this entirely for 3.2.6, see #24747. If you merge the changes from there, this crash shouldn't happen any longer.

**Comment by starwing** [comment]
@vadz Thanks for the fix! it works like a charm, the DLL doesn't crashes on exit now.

But I have some extra issues about the wxWidgets binding :-(

I use the [MemoryModule](https://github.com/fancycode/MemoryModule) to load `wx.dll` for inject the depends of `lua54.dll` into lua executable itself, but It crashs on `wxEntryStart`, it seems crashes on the `DoCommonPostInit`, `RegisterModule` and the register of `wxDDEModule`. But it seems a bug of `MemoryModule` itself. Loading `wx.dll` with just `LoadLibraryA` works well, I will look into `MemoryModule` and `wxDDEModule` to find out why it crashes.

Anyway, Thanks the great fix!

**Comment by starwing** [comment]
I have found out the reason of the wxWidgets crashes on `MemoryModule`. (FYI, [this issue]( https://github.com/fancycode/MemoryModule/issues/62)). `MemoryModule` doesn't support TLS initialize when load DLLs, makes `wxCriticalSection` initialize failed. I will try to patch it to support it, but that's not caused by wxWidgets. So thanks all! This issues now solved complete!

**Comment by Dan-Korn** [comment]
Thank you for fixing this.  We upgraded from 3.1 to 3.2.4 and were wondering why the host application using our DLL (which links statically to wxWidgets) was crashing on close.  I saw the note in the 3.2.6 changelog and upgraded and it no longer crashes.
