### ISSUE TITLE
wxStaticText and wxCheckBox added to wxAuiToolBar are shown with a different background colour than wxAuiToolBar.

### ISSUE THREAD

**Issue by rossanoparis** [wxWidgets/wxWidgets#24765]
### Description

As you can see in the picture below, the two controls are shown with an unexpected background colour
![image](https://github.com/user-attachments/assets/fcd3cc43-5673-445b-81ff-49afa02b6fdd)

In order to reproduce the behaviour I've modified the "aui" sample, adding the following lines of code.
Here I've attached the modified file.
[auidemo.cpp.zip](https://github.com/user-attachments/files/16657946/auidemo.cpp.zip)

I added the following lines of code to auidemo.cpp
```
// WXTEST01 - Start
tb4->AddSeparator();
wxStaticText* statictext = new wxStaticText(tb4, ID_SampleItem + 1000, "This is a wxStaticText");
tb4->AddControl(statictext);
wxCheckBox* checkbox = new wxCheckBox(tb4, ID_SampleItem + 1001, "This is a wxCheckBox");
tb4->AddControl(checkbox);
// WXTEST01 - End

```
### Platform and version information

- wxWidgets version  you use: 3.2.4 and 3.3.0 (master 2024-08-16)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10, Windows 11

**Comment by vadz** [comment]
Using a `wxPanel` for the control might provide a workaround, but this should definitely work even without it, of course...

**Comment by vadz** [comment]
I've created #24780 fixing this, please let me know if you see any problems with it.

**Comment by rossanoparis** [comment]
Thank you @vadz it's OK ...

![image](https://github.com/user-attachments/assets/9ad777db-2757-4d23-84ba-9d6ba50e9d98)
