### ISSUE TITLE
wx uses incorrect keyboard layout in some cases

### ISSUE THREAD

**Issue by unxed** [wxWidgets/wxWidgets#24772]
1. Set Russian keyboard layout to be 1st one in system, English to be the 2nd one
2. Get wx from master
3. Build it
4. Build keyboard sample
5. Run it
6. Select English keyboard layout
7. Press `z` in sample app window

**Expected behavior:**
Keys are shown as `z` in all events

**Observed behavior:**
Keys are shown as `я` in all events except Char

Looks similar to https://github.com/wxWidgets/wxWidgets/issues/23421.

![Снимок экрана от 2024-08-21 20-07-15](https://github.com/user-attachments/assets/952abbdf-ec7b-4788-91e9-208d6ace6fc2)

**Comment by unxed** [comment]
Found a source of a problem.
```
                KeySym keysymNormalized = XkbKeycodeToKeysym(dpy, keycode, 0, 0);
```
uses first installed keyboard layout, not the current one. Changing it to
```
                XkbStateRec state;
                XkbGetState(dpy, XkbUseCoreKbd, &state);
                XkbDescPtr xkb = XkbGetMap(dpy, XkbAllComponentsMask, XkbUseCoreKbd);
                XkbGetNames(dpy, XkbGroupNamesMask, xkb);
                KeySym keysymNormalized = XkbKeycodeToKeysym(dpy, keycode, state.group, 0);
                XkbFreeKeyboard(xkb, XkbAllComponentsMask, True);

```
fixes this issue.

**Comment by unxed** [comment]
Could you please tell me from which release this fix is included in wxWidgets?

**Comment by unxed** [comment]
Still reproduces in wx master!

**Comment by unxed** [comment]
It's `Alt`+`т`

![изображение](https://github.com/user-attachments/assets/62498e70-6c55-4ee2-9220-179f027b7c30)

**Comment by unxed** [comment]
Proposed fix:

```
diff --git a/src/gtk/window.cpp b/src/gtk/window.cpp
index 46dc206694..0b6b3f9d99 100644
--- a/src/gtk/window.cpp
+++ b/src/gtk/window.cpp
@@ -1139,12 +1139,12 @@ wxTranslateGTKKeyEventToWx(wxKeyEvent& event,
     if ( !key_code )
     {
         // do we have the translation or is it a plain ASCII character?
-        if ( (gdk_event->length == 1) || wxIsAsciiKeysym(keysym) )
+        if ( (gdk_event->length == 1) || gdk_keyval_to_unicode(gdk_event->keyval) )
         {
             // we should use keysym if it is ASCII as X does some translations
             // like "I pressed while Control is down" => "Ctrl-I" == "TAB"
             // which we don't want here (but which we do use for OnChar())
-            if ( !wxIsAsciiKeysym(keysym) )
+            if ( !wxIsAsciiKeysym(keysym) && (KeySym)gdk_event->string[0] )
             {
                 keysym = (KeySym)gdk_event->string[0];
             }

```

But I’m not sure if this might break something elsewhere.

**Comment by vadz** [comment]
> keycode is correct, but unicodechar is in wrong layout in keyup/down

Wait, why is it wrong? It is correct that KEY events return the "key", on the keyboard, and not the "character" generated by this key which is only in CHAR event. This is consistent with the events not using Alt and also with Windows.

AFAICS everything works just as expected here, but please reopen if I'm missing something.
