### ISSUE TITLE
Add support for RelWithDebInfo build type

### ISSUE THREAD

**Issue by xyz1001** [wxWidgets/wxWidgets#24779]
### Description

Please use the following sections in your report:

#### Bug description:

Error occurred while I build wxwidgets with RelWithDebInfo build type. And the reason is that the top CMakeListst.txt add this limit in line 16. 
```
        set(CMAKE_CONFIGURATION_TYPES "Debug;Release")
```
It is ok after change this line to 
```
        set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo")
```

#### Expected vs observed behaviour:

It should not fail and build static libraries and pdb.

#### Stack trace:

[build.log](https://github.com/user-attachments/files/16721451/build.log)

#### To Reproduce:

1. Install lastest conan
2. execute `conan install --requires="wxwidgets/3.2.5" -s:h build_type=RelWithDebInfo --build="wxwidgets/*"`
3. See error

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by vadz** [comment]
As `CMAKE_CONFIGURATION_TYPES` is only set to this value if it isn't already set, couldn't you and/or Conan simply set to your preferred value in your own CMakeFile? Maybe it's even possible to set it on Conan command-line?

**Comment by xyz1001** [comment]
You are right. I will create a pull request for conan-center-index

**Comment by xyz1001** [comment]
https://github.com/conan-io/conan-center-index/pull/25046
