### ISSUE TITLE
webview sample issues

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#24787]
When running the webview sample on Windows (using `wxWebViewEdge`), there is always a memory leak reported by MSVS when closing it:
```
Detected memory leaks!
Dumping objects ->
{10545} normal block at 0x000002442B8247D0, 8 bytes long.
 Data: < P F    > 18 50 0D 46 FD 7F 00 00 
{10544} normal block at 0x000002442B824820, 16 bytes long.
 Data: <X  I     G +D   > 58 9C 89 49 F6 7F 00 00 D0 47 82 2B 44 02 00 00 
Object dump complete.
```
The leak is easy to fix, it is created by not deleting the old log target:
```diff
diff --git a/samples/webview/webview.cpp b/samples/webview/webview.cpp
index 427b53ef44..2d52600acb 100644
--- a/samples/webview/webview.cpp
+++ b/samples/webview/webview.cpp
@@ -548,7 +548,7 @@ WebFrame::WebFrame(const wxString& url, int flags, wxWebViewWindowFeatures* wind
         m_log_textCtrl = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY | wxTE_RICH2);
         m_log_textCtrl->SetMinSize(FromDIP(wxSize(100, 100)));
         topsizer->Add(m_log_textCtrl, wxSizerFlags().Expand().Proportion(0));
-        wxLog::SetActiveTarget(new wxLogTextCtrl(m_log_textCtrl));
+        delete wxLog::SetActiveTarget(new wxLogTextCtrl(m_log_textCtrl));
 
         // Log backend information
         wxLogMessage("Backend: %s Version: %s", m_browser->GetClassInfo()->GetClassName(),
```

However, I do not understand the purpose of class `DebugOnlyLog`, which is created and set as the log target in `WebApp::OnInit()`:
https://github.com/wxWidgets/wxWidgets/blob/2fe07151440ad19a8e3d80001d74a4399134b8c2/samples/webview/webview.cpp#L365-L383
only to be replaced by the `wxLogTextCtrl` when creating the main frame `WebFrame` (see the patch above)? Based on the comment, this may be leftover from when `wxLogWindow` was used instead of `wxLogTextCtrl`, only the former passing the messages to the active log target. If I understand the code correctly and both log targets are still wanted, perhaps `wxLogChain` should be used...

**Comment by vadz** [comment]
Thanks, 33931b7378 (UI improvements to WebView sample, 2024-03-19) indeed made using `DebugOnlyLog` irrelevant, so I'll just remove it.

**Comment by PBfordev** [comment]
Speaking about irrelevant code there, another sample change was Chromium-related:
https://github.com/wxWidgets/wxWidgets/blob/2fe07151440ad19a8e3d80001d74a4399134b8c2/samples/webview/webview.cpp#L565-L570

It seems that `wxWebViewChromium` does not implement `AddScriptMessageHandler()`, i.e., it is not overridden from `wxWebView`, is the comment/code an oversight or preparing for implementing the method?

**Comment by vadz** [comment]
> Speaking about irrelevant code there, another sample change was Chromium-related:

It's Chromium-related in the sense that we need to delay calling `GetUserAgent()` until `wxEVT_WEBVIEW_CREATED` with it, and then we can't call `AddScriptMessageHandler()` until after calling `GetUserAgent()` as explained.

We could move `AddScriptMessageHandler()` from `initShow` to the `else` branch of CEF check to avoid the error, but it would be better to implement this for CEF, of course. I'm not sure about how exactly this is supposed to work, so I don't know how difficult this would be.

**Comment by PBfordev** [comment]
I plan to submit a PR changing when `wxWebViewEdge` sends `wxEVT_WEBVIEW_CREATED` (waiting for other `wxWebView` PRs to be merged), see https://github.com/wxWidgets/wxWidgets/issues/24758.

I was going to change the sample code too, where all the backends would catch the event and log it (still keeping the conditional compilation block for `wxWebViewChromium`).
