### ISSUE TITLE
Chinese whitespace character seems to be wrongly evaluated as alphanumeric character on wxOSX but not on wxGTK and wxMSW

### ISSUE THREAD

**Issue by tobiolo** [wxWidgets/wxWidgets#24801]
#### Bug description:

On the macOS port, Chinese characters are not correctly evaluated whether they represent an alphanumeric character or not.
For full description see https://github.com/aardappel/treesheets/issues/708
We suspect wxIsalnum not working properly on Mac.

#### Expected vs observed behaviour:

Chinese characters that are evaluted as whitespace on Linux and Windows port of wxWidgets are not evaluated the same on macOS.

### Platform and version information

- wxWidgets version  you use: latest / git
- wxWidgets port  you use: wxOSX
- OS  and its version: OSX

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by tobiolo** [comment]
Could you please post just the patch you applied to the source code?

**Comment by vadz** [comment]
Sorry, what's a "Chinese whitespace character"? The linked issue contains the following text:

```
你可以复制单元格，例如，选择这个单元格，用 CTRL+C 复制，然后选择上面的任何网格线并按 CTRL+V。如果你选择了多个单元格，所选内容将作为多行插入到目的地。试试看。剪切（CTRL+X）或删除多个单元格选择的操作同样直观。如果插入单元格“内联”粘贴是不可取的，你总是可以先创建一个新的网格，然后在那里粘贴，以创建层次结构。
```

which only contains normal spaces AFAICS.
