### ISSUE TITLE
Clarify usage of wxScrolledWindow

### ISSUE THREAD

**Issue by wh11204** [wxWidgets/wxWidgets#24824]
After fighting two hours with wxScrolledWindow refusing to show the scrollbars in the "The most automatic and newest way" mode I found this remark in a [Wiki page](https://wiki.wxwidgets.org/WxScrolledWindow):

**Trouble with The most automatic and newest way:**
Don't forget to call SetScrollRate. If you want to add components dynamically sizer->FitInside(this) makes the scroll bars appear without resizing the panel

Can this remark be added to the wxScrolledWindow [documentation](https://docs.wxwidgets.org/trunk/classwx_scrolled.html)?

TIA

**Comment by vadz** [comment]
I see several mentions of `SetScrollRate()` in the documentation already, so I'm not sure what do you think should be changed there. But any PRs to the documentation (this part is in `interface/wx/scrolwin.h`) would be welcome, of course.

**Comment by wh11204** [comment]
I would add something like "If you add or remove elements from the sizer later then call sizer->FitInside(this) to update the scroll bars".

**Comment by wh11204** [comment]
Created PR #24825
