### ISSUE TITLE
Versions > 3.0.5.1 seem to be stealing focus. Maybe just a settings problem of the projects that use wxwidgets?

### ISSUE THREAD

**Issue by gc-user** [wxWidgets/wxWidgets#24846]
#### Bug description:

I came across this nuisance when the distro I use rebuilt the same version of audacity (v2.4.1) against v3.2.2.1 of wxwidgets. The previous version of wxwidgets used was v3.0.5.1.

After that update, audacity would always steal focus. E.g. when it was doing some task and the window was minimized and one would work with some other application, audacity would put itself to the front once it was done with the task.

There's a similar bug report for [tenacity](https://codeberg.org/tenacityteam/tenacity/issues/98) (a fork of audacity), but as I have the same version of audacity built against 2 different versions of wxwidgets, I assume that behaviour is caused by wxwidgets rather than audacity / tenacity. Although, it might just be some setting that the devs of other projects could / should enable or disable in order to suppress this stealing of focus.

#### Expected vs observed behaviour:

I would expect the behaviour to be like with v3.0.5.1, i.e. that an application would e.g. stay minimized until maximized by the user. But instead, with e.g. 3.2.2.1 the application would maximize by itself and put itself to the front when a tasks is finished.
If one would e.g. type some text in libreoffice, all of a sudden audacity would steal focus and one would type or click in the audacity window instead of the one one was just using.

That behaviour got so annoying that I decided to hold wxwidgets (i.e. wxwidgets-common and wxwidgets-gtk3) to v3.0.5.1 and also audacity and all other applications that use wxwidgets.

#### To Reproduce:

Steps to reproduce the behaviour, please make them as detailed as possible.
For example:

1. Build audacity (v2.4.1, newer versions might not build against older versions of wxwidget) against wxwidgets v3.0.5.1 and v3.2.2.1.
2. Open some audio file and let audacity perform some operation that would take some time.
3. Minimize the audacity window.
4. Notice the different behaviour between the two builds. The one build against 3.0.5.1 would stay minimized when done with the task, the one build against 3.2.2.1 would auto-maximize / steal focus.

### Platform and version information

- wxWidgets version  you use: v3.2.2.1
- wxWidgets port  you use: wxGTK
- OS  and its version: void linux
  
  + GTK version:  3.24.38 (back when I tested back and forth one year ago)
  + Which GDK  backend is used: X11
  + Desktop environment : xfce 4.18

Note: I tried to build audacity against wxwidgets v3.1.0, to pin down the moment / version when this behaviour was actually introduced but that failed. The make config would have needed adjustments that I'm not able to do, as I'm not a coder.

I also just tested the current version of audacity (v3.4.2) that the distro I use offers, built against wxwidgets v3.2.5 to make sure the behaviour is still there (and it is).

**Comment by vadz** [comment]
Sorry, we don't have the resources to debug audacity, unfortunately. All I can say is that wxWidgets should never raise/focus/activate the application on its own, so the most likely explanation is that Audacity calls some function which does it, e.g. `wxWindow::Raise()`, and this function didn't work correctly (at least in your environment) in 3.0 but was fixed to work in 3.2. The solution would then be to remove the call to this function.

But I don't think this is an issue in wxWidgets itself, unless someone (you or Audacity developers) can show that wxWidgets does activate the application itself, without calling `Raise()`.

**Comment by gc-user** [comment]
Thanks for your reply.

I didn't really expect for anyone to test audacity. I just couldn't find a "discussions" section on this github site and thus opted for the "issue/bug report" option and then just followed the template, but really wanted to get some lead where / what to look for, which you have given me with your reply and specifically the Raise() call.

So, thank you!

Now I can look into this and hopefully can be more specific when asking the audacity devs to check if they can change something.

**Comment by vadz** [comment]
Please note that I'm not _sure_ that it's due to calling `Raise()`, there might be some other reason it gets brought up, it just looks like the most straightforward explanation. But in any case it would be great if you could please look at what happens in the code once a task finishes.

Good luck!

**Comment by gc-user** [comment]
Thanks again for your input and help!
I'll try my best.

The information that in v3.0 something wasn't quit right and was fixed in v3.2 is helpful on its own as it would explain changes in behaviour without changing anything in the code (of audacity).
