### ISSUE TITLE
wxAuiToolbar buttons remain highlighted

### ISSUE THREAD

**Issue by rossanoparis** [wxWidgets/wxWidgets#24849]
### Description

Building the latest v3.3.0 (master 2024-09-29) I observe the following behavior for wxAuiToolbar
It wasn't not present using v3.3.0 (master 2024-08-16)

Moving the mouse cursor over the toolbar, the buttons remain highlighted and the text appears to be in bold.
![aui-toolbars](https://github.com/user-attachments/assets/24c65b40-f2f9-4003-8220-cfecce7d84af)

This is my cmake options I normally use to build the library.
(_I didn't change them since my last build_)
`cmake -S%WXSRC% -B%WXBLD% -A%WXARCH% -D"wxBUILD_TOOLKIT=msw" -D"CMAKE_BUILD_TYPE=Debug" -D"wxBUILD_DEBUG_LEVEL=2" -D"BUILD_SHARED_LIBS=ON" -D"wxBUILD_USE_STATIC_RUNTIME=OFF" -D"wxBUILD_OPTIMISE=OFF" -D"wxBUILD_PRECOMP=ON" -D"wxUSE_OPENGL=ON" -D"wxUSE_SPELLCHECK=OFF" -D"wxUSE_DEBUGREPORT=ON" -D"wxUSE_ON_FATAL_EXCEPTION=ON" -D"wxUSE_UNSAFE_WXSTRING_CONV=OFF" -D"wxUSE_ZLIB=builtin" -D"wxUSE_EXPAT=builtin" -D"wxUSE_LIBPNG=builtin" -D"wxUSE_LIBJPEG=builtin" -D"wxUSE_LIBTIFF=builtin" -D"wxUSE_NANOSVG=builtin" -D"wxUSE_REGEX=builtin" -D"wxUSE_WINSOCK2=ON" -D"wxBUILD_MSVC_MULTIPROC=ON" -D"wxBUILD_COMPATIBILITY=NONE" -D"wxBUILD_VENDOR="
`
### Platform and version information

- wxWidgets version  you use: 3.3.0 (master 2024-09-29)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

**Comment by vadz** [comment]
Thanks, this was indeed broken by 76b3738d13 (Stop using wxAutoBufferedPaintDC in wxAuiToolBar, 2024-08-23), but this commit logic looks fine to me, what is not fine is that `wxCustomBackgroundWindow` in wxMSW doesn't actually erase its own background. I'll try to fix this...

**Comment by MaartenBent** [comment]
> There is actually nothing wrong with `wxCustomBackgroundWindow`, but we need to let it to its work — see #24854 and please let me know if you still see any problems with it.

That fix works too.

**Comment by rossanoparis** [comment]
> ... see https://github.com/wxWidgets/wxWidgets/pull/24854 and please let me know if you still see any problems with it.

it works, thank you
