### ISSUE TITLE
Using Print(prompt=true) to display dialog overwrites provided wxPrintDialogData

### ISSUE THREAD

**Issue by fleckware** [wxWidgets/wxWidgets#24868]
#### Bug description:

When I call `Print(this, &printout, true)` on my `wxPrinter`, the initial `wxPrintDialogData` settings I had provided appear to be overwritten by default values. 

#### Expected vs observed behaviour:

*Expected:* When I have a `wxPrintDialogData` and call `SetAllPages(false)` on it, and then construct my `wxPrinter` using that same `wxPrintDialogData`, I expect the "all pages" setting to be in effect when I call `Print` on my printer.

*Observed:* Although I explicitly call `SetAllPages(false)`, the printer dialog still opens with "all pages" set to true.

#### Patch or snippet allowing to reproduce the problem:

In `samples/printing/printing.cpp`, add this line after line 363:

`printDialogData.SetAllPages(false);`

In context:
```
void MyFrame::OnPrint(wxCommandEvent& WXUNUSED(event))
{
        wxPrintDialogData printDialogData(* g_printData);
        printDialogData.SetAllPages(false);

        wxPrinter printer(&printDialogData);
        MyPrintout printout(this, "My printout");
        if (!printer.Print(this, &printout, true /*prompt*/))
        ...
```

I would also like to note that when you display the print dialog on its own, the `SetAllPages` setting works as expected, so it appears to me that this is specifically a problem with using `printer.Print(this, &printout, true)`

You can recreate the "working" behavior by creating a standalone print dialog that runs before the `Print` one, using this modified code snippet with two extra lines:

```
void MyFrame::OnPrint(wxCommandEvent& WXUNUSED(event))
{
        wxPrintDialogData printDialogData(* g_printData);
        printDialogData.SetAllPages(false);

        wxPrintDialog printDialog(this, &printDialogData);
        printDialog.ShowModal();

        wxPrinter printer(&printDialogData);
        MyPrintout printout(this, "My printout");
        if (!printer.Print(this, &printout, true /*prompt*/))
        ...
```

#### To Reproduce:

To reproduce the first code snippet, which is only the "broken" behavior:

1. After making the first modification, build the sample in `samples/printing` using makefile.unx and run it
2. Click on the 'File' menu
3. Click on the 'Print...' option
4. Observe that "All Pages" is still the selected radio button

To reproduce the second code snippet, which has a "working" dialog:

1. Make the second modification and rebuild
2. Click on the 'File' menu
3. Click on the 'Print...' option
4. The first "working" dialog will appear. Observe that "All Pages" is unselected, and "Pages:" is selected instead
5. Click "Cancel" to exit the first dialog
6. The second "broken" dialog will appear. Observe that "All Pages" is selected, even though it should be using the same `wxPrintDialogData` as the first dialog

### Platform and version information

- wxWidgets version  you use: 3.1.4
- wxWidgets port  you use: wxGTK
- OS  and its version: Red Hat Enterprise Linux 8.6
  
  + GTK version:  3.22.30
  + Which GDK  backend is used: not 100% sure but I think it's X11
  + Desktop environment : Gnome
  + Current theme:  n/a

**Comment by vadz** [comment]
This can still be reproduced with

```diff
diff --git a/samples/printing/printing.cpp b/samples/printing/printing.cpp
index 7c4d7254db..66ddeffa14 100644
--- a/samples/printing/printing.cpp
+++ b/samples/printing/printing.cpp
@@ -356,7 +356,7 @@ void MyFrame::OnPrint(wxCommandEvent& WXUNUSED(event))
     printDialogData.SetMaxPage(2);
     printDialogData.SetFromPage(1);
     printDialogData.SetToPage(2);
-    printDialogData.SetAllPages(true);
+    printDialogData.SetAllPages(false);
 
     wxPrinter printer(&printDialogData);
```

in current master and it's due to this line here:

https://github.com/wxWidgets/wxWidgets/blob/1880fe8b64bb34713f9baf27abd038b50d8dc558/src/gtk/print.cpp#L957

which unconditionally sets "all pages" to true.

Looking also at

https://github.com/wxWidgets/wxWidgets/blob/1880fe8b64bb34713f9baf27abd038b50d8dc558/src/gtk/print.cpp#L978

it seems that the logic here is that you need to set the pages range to the subset of pages you want to print in the overridden `wxPrintout::GetPageInfo()`, but this doesn't make any sense because this function is supposed to use `wxPrintDialogData` to determine which pages to print, so there is a kind of circular dependency here...

I think we should just stop trying to second guess the application code and do

```diff
diff --git a/src/gtk/print.cpp b/src/gtk/print.cpp
index 8406ec916d..32af642a03 100644
--- a/src/gtk/print.cpp
+++ b/src/gtk/print.cpp
@@ -954,7 +954,6 @@ bool wxGtkPrinter::Print(wxWindow *parent, wxPrintout *printout, bool prompt )
     int fromPage, toPage;
     int minPage, maxPage;
     printout->GetPageInfo(&minPage, &maxPage, &fromPage, &toPage);
-    m_printDialogData.SetAllPages(true);
 
     if (minPage < 1) minPage = 1;
     if (maxPage < 1) maxPage = 9999;
@@ -975,9 +974,6 @@ bool wxGtkPrinter::Print(wxWindow *parent, wxPrintout *printout, bool prompt )
         else if (toPage < minPage) toPage = minPage;
     }
 
-    if (((minPage != fromPage) && fromPage != 0) || ((maxPage != toPage) && toPage != 0)) m_printDialogData.SetAllPages(false);
-
-
     wxPrintData printdata = GetPrintDialogData().GetPrintData();
     wxGtkPrintNativeData *native = (wxGtkPrintNativeData*) printdata.GetNativeData();
 
```

here, which seems to be consistent with how wxMSW works too. Any objections to applying this?

**Comment by fleckware** [comment]
Thanks for the quick look at this! I made these modifications to my local build of wxWidgets and can confirm that they fix my problem. So, no objections on my end :)
