### ISSUE TITLE
Not all locale files are installed during Makefile build

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/wxWidgets#24880]
When running `make install`, not all currently produced locale files actually get installed.

The list that gets installed seems to be this hard-coded list of ~22 which git blame says has not been updated in over 20 years:
https://github.com/wxWidgets/wxWidgets/blob/master/build/bakefiles/wx.bkl#L142

Whereas the locales directory seems to contain ~46.

Is there a way in bakefile-speak to specify a dynamically generated list of files?  If not, I could at the very least propose an update to the hard-coded list.

**Comment by yurchor** [comment]
It looks like Makefile.in does not contain all locales

https://github.com/wxWidgets/wxWidgets/blob/5ff25322553c1870cf20a2e1ba6f20ed50d9fe9a/Makefile.in#L2208

**Comment by vadz** [comment]
Thanks for noticing this!

This part of `Makefile.in` is generated using `gettext-catalogs` tag defined in bakefile `gettext` module and modifying it probably doesn't make much sense, so I think we should do one of:

1. Just update the list in https://github.com/wxWidgets/wxWidgets/blob/eda54e82e281ce949ae44f6796ae50669f7c1924/build/bakefiles/wx.bkl#L143-L144
2. Stop using `gettext-catalogs` and add something like `<fragment format="autoconf" file="make_locale.mk"/>` with hand-written `make_locale.mk`.
