### ISSUE TITLE
AUI drop indicator drawn at completely wrong location

### ISSUE THREAD

**Issue by vadz** [wxWidgets/wxWidgets#24892]
Other issue (not solved by this patch)  is e.g. the following
![image](https://github.com/user-attachments/assets/17193453-7f7d-406e-a743-1534ee5abc40)

Drop indicator of aui manager (blue rect) is at the wrong position when we try to drag und drop the right tab back to the left one (mouse position here was some pixels next to the 65_pages tab).

_Originally posted by @sz5000 in https://github.com/wxWidgets/wxWidgets/issues/24890#issuecomment-2422392975_

**Comment by vadz** [comment]
I've tried debugging this but unsuccessfully so far. Or, rather, I only have negative results:

1. This is not due to `CalculateHintRect()` returning a wrong value, it never returns coordinates of such a narrow rectangle.
2. This is not due to timer-based fade in, the problem is still visible when not using it.
3. This is not even wxMSW-specific, I see the same problem under Linux.

It really looks like we're doing something wrong with the overlay somewhere, but I don't see where yet.

**Comment by MaartenBent** [comment]
It happens when drawing the overlay over the tabs instead of over the panel. Converting coordinates in `ClientToScreen` seems to cause it:
https://github.com/wxWidgets/wxWidgets/blob/c301af42f923a9997e99bf8d3b8f00df667f88f9/src/aui/auibook.cpp#L2740

Also it should probably only draw the hint over the tabs, and not continuously switch between the panel and tabs while moving.

**Comment by vadz** [comment]
Thanks! It's nice to get back and see that the problem is already fixed :-)

This line is indeed the culprit, so I'm going to remove it and create a PR with my other related changes soon, but I am not sure how do you suggest to avoid switching between the panel and the tabs? Do you think we shouldn't be showing the hint for dest tabs at all?

**Comment by MaartenBent** [comment]
I am not sure if it should be fixed, or what the fix should be. But when I drag the right panel it keeps switching between these two overlays when the mouse is over the tab bar
<img src="https://github.com/user-attachments/assets/346d7efe-454f-4c9c-8585-2e455b76965a">
<img src="https://github.com/user-attachments/assets/4e86a36a-60ec-48d2-83f7-a8aec42412cc">

**Comment by vadz** [comment]
Yes, I've seen this, and it would be nice to improve this somehow, but it doesn't look _wrong_, just suboptimal.

BTW, I think it looks worse than it should because fade in doesn't work in this case, due to calling `ShowHint()` directly instead of using `DrawHintRect()`, I'm looking at fixing this too.

**Comment by vadz** [comment]
Also, it looks like `ShowHint()` had originally been written to take the rect in screen coordinates, as its documentation explicitly mentions this. So now I wonder if we should restore this instead of removing `ClientToScreen()` call because it might potentially be overridden in the user code...

This was probably changed in 29c8bfc249 (Use wxOverlay to show docking hint instead of transparent wxFrame, 2024-01-31), but I don't think it was done intentionally, was it?

cc @AliKet

**Comment by AliKet** [comment]
> This was probably changed in [29c8bfc](https://github.com/wxWidgets/wxWidgets/commit/29c8bfc24925f1f0c67b7f9a8645a03b65e412a4) (Use wxOverlay to show docking hint instead of transparent wxFrame, 2024-01-31), but I don't think it was done intentionally, was it?
> 
> cc @AliKet

I don't remember why I changed this at the time, but this is indeed the commit to blame (and sorry for introducing this annoying bug) and this patch should restore the correct behavior.

```
diff --git a/src/aui/framemanager.cpp b/src/aui/framemanager.cpp
index d972f40adf..128e70fc93 100644
--- a/src/aui/framemanager.cpp
+++ b/src/aui/framemanager.cpp
@@ -2984,11 +2984,14 @@ void wxAuiManager::OnHintFadeTimer(wxTimerEvent& WXUNUSED(event))
     ShowHint(m_lastHint);
 }
 
-void wxAuiManager::ShowHint(const wxRect& rect)
+void wxAuiManager::ShowHint(const wxRect& rect_)
 {
     wxOverlayDC dc(m_overlay, m_frame);
     dc.Clear();
 
+    wxRect rect = rect_; // rect_ is in screen coordinates
+    m_frame->ScreenToClient(&rect.x, &rect.y);
+
     wxDCClipper clip(dc, rect);
 
     if ( m_flags & wxAUI_MGR_RECTANGLE_HINT )
@@ -3125,7 +3128,7 @@ void wxAuiManager::StartPaneDrag(wxWindow* pane_window,
 // first calls DoDrop() to determine the exact position the pane would
 // be at were if dropped.  If the pane would indeed become docked at the
 // specified drop point, the rectangle hint will be returned in
-// client coordinates.  Otherwise, an empty rectangle is returned.
+// screen coordinates.  Otherwise, an empty rectangle is returned.
 // |pane_window| is the window pointer of the pane being dragged, |pt| is
 // the mouse position, in client coordinates.  |offset| describes the offset
 // that the mouse is from the upper-left corner of the item being dragged
@@ -3207,6 +3210,8 @@ wxRect wxAuiManager::CalculateHintRect(wxWindow* pane_window,
         }
     }
 
+    m_frame->ClientToScreen(&rect.x, &rect.y);
+
     return rect;
 }
 
```

Sorry again.

**Comment by vadz** [comment]
This was fixed by the commit above.
