### ISSUE TITLE
[Suggestion for simplifying the build process] Avoid requiring end users from having to check out additional git submodules

### ISSUE THREAD

**Issue by rubyFeedback** [wxWidgets/wxWidgets#24928]
Today I git cloned the repository here and then wanted to compile wxwidgets from source, as real men and women typically do on a Linux system.

However had, I ran into a problem:

    CMake Error at build/cmake/functions.cmake:609 (message):
      wxscintilla file does not exist:
      "/depot/j/wxWidgets-30.10.2024/src/stc/scintilla/include/Compat.h".  Make
      sure you checkout the git submodules.
    Call Stack (most recent call first):
      build/cmake/lib/stc/scintilla.cmake:13 (wx_add_builtin_library)
      build/cmake/lib/stc/CMakeLists.txt:10 (include)

So, cmake tells me to also check out the git submodules. I can do so (once I find
the syntax), but ...

... isn't that conceptually wrong?

If we have a released tarball from wxiwdgets, such as

    https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.5/wxWidgets-3.2.5.tar.bz2

Then it already has everything it needs by itself, in order to allow us
to compile this thing. External dependencies may still have to be solved by the
end user of course, which is another reason why I dislike additional git commands
to use. My assumption is "if I clone the git repository, I should be able to compile
this right away, without any further ado". That assumption works for many other
projects (not all, but most), so my request here is to actually change the default
when the repository is cloned. People who clone the repo like this, usually want to
be able to compile the project, without any additional git micro downloads or
"check this other repo out, yo man!" (which, if it is an external dependency, is totally
fine; I can handle this on my own if it is an EXTERNAL dependency; I am referring to
internal dependencies here).

Of course you may disagree with this opinion, in which case I recommend making this even
more complicated than it already is, just to prove your point, even though you'd then have
to "un-complicate" it when making the tarball, which will be simpler again, thus invalidating the other opinion just stated before - odd thing, IMO. :D

Thanks for reading this issue request anyway.

**Comment by vadz** [comment]
Sorry, I don't understand the point. There is no way to "change the default when the repository is cloned", this is determined by Git and not by any particular repository. We already have https://github.com/wxWidgets/wxWidgets/blob/master/README-GIT.md saying that you need to get the submodules too and I don't see what else can we do.
