### ISSUE TITLE
AUI toolbar squish when minimized and DockFixed

### ISSUE THREAD

**Issue by marekr** [wxWidgets/wxWidgets#24930]
We've gotten this bug in KiCad for awhile but at random where toolbars after some minimization of the app and unminization causes them to get drawn squished.

https://gitlab.com/kicad/code/kicad/-/issues/14581

In this one issue, it was due to our self closing infobar messages, if you minimized the window while the infobar was open, and then reopened it 10 seconds later (after the infobar would be removed), the toolbars are squished.

But there's definitely other ways to trigger it as I can get it in one window that doesn't even use a infobar.

I found a repro case using the disappearing infobar class we have (called WX_INFOBAR),

Repro auidemo.cpp here: https://gist.github.com/marekr/029504961b8df372a2b413382e5c5718

The repro works by
1. Click the Customize option for the vertical toolbar, I just picked the first place with a click event for this. Nothing special
2. The infobar message appears
![image](https://github.com/user-attachments/assets/a40fe300-39b1-4caa-a7ad-7f0475d42df6)
3. Minimize the application to task bar

![image](https://github.com/user-attachments/assets/356c062b-df79-4dc0-92be-2295dae739af)
4. Wait ~10 seconds (the timer is 6 seconds)
5. Unminimize the app from taskbar
6. Observe squished toolbar
![image](https://github.com/user-attachments/assets/36f0832d-afb2-444a-bc5d-f70b485845da)

Now, the identifiable cause is the DockFixed( true ) on the wxAuiPaneInfo cofigured for the vertical toolbar

```
    m_mgr.AddPane(tb5, wxAuiPaneInfo().
                  Name("tb5").Caption("Sample Vertical Toolbar").
                  ToolbarPane().Left().Resizable( true ).Movable( false ).*DockFixed( true)*
                .LeftDockable().RightDockable().CaptionVisible( false ));
```

Remove DockFixed( true ) and the behavior does not reproduce.

**Comment by marekr** [comment]
Seems like the issue is related to `wxAuiManager::LayoutAll` firing while being minimized with the fixed mode dock panes.

In particular

```
        if (dock.fixed)
        {
            // always reset fixed docks' sizes, because
            // the contained windows may have been resized
            dock.size = 0;
        }
```

zeros out the dock size before trying to calculate it again. Removing the dock.size = 0; statement also fixes it 


Looking further, it may be related to the cli_size variable which is from GetClientsize(), apparently when its minimized the value returned is junk

![image](https://github.com/user-attachments/assets/993c7267-5d81-42c2-ba3f-e20fd6761cf3)

**Comment by vadz** [comment]
Thanks, I see the problem and it's _not_ fixed by b4736f1ccb 

From what I've seen so far, the simplest thing to do to fix this particular problem is to avoid layout while minimized. But I wonder if it's sufficient, i.e. does this only happen after minimizing (or showing the desktop)?

P.S. The info bar also comes up with more and more close icons every time when you show it, it doesn't matter here, of course, but you need to remove `AddCloseButton()` call from your real code if you also have it there.

**Comment by marekr** [comment]
> Thanks, I see the problem and it's _not_ fixed by [b4736f1](https://github.com/wxWidgets/wxWidgets/commit/b4736f1ccb2479a1fdbd42c29e1ef0fc302f5657)
> 
> From what I've seen so far, the simplest thing to do to fix this particular problem is to avoid layout while minimized. But I wonder if it's sufficient, i.e. does this only happen after minimizing (or showing the desktop)?


I have definitely had the issue occur without the infobar open.  I've just never figured out why that happens. I was going to test later today if a monitor Dpi change while the window is minimized causes anything.


Would the "normal" rect returned by win32 GetWindowPlacement work better than GetClientSize for width/height as another workaround?


> P.S. The info bar also comes up with more and more close icons every time when you show it, it doesn't matter here, of course, but you need to remove `AddCloseButton()` call from your real code if you also have it there.

That's just a bug from me creating the repo case.

**Comment by vadz** [comment]
AFAICS any call to `wxAuiManager::Update()`, done for whatever reason, not necessarily due to hiding the info bar, doesn't work correctly when the window is minimized, so my question is not whether this can happen without using info bar, but whether this also happens without minimizing the window?

Also, `GetClientSize()` correctly returns (0,0) when the window is minimized, it's our own code which adjusts it wrongly in this case. But if this really happens only while minimized, I'd rather avoid calling it at all in this case and just do nothing and call `Update()` again when the window is restored.

**Comment by marekr** [comment]
>Also, GetClientSize() correctly returns (0,0) when the window is minimized, it's our own code which adjusts it wrongly in this case

Yes, that's why I'm asking if ::GetWindowPlacement which should always return the non minimized size in the normal rect field is a better option. Because then the layout logic will have a valid width and height to work with.

**Comment by marekr** [comment]
>, I'd rather avoid calling it at all in this case and just do nothing and call Update() again when the window is restored.

Yea this is also an option, I wasn't sure how to schedule a update after window restore occurs though

**Comment by vadz** [comment]
> Yea this is also an option, I wasn't sure how to schedule a update after window restore occurs though when I looked at it

AFAICS it's as simple [as this](https://github.com/wxWidgets/wxWidgets/pull/24934/commits/8b7147261943e3e50bc08492d225e6a012bb433d), see #24934, but please let me know if I'm missing something.
