### ISSUE TITLE
Disabled spinctrl shows active buttons

### ISSUE THREAD

**Issue by sciurius** [wxWidgets/wxWidgets#24948]
#### Bug description:

When a spinctrl is disabled, the [+] and [-] buttons still look active in wxGTK:

![scrot20241111102528](https://github.com/user-attachments/assets/765dbb3c-de80-4673-982f-6363e139fa0b)

#### Expected vs observed behaviour:

I'd expect them to be disabled (greyed out).

#### Stack trace:

N/A.

#### Patch or snippet allowing to reproduce the problem:

Apply this patch to the stock' controls example, build, run, select the wxGauge tab.

[controls.patch.txt](https://github.com/user-attachments/files/17700177/controls.patch.txt)

#### To Reproduce:

Steps to reproduce the behaviour, please make them as detailed as possible.
For example:

1. Build the modified `controls` sample program
2. Click on `wxGauge` tab
3. Look at the spintctrl.

### Platform and version information

- wxWidgets version  you use: 3.2.4
- wxWidgets port  you use: wxGTK
- OS  and its version: Fedora 39
  
  + GTK version: 3.24.43
  + Which GDK  backend is used: X11
  + Desktop environment : Mate
  + Current theme:

**Comment by vadz** [comment]
Must be theme-specific? On my system, using GTK 3.24.38, I don't see this (BTW you don't have to patch anything, just go to the "Spin" page of the "widgets" sample and use "Widget|Enable" to disable the widgets on that page).

**Comment by sciurius** [comment]
I can confirm that (some) other themes behave correct. Close as "not a wxWidgets issue"?

**Comment by vadz** [comment]
Ideal would be to check if the problem happens in "raw" GTK (with this theme) too, because it's still possible that we're doing something wrong here. Can you run the GTK widgets sample (if it still exists?) and check how spin controls look there?

**Comment by sciurius** [comment]
It is a theme thing. See
![scrot20241112231119](https://github.com/user-attachments/assets/81fa0c28-65c6-443f-a45d-ad8dd34b79f6)

In the left spinner, both buttons are enabled. In the right spinner, the [-] is disabled. Clear isn't it ☺.

**Comment by vadz** [comment]
I think this can be closed then, thanks for testing.
