### ISSUE TITLE
wxListCtrl overlay selection doesn't work when starting dragging from an item unlike in Explorer

### ISSUE THREAD

**Issue by BazaarAcc32** [wxWidgets/wxWidgets#24946]
Hi! Why in wxListCtrl overlay selection not working when we try to start select elements from non-empty area? In Windows (see file explorer screenshot) we can select list items even if we start our selection in non-empty area (area with elements), but in wxWidgets to select the elements we should start our selection from empty area (area, which is not filled by elements)

Windows file explorer screenshot (we can start selection from area which is filled by elements):
![windows-overlay-selection](https://github.com/user-attachments/assets/9abc59a8-19b9-4a73-bfd9-565fca03b56f)
wxListCtrl (cannot start selection from area which is filled by elements)
![wx-overlay-selection](https://github.com/user-attachments/assets/8e930c3c-1da7-4e2e-956d-35a3d9865b10)
wxListCtrl (we can start selection from area which is NOT filled by elements)
![Screenshot-218](https://github.com/user-attachments/assets/8cc1bfb6-f678-43ac-b0b3-fdd04c60636e)
How can i solve this problem? I want to get result as in the Windows file explorer

**Comment by vadz** [comment]
I can indeed reproduce this but I don't know why does this happen (or not happens). AFAICS we don't interfere with the native control mouse handling, more debugging is needed.

**Comment by MaartenBent** [comment]
Windows Explorer doesn't use a List View / SysListView32 like wxListCtrl. It's a custom control called DirectUIHWND according to Spy++.

**Comment by vadz** [comment]
Yes, but it mimics ListView and it looks like the standard control does have support for this, as selection works in the same way if you click outside any item. So I'm still not sure if it's not something that we (unintentionally) break, to confirm this I'd need to check it with "raw" Win32 API and I didn't have time to do it yet.

But I should have indeed mentioned that it's also possible that the standard control simply works like this...

**Comment by MaartenBent** [comment]
I see Windows uses the normal list view when you view properties of a file/folder on the security tab, and when you click Advanced on that tab. In those lists you can't select using this method.

**Comment by vadz** [comment]
Hmm, in this case we probably indeed won't be able to implement it, sorry. And thanks for looking at it.

**Comment by PBfordev** [comment]
I looked into this and found out that:
1. The feature is called marquee selection.
2. Creating marquee selection from non-empty space does not work when a `listview` is created with `LVS_EX_FULLROWSELECT`.
3. `wxListCtrl` is always created with `LVS_EX_FULLROWSELECT` style.

I think the style can be easily turned off in the user code, if one is willing to exchange full row selection for marquee selection from empty space.

**Comment by vadz** [comment]
Thanks a lot for looking at this and finding the root cause of the problem!

I agree that the OP should be able to turn this style off in their own code, but perhaps we could add some `wxListCtrl::MSWEnableFullRowSelect(bool)` to make it simpler.
