### ISSUE TITLE
Regression: Alpha values ​​of BMP from ICO files are no longer loaded

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24955]
Recently introduced with b21642b72b4128f0b64ed7d79b4d320cbfc35497 (`Fix loading BMP files which use 32bpp but do not have valid alpha, 2024-11-05`), BMP images from ICO files are now loaded without their alpha values.

This issue can be reproduced in the image sample with the following changes:

```patch
diff --git "a/samples/image/image.cpp" "b/samples/image/image.cpp"
index 9714b04de9..f07b99cf33 100644
--- "a/samples/image/image.cpp"
+++ "b/samples/image/image.cpp"
@@ -1208,18 +1208,27 @@ void MyFrame::OnAbout( wxCommandEvent &WXUNUSED(event) )
 
 wxString MyFrame::LoadUserImage(wxImage& image)
 {
-    wxString filename;
+    // try to find the directory with our ICO file
+    wxString filename = "../sample.ico";
+    if ( !wxFile::Exists( filename ) )
+        filename.insert(0, ".");
+    if ( !wxFile::Exists( filename ) )
+        filename.clear();
 
 #if wxUSE_FILEDLG
-    filename = wxLoadFileSelector("image", wxEmptyString);
+    if ( filename.empty() )
+        filename = wxLoadFileSelector("image", wxEmptyString);
     if ( !filename.empty() )
     {
-        if ( !image.LoadFile(filename) )
+        if ( !image.LoadFile(filename, wxBITMAP_TYPE_ICO , 3) )
         {
             wxLogError("Couldn't load image from '%s'.", filename);
 
             return wxEmptyString;
         }
+
+        if ( !image.HasAlpha() )
+            wxLogError("Image was loaded without alpha.");
     }
 #endif // wxUSE_FILEDLG
 

```

1. Start the image sample.
2. Click on 'Image' and 'Show any image...' or press `Ctrl + O` to load the fourth image, a 64x64 BMP with alpha, from the ICO file `sample.ico` in the `samples` directory.

### Platform and version information

- wxWidgets version  you use: master (b21642b72b4128f0b64ed7d79b4d320cbfc35497)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
Thanks for noticing and reporting this!

@paulcor Will you be able to look at this?

**Comment by paulcor** [comment]
I'll look into it.
