### ISSUE TITLE
Failed to load PNG image

### ISSUE THREAD

**Issue by coldcola233** [wxWidgets/wxWidgets#24951]
When I try to load an image file in png format with wxImage, it fails to load with the error "no image handler for type 15".
Here are the saved error log: 

* No image handler for type 15 defined.
* Failed to load image from file "test.png".

OS: windows11

build infomations:
* compiler: msvc (vc17)
* **using unicode character set** (I guess that might be the problem)
* C++ standard: c++14

project infomations:
* compiler: msvc (vc17)
* using unicode character set
* C++ standard: c++20

main code:
```wxImage img(wxT("test.png"),wxBITMAP_TYPE_PNG);```
***
I didn't try it in the case of a non-unicode character set.

**Comment by vadz** [comment]
Call `wxInitAllImageHandlers()`.

**Comment by coldcola233** [comment]
thanks
