### ISSUE TITLE
[MSW/MSYS2/Clang] Build error with recent clang compiler

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#24958]
I build wxWidgets and/or my application using:

- [x] CMake

wxWidgets version: git head
Platform: Windows 10, MSYS2, clang compiler (64bit), clang version 19.1.3

I have a CI which ensures that CodeLite is successfully built on various platforms, including builds on MSYS2 using clang (my go to compiler on Windows). I recently started getting errors from the CI (during the "build wxWidgets phase"), so I installed a fresh new MSYS2 environment, installed latest clang and cloned wxWidgets repository.

I got the same error:

```bash
In file included from <built-in>:1:
In file included from C:/msys64_2/home/eran/wxWidgets/build-release/libs/CMakeFiles/wxmono.dir/cmake_pch.hxx:5:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/wxprec.h:28:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/msw/private.h:17:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/log.h:27:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/string.h:37:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/strvararg.h:30:
In file included from C:/msys64_2/home/eran/wxWidgets/include/wx/unichar.h:16:
C:/msys64_2/clang64/include/c++/v1/string:2965:22: error: implicit instantiation of undefined template 'std::char_traits<unsigned int>'
 2965 |   return append(__s, traits_type::length(__s));
      |                      ^
C:/msys64_2/home/eran/wxWidgets/include/wx/ustring.h:350:36: note: in instantiation of member function 'std::basic_string<unsigned int>::append' requested
      here
  350 |         return (wxUString &) base->append( s );
      |                                    ^
C:/msys64_2/clang64/include/c++/v1/__fwd/string.h:23:29: note: template is declared here
   23 | struct _LIBCPP_TEMPLATE_VIS char_traits;
 
```

I also tried building using `makefile.gcc` using `clang` - same error

These are the steps I am using when running `cmake`:

```bash
cmake .. -G"MinGW Makefiles" \
  -DCMAKE_BUILD_TYPE=Release  \
  -DwxBUILD_DEBUG_LEVEL=0 \
  -DwxBUILD_MONOLITHIC=1 \
  -DwxBUILD_SAMPLES=SOME \
  -DCMAKE_INSTALL_PREFIX=$HOME/root
```

**Comment by eranif** [comment]
**NOTE**: same code, using `clang version 18.1.8` is working just fine

**Comment by eranif** [comment]
I did some reading on the topic and it seems this in [Clang 19 changes](https://libcxx.llvm.org/ReleaseNotes/19.html#deprecations-and-removals), this paragraph seems the culprit:

> The base template for std::char_traits has been removed in LLVM 19. If you are using std::char_traits with types other than char, wchar_t, char8_t, char16_t, char32_t or a custom character type for which you specialized std::char_traits, your code will stop working. The Standard does not mandate that a base template is provided, and such a base template is bound to be incorrect for some types, which could currently cause unexpected behavior while going undetected.

**Comment by eranif** [comment]
Applying this small fix on my local environment fixes the build issue:

```diff
diff --git a/include/wx/defs.h b/include/wx/defs.h
index 6ebb179dc2..729ea7239c 100644
--- a/include/wx/defs.h
+++ b/include/wx/defs.h
@@ -1024,7 +1024,8 @@ typedef double wxDouble;
     #define wxWCHAR_T_IS_WXCHAR32
     typedef wchar_t wxChar32;
 #else
-    typedef wxUint32 wxChar32;
+    #include <uchar.h>
+    typedef char32_t wxChar32;
 #endif
```

**Comment by vadz** [comment]
Yes, I've already run into this in some other projects and we need to either provide our own char traits or use one of the types for which they are guaranteed to be available, so the fix above looks good.

However I really wonder why do we have this `wxUString` at all. What has it ever been useful for and how is it preferable to just using `std::u32string` directly?

**Comment by vadz** [comment]
It would be nice to backport e37adaba307582749c77e398a3c8ec2c40e55c49 to 3.2, but it needs to be done for clang >= 19 only to avoid changing ABI for the other compilers.
