### ISSUE TITLE
"wx" in wx_GL_COMPAT_PROFILE enum constant is in lower case

### ISSUE THREAD

**Issue by Fat-Zer** [wxWidgets/wxWidgets#24964]
### Description

`wx_GL_COMPAT_PROFILE` in [`wx/glcanvas.h`](https://github.com/wxWidgets/wxWidgets/blame/5edd516add0051d6f51ec87b8001999b6c4035a6/include/wx/glcanvas.h#L56) is defined with lower case "wx". It breaks common conventions, and inconsistent with other enum definitions.

This is obviously a small typo and it's already part of the API for a long time, so if you decide not to fix it, feel free to close the issue.

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxGTK
- OS  and its version: Gentoo
  
  + GTK version: 3.24.41
  + Which GDK  backend is used: X11
  + Desktop environment : TDE
  + Current theme:  Keramik

**Comment by vadz** [comment]
Thanks for reporting this, I had completely failed to notice it back when adding it. I'm pretty sure it's a typo and not intentional, so I've created #24965 to fix this, please let me know if you see any problems with it.
