### ISSUE TITLE
wx 3.3 msw wxGetUserName problem

### ISSUE THREAD

**Issue by tstkr** [wxWidgets/wxWidgets#24976]
Hi,

wxGetUserName does not deliver the result like wx did in 3.2.6 for msw.
The Windows function NetUserGetInfo does not return a proper result.
Even the MS example code in the NetUserGetInfo documentation does not return a result. I assume if a computer name is not given, there won't be a result from that function.
Also the 3.2.6. code contains a more detailed error message than the 3.3 version which makes identification the problem less straightforward.

**Comment by tstkr** [comment]
Vadim,

The NetUserGetInfo call returns a status of 2221 (NERR_UserNotFound)
when given a nullptr servername. According to the doc it should use the
local computer then, but it does not find the user. This is what I meant
with 'proper result'.

I'm on Windows x64 10 22H2.

I think it is a problem with the Windows NetUserGetInfo call. Even the
sample code from the doc page does not produce a result for me with
empty servername...

Am 27/11/2024 um 16:41 schrieb VZ:

**Comment by vadz** [comment]
I wonder if calling `NetUserGetInfo()` with the local computer name instead of null could work better?

I guess the behaviour depends on the computer network settings (domain/workstation/...?), so it would be great if you could please test this.

**Comment by wh11204** [comment]
Netusergetinfo API works only if the user has Admin or group access, see [this](https://learn.microsoft.com/en-us/answers/questions/1162776/netusergetinfo-api-works-only-if-the-user-has-admi), although the error would be ERROR_ACCESS_DENIED.

**Comment by Blake-Madden** [comment]
Falling back to the computer name if there is no server is what we are currently doing. `NetGetAnyDCName` is called to get the domain controller; if that fails, then `nullptr` is passed to 
`NetUserGetInfo` instead, which will use the local computer name. That's what happens on my local machines.

This must have to something to do with permissions as @wh11204 said. I'll add a fallback to the old code I guess. There is a `GetUserNameEx` function, but that requires defining `SECURITY_WIN32` which I imagine will break something somewhere.

**Comment by Blake-Madden** [comment]
I think returning `false` from `bool wxGetUserName(wxChar* buf, int maxSize)` when the Net API fails is the real issue. This function will at least load the login name from `wxGetUserId` (which is what I used to get with the old implementation). I think I should return `true` if `wxGetUserId` was at least able to load something.

I would prefer that than going back to `GetProfileString()` as a fallback because Microsoft warns not to use that anymore https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprofilestringa

Any objections to that?

**Comment by vadz** [comment]
Thanks @Blake-Madden!

@tstkr Could you please check how does the proposed change in #24978 behave on your system?

**Comment by tstkr** [comment]
Vadim,

How do I get this fix? Is this already in a branch?
Sorry, I'm not experienced in git, we are still using svn.


Am 27/11/2024 um 22:07 schrieb VZ:

**Comment by Blake-Madden** [comment]
@tstkr go to file "src\msw\utils.cpp" and look for where `bool wxGetUserName(wxChar* buf, int maxSize)` is defined. Replace this function with the following and rebuild.

```
bool wxGetUserName(wxChar* buf, int maxSize)
{
    wxCHECK_MSG(buf && (maxSize > 0), false,
        "Empty buffer in wxGetUserName");

    if ( !wxGetUserId(buf, maxSize) )
        return false;

    /* This code is based on Microsoft Learn's ::NetUserGetInfo example code.
       Attempt to get the full user name; if any of this fails, we can still
       return true with the buffer at least filled with the login name
       from wxGetUserId().

       Note that there is a ::GetUserNameEx function, but that requires
       defining SECURITY_WIN32, which may have other side effects.
       Instead, use the NetAPI functions.*/

    const static wxDynamicLibrary netapi32("netapi32", wxDL_VERBATIM | wxDL_QUIET);
    if ( !netapi32.IsLoaded() )
    {
        wxLogTrace("utils", "Failed to load netapi32.dll");
        return true;
    }

    const static NetGetAnyDCName_t netGetAnyDCName =
        reinterpret_cast<NetGetAnyDCName_t>(netapi32.GetSymbol("NetGetAnyDCName"));
    const static NetUserGetInfo_t netUserGetInfo =
        reinterpret_cast<NetUserGetInfo_t>(netapi32.GetSymbol("NetUserGetInfo"));
    const static NetApiBufferFree_t netApiBufferFree =
        reinterpret_cast<NetApiBufferFree_t>(netapi32.GetSymbol("NetApiBufferFree"));

    if ( netGetAnyDCName == nullptr ||
         netUserGetInfo == nullptr ||
         netApiBufferFree == nullptr )
    {
        return true;
    }

    LPBYTE computerName{ nullptr };
    USER_INFO_2* ui2{ nullptr };

    // Get the domain controller for any domain.
    if ( netGetAnyDCName(nullptr, nullptr, &computerName) != NERR_Success )
    {
        // May not be networked, so use the local machine.
        computerName = nullptr;
    }
    // ::NetGetAnyDCName calls ::NetApiBufferAlloc to fill the
    // domain controller name, so need to free that upon exit.
    auto dcBufferFree = std::unique_ptr<BYTE, void(*)(LPBYTE)>
        {
        computerName,
        [](LPBYTE computerName)
            {
                if ( computerName != nullptr )
                    netApiBufferFree(computerName);
            }
        };

    // Look up the user on the DC.
    const NET_API_STATUS status = netUserGetInfo((LPWSTR)computerName,
        (LPWSTR)buf,
        2, // level - we want USER_INFO_2
        (LPBYTE*)&ui2);
    // ::NetUserGetInfo calls ::NetApiBufferAlloc to create the
    // USER_INFO_2 structure, so need to free that upon exit.
    auto uiBufferFree = std::unique_ptr<USER_INFO_2, void(*)(USER_INFO_2*)>
        {
        ui2,
        [](USER_INFO_2* ui2)
            {
                if ( ui2 != nullptr )
                    netApiBufferFree(ui2);
            }
        };

    if ( status != NERR_Success )
    {
        wxLogWarning(_("Failed to retrieve full user information: %s"),
                     wxSysErrorMsgStr());
        return true;
    }

    if ( ui2 != nullptr &&
         ui2->usri2_full_name != nullptr )
    {
        wxString fullUserName(ui2->usri2_full_name);
        if ( fullUserName.empty() )
        {
            return true;
        }
        // In the case of full name being in the format of "[LAST_NAME], [FIRST_NAME]",
        // reformat it to a more readable "[FIRST_NAME] [LAST_NAME]".
        const size_t commaPosition = fullUserName.find(", ");
        if ( commaPosition != wxString::npos )
            {
            const wxString firstName = fullUserName.substr(commaPosition + 2);
            fullUserName.erase(commaPosition);
            fullUserName.insert(0, firstName + ' ');
            }
        wxStrlcpy(buf, fullUserName.t_str(), maxSize);
    }

    return true;
}
```

**Comment by tstkr** [comment]
Well, this change fixes the fact, that there is a name - actually the id
of the user - is returned, but there is still an error reported which we
show to the user. He will be confused...

Am 28/11/2024 um 11:00 schrieb Blake-Madden:

**Comment by Blake-Madden** [comment]
Good point. I just pushed another update to fix that.

Basically, replace this:

```
wxLogWarning(_("Failed to retrieve full user information: %s"),
                     wxSysErrorMsgStr());
```

with this:

```
wxLogTrace("utils", _("Failed to retrieve full user information: %s"),
             wxSysErrorMsgStr());
```

You should only get that log message if tracing "utils", which would not be on by default.

**Comment by PBfordev** [comment]
> You should only get that log message if tracing "utils", which would not be on by default.

AFAIK, `wxLogTrace()` on Windows uses `::OutputDebugString()`, so the end user will never see the message, even in Debug builds. Which means the message should probably not be marked for translation.

BTW, the docs for `::NetUserGetInfo()` does not mention that the function sets the last-error code (nor the example code uses it): Does `wxSysErrorMsgStr()` return a valid information here?

BTW2, just curious: The `::Net*()` functions are available since Windows 2k/XP. why are they loaded dynamically?

**Comment by Blake-Madden** [comment]
> AFAIK, `wxLogTrace()` on Windows uses `::OutputDebugString()`, so the end user will never see the message, even in Debug builds. Which means the message should probably not be marked for translation.
> 
> BTW, the docs for `::NetUserGetInfo()` does not mention that the function sets the last-error code (nor the example code uses it): Does `wxSysErrorMsgStr()` return a valid information here?

Just applied your suggestions, thanks.

> BTW2, just curious: The `::Net*()` functions are available since Windows 2k/XP. why are they loaded dynamically?

Using these functions directly would have required adding another lib dependency. Vadim suggested dynamically calling them this way to avoid that.

**Comment by PBfordev** [comment]
> > BTW2, just curious: The `::Net*()` functions are available since Windows 2k/XP. why are they loaded dynamically?
> 
> Using these functions directly would have required adding another lib dependency. 

Thanks, I did not realize this.
