### ISSUE TITLE
[Lexilla PR] How to submit small PR for Lexilla?

### ISSUE THREAD

**Issue by eranif** [wxWidgets/wxWidgets#24985]
I am not sure if anyone is monitoring the `wxWidgets/lexilla` repo, but I have opened there a small PR which fixes 2 annoyances
with the `LexerErrorList`.

https://github.com/wxWidgets/lexilla/pull/3

Thanks,
Eran

**Comment by vadz** [comment]
I don't think we need to keep this open, the other PR is enough.
