### ISSUE TITLE
The Counterintuitive Behavior of wxGenericStaticBitmap with ScaleMode Scale_AspectFit

### ISSUE THREAD

**Issue by StingKo** [wxWidgets/wxWidgets#25029]
When setting the ScaleMode of wxGenericStaticBitmap to Scale_AspectFit, resizing the control only affects the image drawn inside. However, if the control is reduced in size along one axis, the actual size of the control along the other axis remains fixed at the bitmap’s original dimensions, rather than shrinking proportionally. This behavior feels counterintuitive, as the control’s size in the other direction should adjust dynamically to match the scaled image.

**Comment by vadz** [comment]
The controls never adjust their size on their own, the size given to the control is determined by the sizer containing it and the scale mode can only affect what happens inside the rectangle allocated to the control.

So I don't see anything counterintuitive here.

**Comment by vadz** [comment]
I'm not sure what is the intention here: if you use `wxSHAPED`, you intend the bitmap to keep the same ratio, so why use `Scale_AspectXXX` and not `Scale_Fill`?
