### ISSUE TITLE
wxWidgets libraries not found?

### ISSUE THREAD

**Issue by FlashGamingTune** [wxWidgets/wxWidgets#25031]
### Getting this error,

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		wxWidgets libraries not found under "H:\Saad\Liberary\wxWidgets-3.1.5\lib\vc{,143,14x}_x64_{lib,dll}".	FirstGUI	H:\Saad\Liberary\wxWidgets-3.1.5\wxwidgets.props	117		
```

**Even after adding `property sheet` and changing the `SubSystem` settings to `Windows` .**

**Comment by vadz** [comment]
See [my reply](https://github.com/wxWidgets/wxWidgets/issues/22560#issuecomment-2564731235) to your comment in the other issue.
