### ISSUE TITLE
wxColourEnumerator

### ISSUE THREAD

**Issue by wxtrac** [wxWidgets/wxWidgets#9264]
*Issue migrated from trac ticket # 9264*

**priority:** low

#### 2004-06-09 20:41:52: wyo created the issue

___
Currently it's not possible to retrieve the colours
from the wxColourDatabase. It might be a good idea to
have a wxColourEnumerator class quiet similar to the
wxFontEnumerator class.

**Comment by vadz** [comment]
As discussed in [this thread](https://groups.google.com/g/wx-dev/c/nPhYYOLOL9A), it would be useful to add `GetAllNames()` method and this can be done much simpler than adding a whole new class.

Also, this is not related to `wxFontEnumerator` at all.
